### ISSUE TITLE
Remove the statement "For the first release, no simulated Monte Carlo sets are provided"

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1006]
Last sentence in the research introduction page:
http://opendatadev.cern.ch/research/CMS
and last sentence in the CMS box in
http://opendatadev.cern.ch/research

**Comment by tiborsimko** [comment]
Note that the text was amended by @RaoOfPhysics in a57573043c18db18d130887d1835b1e6d3955ad9, the QA shows the new text already, but it still needs to be changed on DEV. I'll take care of updating DEV.

**Comment by tiborsimko** [comment]
Done.
