### ISSUE TITLE
"Things to Remember" not expanding in 2011 Physics Objects

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1010]
Tested on Firefox and Chromium:

![physicsobjectsbug2](https://cloud.githubusercontent.com/assets/7623019/14011619/e132982e-f197-11e5-96bb-1dd9ea2f6946.gif)

**Comment by RaoOfPhysics** [comment]
If @pamfilos or @tiborsimko tell me what code I need to change on `about_CMS_physics_objects_2011.html`, I can do so, since I'm already working on the text here. It would also be preferable so that any chances you implement don't break my work. :)

**Comment by pamfilos** [comment]
@RaoOfPhysics you need to update the anchors of the "Things to remember", since parts of 2010 and 2011 still have the same "id" and confuses the library

For example in 'about_CMS_physics_objects_2010.html' (lines 69-70) change "data-target" and the respective "id" to have a unique name:

```
      <h2 data-toggle="collapse" data-target="#rm-met"  class="title collapsed">MET — Things to remember<span class="fa fa-chevron-down"></span><span class="fa fa-chevron-up"></span></h2>
      <div id="rm-met" class="collapse">
```

to

```
      <h2 data-toggle="collapse" data-target="#rm-met2010"  class="title collapsed">MET — Things to remember<span class="fa fa-chevron-down"></span><span class="fa fa-chevron-up"></span></h2>
      <div id="rm-met2010" class="collapse">
```

**Comment by RaoOfPhysics** [comment]
As discussed on Gitter, please go ahead, @pamfilos. :) Thanks!
