### ISSUE TITLE
Mention pile-up for the simulated data

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1017]
We could mention the pile-up in "How were these data generated"
Probably a generic statement after the processing step where the pile-up events were
added would be best. 

Note that this was mentioned in
https://github.com/cernopendata/opendata.cern.ch/issues/820#issuecomment-157777437
but we probably do not need a separate field for it.

**Comment by tiborsimko** [comment]
We already have the pileup information in the record, living in the field 770. But we don't display it.

- [ ] check metadata model (`opendata.cfg`)
- [ ] amend display templates

**Comment by katilp** [comment]
A similar page than that requested in #864 could be created and linked from each MC record,
with the text after the HLT configuration file:
"To make these simulated data comparable with the collision data, pile-up events are added to the simulated event at the HLT step"
"pile-up events" can then link to this new information page which we can fill from a CMS twiki

**Comment by katilp** [comment]
The information that should go in this page is now in https://twiki.cern.ch/twiki/bin/view/CMSPublic/PublicPileupInfo
@RaoOfPhysics can you put that information on the page that @pamfilos will create.
That would then be linked from all MC records.
