### ISSUE TITLE
Year tabs for CMS validation utilities do not work

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1018]
In http://opendatadev.cern.ch/research/CMS view the year tabs under "CMS validation utilities" do not work.

Both give "Your search did not match any records. Please try again."

**Comment by tiborsimko** [comment]
Now that the run period information has been added to the records, the links work, so I'm closing this issue.  (although we may want to check whether all record have it present, otherwise they would not appear...)
