### ISSUE TITLE
Communication/Outreach for next release

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#1035]
- Release in week of April 18th?
- CERN comms [Achintya and possibly Sünje]: social media, whatelse?
- CMS article [Achintya]: among others, i.e. Achim's/CMS reproducibility example and new MC samples in release
- Symmetry [Sünje]: contact Katie, the Editor in Chief
- AMA [Achintya, Sünje]: understand who wants to join (and who does not want to), find a date (10 days after the release?; Achintya leaves on April 25th)
- Video [Sünje, Achintya]: muse and understand who can do it
- ~~PhD comic [Achintya]~~ Sorry, this won't happen. :( No time to initiate contact etc. Apologies. (– @RaoOfPhysics)

**Comment by tiborsimko** [comment]
We may want to include Melissa for the IT outreach.  Perhaps a  Science Node piece?

**Comment by RaoOfPhysics** [comment]
@suenjedt, @tiborsimko: I forget who was supposed to take action on the Science Node piece. Was it me? :(

**Comment by suenjedt** [comment]
I thought it was Tibor. Happy to chime in though.

**Comment by tiborsimko** [comment]
@RaoOfPhysics I contacted Melissa who replied that Andrew was already in the loop with you (e.g. via your comm meeting), so I did not do anything particular afterwards...

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Oh! Ok, I will write to Andrew, then.
