### ISSUE TITLE
Add Issues and limitations to all config files

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1038]
We could add the following statement in all configuration files

"This file describes the exact setup for the CMS software executable, which was used in this step of data processing. It is provided only for information purposes. Whereas all necessary components (input data, condition data, software version) required to analyse the public primary datasets are provided in this portal, they are not necessarily available to reproduce the data processing step described here."

This could go under a new Issues & Limitations, or be part of the disclaimer. @tiborsimko Which would be better?

@RaoOfPhysics Can you help in formulating this better?

**Comment by RaoOfPhysics** [comment]
@katilp, how about:

> This file describes the exact setup for the CMS software executable that was used in this step of data processing. It is provided only for your information. Although all the necessary components required to analyse the public primary datasets &mdash; such as input data, condition data, software version &mdash; are provided on this portal, they will not necessarily help reproduce the data-processing step described here.

Unless I misunderstood the last clause…

**Comment by katilp** [comment]
Nice, thanks!
The point of the last clause is that we do not provide all necessary versions of condition data and software (and the various intermediate RAW, SIM, RECO.... files). I.e. in a record referring to one of these condition file we do indicate what are the necessary condition data (Global tag) and software (CMSSW)  but we do not give them:

<img width="764" alt="mc" src="https://cloud.githubusercontent.com/assets/5859918/14426706/02639d9c-fff1-11e5-8c4b-2ca806e77501.PNG">

So the message is that you can't run this config , because these pieces are not here.
But I want to mention that we provide everything for the analysis of the open data.

**Comment by RaoOfPhysics** [comment]
Ok, so I think based on that clarification the edit I provided makes sense, right?

**Comment by katilp** [comment]
right... to avoid the impression that one could possibly reproduce this with the open data (which is not the case), I would not say "will not necessarily help reproduce", but maybe something like: are not exact versions needed to...
The "exact versions" refer then to condition data and software, which are versioned, for the input data this is not about the versions but rather the type of data...

**Comment by RaoOfPhysics** [comment]
How about:

> Although all the components required to analyse the public primary datasets — such as input data, condition data, software version — are provided on this portal, components needed to reproduce the data processing-step described here are not necessarily available.

?

**Comment by katilp** [comment]
Perfect! Thanks!

**Comment by tiborsimko** [comment]
> data processing-step

data-processing step

**Comment by tiborsimko** [comment]
FWIW with @katilp we reformulated the text to read:

```
    <datafield tag="556" ind1=" " ind2=" ">
      <subfield code="a"><![CDATA[ This file describes the exact setup for the
      CMS software executable which was used in a data-processing step. It is
      provided only <i>for information purposes</i>. Although all the components
      required to <i>analyse</i> the public primary datasets - such as
      corresponding input data, condition data, software version - are provided
      on this portal, it is not necessarily possible to <i>reproduce</i> all the
      described data-processing steps. ]]></subfield>
    </datafield>
```

trying to be clearer to casual random visitors...
