### ISSUE TITLE
Fix language for di-muon example's record

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1063]
The English needs a tiny bit of clean-up. Assigning to myself.

- [x] Fix language on record 560
    - [x] Also add appropriate caveats as mentioned in #969, i.e.: "The example record should also include this caveat that the code can be run on 2011 data but hasn't been optimised for it."
- [x] Fix language on record 460

**Comment by tiborsimko** [comment]
Here is how to find out where a certain record (e.g. record ID 560) is located in sources:

```
$ git grep '"001".*>560<'
invenio_opendata/testsuite/data/cms/cms-tools-dimuon-spectrum-2010.xml:    <controlfield tag="001">560</controlfield>
```

**Comment by katilp** [comment]
@RaoOfPhysics note that the same text appears also in http://opendatadev.cern.ch/record/460
