### ISSUE TITLE
records template should be updated according to the additional fields on opendata.cfg

### ISSUE THREAD

**Issue by AnxhelaDani** [cernopendata/opendata.cern.ch#1094]
- `520__u` & `520__w`
- `538__u`
- `770__i`
- `786__a` & `786__w`

**Comment by tiborsimko** [comment]
It would be good to provide more details, e.g. which field should be displayed where on the detailed record page and for which collections...

**Comment by AnxhelaDani** [comment]
* `520__u` should be displayed on record 56->Validation report for CERN VM images, after the text of `520__a` - collection:CMS Open Data Instructions
* `520__w` should be displayed on both 2011 condition data records after the text of `520__a` - collection:CMS Condition Data
* According to https://github.com/cernopendata/opendata.cern.ch/issues/1017#issuecomment-208948604 the text of `770__i` should be displayed after the HLT configuration file (which is in `567__a`) in each simulated datasets - collection:CMS Simulated Datasets

Sorry @tiborsimko, hope these help :)

**Comment by tiborsimko** [comment]
(example record for issue number two: 1802)

**Comment by tiborsimko** [comment]
(example record for issue number four: 1326)

**Comment by tiborsimko** [comment]
(example record for issue number five: 3800)

**Comment by tiborsimko** [comment]
Closed by PR #1220.
