### ISSUE TITLE
File name error in stand-alone event display

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#1109]
There is always something.

If one tries to load the first file from 2011A "BTau" then 404 error. The file should actually be "BTag" (record 614). Others are fine though so not catastrophic.

**Comment by tiborsimko** [comment]
@tpmccauley Can you please make a PR?

**Comment by tpmccauley** [comment]
This is fixed in COD3 for iSpy WebGL https://github.com/cms-outreach/ispy-webgl/blob/cod3/data/igfiles.json#L68
