### ISSUE TITLE
CMS: update 2011 VM image to `CMS-Open-Data-1.2.0.ova`

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1113]
Update CMS VM 2011 image to the latest `CMS-Open-Data-1.2.0.ova` version sent by Adam.

**Comment by katilp** [comment]
Was it rc2 earlier?
________________________________________

**Comment by tiborsimko** [comment]
> Was it rc2 earlier?

It was `rc3` earlier.  Adam has produced a new OVA using the latest CernVM release that includes the fix for that logwatch issue.  I tested the new OVA with the demo analyser example and everything seems good.
