### ISSUE TITLE
Correction to record 560

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1116]
Please replace the file demoanalyzer_cfg.py in http://opendata.cern.ch/record/560 with 
/afs/desy.de/public/CMS/opendata/MUO-10-004demo/demoanalyzer_cfg.py
 
Change Demoanalyzer.cc to DemoAnalyzer.cc
(twice) in the text of the user instructions. These two changes go also to the record 460 (but not the file update).

@tiborsimko @suenjedt the original one is buggy, so should not be displayed.
Can we simply replace this?

**Comment by suenjedt** [comment]
Had missed this one. Given it is a replacement to get rid off a bug. It should simply be replaced, I think.

**Comment by katilp** [comment]
This is important to AMA, can it be done before?

**Comment by AnxhelaDani** [comment]
@tiborsimko I change the text on the two records, you have only to replace the file ```demoanalyzer_cfg.py```
