### ISSUE TITLE
Add records for 2011 csv's to the portal

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1139]
we would need records for the files from
https://github.com/tpmccauley/cmsopendata-jupyter/tree/master/data
on the portal.
@tpmccauley Is that Ok?
That would be 8 records similar in structure to http://opendata.cern.ch/record/301
but maybe without json and ig ?

**Comment by tpmccauley** [comment]
@katilp in-principle I suppose yes. However, I wouldn't consider these files as final and therefore "freeze-able". When finished I was planning on adding event display files as well.

**Comment by tiborsimko** [comment]
@tpmccauley Assigning this issue to you, please reply back when the files are final...

**Comment by katilp** [comment]
@tpmccauley It would be nice to have the files, in particular those in https://github.com/cmsopendata-finland/kurssimateriaali/tree/master/Teoriaa-ja-harjoituksia/data asap on the portal
You probably have them elsewhere as well.
For the content, the important thing is that the columns are briefly described - we can probably accommodate other versions in the same records if need arises

**Comment by tpmccauley** [comment]
I have some new csv files (from 2011 with different selections) and more jupyter code which I haven't put in github (yet). I would consider these more "final". How about this week I update the notebooks in github along with the new csv files and we see if the information there is enough to create a sufficiently detailed record for the portal?
@tiborsimko what is new (if anything) about adding a record in invenio?

**Comment by katilp** [comment]
OK, sounds great! Can also you give the link to the new code to @prikkila as he is looking at it now for a university exercise.

**Comment by katilp** [comment]
@tpmccauley Any news on this? It would be really useful to have them on portal for different training courses (e.g. HST and all). I'm adding fast lane but remove if you think you need more time

**Comment by tpmccauley** [comment]
Will have it this week. Sorry for delay.

**Comment by katilp** [comment]
@tiborsimko Will these be on the portal for next week's HST? Thanks!

**Comment by tiborsimko** [comment]
@katilp Deployed as http://opendata.cern.ch/record/545
