### ISSUE TITLE
Updates to the trigger descriptions of the 2010 datasets

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1183]
Following updates to the 2010 datasets (these texts should replace the current text under "How were these data selected?":
## ZeroBias dataset:  (http://opendata.cern.ch/record/13)

Since the actual ZeroBias triggers were moved to the MinimumBias dataset,
the remaining events do not contain useful information and this sample
should not be used.
## MinimumBias dataset: (http://opendata.cern.ch/record/8)

There are four categories of triggers in the MinimumBias dataset:

1) ~60% Minimum-bias-like triggers (some tagger requirements
         or random triggers)
             HLT_L1_BPTX_MinusOnly
             HLT_L1_BPTX_PlusOnly
             HLT_L1_BPTX
             HLT_L1Tech_BSC_HighMultiplicity
             HLT_ZeroBias
             HLT_Random

2) ~10% large track multiplicity triggers (three subcategories:
         >75, 85, 100 tracks) for "ridge" studies
             HLT_PixelTracks_Multiplicity100
             HLT_PixelTracks_Multiplicity85
             HLT_PixelTracks_Multiplicity70

3) ~28% triggers for exotic stopped High mass Stable
         Charged Particles (out of time, out of beam(?))
             HLT_StoppedHSCP35_v3
             HLT_StoppedHSCP20_v3
             HLT_StoppedHSCP

4) ~2%, a technical "muon" (RPC based) trigger
             HLT_L1Tech_RPC_TTU_RBst1_collisions
## Commissioning dataset: (http://opendata.cern.ch/record/2)

There are four categories of triggers in the Commissioning dataset:

1) ~30% "almost" Minimum-bias-like trigger (some tagger requirements)
             HLT_L1_BptxXOR_BscMinBiasOR

2) ~10% multi-vertex triggers with or without energy threshold (biased)
             HLT_MultiVertex6
             HLT_MultiVertex8_L1ETT60

3) ~30% isolated track triggers with some L1 jet (e.g. for taus)
             HLT_IsoTrackHB_v2
             HLT_IsoTrackHB
             HLT_IsoTrackHE_v3
             HLT_IsoTrackHE_v2
             HLT_IsoTrackHE

4) ~20% technical "muon" (DT or CSC based) triggers
             HLT_Activity_CSC
             HLT_Activity_DT
             HLT_Activity_DT_Tuned
## Mu dataset: (record http://opendata.cern.ch/record/14)

There are four categories of triggers in the Mu dataset 
(with significant overlaps):

1) ~70% inclusive single muon triggers with varying trigger pt
         threshold 3,5,7,9,11,13,15,17,19,21 GeV
         plus a few with loosened quality cuts

2) ~20% isolated single muon triggers with varying trigger pt
         threshold 9,11,13,15,17 GeV

3) ~10% inclusive dimuon triggers with varying trigger pt
         threshold 3,5 GeV
         plus one Z->mumu trigger with loosened quality cuts

4) ~20% combinations of muon triggers with various pt
         thresholds 3,5,7,8,9,11 GeV
         with some EM/e/gamma or hadronic/jet energy deposit with
         thresholds 6-100 GeV
## MuOnia dataset:   (http://opendata.cern.ch/record/10) 

(the noncontinuous numbering indicates the conceptual overlap with Mu)

There are two categories of triggers in the MuOnia dataset,
which overlaps noticeably with the Mu dataset, even though the trigger 
selections have no formal overlap:

3) ~30% inclusive dimuon triggers with no explicit trigger pt threshold
         or loosened requirements on 2nd muon

5) ~70% J/psi or quarkonium (dimuon) triggers with no or very loose pt
         thresholds and cuts on dimuon mass in range 1.5-15 GeV
## MuMonitor dataset: (http://opendata.cern.ch/record/9)

There are three categories of triggers in the MuMonitoring dataset,
which strongly overlaps with the Mu and MuOnia datasets, including formal 
overlaps of the trigger selection.
These categories are also heavily overlapping with each other.
The dataset provides some additional acceptance for low pt and/or
lower quality muons.

1) ~70% inclusive single muon triggers with varying trigger pt
         threshold 0,3,5,7 GeV
         plus several with loosened quality cuts

3) ~50% inclusive dimuon triggers with no explicit trigger pt threshold
         or loosened requirements on 2nd muon

5)  ~5% one J/psi trigger with no pt threshold

In case of questions or clarifications, you can ask Achim.

**Comment by katilp** [comment]
The dataset records have not been updated with these descriptions so the issue is reopened.

**Comment by ArtemisLav** [comment]
I checked the 2010 primary datasets .xml and all the changes have already been incorporated there (see Anxhela's commits). 

@tiborsimko , is there anything else to be done here or can these records be updated?

**Comment by tiborsimko** [comment]
@ArtemisLav Yes, the changes were merged, but not deployed yet. I'll take care of this.

**Comment by tiborsimko** [comment]
The changes are now fully dpeloyed after fixing some ALICE issues. However, the display of records seems broken, for example:

- http://opendata.cern.ch/record/14

I''l fit it.
