### ISSUE TITLE
Open Data on Invenio 3

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#1187]
- first prototype available by @jirikuncar 
- approach for next steps: detangle design, collections/content management and Invenio modules so that development/updates on any of the three can be done without inconvenience for the others. 
- start with the "raw" Invenio 3, add specifications for design overlay and IA, collections, and anything specific that might be needed (i.e. Tom's visuals) 
- important to note the new requirements, e.g. specific or easier entry points for teachers/education materials (see #1172), or different collection types for non LHC materials (e.g. machine learning datasets)

To do's: 
- @daslerr to collect and manage requirements in terms of content, collections and IA. What kind of collections are needed, What extra pages are needed, what kind of entry points are crucial. 
- @eamonnmag to propose new design/UI (partially in collab with @daslerr) 
- @jirikuncar to do or delegate the I3 backend development

Plan: 
Work individually, then @daslerr to arrange meeting with @eamonnmag and @jirikuncar (or use Friday triaging) to get outcomes together and implemented.

**Comment by jirikuncar** [comment]
**Packages**
- `cernopendata` - minimal auto-generated overlay from `inveniomanage instance create`
- `cernopendata-theme` - package providing Jinja2 templates, Icons, etc.
- `cernopendata-experiments` - endpoints, templates and additional resources, ...
- `cernopendata-<foo>` ...

We can keep `opendata.cern.ch` as our meta-package with e.g. git subdirectories to all our used packages.

**Comment by suenjedt** [comment]
An update from meeting with @katilp:
CMS is preparing for the next big data release (see for example #1188). This needs to be taken into consideration for the timing of the migration and planning of CODP3. Storage is available from Jan 2017 on. 
@daslerr we need to consider this in particular for the data model questions (MARC/JSON). Current thinking is to finalize data model now and do data release with CODP3 and JSON. Need to have a CODP "summit" with everyone to decide on roadmap (once you gathered the requirements).

**Comment by tiborsimko** [comment]
There will be indeed four distinct "work packages":
- COD3 data model
- COD3 UX/UI
- COD3 overlay
- CMS Run2012 data release

plus devops tasks, plus old data migration tasks. These could be tackled in parallel.

Here is our July 2016 roadmap for COD3, slightly updated regarding born-after UX/UI sprint:

- https://github.com/cernopendata/opendata.cern.ch/wiki/Roadmap

**Comment by tiborsimko** [comment]
> Packages

I fully agree that it'll be good to split at least the "-data" package apart, containing all the fixtures. (Currently these dominate the repository.) I'm less sure about introducing experiment-specific templates, perhaps it's enough to have them live inside the main repository, or introduce one global "-pages" for all kinds of static pages?  (We'll see better depending on how the new IA might change the picture.)

@jirikuncar It'll be good if you can prepare the initial commit for the nascent COD3 overlay that you have in your personal space, using the current data model and the current IA, which will permit to advance with the "COD3 overlay" work package. We can then use this work to experiment with the new data model and the new IA later, as they are becoming ready. 

Perhaps you can create `cernopendata` (or `opendatacernch`?) for now, containing almost everything, with only "-data" being separated apart, and we can see about separating other "less clear" candidates later?

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko I agree to this structure. As we discussed lets add everything except the ```data``` packages to the ```cernopendata``` repository.

**Comment by suenjedt** [comment]
I am closing this and the milestone as we take care of all of this work in other issues/milestones/repos...
