### ISSUE TITLE
2012 datasets - initial considerations

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1188]
Notes for  CMS 2012 data:

Collision data:
`dataset=/*/*2012*22Jan2013*/AOD` (total of 1.1 PB out of which 510 TB Parked - see https://cds.cern.ch/record/1480607/files/DP2012_022.pdf and also https://profmattstrassler.com/articles-and-posts/lhcposts/triggering-advances-in-2012/data-parking-at-cms/ :smiley:  )
A: from the start to May 6: 45 TB (including 2 TB Parked)
B: from May 12 to June 18: 230 TB (95 TB Parked)
C: from July 1 to September 27: 354 TB (155 TB Parked)
D: from September 28 to December 5: 477 TB (260 Parked)

NB (dates approximate, some double-counting in data volumes because of special HZZ, TOPElePlusJets and TOPMuPlusJets processings with 42.9 TB)

![int_lumi_per_day_cumulative_pp_2012](https://cloud.githubusercontent.com/assets/5859918/18252286/20e8f80a-738e-11e6-992a-fb68e073b079.png)

TBD:
- [x] Check if it is justified not to include Parked datasets
- [x] Decide whether release A+B+C (appr 14fb-1) or B+C (appr 13fb-1) or C+D (appr 16 fb-1): all these combinations less than 0.5 PB (without Parked)

MC
`dataset=/*/*Summer12_DR53X*V7*/AODSIM` (total of 2 PB) or
`dataset=/*/*Summer12_DR53X*V19*/AODSIM` (total of 1 PB)

TBD:
- [x] check with the experts if these are overlapping:

No, the legacy campaign for the 2012 MC (called Summer12DR53X) is the one using the GT: START53_V19 (757.6 TB)

 In that campaign there were also some additional special production (mostly run-dependent) using other GTs: 
- START53_V19F: BPH run-dependent DIGI-RECO in 5.3. (162.8 TB)
- START53_V19E : digi-reco in 5.3 with specific Muon alignement for EXO (1.3 TB)
- START53_V7N : run dependent for h2gg (254.6 TB)

Open question for V19D (38 TB)

(From Gianluca Germinara and ppd)
- [x] check if there is any obvious rule to decide what to leave out
- [x] check with the 2011 "algorithm" how to divide these in categories
- [x] check with @tiborsimko that all 2011 procedures scale with the increased number of datasets

**Comment by katilp** [comment]
Include Parked data to the release

**Comment by RaoOfPhysics** [comment]
@katilp: I'm probably missing something, but I thought I should confirm anyway that you mean 0.5 TB for the second TBD and not 0.5 PB.

**Comment by katilp** [comment]
@RaoOfPhysics: good point, thanks; I mean 0.5 PB

**Comment by katilp** [comment]
Recapitulating numbers for the resource request:

Data:
2012 data taking was divided in four runs: RunA, RunB, RunC and RunD with a total of 1.1 PB out of which a part will be released in 2017. The released data will be at maximum 831 TB - in case of releasing RunC + RunD - at minimum 477 TB - if only RunD is released , other combinations are possible, and to be defined considering the best possible compatibility with the MC samples. In long-term, CMS may consider releasing the full data, if so decided by the collaboration board, but this will not happen in 2017.

MC:
The legacy campaign for the 2012 MC (called Summer12DR53X) is the one using the GT: START53_V19 and sums up to 757.6 TB. In addition, some special productions should be kept (run dependent production for B physics with 162.8 TB, special alignment for muons with 1.3 TB and Higgs to gg with 254.6 TB), summing up to a total of 1.2 PB.

CMS therefore needs for the long-term preservation and open access of these samples 2 PB of disk space in eospublic at CERN, to be served through xrootd (or direct download) from opendata.cern.ch.

**Comment by katilp** [comment]
Storage space for 2 PB OK for 2017, so we can proceed 😃

**Comment by katilp** [comment]
Listing of 
https://cmsweb.cern.ch/das/request?view=plain&limit=3000&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12_DR53X*V19*%2FAODSIM

[Summer12_DR53X-PU_S10_START52_V19_listing.pdf](https://github.com/cernopendata/opendata.cern.ch/files/497911/Summer12_DR53X-PU_S10_START52_V19_listing.pdf)

**Comment by katilp** [comment]
For the Run periods to be released, a good choice could be RunB + RunC.
It would amount to 584 TB, and include most of the data that were included in the Higgs discovery analysis. To be discussed with the CMS physics coordination.

**Comment by katilp** [comment]
The release date will be decided together with the CMS physics coordination making sure that all CMS 8 TeV key analyses will have been published before.

**Comment by katilp** [comment]
NB: no DoubleMu in 22Jan2013 reprocessing, checking this with Higgs POG, Muon PAG and PPD. Earlier reprocessing available:
RunB: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleMu%2F*2012B*%2FAOD
RunC:   https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleMu%2F*2012C*%2FAOD
