### ISSUE TITLE
CMS 2012 collision data - physics menus

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1189]
Extract the physics menus from the CMS confdb data base for 2012 data taking as indicated in
http://fwyzard.web.cern.ch/fwyzard/hlt/2012/summary : 
Similar procedure as in #832 
Then make sure that all CMSSW version have tags 
- Physics menus

CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.4/HLT/V5                                        (runs 190456 - 190465)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.4/HLT/V7                                           (runs 190482 - 190539)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.5/HLT/V3                                           (runs 190591 - 190595)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.6/HLT/V5                                           (runs 190645 - 190659)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.7/HLT/V1                                           (runs 190661 - 190679)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.8/HLT/V1                                           (runs 190688 - 190738)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.10/HLT/V1                                          (run 190782)
CMSSW_5_2_3_patch1_ONLINE        /cdaq/physics/Run2012/5e33/v4.11/HLT/V2                                          (runs 190895 - 190906)
CMSSW_5_2_3_patch4_ONLINE        /cdaq/physics/Run2012/5e33/v4.12/HLT/V1                                          (runs 190945 - 190949)
CMSSW_5_2_3_patch4_ONLINE        /cdaq/physics/Run2012/5e33/v4.13/HLT/V1                                          (runs 191043 - 191090)
CMSSW_5_2_3_patch4_ONLINE        /cdaq/physics/Run2012/5e33/v4.14/HLT/V1                                          (runs 191201 - 191411)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V2                                          (runs 191691 - 191726)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V3                                          (runs 191800 - 191859)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V14                                         (runs 193093 - 193124)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V15                                         (runs 193192 - 193207)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V18                                         (runs 193334 - 193336)
CMSSW_5_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2012/5e33/v4.16/HLT/V21                                         (runs 193541 - 193621)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.1/HLT/V11                                          (runs 193834 - 193836)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.1/HLT/V12                                          (runs 193998 - 194210)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.1/HLT/V13                                          (runs 194223 - 194225)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.2/HLT/V2                                           (runs 194270 - 194317)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.2/HLT/V3                                           (runs 194424 - 194712)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.3/HLT/V1                                           (runs 194735 - 194778)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.3/HLT/V2                                           (runs 194788 - 194825)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.3/HLT/V3                                           (runs 194896 - 195970)
CMSSW_5_2_4_onlpatch4_ONLINE     /cdaq/physics/Run2012/7e33/v2.3/HLT/V3                                           (runs 196019 - 196027)
CMSSW_5_2_4_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v2.4/HLT/V1                                           (runs 195868 - 195950)
CMSSW_5_2_4_onlpatch4_ONLINE     /cdaq/physics/Run2012/7e33/v2.5/HLT/V1                                           (runs 196046 - 196531)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.0/HLT/V2                                           (run 198022)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.0/HLT/V3                                           (runs 198023 - 198049)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.0/HLT/V4                                           (runs 198050 - 198063)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.0/HLT/V5                                           (runs 198116 - 198230)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.1/HLT/V1                                           (runs 198249 - 199021)
CMSSW_5_2_4_onlpatch5_ONLINE     /cdaq/physics/Run2012/7e33/v3.1/HLT/V2                                           (runs 199318 - 199608)
CMSSW_5_2_6_onlpatch2_ONLINE     /cdaq/physics/Run2012/7e33/v4.0/HLT/V1                                           (runs 199698 - 199877)
CMSSW_5_2_6_onlpatch2_ONLINE     /cdaq/physics/Run2012/7e33/v4.0/HLT/V4                                           (runs 199960 - 200381)
CMSSW_5_2_6_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v4.1/HLT/V1                                           (runs 200466 - 202504)
CMSSW_5_2_6_onlpatch3_ONLINE     /cdaq/physics/Run2012PI/PilotRun/PIHLT/V2                                        (run 202792)
CMSSW_5_2_6_onlpatch3_ONLINE     /cdaq/physics/Run2012PI/PilotRun/PIHLT/V4                                        (runs 202793 - 202794)
CMSSW_5_2_6_onlpatch3_ONLINE     /cdaq/physics/Run2012/7e33/v4.2/HLT/V1                                           (runs 202970 - 203002)
CMSSW_5_2_7_cand3_ONLINE-cms     /cdaq/physics/Run2012/7e33/v4.2/HLT/V1                                           (run 203709)
CMSSW_5_2_7_ONLINE               /cdaq/physics/Run2012/8e33/v1.0/HLT/V2                                           (runs 203777 - 203994)
CMSSW_5_2_7_ONLINE               /cdaq/physics/Run2012/8e33/v1.1/HLT/V1                                           (runs 204100 - 205238)
CMSSW_5_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2012/8e33/v1.2/HLT/V1                                           (runs 205303 - 205834)
CMSSW_5_2_7_onlpatch2_ONLINE     /cdaq/physics/Run2012/8e33/v1.2/HLT/V1                                           (runs 205908 - 206605)
CMSSW_5_2_7_onlpatch2_ONLINE     /cdaq/physics/Run2012/8e33/v2.0/HLT/V2                                           (runs 206744 - 206745)
CMSSW_5_2_7_onlpatch2_ONLINE     /cdaq/physics/Run2012/8e33/v2.0/HLT/V3                                           (runs 206859 - 207100)
CMSSW_5_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2012/8e33/v2.1/HLT/V5                                           (runs 207214 - 207518)
CMSSW_5_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2012/8e33/v2.1/HLT/V6                                           (runs 207779 - 207886)
CMSSW_5_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2012/8e33/v2.1/HLT/V7                                           (runs 207887 - 208686)

**Comment by katilp** [comment]
Provide complete HLT information for 2012 primary datasets (as in #1201)

- [ ] Add the trigger table (run number - sw - configuration) as http://opendata.cern.ch/record/1700 from the top part of http://fwyzard.web.cern.ch/fwyzard/hlt/2012/summary @tiborsimko ?
- [ ] Extract the corresponding trigger config files on the table above from confdb @katilp
- [ ] make sure that the sw source for the corresponding sw versions is tagged in github  @katilp
- [ ] add the list of possible triggers for each primary dataset from https://fwyzard.web.cern.ch/fwyzard/hlt/2012/dataset @tiborsimko ?
- [ ] extract the trigger path pieces from http://fwyzard.web.cern.ch/fwyzard/hlt/2010/summary @tiborsimko ?

**Comment by katilp** [comment]
The HLT trigger config files are in https://cernbox.cern.ch/index.php/s/LZHXV3lcg7s5OUS

**Comment by katilp** [comment]
The CMSSW versions to be linked to the record are in
 https://github.com/cms-sw/cmssw-cvs/releases (not in the usual https://github.com/cms-sw/cmssw as it is approaching size limit):
CMSSW_5_2_3_patch1: https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_3_patch1
CMSSW_5_2_3_patch4 etc
CMSSW_5_2_4_onlpatch1
CMSSW_5_2_4_onlpatch3
CMSSW_5_2_4_onlpatch4
CMSSW_5_2_4_onlpatch5
CMSSW_5_2_6_onlpatch2
CMSSW_5_2_6_onlpatch3
CMSSW_5_2_7
CMSSW_5_2_7_cand3
CMSSW_5_2_7_onlpatch1
CMSSW_5_2_7_onlpatch2
CMSSW_5_2_7_onlpatch3

**Comment by katilp** [comment]
I'll prepare the json for this

**Comment by katilp** [comment]
```
{
    "publisher": "CERN Open Data Portal", 
    "accelerator": "CERN-LHC", 
    "control_number": "FIXME", 
    "abstract": {
        "description": "\n      Here is the list of trigger configuration files for the CMS Run2012B and Run2012C collision data:\n      <table class=\"table\">\n      <thead>\n      <tr><th>Run number</th><th>Software version</th><th>Trigger configuration</th></tr>\n      </thead>\n      <tbody>\n <tr><td>193834 - 193836</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.1/HLT/V11</a></td></tr>\n <tr><td>193998 - 194210</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.1/HLT/V12</a></td></tr>\n <tr><td>194223 - 194225</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.1/HLT/V13</a></td></tr>\n <tr><td>194270 - 194317</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.2/HLT/V2</a></td></tr>\n <tr><td>194424 - 194712</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.2/HLT/V3</a></td></tr>\n <tr><td>194735 - 194778</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.3/HLT/V1</a></td></tr>\n <tr><td>194788 - 194825</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.3/HLT/V2</a></td></tr>\n <tr><td>194896 - 195970</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.3/HLT/V3</a></td></tr>\n    
<tr><td>195868 - 195950</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch3\">CMSSW_5_2_4_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.3/HLT/V3</a></td></tr>\n      <tr><td>196019 - 196027</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch4\">CMSSW_5_2_4_onlpatch4</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.4/HLT/V1</a></td></tr>\n        <tr><td>196046 - 196531</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch4\">CMSSW_5_2_4_onlpatch4</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v2.5/HLT/V1</a></td></tr>\n      <tr><td>198022</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v3.0/HLT/V2</a></td></tr>\n      <tr><td>198023 - 198049</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v3.0/HLT/V3</a></td></tr>\n      <tr><td>198050 - 198063</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v3.0/HLT/V4</a></td></tr>\n      <tr><td>198116 - 198230</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v3.0/HLT/V5</a></td></tr>\n      <tr><td>198249 - 199021</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v3.1/HLT/V1</a></td></tr>\n      <tr><td>199318 - 199608</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch5\">CMSSW_5_2_4_onlpatch5</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/2012/7e33/v3.1/HLT/V2</a></td></tr>\n      <tr><td>199698 - 199877</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch2\">CMSSW_5_2_6_onlpatch2</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v4.0/HLT/V1</a></td></tr>\n      <tr><td>199960 - 200381</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch2\">CMSSW_5_2_6_onlpatch2</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v4.0/HLT/V4</a></td></tr>\n      <tr><td>200466 - 202504</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch3\">CMSSW_5_2_6_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v4.1/HLT/V1</a></td></tr>\n      <tr><td>202792</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch3\">CMSSW_5_2_6_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012PI/PilotRun/PIHLT/V2</a></td></tr>\n      <tr><td>202793 - 202794</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch3\">CMSSW_5_2_6_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012PI/PilotRun/PIHLT/V4</a></td></tr>\n      <tr><td>202970 - 203002</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_6_onlpatch3\">CMSSW_5_2_6_onlpatch3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v4.2/HLT/V1</a></td></tr>\n      <tr><td>203709</td><td><a href=\"https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_7_cand3\">CMSSW_5_2_7_cand3</a></td><td><a href=\"/record/FIXME\">/cdaq/physics/Run2012/7e33/v4.2/HLT/V1</a></td></tr>\n              </tbody>\n      </table>\n      "
    }, 
    "title": "High-Level Trigger information for 2012 CMS open data", 
    "recid": "FIXME", 
    "date_published": "2017", 
    "experiment": "CMS", 
    "collections": [
        "CMS-Trigger-Information"
    ], 
    "run_period": "Run2012B", "Run2012C",
    "date_created": "2012", 
    "type": {
        "primary": "Supplementaries", 
        "secondary": [
            "Trigger"
        ]
    }, 
    "collaboration": {
        "recid": "451", 
        "name": "CMS collaboration"
    }
}
```

**Comment by katilp** [comment]
@ArtemisLav please check again if there can be two run periods and if the syntax is OK for it.
The files for /cdaq/physics/Run2012/7e33/v2.1/HLT/V13 etc are in  https://cernbox.cern.ch/index.php/s/1Zce2DoxTAGSPUS (there maybe more of them and all should be ported to portal even only those covering run numbers here will be linked from this page)

**Comment by ArtemisLav** [comment]
For the run periods, it would need to be like this `"run_period": "Run2012B-Run2012C"` to validate. 
I will make a PR for this and we will update all the "FIXME"s once the 2012 config files records are in place.

**Comment by tiborsimko** [comment]
> "run_period": "Run2012B-Run2012C"

Hmm, this works, but it's not very pretty... If we have a need for having more than one value, perhaps we should reconsider making `run_period` to be a list?

**Comment by ArtemisLav** [comment]
I guess that is the same question I had about the year facet, because if you only click on `2010` you only get that, but perhaps one should also be able to see the results for `2010-2012`.

**Comment by tiborsimko** [comment]
Indeed, I wanted to open a new issue about `year` facet... just a minute 😄

**Comment by katilp** [comment]
For this, and the other SW records in general we could give year of the data to be used and not run period. They do not depend on particular RunA/B/C/D but work on full range.
And in this case the natural choices would be 2010, 2011, 2012, 2011-2012, see also #1891
