### ISSUE TITLE
docs: dead links in contribution guide

### ISSUE THREAD

**Issue by Kjili** [cernopendata/opendata.cern.ch#1190]
The [CONTRIBUTING.rst](https://github.com/cernopendata/opendata.cern.ch/blob/master/CONTRIBUTING.rst) contains some dead links:
- http://inveniosoftware.org/wiki/Tools/Git/Workflow#R2.Remarksoncommitlogmessages should be https://invenio.readthedocs.io/en/latest/technology/git.html#r2-remarks-on-commit-log-messages
- http://inveniosoftware.org/wiki/Tools/Git/Workflow#R1.Remarksoncommithistory should be https://invenio.readthedocs.io/en/latest/technology/git.html#r1-remarks-on-commit-history
- http://inveniosoftware.org/wiki/Development/Contributing should be https://invenio-github.readthedocs.io/en/latest/contributing.html

imho, can make a PR if required.

**Comment by tiborsimko** [comment]
@Kjili Indeed, the guide was not updated since a while... Please send a PR if you are at it. Thanks!

**Comment by Kjili** [comment]
Sorry, I missed the email, #1193 is out now (and commit message is fixed).
