### ISSUE TITLE
CMS instructions: add a missing step

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1196]
We should have a step 4 under Option A in http://opendata.cern.ch/getting-started/CMS
- download the list of validated runs from http://opendata.cern.ch/record/1001 and change the file name on line goodJSON = ...

**Comment by RaoOfPhysics** [comment]
On it.

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Should I work with the same files as before or are things going to be restructured soon?
