### ISSUE TITLE
Help records (57 and 58) for CMS visualisation tools are broken

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1199]
- http://opendata.cern.ch/record/57
- http://opendata.cern.ch/record/58

Both from http://opendata.cern.ch/search?ln=en&p=mccauley+collection%3ACMS-Open-Data-Instructions&action_search=

Originally reported by @adavidzh.

**Comment by adavidzh** [comment]
For the record, both link above are giving me a 500:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
