### ISSUE TITLE
CMS Collection view: Fix the wrong behaviour of the collection pages

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1200]
http://opendata.cern.ch/search?p=Run2010B%20collection%3ACMS-Primary-Datasets
shows "Showing records 1 to 10 out of 14 results."
Clicking on page 2 (down right) gives
http://opendata.cern.ch/search?p=Run2010B+collection%3ACMS-Primary-Datasets&jrec=11
with only 3 entries visible but saying "Showing records 11 to 14 out of 14 results."
Can the behaviour be fixed so that clicking on page 2 would bring to the 4 remaining entries as expected?

**Comment by tiborsimko** [comment]
Closing the issue; the pagination is fixed in the COD3 version.
