### ISSUE TITLE
CMS: add a raw data sample 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1202]
CMS CB approved releasing (order of) 1M events in RAW format from Minimum bias dataset

- [x] Choose a set of files (a block in DAS?) to release
   - parent data for http://opendata.cern.ch/record/24
   - size of 1M events
   - has enough events passing validation (not mandatory for known use-cases of these data but maybe useful for others)
- [x] Check whether the sample could be reconstructed with http://opendata.cern.ch/record/3610/files/configFile.py and using the currently available global tag FT_53_LV5_AN1
- [ ] Add instructions and limitations
- [ ] Add a new collection for "CMS raw data"

**Comment by katilp** [comment]
A block from run 160957 with a good amount of lumi sections in the json file (http://opendata.cern.ch/record/1001/files/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt : "160957": [[1, 953]])
block=/MinimumBias/Run2011A-v1/RAW#1ae245ba-5350-11e0-8d1d-00151755cb60

**Comment by katilp** [comment]
Confirmation from Marco Musich (on the cms-PPD-conveners-AlCaDB list) to the question whether FT_53_LV5_AN1 (already available from cvfms) can be used for re-reco check of RAW instead of FT_R_53_LV5:

> The list of differences between the two Global Tags you mention is available here:
> 
> https://cms-conddb.cern.ch/gtList/GTdiff.html?GlobalTag=FT_53_LV5_AN1&GlobalTag2=FT_R_53_LV5
> 
> despite the apparently long list of differences, almost everything is just due to the different version of the physical DB snapshot taken at two different times.
> The only tags that actually differ are the Jet Energy corrections, that in the FT_53_LV5_AN1 
> have been updated to the "legacy" ones.
> Since FT_53_LV5_AN1 is more updated w.r.t FT_R_53_LV5 (that indeed was used for the 2011 legacy re-reco [1]) and is advertised as the latest Analysis Global Tag to be used for 2011 legacy re-reco DATA [2], it should be totally OK to use it.
> 
> [1] https://twiki.cern.ch/twiki/bin/view/CMS/PdmVConditionValidation#Legacy_Reprocessing_2011A_B
> [2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions#2011AB_Legacy_re_reco_CMSSW_5_3
> 
>

**Comment by katilp** [comment]
First initial confirmation for the re-reco step.

Workflow:

**Comment by katilp** [comment]
List of RAW files for checking the transfer

/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/02FD18E5-7753-E011-B91D-000423D9A2AE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/0E402934-7E53-E011-868E-0030487CD77E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/107A864F-6053-E011-8C67-001D09F2305C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/12796C93-4E53-E011-A888-001D09F2841C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/1298B669-5553-E011-B3B5-0030487CD7E0.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/1A49C5A2-8153-E011-B455-0030487CD7E0.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/1A6C472C-5D53-E011-8E50-001D09F2512C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/1CC0DC26-7C53-E011-B857-003048F0258C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/2094B7A4-6E53-E011-8059-000423D9890C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/22ECE3B2-7A53-E011-AF5D-001617C3B6C6.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/22EEA058-6153-E011-BBEA-001617DBD5AC.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/263B8DF3-7953-E011-B3C0-001D09F251FE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/2AB43E2F-5153-E011-8D32-001617C3B778.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/2AF00F7D-7853-E011-8100-0030487A195C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/2C992C7F-6853-E011-A5CD-003048D2BB90.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/32666198-6553-E011-90F9-0030487CBD0A.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/3A106243-5353-E011-8776-000423D9890C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/4838B123-6B53-E011-A4E7-003048CFB40C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/5024634C-7453-E011-A15E-0030487A322E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/52E47EBB-4F53-E011-A959-0030487CD178.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/54225188-7F53-E011-8550-001D09F24FEC.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/54ACC2FC-7D53-E011-ADEE-001D09F23A34.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/58A93E0F-6253-E011-900D-001617C3B77C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/5A9A51F9-8053-E011-861C-003048F11C5C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/5EB03417-7053-E011-AE1D-000423D9890C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/64DB6F7A-5553-E011-BFBC-0030487C635A.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/68658FC7-5F53-E011-B594-001D09F2512C.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/6A9F3C50-7A53-E011-8206-001D09F295FB.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/6CB22194-7353-E011-B627-003048F01E88.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/6E1B58EB-6653-E011-9A61-003048F024C2.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/7452F822-7053-E011-93A5-0019B9F730D2.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/767FFF01-5B53-E011-BA7D-001617E30D52.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/7A4E0BB7-6753-E011-B99C-0030487C7392.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/7AD3C3E1-7253-E011-A4CF-003048F11114.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/7AEB2818-8353-E011-957B-003048F024DE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/7ED2BB6D-5053-E011-AC80-001617C3B706.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/823DCFB1-7553-E011-8CBF-003048F11C58.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/8258004A-5A53-E011-BC73-0030487C778E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/860C5B4E-6653-E011-B7E2-003048F024DC.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/88E3BDF7-8053-E011-B841-003048F11114.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/8E21AB3F-8053-E011-B575-001D09F25438.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/96F94636-5453-E011-97CE-0030487A1FEC.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/9863E901-7553-E011-8E60-00304879EDEA.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/98F28E09-7553-E011-A218-0030487A3C92.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/9CBCADB2-7A53-E011-9BC2-001617C3B6FE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/9E58A1A9-5B53-E011-A894-003048F117EA.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/A08F2BF8-8053-E011-80FC-0030487CAF5E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/A405732F-7E53-E011-8E9C-001D09F23D1D.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/A604EBD9-6953-E011-9F08-0030487CAF5E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/ACA00F52-5853-E011-9862-0030487C778E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/AE4000E8-6B53-E011-97C9-001D09F282F5.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/B2B30A93-4E53-E011-B173-001D09F28F11.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/BA3888E2-5D53-E011-A1DB-001D09F2906A.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/BAA1CF7E-5753-E011-A3F5-003048F1C424.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/BC48F4B8-7C53-E011-8E36-0030487A1990.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/CA8B1AB6-6253-E011-8377-003048D2BB90.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/CC894567-6353-E011-9DDA-001617E30CC8.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/CEE4ECE0-5D53-E011-A593-0030487A18F2.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/D01FB7B2-7553-E011-8FB8-003048F110BE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/D6F1F7DD-7753-E011-8DAD-000423D9997E.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/D6FE93B4-7A53-E011-AA04-001617DBD472.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/D8BCEC63-7653-E011-8C9E-0030487CD76A.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/D8E0EE91-5953-E011-8F10-0030487CD178.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/DA5BFEFF-6D53-E011-AF3A-003048F01E88.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/E0130F8E-7F53-E011-8CB8-001D09F24EAC.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/E47141BF-6953-E011-8836-0030487CBD0A.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/E8AA4A7B-7153-E011-8A20-0030487CD7EE.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/F2D54691-5253-E011-BD09-001617C3B778.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/F83AEF93-7353-E011-962D-003048F024FA.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/F8AA8950-7A53-E011-9151-001D09F28EA3.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/160/957/FE147EBF-5653-E011-9A35-001617C3B76A.root

**Comment by tiborsimko** [comment]
@katilp The CMS upload area is missing one file `12796C93-4E53-E011-A888-001D09F2841C.root`.

**Comment by katilp** [comment]
The files in the list above (apart from the one missing) are in root://eospublic.cern.ch//eos/opendata/cms/Run2011A/...

**Comment by katilp** [comment]
Final test instructions, in the 2011 VM:

cd CMSSW_5_3_32/src
mkdir recotest
cd recotest

ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA FT_53_LV5_AN1
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA.db FT_53_LV5_AN1_RUNA.db

cmsenv
wget http://opendata.cern.ch/record/3610/files/configFile.py

Change the following in configFile.py:

in: input = cms.untracked.int32(1) 
- change 1 to -1 (all events in file)
in: fileNames = cms.untracked.vstring('file:reco_DIGI2RAW.root')
- change 'file:reco_DIGI2RAW.root' to 'root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root'
- replace  
process.GlobalTag = GlobalTag(process.GlobalTag, 'FT_R_53_LV5::All', '')
with 
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA.db')
process.GlobalTag.globaltag = 'FT_53_LV5_AN1::All'
- comment out
from Configuration.DataProcessing.RecoTLR import customisePrompt
process = customisePrompt(process)

**Comment by katilp** [comment]
Test rereco:
`
Begin processing the 11668th record. Run 160957, Event 490764641, LumiSection 914 at 03-Aug-2017 03:39:11.399 CEST
170803 03:39:37 7473 Xrd: SendGenCommand: Max time limit elapsed for request  kXR_readv. Aborting command.
----- Begin Fatal Exception 03-Aug-2017 03:39:38 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing run: 160957 lumi: 914 event: 490764641
   [1] Running path 'raw2digi_step'
   [2] Calling event method for module CSCTFUnpacker/'csctfDigis'
   [3] Reading branch FEDRawDataCollection_source__HLT.
Exception Message:
Fatal Root Error: @SUB=TBranchElement::GetBasket
File: root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root at byte:1511814260, branch:FEDRawDataCollection_source__HLT.obj, entry:11667, badread=1, nerrors=1, basketnumber=649
----- End Fatal Exception -------------------------------------------------
03-Aug-2017 03:39:38 CEST  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root

`

**Comment by katilp** [comment]
Test rereco failed again but in a different event:
```
Begin processing the 20928th record. Run 160957, Event 492364710, LumiSection 917 at 04-Aug-2017 02:50:20.620 CEST
170804 02:50:37 8340 Xrd: SendGenCommand: Max time limit elapsed for request  kXR_readv. Aborting command.
----- Begin Fatal Exception 04-Aug-2017 02:50:38 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing run: 160957 lumi: 917 event: 492364710
   [1] Running path 'raw2digi_step'
   [2] Calling event method for module CSCTFUnpacker/'csctfDigis'
   [3] Reading branch FEDRawDataCollection_source__HLT.
Exception Message:
Fatal Root Error: @SUB=TBranchElement::GetBasket
File: root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root at byte:2716866788, branch:FEDRawDataCollection_source__HLT.obj, entry:20927, badread=1, nerrors=1, basketnumber=1043
----- End Fatal Exception -------------------------------------------------
04-Aug-2017 02:50:39 CEST  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MinimumBias/RAW/v1/000/160/957/00CD8D3F-8053-E011-9C1F-001D09F290CE.root
```

**Comment by katilp** [comment]
A test analysis to compare some selected values from the orginal AOD and the new rerecontructed  AOD in preparation

**Comment by katilp** [comment]
The comparison code to validate the rereco step is now available in https://github.com/katilp/compare-rereco (will be move to cms-opendata-validation repository)

**Comment by katilp** [comment]
Summary for the new RAW record:

Name: MinimumBias primary dataset sample in RAW format from RunA of 2011 (from /MinimumBias/Run2011A-v1/RAW) 

Collection: CMS primary datasets

Collision energy: 7 TeV

Description: A sample from MinimumBias primary dataset in RAW format from RunA of 2011. Run period  160957

Characteristics:
Dataset: N events 72 files 252.4 GB in total

System Details
Global tag: FT_53_LV5_AN1
Recommended release for reconstruction: CMSSW_5_3_32

How were these data selected?

Events stored in this primary dataset were selected because of the presence of low-energy particles (soft-QCD events).

Data taking / HLT 
The collision data were assigned to different RAW datasets using the following HLT configuration (link to http://opendata.cern.ch/record/1700).

HLT trigger paths 
The possible HLT trigger paths in this dataset are: 
(same list as in http://opendata.cern.ch/record/24)

How were these data validated?
(same as http://opendata.cern.ch/record/24)

How can you use these data?

These data are in RAW format and not directly usable in analysis. The reconstructed data reprocessed from these RAW data are incuded in the data of record http://opendata.cern.ch/record/24
The reconstruction step can be repeated with the code available in (a new record based on https://github.com/katilp/recotest) and the resulting AOD has been confirmed to be indentical with the original one with comparison code available in (a new record based on https://github.com/katilp/compare-rereco)

Issues & Limitations

This dataset contains one run from 2011 RunA. The list of validated lumi sections, which must be applied to all analyses, can be found in
CMS list of validated runs for primary datasets of 2011 data taking

**Comment by tiborsimko** [comment]
@katilp @RaoOfPhysics Since this is for 2011 data and the first RAW dataset example, coming with only 1 dataset record and 1 software record, shall we release this into PROD instance already using the current COD2 version, separately from the 2012 release rush? Or shall we release this only on the DEV instance using the COD3 version already? Thinking about how this could be best announced for the PR purposes for general public, regarding RAW dataset news (nice!) and 2012 dataset news (2 PBs!) the most efficiently. Do you want to make two separate announcements?

**Comment by katilp** [comment]
@tiborsimko OK for me. @RaoOfPhysics any thought?

**Comment by suenjedt** [comment]
It seems like a low hanging fruit we should harvest sooner rather than later (when it gets mixed up with the next release)

**Comment by tiborsimko** [comment]
@ArtemisLav Can you please prepare corresponding dataset and software records? (either for COD2 or COD3)

**Comment by ArtemisLav** [comment]
@tiborsimko Could you please generate FFTs for the dataset record and fill in `256e` & `256b`?

**Comment by katilp** [comment]
For the RAW record, number of events is 1913190
(das query: file block=/MinimumBias/Run2011A-v1/RAW#1ae245ba-5350-11e0-8d1d-00151755cb60  | sum(file.nevents) )

**Comment by RaoOfPhysics** [comment]
Fine with me, re. releasing this first and 2012 later.

**Comment by tiborsimko** [comment]
> Could you please generate FFTs for the dataset record and fill in 256e & 256b?

Yes, and I'll convert the three records for COD3 only.
