### ISSUE TITLE
Scientific research with CERN Open Data - a list of challenges named by Achim Geiser

### ISSUE THREAD

**Issue by Kjili** [cernopendata/opendata.cern.ch#1203]
**1. Knowledge about the possibility of open data analysis, and being convinced that this possibility is actually practically feasible with reasonable effort.**

For the first, it is up to the collaborations and open data to keep advertising this possibility. This involves providing data suitable for research (the ESA page can be viewed as an example in the right direction for making data accessible, keep this in mind for points 4 and possibly 5).

For the second, it is necessary to advertise the results which have already been achieved by external groups. It might be useful to contact the authors and ask them for their permission to display their work as examples on the open data portal.

Additionally, examples can be provided by collaboration-internals working only with knowledge accessible from the outside to demonstrate feasibility.

**2. Some knowledge about theoretical particle physics in order to judge which kind of analysis would be scientifically relevant.**

This needs to be provided by the users, either by having such experience themselves, or by getting advice from theorists with such experience.

**3. Some knowledge about how detectors and reconstruction algorithms work, in order to be able to make the connection between the quantities actually measured which are provided by the experiment, and the physics quantities or messages which one will eventually want to extract.**

This again needs to be provided by the users, either by having such experience themselves (experienced experimentalist), or by getting advice from experimentalists with such experience.

**4. Documentation how to access and handle the data.**

This is actually not perfect but quite well provided on the research section of the open data page.

Of course, part of this is also that the examples provided actually need to work technically within a reasonable time and effort for a "standard" user who does not have access to a large computing farm with support from a corresponding IT group.
So far, this worked very well for "simple" examples (with the 2010 data from CMS). For more complex examples (the 2011 data from CMS) this is becoming more difficult, both because the examples become more ambitious (the presence of MC enourmously increases the possibilities and complexisty of what one can do) and because the data sets are significantly larger.
At the same time, it becomes much more interesting scientifically.

Also, the amount of information on the open data page is already so large meanwhile that it is not always easy to find what one is looking for. Adding some kind of introductary "dictionary" or tree structure directing people to the right place might be useful.
The "education" part is much more straightforward in that respect.

**5. Documentation on how to use the software.**

This part is very poorly developed so far, since there is almost no formal documentation of research-related software and algorithms on the open data page.
Some, but by far not all of it, can be "guessed" by a user with experience from other experiments by making analogies to data structures known from elsewhere.
If information on details of the (collaboration-specific) software and data structures is publicly available on the web, it can be searched for, but relying on that is not really how open data should work, in particular since nobody will guarantee that this information will still exist in a few months from now.
Collaboration-internals have the possibility to mix this public information with internally available information, but even this may require additional effort.
It would be great to make the existing software documentation, for the software releases which are part of the open data, openly available and easily accessible on/from the open data page. This is of course not a trivial task and help by the collaborations will be needed to achieve it.

_These remarks only refer to scientific research with CERN Open Data, not to the educational parts._

**Comment by suenjedt** [comment]
This partially relates to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSPublicData, I think

**Comment by daslerr** [comment]
Closing, as this was originally partially addressed by #1218 and the twiki content has its own issue at #1518 .
