### ISSUE TITLE
CMS: L1 trigger information records not found

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1204]
I can't find the L1 trigger information records on the portal. From
https://github.com/cernopendata/opendata.cern.ch/blob/6b13253597fc5f40454b64b5ba03ec1499861006/invenio_opendata/testsuite/data/cms/cms-l1-trigger-information-Run2011A.xml
I could guess that they should be records 3700 and on, but they do not exist.
Can't find them with search either.

**Comment by tiborsimko** [comment]
Whoops! Fixed.

- http://opendata.cern.ch/record/3700
- etc
