### ISSUE TITLE
Add record/59 to CMS Learning Resources

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1214]
http://opendata.cern.ch/record/59 to be added to http://opendata.cern.ch/collection/CMS-Learning-Resources

Instructions, paraphrased from @tiborsimko's comment:

> Add record to static template https://github.com/cernopendata/opendata.cern.ch/blob/production/invenio_opendata/base/templates/helpers/text/cms_learning_resources.html

**Comment by tiborsimko** [comment]
@katilp While working on this issue, I noticed that the EGI FedCloud site at IFCA is not responding at the original URL http://cmsopendata.ifca.es/. Can you please check with the IFCA people?

**Comment by RaoOfPhysics** [comment]
It has gone down in the past as well. :(

**Comment by katilp** [comment]
I've contacted the IFCA people for this

**Comment by tiborsimko** [comment]
When the IFCA site is up, we should take a screenshot and update the template accordingly.

(But I merged anyway in the meantime with the masterclass picture.)

**Comment by katilp** [comment]
From IFCA side, the service is being migrated to a new version as there were a lot of problems. They will update us when done.
