### ISSUE TITLE
CMS: bug in downloading the files from records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1222]
Download of xml files in records gives an error page because the browser interprets them instead of just downloading.
Example BuildFile.xml in http://opendata.cern.ch/record/560
Possible solutions:
- change download behaviour (@tiborsimko is this possible and would it be independent of user's browser settings?)
- add instructions to use wget http://opendata.cern.ch/record/560/files/BuildFile.xml

**Comment by RaoOfPhysics** [comment]
I can confirm that the problem manifests in Firefox and Chromium on macOS.

**Comment by katilp** [comment]
@tiborsimko Can this be closed?

**Comment by RaoOfPhysics** [comment]
@katilp: I think so. Firefox prompts me to download the file, while Chromium downloads it directly. Closing the issue.
