### ISSUE TITLE
Disable glossary within iSpy

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1223]
As pointed out in an e-mail to opendata-support, the tooltip for the glossary terms appears on the [iSpy page](http://opendata.cern.ch/visualise/events/CMS) as well, with a slight error:

![latex-in-tooltip-not-evaluated](https://cloud.githubusercontent.com/assets/7623019/22506580/843e75d4-e881-11e6-87e5-a13749548535.png)

It might be best to disable the glossary entries for iSpy itself, while leaving it active in the help pages.

**Comment by tiborsimko** [comment]
This is just one manifestation of MathJax not being enabled on the COD pages.  LaTeX is not rendered in other pages, too.  Hence I'm closing this issue as a subset of #1224.
