### ISSUE TITLE
Files in record 341 not found. Cannot download files

### ISSUE THREAD

**Issue by artfisica** [cernopendata/opendata.cern.ch#1227]
Dear developers,

Thanks as usual for all the help.
We would like to call your attention about some problems to download files in:
http://opendata.cern.ch/record/341

None of the files are reachable, we are getting **502 Bad Gateway** in all of them.

Cheers,
Arturo

**Comment by artfisica** [comment]
Good day,

After Tibor's intervention (Thanks!) the problem is now that we are getting an error of the kind: **404 Not Found** when try to download.

Cheers,
Arturo

**Comment by tiborsimko** [comment]
@artfisica Thanks for reporting! The system should be back to normal now after a permission check and a cache cleanup. Please reopen if you see some other problem.
