### ISSUE TITLE
UI: Mockups

### ISSUE THREAD

**Issue by daslerr** [cernopendata/opendata.cern.ch#1228]
Based on our recent discussions, I've updated the mockup for the homepage. 
- The examples and information stuff has been moved higher on the page to give more emphasis to user stories. 
- The list of datasets has been removed, since users typically will get to those via the VMs and not directly. 

![opendata-mockup-home-v3](https://cloud.githubusercontent.com/assets/3181623/22892837/2ae8d24e-f214-11e6-92da-1cb91982e3cc.png)

**Comment by katilp** [comment]
Very nice! I'll add below comments and suggestions from Achim

**Comment by katilp** [comment]
Comments received from Achim

> Thanks a lot for the mockup and to those who have designed it!
> Is this the proposed sketch of a single starting web page?
> It seems a bit crowded for that purpose to me.
> Probably the PR people are much better trained to judge this
> kind of stuff than me, but here is my opinion:
> 
> In my view, the main starting page should really be addressing the point 
> of view of the general public, since this will presumably be the bulk of 
> the visitors.
> 
> Therefore I would move the "What is this?" section directly after the 
> screenshot eyecatcher (to give orientation to casual visitors),
> discuss the education issues second (presumably second-most frequent
> application), and put the research part third (the most novel, but also
> the most difficult application, which only a small fraction of the 
> visitors will qualify for).
> 
> For the research part, I would again use a picture or two as an 
> eye-catcher (e.g. currently the dimuon mass spectrum, from this summer 
> onwards the Higgs mass peak) and be very generic with the text, e.g. 
> something like:
> "I want to reproduce the content of selected original LHC publications
> or do my own original research with LHC data"
> 
> The corresponding link should then lead to the header page of the
> research part which should change style from the "eye-catcher general
> public" appearance of the general header page to a "scientific style"
> small-print guide to actual research applications, oriented towards
> the information needed by researchers. This is also the level at which 
> branches towards different experiments would appear.
> It would be great if we could at least partly edit things from this
> level downward directly ourselves. This concerns in particular the
> intermediate levels which direct people to the information relevant to 
> them, and which will need frequent updates.
> The basic generic records could then again be standardized (and not 
> editable by us), as they have been so far, since they will presumably not 
> change once established (except if they stop working).
> 
> Correspondingly, I would not put lists of actual research applications on 
> the "front page" (this will quickly exceed any reasonable length for a 
> header page), but rather have them one or partly even two levels lower.
> 
> The style of the educational part should be decided by the "education 
> people", they know better than me.
> 
> The purpose of the "data collections" on the main page is not quite clear 
> to me, since it makes limited sense to direct people to specific data 
> before they have chosen what they want to use these data for.
> Actually there is a corresponding text comment just above ("list of 
> datasets has been removed") which however does not seem to have been 
> implemented.
> 
> Cheers,  Achim

**Comment by daslerr** [comment]
Thanks for the feedback! The comment in the original post talking about removing the list of datasets is referring to a previous mockup version shown in the meeting on Friday that had a highlight list of individual datasets for users to choose from (and not the data collections section). Kati pointed out that users were extremely unlikely to need direct access to the datasets in that way, so that was removed. 

I agree that "data collections" is not a very user-friendly label and needs to be changed. Those are intended to be links to landing pages for subsets of data, such as CMS data or ATLAS data or data for machine learning. Anything tagged with that experiment/collection would show up on that landing page (e.g. datasets, tools or software, relevant examples, etc). It was my understanding from previous conversations that a researcher might know that they wanted to work with CMS data, for instance, and so would want an entry point that directed them straight to CMS data and tools. Is that the case? 

I have a question about this part of the comment:

> It would be great if we could at least partly edit things from this level downward directly ourselves. This concerns in particular the intermediate levels which direct people to the information relevant to them, and which will need frequent updates.

Does this mean that you would like a way for people from the experiments to post or update examples, guidance, or documentation directly instead of that having to be part of a formal site update or data release process? I think this is a good idea, especially since, as you say, this content could benefit from more frequent updates than the usual data release schedule. I see any issues with this being more logistical and human (e.g. who gets permission to do this, does the content require curation or approval, etc.) than technical, but it's something we can explore.

**Comment by tiborsimko** [comment]
@daslerr @sefeg It would be good to enlarge the focus of the "new IA" thougths on the whole web site, i.e. not to focus solely on the story-driven home page, but also discuss the future of the current news, glossary, help, collection, etc pages. Can you please prepare a set of new IA wireframe proposals for all those various pages and/or proposals where to move the information they currently contain?This will help to give the big picture of a coherent whole new web site so that we can start preparing the page templates in the new COD3 overlay.

If it helps, here is the current "local" URL map on top of the Invenio standard pages:

```console
$ inveniomanage show-urls | grep invenio_opendata
/                                                         invenio_opendata.middle                 
//static/<path:filename>                                  invenio_opendata.static                 
/<string:exp>/getstarted                                  invenio_opendata.get_started            
/VM                                                       invenio_opendata.data_vms               
/VM/<exp>/validation/report                               invenio_opendata.val_report             
/VM/<string:exp>                                          invenio_opendata.data_vms               
/VM/<string:exp>/<string:year>                            invenio_opendata.data_vms               
/about                                                    invenio_opendata.about                  
/about/ALICE                                              invenio_opendata.about_alice            
/about/ATLAS                                              invenio_opendata.about_atlas            
/about/CMS                                                invenio_opendata.about_cms              
/about/CMS-Physics-Objects                                invenio_opendata.about_physics          
/about/CMS-Physics-Objects/<string:year>                  invenio_opendata.about_physics          
/about/CMS-Pileup-Simulation                              invenio_opendata.cms_pileup_simulation  
/about/CMS-Simulated-Dataset-Names                        invenio_opendata.sim_dataset_names      
/about/LHCb                                               invenio_opendata.about_lhcb             
/about/alice                                              invenio_opendata.about_alice            
/about/atlas                                              invenio_opendata.about_atlas            
/about/cms                                                invenio_opendata.about_cms              
/about/lhcb                                               invenio_opendata.about_lhcb             
/collection                                               invenio_opendata.collections            
/collection/<name>                                        invenio_opendata.collection             
/collections                                              invenio_opendata.collections            
/education                                                invenio_opendata.educate                
/education/<string:exp>                                   invenio_opendata.educate                
/experiments                                              invenio_opendata.collections            
/getstarted                                               invenio_opendata.get_started            
/getstarted/<string:exp>                                  invenio_opendata.get_started            
/getting-started                                          invenio_opendata.get_started            
/getting-started/<string:exp>                             invenio_opendata.get_started            
/getting-started/<string:exp>/<string:year>               invenio_opendata.get_started            
/glossary                                                 invenio_opendata.glossary               
/news                                                     invenio_opendata.news                   
/privacy-policy                                           invenio_opendata.privacy                
/record/<int:recid>                                       invenio_opendata.metadata               
/record/<int:recid>/                                      invenio_opendata.metadata               
/record/<int:recid>/citations                             invenio_opendata.metadata               
/record/<int:recid>/export                                invenio_opendata.metadata               
/record/<int:recid>/export/<of>                           invenio_opendata.metadata               
/record/<int:recid>/files                                 invenio_opendata.metadata               
/record/<int:recid>/keywords                              invenio_opendata.metadata               
/record/<int:recid>/load/authors/                         invenio_opendata.load_authors           
/record/<int:recid>/load/authors/<int:start>/to/<int:end> invenio_opendata.load_authors           
/record/<int:recid>/load/files/                           invenio_opendata.load_files             
/record/<int:recid>/load/files/<int:start>/to/<int:end>   invenio_opendata.load_files             
/record/<int:recid>/metadata                              invenio_opendata.metadata               
/record/<int:recid>/references                            invenio_opendata.metadata               
/record/<int:recid>/usage                                 invenio_opendata.metadata               
/research                                                 invenio_opendata.research               
/research/<string:exp>                                    invenio_opendata.research               
/resources                                                invenio_opendata.resources              
/resources/<string:exp>                                   invenio_opendata.resources              
/terms-of-use                                             invenio_opendata.terms                  
/visualise/events/<string:exp>                            invenio_opendata.visualise_events       
/visualise/histograms/<string:exp>                        invenio_opendata.visualise_histo        
/youraccount/                                             invenio_opendata.no_accounts            
/youraccount/access                                       invenio_opendata.no_accounts            
/youraccount/display                                      invenio_opendata.no_accounts            
/youraccount/edit/<name>                                  invenio_opendata.no_accounts            
/youraccount/login                                        invenio_opendata.no_accounts            
/youraccount/logout                                       invenio_opendata.no_accounts            
/youraccount/lost                                         invenio_opendata.no_accounts            
/youraccount/register                                     invenio_opendata.no_accounts            
/youraccount/view                                         invenio_opendata.no_accounts            
```

**Comment by daslerr** [comment]
We've taken into account everyone's feedback so far, and we've added some additional pages. Here is a link to a prototype where most stuff is clickable: 

https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/prototype/Home%20page?key=8c2506d3f4eb78c78449a1bee0e5bb2288588016

One important thing that isn't shown in this prototype is the means by which collaboration representatives would be able to post additional guides. This needs further discussion, but we will proceed with testing without it, since it doesn't affect the majority of users. 

The biggest structure-related change proposed here is creating an additional record type for 'articles,' which would be basically anything that's text-heavy, like the help pages or guide/tutorial pages. The hope is that this would help with searching. Many of the pages in Tibor's URL map above could either turn into instances of articles or could become category tags for records. A breakdown of how this could work out is below. 

Comments welcome!

```
**** in prototype - largely unchanged *****
//static/<path:filename>                                  invenio_opendata.static                 
/<string:exp>/getstarted                                  invenio_opendata.get_started                                     
/collection                                               invenio_opendata.collections            
/collection/<name>                                        invenio_opendata.collection             
/collections                                              invenio_opendata.collections                                              
/glossary                                                 invenio_opendata.glossary                                              
/record/<int:recid>                                       invenio_opendata.metadata               
/record/<int:recid>/                                      invenio_opendata.metadata               
/record/<int:recid>/citations                             invenio_opendata.metadata               
/record/<int:recid>/export                                invenio_opendata.metadata               
/record/<int:recid>/export/<of>                           invenio_opendata.metadata               
/record/<int:recid>/files                                 invenio_opendata.metadata               
/record/<int:recid>/keywords                              invenio_opendata.metadata               
/record/<int:recid>/load/authors/                         invenio_opendata.load_authors           
/record/<int:recid>/load/authors/<int:start>/to/<int:end> invenio_opendata.load_authors           
/record/<int:recid>/load/files/                           invenio_opendata.load_files             
/record/<int:recid>/load/files/<int:start>/to/<int:end>   invenio_opendata.load_files             
/record/<int:recid>/metadata                              invenio_opendata.metadata               
/record/<int:recid>/references                            invenio_opendata.metadata               
/record/<int:recid>/usage                                 invenio_opendata.metadata                      

**** removed (could become tags) ****
/education                                                invenio_opendata.educate                
/education/<string:exp>                                   invenio_opendata.educate 
/experiments    <-- same as /collections                  invenio_opendata.collections            
/research                                                 invenio_opendata.research               
/research/<string:exp>                                    invenio_opendata.research 
/resources                                                invenio_opendata.resources              
/resources/<string:exp>                                   invenio_opendata.resources      

**** becomes instance of 'article' record type ****
/VM    <-- documentation; actual VMs are records          invenio_opendata.data_vms               
/VM/<exp>/validation/report                               invenio_opendata.val_report             
/VM/<string:exp>                                          invenio_opendata.data_vms               
/VM/<string:exp>/<string:year>                            invenio_opendata.data_vms  
/about                                                    invenio_opendata.about                  
/about/ALICE                                              invenio_opendata.about_alice            
/about/ATLAS                                              invenio_opendata.about_atlas            
/about/CMS                                                invenio_opendata.about_cms              
/about/CMS-Physics-Objects                                invenio_opendata.about_physics          
/about/CMS-Physics-Objects/<string:year>                  invenio_opendata.about_physics          
/about/CMS-Pileup-Simulation                              invenio_opendata.cms_pileup_simulation  
/about/CMS-Simulated-Dataset-Names                        invenio_opendata.sim_dataset_names      
/about/LHCb                                               invenio_opendata.about_lhcb             
/about/alice                                              invenio_opendata.about_alice            
/about/atlas                                              invenio_opendata.about_atlas            
/about/cms                                                invenio_opendata.about_cms              
/about/lhcb                                               invenio_opendata.about_lhcb 
/getstarted                                               invenio_opendata.get_started            
/getstarted/<string:exp>                                  invenio_opendata.get_started            
/getting-started                                          invenio_opendata.get_started            
/getting-started/<string:exp>                             invenio_opendata.get_started            
/getting-started/<string:exp>/<string:year>               invenio_opendata.get_started  
/news                                                     invenio_opendata.news  
/privacy-policy                                           invenio_opendata.privacy  
/terms-of-use                                             invenio_opendata.terms    

**** not shown in prototype ****      
/youraccount/                                             invenio_opendata.no_accounts            
/youraccount/access                                       invenio_opendata.no_accounts            
/youraccount/display                                      invenio_opendata.no_accounts            
/youraccount/edit/<name>                                  invenio_opendata.no_accounts            
/youraccount/login                                        invenio_opendata.no_accounts            
/youraccount/logout                                       invenio_opendata.no_accounts            
/youraccount/lost                                         invenio_opendata.no_accounts            
/youraccount/register                                     invenio_opendata.no_accounts            
/youraccount/view                                         invenio_opendata.no_accounts 
```

**Comment by tiborsimko** [comment]
Mock-ups for various pages were introduced in https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/grid
