### ISSUE TITLE
CMS: MC categorization for 2012 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1229]
Separating this from #1188

The MC to be included:
GT: START53_V19: The legacy campaign for the 2012 MC (called Summer12DR53X) (757.6 TB)

In that campaign there were also some additional special production (mostly run-dependent) using other GTs:

START53_V19F: BPH run-dependent DIGI-RECO in 5.3. (162.8 TB)
START53_V19E : digi-reco in 5.3 with specific Muon alignement for EXO (1.3 TB)
START53_V7N : run dependent for h2gg (254.6 TB)

The MC listings to be categorized:

https://cmsweb.cern.ch/das/request?view=plain&limit=3000&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12_DR53X*V19-*%2FAODSIM

[Summer12_DR53X-PU_S10_START53_V19-.pdf](https://github.com/cernopendata/opendata.cern.ch/files/782885/Summer12_DR53X-PU_S10_START53_V19-.pdf)

https://cmsweb.cern.ch/das/request?view=plain&limit=3000&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12_DR53X*V19F*%2FAODSIM

[Summer12_DR53X-PU_S10_START53_V19F.pdf](https://github.com/cernopendata/opendata.cern.ch/files/782888/Summer12_DR53X-PU_S10_START53_V19F.pdf)

https://cmsweb.cern.ch/das/request?view=plain&limit=3000&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12_DR53X*V19E*%2FAODSIM

[Summer12_DR53X-PU_S10_START53_V19E.pdf](https://github.com/cernopendata/opendata.cern.ch/files/782889/Summer12_DR53X-PU_S10_START53_V19E.pdf)

https://cmsweb.cern.ch/das/request?view=plain&limit=3000&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12_DR53X*V7N*%2FAODSIM

[Summer12_DR53X-PU_S10_START53_V7N.pdf](https://github.com/cernopendata/opendata.cern.ch/files/782890/Summer12_DR53X-PU_S10_START53_V7N.pdf)

@tiborsimko Can you check what comes out with the 2011 MC categorization algorithm?

**Comment by tiborsimko** [comment]
@katilp Here are the results if I run the previous MC Run2011categorisation rules on the MC Run2012 data:

- http://simko.home.cern.ch/simko/tmp/opendata.cern.ch-issue-1229.html

There are probably too much "SM Inclusive" cases, which was the default fallback category when the previous rules didn't apply... We can see and adjust IRL together.

**Comment by katilp** [comment]
Excellent, thanks! It looks very good, the outsiders in the SM inclusive category look easily recognizable (most likely what we call "exotica" or Beyond Standard Model). I'll check with the physics conveners.

**Comment by katilp** [comment]
Note (for myself): the datasets, which have been requested by different PAGs can be found in PREP (for run1 and McM for run2).
e.g. datasets requested by EXO (-> BSM) in Summer12_DR53X production campaign:
http://cms.cern.ch/iCMS/prep/requestmanagement?status=any&pwg=EXO&campid=Summer12_DR53X&dsn=
 
![prepview](https://cloud.githubusercontent.com/assets/5859918/23469640/6ed06390-fea4-11e6-8701-d4f7671fb7e5.PNG)

NB that the request by a PAG may also contain the SM background samples, so not every entry in the list above goes to the BSM category (and similarly for the other PAGs and categories).

**Comment by katilp** [comment]
After a discussion with Josh:

Agreed to change the catergory BSM Higgs just to BSM
new keywords for BMS

- ADD*
- CIT*
- QBH*
- *prime*
- GMSB*
- AToZh
- GluGluToA
- Graviton*
- *Gravitino*
- *HTohh*
- *MSSM*
- QDQD*
- QDTo*
- QUTo*
- *SMS*
- *SUSY*
- AxiTo*
- Branon*
- Bstar*
- DMZ*
- DarkMatter*
- HeavyGluon*
- *Hplus*
- LQTo*
- Majorana*
- QStar*
- Radion*
- Seesaw*
- THmTTo*
- THpTTo*
- TTChiChi*
- *anomWtb*
- Vector1*
- VectorMix*
- WRTo*
- *chargino*
- monoLepton*
- Spin0Plus*
- Spin2PH*

for B physics (now in SM exclusive, inclusive)
- BcToBsPi
- BsToKstar
- Xibstar0*

for SM exclusive (now is systematic variations)
- TT_MT1000
- TT_MT800
- TT_Mtt-1000
- TT_Mtt-700

for SM Higg (now in SM incl)
- VBF_HWWTo*

**Comment by tiborsimko** [comment]
@katilp Thanks, here are the latest results with some more information about datasets:

- http://simko.home.cern.ch/simko/tmp/opendata.cern.ch-issue-1229.html

**Comment by katilp** [comment]
The samples for which the categories are not clear can be checked by Josh once transferred and we have extracted the LHC header (with the dumpLHEHeader.py script) on the Open Data VM. NB that in the current release the script has a bug which makes it repeat the contents multiple times and this makes the listing very long. Josh will have a look and update.

**Comment by tiborsimko** [comment]
As discussed with @katilp, the BSM category should read `*Graviton*`, not `Graviton*`. Reprocessing...

**Comment by tiborsimko** [comment]
The categorisation is finished:

- http://simko.home.cern.ch/simko/tmp/opendata.cern.ch-issue-1229.html
- http://simko.home.cern.ch/simko/tmp/opendata.cern.ch-issue-1229.txt

**Comment by katilp** [comment]
@tiborsimko I have checked the first MC patch (SM inclusive, in transfer) with Josh, please note the following:

- all M-15To50 and M-6To15 (8 datasets) go to SM exclusive4
- all xHWidth go to SM Higgs
- all
/GluGluTo2L2Nu_Bkgd_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Bkgd_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Bkgd_up_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Signal_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Signal_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Signal_up_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_SignalplusBkgd_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_SignalplusBkgd_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_SignalplusBkgd_up_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
go to SM systematic variations
- /EtabToPsi2SPhi_8TeV-pythia6-evtgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM goes to B physics

**Comment by katilp** [comment]
Possible search key words for BSM MC datasets: sample name

- Dark matter: DM*, DarkMatter
- Leptoquark: LQ*
- BSM Higgs:
- Graviton:
-

**Comment by heitorPB** [comment]
These are the categories from [CMS Publications](https://cms-results.web.cern.ch/cms-results/public-results/publications/):

-    Forward and Small-x QCD Physics
-    B Physics and Quarkonia
-    Standard Model Physics
-    Top Physics
-    Higgs Physics
-    Supersymmetry
-    Exotica
-    Beyond 2 Generations
-    Heavy-Ion Physics

The current categories in the script are:

- B-physics
- BSM
- SM Systematic Variations
- SM Higgs
- SM Exclusive
- SM Inclusive

@katilp, @tiborsimko  how should we proceed? Use only the list from the CMS Physics Publications?

**Comment by heitorPB** [comment]
As per discussed with @katilp, we consider this categorisation scheme:

- B Physics and Quarkonia
- Top Physics
- Higgs Physics
- Forward and Small-x QCD Physics
- Standard Model
  - DY
  - QCD
  - Others
- Heavy-Ion Physics
- Beyond 2 Generations
- Exotica
- Supersymmetry
- Physics Modelling

I'm working with the scripts and currently this is the result:
https://hpascoal.web.cern.ch/hpascoal/tmp/categories-2018-10-03.html

**Comment by heitorPB** [comment]
with the 2015 and 2016 MC samples, there are a lot of `Exotica` datasets. Should we split them in subcategories? Which ones you suggest, @katilp ?

The script has these tests that should be moved to other categories:

- BSM:
  - '/atozh',
  - '/gluglutoa',
  - 'htohh',
  - '/qdqd',
  - '/qdto',
  - '/quto',
  - '/axito',
  - '/heavygluon',
  - '/thmtto',
  - '/thptto',
  - '/ttchichi',
  - 'anomwtb',
  - '/vector1',
  - '/vectormix',
  - '/wrto',
  - '/monolepton',
  - '/spin0plus',
  - '/x53',
  - '/spin2ph',
- SM Exclusive:
  - 'HT'
  - 'Pt'
  - 'enriched'
  - 'tt_mt1000'
  - 'tt_mt800'
  - 'tt_mtt-1000'
  - 'tt_mtt-700'
  - '[0-9]jet'

suggestions?

I tried to run `dumpLHEheader` script in the `/AxiToQjet*`, but the files are not available.

Results here:
https://hpascoal.web.cern.ch/hpascoal/tmp/2018-10-05/

**Comment by tiborsimko** [comment]
We had discussed the question whether the categories should be nested or not with @ArtemisLav in the past and we think it would be good to keep the list linear.  This would mean using "composite expressions" like:

```
Standard Model: DY
Standard Model: QCD
Standard Model: Others
```

Could we start like this? Depending on how the display would look like after we populate the categories for existing datasets, we could eventually introduce nested browsing.  (@heitorPB Do you know you will be limited to using one level only?)

**Comment by heitorPB** [comment]
The idea was to use a maximum of two levels. Add each dataset _to_ one category (or subcategory). This is hardcoded for each record, not flexible. For example:

- B Physics and Quarkonia
- Top Physics
- Higgs Physics
  - SM
  - BSM
- Forward and Small-x QCD Physics
- Standard Model
  - DY
  - ElectroWeak
  - QCD
  - T
  - Others
- Heavy-Ion Physics
- Beyond 2 Generations
- Exotica
  - Dark Matter
  - Leptoquark
  - Graviton
  - Extra Dimensions
  - Excited Fermions
  - Heavy Gauge Bosons
  - Contact Interaction
  - Heavy Fermions, Heavy Righ-Handed Neutrinos
  - Colorons, Axigluons, Diquarks
  - Resonances
  - others
- Supersymmetry
- Physics Modelling

Another idea was to complement the categories with labels. This is a flexible 'categorisation', independent of the category of the dataset, to improve the search. Tags/labels can be combined with logical operators `and` and `or` (also `not`?) as in [here](https://twiki.cern.ch/twiki/bin/view/AtlasPublic/ExoticsPublicResults):
![higgs](https://user-images.githubusercontent.com/13461702/48069687-50d22380-e1d6-11e8-8878-788db2974231.png)

**Comment by heitorPB** [comment]
PR #2457 adds a page with description of the categories

**Comment by heitorPB** [comment]
Page about the categories is live in dev: http://opendata-dev.cern.ch/docs/simulated-dataset-categories

**Comment by tiborsimko** [comment]
@katilp The new categories for all currently existing CMS MC 2011 and 2012 records are visible on DEV:

- http://opendata-dev.cern.ch/search?subtype=Simulated&type=Dataset&experiment=CMS

You may want to check the "Categories" facet and how it behaves. We shall need to widen the facet box width but also probably shorten some category names (e.g. `Forward and Small-x QCD Physics` will be always sort of long...)

**Comment by heitorPB** [comment]
Categories deployed on opendata-dev.cern.ch, scripts will be on https://github.com/cernopendata/data-curation soon
