### ISSUE TITLE
CMS: Testing MC production on Open Data VM

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1231]
The available MC collection cannot cover all possible use-cases, which depend on users' interest and the subject of study. Therefore we are studying the possibility of generating MC samples on 2011 Open Data VM with

- the CMSSW release corresponding to the collision data (CMSSW_5_3_32)
- the available Global Tag (START53_LV6)

If successful, we can try to repeat this for 2010 Open Data VM.

First observations:

1: Adapt an existing configuration file and see if it works

copy the first configuration file for MC production for the dataset http://opendata.cern.ch/record/1393
(linked after "Step SIM")

cd CMSSW_5_3_32/src/
mkdir Gen
cd Gen
wget http://opendata.cern.ch/record/3286/files/configFile.py
cmsenv

This first step, producing GEN-SIM (i.e. doing pythia event generation and simulation step) runs on 2011 Open Data VM when the symbolic links are first set to

ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1 START53_LV6A1
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db START53_LV6A1.db

and then run

cmsRun configFile.py

with this change of GlobalTag in the configFile.py:
comment the following line
process.GlobalTag = GlobalTag(process.GlobalTag, 'START53_LV4::All', '')

and add these two lines:
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db')
process.GlobalTag.globaltag = cms.string('START53_LV6A1::All')

For HLT step download right configFile.py and make following changes

wget http://opendata.cern.ch/record/3258/files/configFile.py
   
comment the following lines
process.load('SimGeneral.MixingModule.mix_2011_FinalDist_OOTPU_cfi')
process.mix.input.fileNames = cms.untracked.vstring([])

and add these lines
process.load('SimGeneral.MixingModule.mixNoPU_cfi')
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db')
process.GlobalTag.globaltag = cms.string('START53_LV6A1::All')

For the RECO step change only global tags

wget http://opendata.cern.ch/record/3303/files/configFile.py

comment the following line
process.GlobalTag = GlobalTag(process.GlobalTag, 'START53_LV6::All', '')

and add these lines
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db')
process.GlobalTag.globaltag = cms.string('START53_LV6A1::All')

2: check the cmsDriver.py script

cmsDriver.py is a script which can generate the configuration files for the MC production and for the MC and collision data reconstruction, and it is available on the Open Data VM (after cmsenv).

Configuration files can be generated with (taken from an example in https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGeneration#SampleConfig)

cmsDriver.py Configuration/Generator/python/SingleElectronPt10_cfi.py -s GEN,SIM,DIGI,L1,DIGI2RAW,HLT --conditions GlobalTag,START53_LV6::All --datatier 'GEN-SIM-RAW' --eventcontent RAWSIM -n 10 --no_exec

(resulting file)
SingleElectronPt10_cfi_py_GEN_IDEAL.py

and they produce files (after having changed the reading of global tags from cvfms as above) which can be opened in root.

NB: when opening the newly generated file with the root version in use together with CMSSW_5_3_32 
5.32/00 ends into segmentation fault when opening some of the collections. This happens both on Open Data VM and on lxplus (also when the root file has been produced on lxplus and not). This problem does not occur on lxplus with a more recent root version 5.34/36.

**Comment by katilp** [comment]
See the report from @caredg in https://indico.cern.ch/event/707169/contributions/2906362/attachments/1607580/2551373/LongLivedAndExamples_DPOA_ECarreraFNavarro.pdf (p7 cmsdriver.py fully functional)

**Comment by katilp** [comment]
@caredg The GT START42_V17B is now available on /cvmfs for 2010 MC.
Would you have a MC generation test job to try if it can be read properly?

**Comment by caredg** [comment]
@katilp, I have tested the new GT under CMS 2010 VM v5, and the SLC5 container. Working with CMSSW_4_2_8, I was not successful in reading this GT from /cvfms while trying to simulate some DY montecarlo.  The error I get is in the attached log file.
[gen.log](https://github.com/cernopendata/opendata.cern.ch/files/2546390/gen.log):
%MSG-s CMSException:  (NoModuleName) 04-Nov-2018 17:25:48 -05 pre-events
cms::Exception caught in cmsRun
---- Configuration BEGIN
Error occurred while creating PoolDBESSource
---- Data member "m_wrapper" not found in the mapping element of variable "value_type". from ObjectStreamerBase::buildDataMembers BEGIN
---- Data member "m_wrapper" not found in the mapping element of variable "value_type". from ObjectStreamerBase::buildDataMembers END
---- Configuration END

I had followed similar modifications (regarding the GT) as were put in place for the trigger example (https://github.com/cms-opendata-analyses/trigger_examples/blob/2010/TriggerInfo/TriggerInfoAnalyzer/README.md).

On the other hand, if I try to read directly from Frontier, it complains that "TagCollectionRetriever::getTagCollection: global tag: START42_V17B:All does not exist", as was expected.

**Comment by caredg** [comment]
I re-ran the gen-sim config file for DY production that I had tried before.  This time I can confirm that it ran smoothly.  
I will complete the test over the whole chain (+HLT and RECO), but I do not expect issues, at least with the access....

**Comment by katilp** [comment]
Closing as followed now in #2344
