### ISSUE TITLE
FAQ items

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1234]
Here is an initial list of frequently asked questions:

The root password for CMS Open Data VM is "password"

In some versions of VirtualBox, the CMS Open Data VM does not open correctly. This has happened for example for VirtulBox 5.0.32, but for example 5.1.8 is OK.

xml files do not download correctly by clicking on "Download" e.g. http://opendata.cern.ch/record/560/files/BuildFile.xml 
in record http://opendata.cern.ch/record/560
Note that all files can be downloaded directly from the CMS Open Data VM terminal with wget e.g.
wget http://opendata.cern.ch/record/560/files/BuildFile.xml

**Comment by katilp** [comment]
After the Windows update in June 2017, Virtualbox will not start. The problem has been fixed by the VirtualBox team and downloading the most recent version (5.1.22) from https://www.virtualbox.org/wiki/Downloads solves the problem.

**Comment by tiborsimko** [comment]
This should be added to the "CMS Guide to troubleshooting" as seen with @katilp. 

@atrisovic Can you please take care of this?

**Comment by atrisovic** [comment]
Should this be added to "known issues FAQ" or troubleshooting?

**Comment by katilp** [comment]
@atrisovic to the new troubleshooting guide.
