### ISSUE TITLE
OPERA: attach CSV files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1243]
After OPERA dataset records are created (#1242), the CSV data files from Sergey should be attached to the records.

**Comment by tiborsimko** [comment]
@dmitr25 Please see the following record about CVS column description: (see "Dataset Semantics")

- http://opendata.cern.ch/record/328

**Comment by tiborsimko** [comment]
Example from CMS:

```
EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,DER_pt_ratio_lep_tau,DER_met_phi_centrality,DER_lep_eta_centrality,PRI_tau_pt,PRI_tau_eta,PRI_tau_phi,PRI_lep_pt,PRI_lep_eta,PRI_lep_phi,PRI_met,PRI_met_phi,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight
100000,138.47,51.655,97.827,27.98,0.91,124.711,2.666,3.064,41.928,197.76,1.582,1.396,0.2,32.638,1.017,0.381,51.626,2.273,-2.414,16.824,-0.277,258.733,2,67.435,2.15,0.444,46.062,1.24,-2.475,113.497,0.00081448039868,s,t,0.00265331133733
100001,160.937,68.768,103.235,48.146,-999.0,-999.0,-999.0,3.473,2.078,125.157,0.879,1.414,-999.0,42.014,2.039,-3.011,36.918,0.501,0.103,44.704,-1.916,164.546,1,46.226,0.725,1.158,-999.0,-999.0,-999.0,46.226,0.681041906806,b,t,2.23358448717
100002,-999.0,162.172,125.953,35.635,-999.0,-999.0,-999.0,3.148,9.336,197.814,3.776,1.414,-999.0,32.154,-0.705,-2.093,121.409,-0.953,1.052,54.283,-2.186,260.414,1,44.251,2.053,-2.028,-999.0,-999.0,-999.0,44.251,0.715742006349,b,t,2.34738894364
```

**Comment by tiborsimko** [comment]
@dmitr25 I have tried to attach your files locally on my laptop, but the organisation of having 2 records with 6533 attached CSV files does not really work that well... Moreover it would be hard for people to cross-link ED and ECC events, such as get all data for 12337026514 regardless of whether it is ED and ECC, if that kind of use case may be of interest.  

Can we talk about the record-vs-files organisation on Tuesday? Some options to consider:

- create one record per event?
- create separate records for subdetectors?
- attach files as not-so many CSV files, but rather as a few ZIP files?

(Basically I'm looking at better numeric balance between the number of records and files. More IRL.)

**Comment by dmitr25** [comment]
@tiborsimko Yes, we can discuss this (may be via Skype?) on Tuesday morning. Is 10am OK for you? My skype account is s_dmitrievsky. As for me, more than 1-2 files per event is too many. :) I would also prefer to have a bit more complicated format for each file and to combine, for example, TT, RPC, and DT hits. Just let me know!

**Comment by tiborsimko** [comment]
@dmitr25 I'm busy at 10am but I'll let you know via email. Skype is OK.

**Comment by dmitr25** [comment]
@tiborsimko Here is the final version of the ED and ECC data collections for 818 OPERA events.
[OpenDataCollections_818Events.zip](https://github.com/cernopendata/opendata.cern.ch/files/1038442/OpenDataCollections_818Events.zip)
