### ISSUE TITLE
CMS: 2012 data transfer

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1250]
#Starting the data transfer of 2012 data

Collision data (557.6 TB)

RunB collision data: /*/*2012B-22Jan2013*/AOD 218.9 TB request done + completed  + moved
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1013354

RunC collision data: dataset=/*/*2012C-22Jan2013*/AOD 338.7 TB excluding LP_* request done + completed + moved
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1026086

MC: 

SM inclusive  (326.9 TB)
part 1/ SM inclusive 131.4 TB
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1094160 completed + moved 
part 2/ SM inclusive 179.7 TB
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1094164 completed + moved 
part 3/ SM inclusive 15.8 TB
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1094169 completed + moved 

Dataset in addition to those above needed for 4lepton example preparation
/SMHiggsToZZTo4L_M-125_8TeV-powheg15-JHUgenV3-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1122909 completed + moved
SM Higgs 106.2 GB

SM exclusive (207 TB)
part 1/SM exclusive  113 TB
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1128391 started + last dataset done (update 19 april 2018)
part 2/ SM exclusive 94 TB
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1128392 started + all done (updated 12 March 2018) + moved #2347

SM Higgs (16.9 TB + ...)
part 1/ all 125 files for H_m = 125
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1152684 started + all doen (updated 2 Nov 2018)

Two missing single t/tbar files
2 files
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1154769 started + completed

**Comment by katilp** [comment]
checking if the following are SM incl:

To (SM excl?)
/DYToMuMu_M-6To15_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-6To15_TuneZ2star_8TeV-pythia6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/DYToMuMu_M-15To50_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-6To15_Tune4C_8TeV-pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM

xHWidth (SM H?) e.g:
/GluGluToWWTo2L2Nu_25xHWidthContinInterf_M-125_mWW-140to300_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluToWWTo2L2Nu_25xHWidthContinInterf_M-125_mWW-300_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluToWWTo2L2Nu_1xHWidthContinInterf_M-125_mWW-0to140_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluToWWTo2L2Nu_1xHWidthContinInterf_M-125_mWW-140to300_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

up/down (syst?)
/GluGluTo2L2Nu_SignalplusBkgd_up_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_SignalplusBkgd_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Signal_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Signal_up_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GluGluTo2L2Nu_Bkgd_down_8TeV_gg2vv315-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

(B?)
/EtabToPsi2SPhi_8TeV-pythia6-evtgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

**Comment by katilp** [comment]
Continue the MC transfer

SM systematics: 65753 files, 183.2 TB bytes in total
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1202479

**Comment by tiborsimko** [comment]
Physics Modelling: 1 transfer needed

- /Neutrino_Pt_2to20_gun/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
