### ISSUE TITLE
CMS: Global tag and the corresponding condition data for 2012 release

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1263]
- [x] Verify if the Global Tag to be used for analysis of 2012 collision data is different from FT_53_LV5_AN1 (i.e. that for the 2011 data) and the one for 2012 MC different from START53_LVA1

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions#Winter13_2012_A_B_C_D_datasets_r : FT53_V21A_AN6 and START53_V27 Waiting for a  confirmation from Giovanni Franzoni.

- [x] Ask for sqlite files to be produced for the condition data of the run range (full 2012 190456- 208686, and only runs in in RunB 193833-196531 and RunC 198022- 203742 - in order to reduce the waiting time at the beginning of the analysis job). (NB the events numbers are taken from https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2012Analysis#22_JanReReco)

- [x] Make sure that the special treatment for JEC corrections (extended run range) is included if needed. Waiting for a confirmation from Sal Rappoccio.

- [x] Have the sqlite file transferred to cvmfs. The instructions for copying them to cvfms

> You'd login to cvmfs-cms-opendata-conddb.cern.ch  and then do
> 
>    sudo -i -u cvcmso
>    cvmfs_server transaction cms-opendata-conddb.cern.ch
> 
> Now /cvmfs/cms-opendata-conddb.cern.ch is writable and you can use the
> shell to copy all the files you need.  Once finished, you'd do
> 
>    cvmfs_server publish cms-opendata-conddb.cern.ch
> 
> And ~1h later the content appears at the clients. 

 

- [ ] Add the files in http://opendata.cern.ch/collection/CMS-Condition-Data

**Comment by katilp** [comment]
From Giacomo: the new folders and files in /cvmfs/cms-opendata-conddb.cern.ch/:

MC:
START53_V27 and START53_V27.db 

RunB:
FT53_V21A_N6 and FT53_V21A_N6.db ( exported for run interval 193833-196531, except for the JetCorrector tags for the first  - NB they are less then the older set for 2011)

RunC:
 FT53_V21A_N6_RUNC contains  198022-203742 the JetCorrector tags fixed for the first iov=1.

ls /cvmfs/cms-opendata-conddb.cern.ch
FT53_V21A_AN6     FT53_V21A_AN6_RUNC     FT_53_LV5_AN1     FT_53_LV5_AN1_RUNA     START53_LV6A1     START53_V27     testfile
FT53_V21A_AN6.db  FT53_V21A_AN6_RUNC.db  FT_53_LV5_AN1.db  FT_53_LV5_AN1_RUNA.db  START53_LV6A1.db  START53_V27.db

**Comment by katilp** [comment]
Testing with a 2012 datafile, see #1295

**Comment by katilp** [comment]
Testing with https://github.com/cms-opendata-analyses/pattuples2011, json file from #1262 and root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BJetPlusX/AOD/22Jan2013-v1/20000/00009852-3182-E211-A433-0026189438E9.root.
Done:
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6 FT53_V21A_AN6
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6.db FT53_V21A_AN6.db
In config file
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6.db')
process.GlobalTag.globaltag = 'FT53_V21A_AN6::All'
Got the following error:
`18-Jul-2017 11:24:54 CEST  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BJetPlusX/AOD/22Jan2013-v1/20000/00009852-3182-E211-A433-0026189438E9.root
Begin processing the 1st record. Run 195868, Event 75303238, LumiSection 43 at 18-Jul-2017 11:26:24.343 CEST
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::fetchNext 1 SQL logic error or missing database
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::finalize 10 disk I/O error
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::finalize 1 cannot commit - no transaction is active
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::execute 1 cannot commit - no transaction is active
----- Begin Fatal Exception 18-Jul-2017 11:28:33 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 195868 lumi: 43 event: 75303238
   [1] Running path 'p'
   [2] Calling event method for module PATElectronProducer/'patElectrons'
   [3] Using EventSetup component EcalLaserCorrectionService/'' to make data EcalLaserDbService/'' in record EcalLaserDbRecord
   [4] Using EventSetup component PoolDBESSource/'GlobalTag' to make data EcalLaserAPDPNRatios/'' in record EcalLaserAPDPNRatiosRcd
Exception Message:
A std::exception was thrown.
cannot commit - no transaction is active ( CORAL : "SQLiteStatement::execute" from "CORAL/RelationalPlugins/sqlite" )
----- End Fatal Exception -------------------------------------------------
18-Jul-2017 11:28:33 CEST  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BJetPlusX/AOD/22Jan2013-v1/20000/00009852-3182-E211-A433-0026189438E9.root
`

**Comment by katilp** [comment]
First run fails, the next attempt is OK, this behaviour is seen also by Edgar when testing trigger info reading.

**Comment by katilp** [comment]
Problem solved (by itself?), see https://github.com/cernopendata/opendata.cern.ch/issues/1300#issuecomment-317055488 and https://github.com/caredg/cms_legacy_data/tree/2011/TriggerInfo/TriggerInfoAnalyzer usage instructions)

**Comment by tiborsimko** [comment]
@ArtemisLav Here is the information for creating three new Condition Data records for the CMS 2012 data release.  (Note that I haven't copied the files onto EOS yet...)

**Comment by ArtemisLav** [comment]
@katilp Could you please provide titles and descriptions for each record?

**Comment by katilp** [comment]
This is for collision data Run2012B, should we have a separate entry for Run2012C (in that case, it is equal to this but FT53_V21A_AN6_RUNC in place of FT53_V21A_AN6.
@tiborsimko can get the files. Take note of the mention in https://github.com/cernopendata/opendata.cern.ch/pull/1805#issuecomment-344686234 for the file location in EOS

```
{
    "files": [
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/FT53_V21A_AN6.db", 
            "version_id": "41b26351-39d6-4f2b-954c-4299429472a2", 
            "key": "FT53_V21A_AN6.db", 
            "size": FIXME
        }, 
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/FT53_V21A_AN6.tgz", 
            "version_id": "eb18dfd8-f341-478a-9622-cf229418012c", 
            "key": "FT53_V21A_AN6.tgz", 
            "size": FIXME
        }, 
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/file-indexes/CMS_Run2012B_db_FT53_V21A_AN6_file_index.txt", 
            "version_id": "FIXME", 
            "key": "CMS_Run2012B_db_FT53_V21A_AN6_file_index.txt", 
            "type": "index", 
            "size": FIXME
        }
    ], 
    "publisher": "CERN Open Data Portal", 
    "accelerator": "CERN-LHC", 
    "control_number": "1801", 
    "abstract": {
        "description": "<p>Condition database includes non-event-related\n      information (Alignment, Calibration, Temperature, etc) and parameters for\n      simulation/reconstruction/analysis software.</p>\n      <p> These files are needed when running a CMSSW job on the Open Data VM. They are automatically read from\n      the /cvmfs/cms-opendata-conddb.cern.ch runtime, you do not need to download these files from here separately.</p>\n      <p>FT53_V21A_AN6 is to be used with the collision data of RunB 2012 (with the event range of the open data, the file for the full event range for 2012 are also stored\n      under FIXME on /cvmfs/cms-opendata-conddb.cern.ch)</p> \n      <p>For 2012 CMS Simulated Datasets see:</p>", 
        "links": [
            {
                "recid": "FIXME"
            }
        ]
    }, 
    "title": "Condition data for 2012 CMS collision data", 
    "recid": "FIXME", 
    "date_published": "2017", 
    "experiment": "CMS", 
    "collections": [
        "CMS-Condition-Data"
    ], 
    "run_period": "Run2012B", 
    "date_created": "2012", 
    "type": {
        "primary": "Environment", 
        "secondary": [
            "Condition"
        ]
    }, 
    "collaboration": {
        "recid": "451", 
        "name": "CMS collaboration"
    }
}
```

**Comment by katilp** [comment]
For simulated data, we have a "problem" of file location. For 2011, it was put under root://eospublic.cern.ch//eos/opendata/cms/Run2011A/db/ whereas strictly speaking MC tag is good for all 2011 (or 2012), and not for run period Run2011A only (or for Run2012B or Run2012C only). It would make more sense to have it under plain year directory. Here however, I keep the usage from 2011 :

```
{
    "files": [
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/START53_V27.db", 
            "version_id": "FIXME", 
            "key": "START53_V27.db", 
            "size": FIXME
        }, 
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/START53_V27.tgz", 
            "version_id": "FIXME", 
            "key": "START53_V27.tgz", 
            "size": FIXME
        }, 
        {
            "checksum": "FIXME", 
            "bucket": "FIXME", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/file-indexes/CMS_Run2012B_db_START53_V27_file_index.txt", 
            "version_id": "FIXME", 
            "key": "CMS_Run2012B_db_START53_V27_file_index.txt", 
            "type": "index", 
            "size": FIXME
        }
    ], 
    "publisher": "CERN Open Data Portal", 
    "accelerator": "CERN-LHC", 
    "control_number": "1801", 
    "abstract": {
        "description": "<p>Condition database includes non-event-related\n      information (Alignment, Calibration, Temperature, etc) and parameters for\n      simulation/reconstruction/analysis software.</p>\n      <p> These files are needed when running a CMSSW job on the Open Data VM. They are automatically read from\n      the /cvmfs/cms-opendata-conddb.cern.ch runtime, you do not need to download these files from here separately.</p>\n      <p>START53_LVA1 is to be used with the simulated data</p>\n      <p>For 2011 CMS collision data see</p>",       

        "links": [
            {
                "recid": "FIXME"
            }
        ]
    }, 
    "title": "Condition data for 2012 CMS Simulated Datasets", 
    "recid": "FIXME", 
    "date_published": "2017", 
    "experiment": "CMS", 
    "collections": [
        "CMS-Condition-Data"
    ], 
    "run_period": "Run2012B", 
    "date_created": "2012", 
    "type": {
        "primary": "Environment", 
        "secondary": [
            "Condition"
        ]
    }, 
    "collaboration": {
        "recid": "451", 
        "name": "CMS collaboration"
    }
}
```

**Comment by tiborsimko** [comment]
@katilp I see the `*.db` files in `/cvmfs/cms-opendata-conddb.cern.ch`, but not the `*.tgz` files... Where to get them from?

**Comment by tiborsimko** [comment]
I'll just make a tarball of all the files in given `FT53_V21A_AN6` directories...

**Comment by katilp** [comment]
@tiborsimko OK, that's fine. We may need an update for this, to be confirmed in few days.

**Comment by tiborsimko** [comment]
So far I have copied the following only:

```
root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/FT53_V21A_AN6.db 119808 9f6b79104ed3562232849454dd6cb6b5039e9238
root://eospublic.cern.ch//eos/opendata/cms/Run2012B/db/START53_V27.db 130048 6f0f12509c70baddb99380da8859d879e3f5b58f
root://eospublic.cern.ch//eos/opendata/cms/Run2012C/db/FT53_V21A_AN6_RUNC.db 120832 4fa656cdfe9efd4bae55d776b16e144b40fb2706
```

@ArtemisLav You can perhaps update your PR with these files only, and we can merge it, while waiting for the confirmation for final files.

@katilp For MC, we could also store the `db` under `/eos/opendata/cms/MonteCarlo2012/...`, which would make more sense... however this would alter the 2011 practice indeed.

@katilp Do we want to store also the other files, e.g. RUNA or FULL, for the sake of completeneness?

**Comment by katilp** [comment]
FULL is new and it is important, as it covers full 2012 data-taking (and not only specific run ranges). It needs an update for VM (#1959) which I think can be done before the release (but not for beta).
For the storage, again the logical problem where to put it...

RUNA is a 2011 db (for RunA ran range).

For MC it would indeed make sense to store it under MonteCarlo2012
