### ISSUE TITLE
CMS: typo in the documentation of http://opendata.cern.ch/record/101 and 234

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1264]
In records
http://opendata.cern.ch/record/101 and http://opendata.cern.ch/record/234
there is a typo in the documentation:

Under "Data selection" in lines 
Distance between the electron z-vertex and the interaction z-vertex < 0.02 cm;
Distance between the muon z-vertex and the interaction z-vertex < 0.02 cm;
the value should be 0.2 cm (for both of these lines)

**Comment by tiborsimko** [comment]
@katilp What about the transverse impact parameter, it's once 0.04cm and once 0.02cm, is that OK? (I'm wondering since I only saw 0.02cm in Dmytro's message.)

**Comment by katilp** [comment]
@tiborsimko The values are different for electrons and muons and for them the text corresponds to the values in the example code, i.e. it is OK as it is now. Thanks for checking!
