### ISSUE TITLE
Update to the record 1050

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1286]
http://opendata.cern.ch/record/1050 can be updated with the following

"The detailed list of luminosity by lumi section is in 2010lumibyls.csv for the list of validated runs and lumi sections."

- 2010lumibyls.csv is in https://cernbox.cern.ch/index.php/s/UrgyCkOt80OyAdO and should be uploaded to the record.
- "the list of validated runs and lumi sections" in the text above should like to http://opendata.cern.ch/record/1000

**Comment by katilp** [comment]
@ArtemisLav Any news on this?

**Comment by ArtemisLav** [comment]
The PR is ready for this, it just needs to get checked by @tiborsimko.

**Comment by katilp** [comment]
@tiborsimko This was an update to CODP2, @ArtemisLav has made the PR, can we make sure that the updates are propagated to CODP3 (PR #1294 is still open)?

**Comment by tiborsimko** [comment]
@katilp Taking care of this now...
