### ISSUE TITLE
Notes from HST 2017

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1292]
Collecting here remarks from HST Open data WG:
- teachers would expect that lowercase/uppercase would not matter in URL
- add a file type as a search key (i.e csv, ig, root, AOD, AODSIM)
- http://opendata.cern.ch/record/72 does not appear under Learning resources

**Comment by sefeg** [comment]
Adding a few more information on the remarks:

- The case sensitivity applies mostly to pages _like_ http://opendata.cern.ch/education/**CMS** (where http://opendata.cern.ch/education/**cms** does not work)

- The file type refers mostly to the datasets as I understand (and could be an interesting category for the faceting)

**Comment by suenjedt** [comment]
See also notes from HST2016 https://github.com/cernopendata/opendata.cern.ch/issues/1172 (will close it now)

**Comment by sefeg** [comment]
Closing, as implemented by now
