### ISSUE TITLE
Cannot find record 545 in search

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1293]
I cannot find the new record
http://opendata.cern.ch/record/545
(e.g..cernopendata.ch/search?ln=en&p=SingleElectron&action_search= or with any other search string from the record name)
in search and it does not appear in the list of derived datasets for 2011
http://opendata.cern.ch/search?p=Run2011A%20collection%3ACMS-Derived-Datasets

**Comment by tiborsimko** [comment]
@katilp Should be fixed now, for example:

- http://opendata.cern.ch/search?p=Datasets+derived+from+the+Run2011A+SingleElectron+SingleMu+DoubleElectron+DoubleMu+primary+datasets
