### ISSUE TITLE
Trigger examples and information to be added to the portal

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1300]
@caredg Could your add a link to your example and any open issues to be discussed here.

**Comment by caredg** [comment]
I have made a simple analyzer example on how to access trigger information.
These are the instructions for 2011: 
https://github.com/caredg/cms_legacy_data/tree/2011/TriggerInfo/TriggerInfoAnalyzer
and for 2010:
https://github.com/caredg/cms_legacy_data/tree/2010/TriggerInfo/TriggerInfoAnalyzer

**Comment by tiborsimko** [comment]
@hjhsalo The source is in Markdown so we can use this as another nice Markdown display example...

**Comment by katilp** [comment]
@caredg Do you think you could "donate" these repos to https://github.com/cms-opendata-validation ?
Or should we rather add them in https://github.com/cms-opendata-analyses as they are rather usage instructions more than validation?

We will link directly to github from the portal records (that's why we would prefer centralised repos rather than personal). However, for data preservation purposes, we can also add the contents of the repo to the records.

I see also that you have nice tree structure in your own repo, maybe we should restucture cms-opendata-validation and cms-opendata-analyses  in a similar manner, at least for the year numbers.
@tiborsimko What do you think? it is still doable as the repos are not too large yet.

**Comment by caredg** [comment]
Hello @katilp , certainly I can "donate" whatever is needed and/or useful.  I think you are right, the trigger info instructions should go into opendata-analyses rather than into validation.  Is there anything I have to do in order to perform this "donation"?

**Comment by katilp** [comment]
@caredg Thanks, very good. You can do it in github Settings, then Transfer Ownership (under "Danger Zone")

**Comment by katilp** [comment]
Thinking about how best to present the information in the portal @tiborsimko @ArtemisLav:
We could have this in the portal as a guide called "The CMS Trigger System"  which consists of text in readme of https://github.com/caredg/cms_legacy_data/tree/2011/TriggerInfo/TriggerInfoAnalyzer
(starting from subtitle "The CMS Trigger System" and ending before "Usage instruction")
The text in this part is the same (@caredg TBC) apart from links to the different versions of the CMSSEW code - but even in case of differences, can we handle this in the similar way with tabs as it is now for Getting started or VM?

Then we can have the code records themselves, in a similar way as other sw records to which the "guide" page should link.

The SW records will then need
Title:
Authors:
Description:
Use with:
System details:
Related items:
How can you use this code:
Issues and limitations:

@caredg Could you provide here the text to appear under these title so that @ArtemisLav and @tiborsimko can prepare the records. If the titles do not fit we can discuss how to change them.
The current sw records look like http://opendata.cern.ch/record/550 or http://opendata.cern.ch/record/200 or others or in http://opendata.cern.ch/search?p=Run2010B%20collection%3ACMS-Validation-Utilities . We have not yet converged for different headers in the records i.e "data selection", "validation", "Issues and limitations", suggestions welcome, we may want to unify a little now as more records are being added.

**Comment by katilp** [comment]
@caredg Could you transfer ownership of the repo to cms-opendata-analyses?

Also to prepare the records, it would be very helpful if you give the information needed for the SW reocrds already in the same form as in http://opendata-qa.web.cern.ch/record/5000 (i.e. Export JSON in the right side of the text, and copy-paste it here in a comment and change the fields to correspond to the trigger example).

NB

1. The general text does not need to be in the record, it will be in the "Guide" part, i.e. separate page that will appear under "Documentation"
2. It would be good to have two SW records, one for 2010 and the other for 2011

**Comment by caredg** [comment]
@katilp , I am so sorry for the delay.  For some reason I thought I already did this.  I have just transferred ownership to the full repository.  The naming (cms_legacy_data) might not be the most accurate to describe the particular case of the Trigger examples.  I have transferred any way.
I will take a look at the needed information for the SW records.....

**Comment by katilp** [comment]
@caredg thanks, no problem! Would you also give a release tag (see https://github.com/cernopendata/opendata.cern.ch/issues/1552#issuecomment-345764057 )

**Comment by katilp** [comment]
@atrisovic Could you prepare an article "Guide to the CMS Trigger System", category Documentation, subcategory Guide? Take the text starting from subtitle "The CMS Trigger System" and ending before "Usage instruction" from https://github.com/cms-opendata-analyses/trigger_examples/blob/master/TriggerInfo/TriggerInfoAnalyzer/README.md. When the SW records in preparation in this issue are done, the article should link to them as Usage instructions (one link for 2010, another for 2011). Thanks!

@caredg I renamed the repo to trigger_examples

**Comment by katilp** [comment]
@caredg Remember to update the git commands in readme to reflect the new location, thanks!

**Comment by caredg** [comment]
- I have updated the instructions in the README.md file to change the git commands to point to the new location.
- I have made two tags, v10.0.0  and v11.0.0, corresponding to 2010 instructions and 2011 instructions, respectively.
- I will prepare the information for the SW records ....

**Comment by caredg** [comment]
This is the information, in json format, for the 2010 trigger example SW.  I have copied and modified only the fields that I thought I could chime in with:

{    
    "title": "Analysis code for extracting the trigger information from the CMS 2010 data",    
    "authors": [
        {
            "name": "Carrera, Edgar"
        }
    ],
    "abstract": {
        "description": " <p>This is an example of the C++ code (and its configuration in Python) needed to extract the trigger information from CMS Open/Legacy data. These instructions are valid to work with 2010 data.  Snippets of this software can be used for physics analysis.  </p>"
    }, 
    "use_with": {
        "description": "Use this with any CMS 2010 primary dataset and/or Montecarlo datasets.", 
        "links": [
            ]
    }, 
    "system_details": {
        "release": "CMSSW_4_2_8", 
        "recid": "249", 
        "description": "Use this code with the CMS Open Data VM environment"
    }, 
    "note": {
        "description": "The examples, within the code, have plenty of in-line comments to make it more understandable (hopefuly) and to point potential users to the original information sources. It has been put together compiling the most important pieces of already-available <a href=\"https://github.com/cms-sw/cmssw\">CMSSW</a> software."
    },
    "usage": {
        "description": " <p>If you do not have the CERN Virtual Machine for 2010 CMS data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2010\">How to install a CERN Virtual Machine</a>. Then install and run the Demo (demo analyzer) program following the instructions at <a href=\"/VM/CMS/2010#testvalidate2010\">How to Test & Validate</a>.</p> <p>To run the analysis, follow the instructions at <a href=\"https://github.com/cms-opendata-analyses/trigger_examples/tree/2010/TriggerInfo/TriggerInfoAnalyzer\">https://github.com/cms-opendata-analyses/trigger_examples/tree/2010/TriggerInfo/TriggerInfoAnalyzer</a>.</p> "
    }, 
   
}

**Comment by caredg** [comment]
This is the information, in json format, for the 2011 trigger example SW.  I have copied and modified only the fields that I thought I could chime in with:

{    
    "title": "Analysis code for extracting the trigger information from the CMS 2011 data",    
    "authors": [
        {
            "name": "Carrera, Edgar"
        }
    ],
    "abstract": {
        "description": " <p>This is an example of the C++ code (and its configuration in Python) needed to extract the trigger information from CMS Open/Legacy data. These instructions are valid to work with 2011 data.  Snippets of this software can be used for physics analysis.  </p>"
    }, 
    "use_with": {
        "description": "Use this with any CMS 2011 primary dataset and/or Montecarlo datasets.", 
        "links": [
            ]
    }, 
    "system_details": {
        "release": "CMSSW_5_3_32", 
        "recid": "251", 
        "description": "Use this code with the CMS Open Data VM environment"
    }, 
    "note": {
        "description": "The examples, within the code, have plenty of in-line comments to make it more understandable (hopefuly) and to point potential users to the original information sources. It has been put together compiling the most important pieces of already-available <a href=\"https://github.com/cms-sw/cmssw\">CMSSW</a> software."
    },
    "usage": {
        "description": " <p>If you do not have the CERN Virtual Machine for 2011 CMS data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2011\">How to install a CERN Virtual Machine</a>. Then install and run the Demo (demo analyzer) program following the instructions at <a href=\"/VM/CMS/2011#testvalidate2011\">How to Test & Validate</a>.</p> <p>To run the analysis, follow the instructions at <a href=\"https://github.com/cms-opendata-analyses/trigger_examples/tree/2011/TriggerInfo/TriggerInfoAnalyzer\">https://github.com/cms-opendata-analyses/trigger_examples/tree/2011/TriggerInfo/TriggerInfoAnalyzer</a>.</p> "
    }, 
   
}

**Comment by katilp** [comment]
@caredg Very good, thanks! The step "Then install and run the Demo (demo analyzer) program following the instructions at <a href="/VM/CMS/2011#testvalidate2011">How to Test & Validate" in usage is probably not needed.

**Comment by katilp** [comment]
@ArtemisLav The files to be attached to this records are:
2010: download zip from https://github.com/cms-opendata-analyses/trigger_examples/tree/v10.0.0
2011: download zip from https://github.com/cms-opendata-analyses/trigger_examples/tree/v11.0.0

**Comment by ArtemisLav** [comment]
I am reopening this since the software records have not been worked on yet.
