### ISSUE TITLE
glossary: link terms from pages

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1314]
We need to offer glossary term explanation to users when they are reading any kind of web page on the CERN Open Data portal. 

One use case scenario: a user is on the page such as `/about/CMS` where he/she sees a long content that contains also the word "muon" that happens to be a glossary term.  The word "muon" should be dot-underlined or otherwise graphically highlighted, and when the user hovers over it with the mouse, he/she should see the explanation of the term.  (and perhaps also see link to the detailed record page for the word muon (`/term/muon`) if we want).

In COD2 world, recognising glossary terms in pages, and linking to them, was done using the `zglossary`  library. In COD3, we are fully free to change the technology, now that we have glossary terms live as records. E.g. we can use the same library and prepare its JSON-needed data format from the term records.  E.g. we can create a fully new way the terms will be linked across pages. E.g. simple JS, e.g. Angular, looking at the future "live instance" use case with deposit and whatnot.

**Comment by ioannistsanaktsidis** [comment]
Only technologies I found are these 2:
https://github.com/gregallensworth/jquery-glossary
https://github.com/PebbleRoad/glossarizer

Can't find ```zglossary``` one. Could it be the case that maybe it doesn't exist itself. Also about the second one I found(glossarizer) seems that there is no license. Is it ok if we can use it ?

**Comment by ioannistsanaktsidis** [comment]
After trying all of them I think number 2 (https://github.com/PebbleRoad/glossarizer) is the best one to use, should we contact the guys so as as to add a license ?

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Besides asking about license, you can also ask about making a release on NPM, and perhaps offer your help preparing a PR for that if they are busy? We had good experiences in the past with similar FLOSS initiatives...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  yes good idea, will create an issue in their repo.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  guys replied and published the package in npm :D 
https://www.npmjs.com/package/glossarizer

**Comment by ioannistsanaktsidis** [comment]
Also do we know exactly  in which pages we want to include the library ? Is it only the ```/about``` ones ? I am asking because this package that i am trying to use has some dependencies that are a bit tricky to resolve... cc @daslerr  @sefeg  @tiborsimko

**Comment by ioannistsanaktsidis** [comment]
So after some tries and some searching finally it appears that we can't use the glossarizer that they released. There are some unresolved dependency issues. I guess we can go on using @pamfilos  library from COD2 as it already works.

**Comment by tiborsimko** [comment]
> Also do we know exactly in which pages we want to include the library ? Is it only the /about ones ? 

It is to be plugged virtually on any page on the system, including record display pages, see for example "photon" linked in:

- http://opendata.cern.ch/record/12 

We excluded it only for some specific pages (or parts of pages), see the use of `no-glossary` in the `qa` branch.
