### ISSUE TITLE
system: remove dependency on `invenio-collections`

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1315]
In COD2, the collections are used heavily.

In COD3, we can remove the `invenio-collections` and simply use the datafield as one facet and experiment field as another facet.  

Since all the data is public, we should not need any specific collection-dependent treatment, and hence can remove this dependency to simplify the setup.

Beware: the former collection pages should be replaced by new Jinja template pages if we do remove the `invenio-collections` module. For example http://opendata.cern.ch/collection/CMS-Learning-Resources

Note also that all the former URLs should work still, so `/collection/ATLAS-Simulated-Dataset`, if no specific page is needed, could redirect to the search page to a URL like `search?collection=dataset&experiment=atlas` (schematically speaking). Or we'd simply introduce Jinja templates for each old collection name.

**Comment by tiborsimko** [comment]
Removing RFC as we agreed to go this way.

Here are the pages to introduce:

- [ ] `/collection/`
- [ ] `/collection/ALICE`
- [ ] `/collection/ALICE-Derived-Datasets`
- [ ] `/collection/ALICE-Learning-Resources`
- [ ] `/collection/ALICE-Reconstructed-Data`
- [ ] `/collection/ALICE-Tools`
- [ ] `/collection/ATLAS`
- [ ] `/collection/ATLAS-Derived-Datasets`
- [ ] `/collection/ATLAS-Higgs-Challenge-2014`
- [ ] `/collection/ATLAS-Learning-Resources`
- [ ] `/collection/ATLAS-Simulated-Datasets`
- [ ] `/collection/ATLAS-Tools`
- [ ] `/collection/Author-Lists`
- [ ] `/collection/CMS`
- [ ] `/collection/CMS-Condition-Data`
- [ ] `/collection/CMS-Configuration-Files`
- [ ] `/collection/CMS-Derived-Datasets`
- [ ] `/collection/CMS-Learning-Resources`
- [ ] `/collection/CMS-Luminosity-Information`
- [ ] `/collection/CMS-Open-Data-Instructions`
- [ ] `/collection/CMS-Primary-Datasets`
- [ ] `/collection/CMS-Simulated-Datasets`
- [ ] `/collection/CMS-Tools`
- [ ] `/collection/CMS-Trigger-Information`
- [ ] `/collection/CMS-Validated-Runs`
- [ ] `/collection/CMS-Validation-Utilities`
- [ ] `/collection/Data-Policies`
- [ ] `/collection/LHCb`
- [ ] `/collection/LHCb-Derived-Datasets`
- [ ] `/collection/LHCb-Learning-Resources`
- [ ] `/collection/LHCb-Tools`
- [ ] `/collection/OPERA`
- [ ] `/collection/OPERA-Detector-Events`
- [ ] `/collection/OPERA-Electronic-Detector-Datasets`
- [ ] `/collection/OPERA-Emulsion-Detector-Datasets`

**Comment by pamfilos** [comment]
So..IRW [the wireframe](https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/Collection%20%28generic%29) what is needed for the collection pages? 

We need ```title```, ```description```,  ```thumbnail```, and record list/s..

Something else needed?

Should we have child/secondary collections (ex parent collection: CMS, secondary collection: CMS-Datasets, like in http://opendata.cern.ch/collection/CMS )? Or should we just have faceting for the same job?

CC @tiborsimko , @sefeg , @daslerr

**Comment by daslerr** [comment]
Off the top of my head, the items you list sound like all that's needed for the collection pages. We don't even necessarily need the thumbnail for collections that don't have experiment logos. 

I'm not entirely clear on what practical difference secondary collections vs. facets makes to the user. If we went with facets instead, this means that if someone wanted to see all CMS derived datasets (for example), they could go to the CMS collection page and select a facet for Derived Datasets, but there would be no separate CMS Derived Datasets page, correct? Does that mean they'd always have to get to the CMS derived datasets that way? Or would there be a page they could link to? If they searched instead for "CMS derived datasets" would they find them? Or does there need to be a named collection in order for that search to be useful?

**Comment by tiborsimko** [comment]
@pamfilos @daslerr I also don't think that we would really need subcollections[*]; all we need is to generate the "same" output as we do now for `/collection/foo` pages. For many collection pages, nothing interesting is printed there, so a simple "go-to-search" would be enough. However, for some collection pages, there is extra information displayed there, so care has to be taken...

[*] E.g. note the ATLAS Kaggle challenge collection which has quite some information on the collection page.  If we turn it into a Jinja template, all is well[**]. If we turn it into a "blog post story", then we probably don't need subcollections, but a nice display of the story body with "attached records". 

[**] Technologically, I was thinking of a simple setup e.g. `/collection/foo` would render template for collection foo if that template file exists; otherwise would search for foo.  That should be enough, I think? We talked about it a bit last Friday...

Let's chat IRL this PM?

**Comment by daslerr** [comment]
Just to document: In the meeting yesterday afternoon, we agreed we don't need secondary collections.

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented. Comments about pages implement are now to corresponding issues.
