### ISSUE TITLE
previewer: demobbed

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1319]
Port standalone OPERA previewer `demobbed` from COD2 to COD3.  Page at `/visualise/events/OPERA/10122009936`.

Requires release on `npm` etc.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  could you pls forward the mail discussion concerning this issue ?

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Yup, I'll do! For the first release, we can NPM-package the JS files with existing embedded data, because it'll take time to create add these additional files onto EOS. We'll follow via email with Sergey...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  Ok then in that case I will prepare a first npm release.

**Comment by ioannistsanaktsidis** [comment]
First release available on npm:
https://www.npmjs.com/package/demobbed-viewer
