### ISSUE TITLE
records: long author list (file list) display paginator

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1322]
Port paginated display for long author and file fields from COD2 to COD3.  Examples:

- long author list http://opendata.cern.ch/record/450
- long file list http://opendata.cern.ch/record/12

Consider technology changes to Angular/whatnot.

This will take care of migrating some COD2 URLs such as `/record/int:recid/load/files/int:start/to/int:end` that we don't need to preserve in COD3 since they were used by the UI only.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in previous PRs.
