### ISSUE TITLE
records: define wanted export formats

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1324]
In COD2, the records were coded in MARC and could have been easily exported into a plethora of formats supported by Invenio (Dublin Core, RefWorks, EndNote...).

In COD3, the records will be coded in custom JSON Schema formats (see #1312). We shall have to write custom serialisers from JSON to any wanted export format we would like to offer.

This RFC is about which export formats we would like offer in addition to JSON to our end users. For example:

- BibTeX
- DataCite XML
- Dublin Core
- CSL
- ...

Any suggestions?

**Comment by suenjedt** [comment]
JSON-LD says @artemislav

**Comment by tiborsimko** [comment]
JSON-LD export is obviously good to offer, but we would still have to decide on which ontologies or vocabularies we would use in its context. For example, do we want to offer FOAF to describe authors, or INSPIRE author schema, or somesuch?  For datasets, shall we use strict DCAT, or Research Objects, or something else? Or shall we simply use only our own custom schemas? That could be another standalone ticket that "only" need implementation once we decide about our own data model. In other words, in this ticket, I was concerned mostly about which kind of  already-existing external schemas we think we would like to support, hence how do we serialise our internal format to the outside world...

**Comment by tiborsimko** [comment]
Example: Frictionlessdata? See e.g. the RDA standard list at http://rd-alliance.github.io/metadata-directory/standards/

**Comment by tiborsimko** [comment]
schema.org for Google dataset search: https://research.googleblog.com/2017/01/facilitating-discovery-of-public.html

**Comment by suenjedt** [comment]
Some additional info from FREYA/Datacite:
- Examples from FREYA partners (that do the LD part too):
PANGAEA: https://doi.pangaea.de/10.1594/PANGAEA.58279 -> get the source and search for the <script type="application/ld+json"> element. Its content is http://schema.org/Dataset JSON-LD.
EBI: http://bioschemas.org/specifications/index.html

- list of repositories already using schema.org https://github.com/datacite/freya/blob/master/schema_org.csv (in case that is helpful)

**Comment by tiborsimko** [comment]
Let's go then for:

- schema.org with JSON-LD

This is exactly what Zenodo did.

**Comment by tiborsimko** [comment]
Closing the RFC.
