### ISSUE TITLE
files:  decide on storage policy

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1325]
In COD2, we have two kinds of files, (i) internal file attached to a record using standard Invenio tools, (ii) external file living on EOS and simply linked in the record.

We need to decide what to do in COD3.  The proposal is to put all the files on EOS, but this could be done (a) using Invenio 3 files module and customising "light buckets" representing big files; (b) using external files living on EOS that will be simply linked in the records without Invenio 3 files module. 

Pros/cons/considerations: 
- we have more files of the "big" kind than of the "small" kind, so attaching files to record is not advantageous, and it makes sense to treat all (i) files like (ii) now [AGREED]
- we don't have any active file submission by users, so treating EOS files as mostly static makes perfect sense, permitting b over a; however later we plan to move onto "live platform" milestone one day, so this might need to be revisited later;
- if we go for a, we would probably have to enrich Invenio files module with "light bucket" support for our special way of storing big files in XRootD exportable folders;
- if we go for b, we would have to write custom file openers for say invenio-previewer to work with this kind of attached-yet-not-really-attached PDF files;
- if we go for b, we would have to write custom SHA1 or byte checkers and correspondence file list <-> EOS content [which is what I'm doing for all collections at the time of creation]

**Comment by tiborsimko** [comment]
Note also that we'd need to introduce some kind of EOS space structure for the former type of files that are currently attached under records (e.g. data policy PDF files). This is because on EOS we only have experiment-oriented structure (e.g. `/eos/opendata/alice/...`). Currently all the files are "experiment-labelled", as it were.  We can obviously use something generic (`/eos/opendata/alice/documents/...`)
or even a directory structure based on musings on data types #1312.

**Comment by tiborsimko** [comment]
Regarding a vs b choice above, investigate also the use of `FileInstance` from `invenio-files-rest` to possibly wrap EOS files in records.

**Comment by ioannistsanaktsidis** [comment]
Concerning ```invenio-files-rest``` I believe after some testing that it doesn't worth to use it, as it requires ```Flask-Login``` and creates some problems in our API. I guess we can go to our custom way by checking ```eos``` files on our own.

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis On the one hand, there is login and user permissions complication indeed. On the other hand, we'd need to create our own custom fixity checksums and friends... so dunno. Perhaps it's easier to configure roles and use the package?  Let's see concrete pros/cons after we have first examples... e.g. data policies are quick to centralise (#1345).
