### ISSUE TITLE
templates: update histogramming's data sources

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1327]
Data sources for basic histogramming tool should be updated following up the record loading and the final URL schema (#1312).

See https://github.com/cernopendata/cernopendata/pull/32#issuecomment-324351419

**Comment by ioannistsanaktsidis** [comment]
See https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/static/js/visualise/visualise_histograms.js#L4
