### ISSUE TITLE
templates: nice record page for Data Policies

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1354]
Now that we have Data Policy records with example PDF files on EOS (#1353), let's prettify the record display page for this record.  This comprises two parts:

(i) prettifying the display of metadata

Make nice boxes and display nicely the record information what has to be displayed etc, following the new wireframes and the old look visible at http://opendata.cern.ch/record/410.  Note that  the current output page is very basic http://0.0.0.0:5000/records/410 and that implementing this issue should make the page nice enough to be user-demoable. 😄 

(ii) serving the files themselves

Offer an URL to download the PDF file without users even knowing the EOS target path. Optionally, plug the integrated PDF previewer, see #1317.

Note that `files.uri` of the form `root://eospublic.cern.ch//eos/opendata/.../foo.pdf` can be opened either with PyFilesystem/XRootD or with HTTP from the EOSPUBLICHTTP front-end server, under `https://eospublichttp.cern.ch/eos/opendata/.../foo.pdf`.

Note that we need to create an endpoint analogous to the old URL `/record/410/files/LHCb-Data-Policy.pdf` so that the legacy URLs would be served well.  In this way the old URLs will keep on working without any redirecting needs.

See also https://github.com/cernopendata/opendata.cern.ch/issues/1325 regarding whether to use Invenio components and for what...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  I have made the detailed page based on the ```data-policies``` example. Does it make sense to merge it since there is this one https://github.com/cernopendata/opendata.cern.ch/issues/1323 still open ? Are we going to keep the schema as it is now or is it going to change ? In case it changes I will put my PR on hold and wait for the changes. Otherwise we can :shipit:  .

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis I think it makes sense to make a PR and merge now, in order to finish the "data policies" example fully... I'll comment on #1323 though.

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented by #1356 and #1416 .
