### ISSUE TITLE
templates: /collection/xxx vs /about/xxx in the page header

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1359]
The page header has prominent "Collaborations" menu with ALICE, ATLAS, LHCb, CMS, OPERA.

Currently, when you click on say CMS, it brings you to a limited `/about/cms` page, while the end user would expect to see lots of CMS-related datasets and information there.

In the new IA/UX/UI, we wanted to point to something like this, I think:

- https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/Collection%20%28generic%29
 
If so, then we need to create these content-ultra rich `/collaboration/xxx` pages and plug them onto page header instead of content-poor `/about/xxx` page.

**Comment by daslerr** [comment]
Yes, the links in the header should go to content-rich pages, rather than the `/about/xxx` pages. But the intention was that they'd go to `/collection/xxx`, which would follow the wireframe you linked to like every other collection, rather than making a new directory for `/collaboration/xxx`.

**Comment by tiborsimko** [comment]
I just copied the `/collaboration` URL from the mock-up 😄 OK for `/collection`.

**Comment by tiborsimko** [comment]
So I think the "Collaboration -> CMS" link in the header is very misleading from the UX point of view. It leads to an "About CMS open data" like page, which should be rather filled under "About -> CMS Open Data" in the page header, as was the case on COD2.

Since we don't have any dedicated collaboration pages, and since we promote search as the main information discovery path, and since we'll feature a very prominent experiment facet there, I propose to simply remove the "Collaborations" menu at the top.

(Otherwise we'd have to go for creating those content-rich pages...)

**Comment by daslerr** [comment]
I agree the pages should move to About instead, and our testing confirms this. No one seems to know what to do with "Collaboration" even if we specifically ask them to find general information for one of the experiments. 

I do think that the content-rich pages would be a good addition, but I agree they're not a priority right now. And even if we create them, they could still be filed under About, so the move makes sense.
