### ISSUE TITLE
docs: proof-read text for /about/opera

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1367]
Implement http://opendatadev.cern.ch/getting-started/OPERA

Currently empty; ask Giovanni and Sergey about page content.

- case 4 - Alias to Faceted Search
- Each getting started page will become an Article and will be tagged with experiment and year.
- Port body to Markdown.

**Comment by annatrz** [comment]
The link is hitting to the faceted page now, implemented in #1442, only markdown needs to be done

**Comment by daslerr** [comment]
I'm removing this issue from the current COD3-Production milestone, since the OPERA release is scheduled for later.

**Comment by atrisovic** [comment]
The docs for the opera first release and about opera exist:

```
/docs/opera-news-first-release-2017
/docs/opera-about
```

**Comment by tiborsimko** [comment]
The press release issue moved to #2380.

So this issue is only about proof-reading the text behind http://opendata-dev.web.cern.ch/docs/about-opera

Changing the issue titte accordingly.

**Comment by tiborsimko** [comment]
@ArtemisLav I think you had some large updates from Giovanni for the "About OPERA" page?

**Comment by ArtemisLav** [comment]
@tiborsimko Yes, you can check https://github.com/cernopendata/opendata.cern.ch/pull/1535

**Comment by tiborsimko** [comment]
OK, I see that the update was merged as @1905 as HTML, but it actually disappeared later when moving the docs Markdown, see `cernopendata/modules/fixtures/data/docs/opera-about/opera-about.md`, for a reason or another... Can you please re-update the Markdown?
