### ISSUE TITLE
templates: /education

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1369]
Implement http://opendata.cern.ch/education/

- mock-up https://invenio.mybalsamiq.com/projects/cod/Education%20landing%20page%20%28dynamic%29

Edit (by @daslerr) : This is a deprecated mockup. The intention at the time of this issue was that selecting a tag would bring the user to a faceted search results page for that tag.

**Comment by tiborsimko** [comment]
Also:

- case 4 - Alias to Faceted Search
- "Education" may or may not become a tag for a Record, depending on whether we determine more specific tags

which may not be fully consistent with the above IA mock-up, unless we enrich the regular search to display rich headers and whatnot...

**Comment by daslerr** [comment]
Sorry, the mock-up linked above is from a deprecated set of wireframes. I've updated the original issue to avoid confusion. 

Per the discussion in the meeting yesterday, "Education" and "Research" will be removed as collections. Additional keywords/tags may be determined later after discussion with the collaborations. Development discussion on display of non-collection keywords/tags is pending.

**Comment by tiborsimko** [comment]
@annatrz Regarding "education" vs "research" for search redirection, the definition is basically as follows:

- the distinction will be based on "collections" value only; 
- if not said otherwise, a collection is education by default;
- the research collections are the following ones: http://opendatadev.cern.ch/research/CMS
- beware, some of them are education also, see: http://opendatadev.cern.ch/education/CMS
- which means that one education means collections C1, C2, C3... and research means collections C2, C10, C11, so to speak.

Implementation-wise, a search for education would mean to do `(collection:C1 OR collection:C2 ...)`, and ditto for research, where you'd simply hard-code the collection list in the code. (As we have some hard-coded stuff in COD2 in places like `invenio_opendata/base/templates/helpers/collections_research.html`.)

Alternatively, to make things simpler, we could redirect to the current search, and simply switch on and off certain corresponding type facets, e.g. primary and collision datasets for research, derived datasets for education, etc. Which facet values are to be switched on and off for education vs research can be derived by looking at the collection list at http://opendatadev.cern.ch/research/CMS.  Usually it is easy, and please recall that we don't have to be 100% correct here, since these URLs will be simply for backwards-compatibility, we won't be advertising them much anymore.

Additionally, we'll have to return also "articles" or "posts" that are displayed under http://opendatadev.cern.ch/research/CMS, such as "How to install CMS VM" etc. So these may be harder to distinguish, which "Documentation" guides should be returned for education and which for research. We could use subtypes here perhaps, as we shall be introducing them to documenation articles.

**Comment by annatrz** [comment]
Ok, I guess solution with using facets should work fine. 
What about /education and /research itself? should return education or research collections for all of the experiments?

**Comment by daslerr** [comment]
Yes, for /research and /education please return search results with the appropriate facets selected to correspond with research or education results for all experiments.
