### ISSUE TITLE
templates: /research

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1374]
Implement http://opendata.cern.ch/research

-   case 4 - Alias to Faceted Search
-  "Research" may or may not become a tag for a Record, depending on whether we determine more specific tags

**Comment by tiborsimko** [comment]
But what about current intro to VM and intro to getting started if this is only a simple faceted search? Use "blog stories"? Or we forget about it?

**Comment by daslerr** [comment]
Yes, the plan was for that kind of introductory and "how to use this" information to become stories that could be searched for or linked from other pages (like the collaboration collection pages). They don't need to be limited to just a research or just an education context. 

Also, "Research" and "Education will be removed as collections. See https://github.com/cernopendata/opendata.cern.ch/issues/1369#issuecomment-329114211.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  @daslerr so what do we do finally with these ones ? do we keep research, education or we drop them completely? and if we keep them should we "tag" the records ? I am asking because I want to start implementing it if we need it or drop all the related issues.

**Comment by daslerr** [comment]
We're not going to use them as tags. /research and /education will each point to search results with certain facets turned on or off (as determined by the COD2 collection lists). See https://github.com/cernopendata/opendata.cern.ch/issues/1369#issuecomment-329114211. I've updated the response there.

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis I talked to @annatrz about how to implement this.  Basically it should be a redirection to search where we enable only certain types... 

BTW I see the URL is broken now:

- http://opendata-dev.web.cern.ch/research

because of:

```
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
web_1            |     rv = self.dispatch_request()
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
web_1            |     return self.view_functions[rule.endpoint](**req.view_args)
web_1            |   File "/code/cernopendata/modules/pages/views.py", line 128, in research
web_1            |     exp_colls, exp_names = get_collections()
web_1            | NameError: global name 'get_collections' is not defined
```

If you plan to take this issue over while @annatrz  is away, I can provide the details...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko yes please provide all the required info, we can start implementing it now.
