### ISSUE TITLE
templates: /visualise

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1377]
Would be nice to return something instead of nothing for this endpoint. E.g. list everything we have on the portal, CMS events, OPERA events, CMS histogramming...

**Comment by daslerr** [comment]
This seems like a case where a landing page would be useful, so we could list the CMS event visualiser, the OPERA event visualiser, and the CMS histogramming in the same place. This is one time where a landing page would be better than a search result list, because it would be more visually interesting.

**Comment by tiborsimko** [comment]
I fully agree. Do you have any UX/UI proposals? The old pages were very simple, just listing what's available: http://opendatadev.cern.ch/visualise/events/

**Comment by ioannistsanaktsidis** [comment]
I am not sure if we need a landing page for that one since with the new homepage we have a block of visualise content where all possible visualisations are listed. cc @daslerr @tiborsimko

**Comment by daslerr** [comment]
I agree that a landing page isn't entirely necessary, given the way the home page is set up now, but if we're set on maintaining old URLs and having them point to something, then it should point to something, and a landing page makes the most sense for the thing it should point to.

**Comment by ioannistsanaktsidis** [comment]
I agree, but /visualise is not returning anything in the COD2 either. Thats why I think we should not added. Anyway if we need it, it is really simple to add it.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko do we finally need this one ?
