### ISSUE TITLE
templates: /glossary

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1378]
Improve styling of `/glossary` in `master` branch.

Mock-up at https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/Glossary

Display prominent "Glossary" title to show where we are.

Display navigation trail.

What about the output message "Found 22 results"? Could be misleading... Hide it? Or just position it more nicely?

**Comment by tiborsimko** [comment]
Beware of "permanent anchors" such as http://opendata.cern.ch/glossary#montecarlo that people may have used. Would be nice to preserve these old URLs.

**Comment by annatrz** [comment]
add breadcrumbs and we can merge

**Comment by tiborsimko** [comment]
The navigation trail subtask is done, but the "Glossry Terms" title subtask and the "Found 22 results" subtask isn't... @annatrz @ioannistsanaktsidis Have you been looking into displaying featured text on search results pages? We should either reopen this ticket or create new daughter tickets so that this does not forgotten...
