### ISSUE TITLE
templates: /education/alice

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1381]
Implement http://opendata.cern.ch/education/ALICE

- case 3 - Collection
- Note: There needs to be a view for each experiment, which will replace the current /education/string:exp and /research/string:exp. So eventually there will be a CMS Collection (for example), but not an /education/CMS Collection.

**Comment by tiborsimko** [comment]
See my notes https://github.com/cernopendata/opendata.cern.ch/issues/1375#issuecomment-328525038 that apply also here.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko concerning this page, how are we going to implement it  ? I can add it as a collection but how can I recognise that it is education? Do we need sth like ```experiment=ALICE&type=Software```? Or should we have sth like ```experiment=ALICE&tag=Education``` ?
