### ISSUE TITLE
templates: /collection/xxx

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1384]
Once we have the demo data, check that all collection pages reply successfully with the same or similar content as the production site.

This will take a while...

- [ ] /collection/
- [x] /collection/ALICE
- [x] /collection/ALICE-Derived-Datasets
- [ ] /collection/ALICE-Learning-Resources
- [x] /collection/ALICE-Reconstructed-Data
- [x] /collection/ALICE-Tools
- [x] /collection/ATLAS
- [x] /collection/ATLAS-Derived-Datasets
- [ ] /collection/ATLAS-Higgs-Challenge-2014
- [x] /collection/ATLAS-Learning-Resources
- [x] /collection/ATLAS-Simulated-Datasets
- [x] /collection/ATLAS-Tools
- [x] /collection/Author-Lists
- [x] /collection/CMS
- [x] /collection/CMS-Condition-Data
- [x] /collection/CMS-Configuration-Files
- [x] /collection/CMS-Derived-Datasets
- [ ] /collection/CMS-Learning-Resources
- [x] /collection/CMS-Luminosity-Information
- [x] /collection/CMS-Open-Data-Instructions
- [x] /collection/CMS-Primary-Datasets
- [x] /collection/CMS-Simulated-Datasets
- [ ] /collection/CMS-Tools
- [ ] /collection/CMS-Trigger-Information
- [x] /collection/CMS-Validated-Runs
- [x] /collection/CMS-Validation-Utilities
- [x] /collection/Data-Policies
- [x] /collection/LHCb
- [x] /collection/LHCb-Derived-Datasets
- [x] /collection/LHCb-Learning-Resources
- [x] /collection/LHCb-Tools
- [ ] /collection/OPERA
- [ ] /collection/OPERA-Detector-Events
- [ ] /collection/OPERA-Electronic-Detector-Datasets
- [ ] /collection/OPERA-Emulsion-Detector-Datasets

**Comment by tiborsimko** [comment]
@annatrz What is the meaning of the checkboxes above?  The collections that are checked do not seem to work yet...

**Comment by annatrz** [comment]
All of them works with lowercase letters urls e.g. /collection/alice, by redirecting to faceted search page. Pages like LHCb-Derived-Datasets, where assuming that this will be a subtype of record, but now with changes in data model, it's probably not valid anymore..

**Comment by tiborsimko** [comment]
Even with lowercasing, some collections work, like:

- http://opendata.cern.ch/collection/CMS-Validation-Utilities
- http://0.0.0.0/collection/cms-validation-utilities

Some collections don't, like:

- http://opendata.cern.ch/collection/CMS-Learning-Resources
- http://0.0.0.0/collection/cms-learning-resources

Reopening...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko what should we return in ```/collection/``` and ```/collection/OPERA``` ? 
This url ```http://127.0.0.1:5000/search?page=1&size=20&collections=OPERA``` returns no results currently.

**Comment by tiborsimko** [comment]
We don't store the "father" collections CMS in the record metadata.  We could, but what we discussed with @annatrz is to simply return `&experiment=OPERA` which will have the same effect...
