### ISSUE TITLE
templates: /about/CMS-Simulated-Dataset-Names

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1385]
Implement http://opendata.cern.ch/about/CMS-Simulated-Dataset-Names

- case 2 - Page
- might be implemented as a generic record (case 1) in the future; no detailed granularity in schema structure, content simply under content-key possibly as Markdown.

**Comment by tiborsimko** [comment]
Notice that http://0.0.0.0/about/cms-simulated-dataset-names exists... but the old URL does not reply.

I.e. we need just case sensitivity here 😄

**Comment by ioannistsanaktsidis** [comment]
This one needs to be implemented in ```nginx``` . cc @diegodelemos @tiborsimko.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko this is not a ui related issue. Could you pls move it to the corresponding milestone ?

**Comment by tiborsimko** [comment]
The template is done, the redirect will work once #1664 is merged, so I'm closing the issue.
