### ISSUE TITLE
templates: /about/CMS-Pileup-Simulation

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1386]
We have implemented https://opendata-dev.cern.ch/about/cms-pileup-simulation

but we need to also reply under the production-style case-sensitive URL http://opendatadev.cern.ch/about/CMS-Pileup-Simulation so that for the old URL will be valid after upgrade.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko this is not a ui related issue. Could you pls move it to the corresponding milestone ?

**Comment by hjhsalo** [comment]
Closing since PR #1747 should take care of this.
