### ISSUE TITLE
CMS: a script for extracting LHE headers from MC samples

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1398]
We would need the following script to be run on Open Data VM as soon as the MC datasets become available:
 
if the dataset has LHE step

- run: dumpLHEHeader.py input=file:afilefromthedataset.root output=thedataset.lhe

- copy the file thedataset.lhe in an appropriate place (it is some sort of configuration file, although not for CMSSW jobs)

@tiborsimko Can someone help me with this?

Josh will update the dumpLHEHeader.py script to correct the current malfunctioning

**Comment by heitorPB** [comment]
PR  #2432 contains information on how to run the script.

**Comment by heitorPB** [comment]
@katilp we still need this? #2432 is merged

**Comment by katilp** [comment]
@heitorPB I'll check if I can do it with the new instructions when out in qa and if OK then this can be closed.

**Comment by katilp** [comment]
Closing as the UL script is followed up elsewhere https://github.com/cernopendata/data-curation
