### ISSUE TITLE
Visualization files for Run2012[B,C]

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#1404]
Event display files must be produced for each of the Run2012B and Run2012C primary datasets. The primary datasets displayed will be:

- [x] BJetPlusX
- [x] BTag
- [x] DoubleElectron
- [x] DoubleMu
- [x] DoublePhoton
- [x] DoublePhotonHighPt
- [x] ElectronHad
- [x] HTMHTParked
- [x] HcalNZS
- [x] JetHT
- [x] JetMon
- [x] MET
- [x] MuEG
- [x] MuHad
- [x] MuOnia
- [ ] ~~MultiJet1Parked~~ (does not appear to be in release)
- [x] PhotonHad
- [x] SingleElectron
- [x] SingleMu
- [x] SinglePhoton
- [x] TauParked
- [x] TauPlusX
- [x] VBF1Parked
- [x] MinimumBias
- [x] NoBPTX
- [x] Commisioning

**Comment by katilp** [comment]
Would be nice also for MinimumBias, NoBPTX, Commisioning (to see the difference to the others).
For (some of) those you marked with question mark, see https://github.com/cernopendata/opendata.cern.ch/issues/1188#issuecomment-253178518

**Comment by katilp** [comment]
Take note of https://github.com/cernopendata/opendata.cern.ch/issues/1262 for the JSON file (and https://github.com/cernopendata/opendata.cern.ch/issues/1263#issuecomment-316003012 if condition data needed and if testing on Open data VM)

**Comment by tpmccauley** [comment]
Thanks for the information and clarification. I have updated my comment in this issue and will use it to track the progress.

**Comment by tpmccauley** [comment]
@katilp I can't seem to access the data from lxplus. Is it available yet? For example, if I want to dump the EDM content:

[mccauley@lxplus063 Analyzers]: edmDumpEventContent /store/data/Run2012B/Commissioning/AOD/22Jan2013-v1/30000/002C75D6-137C-E211-80F7-20CF305B050B.root
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_30/bin/slc6_amd64_gcc472/edmDumpEventContent", line 226, in <module>
    raise RuntimeError, "Could not open file '%s'." % filename
RuntimeError: Could not open file 'root://eoscms.cern.ch//eos/cms/store/data/Run2012B/Commissioning/AOD/22Jan2013-v1/30000/002C75D6-137C-E211-80F7-20CF305B050B.root'.

If I look on DAS this file does seem to have T3_CH_CERN_OpenData as one of the sites from which it is available:
<img width="841" alt="screen shot 2017-09-15 at 10 57 13 am" src="https://user-images.githubusercontent.com/496503/30477342-b3cd6a78-9a04-11e7-86ce-e2d13478f6ff.png">

**Comment by tpmccauley** [comment]
Ah, seems to be I was looking in wrong location (of course):
[mccauley@lxplus063 Analyzers]: edmDumpEventContent root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BJetPlusX/AOD/22Jan2013-v1/20000/00009852-3182-E211-A433-0026189438E9.root
works fine.

**Comment by katilp** [comment]
Right, DAS points to the upload area from which the files have been moved to their final open data location. But, indeed, we will need to delete the DAS entry in order to avoid errors. We'll see that with Tibor and Cristoph Wissing, we have had some preliminary email exchange on the topic

**Comment by tpmccauley** [comment]
I still need to check every file but they are here:

https://cms-docdb.cern.ch/cgi-bin/PublicDocDB//ShowDocument?docid=13402

for Run2012B primary datasets

**Comment by tpmccauley** [comment]
File for Run2012C are now in DocDB as well

**Comment by ArtemisLav** [comment]
I will start creating a JSON skeleton for all these based on the structure we already use for such records (e.g. http://opendata.cern.ch/record/630). Files and titles etc. will be taken care of at a second stage in a less manual way; right now, I would need updates (if applicable) for the information in sections `Description`, `Characteristics`, `System Details`, `How were these data selected?`, `How can you use these data?`, `Issues & Limitations`, `Collision Energy`, `Parent Dataset`, and `Author/s`. 

@tpmccauley if this information should not be the same across all records, please let me know.

**Comment by tpmccauley** [comment]
@ArtemisLav thanks.

Of course the `Parent Dataset`s are different for each and correspondingly so are the `Description`s. Otherwise everything else is the same for all the records.

**Comment by ArtemisLav** [comment]
@tpmccauley For the description, I meant the rest of the text (i.e. `Sample event set from ... primary dataset in json format readable from the browser-based 3d event display`); the dataset name will of course be different. 

So, if you are fine with how the previous event display records are, I will just copy the `Description`, `How were these data selected?`, `How can you use these data?` etc. from there.

However, if any sections need to be updated, e.g. `Global tag`, `Software release` or anything else, please leave me a note here.

**Comment by tiborsimko** [comment]
@tpmccauley @katilp Regarding the following two files:

```
DoubleMuParked_Run2012C_0.ig
DoubleMu_Run2012B_0.ig 
```

We only have DoubleMuParked AOD in the release, for both Run2012B and Run2012C. 

What about `DoubleMu_Run2012B_0.ig`? Is it meant for DoubleMuParked Run2010B? If so, should it be renamed? Or are we missing an IG file for this dataset?

**Comment by katilp** [comment]
Normally, DoubleMuParked contains the original DoubleMu in RAW that is why it is not rerecoed and we do not have AOD for DoubleMu. @tpmccauley Maybe check the names?

**Comment by tpmccauley** [comment]
Yes, it looks like there is an error in the name.

DoubleMu_Run2012B_0.ig -> DoubleMuParked_Run2012B_0.ig

**Comment by tiborsimko** [comment]
@tpmccauley Here is the record ID <-> IG file on EOS file correspondence:

```
7100 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BJetPlusX/IG/22Jan2013-v1/BJetPlusX_Run2012B_0.ig
7101 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/BTag/IG/22Jan2013-v1/BTag_Run2012B_0.ig
7102 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/Commissioning/IG/22Jan2013-v1/Commissioning_Run2012B_0.ig
7103 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/DoubleElectron/IG/22Jan2013-v1/DoubleElectron_Run2012B_0.ig
7104 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/DoubleMuParked/IG/22Jan2013-v1/DoubleMuParked_Run2012B_0.ig
7105 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/DoublePhoton/IG/22Jan2013-v1/DoublePhoton_Run2012B_0.ig
7106 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/DoublePhotonHighPt/IG/22Jan2013-v1/DoublePhotonHighPt_Run2012B_0.ig
7107 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/ElectronHad/IG/22Jan2013-v1/ElectronHad_Run2012B_0.ig
7108 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/HTMHTParked/IG/22Jan2013-v1/HTMHTParked_Run2012B_0.ig
7109 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/HcalNZS/IG/22Jan2013-v1/HcalNZS_Run2012B_0.ig
7110 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/JetHT/IG/22Jan2013-v1/JetHT_Run2012B_0.ig
7111 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/JetMon/IG/22Jan2013-v1/JetMon_Run2012B_0.ig
7112 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/MET/IG/22Jan2013-v1/MET_Run2012B_0.ig
7113 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/MinimumBias/IG/22Jan2013-v1/MinimumBias_Run2012B_0.ig
7114 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/MuEG/IG/22Jan2013-v1/MuEG_Run2012B_0.ig
7115 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/MuHad/IG/22Jan2013-v1/MuHad_Run2012B_0.ig
7116 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/MuOnia/IG/22Jan2013-v1/MuOnia_Run2012B_0.ig
7117 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/NoBPTX/IG/22Jan2013-v1/NoBPTX_Run2012B_0.ig
7118 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/PhotonHad/IG/22Jan2013-v1/PhotonHad_Run2012B_0.ig
7119 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/SingleElectron/IG/22Jan2013-v1/SingleElectron_Run2012B_0.ig
7120 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/SingleMu/IG/22Jan2013-v1/SingleMu_Run2012B_0.ig
7121 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/SinglePhoton/IG/22Jan2013-v1/SinglePhoton_Run2012B_0.ig
7122 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/TauParked/IG/22Jan2013-v1/TauParked_Run2012B_0.ig
7123 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/TauPlusX/IG/22Jan2013-v1/TauPlusX_Run2012B_0.ig
7124 root://eospublic.cern.ch//eos/opendata/cms/Run2012B/VBF1Parked/IG/22Jan2013-v1/VBF1Parked_Run2012B_0.ig
7125 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/BJetPlusX/IG/22Jan2013-v1/BJetPlusX_Run2012C_0.ig
7126 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/BTag/IG/22Jan2013-v1/BTag_Run2012C_0.ig
7127 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/Commissioning/IG/22Jan2013-v1/Commissioning_Run2012C_0.ig
7128 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/DoubleElectron/IG/22Jan2013-v1/DoubleElectron_Run2012C_0.ig
7129 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/DoubleMuParked/IG/22Jan2013-v1/DoubleMuParked_Run2012C_0.ig
7130 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/DoublePhoton/IG/22Jan2013-v2/DoublePhoton_Run2012C_0.ig
7131 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/DoublePhotonHighPt/IG/22Jan2013-v1/DoublePhotonHighPt_Run2012C_0.ig
7132 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/ElectronHad/IG/22Jan2013-v1/ElectronHad_Run2012C_0.ig
7133 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/HTMHTParked/IG/22Jan2013-v1/HTMHTParked_Run2012C_0.ig
7134 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/HcalNZS/IG/22Jan2013-v1/HcalNZS_Run2012C_0.ig
7135 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/JetHT/IG/22Jan2013-v1/JetHT_Run2012C_0.ig
7136 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/JetMon/IG/22Jan2013-v1/JetMon_Run2012C_0.ig
7137 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/MET/IG/22Jan2013-v1/MET_Run2012C_0.ig
7138 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/MinimumBias/IG/22Jan2013-v1/MinimumBias_Run2012C_0.ig
7139 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/MuEG/IG/22Jan2013-v1/MuEG_Run2012C_0.ig
7140 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/MuHad/IG/22Jan2013-v1/MuHad_Run2012C_0.ig
7141 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/MuOnia/IG/22Jan2013-v1/MuOnia_Run2012C_0.ig
7142 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/NoBPTX/IG/22Jan2013-v1/NoBPTX_Run2012C_0.ig
7143 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/PhotonHad/IG/22Jan2013-v1/PhotonHad_Run2012C_0.ig
7144 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/SingleElectron/IG/22Jan2013-v1/SingleElectron_Run2012C_0.ig
7145 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/SingleMu/IG/22Jan2013-v1/SingleMu_Run2012C_0.ig
7146 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/SinglePhoton/IG/22Jan2013-v1/SinglePhoton_Run2012C_0.ig
7147 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/TauParked/IG/22Jan2013-v1/TauParked_Run2012C_0.ig
7148 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/TauPlusX/IG/22Jan2013-v1/TauPlusX_Run2012C_0.ig
7149 root://eospublic.cern.ch//eos/opendata/cms/Run2012C/VBF1Parked/IG/22Jan2013-v1/VBF1Parked_Run2012C_0.ig

```

**Comment by tiborsimko** [comment]
@tpmccauley @katilp BTW please note that there is no IG file for `MuOniaParked`, only for `MuOnia`... I guess that's OK, similarly to `DoubleMu` and `DoubleMuParked`...
