### ISSUE TITLE
installation: invenio-rest[cors]

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1407]
After recent merging of probably record files #1357 (?), the COD3 site does not install anymore due to:

```
Successfully installed jinja2-cli-0.6.0 pyyaml-3.12
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/cernopendata/bin/cernopendata", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/invenio/.virtualenvs/cernopendata/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Flask-CORS>=2.1.0; extra == "cors"' distribution was not found and is required by invenio-rest
ERROR: Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1
```

We probably need explicit dependency on 'invenio-rest[cors]>=1.0.0b1' in `setup.py`.

CC @pamfilos @ioannistsanaktsidis Please have a look and amend (and please always check build before merging important changes!)

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko I don't understand why this happened since in my local installation and in travis ci there was no error. Any ideas  ?

**Comment by tiborsimko** [comment]
Perhaps you installed CORS manually? You can check `pip freeze`... Travis CI does not catch this kind of issues, because it does not run the full build, see `run-tests.sh`. But we should plug it soon, since it'll be useful for nighly deployments on OpenShift.

**Comment by tiborsimko** [comment]
> requirements-devel-cernopendata.txt 

These are only "optional" dependencies to be able to test the latest development versions of some core components... that was the only goal of "devel" requirements.  I.e. nothing needed for production. if we need something for production, then we should add it to regular dependencies in `setup.py`.

> -e git+https://github.com/pamfilos/invenio-files-rest.git@eos-storage#egg=invenio-files-rest
> -e git+https://github.com/pamfilos/invenio-xrootd.git@eos-storage#egg=invenio-xrootd

@pamfilos Please do the necessary PR to upstream Invenio repositories, we shouldn't depend on personal forks... 

For the speed of development, if we need to depend on some temporary package, then we should add it to `scripts/create-instance.sh` with a FIXME note, and later add it to `setup.py` when it's released upstream.

**Comment by pamfilos** [comment]
@tiborsimko necessary PRs for ```invenio-files-rest``` and ```invenio-xrootd``` need to be discussed with Invenio people on the implementation..for now I just added it in https://github.com/cernopendata/opendata.cern.ch/blob/master/requirements-devel-cernopendata.txt for speed, else files with EOS wouldn't play ( for the demo and rest..)

**Comment by diegodelemos** [comment]
I have started everything from scratch on http://opendata-dev.web.cern.ch/ and build failed with this error 💀 (since I have deleted previous deployments I have no backup 😓 so it will be down until we fix it). I have tried adding `pip install -r requirements-devel-cernopendata.txt` and it doesn't work:

```
 Could not find a version that satisfies the requirement pyxrootd (from xrootdpyfs>=0.1.2->invenio-xrootd->-r requirements-devel-cernopendata.txt (line 27)) (from versions: )
No matching distribution found for pyxrootd (from xrootdpyfs>=0.1.2->invenio-xrootd->-r requirements-devel-cernopendata.txt (line 27))
ERROR: Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1
```

Neither did it  with ` 'invenio-rest[cors]>=1.0.0b1'` explicit dependency on `setup.py`:
```
  Could not find a version that satisfies the requirement pyxrootd (from xrootdpyfs>=0.1.2->invenio-xrootd) (from versions: )
No matching distribution found for pyxrootd (from xrootdpyfs>=0.1.2->invenio-xrootd)
ERROR: Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1
```

quick fix?

**Comment by ioannistsanaktsidis** [comment]
You need to install python bindings for xrootd first
https://pythonhosted.org/xrootdpyfs/
and then it will be ok.

**Comment by tiborsimko** [comment]
@pamfilos As I mentioned above, I understand your motives, but `requirements-devel-cernopendata.txt` is not the right place for that... That one has been used solely for testing "devel" level dependencies for Travis CI.   (and is not even in the game anymore after COD3 modules were centralised into the single repository)

OK, I'll fix the build, but please prepare the two XRootD-related PRs in the meantime for upstream integration, so that we can start things moving.

**Comment by tiborsimko** [comment]
Fixed except for https://github.com/cernopendata/opendata.cern.ch/pull/1357/files#r139068861. I'll clean the branch and make PR later this morning...
