### ISSUE TITLE
Visualization of Higgs candidates in Run2012 datasets

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#1410]
There are many Higgs candidate events which have been noted and documented that exist in the Run2012 public datasets. It would be nice to extract them into event display files for visualization. Some of the events (Htautau) have already been extracted in the course of usual event display production:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/Hig13004PubTWiki#Event_Display

There are varied and rich event topologies available in:

- [ ] Hbb
- [ ] Htautau
- [ ] HWW
- [ ] HZZ
- [ ] Hgammagamma

**Comment by tpmccauley** [comment]
I will have H to 4l candidate events ready sometime today (2 more to find). They will be ones that pass the selections in the analysis example. I will paste a json file for the record similar to http://opendata-dev.web.cern.ch/record/300

**Comment by tpmccauley** [comment]
{
    "files": [
        {
            "checksum": "",
            "uri": "Hto4l_Run2012.ig",
            "size":
        },
        {
            "checksum": "",
            "uri": "Hto4l_Run2012.csv",
            "size":
        }
    ],
    "accelerator": "CERN-LHC", 
    "abstract": {
        "description": "This document contains Higgs candidate events (with an invariant mass between 120-130 GeV) that pass the selections found in the example Higgs-to-four-lepton analysis of CMS public data"
    },
    "authors": [
        {
            "name": "McCauley, Thomas"
        }
    ],
    "date_published": "2017",
    "run_period": "Run2012",
    "publisher": "CERN Open Data Portal",
    "doi": "",
    "license": {
        "attribution": "CC0"
    },
    "title": "Higgs candidate events from Run2012 selected in the Higgs-to-four-lepton analysis example",
    "control_number": "300",
    "note": {
        "description": "These data were selected for use in education and outreach and contain a subset of the total event information. They are not suitable for a full physics analysis."
    },
    "methodology": {
        "description": "These events were selected in the example Higgs-to-four-lepton analysis of CMS public data"
    },
    "experiment": "CMS",
    "collections": [
        "CMS-Derived-Datasets"
    ],
    "usage": {
        "description": " <p>Files with the extension .ig are JSON files containing information suitable for visual display. The data can be accessed from the file menu of <a href=\"/visualise/events/CMS\">the online event display</a>. Comma-separated value (csv) files can be used in online applications such as <a href=\"/visualise/histograms/CMS\">the histogram visualizer</a> and other applications, examples are given in</p> ",
        "links": [
            {
                "recid": "5101"
            },
            {
                "recid": "5102"
            },
            {
                "recid": "5100"
            }
        ]
    },
    "recid": "300",
    "distribution": {
        "formats": [
            "csv",
            "ig",
            "json"
        ]
    },
    "validation": {
        "description": "These events were selected in the example Higgs-to-four-lepton analysis of CMS public data"
    },
    "type": {
        "primary": "Dataset",
        "secondary": [
            "Derived"
        ]
    }
}

**Comment by tpmccauley** [comment]
The event display file is here:
https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=13424&filename=H4l_Run2012_0.ig&version=2

**Comment by tpmccauley** [comment]
I have collected all of the events from 2011 and 2012 from http://opendata.cern.ch/record/5500 in csv and event display format. They are all here: https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/ShowDocument?docid=13424

**Comment by tpmccauley** [comment]
A new json file with metadat suitable to create a new record for the portal is needed. I can create one. Then what additional steps are needed to create a new record?

**Comment by katilp** [comment]
Thanks, that should be all, I've added this to the next release milestone (ML), assigning to @ArtemisLav and to @tiborsimko for further steps

**Comment by tpmccauley** [comment]
Besides the changes to the file names, the required changes to the json file are below:

"abstract": {
"description": "This document contains Higgs candidate events that pass the selections found in the example Higgs-to-four-lepton analysis of CMS public data"
}

"links": [
{"recid": "5101"},
{"recid": "5102"},
{"recid": "5100"},
{"recid": "5500"}
]

"run_period": "Run2012", "Run2011"  _Does the format support more than one run_period?_

**Comment by ArtemisLav** [comment]
> 
> "run_period": "Run2012", "Run2011" _Does the format support more than one run_period?_

@tpmccauley It's currently a string in the data model, but in the past we've done it like this:  "run_period": "Run2012B-Run2012C"

**Comment by tpmccauley** [comment]
@ArtemisLav got it. In that case, it should be "Run2011A-Run2012B-Run2012C"

**Comment by tiborsimko** [comment]
@tpmccauley @katilp Which files from CMS Document 13424-v4 would you like to attach? Under which `/eos/opendata/cms/...` directory to attach them?

**Comment by tpmccauley** [comment]
@tiborsimko I believe all of them. In fact, I just changed one of the ig file names in the record so that it conforms with the others. It's now Hto4l_120-130GeV.ig

**Comment by ArtemisLav** [comment]
@tpmccauley do you have an ORCID iD I could add to this record (as well as to all other records with your name as a next step)?

**Comment by tpmccauley** [comment]
0000-0001-6589-8286

**Comment by tiborsimko** [comment]
@katilp @tpmccauley What would be a good EOS directory name to host these files?  Shall we go for `derived-data/...`? If so, we'd need the tool that generated them ideally... In any case, we'll need to invent a good directory name that would describe them all under the same umbrella name. (The last time we used `masterclass-2014` so that's another option if they are being used that way...)

**Comment by tpmccauley** [comment]
@tiborsimko `masterclass-2014` or something like it implies that the files are used for a specific purpose, like masterclasses. These files are meant to be of general interest (which is not to say they won't find specific purposes later). I think then that `derived-data` would be fine. For me anyway.

**Comment by tiborsimko** [comment]
Sure, but what name to use under `derived-data` to describe this dataset?

```
/eos/opendata/cms/derived-data/.../2e2mu_2011.csv
/eos/opendata/cms/derived-data/.../Hto4l_120-130GeV.ig 
...
```

I.e. what string to use for `...` directory placeholder in a way that would nicely express the nature of this dataset collection and that would be nicely evolutive for possible other datasets like this to come in the future? That was the core of the question :wink:

**Comment by tpmccauley** [comment]
Just `higgs`? I can imagine as more data are released that we would have more under this category. Or `physics-candidates/higgs` where we might add other types of event candidates e.g. `physics-candidates/ttHbb` (to give a recent example of some event displays I made this week)?

**Comment by tiborsimko** [comment]
It should still have a unique ID underneath to be friendly to future updates. If there is nothing better, we could use DocDB ID for example:

```
/eos/opendata/cms/derived-data/run2-physics-candidates/higgs/13424-v5/2e2mu_2011.csv
/eos/opendata/cms/derived-data/run2-physics-candidates/higgs/13424-v5/Hto4l_120-130GeV.ig 
```

**Comment by tpmccauley** [comment]
Sounds good to me

**Comment by tiborsimko** [comment]
@tpmccauley Thanks, I attached all the files there, please check out the record on DEV: http://opendata-dev.cern.ch/record/5200 

- If you'd like to amend anything in the text, please make a PR.

- It would be good if you could get to documenting various eta1, eta2 columns for the general public.  This can be done via `dataset_semantics` field, see the old issue https://github.com/cernopendata/opendata.cern.ch/issues/728 and see how to do it for the forthcoming ML samples, e.g. http://opendata-dev.cern.ch/record/12100
