### ISSUE TITLE
templates: nice record page for datasets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1417]
Following up #1415, modify the detailed record template page to show more fields for the `dataset` data type.

The template to edit is `cernopendata/templates/cernopendata_records_ui/records/detail.html`.

CMS dataset example:
- COD2: http://opendata.cern.ch/record/15
- COD3: http://0.0.0.0/records/15

OPERA dataset example:
- COD2: http://opendatadev.cern.ch/record/3900 
- COD3: http://0.0.0.0/records/3900

OPERA event example:
- COD2: http://opendatadev.cern.ch/record/4003
- COD3: http://0.0.0.0/records/4003

Add missing fields to the display.

Remember to be conditional (if `foo.bar exists, show it) for safety when the data model might change.

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.

**Comment by tiborsimko** [comment]
Don't close the issue too soon, the `master` branch does not have it yet. COD2 and COD3 pages should expose the same amount of information, while they are very different in `master`...

**Comment by ioannistsanaktsidis** [comment]
I made a PR for this one, it adds most of the information. Some of the info needs to be amended as there are some inconsistencies in the schema. We can amend later the rest of them. For now we can proceed by merging #1449.

**Comment by tiborsimko** [comment]
There's also the file download box trouble spotted by @katilp.  The current look mixes file indexes and dataset files in the same list:

![z](https://user-images.githubusercontent.com/517546/30858248-2757aa0e-a2bf-11e7-8190-e2c0df739cbc.png)

Based on the file `type` field, the indexes should be displayed first and in a separate section from the rest of the dataset files; see the layout in COD2:

- http://opendata.cern.ch/record/15

**Comment by tiborsimko** [comment]
> Based on the file `type` field [...]

@pamfilos Please see the `"type": "index"` labelling of those files in fixtures:

```console
$ grep index cernopendata/modules/fixtures/data/datasets/cms-2011-collision-datasets.json  
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2011A/BTag/AOD/12Oct2013-v1/file-indexes/CMS_Run2011A_BTag_AOD_12Oct2013-v1_00000_file_index.txt",
            "type": "index",
            "description": "BTag AOD dataset file index (1 of 2) for access to data via CMS virtual machine",
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2011A/BTag/AOD/12Oct2013-v1/file-indexes/CMS_Run2011A_BTag_AOD_12Oct2013-v1_20000_file_index.txt",
            "type": "index",
            "description": "BTag AOD dataset file index (2 of 2) for access to data via CMS virtual machine",
```

**Comment by tiborsimko** [comment]
@pamfilos Do we now have access to files' metadata tags such as `type` or is this still an issue? If so, let's reference the upstream Invenio ticket here...

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented. The remaining issues have moved accordingly.
