### ISSUE TITLE
template: prettify home page

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1419]
Prettify home page a bit.

Introduce different images for carousel news items. Display more news items instead of the carousel(?)

For the visualise part, do not show experiment logos there, but rather take actual event display screenshots:

- for CMS: take image from https://github.com/cms-outreach/ispy-webgl
- for OPERA: take one track image from http://0.0.0.0/visualise/events/OPERA/10125032322

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.

**Comment by tiborsimko** [comment]
Please use `(closes #123)` directive in the commit log messages for nicer housekeeping...
