### ISSUE TITLE
records: /dataset/<doi>

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1421]
Following up #1415, the dataset records are exposed using record IDs.

We thought of exposing `/dataset/<doi>` as the canonical URLs here, since we shall be minting DOIs for all datasets, even small derived ones.

If we do go for it, then we need a new PID fetcher/minter/etc...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko Could you please update dataset records to include dois so as to push my PR ? Otherwise we can't proceed with this issue.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko sorry for the comment seems like all records have a doi, I had made a mistake in my PR thats why I couldn't realise it.
