### ISSUE TITLE
facets: prettify "experiment" analysers

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1422]
Prettify "experiment" facet analysers, because some values are shown in lowercase:

![foo](https://user-images.githubusercontent.com/517546/30584070-ec8cfb36-9d28-11e7-9a0b-2faa2d620cbb.png)

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.

**Comment by tiborsimko** [comment]
Closed by https://github.com/cernopendata/opendata.cern.ch/pull/1435/commits/d111704f95b532060d1800b8ffdff83cfae89fa9 in #1435.

Please always use `(closes #123)` directive in the commit log message so that we can track issue/code relations. If you need to close something manually, then please cite the commit SHA1 and/or the PR number.  These are good housekeeping practices that may come handy for potential later refactoring and other bisecting...
