### ISSUE TITLE
templates: nicer brief display for "articles"

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1427]
Prettify brief display for "articles". Currently we are showing source "as is", see below.

If the body is in HTML, show it. If the body is in Markdown, intepret it.  

Also, hide "Show source" link which is not good to offer in the brief display.  (It'll be there in the detailed display, and persons interested in getting JSON out of searches will use REST API anyway.)

![a1](https://user-images.githubusercontent.com/517546/30586063-098a4f3a-9d2f-11e7-8975-c332c0cf078f.png)

**Comment by ioannistsanaktsidis** [comment]
2 options for this one. Either we install ```angular-markdown``` library or we can add a short description  in the records which will not contain markdown, just some text for the brief results. 
I prefer option n.2 . cc @tiborsimko

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented in the new-ui

**Comment by tiborsimko** [comment]
The issue is still there:

 - http://opendata-dev.web.cern.ch/search?q=cms%20releases

**Comment by ioannistsanaktsidis** [comment]
@hjhsalo  please take care alongside with the mathjax issue. They can go together.

**Comment by katilp** [comment]
Markdown in brief display still does not reneder

![md](https://user-images.githubusercontent.com/5859918/33257290-f9921baa-d355-11e7-9b1c-7171e9a9085e.PNG)

**Comment by pamfilos** [comment]
IMHO we should either remove description of a "markdown" record, or just add a short description (which we want to show on search briefs) in the ```short_description``` field that is already created, else I am afraid there will be ugly UI problems

**Comment by RaoOfPhysics** [comment]
@pamfilos: Agree. No reason to have hyperlinks etc. appear in the short description.

Also makes sense to have a tailored description than a generic cropping of existing text. A bit of work, but worth it, IMHO.

**Comment by tiborsimko** [comment]
Let's create a new issues then; this one is from the past sprint that fixed the HTML preview, which was a more visible problem.
