### ISSUE TITLE
templates: better navtrail for visualise events

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1436]
Visualise events navtrail is kind of empty, directly attached to root, while it could show parent tree for CMS and OPERA.

![z](https://user-images.githubusercontent.com/517546/30590416-c4b7f1f4-9d3e-11e7-8d65-2fb0b41f5f23.png)

**Comment by ioannistsanaktsidis** [comment]
Closing as superseded from #1675.
