### ISSUE TITLE
testsuite: populate `experiment` field (`693`)

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#145]
As discussed elsewhere https://github.com/cernopendata/opendata.cern.ch/issues/112#issuecomment-55096661, the testsuite demo records should be all populated with appropriate experiment field looking like:

```
<datafield tag="693" ind1=" " ind2=" ">
  <subfield code="a">CERN-LHC</subfield>
  <subfield code="e">CMS</subfield>
</datafield>
```

**Comment by pherterich** [comment]
@tiborsimko Is there a smart way to check if I have added it to all of the records and this issue can be closed?

**Comment by tiborsimko** [comment]
@pherterich If you check out the source code on your laptop, then one technique is to use "git grep" to count the number of MARC tags 001 (hence records) and the number of MARC tags 693 (assuming there is only one per record):

```console
$ git grep '"001"' invenio_opendata/testsuite/data/ | wc -l
98
$ git grep '"693"' invenio_opendata/testsuite/data/ | wc -l                                        
87
```

Seems like there are 9 records missing this field.  

To discover which records are these, you can grep file by file for 001 and 693 tags like this:

```console
$ find invenio_opendata/testsuite/data/ -type f -exec grep -E '"001"|"693"' {} \;
```

Expected output is 001 and 693 after each other:

```console
    <controlfield tag="001">1</controlfield>
    <datafield tag="693" ind1=" " ind2=" ">
```

Unexpected output is 001 alone:

```console
    <controlfield tag="001">320</controlfield>
    <controlfield tag="001">321</controlfield>
    <controlfield tag="001">322</controlfield>
    <controlfield tag="001">323</controlfield>
    <controlfield tag="001">324</controlfield>
    <controlfield tag="001">325</controlfield>
    <controlfield tag="001">611</controlfield>
    <controlfield tag="001">612</controlfield>
    <controlfield tag="001">613</controlfield>
```

Hence it seems that you need to touch these 9 records.
