### ISSUE TITLE
templates: improve download warning behaviour

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1451]
Following up on #1437 it seems that PR #1445 does not fix everything.  Let's take OPERA dataset as an example:

- The warning is shown even for small files such as http://opendata-dev.web.cern.ch/datasets/4007. We should improve the download time math estimates, otherwise it looks weird. (See below.) Or we can simply have a threshold and display the warning for "big" files only.

- The warning mentions to use of CMS VM, which is applicable only to ROOT files and only to CMS primary datasets.  It should not be shown for CSV datasets.

- The download functionality itself works fine, but the warning modal window does not disappear for me even after the download was successfully finished.

![z](https://user-images.githubusercontent.com/517546/30850234-22757468-a2a5-11e7-9cb2-207a70786008.png)

**Comment by ioannistsanaktsidis** [comment]
>  Or we can simply have a threshold and display the warning for "big" files only.
@tiborsimko is it ok if I put the threshold bigger than 1gb ?

**Comment by ioannistsanaktsidis** [comment]
> The download functionality itself works fine, but the warning modal window does not disappear for me even after the download was successfully finished.

All the bullets are addressed in the pending PR except this one which seems to be a bit tricky. I created  a separate ticket for that.
