### ISSUE TITLE
templates: file list pagination

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1453]
When a dataset contains many files, such as for the following record:

- COD2: http://opendata.cern.ch/record/15
- COD3: http://opendata-dev.web.cern.ch/records/15

The dataset files should be displayed in a paginated manner, say a5 by 5, in order to reduce page height. Compare the behaviour of COD2 and COD3 pages.

See also a somewhat related issue about separating file indexes from dataset files (base on "file type") and presenting them in a different box:  

- https://github.com/cernopendata/opendata.cern.ch/issues/1417#issuecomment-332170718

**Comment by katilp** [comment]
Any news on this (and  #1519)?

**Comment by ioannistsanaktsidis** [comment]
This might need a reimplementation of the files system. It is not considered only as part of this Sprint. Will move it to COD3-UI so as to address it in the next phase.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in previous PRs.
