### ISSUE TITLE
search: introduce "condensed" format

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1465]
As discussed with @katilp @RaoOfPhysics, it would be useful to offer on search pages (1) a choice of output formats to the user (=brief, detailed, etc); (2) introduce a very condensed format that would display only the dataset titles.

Use case: somebody would search through CMS datasets, choose this and that facet category, and want to see ~600 items per page to quickly scan through the entire results set as it if affected by the facet choice.

**Comment by katilp** [comment]
The condensed view is nice, thanks!
Some remarks:

- can the empty line (or the white space between the entries) be removed?
- can we offer an option for number of entries per page (and show all)?
- can we offer an option to dump the output to a file (although copy-paste works as well...)?

The use case behind this is the need for a user to get a quick overview of what is a available (needed for example for O(1000) of MC entries from CMS).

**Comment by ioannistsanaktsidis** [comment]
@katilp yes all that can be done :)

**Comment by tiborsimko** [comment]
We can introduce two new selection boxes WRT choosing format (condensed, default) and WRT choosing hits per page (25,50,100...) next to the "Sort by" option.

To display ~600 items per page was indeed the target of this issue, see the original description. However, we should make sure to measure performance, in case ~3000 users will start simultaneously displaying pages ~1000 items long 😄 . For CDS and INSPIRE, only "priviledged" users were allowed to do this; for COD, we don't have any user accounts yet. (and it's better if we don't have to introduce them yet)

The output should be definitely condensed more, but the copy-pasting technique would be probably enough than offering text file download...
