### ISSUE TITLE
glossary: tooltip for underlined glossary terms 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1469]
The glossary terms are well underlined, but no help text tooltip is displayed.  For example, on the page http://opendata-dev.web.cern.ch/about/cms, hovering over the underlined "Muon" text should show a tooltip with an explanatory text about muon. (and perhaps even offer link to http://opendata-dev.web.cern.ch/glossary/muon). Compare the behaviour with http://opendata.cern.ch/about/CMS.

![z](https://user-images.githubusercontent.com/517546/31165085-f48c9bb2-a8e9-11e7-9ce4-8d857059bac9.png)

**Comment by tiborsimko** [comment]
See also #1521 that is related if you take up glossary tooltip display within this milestone...

**Comment by ioannistsanaktsidis** [comment]
Moving this to COD3-UI as I want to check it a bit after we have a stable version in dev.
