### ISSUE TITLE
CMS 2012 primary dataset records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1470]
Information needed for the 2012 dataset records:

- Collision energy: 8 TeV
- Description: 
   -  NNN primary dataset in AOD format from RunB of 2012. Run period from run number 193833 to 196531.
   - NNN  primary dataset in AOD format from RunC of 2012. Run period from run number 198022 to 203742. 
- Characteristcs: n events, n files, N TB in total (from DAS)
- System details - as 2011 records i.e.:
    - Global tag: FT_53_LV5_AN1
    - Recommended release for analysis: CMSSW_5_3_32
- How were these data selected
   - general description - to be provided
   - Data taking/ HLT - link to a new record see #1189 and #1870
   - Data processing / RECO - to be extracted from DAS
   - Possible trigger paths - see #1189#issuecomment-259430837 (and https://fwyzard.web.cern.ch/fwyzard/hlt/2012/dataset)
- How were there data validated - as 2011 records
- How can you use these data - as 2011 records
- Issues & limitations
  - This dataset contains all runs from 2012 RunB/RunC. The list of validated runs, which must be applied to all analyses, can be found in (link to a new record, see #1262)

**Comment by katilp** [comment]
@ArtemisLav How do we proceed with building these records? To provide the general description, it would be very helpful if they were available on the dev portal  with the trigger paths so that I can ask someone to help with the description.   @tiborsimko How do you prefer? It certainly takes several days to iterate (simply for the one day feedback delay for the build) so we start to be in a hurry with them for Monday Dec 4)

**Comment by katilp** [comment]
@tiborsimko Do you get the n_events from CMSDAS ny script for these? @caredg wil provide the brief description early next week.

**Comment by tiborsimko** [comment]
@katilp Yes, I get it from DAS.  For example, for `/VBF1Parked/Run2012C-22Jan2013-v1/AOD`, I see:

- "size": 68900769145577,
- "num_lumi": 91685,
- "num_file": 18817,
- "nlumis": 91685,
- "nfiles": 18817,
- "nevents": 241571212,
- "nblocks": 65,

**Comment by tiborsimko** [comment]
@ArtemisLav Would you have 52 pre-reserved DOIs that I could use for the generated records?

**Comment by ArtemisLav** [comment]
@tiborsimko sure; however, as far as I know, the solution @annatrz implemented should allow us to generate unique, random DOIs automatically.

**Comment by tiborsimko** [comment]
@katilp There is a problem with one dataset `/DoublePhoton/Run2012C-22Jan2013-v1/AOD` where DAS returns nblocks 5 but otherwise everything else (size, nfiles, nevents) is 0.  Can you please have a look?

**Comment by tiborsimko** [comment]
@ArtemisLav OK but then we should leave DOI minting for the very end, since we are still amending data programmatically... We'd need to have DOIs in the fixtures to ensure they always go to the same record.

**Comment by katilp** [comment]
@tiborsimko I'm checking that, it is indeed marked "invalid" in DAS and it has no other reprocessing available. It does have a parent RAW, but it is not impossible that it is overlapping with another dataset. I'm investigating further.

**Comment by katilp** [comment]
Looks OK, Photon dataset has all the triggers as DoublePhoton apart from
HLT_Photon26_R9Id85_OR_CaloId10_Iso50_Photon18_R9Id85_OR_CaloId10_Iso50_Mass70
HLT_Photon36_R9Id85_OR_CaloId10_Iso50_Photon10_R9Id85_OR_CaloId10_Iso50_Mass80

For these triggers (from http://fwyzard.web.cern.ch/fwyzard/hlt/2012/summary)

Path HLT_Photon36_R9Id85_OR_CaloId10_Iso50_Photon10_R9Id85_OR_CaloId10_Iso50_Mass80:(DoublePhoton dataset)
 - first seen online on run 203777 (/cdaq/physics/Run2012/8e33/v1.0/HLT/V2)
 - last  seen online on run 209151 (/cdaq/special/25ns/v1.1/HLT/V2)
 - V1: (runs 203777 - 209151) seeded by: L1_SingleEG22
is used outside of RunC: 198022 to 203742.

Remains only:

Path HLT_Photon26_R9Id85_OR_CaloId10_Iso50_Photon18_R9Id85_OR_CaloId10_Iso50_Mass70 (DoublePhoton dataset)
 - first seen online on run 194270 (/cdaq/physics/Run2012/7e33/v2.2/HLT/V2)
 - last  seen online on run 209151 (/cdaq/special/25ns/v1.1/HLT/V2)
 - V1: (runs 194270 - 196531) seeded by: L1_DoubleEG_13_7
 - V2: (runs 198022 - 209151) seeded by: L1_DoubleEG_13_7

I'll check, this trigger probably overlaps with another one in Photon dataset.

**Comment by katilp** [comment]
Checking further: there's no Photon dataset in RunC, just SinglePhoton and DoublePhoton (see also RAW: dataset=/*Photon/Run2012C*/RAW)

**Comment by katilp** [comment]
@tiborsimko OK, now it is clear: DoublePhoton it is V2 on DAS, so please check: 
dataset=/DoublePhoton/Run2012C-22Jan2013-v2/AOD
https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDoublePhoton%2FRun2012C-22Jan2013-v2%2FAOD&instance=prod%2Fglobal

Dataset size: 10.7TB, Number of blocks: 18, Number of events: 41564679, Number of files: 2719

**Comment by tiborsimko** [comment]
@katilp Oh, indeed, thanks! I'll fix the given record.

**Comment by katilp** [comment]
For reco configs, explicitly checked on 6 first datasets on this list that "RECO" config file of AOD is identical to one of the config files of RAW.
As provenance, take "RECO" config file of AOD (the file name chosen based on the commented 1st line = the file name as in the script with which the config file was generated)

- [ ] /BJetPlusX/Run2012B-22Jan2013-v1/AOD /tmp/x509up_u5073 https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21c0826/configFile > reco_2012B_BJetPlusX.py
- [ ] /BTag/Run2012B-22Jan2013-v1/AOD  https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb223e9be/configFile > reco_2012B_BTag.py
- [ ] /Commissioning/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb27eb3f6/configFile > reco_2012B_Commissioning.py
- [ ] /DoubleElectron/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2782e7a/configFile > reco_2012B_DoubleElectron.py
- [ ] /DoubleMuParked/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21f80b3/configFile > reco_2012B_DoubleMuParked.py
- [ ] /DoublePhoton/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2472c59/configFile > reco_2012B_DoublePhoton.py
- [ ] /DoublePhotonHighPt/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb20d293b/configFile > reco_2012B_DoublePhotonHighPt.py
- [ ] /ElectronHad/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23bf815/configFile > reco_2012B_ElectronHad.py
- [ ] /HTMHTParked/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb265fc2d/configFile > reco_2012B_HTMHTParked.py
- [ ] /HcalNZS/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23dceac/configFile > reco_2012B_HcalNZS.py
- [ ] /JetHT/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb25d129f/configFile > reco_2012B_JetHT.py
- [ ] /JetMon/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21d935e/configFile > reco_2012B_JetMon.py
- [ ] /MET/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2a6644f/configFile > reco_2012B_MET.py
- [ ] /MinimumBias/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2592509/configFile > reco_2012B_MinimumBias.py
- [ ] /MuEG/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23eab78/configFile > reco_2012B_MuEG.py
- [ ] /MuHad/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2651ee2/configFile > reco_2012B_MuHad.py
- [ ] /MuOnia/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2b4a98f/configFile > reco_2012B_MuOnia.py
- [ ] /MuOniaParked/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21dde62/configFile > reco_2012B_MuOniaParked.py
- [ ] /NoBPTX/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb220b96c/configFile > reco_2012B_NoBPTX.py
- [ ] /PhotonHad/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb24cf31c/configFile > reco_2012B_PhotonHad.py
- [ ] /SingleElectron/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb273b491/configFile > reco_2012B_SingleElectron.py
- [ ] /SingleMu/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2ac926d/configFile > reco_2012B_SingleMu.py
- [ ] /SinglePhoton/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21e6fc8/configFile > reco_2012B_SinglePhoton.py
- [ ] /TauParked/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23e3b63/configFile > reco_2012B_TauParked.py
- [ ] /TauPlusX/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23d10a9/configFile > reco_2012B_TauPlusX.py
- [ ] /VBF1Parked/Run2012B-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23ca8c6/configFile > reco_2012B_VBF1Parked.py

These RECO configs for 2012B are in /afs/cern.ch/user/k/kati/public/reco_2012B

**Comment by katilp** [comment]
- /MET/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23731f6/configFile > reco_2012C_MET.py
- /MuEG/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb293c54c/configFile > reco_2012C_MuEG.py
- /MuHad/Run2012C-22Jan2013-v1/AOD  https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb213667e/configFile > reco_2012C_MuHad.py
- /MuOnia/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/707dcf6bbc0fa1fbfd17bc48c8da1b7e/configFile > reco_2012C_MuOnia.py
- /MuOniaParked/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb24096a6/configFile > reco_2012C_MuOniaParked.py
- /NoBPTX/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2220120/configFile > reco_2012C_NoBPTX.py
- /PhotonHad/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23feadc/configFile > reco_2012C_PhotonHad.py
- /SingleElectron/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2284920/configFile > reco_2012C_SingleElectron.py
- /SingleMu/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb26492a3/configFile > reco_2012C_SingleMu.py
- /SinglePhoton/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2b45f86/configFile > reco_2012C_SinglePhoton.py
- /TauParked/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb21755b3/configFile > reco_2012C_TauParked.py
- /TauPlusX/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2679423/configFile > reco_2012C_TauPlusX.py
- /VBF1Parked/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/855e1f94a0e0449d5bc49d737e53b481/configFile > reco_2012C_VBF1Parked.py
- /MinimumBias/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb264c4b5/configFile > reco_2012C_MinimumBias.py
- /BJetPlusX/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2787aac/configFile > reco_2012C_BJetPlusX.py
- /BTag/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb25664c8/configFile > reco_2012C_BTag.py
- /Commissioning/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb269a4f2/configFile > reco_2012C_Commissioning.py
- /DoubleElectron/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb22131a4/configFile > reco_2012C_DoubleElectron.py
- /DoubleMuParked/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb213fe5b/configFile > reco_2012C_DoubleMuParked.py
- /DoublePhoton/Run2012C-22Jan2013-v2/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2204515/configFile > reco_2012C_DoublePhoton.py
- /DoublePhotonHighPt/Run2012C-22Jan2013-v1/AOD  https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2b74499/configFile > reco_2012C_DoublePhotonHighPt.py
- /ElectronHad/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb23f74d9/configFile > reco_2012C_ElectronHad.py
- /HTMHTParked/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2218187/configFile > reco_2012C_HTMHTParked.py
- /HcalNZS/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb249fcc8/configFile > reco_2012C_HcalNZS.py
- /JetHT/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb24e72d8/configFile > reco_2012C_JetHT.py
- /JetMon/Run2012C-22Jan2013-v1/AOD https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/2f7942d681da6a0f0f7cbc8eb2436b39/configFile > reco_2012C_JetMon.py

These RECO configs for 2012C are in /afs/cern.ch/user/k/kati/public/reco_2012C
