### ISSUE TITLE
CMS: suggestion for additional search tags for MC

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1472]
Suggestions for additional search tags for MC

Drell-Yan (search DY*)
/DY1JetsToLL_M-10To50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DY1JetsToLL_M-50_8TeV_ext-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DY2JetsToLL_M-50_8TeV_ext-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DY2JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DY3JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DY4JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DYJetsToLL_M-10to50_HT-200to400_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYJetsToLL_M-10to50_HT-400toInf_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYJetsToLL_M10-50_PtZ-100_TuneZ2star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYJetsToLL_M10-50_PtZ70-100_TuneZ2star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball-tauola-tauPolarOff/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-No_PU_RD1_START53_V7N-v1/AODSIM
/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DYJets_0p0_1p2_2p10_3p15_4p15_CT10_8TeV-sherpa/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-ExtFlat10_PU_RD1_START53_V7N-v1/AODSIM
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-ExtFlat20_PU_RD1_START53_V7N-v1/AODSIM
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-ExtFlat30_PU_RD1_START53_V7N-v1/AODSIM
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-NewG4Phys_PU_RD1_START53_V7N-v1/AODSIM
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v3/AODSIM
/DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-15To50_TuneZ2star_8TeV-pythia6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/DYToMuMu_M-15To50_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-20_CT10_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DYToMuMu_M-6To15_Tune4C_8TeV-pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/DYToMuMu_M-6To15_Tune4C_8TeV-pythia8/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/DYToMuMu_M-6To15_TuneZ2star_8TeV-pythia6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/DYToMuMu_M-6To15_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

Di-photon (DiPhoton* Diphoton*)

/DiPhotonBorn_Pt-10To25_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v2/AODSIM
/DiPhotonBorn_Pt-250ToInf_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonBorn_Pt-250ToInf_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v2/AODSIM
/DiPhotonBorn_Pt-25To250_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonBorn_Pt-25To250_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v2/AODSIM
/DiPhotonBox_Pt-10To25_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonBox_Pt-250ToInf_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonBox_Pt-25To250_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v2/AODSIM
/Diphoton2Jets_EW4_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonJetsBox_M60_8TeV-sherpa/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonJets_7TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonJets_8TeV-madgraph-tarball-v2/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/DiPhotonJets_M0_8TeV-madgraph/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM

Photon-jet (GJet*)
/GJet_M80_doubleEMEnriched_8TeV-sherpa/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/GJet_Pt-20to40_doubleEMEnriched_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/GJet_Pt40_doubleEMEnriched_TuneZ2star_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/GJet_Pt40_doubleEMEnriched_TuneZ2star_8TeV_ext2-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/GJets_HT-100To200_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/GJets_HT-40To100_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

QCD (QCD*)
/QCD4Jets_Pt-100to180_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD4Jets_Pt-180to250_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD4Jets_Pt-250to400_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD4Jets_Pt-400to5600_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD6Jets_Pt-100to180_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD6Jets_Pt-180to250_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD6Jets_Pt-250to400_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD6Jets_Pt-400to5600_TuneZ2Star_8TeV-alpgen/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD_Pt-1000_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt-15to3000_Tune4C_Flat_8TeV_pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt-15to3000_TuneZ2star_Flat_8TeV_pythia6/Summer12_DR53X-NoPileUp_START53_V7N-v1/AODSIM
/QCD_Pt-15to3000_TuneZ2star_Flat_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt-300to470_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt-30to40_doubleEMEnriched_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt-40_doubleEMEnriched_TuneZ2star_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt-470to600_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt-600to800_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt-800to1000_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_120to170_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_15to30_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_170_250_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt_170to300_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_20_MuEnrichedPt_15_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
/QCD_Pt_250_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v4/AODSIM
/QCD_Pt_30_80_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt_30to50_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM
/QCD_Pt_50to80_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v3/AODSIM
/QCD_Pt_80to120_CTEQ6L1_8TeV_herwig6/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM

etc to be continued...

**Comment by tiborsimko** [comment]
We can try to automatise this together with the task of parsing MC names to extract processes and final state particles...

**Comment by tiborsimko** [comment]
This can be addressed as part of #1676.

**Comment by katilp** [comment]
This is now implemented in https://github.com/cernopendata/data-curation/blob/master/cms-YYYY-simulated-datasets/code/categorisation.py

Any necessary updates for new releases to be followed there.
Closing.
