### ISSUE TITLE
homepage: introduce new logo

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1479]
Currently in COD2 we have this logo
<img width="149" alt="screen shot 2017-10-12 at 11 10 02" src="https://user-images.githubusercontent.com/7301890/31488434-ec7d3c38-af3d-11e7-96a1-5d1c3dc218c2.png">
and in COD3 we have this one 
<img width="231" alt="screen shot 2017-10-12 at 11 10 30" src="https://user-images.githubusercontent.com/7301890/31488464-fb610608-af3d-11e7-888f-865da19f8c4e.png">
We should decide which one we want to keep. In case we keep the COD2 it needs some new design as it doesn't fit the new UI.

**Comment by hjhsalo** [comment]
If this a voting, I vote for original one

**Comment by pamfilos** [comment]
I am adding also here another iteration of logos, derived from the COD2 one in production ( with lowercase letters, dropped "Portal", cleaner design). Lets decide in the next days and finalize! 

![logos](https://user-images.githubusercontent.com/6625469/31492774-cdab21d0-af4c-11e7-8a1f-988ad7ba0bd2.png)

**Comment by diegodelemos** [comment]
I would go for the old logo adapted to the new UI, something like:

![screen shot 2017-10-13 at 2 31 45 pm](https://user-images.githubusercontent.com/9035606/31546387-64c0e6e6-b023-11e7-9885-b0a7bdccc210.png)

zoom

![screen shot 2017-10-13 at 2 34 00 pm](https://user-images.githubusercontent.com/9035606/31546461-b20a5e0a-b023-11e7-9177-62172d1024a1.png)

**Comment by tiborsimko** [comment]
Yes, I also prefer reusing the old logo and "modernising" it slightly in order to fit the new style.  Adapting fonts, introducing curves, etc.  (A bit like Indico did.)

**Comment by ioannistsanaktsidis** [comment]
So to finalise also this one, my opinion is that the one fits our case is this one 
<img width="150" alt="screen shot 2017-10-16 at 11 55 34" src="https://user-images.githubusercontent.com/7301890/31606304-0618726a-b269-11e7-94dd-d313bd48603f.png">
If we change a bit the CERN to the blue color that Eammon provided. Please upvote or downvote.

**Comment by suenjedt** [comment]
@sefeg could you please check CERN's design guidelines and make sure our logo of choice sticks to it? if required please reach out to @pamfilos to adjust the design. Thanks!

**Comment by sefeg** [comment]
Extracted from the CERN design [guidelines](http://design-guidelines.web.cern.ch/typography):

> The font used for the word CERN in the logo is Optima. This should be used wherever possible, along with Helvetica Neue. Together, these two strong and elegant fonts reinforce our identity.
> If these fonts are not available, Arial should be used.
> For internal mail and presentations, Arial is the standard choice.
> If you wish to give a particular look and feel to certain documents, another font may be used.

The last sentence implies that we could be flexible. To take the easy way, we just use Optima / Helvetica Neue. Is that currently the case @pamfilos ?

Instead, [rules](http://design-guidelines.web.cern.ch/guidelines-cern-websites) concerning the logo are more restrictive:

- The CERN logo should always be an active link to http://home.cern

- The logo should be no less than 60px wide, and its correct proportions must be respected.
- Observe the general guidelines for use of the CERN logo, such as minimum spacing and colour restrictions
- The CERN logo may be omitted from websites destined to hand-held devices

We should consider this mainly when it comes to the CERN logo in the footer. @ioannistsanaktsidis

**Comment by ioannistsanaktsidis** [comment]
For the cern logo in the footer, it is not big deal, as we can easily revert to the old one in case this one does not fit the rules. Will check it out.

**Comment by tiborsimko** [comment]
> So to finalise also this one, my opinion is that the one fits our case is this one

That one is visually far from the original logo by its inverted positioning... In my eyes it would be preferable to stick closer to the original, which would make a smoother transition. (Similarly to what Indico project did.)

> Please upvote or downvote.

I guess I had already casted my upvote before your call :) but if we go for serious voting, then let's make the options clear, i.e. not to vote only on one candidate, but enumerate all plausible candidates in @pamfilos's original palette, for example in top-down left-to-right manner, and vote on them.

Another option is to get together for a coffee on Tuesday to shorten the candidate list live, which may be perhaps the quickest[*].

[*] See our lengthy CAP logo selection discussions, including precious bits about various body fluids :) https://github.com/cernanalysispreservation/analysispreservation.cern.ch/issues/40

**Comment by ioannistsanaktsidis** [comment]
Ok then lets narrow the list and then we can decide

**Comment by suenjedt** [comment]
@sefeg can you please prepare the short list and process for the decision (according to Tibor's suggestion above) so that we can make this easier. Thanks.

**Comment by sefeg** [comment]
I prepared a short list that should reflect well the choices we have.

![image](https://user-images.githubusercontent.com/25487025/31657964-0f978cbe-b330-11e7-8677-e7f854100377.png)

Everyone should vote for the favorite logo. In order to not have this thread explode, please just vote by selecting the corresponding emoji.

**Comment by ioannistsanaktsidis** [comment]
So I guess that we have decided that we go for option 😄 ! Is the RFC considered done ?  cc @suenjedt
