### ISSUE TITLE
templates: file index according to type

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1519]
Move txt files from Files section  to indexes section

**Comment by tiborsimko** [comment]
Stemmed from https://github.com/cernopendata/opendata.cern.ch/issues/1417#issuecomment-332170718 which contains hints how to implement this.

**Comment by ioannistsanaktsidis** [comment]
Same here, related to #1453 . These two will go together.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in previous PRs.
