### ISSUE TITLE
CMS: create new software records for RAW dataset

### ISSUE THREAD

**Issue by ArtemisLav** [cernopendata/opendata.cern.ch#1525]
Generate two new software records, as per the discussion in #1202:

1. a new record based on https://github.com/cms-opendata-validation/recotest 

2. a new record based on https://github.com/katilp/compare-rereco

**Comment by ArtemisLav** [comment]
@katilp Could you please provide some metadata for these two records (i.e. titles and descriptions)? Also, is GNU still fine for you for the license?

**Comment by katilp** [comment]
GNU is fine, should I do/add something about that in the github directories?
The repositories have been renamed:

- https://github.com/cms-opendata-validation/recotest -> https://github.com/cms-opendata-validation/2011-minimumbias-raw-recotest
- https://github.com/katilp/compare-rereco -> https://github.com/cms-opendata-validation/2011-mimimunbias-compare-rereco



For recotest:

Title: Validation code for reprocessing AOD from 2011 MinimumBias RAW sample

Description: This code for validation reproduces AOD format in http://opendata.cern.ch/record/24 from 2011 MinimumBias RAW sample (LINK to the new record). It only contains the configuration file to be run on 2011 OpenData VM (LINK) using CMSSW_5_3_32. No compilation is required.  The configuration file has been slightly modified from the original one (LINK to http://opendata.cern.ch/record/3610) to take into account the OpenData computing environment (global tag, input file, commenting out unnecessary steps).  Note that the code in this category is not meant to be a pedagogical example but is a validation tool. 

Use with:
2011 MinimumBias RAW sample (LINK to the new record)

System details
Use this code with the CMS Open Data VM environment
Software release: CMSSW_5_3_32
CMS VM Image, for 2011 CMS open data (http://opendata.cern.ch/record/252)

Files
Should we take a download zip from https://github.com/cms-opendata-validation/2011-mimimunbias-raw-recotest here?

How were this code validated?
The AOD produced by this code can be validated by comparing histograms produced with (LINK to compare-rereco) from the reprocessed AOD and the original AOD, and the histograms, when run over the same event numbers, are found to be equal.

How can you use this code?

If you do not have the CERN Virtual Machine for 2011 CMS data  installed, follow the instructions in step 1 and step 2 at How to install a CERN Virtual Machine (link http://opendata.cern.ch/VM/CMS/2011). Then follow the instructions in https://github.com/cms-opendata-validation/2011-mimimunbias-raw-recotest/blob/master/README.md


For compare-rereco

Title: Validation code to plot basic physics objects from AOD 

Description: This is a simple comparison code to validate the reprocessing step on the Open Data VM by comparing the resulting file (newly rereconstructed from the RAW data sample available on the Open Data Portal) and  the original AOD (also available on the Open Data portal). It loops over different physics objects (tracks, electrons, muons, photons, jets, taus and missing et) and fills histograms with P, pt, eta and phi of these objects. 

Use with:
2011 MinimumBias AOD sample (http://opendata.cern.ch/record/24)
Output of Validation code for reprocessing AOD from 2011 MinimumBias RAW sample (LINK)

System details
Use this code with the CMS Open Data VM environment
Software release: CMSSW_5_3_32
CMS VM Image, for 2011 CMS open data (http://opendata.cern.ch/record/252)

Files
a download zip from github reco to be added, but let me clean the repository before?

How can you use this code?

If you do not have the CERN Virtual Machine for 2011 CMS data  installed, follow the instructions in step 1 and step 2  at How to install a CERN Virtual Machine (link http://opendata.cern.ch/VM/CMS/2011). Then follow the instructions in 
https://github.com/cms-opendata-validation/2011-mimimunbias-compare-rereco/blob/master/README.md

**Comment by ArtemisLav** [comment]
That's great, thank you. Just let me know when the compare-rereco repo is good to go, so that I can grab the files.
 
For the license, one very easy way to add it is [this](https://help.github.com/articles/adding-a-license-to-a-repository/), if you would like to have it on GitHub as well.

**Comment by katilp** [comment]
OK, thanks, done for the license. For the compare-rereco I may need to make some updates/cleaning in the code, can you already build the record without attached download zip (just the link)?

**Comment by ArtemisLav** [comment]
Yes, no problem, I will generate the records without attaching the files and we can add them later on.
