### ISSUE TITLE
templates: disclaimer in software records

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1528]
The "Disclaimer" box on the software record detailed page should not be hardcoded, but should display the given license information taken from the `license` JSON record field.

Compare COD2 and COD3:

- http://opendata.cern.ch/record/461
- http://opendata-dev.web.cern.ch/records/461 

(stemmed from #1423)

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
