### ISSUE TITLE
data model: enrich JSON schema information

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1529]
Once we have full examples for all collections, we should take time to enrich JSON schemas to do things like:

- [ ] mark fields as mandatory or optional
- [ ] describe the meaning of all fields

**Comment by ArtemisLav** [comment]
@tiborsimko is it possible to just keep `record-v1.0.0.json` & `glossary-term-v1.0.0.json`? I know we've had this conversation before, but I simply don't recall the reasoning behind having more than just one global schema.

**Comment by tiborsimko** [comment]
(1) If we plan to keep having all the records in the same `record` namespace -- as we did during the COD2->COD3 sprint fever -- then we can indeed remove all the other schemas and mappings for better clarity.

(2) If we plan to one day split the records into `dataset`, `software` and other different namespaces, then we can keep them on the disk. However there is indeed a risk of them being outdated.  Hence, 
since we have these files in the git commit history, we can perhaps remove them anyway...

What is your preference? 

P.S. See also the past musings in https://github.com/cernopendata/opendata.cern.ch/issues/1312#issuecomment-324318497 and elsewhere. Since we are quite busy with CAP and REANA, I am not sure it is advantageous to schedule the record splitting work package anytime soon...  We may simply live with just `record` and `docs` namespaces.  Let's muse IRL?
