### ISSUE TITLE
RFC data model tuning

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1531]
- flat fields vs nested fields (e.g. abstract, types, dates?)
- generation vs selection for simulated datasets
- parent_dataset -> use relations like for OPERA with "isDerivedFrom", "isChildOf"

**Comment by tiborsimko** [comment]
- note vs documentation

**Comment by tiborsimko** [comment]
- keywords 653 vs 655

**Comment by tiborsimko** [comment]
@katilp One thing we discussed in the past is regarding `type` and `subtype` multiplicity. It would be good to decide now.

The type/subtype examples include

- type=Dataset, subtype=Collision Data
- type=Dataset, subtype=Derived Data
- type=Software, subtype=Validation
- type=Software, no subtype
- ...

Can we safely rely that there will be in the future only one `type` and either zero or only one `subtype`? 

During some of our past discussions, we were evoking a possibility that `subtypes` may be a list perhaps... Do you have any thoughts on that? (It would be good to foresee this possibility now, so that we don't have to change the data model later.)

See also faceting by types/subtypes at http://opendata-dev.web.cern.ch/search

**Comment by katilp** [comment]
When it comes to types like Dataset and Software, we can probably assume only one type.
For subtypes, I would be more cautious, we may have a record good for both Validation and Example and there I would allow for a list.
And derived dataset can be event display or some others

But for the search, I hope that the facets be also be keywords which can be added to the records or modified if needed?

**Comment by tiborsimko** [comment]
- language vs languages

**Comment by tiborsimko** [comment]
@katilp Thanks, we shall foresee possible lists. 

Yes, the facets will be possible by keywords, as discussed in the past. https://github.com/cernopendata/opendata.cern.ch/issues/865#issuecomment-161244193

**Comment by tiborsimko** [comment]
Notes from discussion with @ArtemisLav:

```
type: {
  primary: Dataset,
  secondary: [Collision Data,]

title
title_additional

language: english

topic:
  category: BSM
  source: CMS

note -> relations isRelatedTo

documentation -> note

selection

generation
```

**Comment by katilp** [comment]
@tiborsimko @ArtemisLav Careful though with the categories for MC (like BSM): we may need to change and adjust them according to the user feedback or due to wrong assignments. Will this be possible afterwords?

**Comment by tiborsimko** [comment]
@katilp Yes, here we thought about structure only (=placing them in `topic`), not about values. The plan is to load records to DEV in the next weeks, so that you can see how the records look like "live", including faceting based on category. Yes, it'll be very well possible to update the values afterwards iteratively based on the user feedback.

**Comment by tiborsimko** [comment]
Some more to discuss live with @ArtemisLav:

- cms_confdb_id / 035 (naming?)
- report_number / 037 (naming?)
- title_subtitle / 245 $b (not used?)
- additional_title_subtitle / 246 $b (not used?)
- prepublication / 269 (naming?)
- extent / 300 (naming?)
- methodology / 567 (naming?)
- generator / 593 (plurals?)
- collaboration / 110 and 710 (multiple?)
- code to produce files / 777 (relations with isProducedBy)
- related dataset / 786 (relations with isPartOf)
- related item / 787 (label? note? multiple recids?)

**Comment by tiborsimko** [comment]
- harmonise using integers vs strings for "recid", "number_files" etc

**Comment by tiborsimko** [comment]
Notes from discussion with @ArtemisLav:

- report_number -> move under prepublication

- extent --> delete

- methodology -> keep, and do not introduce generation, selection

- generators --> expand from:


```
 "generator": {
   "global_tag": "Global tag: START53_LV6", 
   "name": "Generators: madgraph madspin pythia6 tauola"
 },
```

into:

```
 "generator": {
   "global_tag": "START53_LV6", 
   "names": ["madgraph", "madspin", "pythia6", "tauola"]
 },
```

(ditto elsewhere for "Global tag: XXX"?)

- collaboration -> 110 AND 710 merge into the same field

- related_item -> description and recid into relations, label and link into links

- beware for 516 and 787 there can be multiple $w

- harmonise recid is a string, number_files etc is an integer

**Comment by tiborsimko** [comment]
All fields discussed and the MARC to JSON conversion procedures were updated accordingly.
