### ISSUE TITLE
Formating issues in http://opendata-dev.web.cern.ch/articles/cms-2011-virtual-machines-how-to-install

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1536]
in http://opendata-dev.web.cern.ch/articles/cms-2011-virtual-machines-how-to-install

- the list at the beginning should link to the corresponding place in the record
- Example ouput (after"if you get an output like:" displays an empty line between each line -> remove
- Q&A in verbatim -> should be normal text

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in previous PRs.
