### ISSUE TITLE
templates: close modal after downloading

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1538]
Right now when you click download modal stays. We should close it directly after the download starts.

**Comment by tiborsimko** [comment]
(stems from https://github.com/cernopendata/opendata.cern.ch/issues/1451#issue-260534499)

**Comment by ioannistsanaktsidis** [comment]
Moving to general UI Sprint as it will be implemented alongside with the files Sprint.
