### ISSUE TITLE
ispy: integrate ispy previewer

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1539]

**Comment by tpmccauley** [comment]
There will certainly have to be some changes to make re: populating the load file dialog with files from portal. This is best done when previewer is integrated.

**Comment by tpmccauley** [comment]
Actually for the previewer this should not be an issue since it will be displaying the file in the record.

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley Good news :)  I integrated the previewer, everything seems to work fine with bootstrap 4. There might need to be some changes in setup.js and files-load.js in the way of importing the json files. There seem to be some problems including them like this ```ispy.getJSON('./geometry/tob.json')``` .  If I change it to ```ispy.getJSON('/static/node_modules/ispy-webgl/geometry/tob.json')```
everything is fine :D

**Comment by ioannistsanaktsidis** [comment]
Moving to COD3-UI milestone. There is already an open PR. We need to muse with @tpmccauley  so as to finalise it.

**Comment by tpmccauley** [comment]
@ioannistsanaktsidis I published a new version 0.9.8-COD3.3 which should address the issues above. There are some minimal changes to the index.html as well.

**Comment by tpmccauley** [comment]
Sorry, make that 0.9.8-COD3.4

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  thanks for the update. Most of the things are fixed.```setup.js``` and ```files-load.js``` need also to be updated because json files ant mtl are not fetched. See img 
![screen shot 2017-10-25 at 11 46 57](https://user-images.githubusercontent.com/7301890/31992418-923db76a-b97a-11e7-9384-ad43367f9009.png)

**Comment by tpmccauley** [comment]
@ioannistsanaktsidis shouldn't the url path be /visualise/events/CMS/?
Also, are you sure you have the right version? In 0.9.8-COD3.4 I don't load eb.json or ee.json but instead the reduced geometries: https://github.com/cms-outreach/ispy-webgl/blob/0.9.8-COD3.4/js/setup.js#L363-L364

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  you are right, for some reason it still kept the old version. Now everything seems to be working I just get one error in console
![screen shot 2017-10-25 at 13 18 59](https://user-images.githubusercontent.com/7301890/31996009-160ab82a-b987-11e7-9c52-c1b6878b33b1.png)
It fails at that line
```
tbl.insertRow(tbl.rows.length).insertCell(0).innerHTML = '<a onclick="ispy.showWebDir(\'' + data[d].release + '\');">' + data[d].release + '/' + '</a>';
```
but I don't see any issue when I play around with the visualiser . Any ideas  ?

**Comment by tpmccauley** [comment]
@ioannistsanaktsidis I bet that the element here:
```
var tbl = document.getElementById("browser-dirs");
```
isn't in the index.html (rather its equivalent file in visualise/event/CMS) like here:

https://github.com/cms-outreach/ispy-webgl/blob/0.9.8-COD3.4/index.html#L267-L268

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  perfect that was the issue :) I am pushing my PR now so as to merge it. Everything is working good.  Only the fullScreenMode is failing but it is ok for now, we can deal with it later. Thank you very much for the help!

**Comment by tpmccauley** [comment]
@ioannistsanaktsidis thanks. Once the PR is merged I can work on it as well.
