### ISSUE TITLE
Wrong disclaimer (LHCb) in a CMS record

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1542]
http://opendata-dev.web.cern.ch/software/461 has LHCb in the disclaimer ...
We did not have that text earlier (see http://opendata.cern.ch/record/461), no problem for adding it though, if corrected ;-) and considered useful. 
However, should the word "releases" be replaced by "records" in
" All releases will have a unique DOI that you are requested to cite in any applications or publications. "

**Comment by ioannistsanaktsidis** [comment]
@katilp  already addressed in a pending PR https://github.com/cernopendata/opendata.cern.ch/pull/1530/files#diff-039352f2567386922b8c558f308ff2a8R103. ;)

**Comment by katilp** [comment]
OK, sorry, then closing
