### ISSUE TITLE
Visual issues with dataset record (sub?)subtitles

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1547]
Example dataset record that illustrates the issues can be found [here](http://opendata-dev.web.cern.ch/datasets/10.7483/OPENDATA.CMS.N372.QF6S). 

Within _How were these data selected?_, the following issues have been observed:

- Subtitles are not clearly distinguished visually from the rest of the text. Compare: [current version.](http://opendata.cern.ch/record/15)

- As can be seen, several words are missing

**Comment by ioannistsanaktsidis** [comment]
@hjhsalo could you pls take a look ?

**Comment by katilp** [comment]
Could you also see if the empty lines between HLT trigger paths can be removed? The list can be long and it would be much better to fit as much of it as possible in one screen (see e.g http://opendata.cern.ch/record/26)

**Comment by katilp** [comment]
Further comments on the visual aspect, a random example of
http://opendata-dev.web.cern.ch/record/1321
Comparing with http://opendata.cern.ch/record/1321:
the titles (and in consequence the record structure and an overview of available information) are much better visible in the old record, do you agree or is it just me?
