### ISSUE TITLE
Update 2010 instructions for new VM and condition data reading

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1550]
Test #1298 and #1549  and update instructions when ready

**Comment by katilp** [comment]
Concerns:

- [ ] http://opendata.cern.ch/getting-started/CMS/2010 (cfr http://opendata.cern.ch/getting-started/CMS/2011)
- [ ] Trigger instructions https://github.com/caredg/cms_legacy_data/tree/2010/TriggerInfo/TriggerInfoAnalyzer see #1300

Does NOT concern the validation records http://opendata.cern.ch/record/460, http://opendata.cern.ch/record/461, http://opendata.cern.ch/record/462 as no condition data read (testing required!)

**Comment by katilp** [comment]
Concern also

- [ ] http://opendata.cern.ch/docs/cms-guide-for-condition-database:
    - 3rd paragraph: remove "For 2011-2012 CMS Open Data, "
    - add a section for 2010 collision data

**Comment by katilp** [comment]
- [ ] New VM updated to from 1.1.0 to 1.1.1  (CMS-OpenData-1.1.1), change correspondingly above

**Comment by ioannistsanaktsidis** [comment]
@katilp anything else needed for this one ? or I can close it ?

**Comment by katilp** [comment]
@ioannistsanaktsidis Can be closed, thanks! @caredg has the trigger instructions ready to go for the github page referred above.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed.
