### ISSUE TITLE
Create record for the 2011 ttbar validation example

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1552]
Bring to the portal https://github.com/cms-opendata-validation/2011-doubleelectron-doublemu-mueg-ttbar

@zenaiev Provide entries under the different titles for the software record (get inspiration from http://opendata.cern.ch/record/462 or http://opendata.cern.ch/record/233 but note that the header names with "data" are wrong and will be changed see #1537) 

@ArtemisLav @tiborsimko Are we happy with sw record subtitle or should we change/add/remove some? Should we unify validation with other software records?

Current visible fields are (taken into account #1537) 
If you feel that these titles do not match the contents or are not enough, we can still change them.
Title:
Authors:
Description:
Use with:
System details:
Related items:
How can you use this code:
Issues and limitations:

Note that we will give the github repository link in the record (for example in How can you use this code) but for data preservation purposes, we would also like to add the contents of the repo as a file.

**Comment by zenaiev** [comment]
Proposed requested entries:

Title: 
Analysis code for measurements of top quark pair production in dilepton channel at 7 TeV using 2011 data

Authors:
Oleksandr Zenaiev

Description:
This code for analysing and benchmarking of the DoebleElectron, DoubleMuon and MuEG datasets is set up at Research level, i.e. it requires university-student-level programming experience. Minimal acquaintance with Linux and the ROOT analysis package (https://root.cern.ch/) as well as a basic text editor is needed.

Use with:
Use this with 2011 DoebleElectron, DoubleMuon and MuEG primary dataset (see detailed instructions in readme files and code): http://opendata.cern.ch/record/16, http://opendata.cern.ch/record/17, http://opendata.cern.ch/record/25

System Details:
Use this code with the CMS Open Data VM environment http://opendata.cern.ch/record/249
Software release: CMSSW_5_3_32

Related items:
The output of the code at different stages is described readme.txt

How can you use this code:
If you do not have the CERN Virtual Machine for 2011 CMS data installed, follow the instructions in step 1 at http://opendata.cern.ch/VM/CMS/2011. Then install and run the Demo (demo analyzer) program following the instructions at http://opendata.cern.ch/VM/CMS/2011#testvalidate2011. To run the analysis, follow the instructions in the file readme.txt above.

Issues and limitations:
??? (not aware of any issues or limitations)

**Comment by katilp** [comment]
@zenaiev Thanks! We can leave Issues and limitations out.

**Comment by katilp** [comment]
@zenaiev Coud you check, I think that "Then install and run the Demo (demo analyzer) program following the instructions at http://opendata.cern.ch/VM/CMS/2011#testvalidate2011." Is not needed here, is it? Thanks!

**Comment by zenaiev** [comment]
Correct, not needed, thanks!

**Comment by tiborsimko** [comment]
@katilp @zenaiev Can you please tag the repository  https://github.com/cms-opendata-validation/2011-doubleelectron-doublemu-mueg-ttbar with a release tag, for example v1.0.0, so that we can grab the tarball and ingest it into CERN Open Data?  (We prefer to always ingest tagged releases, so that when we mint the software record with a DOI, there will be unique identification which version does this DOI belong to.) Thanks!

**Comment by zenaiev** [comment]
@tiborsimko version 1.0.0 should be available now

**Comment by tiborsimko** [comment]
@zenaiev Thanks, ingested.
