### ISSUE TITLE
Create record for 2011 dimuon spetrum example code

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1556]
Prepare the record based on /afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo_2011/

NB We can remove from BuildFile 
```
<export>
   <lib name="1"/>
</export>
```
as instructed in the compile time warning:
****WARNING: No need to export library once you have declared your library as plugin. Please cleanup src/Demo/DemoAnalyzer/BuildFile by removing the <export></export> section.

Prepare a github repo for this under cms-opendata-analyses

**Comment by katilp** [comment]
The code is now also in https://github.com/cms-opendata-analyses/DimuonSpectrum2011

**Comment by katilp** [comment]
Title:
Example code to produce the di-muon spectrum from a CMS 2011 primary dataset

Authors:
 Geiser, Achim; Dutta, Irene; Hirvonsalo, Harri; Sheeran, Bridget 

Description:
This simple analysis example is set up at Research level, i.e. it requires university-student-level programming experience. Minimal acquaintance with Linux and the ROOT analysis package (https://root.cern.ch/) as well as a basic text editor is needed.

Use with:
Use this with 2011 Mu primary datasets or any other 2011 primary datasets containing muons (see detailed instructions in code)

System details:
Use this code with the CMS Open Data VM environment
Software release: CMSSW_5_3_32
CMS VM Image, for 2011 CMS open data



How can you use this:
If you do not have the CERN Virtual Machine for 2010 CMS data installed, follow the instructions in step 1 at How to install a CERN Virtual Machine (http://opendata.cern.ch/VM/CMS/2011)
Then follow the instructions in https://github.com/cms-opendata-analyses/DimuonSpectrum2011

You should get an output file DoubleMu.root, which contains histograms for 10000 input events (a small subset of the data). These can be looked at using a ROOT Browser. The most interesting histogram is GM_mass_log. In order to compare it with the invariant-mass spectrum of di-muons in MUO-10-004 (https://inspirehep.net/record/1118729/plots), it should be viewed with the logy option. With 10000 events the comparison is poor, but the J/ψ (at log10(mass)=0.5), Υ (at log10(mass=0.98)) and Z (at log10(mass)=1.95, one event only) peaks should be visible.
Finally, to run over more or even the full data, edit the relevant parts of the Python file demoanalyzer_cfg.py (see comments therein) and rerun. 

Validation:

Only the list of validated runs are accepted: http://opendata.cern.ch/record/1001

(Although I'm sure if "Validation" is the appropriate subtitle for this, using only validated events does not validate this example... we could use Issues and limitations instead)

**Comment by tiborsimko** [comment]
@katilp Can you please tag the repository https://github.com/cms-opendata-analyses/DimuonSpectrum2011 with a release tag, for example v1.0.0, so that we can grab the tarball and ingest it into CERN Open Data? (We prefer to always ingest tagged releases, so that when we mint the software record with a DOI, there will be unique identification which version does this DOI belong to.) Thanks!

**Comment by katilp** [comment]
OK, @zenaiev could you advice how to do that? Thanks!

**Comment by zenaiev** [comment]
@katilp go to repository webpage -> "0 releases" (push there) -> "create a new release" -> enter tag version -> "publish release"

**Comment by katilp** [comment]
@zenaiev Thanks! @tiborsimko v1.0.0 done

**Comment by tiborsimko** [comment]
@katilp Thanks, ingested.
