### ISSUE TITLE
CMS public site has moved - replace links to cms.cern

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1586]
The new CMS public page is  https://cms.cern/, was cms.cern.ch
Replace all...

**Comment by tiborsimko** [comment]
Also replace `cern.ch/cms`.

**Comment by tiborsimko** [comment]
Also replace `cms.web.cern.ch`.

**Comment by atrisovic** [comment]
- [ ] ./cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json:4:    "description": "The virtual machine image is based on CernVM (cernvm.cern.ch), with Scientific Linux CERN 6 (slc6), which is the environment needed for the
 It gets the CMS software (CMSSW) from /cvmfs/cms.cern.ch and the jobs running on the CMS open data VM read the condition data from /cvmfs/cms-opendata-conddb.cern.ch. Access to the data is through XRootD."

- [ ] ./cernopendata/templates/cernopendata_theme/footer.html:15:            <a href="http://cms.cern.ch"><img src="{{ url_for('static', filename='img/cms.gif') }}" alt="" width="55"

- [ ] ./cernopendata/modules/fixtures/data/articles/about-cms/cms.md:1:The Compact Muon Solenoid (CMS) Experiment is one of the large particle detectors at CERN's Large Hadron Collider. The CMS Collaboration consists of more than 3000 scientists
d universities from 40+ countries. You can find more information about the CMS [detector design](http://cms.web.cern.ch/news/cms-detector-design) and [overview](http://cms.web.cern.ch/news/detector-overview) on the official [CMS website](h

- [ ] ./cernopendata/modules/fixtures/data/articles/cms-physics-objects-2010/cms-physics-objects-2010.md:60:The energy and momentum were ready to use. However for photon identification additional selection needs to be applied. These cuts are lis
s-physics/public/EGM-10-006-pas.pdf).

- [ ] ./cernopendata/modules/fixtures/data/articles/cms-physics-objects-2011/cms-physics-objects-2011.md:60:The energy and momentum were ready to use. However for photon identification additional selection needs to be applied. These cuts are lis
s-physics/public/EGM-10-006-pas.pdf).

- [ ] ./cernopendata/modules/fixtures/data/terms/terms.json:440:                              "url": "http://cern.ch/cms"

- [ ] ./cernopendata/static/test_data/debug.md:61:The energy and momentum were ready to use. However for photon identification additional selection needs to be applied. These cuts are listed in [Table 1 here [PDF]](http://cms-physics.web.cern.ch

- [ ] ./cernopendata/templates/cernopendata_pages/about/about_cms.html:13:    <a href="http://cms.web.cern.ch/news/detector-overview">overview</a> on the official <a href="http://cern.ch/cms">CMS

- [ ] ./cernopendata/templates/cernopendata_pages/visualise_events_cms.html:334:          A browser-based event display for the <a target="_blank" href="http://cern.ch/cms">CMS experiment</a> at the

- [ ] ./cernopendata/templates/cernopendata_pages/visualise_events_cms_standalone.html:293:          A browser-based event display for the <a target="_blank" href="http://cern.ch/cms">CMS experiment</a> at the

- [ ] ./cernopendata/modules/fixtures/data/articles/about-cms/cms.md:1:The Compact Muon Solenoid (CMS) Experiment is one of the large particle detectors at CERN's Large Hadron Collider. The CMS Collaboration consists of more than 3000 scientists,
d universities from 40+ countries. You can find more information about the CMS [detector design](http://cms.web.cern.ch/news/cms-detector-design) and [overview](http://cms.web.cern.ch/news/detector-overview) on the official [CMS website](ht

- [ ] ./cernopendata/modules/fixtures/data/articles/about-cms/cms.md:50:* If you are interested in more, please contact nearest [CMS university/institute](http://cms.web.cern.ch/content/cms-collaboration)

- [ ] ./cernopendata/modules/fixtures/data/articles/news/html/cms_20112014.html:1:<p>The Compact Muon Solenoid (CMS) Collaboration at CERN is excited to announce the public release of the first batch of high-level, analysable and open data from t
. The datasets are available on the new CERN Open Data Portal and are being released into the public domain under the Creative Commons CC0 waiver, in keeping with CMS's commitment to data preservation and open data. <a href=\"http://cms.we
ata\">Read full release announcement</a></p>

- [ ] ./cernopendata/modules/fixtures/data/articles/news/html/cms_22042016.html:2:<p>Available on the CERN Open Data Portal - which is built in collaboration with members of CERN's IT Department and Scientific Information Service - the collision
r and come in types: The so-called \"<a href=\"http://opendata.cern.ch/search?ln=en&p=Run2011A+AND+collection%3ACMS-Primary-Datasets\">primary datasets</a>\" are in the same format used by the CMS Collaboration to perform research. The \"<a
collection%3ACMS-Derived-Datasets\">derived datasets</a>\" on the other hand require a lot less computing power and can be readily analysed by university or high-school students, and CMS has provided a limited number of datasets in this fo
batch-research-data-lhc\">Read full release announcement</a></p>

- [ ] ./cernopendata/templates/cernopendata_pages/about/about_cms.html:12:    <a href="http://cms.web.cern.ch/news/cms-detector-design">detector design</a> and

- [ ] ./cernopendata/templates/cernopendata_pages/about/about_cms.html:13:    <a href="http://cms.web.cern.ch/news/detector-overview">overview</a> on the official <a href="http://cern.ch/cms">CMS

- [ ] ./cernopendata/templates/cernopendata_pages/about/about_cms.html:141:                                                            href="http://cms.web.cern.ch/content/cms-collaboration">CMS university/institute</a>.

- [ ] ./cernopendata/templates/cernopendata_pages/visualise_events_cms.html:521:        <p>Want to know more? Go <a href='http://cms.web.cern.ch/news/cms-detector-design' target='_blank'>here</a>.

- [ ] ./cernopendata/templates/cernopendata_pages/visualise_events_cms_standalone.html:480:        <p>Want to know more? Go <a href='http://cms.web.cern.ch/news/cms-detector-design' target='_blank'>here</a>.
