### ISSUE TITLE
Link to CMS-Physics-Objects in about/CMS

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1592]
The link to http://opendata.cern.ch/about/CMS-Physics-Objects has disappeared/is not visible in http://opendata-dev.web.cern.ch/about/cms

**Comment by atrisovic** [comment]
I think `/about/cms` should be redirected to `/articles/about-cms`
http://opendata-dev.web.cern.ch/articles/about-cms
@tiborsimko what do you think?

**Comment by tiborsimko** [comment]
We have some pages living as "simple Jinja templates" (started in summer), and some living as "articles" (started later). The distinction was that the first ones are of the nature that it is not necessalry for them to appear in searches (such as the privacy policy page, the terms of service page, etc), while the second ones may be interesting for search (so they should live as records). Perhaps there was a confusion for the "about" ones as to whether they were "simple pages" or "article records"?

(Personally, now that we have an easy Markdown authoring support, perhaps we could consider converting all formerly "simple pages" into "markdown articles", if we are OK that they would appear in searches... it would avoid confusion such as this one.)

**Comment by katilp** [comment]
Closed as implemented
