### ISSUE TITLE
facets: inconsistent result counts and facet counts

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1600]
Fix inconsistent facet counts at: 

- http://0.0.0.0/search?page=1&size=20&type=Environment

The page shows only 12 hits in the page body, but the facet counts are shown for the whole database.  The facet count numbers should correspond to the results presented in the search.

How to reproduce:

- a user goes to COD3 homepage
- the user searches for "cms"
- the user sees 2026 hits with many facets
- the user clicks on the 3rd hit on its "Environment" label
- ... and the search finds 12 hits, but the facets are shown for everything.

![hungry-facets](https://user-images.githubusercontent.com/517546/32502193-60ebbaa8-c3da-11e7-97a6-066face95219.png)

**Comment by annatrz** [comment]
So this one can be closed, as we agreed on implementation (calculating numbers) as defined in #1685
