### ISSUE TITLE
records: rich metadata display for cms-eventdisplay-files.json

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1655]
Ensure that the records from cms-eventdisplay-files.json are displayed in a complete manner in
both brief and detailed formats.

Compare the COD2 and COD3 display for several representative records from the
file, for example:

- COD2 http://opendata.cern.ch/record/600
- COD3 http://0.0.0.0/record/600

All metadata fields displayed in COD2 should be displayed also in COD3 in
roughly the same order and the same style.

Don't forget to check also the brief formats as the records are displayed in
search.

Update both brief and detailed record templates as necessary to display all the
fields:

- `cernopendata/static/templates/search/briefs/record.html`
- `cernopendata/templates/cernopendata_records_ui/records/record_detail.html`

Assume that fields may be optional; use `record.get(somefield, 'somedefault')`
technique.

When the record field contains HTML, it is safe to assume that the contents is
safe to display in Jinja.

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  for loading the standalone previewer inside  the record, which is the correct function to use ? https://github.com/cms-outreach/ispy-webgl/blob/cod3/js/files-load.js#L202 is this function doing the job?

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Regarding *embedded* previewer mode (inside records, on `/record/NNN` pages), as opposed to *standalone* previewer (outside records, on `/visualise/events/cms` pages), you can also check what was done in COD2 regarding local file loading:

- https://github.com/inveniosoftware/invenio-previewer-ispy/blob/master/invenio_previewer_ispy/templates/previewer/ispy_base.html

(obviously not applicable *too* directly...)
