### ISSUE TITLE
search: investigate facet behaviour

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1661]
Currently, we offer multiple facets wirh multiple values, each having checkboxes, so that users can select multiple values to combine any query they want.

However, this may lead to situations where the user selects some value from some facet and then wonders why the other facets were not updated.

Another option would be to refresh the page after a facet value is selected (as was chosen on some other Invenio instances). However, this may also lead to potential UX problems how to select multiple values.

We can user-test the two approaches and select a preferred one that would be matching the best our target general public audience.

**Comment by sefeg** [comment]
This is a very helpful guide to best practices on designing facets and can be a reference for further discussions: https://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php

In step 2, they nicely demonstrate how unavailable check boxes can be disabled. That of course would require us to refresh the page.

**Comment by sefeg** [comment]
Closing, as addressed in #1685
