### ISSUE TITLE
templates: Explore in the page header

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1671]
The "Explore" menu in the page header is currently offering to explore:
 
- Datasets
- News
- Documentation
- Software
 
The list should be completed, not forgetting some popular functionality such as event display and histogramming.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko you mean visualise histograms and cms detector events like we have them in the bottom of the page in the visualise part ?

**Comment by tiborsimko** [comment]
Yes, I think that would be good, based on my talks with @katilp. For example, "Expore news" does not really makes sense there to me eyes... while "Explore histograms" clearly would.  Basically, the "Explore" menu serves the purpose of promintently advertising the main content of the site.  Hence "Explore detector events", leading to a dedicated page about how to events display, or to a faceted search page showing all events, would make perfect sense as well... but I guess @sefeg @dassler will chime in here with their initial user testing observations...

**Comment by tiborsimko** [comment]
It is premature to close this ticket, note that my description said "the list should be completed", the musings below were just an example...The "Explore" list will be completed based also on user tests, I think @sefeg will create an issue.

**Comment by sefeg** [comment]
Well, here we basically discussed to add all the entries of the type facet (Dataset, Documentation, Environment, Glossary, News, Software, Supplementaries) to completely represent the "sticky" type filter (see #1659) in the facet results.

**Comment by katilp** [comment]
I would leave out from the Explore menu Supplementaries and Environment. The first is a monster category with items that are there for documentation purposes and which only make sense when presented in the proper context (as they are when linked to the datasets in the dataset records) and we do not want to expose them as such (more than the presence of that category in the normal search).
The latter will be misleading as it makes the user think that s/he must load all that (including conditions) for the working environment whereas the VM is enough.
And see Tibor's comment on "Explore news" above :-)

**Comment by sefeg** [comment]
We just had another quick chat on that. Basically, we agreed that we would add **all** types to the Explore menu, in order to allow for an effective way of accessing all file types. For some of the entries it might be less obvious to "explore" them, but since the record types are at the core of our UX, we should completely represent them in the menu.

**Comment by katilp** [comment]
I'm still opposed to have Supplementaries there, there is no reasons for anybody to explore them stand-alone.  They are just confusing and without meaning out of their proper context. I think the UI design considerations should rather take into account the contents (which is important for the user) and not the underlying structure (which does not matter for the user). To my view the main function of the Explore menu is to make access to information easier for user by picking up relevant things - and it does not need to be a full duplication of search in file type category, does it?

**Comment by sefeg** [comment]
If there is absolutely no reason to look for content under the _Supplementaries_ tag on its own, we can leave it out.
