### ISSUE TITLE
CMS: extract keywords from simulated dataset titles

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1676]
Extract keywords from simulated dataset titles.

Follow explanations from http://opendata.cern.ch/about/CMS-Simulated-Dataset-Names.

Can extract process (gluon-gluon to higgs to zz to 4 leptons).

Can extract generators (madgraph, pythia).  But also from DAS.

Can extract concepts, e.g. VBF vector boson fusion.

**Comment by heitorPB** [comment]
I have some notes about it here:
https://demo.codimd.org/Dv5MjPctQOeHBBix5Zkj2A?both#
