### ISSUE TITLE
ui: plug MathJax 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1677]
Plug MathJax for the nice display of mathematics.

Example:

- COD2 http://opendata.cern.ch/record/328
- COD3 http://0.0.0.0/record/328

See also #1447.

(stemmed from https://github.com/cernopendata/opendata.cern.ch/pull/1669#issuecomment-343096770)

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
