### ISSUE TITLE
fixtures: ATLAS link to atlas-opendata page broken

### ISSUE THREAD

**Issue by pamfilos** [cernopendata/opendata.cern.ch#1684]
There are records with metadata links to the ATLAS Opendata page, that are broken

e.x: record 3803
```
"usage": {
    "description": "You can access these data through the ATLAS Virtual Machines and Software. More documentation is available at:",
    "links": [
        {
            "url": "http://atlas-opendata.web.cern.ch/atlas-opendata/extendedanalysis/documentation.php"
        }
    ]
}
```

**Comment by tiborsimko** [comment]
Yup, ATLAS changed their website...

**Comment by artfisica** [comment]
Dear All,

Thank you very much, this was mentioned as well in ticket https://github.com/cernopendata/opendata.cern.ch/issues/1226

In case you would like to clean/close that one too.

Cheers,
Arturo
