### ISSUE TITLE
Facet / Search related findings and observations

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1685]
@daslerr and I conducted user tests to study the interaction with the current version of the search facets. We discussed our findings with @tiborsimko and @katilp and agreed to the following:

- [x] **Recalculate the number of applicable entries on the right of each facet element.** The number should indicate the amount of search results presented after selecting the corresponding facet element. The way the facets work will not change. That means that selecting multiple entries in the same facet group acts as a logical OR, while selecting elements between groups acts as a logical AND.

- [ ] Don't show any number for OR related facet elements that currently display 0. Example: Showing the facets for the full amount of information on resources available, one selects CMS. Currently, all other collaborations are then shown a 0. Hide that number.

- [ ] Selecting a facet-element that has sub-elements assigned (e.g. Documentation) leads to the selection of all the sub-elements, while deselecting the father element leads to the de-selection of all child elements. Question is, how do we show the direct selection of one child element? Usually, one would display a visually less strong check in the father's checkbox. We could e.g. only display the check, without the blue background in case not all child elements are selected. @tiborsimko 

- [x] A facet group should display a sort of clear button that allows the user to clear all selected category elements (in case at least one element is selected)

- [x] We made an interesting observation: Searching for "ion" returns 4 results. Selecting Sort by "Title A- Z" returns only 2.

- [x] The facet elements are ordered alphabetically. Only the year category is not ordered logically (2010 - 2017).

**Comment by sefeg** [comment]
On Friday afternoon, @annatrz finished part of the facet element recalculation. Selecting an element now leads to correctly calculating all elements that have a logical AND dependency to the selected element (i.e. elements from other facet groups than the facet group to which the selected element belongs). An example: Look at the [full list](http://opendata-dev.web.cern.ch/search?page=1&size=20&q=). Selecting LHCb leads to 8 results. In the record type category, all elements are calculated correctly (e.g. 3 Dataset, 3 Documentation, 2 Software, several element = 0). However, due to some limitations, also all the elements within the group of the selected element are set to 0. As we have a logical OR for selection within a group, that is very confusing and again does not reflect what the user can expect clicking on such an element. In the above case, selecting e.g. in addition CMS leads to 2023 results - and not to 0.

On that matter, we have to decide between two approaches:
1. Spend time on overcoming the technical limitations and make sure that also the OR connected elements are showing a value that makes sense.

2. Consider facet elements as drill-down links. That means, that only one element in each category can be selected. All others will be hidden if one is selected.

@tiborsimko @daslerr

**Comment by sefeg** [comment]
Personally, I much prefer approach number 1.

**Comment by daslerr** [comment]
I agree that approach number 1 sounds the best.

**Comment by suenjedt** [comment]
Given the amount of tickets we currently have, I wonder what the priority of this is @sefeg. It already looks much better now, I find.

**Comment by sefeg** [comment]
We just further discussed this issue. Consensus is, that we should not hide OR related facet elements (Option 2) and that showing a 0 value for OR related facet elements is confusing.

For the moment, we selected a pragmatic approach: Don't show any number for OR related facet elements that currently display 0. This is a simple solution that we expect to be less confusing for users. We can then test this with users. In the future, we can always spend time on implementing Option 1, as mentioned above. I updated the to-do list on the top of this issue accordingly.

**Comment by sefeg** [comment]
@annatrz I updated the tasks on the top of this issue based on our latest findings and discussions this week

**Comment by sefeg** [comment]
At the end of last week, concerns were raised if hiding 0's for OR-related facet elements is the best solution. I tested both approaches (showing 0's and hiding 0's) and came to the following conclusion: Both are not perfectly intuitive, but there are differences. Since we now reliably update all other facet elements (= numeric value indicates the number of results that selection will lead to), showing 0's is misleading. Users expect that the result will be 0, some think that a logical AND would be performed. While the other solution, hiding 0, does not provide information on its effect, it is not misleading.

In the daily, we agreed that we do not want to consider another option (e.g. completely hiding the numbers), but stick with the pragmatic solution we described in the task list above.

**Comment by annatrz** [comment]
Ok, so we can close this one, as with #1977 we implement a different way of faceting. Once it's deployed, we can create another issues/rfc about missing features.

So just to sum up, after #1977:
* faceting is gonna work like logical OR within one aggregation type, and AND for others
* we don't show facet value, if has 0 hits
* when parent aggregation checked, all subaggregations will get checked
* when parent aggregation unchecked, all subaggregations will get unchecked
* when subaggregation checked, parent aggregation will get checked
* we have clear buttons for all checked facet values, and one extra to clear them all
