### ISSUE TITLE
records: option to "feature" selected articles

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1729]
Introduce "featured articles" feature that will make it possible to "promote" certain articles to display them on the home page.

This requires to:

(1) enrich the article data model with new fields in order to introduce new fields such as:

- **screenshot** -- holding path to the illustrative screenshot (#1483)
- **featured** -- holding number representing position on the home page

(2) alter home page in order to display featured articles based on increasing numbers.  (Limit to top 3, or top 6...)

The articles will be featured by altering the JSON metadat via regular metadata-editing pull requests.

Note: this ticket is about implementing the feature; the concrete selection of articles for display, and their illustrative screenshots, will happen in #1483.

**Comment by sefeg** [comment]
Since this seems to be purely technical and #1483 muses about design decisions, I created a dedicated issue for the selection of the six featured release articles: #1732
