### ISSUE TITLE
Scaling behaviour of the entry page when zooming in/out

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1734]
On firefox and chrome, the box (figure) size does not scale down when I zoom < 100%, only the text size changes. Resizing the window, however, resizes the boxes as expected.

**Comment by katilp** [comment]
More on scaling, the girls get squeezed or flattened with the scale, is that expected?

170%:
![scale170](https://user-images.githubusercontent.com/5859918/33282586-5ca259d2-d3a9-11e7-9e05-1e28d5ccb54d.PNG)
100%:
![scale100](https://user-images.githubusercontent.com/5859918/33282607-6a95986a-d3a9-11e7-826f-dd32ed63daab.PNG)

67%
![scale170](https://user-images.githubusercontent.com/5859918/33282616-71128c66-d3a9-11e7-9411-8db38d989e03.PNG)

**Comment by tiborsimko** [comment]
This will be addressed by a new home page UI design we discussed yesterday. The home page won't have story pictures and will be rather search-centric... so I think we can close this.
