### ISSUE TITLE
template: titles in articles to be made larger (h1)

### ISSUE THREAD

**Issue by atrisovic** [cernopendata/opendata.cern.ch#1741]
These ones:
<img width="1018" alt="screen shot 2017-11-10 at 16 13 25" src="https://user-images.githubusercontent.com/13986265/32664635-326d83dc-c632-11e7-98b4-1aa5c4593ebc.png">

**Comment by ioannistsanaktsidis** [comment]
Closing as we can discuss later about the general detail view. Right now as it is it corresponds to the old COD2 version.
