### ISSUE TITLE
Difference between c and cc  in file type

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1745]
There should not be any difference between c and cc?
For the CMS records they are partially overlapping
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&experiment=CMS&file_type=c

**Comment by tiborsimko** [comment]
There are some files called like `mergeMu.C`, and other files called like `DemoAnalyzer.cc`, hence both `C` and `cc` extensions are detected. Hence everything is OK on the COD3 side.

Ideally, you could use the same C++ file extensions in examples... or we could "silently" treat `*.C` as if it were `*.cc`, but that could perhaps backfire later when in some cases this difference could be significant...

**Comment by katilp** [comment]
OK, fine, makes sense.
How do you treat records that have a link to a github repository?
Would it be useful that they appear as a file type listing as well.
Ideally, all this kind of records should also have the zip of the repository attached but it not the case, yet.

**Comment by tiborsimko** [comment]
> How do you treat records that have a link to a github repository?

We don't analyse external links, only COD3-hosted files.  But if we download the software for a record from GitHub, and store it as a tarball, it should have "zip" or "tar.gz" or the tarball-specific format extension.  (But we don't analyse whether it is Python or C++ or other languages *inside* the tarball!) 

For example, this record contains a tarball on COD2:

- http://opendata.cern.ch/record/200

and has the following distribution formats on COD3:

```
 "distribution": {
      "formats": [
        "gz"
      ], 
```
(see http://opendata-dev.web.cern.ch/api/records/200)

Note that `tar.gz` is treated as `gz`...
