### ISSUE TITLE
search: style facets using checkboxes

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#175]
Search was found complicated by the testers. Two suggestions
1) in http://opendata.cern.ch/search could a view showing all collections in the left bar be the default
http://opendata.cern.ch/search#[[%22%2B%22%2C%22collection%22%2C%22CMS%22]%2C[%22!%22%2C%22collection%22%2C%22CMS%22]]
That would show the data collections immediately in search.
2) Could the selection of different collections (or other search items)  be done with a click box
(i.e. like ebookers or many others)?

**Comment by tiborsimko** [comment]
Invenio v2.2+ has checkbox-styled facets out of the box, so this will be addressed when the CERN Open Data overlay upgrades to higher Invenio version.

**Comment by suenjedt** [comment]
I am closing this as it comes "automatically" with the new OD on Invenio 3.
