### ISSUE TITLE
articles: titles and slugs 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1753]
As discussed in various PRs such as #1601 and #1749, it would be useful to have a complete list of all "articles" we plan to display with their wanted titles and slugs, so that we can organise the source code accordingly.

For example:

page idea | old URL | new URL (/articles/slug) | page title
----------|--------|--------------|-----
 VMs for ALICE | `/VM/ALICE` | `/articles/virtual-machines-alice` | ALICE Virtual Machines: How to install 
CMS open data research-oriented guide written by Achim | - | `/articles/cms-guide-for-research` |  CMS Guide to research use of CMS Open Data 
... | ... | ... | ...

Such a complete table will help with finding nice names for "CMS troubleshooting" etc.

Note that currently, slug is derived from title, while in the future, it should be settable in the JSON, so that the last part of "new URL" will be different (=shorter) from the full title.  IOW, we shall treat slug as a doi, or as a recid, of sorts... This will also permit us to change titles without changing URLs.  (We had cases of this happening in the past...)

@daslerr @sefeg Would you like to take a stab at drafting such as Slug vs Title map for all the articles?  You could take the list of all available COD2 pages for a start: https://github.com/cernopendata/opendata.cern.ch/issues/1228#issuecomment-292994773

**Comment by sefeg** [comment]
This combines COD2 pages and the articles discussed in #1732 (those that are ready). **Everyone can directly edit this table.**

page idea | old URL | new URL (/articles/slug) | page title
----------|--------|--------------|-----
 VMs for ALICE | `/VM/ALICE` | `/documentation/virtual-machines-alice` | ALICE Virtual Machines: How to install 
VMs for CMS | `/VM/CMS` | `/documentation/virtual-machines-cms` | CMS 2011 Virtual Machines: How to install
VMs for LHCb | `/VM/LHCb` | `/documentation/virtual-machines-lhcb` | LHCb Virtual Machines: How to install 
VM validation report for CMS | `/VM/CMS/validation/report` | `/documentation/virtual-machines-validation-cms` | Testing the CernVM
CMS Physics Objects | `/about/CMS-Physics-Objects` | `/documentation/cms-physics-objects` | CMS Physics Objects
CMS Pile-up Simulation | `/about/CMS-Pileup-Simulation` | `/documentation/cms-pileup-simulation` | CMS Pile-up Simulation
CMS Simulated Dataset Names | `/about/CMS-Simulated-Dataset-Names` | `/documentation/cms-simulated-dataset-names` | CMS Simulated Dataset Names
Getting started with `<year>` CMS data | `/getting-started/CMS/<year>` | `/documentation/getting-started-<year>-cms` | Getting started with CMS `<year>` data
Getting started with ALICE resources | `/getting-started/ALICE` | `/documentation/getting-started-alice` | Learn how to use the ALICE virtual machine to have a first look at ALICE events and use analysis tools
Getting started with LHCb resources | `/getting-started/LHCb` | `/documentation/getting-started-lhcb` | Learn how to use the LHCb virtual machine to have a first look at LHCb events and use analysis tools
CMS open data research-oriented guide written by Achim | - | `/documentation/cms-guide-for-research` |  Guide to research use of CMS Open Data
CMS open data education-oriented guide written by Achim | - | `/documentation/cms-guide-for-education` |  Guide to education use of CMS Open Data 
News article to inform about COD3 portal update | - | `/documentation/portal-update-2017` | Welcome to our updated portal
Report from 2017 summer students | - | `/documentation/summer-student-report-2017` |  Improving educational content with high school teachers: A summer student report

**Comment by tiborsimko** [comment]
@sefeg Thanks! 

Regarding `getting-started-<year>-cms`, I think it's better to have the order `<topic>-<exp>-<year>` rather than `<topic>-<year>-<exp>`,  because some experiments don't have year.. 

Moreover, since we also have `cms-physics-objects-<year>`, perhaps we should standardise upon the following scheme:

- `<exp>-<topic>-<year>`

which would give:

- cms-physics-objects-2010
- cms-getting-started-2011
- cms-guide-for-research
- cms-summer-student-report-2017
- alice-getting-started
- ...

I think this would give a nicely consistent naming everywhere?

**Comment by sefeg** [comment]
Agreed! I updated the table accordingly
