### ISSUE TITLE
Early feedback

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1755]
Following a session with @katilp and Achim, I want to capture collected feedback here.

- When we want to point to educational resources, we can not simply point to the Guide tag. Guides contain also articles that are not suited for education.

Possibles solutions: Distinguish between Education Guides / Research Guides. Add a keyword "education". Educational guides could in the later case be accessed by a combination of _Guides_ and _keyword_: education #1790 

- Existing instructions have to be adapted to reflect new portal structure (navigation)

- Show important guiding articles on the collaboration's About page #1787 

- Remove duplicate CMS string in guide articles

- Link event display file to corresponding dataset (and vice versa)

- For the future: Investigate if we want to analyse user behaviors and list facet elements according to the priority

**Comment by katilp** [comment]
Some feedback related to the (updated) contents of this guide (wrong/missing links etc):

- Does event display (i.e direct link to it) appear in the search somewhere?
- It would be useful to add a keyword "display" for event display files
- "Need help?" has disappeared from http://opendata-dev.web.cern.ch/visualise/events/CMS
- record http://opendata-dev.web.cern.ch/record/52 has a wrong link, should be http://particle-physics-playground.github.io/
- http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-open-data is about 2010, what about 2011

**Comment by katilp** [comment]
Separated the above list to issues of their own, the last is being taken care of already

**Comment by sefeg** [comment]
Closing as feedback is addressed (resolved or active in other issues)
