### ISSUE TITLE
Instructions for use of CMS Open Data in R for schools and education

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1762]
json content for a record (copy pasted from http://opendata-dev.web.cern.ch/record/72)

@tiborsimko @ArtemisLav 
Feel free to add other fields if needed.
For the records #1760, #1761, we have multiple contributors (authors), for this record the author is
Edith Natalia Villegas Garcia 

If "school" and "education" can be keywords, they are not needed in the record title.

@RaoOfPhysics Could you check the language, please?

For the record #1761, we have multiple contributors (authors), here ts 

```
{
    "publisher": "CERN Open Data Portal", 
    "accelerator": "CERN-LHC", 
    "control_number": "**XXXXX**", 
    "abstract": {
        "description": " <p> CMS Open Data in csv format can be used in most practical way in programming applications such as jupyter notebooks or R. A tutorial is provided  to introduce R and CMS Open Data. You can access the repository of instructions in different languages in <a href=\"https://github.com/cms-opendata-education/cms-rmaterial-multiple-languages\">a github repository</a>  or download the pdf file of the instructions in English from this record.  We welcome new translations in different languages and other contributions.</p>
 "
    }, 
    "title": "Instructions for use of CMS Open Data in R for schools and education", 
    "recid": "**XXXXX**", 
    "date_published": "2017", 
    "experiment": "CMS", 
    "collections": [
        "CMS-Open-Data-Instructions"
    ], 
    "date_created": "2017", 
    "distribution": {
        "formats": [
            "pdf"
        ]
    }, 
    "type": {
        "primary": "Documentation", 
        "secondary": []
    }, 
    "collaboration": {
        "recid": "451", 
        "name": "CMS Collaboration"
    }
}
```

The file to attach in the record is 
https://github.com/cms-opendata-education/cms-rmaterial-multiple-languages/blob/master/EN-R-Tutorial.pdf.pdf

**Comment by RaoOfPhysics** [comment]
```
"description": "<p>CMS Open Data in the form of CSV files can be used in programming applications such as Jupyter notebooks or R. A tutorial is provided to introduce R and CMS Open Data. You can access the repository of instructions in different languages in <a href=\"https://github.com/cms-opendata-education/cms-rmaterial-multiple-languages\">this Github repository</a> or download the PDF file of the instructions in English from this record. We welcome translations into different languages and other contributions.</p>"
```

**Comment by RaoOfPhysics** [comment]
@katilp: Can we migrate this repo to Jupyter as well, using the IR Kernel? It's probably better than a PDF.

**Comment by katilp** [comment]
@RaoOfPhysics yes, it would be better,  although I have never used R so I won't be able to do it quickly

**Comment by RaoOfPhysics** [comment]
@katilp: I meant to offer to do this! Sorry it didn't come across. I'll need to learn how to ensure that something like Binder can grab the IR Kernel directly. Will poke around. Keeping this tab open for now.

**Comment by katilp** [comment]
Oh cool, that would be great, thanks! Feel free to add it to the repo.

**Comment by RaoOfPhysics** [comment]
Before merging, please make sure that https://github.com/cms-opendata-education/cms-rmaterial-multiple-languages/pull/1 is closed.
