### ISSUE TITLE
templates: display pile-up information for CMS Simulated Datasets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1770]
Display pile-up information for CMS Simulated Datasets records.

The pile-up record is here:

- http://opendata.cern.ch/record/3600

and it is linked from the MC datasets in JSON, for example: 

```
  "pileup": {
    "description": " <p> To make these simulated data comparable with the collision data, <a href=\"/about/CMS-Pileup-Simulation\">pile-up events</a> are added
 to the simulated event in this step. </p> ", 
    "links": [
      {
        "recid": "3600", 
        "title": "/MinBias_TuneZ2_7TeV-pythia6/Summer11Leg-START53_LV4-v1/GEN-SIM"
      }
    ]
  }, 
```

but it is not displayed currently in the HTML templates anywhere.

(1) We should enrich record detailed template to display the pile-up information.

(2) We should also link record 3600 from `http://opendata.cern.ch/about/CMS-Pileup-Simulation`.

(stemmed from https://github.com/cernopendata/opendata.cern.ch/issues/1705#issuecomment-344521384)

**Comment by tiborsimko** [comment]
Example of how this was displayed in COD2: (e.g. record 1671)

![pileup](https://user-images.githubusercontent.com/517546/37667064-690df5e4-2c61-11e8-8084-9309b3613e94.png)

**Comment by katilp** [comment]
The page to link is http://opendata.cern.ch/docs/cms-guide-pileup-simulation

**Comment by tiborsimko** [comment]
So we can: (1) amend fixtures to use the link suggested by @katilp; (2) display `pileup.description` field in the templates; (3) do nothing with `pileup.links` as of yet.

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
