### ISSUE TITLE
Add guides to "About CMS Open Data" page

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1787]
As discussed with @katilp and Achim, we should list the most important guides on the [About CMS](http://opendata-dev.web.cern.ch/about/cms) collaboration page.

We have to decide which resources we want to add to such a box.

So far we discussed:
- [Guide to education use of CMS Open Data](http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data)
- [Guide to research use of CMS Open Data](http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data)

I imagine that we should also add [Getting Started with CMS Open Data](http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-open-data)

Do you think that something else should be there? @katilp

**Comment by katilp** [comment]
@sefeg 

These two guides are quite comprehensive, so in my view the two of them will be enough in About CMS.

I'm a bit hesitant for Getting started, I would not like to distract the readers while they are going through it. Maybe a link to [Research guide](http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data) at the end of the instructions....

**Comment by katilp** [comment]
@atrisovic @RaoOfPhysics Could you take care of this?

**Comment by RaoOfPhysics** [comment]
@atrisovic: Should I?

**Comment by atrisovic** [comment]
you should ;)

**Comment by RaoOfPhysics** [comment]
- [ ] All links to primary, derived etc. are broken and need fixing.

**Comment by katilp** [comment]
Closed by #1941
