### ISSUE TITLE
reduced dataset: invent descriptive file types

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#18]
Enrich small data sample record with ig files and possibly call them:
- csv, json: 4-vectors? slimmed dataset? reduced dataset?
- ig : event displays

**Comment by katilp** [comment]
@tiborsimko Has this been addressed in CODP3?

**Comment by tiborsimko** [comment]
We don't have any description for the derived files in COD3 either. However, since there was not much movement in this issue, and we have not seen many user questions on this either, perhaps the names are already descriptive enough so that we can close the issue.
