### ISSUE TITLE
CMS: New record: Luminosity information for 2012

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1827]
Record as http://opendata-dev.web.cern.ch/record/1051

With the corresponding files:

- summary table
   - all 2012 [lumi2012.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486457/lumi2012.txt)
   - RunB [2012RunBlumi.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486458/2012RunBlumi.txt)
   - RunC [2012RunClumi.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486460/2012RunClumi.txt)
- prescale table [prescale2012.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486463/prescale2012.txt)
- lumi by ls (2012lumibyls.csv) https://cernbox.cern.ch/index.php/s/hRMhtRVOfcA84cU

The following is for memory, not for the record: How to get these files:

Validated runs: Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt see #1262
Run range of RunB and RunC: full 2012 190456- 208686, and only runs in in RunB 193833-196531 and RunC 198022- 203742, see #1263 

Make JSON files 
[RunB2012_JSON.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486444/RunB2012_JSON.txt) and
[RunC2012_JSON.txt](https://github.com/cernopendata/opendata.cern.ch/files/1486448/RunC2012_JSON.txt)

Run brilcalc on lxplus:

```
cmsrel CMSSW_5_3_32 (although the exact version is not relevant)
cd CMSSW_5_3_32
cmsenv

setenv PATH $HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH

# if needed, if not installed: 
pip install --install-option="--prefix=$HOME/.local" brilws
 rehash

brilcalc lumi -i Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt > 2012lumi.txt
brilcalc lumi -i RunB2012_JSON.txt > 2012RunBlumi.txt
brilcalc lumi -i RunC2012_JSON.txt > 2012RunClumi.txt
brilcalc lumi --byls -i Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt -o 2012lumibyls.csv

```
For prescale, see https://github.com/cernopendata/opendata.cern.ch/issues/1138#issuecomment-303674496

**Comment by ArtemisLav** [comment]
@katilp could you please provide a description for this record? Also, do I understand correctly that this is from two run periods?

**Comment by katilp** [comment]
{
    "files": [
        {
            "checksum": "XXX", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012lumi.txt", 
            "size": XXX
        }, 
        {
            "checksum": "XXX", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012RunBlumi.txt", 
            "size": XXX
        }, 
       {
            "checksum": "XXX", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012RunClumi.txt", 
            "size": XXX
        }, 
        {
            "checksum": "XXX", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012lumibyls.csv", 
            "size": XXX
        }, 
        {
            "checksum": "XXX", 
            "uri": "root://eospublic.cern.ch//eos/opendata/cms/luminosity/2011/prescale2011.txt", 
            "size": XXX
        }
    ], 
    "accelerator": "CERN-LHC", 
    "abstract": {
        "description": " <p>The integrated luminosity for validated runs and luminosity sections of the 2012 public data (RunB and RunC) is available in the tables <a href=\"/record/XXX/files/2012RunBlumi.txt\">2012RunBlumi.txt</a> and a href=\"/record/XXX/files/2012RunClumi.txt\">2012RunClumi.txt</a>. (The integrated luminosity for validated runs and luminosity sections of all 2012 p-p data taking is available in <a href=\"/record/XXX/files/2012lumi.txt\">2012lumi.txt</a>.)</p>\n<p>In your estimate for the integrated luminosity, check for which runs the trigger you have selected is active and sum the values for those runs. The uncertainty in the luminosity measurement of 2012 data should be considered as NN% (reference <a href=\"https://cds.cern.ch/record/NNN\">CMS PAS NNN</a>).</p>\n<p>If you are using prescaled triggers, you can find the HLT trigger prescale factors for different run ranges in trigger configuration files listed in <a href=\"http://opendata.cern.ch/record/XXX\">this record</a> (under \"PrescaleService\"). Note that these factors may change during a run, and the change of prescales (run, lumi section, index of prescales) is recorded in\n<a href=\"/record/XXX/files/prescale2012.txt\">prescale2012.txt</a>. In this case you may also need detailed list of luminosity by lumi section in <a href=\"/record/XXX/files/2012lumibyls.csv\">2012lumibyls.csv</a> for the <a href=\"/record/1002\">list of validated runs</a> and lumi sections.</p> "
    }, 
    "recid": "XXX", 
    "date_published": "2017", 
    "run_period": "Run2012B", "Run2012C",
    "publisher": "CERN Open Data Portal", 
    "doi": "XXX", 
    "title": "CMS luminosity information, for 2012 CMS open data", 
    "control_number": "XXX", 
    "experiment": "CMS", 
    "collections": [
        "CMS-Luminosity-Information"
    ], 
    "date_created": "2012", 
    "distribution": {
        "formats": [
            "txt", 
            "csv"
        ]
    }, 
    "type": {
        "primary": "Supplementaries", 
        "secondary": [
            "Luminosity"
        ]
    }, 
    "collaboration": {
        "recid": "451", 
        "name": "CMS Collaboration"
    }
}

**Comment by katilp** [comment]
@ArtemisLav This was based on 2011 record JSON, is it OK? Note all XXX, and for my side I have to check NNN (i.e. the reference number to be cited).

**Comment by katilp** [comment]
Check also the syntax for the two run periods     "run_period": "Run2012B", "Run2012C",

**Comment by katilp** [comment]
@ArtemisLav The error estimate and the reference publication have now been updated above.

**Comment by ArtemisLav** [comment]
That's great, thanks, @katilp. No problem at all with using older records as a skeleton for the JSON. In fact, just to add a note on this, providing a JSON with metadata in the issue is actually a great way (=faster) of working for when you need new records added in my opinion, because you can already see from a similar record what metadata we would need and we skip a couple of steps in the process 😃.

**Comment by ArtemisLav** [comment]
So, we don't have a record for HLT information for 2012, right? What shall we do with `...you can find the HLT trigger prescale factors for different run ranges in trigger configuration files listed in <a href=\"http://opendata.cern.ch/record/XXX\">this record</a> (under \"PrescaleService\")...` ?

**Comment by katilp** [comment]
It is the same (in structure) as http://opendata.cern.ch/record/1700, and  all the information should be in  #1189 for it to be completed. Let me know if there's something missing.

**Comment by ArtemisLav** [comment]
@tiborsimko what is left for this is the files and that recid for the forthcoming HLT 2012 record.

**Comment by tiborsimko** [comment]
@ArtemisLav I have added the files on EOS. Here is the (uri, size, sha1sum) file information:

```
root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012lumi.txt 48284 fda50848945c709b3fba2dda30c9712c86beabc2
root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012RunBlumi.txt 12916 0c63092d2b815e7c6510679b176c007bc1a1f30b
root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012RunClumi.txt 16070 47dcef3072b17f76734bc053f3c4c7bda1078cc9
root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/2012lumibyls.csv 19463607 ea8837412e962faaf1ca452c9f7f4da678d648f2
root://eospublic.cern.ch//eos/opendata/cms/luminosity/2012/prescale2012.txt 49680 14ca08d74f697e106944c1e173ba909915a0f567
```
