### ISSUE TITLE
RFC: anchors for <H> tags for (optional) TOC on long articles/documentation

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1842]
For example, I would like to break the [CMS education guide](http://opendata.cern.ch/docs/cms-guide-for-education) into three sections, aimed broadly at:

- Beginner (event displays etc.)
- Intermediate (histograms etc.)
- Advanced (VM-based analysis etc.)

It would be nice if I could add an optional `{:.toc}` tag at the top to generate a table of contents that links to the header tags for each section.

Is it possible to automatically assign `<a name="#{header-title}">` for this?

(NOT priority: this can wait until after the next data release, of course.)

**Comment by heitorPB** [comment]
New link to the page: http://opendata.cern.ch/docs/cms-guide-for-education

**Comment by RaoOfPhysics** [comment]
Thanks, @heitorPB! I've updated the OP with the correct link.

**Comment by heitorPB** [comment]
It's possible to use the Python-Markdown [TOC](https://python-markdown.github.io/extensions/toc/) extension for this. It automatically assigns an `id="(header-title)"` to each `<hn>Header</hn>` (wiith n the header level) so you can place the `[TOC]` anywhere in the document.

**Comment by RaoOfPhysics** [comment]
Can we implement this, @tiborsimko? :D

**Comment by tiborsimko** [comment]
Yes, we are already using quite a few python-markdown extensions, so we can see about adding this one.

**Comment by heitorPB** [comment]
See [this commit](https://github.com/cernopendata/opendata.cern.ch/commit/854d49f590cf414052aa30f8ec3670c3546c9f5c) for how I updated some markdown extensions.
