### ISSUE TITLE
Subcategories for Documentation and Software

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1846]
Subcategories for Documentation topics:
- Policy: 410 411 412 413
- Help: 57 58
- Activity: 4901 41 330 52 53 61 329 55 50 51 72 60 59 40
- Author list: 450 451 452
- Report: 56
- Guide: add 71 70

Software will follow...

**Comment by tiborsimko** [comment]
@ArtemisLav Can you please see with @katilp and complete the list? I'll then amend the records as needed...

**Comment by tiborsimko** [comment]
Record 402 should be moved from Software to Environment.

**Comment by katilp** [comment]
Software
- Framework 220 3850 212 221
- Tool 550 352 233 200 552 1201 551
- Analysis 560 234 553 4902 101 1200 1202 1203

1000 and 1001 (and the future 1002?) could go to Environment

1203 Tool/analysis?

**Comment by ArtemisLav** [comment]
Thanks @katilp. Most of the subcategories are fine for me; I'm just not sure about `Activity`. Also, for `Author list`, it would probably be better if it was not two words, so that it matches the rest. Perhaps just `Authors`?

**Comment by katilp** [comment]
@ArtemisLav Authors is fine, I'm quite happy with Activity/ies: usually instructions how to use open data in different contexts

**Comment by tiborsimko** [comment]
Hmm, "Documentation > Activities" seems to indeed make sense for the masterclass records we have there...

**Comment by ArtemisLav** [comment]
Sure, it's just not that clear for me, but as you prefer.
