### ISSUE TITLE
UI: styling of the file download box

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1849]
We currently have:

![files-box](https://user-images.githubusercontent.com/517546/33079941-25bcec2e-ced7-11e7-8445-f14e9ef84536.png)

Two observations made by @katilp:

(1) The next/previous links should be styled.

(2) The "EOS Link" is not necessary and may confuse people who click on it.  Let's rather not show this. (Advanced users will get this XRootD location information from the hfile indexes and/or from REST API JSON.)

@pamfilos Can you please have a look when you'll touch the record files?

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in previous PRs.
