### ISSUE TITLE
CMS: VM record for 2012 data release

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1850]
The VM is the same for 2011 and 2012 data release.

Shall we create a new record pointing to the 2011 record? 

Shall we just change the name of the existing record to add 2012 year there?  But what about faceting e.g. when user selects 2012 value from the year facet?  (I'm afraid this field has to be unique in the current data model...)

CC @ArtemisLav @katilp

**Comment by katilp** [comment]
Maybe a new record pointing to the 2011 is the best. 

But:
All 2011 software records can also be used for 2012 data equally, but in the usage instructions we usually specify which datasets to use and they have a definite year. We may need to rethink when software records for 2012 will become available.

**Comment by katilp** [comment]
@tiborsimko NB: the new Higgs to four leptons example combines data from 2011 and 2012 (it must otherwise not enough events for anything visible), so it will need to be 2011-2012. Can this be added? This would then apply for the current 2011 VM as well.

**Comment by ArtemisLav** [comment]
@katilp which option should be implemented? New record pointing to the 2011 record or just a fix for the current record to be 2011-2012? If it's a new record, I would just need a brief description text.

**Comment by daslerr** [comment]
@katilp Did you and @ArtemisLav decide on this? Would this be solved by the wording changes proposed in #2044?

**Comment by katilp** [comment]
Finally we should go as in #2044 The fact is that the new VM version there is not specific to 2012, nor the old to 2011 so I do not want to have them in separate records.
So update as in #2044 and the title and the metadata fields updated to 2011-2012

**Comment by daslerr** [comment]
Great, thanks! I'll close this issue, since the fix will be solved by the tasks in #2044.
