### ISSUE TITLE
Rename and update CMS Getting started pages

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1871]
We have now
http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-open-data for 2010
(Title: Getting Started with CMS Open Data)
and
http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-data for 2011
(title: Getting started with CMS 2011 data)

- [x] Please unify the naming and the titles. The year should appear in the link and in the title.

- [x] Furthermore, the 2010 instructions have content links at the beginning, 2011 does not (add to 2011 page)
- [x] 2010 shows VM keyword (under title), should be Documentation and Guide
- [x] 2011 shows education keyword (under title), should be Documentation and Guide

- [x] The link to VM install instructions is broken on both pages.
Should be: 
http://opendata-dev.web.cern.ch/articles/cms-2010-virtual-machines-how-to-install
http://opendata-dev.web.cern.ch/articles/cms-2011-virtual-machines-how-to-install
(do I understand correctly that http://opendata-dev.web.cern.ch could be omitted in articles?)

- [x]  The link to Physcis object is broken (x3) on both pages
Should be:
http://opendata-dev.web.cern.ch/articles/cms-physics-objects-2010
http://opendata-dev.web.cern.ch/articles/cms-physics-objects-2011

More updates will be needed, I will check and continue.

@atrisovic Would you be able to update?

**Comment by katilp** [comment]
Continue:
Graphics is different:
2011 has the black background for some object, 2010 they are highlighted red (I would prefer the 2010)

The glossary object appear as links in 2011, as nothing in 2010:
Neither is good, they should appear differently but not as links as otherwise it becomes unreadable (maybe a separate issue for @ioannistsanaktsidis ?

**Comment by katilp** [comment]
Contentwise:
we can update under Option A the link name "this CMS Tools entry" to "this CMS analysis example" and the link is:
2010: http://opendata-dev.web.cern.ch/record/560 
2011: http://opendata-dev.web.cern.ch/record/5001

In 2011 guide, everything starting  from "Before you proceed", to Option B (i.e. the 5 steps) can be removed.

**Comment by RaoOfPhysics** [comment]
@atrisovic: Please let me know if you would like me to take care of this issue.

**Comment by katilp** [comment]
Adding mentions of 2012 to the 2011 instructions:
- At the beginning: To analyse CMS data collected in 2011 -> To analyse CMS data collected in 2011 and 2012
- Under Option B: With the 2011 data -> With the 2011 and 2012 data

Add mention about different condition data for 2011 and 2012

- you have to set the symbolic links to the condition database. -> you have to set the symbolic links to  the condition database for 2011 data.
- after ln -s commands add:
Make sure the `cms-opendata-conddb.cern.ch` directory has actually expanded in your VM.  One way of doing this is executing:
```
ls -l
ls -l /cvmfs/
```
- after global tag code snippet add: This is example is reading 2011 RunA data. If you reading data from other run periods or simulated data, use the following:

| Data        | VM           | Global tag  | Validated runs |
| -------- - |:-----------:| ------------:| ---------------- |
| 2010 RunB      | [2010 VM](/record/250 |  | [2010 list](/record/1001) |

**Comment by atrisovic** [comment]
thanks @RaoOfPhysics I am now on it, I'll let you know if I need help ;)
