### ISSUE TITLE
Article display on the landing page

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1876]
After having placed the first two articles (with their images) on the landing page, consensus was that the page design suffers from the images being too colorful and not representing the portal's message ("why is their an image with an umbrella?")

This is to propose a slightly modified article display. As has been proposed in #1483, we could display images only for selected articles. For example, only one article could be assigned an image (top row of the following image), or we could have a dynamic presentation in which the space for two or three non-image articles can be replaced by one article with an image.

![31770797-c487d9c6-b4d9-11e7-887b-6782d94c51d0](https://user-images.githubusercontent.com/25487025/33202103-717e7dfa-d0fb-11e7-902a-ef4b798431c7.png)

We did not see an immediate need to implement the above proposal back then. Having seen now, how difficult the selection of images can be (and we only tried with two articles), it could relief pressure of finding suitable images for every single article on the landing page. 

For the moment, I assigned RFC status @daslerr @suenjedt @tiborsimko

**Comment by RaoOfPhysics** [comment]
FWIW, from my side, the proposal both looks good and sounds like a reasonable compromise.

**Comment by sefeg** [comment]
@ioannistsanaktsidis is adapting a design proposal for the landing page which displays the three sections (top image / navigation, articles and visualization tools) as blocks that use 100% of the browser's height. The article section will be displayed as proposed above.

**Comment by ioannistsanaktsidis** [comment]
Closing as we have already decided the new implementation. @pamfilos  is preparing a sketch .
