### ISSUE TITLE
Mistake in subtitle in About CMS 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1879]
In About CMS http://opendata-dev.web.cern.ch/about/cms
subtitle "Data Policies Primary and simulated datasets" should be "Primary and simulated datasets"

**Comment by RaoOfPhysics** [comment]
@atrisovic: Happy to take this if you want.

**Comment by atrisovic** [comment]
don't worry @RaoOfPhysics i can just put it in the current PR
