### ISSUE TITLE
VM records 250 and 252, broken or oudated links

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1883]
In 
http://opendata-dev.web.cern.ch/record/250
http://opendata-dev.web.cern.ch/record/252
links should be:

Issues and limitations:
250: http://opendata-dev.web.cern.ch/docs/cms-2010-virtual-machines-how-to-install#issues2010
252: http://opendata-dev.web.cern.ch/docs/cms-2011-virtual-machines-how-to-install#issue

How can you use these data?
250: http://opendata-dev.web.cern.ch/docs/cms-2010-virtual-machines-how-to-install
252: http://opendata-dev.web.cern.ch/docs/cms-2011-virtual-machines-how-to-install

**Comment by tiborsimko** [comment]
Note that these records use absolute URLs (`opendata.cern.ch/foo`) while they should rather be using relative ones (`/foo`) so that the links would work on DEV, QA, PROD... whatever the base URL. This is true for many other records, not only the above ones; I'll fix it globally.

**Comment by katilp** [comment]
Corrected the links above articles -> docs
