### ISSUE TITLE
Style changes

### ISSUE THREAD

**Issue by atrisovic** [cernopendata/opendata.cern.ch#1886]
Graphics is different:

- [ ] 2011 has the black background for some object, 2010 they are highlighted red (I would prefer the 2010)

- [ ] The glossary object appear as links in 2011, as nothing in 2010:
Neither is good, they should appear differently but not as links as otherwise it becomes unreadable

**Comment by katilp** [comment]
This refers to differences between
http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2010-open-data 
http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-open-data

**Comment by katilp** [comment]
NB, the glossary terms behave in differently in http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-open-data than some other paged: here they are links whereas on other pages the explanation opens when hovering over

**Comment by RaoOfPhysics** [comment]
1. The glossary-terms-as-links also causes an additional problem in that clicking on them merely takes you to the top of the current page, as the anchor tag goes nowhere.
1. The glossary terms break the header tags on some (and only some) pages:
    - Same size as rest of header on e.g. http://opendata-dev.web.cern.ch/articles/cms-pile-up-simulation <img width="957" alt="firefox - - screen shot 28 nov 2017 at 10 19 21" src="https://user-images.githubusercontent.com/7623019/33311622-b160ae48-d425-11e7-889f-90436c063a6a.png">
    - Different size than rest of header on e.g. http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data <img width="958" alt="firefox - - screen shot 28 nov 2017 at 10 19 02" src="https://user-images.githubusercontent.com/7623019/33311648-d038f71c-d425-11e7-8f7e-add661e0e8e7.png">

**Comment by heitorPB** [comment]
I guess this was fixed meanwhile

**Comment by tiborsimko** [comment]
@heitorPB Not completely, e.g. the "code" markup is still different, note the "black background" vs "red foreground" style of highlighting:

- http://opendata-dev.web.cern.ch/docs/cms-getting-started-2010
- http://opendata-dev.web.cern.ch/docs/cms-getting-started-2011
