### ISSUE TITLE
templates: proper display of the record "CMS Simulated dataset names"

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1888]
Can we remove http://opendata-dev.web.cern.ch/record/71 it is totally useless. We need: http://opendata.cern.ch/about/CMS-Simulated-Dataset-Names but I can't find it on dev, does it exist?

**Comment by ioannistsanaktsidis** [comment]
@katilp  http://opendata-dev.web.cern.ch/about/cms-simulated-dataset-names
Also here nginx layer should take care. cc @tiborsimko  @hjhsalo

**Comment by katilp** [comment]
@ioannistsanaktsidis @tiborsimko Any news on this, where should I link for this file? Will it stay in /about/ or become /docs/ ? As it is now, it does not appear in search.

**Comment by tiborsimko** [comment]
On the first level, this is not about redirections, because this record was already published. We just need to update the record template update to missing abstract link information.  Compare:

- COD2 http://opendata.cern.ch/record/71
- COD3 http://opendata-dev.web.cern.ch/record/71

(later on we can muse on revamping "record" pages and related "docs" pages...)

**Comment by tiborsimko** [comment]
Ditto for the CMS Pileup Simulation record; please compare:

- COD2 http://opendata.cern.ch/record/70
- COD3 http://opendata-dev.web.cern.ch/record/70

Anybody having time to look at amending record templates?  @hjhsalo? @diegodelemos?

The source record recid 70 or 71:

```
  "abstract": {
    "description": "Monte Carlo simulation of pile-up is controlled by the code and configuration files of the package  SimGeneral/MixingModule. An input distr
ibution is specified for each set of production samples which is supposed to represent the distribution of the mean number of interactions seen during data-tak
ing. Below you can find more information on how the simulation proceeds:", 
    "links": [
      {
        "url": "/about/CMS-Pileup-Simulation"
      }
    ]
  }, 
```

The template to edit:

`./cernopendata/templates/cernopendata_records_ui/records/record_detail.html`

Other random records that use the "abstract" field should be then checked if they still display OK.

**Comment by diegodelemos** [comment]
It has to be rendered exactly as it was in COD2?

I have noticed that we have several ways of rendering `links`:
```console
$ git grep 'for link'
cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html:                  {% for link in record.validation.links %}
cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html:                  {% for link in record.usage.links %}
cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html:                  {% for link in record.note.links %}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:              {% for link in record.use_with.links %}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:                {% for link in record.note.links %}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:                    {% for link in record.links%}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:                    {% for link in record.methodology.links %}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:                  {% for link in record.validation.links %}
cernopendata/templates/cernopendata_records_ui/records/record_detail.html:                  {% for link in record.usage.links %}
cernopendata/templates/cernopendata_records_ui/records/software_detail.html:                    {% for link in record.use_with.links %}
cernopendata/templates/cernopendata_records_ui/records/software_detail.html:                    {% for link in record.validation.links %}
```
if I have to add yet another if, what should I assume that `links` will have when it appears under `abstract`? cc @tiborsimko

**Comment by tiborsimko** [comment]
@diegodelemos The `links` field and its properties should be prety much the same across all the fields, so we should be able to simplify this and introduce a macro. Hopefully there is no need to display them differently... @ioannistsanaktsidis was trying out all the various collections and so can estimate whether there were some important differences... I hope we shall be able to go for a common strategy displaying each new link on a new line, etc.

**Comment by katilp** [comment]
Is the fact that http://opendata-dev.web.cern.ch/about/cms-simulated-dataset-names does not show directly in search http://opendata-dev.web.cern.ch/search?page=2&size=20&q=&type=Documentation&experiment=CMS# being taken care of?
Is there any reason why it should be under ../about/.. and not in .../docs/... as everything else?

**Comment by ioannistsanaktsidis** [comment]
@katilp it should be under /docs as you indicated.

**Comment by katilp** [comment]
@ioannistsanaktsidis OK, very good! Will someone move it there 😃 ? NB, updates to all simulated data records needed (or redirecting), see e.g. http://opendata-dev.web.cern.ch/record/1333

**Comment by ioannistsanaktsidis** [comment]
cc @atrisovic  Could you please take care of that ?

**Comment by atrisovic** [comment]
@ioannistsanaktsidis @katilp there is a new entry in docs cmd-simulated-dataset-names in my new PR #2011

**Comment by atrisovic** [comment]
maybe we can merge the PR?

**Comment by ioannistsanaktsidis** [comment]
Fine by me, just need to be approved from @tiborsimko  or @daslerr :)

**Comment by ioannistsanaktsidis** [comment]
@atrisovic your PR redirects the record to http://127.0.0.1:5000/docs/cms-dataset-names ? Is this intended ? Shouldn't it be /docs/cms-simulated-dataset-names ?

**Comment by atrisovic** [comment]
yes, that is how the article is called. I put it like that because it's shorter.

I can change it in the next PR if there are any problems with it?

**Comment by ioannistsanaktsidis** [comment]
I guess it is wanted like in COD2 for compatibility reasons. cc @katilp  ?

**Comment by katilp** [comment]
@ioannistsanaktsidis I'm not sure if I understand correctly but in summary we would like to

- have this page appear in the documentation search
- update the links to it in the records for simulated data
- and in addition, eventually, not show the double page  http://opendata-dev.web.cern.ch/record/71 in documentation search (because the other one is enough and brings the reader directly to the information)

For compatibility, do you mean eventual external links to this page?

**Comment by atrisovic** [comment]
@katilp we are thinking if  `/docs/cms-dataset-names` is a good url location for the article, maybe it should be `/docs/cms-simulated-dataset-names`. what do you think?

it should appear in the search once the article (document) is there

**Comment by katilp** [comment]
@atrisovic better `cms-simulated-dataset-names`  indeed, as it is only about MC
