### ISSUE TITLE
Need year as a search facet for CMS software

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1891]
We would need year of data 2010 or 2011 (maybe 2011-2012, and 2012 in the future) for CMS software records, it is very difficult to find anything now. 
For now:

2010: 101 550 461 462 460 200 220 553 552 560
2011: 234 551 5001 5000 233 221
2012 or 2011-2012: 221

~~1000 and 1001 should go to Category Environment subcat Validation~~ Done!

**Comment by katilp** [comment]
Add
2010: 5003
2011: 463 464 5004

**Comment by ArtemisLav** [comment]
5100
72
560
551
464
5103
461
451
450
5101
70
460
71
234
262
463
233

**Comment by ArtemisLav** [comment]
The following records show up for years 2014, 2016 & 2017:
70
71
72
233
234
450
451
460
461
262
463
464
551
560
5100
5101
5103

@katilp there is no issue in the JSON for some of the recids you mention: 101, 200, 220, 5000, 5001, 5003, 5004. And for 221, it is currently under 2011; should it go to 2012? You placed it in both in your first comment.

**Comment by katilp** [comment]
Some of the records you listed listed are connected to documents not to software, those are not necessarily on my list which hopefully covers SW

A search use-case is "what are the software records which can be used with the data from data-taking NNN"
221 is CMSSW which can be used both for 2011 and 2012. 
Therefore, we need 2011-2012 in addition. It will also be needed for the new Higgs example (will be 5500) and will probably be useful for many others

**Comment by ArtemisLav** [comment]
OK, what about record 72?

**Comment by katilp** [comment]
72 is not a software record but under documentation.
If a specific data-taking year is given, it should be 2010-2012 (as all other education "stuff", i.e. event display, notebooks and spreadsheet )
