### ISSUE TITLE
templates: header badges for records

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1894]
Currently the COD3 record pages show COD2-style "header" featuring the prominent concept of collections:

![record-header](https://user-images.githubusercontent.com/517546/33241684-4151e7f0-d2c9-11e7-9e4a-fd66718471ea.png)

(Note "Collection: CMS-Primary-Datasets" there.)

Since we try to hide the concept of collections, I propose to rather display there the information about `type.primary`, `type.secondary`,  possibly in a nice form of badges.

(stemmed from https://github.com/cernopendata/opendata.cern.ch/issues/1856#issuecomment-346303362)

**Comment by katilp** [comment]
👍 to replace collections. The other information (energy, exp, accelerator) will stay?

**Comment by tiborsimko** [comment]
The others look OK, but we can surely rethink the banner and amend them at the same time as well!

**Comment by katilp** [comment]
The other look OK to me as they are now, they are solid, basic information and not as likely to change as the collections concept.
