### ISSUE TITLE
File index display appears with no files, does not show file names

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1896]
Observe while reviewing http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data:

- [x]  http://opendata-dev.web.cern.ch/record/53 has file index part even if it does not have files

- [x] file names does not display in http://opendata-dev.web.cern.ch/record/50

**Comment by pamfilos** [comment]
@katilp @tiborsimko file names are not display because files are not uploaded (or upload was not completed)
