### ISSUE TITLE
articles: unsaturated photo colours in the CMS summer student report

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1898]
The CMS summer student report photo is not very saturated to me.  Compare:

- https://user-images.githubusercontent.com/25487025/32649886-0456f0f4-c5fc-11e7-9616-de2ff76e0e9d.png
- http://opendata-dev.web.cern.ch/static/articles/cms-summer-student-report-2017/opendatasummer.jpeg

Was it manipulated in some way that led to the colour space issues? Adobe RGB, sRGB, and friends? Have you checked the looks on Linux, Mac, Windows? 

![cms-summer-students-photo](https://user-images.githubusercontent.com/517546/33256935-86878bb4-d354-11e7-92d2-8c7615a98be0.png)

**Comment by sefeg** [comment]
As discussed during the daily, the saturation changed because of design issues and lead to #1876, which proposes to support articles that don't display an image on the landing page.

**Comment by ioannistsanaktsidis** [comment]
Closing as for now I replaced it with the original image, yet as we discussed we most probably going to drop images from articles except one.
