### ISSUE TITLE
capital letter link http://opendata-dev.web.cern.ch/visualise/events/CMS does not work

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1899]
The link http://opendata-dev.web.cern.ch/visualise/events/CMS still does not work, while http://opendata-dev.web.cern.ch/visualise/histograms/CMS is OK. Is this expected?
Both work with cms

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  this one should be taken care on the nginx layer. cc @hjhsalo

**Comment by ioannistsanaktsidis** [comment]
Closing as it is working now after the latest updates.
