### ISSUE TITLE
Make "Expand" / "Collapse" buttons look like buttons?

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1911]
The `+`/`-` symbols next to categories with sub-categories are not clear enough for end users (and the `-` in particular is too small). Can these be replaced by something like `>`/`v`?

**Comment by tiborsimko** [comment]
BTW, now that we are displaying more facet values in a compact manner (neat!), see:

- http://opendata-dev.web.cern.ch/search

We can perhaps have the type sub-categories expanded by default?  It would help to advertise the content more prominently... giving something like: 

![search](https://user-images.githubusercontent.com/517546/33365538-d03e264c-d4e8-11e7-8745-e9d44b93c63b.png)

**Comment by tiborsimko** [comment]
... or, to take into account the new types introduced in #1925, we have this:

![search2](https://user-images.githubusercontent.com/517546/33365901-026f48f2-d4ea-11e7-8071-5bf0788b89e1.png)

We can update the structure some more, e.g. what about moving "News" and "Glossary" under "Documentation"?  I think it would make sense from the data organisation point of view, and it would even help to improve things visually in my eyes... CC @sefeg @daslerr @ArtemisLav 

(Well, I would even suggest to rename "News" into "Announcements" or something, as we mused about it elsewhere... but that's for another tangent.)

**Comment by RaoOfPhysics** [comment]
I like the idea of expanding sub-categories by default. I wouldn't put News under Documentation, but putting Glossary there makes sense.

**Comment by tiborsimko** [comment]
... another thing, taking into consideration that "supplementaries" is plural and words like "software" or "documentation" are already semi-plural, would be to consider standardising on using the plurals in the top-level primary categories everywhere? This would give:
- Datasets
- Documentation
- Environments
- Software
- Supplementaries

**Comment by tiborsimko** [comment]
@annatrz @ioannistsanaktsidis I see this is closed already, but what about the above musings regarding the type facet to be expanded-by-default? @RaoOfPhysics seemed to like it, and I did not notice any other contrary opinions...

**Comment by tiborsimko** [comment]
... reopening so that we won't forget. 😄

**Comment by RaoOfPhysics** [comment]
Update: Looks super nice! One Q, @annatrz and @tiborsimko: Do we need bullets for sub-categories when there are no bullets for categories themselves (besides the checkboxes)?

**Comment by tiborsimko** [comment]
@RaoOfPhysics Probably not, although it may be good to retain this possibility in case we'd like to offer people a chance to close some facets they are not interested at...Kind of like ADS is doing https://github.com/cernopendata/opendata.cern.ch/issues/1917 but lighter...
