### ISSUE TITLE
"Visualise CERN data" vs "Visualise our data"

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1912]
Are experiments happy to call them "CERN data"? @katilp?

**Comment by katilp** [comment]
@RaoOfPhysics According to the feedback I've got earlier for a similar wording, CMS prefers CMS data

**Comment by RaoOfPhysics** [comment]
So, for a generic title, we should probably go for "Visualise our data", above data from CMS, OPERA etc.

**Comment by katilp** [comment]
Or plain "Visualise data" or "Visualise open data", leaving out "our"?

**Comment by tiborsimko** [comment]
Yes, I  fully agree that it should be changed... We did not use such an expression on COD2 either... 

We had called the menu simply "Visualise" in our new home page musings. (#1940)
