### ISSUE TITLE
RFC: HTTPS for launch of upgraded portal

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1913]
@tiborsimko, I recall discussing migrating `opendata.cern.ch` to HTTPS at some stage. Are there plans for doing this for the forthcoming launch of the upgraded portal?

Related: #826

**Comment by tiborsimko** [comment]
Yes; see https://github.com/cernopendata/opendata.cern.ch/issues/1333.

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Nice! So I guess I can close this issue. Sorry about the duplicate.
