### ISSUE TITLE
search: Broken links from old portal to new –– will we have redirects?

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1914]
Pages like the following are broken:

- [x] http://opendata-dev.web.cern.ch/about/CMS-Physics-Objects/2011
- [x] http://opendata-dev.web.cern.ch/collection/CMS-Primary-Datasets

Will these be redirected to the new relevant URLs?

**Comment by tiborsimko** [comment]
The first URL is problematic indeed, the redirection is missing.

The second URL is OK, since it is already redirect to a search page.  (May take a second...)

**Comment by tiborsimko** [comment]
Reminder of all `/about/*` pages to check:

- [ ] /about
- [ ] /about/ALICE
- [ ] /about/ATLAS
- [ ] /about/CMS
- [ ] /about/CMS-Physics-Objects
- [ ] /about/CMS-Physics-Objects/<string:year>
- [ ] /about/CMS-Pileup-Simulation
- [ ] /about/CMS-Simulated-Dataset-Names
- [ ] /about/LHCb
- [ ] /about/alice
- [ ] /about/atlas
- [ ] /about/cms
- [ ] /about/lhcb

I thought they were all done in the autumn...

(see the full old URL list in https://github.com/cernopendata/opendata.cern.ch/issues/1228#issuecomment-292994773)

**Comment by atrisovic** [comment]
some of the views are there, but they are case sensitive

**Comment by hjhsalo** [comment]
Here is the updated list of URL, their redirect and status (working or not)

(Not CS == not case-sensitive)
- [x] /about
- [x] /about/ALICE --> /about/ALICE (Not CS)
- [x] /about/ATLAS  --> /about/ATLAS (Not CS)
- [x] /about/CMS --> /docs/about-cms (Not CS)
- [ ] /about/CMS-Physics-Objects --> **PAGE NOT FOUND** (Should redirect to /docs/cms-physics-objects-2011)
- [ ] /about/CMS-Physics-Objects/<2010|2011|2012> --> **PAGE NOT FOUND** (Should redirect to /docs/cms-physics-objects-yyyy)
- [x] /about/CMS-Pileup-Simulation --> /about/CMS-Pileup-Simulation (Not CS)
- [x] /about/CMS-Simulated-Dataset-Names --> /about/CMS-Simulated-Dataset-Names (Not CS)
- [x] /about/LHCb --> /about/LHCb (Not CS)
- [x] /about/alice --> /about/alice (Not CS)
- [x] /about/atlas --> /about/atlas (Not CS)
- [x] /about/cms --> /docs/about-cms (Not CS)
- [x] /about/lhcb --> /about/lhcb (Not CS)

**Comment by atrisovic** [comment]
Ugh I am working on this x)

but not on enabling CS, just redirection

**Comment by hjhsalo** [comment]
OK. Thanks.

> but not on enabling CS, just redirection

Correct. Nginx should handle CS.

**Comment by daslerr** [comment]
Closing, as all the redirects in the lists above are now implemented. There's no redirect for /about/CMS-Physics-Objects/2012 because 2012 CMS physics objects weren't released on COD2.
