### ISSUE TITLE
templates: Inconsistencies in types of articles/pages

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1917]
- http://opendata-dev.web.cern.ch/about/cms-simulated-dataset-names
- http://opendata-dev.web.cern.ch/articles/cms-physics-objects-2011

But I guess this is being resolved. Feel free to close…

**Comment by tiborsimko** [comment]
Yes, we had discussed that all "simple pages" (such as about) should be turned to "docs" (the old name "articles") and ideally even ported to Markdown... The `/about` could be kept for future reference.

Not sure whether this was ticketised properly?  Need nice slugs... #1753 

@dassler @atrisovic Have you started looking into this?

**Comment by atrisovic** [comment]
yes

**Comment by atrisovic** [comment]
Suppressed by `docs`.
