### ISSUE TITLE
Rename "events" to "collisions"

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1920]
Why:

- The target audience is non-physicists.
- "Events" mean something different to a non-physicist audience.
- "Collisions" are clearer. People know that they shouldn't be looking for a calendar of happenings (events).

- [ ] Text will need to be changed.
- [ ] URLs will need to be changed and redirected.

Pinging @katilp, @tpmccauley, @tiborsimko.

**Comment by katilp** [comment]
@RaoOfPhysics I agree, "Collisions" is clear, "Events" can be confusing

**Comment by tiborsimko** [comment]
@RaoOfPhysics Rename where? Which pages did you have in mind?

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Across the portal, whenever we're speaking to a non-physics audience. So, even things like `/visualise/collisions` in the URLs instead of `/visualise/events` and saying "collision visualiser" instead of "event visualiser".

**Comment by atrisovic** [comment]
I don't agree with this one... the word `event` is appearing already `31 029` times in COD and it's part of the common terminology (even across the experiments)

**Comment by RaoOfPhysics** [comment]
But the target group for the event displays are not experimentalists… The term means something completely different for those who are most likely to visit the visualisers.

**Comment by RaoOfPhysics** [comment]
Any thoughts on this prior to launch?

**Comment by ioannistsanaktsidis** [comment]
We can revisit this after the release as it might require some effort to change it everywhere. Moving to someday.

**Comment by heitorPB** [comment]
Another approach would be to add `events` to the glossary. This way there's no need to change the urls and would solve the possible confusion to non-physicists.
