### ISSUE TITLE
Changes to documentation/guide pages.

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1921]
- [x] Manually link "related" content on pages like "Physics Objects"
    - On the old portal, a page like "CMS Physics Objects" has tabs for 2010 and 2011: http://opendata.cern.ch/about/CMS-Physics-Objects/
    - This is useful since they're both "related" to one another with a lot of similar padding/explanation/intro on the top.
    - On the new portal, these are separate pages entirely:
        - http://opendata-dev.web.cern.ch/articles/cms-physics-objects-2010
        - http://opendata-dev.web.cern.ch/articles/cms-physics-objects-2011
    - The new style is problematic because it's not clear to an end user that other pages of related content exist. Can we "virtualise" such tabs by having links to related content appear at the top of such pages as buttons or something?
- [x] ~Pin title to top of long documentation pages -- it can get confusing to recall which page you're surfing otherwise.~
- [x] Links to specific objects need to be fixed on new portal:
    - On the old portal, one could link to, e.g., http://opendata.cern.ch/about/CMS-Physics-Objects/2010#electron2010
    - It's not obvious if this can be done on the new portal?

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
