### ISSUE TITLE
Show date for news

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1927]
Current news items (http://opendata-dev.web.cern.ch/search?page=1&size=20&type=News) do not show date anywhere.

It should be added, also for the old items  and in particular to the old CMS release note (http://opendata-dev.web.cern.ch/articles/cms-releases-new-batch-of-research-data-from-lhc) in order to avoid confusion with the new one

**Comment by tiborsimko** [comment]
We should display it at least on the detailed record page...

P.S. See also the issue I had opened in the past about dispaying dates for news (#1452). We should do it everywhere for "articles" style of "posts"...
