### ISSUE TITLE
Update featured article from the MIT group

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1931]
Jesse has written the text, which can be featured on the portal: http://www.jthaler.net/doku.php?id=playground:cmstest

In his message he says that "Please let me know if you have any suggestions for improving the text, adding links, etc.  I decided to write a longish entry in order to capture as many aspects of the project as I could."

I'm very happy with it, it is true that it is long but I believe that any potential research user should have the patience to read it through 😃

**Comment by RaoOfPhysics** [comment]
Yes, it's a great text! I have some minor comments for him anyway. :)

Maybe we shouldn't link to it publicly just yet, though? Thoughts?

**Comment by katilp** [comment]
Create a template file so that we can copy the news article there @tiborsimko?

**Comment by RaoOfPhysics** [comment]
@katilp: Is it OK to wait until I have the final draft from Jesse? I have some feedback to give him and would like us to take his final text and upload that directly, rather than iterate on two platforms for now (e-mail and the portal). I hope that's OK?

**Comment by tiborsimko** [comment]
@atrisovic Can you please introduce a new `docs` page for this? Beware of slugs...

**Comment by atrisovic** [comment]
yes

**Comment by RaoOfPhysics** [comment]
It would've been good to wait until the final version of the text was ready before uploading this, per my request above… :(

**Comment by atrisovic** [comment]
sure you can make adjustments or replace the text. I just created the files for it and also for the guide for the condition databse (which doesn't have anything in it)

**Comment by RaoOfPhysics** [comment]
Repurposing the same issue to update the text. I hope that's OK.
