### ISSUE TITLE
Remove "above" in SW record 460 461 462 + add github link

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1935]
In:
http://opendata-dev.web.cern.ch/record/460
http://opendata-dev.web.cern.ch/record/461
http://opendata-dev.web.cern.ch/record/462

remove "above" in "To run the NNN sample validation, follow the instructions in the file readme.txt above" (the readme.txt appears below...)

and add
- in 460: "or follow the instructions in the github repository https://github.com/cms-opendata-validation/2010-mu-mumonitor-dimuon/tree/v.1.0.0"
- in 461: "or follow the instructions in the github repository https://github.com/cms-opendata-validation/2010-commissioning-dimuon/tree/v.1.0.0"
- in 462: "or follow the instructions in the github repository https://github.com/cms-opendata-validation/2010-minimumbias-trackvertex/tree/v.1.0.0"

**Comment by tiborsimko** [comment]
This raises a more general question about the box ordering on the detailed record pages... currently it does not follow COD2 order. Do we want to change the order how the information is preserved? Or go back to COD2 order?  E.g. I had mentioned "File indexes" before "Files" to @pamfilos @ioannistsanaktsidis... Let's muse about the box display order before amending record metadata information.  (That one would be the best formulated in a presentation-agnostic style anyhow...)
