### ISSUE TITLE
facets: data-taking year vs record-upload year

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1944]
Currently, the year facet looks like:

![facet-year](https://user-images.githubusercontent.com/517546/33384168-8bab7402-d525-11e7-89c4-204aa767dbaf.png)

Some UX issues here to consider:

- It looks like we only have 3 records added in 2017... as if we were inactive.. this is not good.  

  This is obviously because the "year" facet prefers to use "data taking year", so all new records are uploaded with 2012.  Perhaps we should rename the facet and use it for "data taking" year, or perhaps we should use it for "upload year" because this is what most lambda users would understand... Or perhaps we can simply index both the data taking year and the record-upload year in the same facet... (yeah, that might also be confusing).

- The value "2010-2012" does not look that good there.  If we have a need for storing multiple year values, then perhaps we should amend the data model to allow lists instead of single values?

Any thoughts?

(see also https://github.com/cernopendata/opendata.cern.ch/issues/1189#issuecomment-347898882)

**Comment by RaoOfPhysics** [comment]
I think it's important to note the year the data were collected from the collisions as this is the number of interest from a scientific perspective. This also implicitly provides us (i.e., those in the know) with information on running conditions (e.g.: 2010 was at 7 TeV, 2011 and 2011 was at 8 TeV, etc.) When we actually upload open data is of relatively less consequence or interest.

Can it simply say "Year of data collection" or something similar?

**Comment by katilp** [comment]
@tiborsimko correct... for data records, the data taking time is now determined by "run_period": "Run201aA" (or other) and  "date_created": "2011", it would be best to have "data taking year" as well.
But here we would need it for two purposes
- the direct indication of year of data taking for datasets (which is now given by run_period and data-created)
- but also, and importantly, for SW records, where we would need values 2010, 2011, 2012 and also 2011-2012 (for example for CMSSSW and for the Higgs example) 
- 2011-2012 facet could also be needed for some rare derived datasets, now for example an event dislpay set,

**Comment by heitorPB** [comment]
#2463 defines the new structure for `run_period`:
list of strings in the format:
- [`RunYYYYX`] for collision data
- [`RunYYYY`] for MC data

The records should be updated accordinly (#2489)

**Comment by tiborsimko** [comment]
Note that this issue is about `date_created` and related `date_*` fiields, not about `run_period` which is addressed elsewhere.  However, we can use the same technique as was used for `run_period` and, instead of having `date_created` being equal to `2010-2012`, we could use:

```json
   "date_created": [
      "2010",
      "2011",
      "2012"
   ]
```

See my RFC musings in https://github.com/cernopendata/opendata.cern.ch/issues/2463#issuecomment-446126410

**Comment by tiborsimko** [comment]
Discussion with @ArtemisLav: make `date_created` a list, amend serialisers to display the final year for those use cases that need a single value (JSON-LD/schema.org).

Rename facet to "data-taking year" or somesuch.

Possibly rename of field to something like `data_taking_years` later.
