### ISSUE TITLE
CMS: Quick start instructions in research guide

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1953]
We should have two quick start links right at the start of Research guide:

- Install VM: http://opendata-dev.web.cern.ch/articles/cms-2011-virtual-machines-how-to-install
- Get started with data: http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-data

The guide looks quite complicated now, and it would help to say at the beginning that this is alll you need to get started, rest is just useful information. @RaoOfPhysics What do you think?

**Comment by RaoOfPhysics** [comment]
Something like:

> For step-by-step instructions to start working with CMS Open Data, please consult these pages:
> 1. Install Virtual Machine
> 1. Get started with CMS Open Data

?

**Comment by katilp** [comment]
OK, sounds good, that could come right after:
"If you are interested in conducting a research-oriented analysis using CMS Open Data, you should find hints, tips and guidance on this page. Please note that possible solutions to frequently encountered issues can be found on our page of known errors."

Any suggestion for wording for what follows, i.e we may need then some explanatory words before "Quick introduction"...

**Comment by RaoOfPhysics** [comment]
How about restructuring the text like this:

> If you are interested in step-by-step instructions to start working with CMS Open Data, please consult these pages:
> 1. Install Virtual Machine
> 1. Get started with CMS Open Data
>
> However, if you are interested in finding hints, tips and guidance for conducting a research-oriented analysis using CMS Open Data, please see our notes on this page. Note that possible solutions to frequently encountered issues can be found on our page of known errors.

**Comment by katilp** [comment]
The links are:
1. http://opendata-dev.web.cern.ch/articles/cms-2011-virtual-machines-how-to-install
2. http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-open-data

but if I understand correctly now: articles -> docs

**Comment by ioannistsanaktsidis** [comment]
@katilp  yes after we merge my PR this becomes /docs
