### ISSUE TITLE
templates: Broken link on CMS Research Guide page

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1954]
- "Getting started with CMS 2010 open data"(/articles/getting-started-with-cms-2010-open-data)

**Comment by atrisovic** [comment]
It works for me http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2010-open-data

**Comment by atrisovic** [comment]
ah I see what you are saying, I can add this to an existing PR

**Comment by atrisovic** [comment]
fixed ✅ thank you!

**Comment by katilp** [comment]
@atrisovic Is it easy to add also #1953 now? We can also do it later if better?

**Comment by atrisovic** [comment]
Yes, it should be easy to do, I will add it to the PR
