### ISSUE TITLE
Missing subcategories for SW and Documentation

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1956]
Software:

- 555 Tool
- 463 464 Validation

Documentation

- 54 Activities
- 56 Report (only one in this category, for the time being)
- 57 58 Help 

To my view, Help pages are different from Guides (to some wider topic) or About (information on a concept) in the sense that they are directly tied to a well-defined activity.

In addition:

- 70 almost empty record corresponding to the real page http://opendata-dev.web.cern.ch/articles/cms-pile-up-simulation (but also  http://opendata-dev.web.cern.ch/about/cms-pileup-simulation exists) , can possibly be kept if it would contain the plots (and eventually the numbers in plots) for the about page, see also #1915
- 71 almost empty record  for http://opendata-dev.web.cern.ch/about/cms-simulated-dataset-names , 71 should be removed. The real record does not appear under Documentation, can this be fixed? See also #1888

**Comment by katilp** [comment]
In addition: 

- 5001 should be Analysis, not Validation

**Comment by ArtemisLav** [comment]
@katilp @tiborsimko WRT records 70 and 71, is the discussion for those moved to #1888? If so, this issue can be closed with this PR
