### ISSUE TITLE
records: generate CMS 2012 HLT configuration files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1961]
Stemmed from #1189

**Comment by tiborsimko** [comment]
> https://github.com/cms-sw/cmssw-cvs/releases (not in the usual https://github.com/cms-sw/cmssw as it is approaching size limit):

@katilp Besides the above, I noticed also that trailing "_ONLINE" was dropped, for example there is:

- https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_5_2_4_onlpatch1

while we used to have:

- https://github.com/cms-sw/cmssw/tree/CMSSW_4_2_7_onlpatch3_ONLINE

Is that OK?

**Comment by katilp** [comment]
Yes, that's OK. "_ONLINE" was dropped, it was added by mistake for the previous tags when the data-taking releases were tagged  (but the mistake as such does not matter because it was only a slight deviation of CMS internal practices  ).
