### ISSUE TITLE
Add collaboration keyword to author lists  

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1962]
The collaboration lists 
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&subtype=Authors
do not show collaboration keyword, and do not show in search CMS and Authors:
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&subtype=Authors&experiment=CMS

**Comment by tiborsimko** [comment]
Actually, they have the collaboration keyword already:

```
  "collaboration": {
    "name": "CMS collaboration"
  }, 
  "collections": [
    "Author-Lists"
  ], 
```

but they don't have `experiment` keyword... I'll add it.
