### ISSUE TITLE
CMS author list for the 2012 data release

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1963]
The author list for the 2012 data release is the same as for the 2011 release.
Options:

- modify record http://opendata.cern.ch/record/451 (Title, description, file name) or
- add new record with identical file but with new title, description and file name

**Comment by tiborsimko** [comment]
The second option is maybe better, because it'll work when people select "2012" in the year facet.

(esee also musings in #1944)

**Comment by ArtemisLav** [comment]
I guess then the name of the author list file should be updated as well, because right now it is `cms-author-list-2011.pdf`

**Comment by katilp** [comment]
A copy will do, i.e. the same file but different name.

**Comment by ArtemisLav** [comment]
OK, I have named the file in the PR `cms-author-list-2012.pdf`, so we just need the copy on EOS.

**Comment by tiborsimko** [comment]
@ArtemisLav @katilp The 2011 file is copied as 2012. However please note that it says "2011" on the first page... so it is probably just a question of time when this will confuse somebody...  (seeing 2011 in a 2012 file).
