### ISSUE TITLE
New record for the Higgs to 4 leptons analysis example

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1966]
Prepare new record for the Higgs to 4 leptons analysis example.

Instructions text from Achim (not final) is in 

[instructions.txt](https://github.com/cernopendata/opendata.cern.ch/files/1519226/instructions.txt)

It will hopefully get to a github directory for easier reading and access.

**Comment by tiborsimko** [comment]
Great! I was wondering whether we shall be able to have this analysis ready...

**Comment by katilp** [comment]
{
    "files": [
        {
            "checksum": "FIXME", 
            "uri": "FIXME", 
            "size": FIXME
        }
    ], 
    "accelerator": "CERN-LHC", 
    "abstract": {
        "description": " <p>This research level example is a strongly simplified reimplementation of 
parts of the original CMS Higgs to four lepton analysis published in
<a href=\https://inspirehep.net/record/1124338?ln=en\">Phys.Lett. B716 (2012) 30-61,  arXiv:1207.7235</a>.</p>
<p>The published reference plot which is being approximated in this example is  
<a href=\https://inspirehep.net/record/1124338/files/H4l_mass_v3.png>https://inspirehep.net/record/1124338/files/H4l_mass_v3.png</a>.
Other Higgs final states (e.g. Higgs to two photons), which were also part of 
the same CMS paper and strongly contributed to the Higgs boson discovery, are not 
covered by this example.</p>
<p>The example addresses users who feel they have at least some minimal 
understanding of the content of this paper and of the meaning of this 
reference plot.
It requires a minimal acquaintance with the linux operating system and 
the ROOT analysis package (<a href=\"https://root.cern.ch/\">https://root.cern.ch/</a>).</p>"
    }, 
    "run_period": "Run2011A-Run2011C", 
    "date_published": "2017", 
    "date_created": "2017", 
    "authors": [
        {
            "name": "Jomhari, Nur Zulaiha"
        },
        {
            "name": "Geiser, Achim"
        },
        {
            "name": "Bin Anuar, Afiq Aizuddin"
        }
    ], 
    "use_with": {
        "description": "Use this with 2011-2012 DoubleElectron, DoubleMuon collision datasets and the simulated datasets listed below (see the detailed instructions in the readme files and code). (FIXME this lists only 2011 datasets, 2012 to be added)", 
        "links": [
            {
                "recid": "16"
            }, 
            {
                "recid": "17"
            }, 
            {
                "recid": "1651"
            }, 
            {
                "recid": "1648"
            }, 
            {
                "recid": "1382"
            }, 
            {
                "recid": "1507"
            }, 
            {
                "recid": "1394"
            }, 
            {
                "recid": "1393"
            }, 
            {
                "recid": "1360"
            }
        ]
    }, 
    "publisher": "CERN Open Data Portal", 
    "doi": "FIXME", 
    "license": {
        "attribution": "GNU General Public License (GPL) version 3"
    }, 
    "title": "Higgs-to-four-lepton analysis example using 2011-2012 data", 
    "control_number": "FIXME", 
    "note": {
        "description": "This example can be done in different levels of complexity: 1) compare the provided output plot to that of the original publication, 2) reproduce the final output plot from the predefined histogram files, 3) reproduce one of the Root data input files and the Higgs signal MC input file and reproduce the the final output plot using the Root macro, or 4) reproduce the full example analysis.
    }, 
    "experiment": "CMS", 
    "collections": [
        "FIXME"
    ], 
    "system_details": {
        "release": "CMSSW_5_3_32", 
        "recid": "252", 
        "description": "Use this code with the CMS Open Data VM environment"
    }, 
    "usage": {
        "description": " <p>If you do not have the CERN Virtual Machine for 2011 CMS data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2011\">How to install a CERN Virtual Machine</a>.</p> <p>To run the analysis, follow the instructions in FIXME</p> "
    }, 
    "recid": "FIXME", 
    "distribution": {
        "size": FIXME, 
        "number_files": FIXME, 
        "formats": [
            "FIXME"
        ]
    }, 
    "type": {
        "primary": "Software", 
        "secondary": [
            "Analysis"
        ]
    }
}

**Comment by katilp** [comment]
I've extracted the parts of the instructions, which can be shown directly in the record. The full instrcutions text can be attached as text file, or a link to github. 

In total, this record will (likely) have:

- the final plot (available Monday)
- the intermediate histogram file(s) (in root format) (available Monday)
- the code in zipped github directory (updated next week)
- instructions text file (updated next week)

**Comment by katilp** [comment]
@ArtemisLav I have updates for this, I'll add them here. In case you want them separate, let me know

**Comment by katilp** [comment]
@ArtemisLav @tiborsimko The file can now be taken as follows

The logic goes that there are 4 levels of possible complexity for  doing this analysis.

1. look at the final plots only
2. reproduce the final plots from root files (provided)
3. run on a limited number of events 
4. run the full analysis

The instructions and files are in

/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample

The files to be attached are:

Final plots:

/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/mass4l_combine.pdf
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/mass4l_combine.png

Intermediate root files for "levels 2 and 3"

17 root files from /afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/rootfiles
We may want a separate record for this, otherwise this record becomes quite messy. I'll open an issue for it.

Two root macros from that directory can be attached to the record:
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/rootfiles/M4Lnormdatall.cc
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/rootfiles/M4Lnormdatall_lvl3.cc

The other files:

/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/BuildFile.xml
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/HiggsDemoAnalyzer.cc
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/demoanalyzer_cfg_level3data.py
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/demoanalyzer_cfg_level3MC.py
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/demoanalyzer_cfg_level4data.py
/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/demoanalyzer_cfg_level4MC.py

**Comment by tiborsimko** [comment]
@katilp Regarding files, which repository name would you like to use?  I'm referring to repository names like `2011-doubleelectron-doublemu-mueg-ttbar`.  Would be good to use the "final name" when attaching files on EOS.
