### ISSUE TITLE
CMS: enrich 2012 collision dataset descriptions

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1968]
Enrich CMS 2012 collision dataset descriptions through CSV files sent by Kati and Edgar

```
CMSDatasetDescription_Run2012B.csv
CMSDatasetDescription_Run2012C.csv
```

CC @katilp

**Comment by tiborsimko** [comment]
P.S. This should go to the beginning of "How were these data selected?".

**Comment by katilp** [comment]
Yes, exact, in the same way as for the current collision data records
