### ISSUE TITLE
Guide to the CMS condition database

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1969]
In order not to overload Getting started and to get a proper place to describe the details and usage of condition data and global tags, it would be best to have a new guide page. 

@tiborsimko Could you create a page where I could start adding content?

After the page is ready:

- [x] Update http://opendata-dev.web.cern.ch/articles/getting-started-with-cms-2011-open-data so that all details are in the new guide

- [x] Add a link to in the research guide http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data

**Comment by tiborsimko** [comment]
@atrisovic Can you please introduce a new `docs` page with empty Markdown for this?  Beware of slugs...

**Comment by atrisovic** [comment]
yes

**Comment by atrisovic** [comment]
The files are created in my new PR! :)

**Comment by katilp** [comment]
Thanks! Will this be available under https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/docs so that I can add content?

**Comment by atrisovic** [comment]
yes!

**Comment by katilp** [comment]
Closed in #2047
