### ISSUE TITLE
Year facet for dataset search does not work as expected

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1983]
http://opendata-dev.web.cern.ch/search?page=1&size=100&q=&subtype=Collision&experiment=CMS&year=2012&type=Dataset
does not give the datasets with data-taking year of 2012 but many others

In this case we really expect the year to mean the data taking year, any other behaviour is a bug and not a feature

**Comment by tiborsimko** [comment]
I see 52 results only; the issue seems to be fixed.  

P.S. @annatrz It takes a while to see the search results page; it would be nice to have some spinning wheel show while waiting... We can see about it during the production sprint.

**Comment by katilp** [comment]
I confirm, now I see the correct result, maybe I checked the outcome too quickly (it indeed takes a while to complete the search results and it does not show that it is searching as mentioned by @tiborsimko )
