### ISSUE TITLE
In condensed view all record links point to  docs -> Page not found

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1985]
http://opendata-dev.web.cern.ch/search?page=1&size=20&type=Software&experiment=CMS
show records correctly in  under /records

If "Condensed view" is chosen, the links are changed to ..../docs/... and and the links give page not found

**Comment by katilp** [comment]
This is true for all records (not only SW)

**Comment by tiborsimko** [comment]
@annatrz Can you please have a look?

**Comment by ioannistsanaktsidis** [comment]
Closing as already solved.
