### ISSUE TITLE
docker: elasticsearch dockerhub registry has been deprecated

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/opendata.cern.ch#2005]
Elasticsearch Dockerhub registry has received a deprecation notice:
https://hub.docker.com/_/elasticsearch/

In the future Elasticsearch Docker images will be hosted from `docker.elastic.co` and images in Dockerhub registry won't receive new updates.

However, Elasticsearch V2 is not available from `docker.elastic.co` so before it is released in there as well (which might not never happen, since Elasticsearch 2 will be deprecated next spring), opendata.cern.ch cannot change to use `docker.elastic.co/elasticsearch/elasticsearch` in `docker-compose.yml / Dockerfile`.

Alternatively, once opendata.cern.ch has tested support for Elasticsearch 5 we could change to using Elasticsearch image `docker.elastic.co/elasticsearch/elasticsearch:5`.

**Comment by tiborsimko** [comment]
COD3 is now converted to Elasticsearch 5 by default, using regular repository.

**Comment by psaiz** [comment]
The latest version of COD (still only in dev), uses opensearch instead of elasticsearch. I think that this ticket could be closed once the opensearch container becomes the default

**Comment by tiborsimko** [comment]
I think that this issue is already closed by the "master" branch, so to speak, since the master already contains all the necessary Elasticsearch -> OpenSearch changes.

What might be good though is to clean the remaining "traces" of Elasticsearch in our code base after ES that still remain here and there:

```console
$ git diff master upstream/master

$ git ls-files | grep -i elasticsearch
elasticsearch-proxy/.htpasswd
elasticsearch-proxy/Dockerfile
elasticsearch-proxy/nginx.conf

$ rg -i elasticsearch
• MANIFEST.in
12:include elasticsearch-proxy/Dockerfile
13:include elasticsearch-proxy/nginx.conf
48:recursive-exclude elasticsearch-proxy *

• setup.cfg
38:    elasticsearch-*

• requirements-production.txt
53:    #   elasticsearch
311:invenio-search[elasticsearch7]==1.4.1
459:    #   elasticsearch-dsl
496:    #   elasticsearch-dsl
558:    #   elasticsearch

• .gitignore
69:elasticsearch-proxy/nginx.crt
70:elasticsearch-proxy/nginx.key

• scripts/generate-localhost-certificate.sh
5:openssl req -x509 -out ./elasticsearch-proxy/nginx.crt -keyout ./elasticsearch-proxy/nginx.key \

• scripts/instance.cfg
14:# Elasticsearch
15:SEARCH_ELASTIC_HOSTS='{{ environ('INVENIO_ELASTICSEARCH_HOST') }}'

• .inveniorc
16:export INVENIO_ELASTICSEARCH_HOST=192.168.50.13

• elasticsearch-proxy/nginx.conf
17:        proxy_pass http://elasticsearch:9200;

• cernopendata/config.py
610:#: Default Elasticsearch document type.
625:#: Default Elasticsearch index.

• cernopendata/modules/records/serializers/basic_json.py
62:        :param search_result: Elasticsearch search result.

• cernopendata/modules/records/search/query.py
37:    """Default parser that uses the Q() from elasticsearch_dsl.

• cernopendata/mappings/os-v2/__init__.py
25:"""CERN Open Data Elasticsearch v7 Mappings."""
```

If we clean these traces whenever possible, then the Elasticsearch -> OpenSearch migration will be fully apparent eveywhere.
