### ISSUE TITLE
files: cannot download files?

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2013]
As observed in https://github.com/cernopendata/opendata.cern.ch/pull/2006#pullrequestreview-80836592 the file download is having issues.

How to reproduce:

```console
$ ./scripts/clean-instance.sh 
$ ./scripts/populate-instance.sh --skip-records
$ cernopendata fixtures records \
   -f ./cernopendata/modules/fixtures/data/records/cms-luminosity-information-Run2012B.json \
    --mode insert
$ firefox http://0.0.0.0/record/1052
$ firefox http://0.0.0.0/record/1052/files/2012lumi.txt
```

I think DEV, QA and PROD have the same problem. This used to work well last week.. @ioannistsanaktsidis do you recall whether the file upload was working well for your insert-or-replace mode branch?  (IIRC I tested metadata updates mostly last weekend...)

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko I didn't test the file download functionality when I implemented. Could be that this is the cause of the problem. We have to check it out.

**Comment by tiborsimko** [comment]
FWIW now it works fine for me as well, without changing anything...  Also it works again on DEV, QA, PROD without touching the instances..  It seems this it might have been an EOSPUBLIC issue.... Huh.
