### ISSUE TITLE
templates: nicer display where there are no files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2015]
**Example**

http://0.0.0.0/record/618

**Problem**

When you upload records with `--skip-files`, there are no files attached, and the previewer wants to show some.  This leads to a crash like:

![crash](https://user-images.githubusercontent.com/517546/33558517-59aa73ca-d90a-11e7-9002-62afe6e74b09.png)
:

Ideally we should fail more gracefully in these kinds of situations...

**Comment by ioannistsanaktsidis** [comment]
I have seen that error. I didn't fix it as I supposed that if a record has files in prod it will never fail as the files will be there. We can add a fallback so as to avoid it.
