### ISSUE TITLE
system: complete file load on OpenShift 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2023]
The loading of files currently fails on OpenShift due to excesive number of files in a record.

We have an issue about speeding this up, see #1826.  

However, we should also investigate in parallel how the populating job could safer pass on the OpenShift deployment.  Currently, we see two issues there: (1) more frequently, Elasticsearch times out (while it does not on local laptop); (2) less frequently, the population process gets killed (for taking too many resources?).

Here are two screenshots from two independent deployments:

(1) Elasticsearch time-out

![os2](https://user-images.githubusercontent.com/517546/33602282-26ab43aa-d9af-11e7-936e-739e10114b27.png)

(2) Process killed

![os1](https://user-images.githubusercontent.com/517546/33602321-46362fb4-d9af-11e7-938d-e7f31c20673b.png)

Let's investigate how to improve the situation:

- dedicate more OpenShift resources to population process
- populate site outside of OpenShift and just push the "final image" there
- use bulk record indexing in COD3 app 
- switch to a different persistent storage
- switch to ESoD and DBoD

**Comment by diegodelemos** [comment]
Regarding write operations we have for now:

| Command                                                        | Locally        | OpenShift DB writing to NFS volume | OpenShift DB writing to emptyDir | OpenShift+DBoD |
| -------------------------------------------------------------- |:--------------:| :------------: | :------------: | :------------: |
| `fixtures records -f cms-primary-datasets.json --skip-files --mode insert`      | 0m9.554s       | 0m32.173s     | 0m30.610s | 0m19.810s |

**Comment by diegodelemos** [comment]
DEV, PROD and QA are using DBoD and ES2 with `emptyDir` for persistence. Hence, they are ready to be populated.

**Comment by tiborsimko** [comment]
The complete loading is now OK since the change of asset loading strategy in #2075 and #1826. Moreover, all instances were converted to better DB and ES storage options.
