### ISSUE TITLE
Software record for event display file code

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#2025]
As pointed out in #1993 we should have a record for the event display file production code a la http://opendata.cern.ch/record/550

The new urls are

https://github.com/cms-outreach/ispy-analyzers/tree/Run2012
https://github.com/cms-outreach/ispy-services

Is a pointer to a branch fine as before or is a tag preferred?

**Comment by tiborsimko** [comment]
@tpmccauley A tagged release is preferred. Thanks!

**Comment by ArtemisLav** [comment]
@tpmccauley Could you please provide a title and the information for sections `System Details`, `Data selection`, `Validation` and `Related Items`, so that I can prepare the record?

**Comment by tpmccauley** [comment]
@ArtemisLav sure. Do you have a template I can just fill in?

**Comment by ArtemisLav** [comment]
Perhaps you could take the JSON [export from record 550](http://opendata-dev.web.cern.ch/record/550/export/json) as a template and just update where necessary, if that's easier. Then you can simply paste it here.

**Comment by tpmccauley** [comment]
Thanks @ArtemisLav . 

Here it is. I filled in record numbers where appropriate; 550 and 250 needed to be changed.

{
    "links": [
        {
            "url": "http://cms-outreach.github.io/ispy/#what-is-an-ig-file", 
            "description": "More information on the format can be found at"
        }, 
        {
            "url": "https://github.com/cms-outreach/ispy-analyzers/tree/Run2012"
        }
    ], 
    "abstract": {
        "description": "Software to extract the data for the browser-based event display for the CMS Experiment"
    }, 
    "authors": [
        {
            "name": "McCauley, Thomas"
        }
    ], 
    "recid": "550", 
    "date_published": "2017", 
    "run_period": "Run2012", 
    "use_with": {
        "description": "Use this with any of the CMS primary datasets"
    }, 
    "publisher": "CERN Open Data Portal", 
    "accelerator": "CERN-LHC", 
    "license": {
        "attribution": "GNU General Public License (GPL) version 3"
    }, 
    "title": "Software to extract the event display format from the CMS primary dataset", 
    "control_number": "550", 
    "relations": [
        {
            "type": "isRelatedTo", 
            "recid": "7125", 
            "description": "The output are files in json format such as"
        }
    ], 
    "methodology": {
        "description": "The software produces the objects to be displayed. The configuration file https://github.com/cms-outreach/ispy-analyzers/blob/Run2012/produceIg.py defines the objects to write out, which is done in the corresponding cc files in the src directory. No event selection, apart from accepting only the validated runs, is applied."
    }, 
    "experiment": "CMS", 
    "collections": [
        "CMS-Tools"
    ], 
    "system_details": {
        "release": "CMSSW_5_3_32", 
        "recid": "250", 
        "description": "Use this code with the CMS Open Data VM environment"
    }, 
    "usage": {
        "description": "See the run instructions in", 
        "links": [
            {
                "url": "https://github.com/cms-outreach/ispy-analyzers/blob/Run2012/README.md", 
                "description": "GitHub"
            }
        ]
    }, 
    "date_created": "2017", 
    "validation": {
        "description": "Only the list of validated runs are accepted:", 
        "links": [
            {
                "recid": "1002"
            }
        ]
    }, 
    "type": {
        "primary": "Software", 
        "secondary": [
            "Tool"
        ]
    }
}

**Comment by tpmccauley** [comment]
@tiborsimko here are the tags:

https://github.com/cms-outreach/ispy-analyzers/tree/Run2012.v2
https://github.com/cms-outreach/ispy-services/tree/Run2012.v1

**Comment by ArtemisLav** [comment]
@tpmccauley that's great, thank you.
