### ISSUE TITLE
CMS: no csv files attached to some records which show in csv search

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2030]
Not all CMS records that appear under search:

http://opendata-qa.web.cern.ch/search?page=1&size=20&q=csv&experiment=CMS&subtype=Derived

have csv fils attached. They should be there, but do not show. This is the case for records

- 307: http://opendata-qa.web.cern.ch/record/307 (http://opendata.cern.ch/record/307)
- 305: http://opendata-qa.web.cern.ch/record/305 (http://opendata.cern.ch/record/305)
- 302: http://opendata-qa.web.cern.ch/record/302 (http://opendata.cern.ch/record/302)

**Comment by tiborsimko** [comment]
@pamfilos This may be a file box pagination display problem. Let me take the record 307 and the file `Zmumu.csv` as an example.

I see the file is well listed in record JSON:

- http://opendata-qa.web.cern.ch/record/307/export/json

and it is well located on EOS:

- `root://eospublic.cern.ch//eos/opendata/cms/masterclass-2014/Zmumu.csv`

and it is well accessible via:

- http://opendata-qa.web.cern.ch/record/307/files/Zmumu.csv

However, it does not appear in the file list box:

- http://opendata-qa.web.cern.ch/record/307

Can you please have a look at the file pagination?
