### ISSUE TITLE
fixtures: files and insert-or-replace mode

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2039]
It seems we have a problem with files when using fixtures with `--mode insert-or-replace`.  To be tested locally and fixed.  

Here's one scenario to test:

1. Upload some record with `--skip-files --mode-insert`.  (so no files)
2. Upload the same record with `--mode insert-or-replace`. (so with files)

Might be good to test other combinations of (1) initial record state (with or without files); and (2) update mode (replace or insert-or-replace, with or without files).

**Comment by pamfilos** [comment]
yes when replacing or updating a file with ```update_record``` the ```record['files']``` is replaced with files from fixtures.

Easy fix: is to just update metadata for this records..and skip files leaving them in their `before_update` state. Else, all files need to be removed and reloaded , if we have no clue which file is the one updated (if there is any )

**Comment by tiborsimko** [comment]
If we update only the metadata, then we would not cover the original scenario described above. It is possible that the record metadata has changed, or the file information such as some file size has changed, or some new files were added... We need to have an easy way to update records in all these scenarios.

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Yes, that would be perfect, since we always do a full "replace" operation, and never a partial "update".
