### ISSUE TITLE
Dataset records showing parent dataset

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2048]
Sim records now show parent datasets record (wrong as it shows the record itself):

e.g. http://opendata-dev.web.cern.ch/record/1333
"Dataset Simulated Collision Energy: 7TeV Experiment: CMS Accelerator: CERN-LHC Parent Dataset: /JJHiggs0PToGG_M-125p6_7TeV-JHUGenV4-pythia6-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM"

Collision records show the correct parent but as we are not hosting it on the portal there is now reason to display it. It should also be removed from "Related datasets" for the same reason.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko this is happening because of this field
```
 "relations": [
        {
            "type": "isChildOf", 
            "title": "/JJHiggs0PToGG_M-125p6_7TeV-JHUGenV4-pythia6-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM"
        }
    ], 
```
should we remove parent dataset when type == IsChildOf ?

**Comment by tiborsimko** [comment]
@katilp The wrong parent information comes from COD2, I noticed we had it there wronly already... and I agree that since we don't host it and/or link to it, we don't need to show it.  

I'd propose to simply delete this information from the metadata for both collision and simulated datasets, and keep it only for derived datasets when we host the parent...

**Comment by katilp** [comment]
For collision data the information is correct, it is not relevant in the context of the portal, but eventually useful for DP. Would it be possible to delete it from MC and keep it for collision data but not show it?

**Comment by tiborsimko** [comment]
It would not be practical to introduce a special exception for collision data, but we could perhaps have  this generic rule:

"For `isChildOf` type of relations, show the related dataset if and only if we also host the related dataset as well; i.e. if we have the record ID in the relations link."

**Comment by katilp** [comment]
True, this would work.
Note however that for the MC datasets this is just wrong, the dataset claims that it is the child of itself so `isChildOf` field should be removed from them

**Comment by tiborsimko** [comment]
@hjhsalo @ioannistsanaktsidis The PR #2094 takes care of the wrong record metadata; can you please take care of amending the record page display as mentioned in https://github.com/cernopendata/opendata.cern.ch/issues/2048#issuecomment-350538338 when you have time?

**Comment by katilp** [comment]
This is now addressed for the new collision data records but not for the old ones:
http://opendata-dev.web.cern.ch/record/6029 (no parent dataset shown)
http://opendata-dev.web.cern.ch/record/16 (parent dataset shown after CERN-LHC)
