### ISSUE TITLE
elasticsearch: fast dump and load 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2054]
Investigate fast dump and load options for Elasticsearch indices.

A use case scenario: we create a COD3 instance, load all records, and take a snapshot of the Elasticsearch instance indices, and launch the site. In case we loose the Elasticsearch cluster for a reason or another, we would like to quickly restore Elasticsearch indexes without having to repopulate the COD3 records from scratch again.

Option A: use some Invenio-agnostic tool such as https://github.com/taskrabbit/elasticsearch-dump

Option B: add a new COD3 CLI command that would reindex all records in a bulk mode, taking records from existing DB and indexing them afresh in ES.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  I think this one considered as done due to @hjhsalo PR about reindexing all records ?

**Comment by tiborsimko** [comment]
Yes, we can close this one since we have Option B in place.

However we should still deploy `worker` on OpenShift to be able to reindex records... I'll create a new issue for that. CC @diegodelemos
