### ISSUE TITLE
files: check download of some files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2064]
As observed in https://github.com/cernopendata/opendata.cern.ch/pull/2055#issuecomment-350335270, some file download works, some does not.

- this works: http://0.0.0.0/record/613/files/ZeroBias.ig
- this gives exception: http://0.0.0.0/record/7120/files/SingleMu_Run2012B_0.ig

@ioannistsanaktsidis This is without doubt also why the embedded previewer worked for some records and why it did not work for others, as I mentioned you IRL last week...

**Comment by ioannistsanaktsidis** [comment]
Some files are missing the ```sha1:...``` property in the fixtures thats why download is failing.
