### ISSUE TITLE
templates: file download warning box

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2066]
The file download warning box seems to have disappeared.

Let us bring it back, as it is important do warn the users that they don't have to download big files if they use VM for analysing.

See #1437 and #1451.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  I can't replicate the problem. I am trying with /record/35 and the box appears when I click the download button.

**Comment by tiborsimko** [comment]
As discussed IRL, I tried with a file of ~600MB, for which COD2 was giving a warning box, while the limit is set hight for COD3:

```console
$ grep 1073741824 cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html
  <a class="btn btn-primary" ng-if="file.size <= 1073741824" href="{{download_uri}}">
    ng-if="file.size  > 1073741824"
```

Let us reduce the limit to ~200 MB to be on the safer side.

(and perhaps let's put the number in a config variable)
