### ISSUE TITLE
CMS: Update lists to show properly on the portal

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2069]
The lists with `-` do not show properly (although OK on github) , they have to be with `*`

**Comment by RaoOfPhysics** [comment]
They appear fine… Can you show a screenshot?

**Comment by katilp** [comment]
Sorry, no I can't, I'm just changing the md (I have no local installation) but based docs already on the portal, this should fix the formatting

**Comment by RaoOfPhysics** [comment]
I meant which docs on the portal do you see issues with. :) The latest version looks fine to me.

**Comment by katilp** [comment]
OK, it was:

![mdportal](https://user-images.githubusercontent.com/5859918/33824259-1822bea4-de5e-11e7-8c94-39da52271d7b.PNG)
![mdgithub](https://user-images.githubusercontent.com/5859918/33824260-1ae314a4-de5e-11e7-9463-3fd389cbd9bb.PNG)

but now it should be fixed

**Comment by RaoOfPhysics** [comment]
Ah, I see. OK, so this should be taken care of at the backend. It's probably not interpreting the line breaks correctly. I don't know if changing `-` to `*` will work. @tiborsimko, @pamfilos?

**Comment by katilp** [comment]
Yes, it is working, I did some experimental observations yesterday 😃 :
the `*`s are working fine in About CMS Open Data
