### ISSUE TITLE
templates: check all links

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2072]
Check all COD2 links whether they are well alive on COD3 and whether they return something reasonable. This should have been already addressed, but we've seen some recurse, so let's double check all redirections once more.

Rules of thumb:

(1) If we clearly know where to redirect and the target page is a single page,
then we should always redirect there.

- good example: `/about/xxx` -> `/docs/yyy`
- bad example: `/about/xxx` -> `/search?q=yyy`

(bad because it returns more items than it should)

(2) If it is not clear where to redirect, for example because the concept is
hidden (such as collection pages, education vs research), then redirect to
appropriate search page with appropriately selected data type facets.

- good example: `/collection/CMS-Primary-Datasets` -> `/search?subtype=Collision&experiment=CMS`
- bad example: `/collection/CMS-Primary-Datasets` `/search?collections=CMS-Primary-Datasets`

(bad because it exposes past concepts over the new ones)

(3) If we redirect to a search page, but there is no good combination of facets
that would permit us to expose "new concepts" over the "old concepts", then let
us use the past concepts:

- example: `/research` -> `/search?collections=X&collections=Y&...`

(albeit ideally we should prefer option 2 over option 3)

(4) Here is the list of all pages to check:

- [x] http://opendata-dev.web.cern.ch/
- [x] http://opendata-dev.web.cern.ch/<string:exp>/getstarted
- [x] http://opendata-dev.web.cern.ch/VM
- [x] http://opendata-dev.web.cern.ch/VM/<exp>/validation/report
- [x] http://opendata-dev.web.cern.ch/VM/<string:exp>
- [x] http://opendata-dev.web.cern.ch/VM/<string:exp>/<string:year>
- [x] http://opendata-dev.web.cern.ch/about
- [x] http://opendata-dev.web.cern.ch/about/ALICE
- [x] http://opendata-dev.web.cern.ch/about/ATLAS
- [x] http://opendata-dev.web.cern.ch/about/CMS
- [x] http://opendata-dev.web.cern.ch/about/CMS-Physics-Objects
- [x] http://opendata-dev.web.cern.ch/about/CMS-Physics-Objects/<string:year>
- [x] http://opendata-dev.web.cern.ch/about/CMS-Pileup-Simulation
- [x] http://opendata-dev.web.cern.ch/about/CMS-Simulated-Dataset-Names
- [x] http://opendata-dev.web.cern.ch/about/LHCb
- [x] http://opendata-dev.web.cern.ch/about/alice
- [x] http://opendata-dev.web.cern.ch/about/atlas
- [x] http://opendata-dev.web.cern.ch/about/cms
- [x] http://opendata-dev.web.cern.ch/about/lhcb
- [x] http://opendata-dev.web.cern.ch/collection
- [x] http://opendata-dev.web.cern.ch/collection/<name>
- [x] http://opendata-dev.web.cern.ch/collections
- [x] http://opendata-dev.web.cern.ch/education
- [x] http://opendata-dev.web.cern.ch/education/<string:exp>
- [x] http://opendata-dev.web.cern.ch/experiments
- [x] http://opendata-dev.web.cern.ch/getstarted
- [x] http://opendata-dev.web.cern.ch/getstarted/<string:exp>
- [x] http://opendata-dev.web.cern.ch/getting-started
- [x] http://opendata-dev.web.cern.ch/getting-started/<string:exp>
- [x] http://opendata-dev.web.cern.ch/getting-started/<string:exp>/<string:year>
- [x] http://opendata-dev.web.cern.ch/glossary
- [x] http://opendata-dev.web.cern.ch/news
- [x] http://opendata-dev.web.cern.ch/privacy-policy
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/citations
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/export
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/export/<of>
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/files
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/keywords
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/load/authors/
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/load/authors/<int:start>/to/<int:end>
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/load/files/
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/load/files/<int:start>/to/<int:end>
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/metadata
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/references
- [x] http://opendata-dev.web.cern.ch/record/<int:recid>/usage
- [x] http://opendata-dev.web.cern.ch/research
- [x] http://opendata-dev.web.cern.ch/research/<string:exp>
- [x] http://opendata-dev.web.cern.ch/resources
- [x] http://opendata-dev.web.cern.ch/resources/<string:exp>
- [x] http://opendata-dev.web.cern.ch/terms-of-use
- [x] http://opendata-dev.web.cern.ch/visualise/events/<string:exp>
- [x] http://opendata-dev.web.cern.ch/visualise/histograms/<string:exp>

**Comment by atrisovic** [comment]
- [ ] http://opendata-dev.web.cern.ch/
- [ ] http://opendata-dev.web.cern.ch/<string:exp>/getstarted
- [ ] http://opendata-dev.web.cern.ch/VM
- [ ] http://opendata-dev.web.cern.ch/VM/<exp>/validation/report
- [ ] http://opendata-dev.web.cern.ch/VM/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/VM/<string:exp>/<string:year>
- [ ] http://opendata-dev.web.cern.ch/about
- [ ] http://opendata-dev.web.cern.ch/about/ALICE
- [ ] http://opendata-dev.web.cern.ch/about/ATLAS
- [ ] http://opendata-dev.web.cern.ch/about/CMS
- [ ] http://opendata-dev.web.cern.ch/about/CMS-Physics-Objects
- [ ] http://opendata-dev.web.cern.ch/about/CMS-Physics-Objects/<string:year>
- [ ] http://opendata-dev.web.cern.ch/about/CMS-Pileup-Simulation
- [ ] http://opendata-dev.web.cern.ch/about/CMS-Simulated-Dataset-Names
- [ ] http://opendata-dev.web.cern.ch/about/LHCb
- [ ] http://opendata-dev.web.cern.ch/about/alice
- [ ] http://opendata-dev.web.cern.ch/about/atlas
- [ ] http://opendata-dev.web.cern.ch/about/cms
- [ ] http://opendata-dev.web.cern.ch/about/lhcb
- [ ] http://opendata-dev.web.cern.ch/collection
- [ ] http://opendata-dev.web.cern.ch/collection/<name>
- [ ] http://opendata-dev.web.cern.ch/collections
- [ ] http://opendata-dev.web.cern.ch/education
- [ ] http://opendata-dev.web.cern.ch/education/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/experiments
- [ ] http://opendata-dev.web.cern.ch/getstarted
- [ ] http://opendata-dev.web.cern.ch/getstarted/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/getting-started
- [ ] http://opendata-dev.web.cern.ch/getting-started/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/getting-started/<string:exp>/<string:year>
- [ ] http://opendata-dev.web.cern.ch/glossary
- [ ] http://opendata-dev.web.cern.ch/news
- [ ] http://opendata-dev.web.cern.ch/privacy-policy
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/citations
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/export
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/export/<of>
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/files
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/keywords
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/load/authors/
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/load/authors/<int:start>/to/<int:end>
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/load/files/
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/load/files/<int:start>/to/<int:end>
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/metadata
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/references
- [ ] http://opendata-dev.web.cern.ch/record/<int:recid>/usage
- [ ] http://opendata-dev.web.cern.ch/research
- [ ] http://opendata-dev.web.cern.ch/research/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/resources
- [ ] http://opendata-dev.web.cern.ch/resources/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/terms-of-use
- [ ] http://opendata-dev.web.cern.ch/visualise/events/<string:exp>
- [ ] http://opendata-dev.web.cern.ch/visualise/histograms/<string:exp>

**Comment by atrisovic** [comment]
Many of these links are broken (eg `/resources` and `/research`). Should we have new views for them?

**Comment by ioannistsanaktsidis** [comment]
hmmm I don't know what happen with them. ```/resources /research``` used to work .

**Comment by tiborsimko** [comment]
`/research` redirects well to a long query:

- http://opendata-dev.web.cern.ch/search?page=1&size=20&collections=CMS-Primary-Datasets&collections=CMS-Simulated-Datasets&collections=CMS-Derived-Datasets&collections=CMS-Tools&collections=CMS-Validation-Utilities&collections=CMS-Learning-Resources&collections=CMS-Simulated-Datasets&collections=CMS-Open-Data-Instructions&collections=CMS-Trigger-Information&collections=CMS-Condition-Data&collections=CMS-Configuration-Files&collections=CMS-Luminosity-Information

which gives an empty page.

This was working before, so it must be connected to ES2 -> ES5 upgrade.  CC @annatrz

**Comment by tiborsimko** [comment]
BTW here is the reason why my original rule of thumb 1 good approach (=redirecting to given target page) is better the bad approach (=redirecting to search):

![g](https://user-images.githubusercontent.com/517546/35923691-3dfda558-0c21-11e8-8497-5421ac354e31.png)

Please make sure to tick the URLs in the above list only after it's fully working and follows the rule of thumb...

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed.
