### ISSUE TITLE
templates: centralise spinning wheel

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2088]
When search takes some time, the spinning sheel loading bar icons appears at the very top-left corner, where users hardly notice it.

Improve the spinning wheel position, e.g. centralise it on the page.

**Comment by tiborsimko** [comment]
@annatrz Is there still a spinning wheel? 😄

**Comment by annatrz** [comment]
No, it's hidden now, there is just loading bar on the top of page (bit thicker). 

With spinning wheel it didn't look good in the middle of the page, especially when user clicking on facet wasnt at the top of the page (loading bar and spinning wheel not visible then at all, or when make them sticky, didnt look good, as covering part of search page).. 

If anybody has suggestions how to make it look good, I can implement today.
