### ISSUE TITLE
search: centralise search box position 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2091]
The search is located in the page header bar, which is good, but it looks tiny, which is geographically far from the center of the page where the user attention is (filter by, sort by).

Let's centralise the search box position on the search results pages, either keeping it in the header and making it bigger, or moving it under the header in a centralised position and above the Sort-by and DIsplay options...

See for inspiration how Google, DuckDuckGo, libraries.io and friends do the job.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed by @annatrz .
