### ISSUE TITLE
files: create rich index files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2093]
For every index file in TXT, create rich index file in JSON. Example content:

```json
[
    {
        "filename": "foo.zip",
        "size": 1234,
        "checkum": "abcde",
        "uri": "root://eospublic.cern.ch//eos/opendata/.../foo.zip"
    },
    {
        "filename": "bar.C",
        "size": 567,
        "checkum": "fghijk",
        "uri": "root://eospublic.cern.ch//eos/opendata/.../bar.C"
    }
]
```

@tiborsimko to create and attach JSON files on EOS for each concerned record. (PR #2075)
@pamfilos to take these files from `/record/NNN/files/XXX.json` and use them in the file pagination box on the detailed record pages.

Stemmed from  #1826.

**Comment by tiborsimko** [comment]
Progress:
- [ ] CMS 2010 collision data
- [ ] CMS 2011 collision data
- [ ] CMS 2011 raw data
- [ ] CMS 2011 simulated data
- [ ] CMS 2012 collision data 
- [ ] CMS 2021 simulated data

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
