### ISSUE TITLE
Fix subtitles for CMS VM and contextualization script records

### ISSUE THREAD

**Issue by ArtemisLav** [cernopendata/opendata.cern.ch#2103]
I am centralising here some tasks from #2044 and #2045 that can be worked on together:

For contextualization script records 249, 251 and 253:

- [ ] How can you use these data? -> How to use?

For VM records 252 and 250:

- [ ] How were these data selected? -> How was this built?

- [ ] How were these data validated? -> How to validate?

- [ ] How can you use these data? -> How to use?

**Comment by katilp** [comment]
Good to have them together here 👍 
Indeed, "How to use?" is fine in 249 as well . Note that same applies also for 251 and for the new record #2045

**Comment by ArtemisLav** [comment]
OK, I updated my comment.

**Comment by tiborsimko** [comment]
Basically, for all records of Environment type, the deailed record page should not print the default text, but the alternative text. We already have an exception for "Software" records in `cernopendata/templates/cernopendata_records_ui/records/record_detail.html`. @ioannistsanaktsidis @pamfilos Can you please add a new exception for "Environments" records?
