### ISSUE TITLE
Corrections and updates to the condition data records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2106]
The condition data records

- [ ] 2010 collision data (http://opendata-dev.web.cern.ch/record/1800) does not show any attached files

- [x] 2011 collision data (http://opendata-dev.web.cern.ch/record/1801) and 2011 simulated data (http://opendata-dev.web.cern.ch/record/1802) show only the file index with the path to the files, should the files be shown as well?

- [ ] 2012 collision data (http://opendata-dev.web.cern.ch/record/1803) and 2012 simulated data (http://opendata-dev.web.cern.ch/record/1804) show only the db file, they should have the zipped files as well or the file index as those of 2011

- [ ] 2012 collision data (1803) should have /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL attached

- [x] Add "See further information in <a href=\"/docs/cms-guide-for-condition-database\">the guide to CMS condition database</a>." to 2011 and 2012 records (1801, 1802, 1803, 1804), e.g. in abstract description before the text  "For 2011/2012 CMS Simulated/collision datasets see:"

- [x] In simulated data records 1802 and 1804 title "Simulated Datasets" -> "simulated datasets"

- [x] In collision data records 1801 and 1803, "Simulated Datasets" -> "simulated datasets" in the end of the abstract description

- [x] Update the abstract description of the 2012 collision data record 1803: 
replace:
<p>FT53_V21A_AN6 is to be used with the collision data of RunB 2012 and FT53_V21A_AN6_RUNC with the collision data of RunC 2012 (with the event range of the open data, the file for the full event range for 2012 are also stored\n      under FIXME on /cvmfs/cms-opendata-conddb.cern.ch)</p>

with

<p>FT53_V21A_AN6_FULL is for the full event range for 2012 and can be used both for RunB and RunC 2012 collision data.  Databases for limited event ranges are also available under  /cvmfs/cms-opendata-conddb.cern.ch (FT53_V21A_AN6 is for the event range of RunB and FT53_V21A_AN6_RUNC for the event range of RunC).</p>

**Comment by ArtemisLav** [comment]
@katilp in 1803 there is a "FIXME" in the abstract. Can I replace it with something?

**Comment by ArtemisLav** [comment]
@katilp 👍 
This PR takes care of the updates to the metadata, so what is left is the file-related tasks.

**Comment by tiborsimko** [comment]
The first example: record 1800 lives in `cms-condition-data-Run2010B.json` and there is no link to existing file `/eos/opendata/cms/Run2010B/db/GR_R_42_V25-cmssw4.2.8.tgz` there.

**Comment by tiborsimko** [comment]
The third example, the 2012 condition DB files are big, see https://github.com/cernopendata/opendata.cern.ch/issues/1263#issuecomment-348157835, and cannot be easily packaged on the servers due to insufficient scratch space.  Perhaps use `/tmp/` on a given AIADM machine such as AIADM68.

**Comment by tiborsimko** [comment]
WRT first example:

```
path=root://eospublic.cern.ch//eos/opendata/cms/Run2010B/db/GR_R_42_V25-cmssw4.2.8.tgz size=35152737806 checksum=5a5e1e45
```

**Comment by katilp** [comment]
Closing as this is now addressed differently, i.e. pointing to the /cvmfs area instead of attaching the files

![condition](https://user-images.githubusercontent.com/5859918/61222675-72978900-a71b-11e9-9d75-53491b02bfb7.JPG)
