### ISSUE TITLE
CMS 2010 validation report missing (record 56)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2122]
I cannot find http://opendata-dev.web.cern.ch/record/56

We had it in http://opendata.cern.ch/VM/CMS/validation/report earlier

**Comment by tiborsimko** [comment]
Indeed, it does not seem to have been ported.

The page content was living in QA under:

- `invenio_opendata/base/templates/helpers/text/cms_validation_report.html`

@atrisovic Can you please look at making a docs record with an appropriate Markdown?

**Comment by atrisovic** [comment]
yup 👍

**Comment by tiborsimko** [comment]
For the slug, something like `/docs/cms-vm-validation-2010` might be nice perhaps... And we should put redirection from `/vm/cms/validation/report`.
