### ISSUE TITLE
nginx: scaling and pod anti-affinity

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2128]
We should introduce at least three nginx pods.  They should be configured with proper anti-affinity so that they would be hosted on different nodes.  This will make sure that our ngixn pods won't compete for the same emptyDir space on the same node, as it were.

https://docs.openshift.com/container-platform/3.6/admin_guide/scheduling/pod_affinity.html

**Comment by diegodelemos** [comment]
Done. Deployed on PROD, QA and DEV
