### ISSUE TITLE
CMS: add a file list to record 5501 for easier download

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2154]
http://opendata-dev.web.cern.ch/record/5501
Add file list from

/afs/desy.de/user/g/geiser/public/CMS/opendata/Higgsexample/rootfiles/rootfilelist.txt
containing the root files needed for 5500 example (they are not all).

and update:

"usage": {
        "description": "These datasets are provided as part of the Higgs-to-four-lepton analysis example using 2011-2012 data. You can download all root files needed for the Level 3 exercise to your working area by downloading first the file list<code> rootfilelist.txt </code> and then the root files  with <code>wget -i rootfilelist.txt</code>. ", 
        "links": [
            {
                "recid": "5500"
            }
        ]
    },

**Comment by tiborsimko** [comment]
@ArtemisLav Here's the file information:

```
    {
      "checksum": "adler32:5b338e95",
      "size": 1206,
      "uri": "root://eospublic.cern.ch//eos/opendata/cms/software/HiggsExample20112012/rootfilelist.txt"
    }
```

@katilp Note that the file content contains URLs to DEV:

```
http://opendata-dev.web.cern.ch/record/5501/files/DoubleMu11.root 
http://opendata-dev.web.cern.ch/record/5501/files/DoubleE11.root 
http://opendata-dev.web.cern.ch/record/5501/files/DoubleMu12.root   
[...]
```

We'd better change this to thePROD URL when we release...
