### ISSUE TITLE
Our own "about" page with broken format

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#2161]
See http://opendata-dev.web.cern.ch/docs/about

and note that Invenio paragraph needs updating!

<img width="895" alt="screen shot 2017-12-15 at 12 41 03 pm" src="https://user-images.githubusercontent.com/7300319/34040721-417474de-e195-11e7-88b3-2be618e83c17.png">

**Comment by suenjedt** [comment]
@sefeg can you take a look at the invenio paragraph to update this with material from http://invenio-software.org/? thanks

**Comment by sefeg** [comment]
Sure! I changed / enhanced the text with wording from the Invenio page:

Invenio is a digital library framework that allows to run your own digital library, institutional repository, multimedia archive, or research data repository on the web. The technology offered by the software covers all aspects of digital library management, from document ingestion through classification, indexing, and curation up to document dissemination. The flexible data model uses JSON schema to describe articles and various other types of media and supports popular master metadata formats, such as MARC21 as its underlying bibliographic format. Invenio features a powerful search engine that handles repositories of up to several million records with ease. Being composed of a multitude of independent pluggable packages, the digital library framework provides the needed flexibility for a wide range of applications. Invenio is a strong advocate of open standards and open access and makes use of DOI, Memento, OAI-PMH, ORCID, OpenAIRE and many others.

**Comment by sefeg** [comment]
@atrisovic Could you please fix the formatting in the CernVM section and replace the text in the Invenio section with my proposed text above? Thank you

**Comment by atrisovic** [comment]
yup 👍

**Comment by atrisovic** [comment]
what do you think we change the first sentence to: `Invenio is a library management software that allows to run your own digital library, institutional repository, multimedia archive, or research data repository on the web.` rather then having `digital library` two times in the sentence ?

**Comment by sefeg** [comment]
Fully agree! 
I commented the PR...I think the Impressum part needs to be separated from the blob of text?

**Comment by atrisovic** [comment]
yeah that is fixed now. there was a `<div>` that was messing the formating ;)

**Comment by suenjedt** [comment]
Thanks!

**Comment by tiborsimko** [comment]
"Invenio is a library management software" sounds weird... that are so many dfferent things that are called "libraries".   I'll make a PR about this later...
