### ISSUE TITLE
templates: file pagination to stay within web application service

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2166]
The addition of special `web-files` service (#2130) isolated file downloads to a dedicated micro-service which  improved the system responsiveness in case file download would not be possible due to a backend system failure or in case of huge file download clogging the service.

However, there remains one endpoint used for file pagination.  If a user hits `/record/6005` detailed record page for a record that has index files, the web application service hits ` /record/6005/files/p/1?group=1` to offer the file pagination box. This "user-invisible" endpoint hits the web-files service:

```
web-files_1      | 172.19.0.10 - - [15/Dec/2017 14:24:36] "GET /record/6005/files/p/1?group=1 HTTP/1.0" 200 -
```

It would be useful to move this endpoint to something like:

```
/record/6005/filelist/...`
```

so that everything would remain inside the web application service space.

In this case, if the web files service is down, the users will still be able to paginate inside rich indexes...  The users would be affected only when they actually try to download one such asset file.

@pamfilos Can you please amend?

**Comment by pamfilos** [comment]
Closing as fixed with #2108
