### ISSUE TITLE
CMS: in VM records error link shows twice: "title" -> "description"?

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2171]
In http://opendata-dev.web.cern.ch/record/252

"note": {
        "description": "For known issues and limitations see", 
        "links": [
            {
                "url": "/VM/CMS/2011#issue", 
                "title": "CMS Virtual Machines - Known Issues and Limitations"
            }
        ]
    }, 

shows the link twice, should "title" be "description" (as for the other links)?

Same for http://opendata-dev.web.cern.ch/record/250

**Comment by tiborsimko** [comment]
This is a display problem.  The metadata looks OK to me:

```json
  "note": {
    "description": "For known issues and limitations see", 
    "links": [
      {
        "title": "CMS Virtual Machines - Known Issues and Limitations", 
        "url": "/VM/CMS/2010#issues2010"
      }
    ]
  }, 
```

This means that in the Note nox, the description should be printed, followed by one link only, the title of the link should be "CMS Virtual.....", and the link should point to "/VM/...".

@ioannistsanaktsidis @pamfilos Can you please look at updating detailed record templates?
