### ISSUE TITLE
CMS: feedback for the histogram visualizer

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2177]
Feedback from Achim's tester to histogram visualizer:

 

>   [http://opendata-dev.web.cern.ch/visualise/histograms/cms]
>    The histograms show up without axis label or other explanations, so the
>    tester, even though physics student, couldn't make sense of them.
>    (I guess they are usually used "in context" with other exercises?)

**Comment by tpmccauley** [comment]
Point taken. One can see information on the parameters when hovering over the button but we should really label the x axis. Will make a PR.
