### ISSUE TITLE
all links broken: http://opendata-dev.web.cern.ch/docs/atlas-higgs-machine-learning-challenge

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#2188]

**Comment by atrisovic** [comment]
These are the links, we'll have to see what to replace them with :s

http://www.atlas.ch/news/2014/are-you-up-for-higgs-challenge.html
http://www.atlas.ch/news/2013/higgs-into-fermions.html
http://atlas.ch/news/2014/machine-learning-wins-the-higgs-challenge.html
