### ISSUE TITLE
Remove link in /record/252

### ISSUE THREAD

**Issue by atrisovic** [cernopendata/opendata.cern.ch#2189]
<img width="420" alt="screen shot 2017-12-17 at 18 51 00" src="https://user-images.githubusercontent.com/13986265/34082339-6f64e108-e35c-11e7-8894-c2f7cc9571a3.png">

I think that the last row in the image shouldn't be displayed.

the page: http://opendata-dev.web.cern.ch/record/252

**Comment by katilp** [comment]
Right, this is being addressed in  #2171

**Comment by atrisovic** [comment]
ok great, I'll close this one then :)
