### ISSUE TITLE
Unnecessary and broken Preview link in (some) software and data records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2191]
A preview link has appeared in some software records, it should be removed, see:

![preview](https://user-images.githubusercontent.com/5859918/34082758-90c42ab8-e364-11e7-9ba9-48e7eee86371.JPG)
 
or 
http://opendata-dev.web.cern.ch/record/5001
http://opendata-dev.web.cern.ch/record/5500
http://opendata-dev.web.cern.ch/record/6006
http://opendata-dev.web.cern.ch/record/7735

**Comment by tiborsimko** [comment]
See also https://github.com/cernopendata/opendata.cern.ch/issues/2183
