### ISSUE TITLE
CMS: MC datasets without GEN

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2203]
89 MC AODSIM datasets without GEN grandparent (see also http://simko.home.cern.ch/simko/tmp/cod3-mc.txt  or 
[cod3-mc.txt](https://github.com/cernopendata/opendata.cern.ch/files/1747071/cod3-mc.txt)
)

22.02.2018 updated with some links:

- /BBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM parent GEN-SIM status=DELETED, (https://cmsweb.cern.ch/das/request?input=dataset%3D%2FBBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola%2FSummer12-START53_V7C-v1%2FGEN-SIM&instance=prod%2Fglobal) but configs there, take output-config-1:
  - https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/a97a2f6c22dfba999c0131657a81ecfd/configFile
- /DiPhotonBorn_Pt-10To25_8TeV_ext-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v2/AODSIM idem: parent GEN-SIM status=DELETED  (https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDiPhotonBorn_Pt-10To25_8TeV_ext-pythia6%2FSummer12-START52_V9-v1%2FGEN-SIM&instance=prod%2Fglobal) take output-config-1 
   - https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/77a3ead6ad2fd8a3ee6652b760be2fd9/configFile (although this is for some reason the stadrd configurations are fully written out but the Pythia parameters are there) + same for two others DiPhotonBorn 
- /DiPhotonBox_Pt-10To25_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM parent GEN-SIM N/A but no output-config-1 i.e. no config for SIM step + same for twoo other DiPhotonBox
- /DiPhotonJetsBox_M60_8TeV-sherpa/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM, N/A GEN-SIM parent has output-config-1 https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/cf4f2d0d0f3bc97530e34764ca4b3883/configFile
- /DoubleElectron_FlatPt-5To300_gun/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM N/A GEN-SIM parent has output-config-1 https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/05e7f803b55fe910471147e8498f3f2d/configFile
- /DYJets_0p0_1p2_2p10_3p15_4p15_CT10_8TeV-sherpa/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM idem https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/28991b96748afc67ee2e050bc1d3f770/configFile (no pythia parameters here but sherpa in "process.generator =" )
- /DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/Summer12_DR53X-ExtFlat30_PU_RD1_START53_V7N-v1/AODSIM take https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/adda25dea992e96fb7e8f4be89889c0b/configFile
- /DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/1ac6d193605fc02b9ef72f9a139d52e1/configFile
-  /DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIMhttps://cmsweb.cern.ch/couchdb/reqmgr_config_cache/1ac6d193605fc02b9ef72f9a139d52e1/configFile

- /TT_SC_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V19-v2/AODSIM parent dataset N/A, no information

**Comment by katilp** [comment]
Summary so far: if a dataset has been deleted, it still has the metadata in (including the config file - with generator parameters - used to produce this dataset and the configs for the following step), but the information of its parent is lost

**Comment by katilp** [comment]
An update: after discussion with Valentin, it looks like that rather than deleted the dataset may never been entered to the service where DAS is looking for it.

A summary of different services:
- DBS main CMS data catalog
- PHedex,  main data location service
- ReqMgr, service for workflow processing (both MC and data) registration
- McM, service for MonteCarlo requests registration
etc.

Note also for the parent-child relationship:
> It is done at a file level and if such relationship exists for all files
> it propagates to dataset level. If not all files have parents then relationship
> will not be present at dataset level, but will still exists at a file level
> for those who had it.

**Comment by heitorPB** [comment]
Some of those datasets have no parent because they are already the parent.

For example:
- dataset: /BBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM
  there is no parent. But it has children. And in the config files (not of the children) you chan see all the details about the Pythia parameters

**Comment by tiborsimko** [comment]
> ` /BBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM`

This record seems OK, it has the SIM step: http://opendata.cern.ch/record/7299

**Comment by tiborsimko** [comment]
> `/DiPhotonBox_Pt-10To25_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM`

This is a good example, because its GEN-SIM parent does not have any `byoutputdataset` config info, but it has plenty of `byinputdataset` config files... e.g. `6a33b72e9283e79fcf088daae692ece0`.  Perhaps they can be accessed and parsed? @heitorPB

**Comment by heitorPB** [comment]
Some of the entries from Kati's list are in the portal with GEN info. These are the ones without gen info in the portal (3rd and last):

- /DiPhotonBox_Pt-10To25_8TeV-pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM parent GEN-SIM
  - No entry in McM
  - parent has 10 config files, none of them are GEN.
    - one has `process = cms.Process("NONE")` and it is not useful
  - no LHE header to dump
  - no grandparent

- /TT_SC_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V19-v2/AODSIM
  - no GEN config script
  - _has_ useful LHE header
  - McM entry says `input_dataset: "/TT_SC_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12-START53_V7C-v1/GEN-SIM"`
    - this dataset _has_ gen info (external generator + pythiaHadronizerFIlter): https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/7ee5ca4f535f8eb6eaa8ff5a54ef9089/configFile

Didn't check Tibor's list yet.

**Comment by heitorPB** [comment]
We could focus in the datasets with more popularity:
https://github.com/katilp/cms-data-popularity

**Comment by heitorPB** [comment]
Closing this issue as the information is not in CMSDAS neither in McM
