### ISSUE TITLE
ui: order and selection of news on the home page

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2207]
**1.** The order of news items on the home page:

- http://opendata.web.cern.ch/#news

is currently not chronological:

- 2017-12-18 Welcome to our updated portal
- 2017-11-15 Improving educational content with high-school teachers: A field report from our summer students
- 2017-12-01 The Future of Particle Physics is "Open"

If this is news in it literal sense, then we should rather order them chronologically.

**2.** Regarding the first item, " by Open Data Portal team" would be better said "by the CERN Open Data portal team".

**3.** Regarding the second item, "...from our summer students" would be better said "...from  CMS summer students" because we are in the COD publishing domain here, not in the CMS blog domain anymore.

**4.** Do we have a news item about the forthcoming CMS 2012 release? What about featuring H4L analysis separately there? CC @RaoOfPhysics @katilp  

**P.S.** Personally I'd favour displaying more content-related news rather when welcome related news...this could be put to the "About..." page.

**Comment by RaoOfPhysics** [comment]
> 4. Do we have a news item about the forthcoming CMS 2012 release? What about featuring H4L analysis separately there? CC @RaoOfPhysics @katilp

I'm preparing the news item! Not sure I want to comment on the H4l analysis –– I leave this to @katilp!

**Comment by katilp** [comment]
We have not planned any separate news item for the h4l analysis, so not in this time scale. It is very nicely featured in the main CMS release announcement, though.

**Comment by tiborsimko** [comment]
Closed by #2207 and #2223.
