### ISSUE TITLE
UI: provide contextual information in <title>

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#2237]
It would be nice if information about the page one is on were to be displayed in the `<title>` tag, so one has context when looking at multiple tabs. At the moment, all pages only say "CERN Open Data Portal" [OT: should the "p" be lower case?]:

<img width="1072" alt="firefox - - screen shot 20 dec 2017 at 19 47 34" src="https://user-images.githubusercontent.com/7623019/34223241-defe99aa-e5be-11e7-985b-c16397376acb.png">
This could probably say "About CMS | CERN Open Data portal".

---

<img width="1072" alt="firefox - - screen shot 20 dec 2017 at 19 47 35" src="https://user-images.githubusercontent.com/7623019/34223245-e25d36d8-e5be-11e7-9019-ddb5553f9599.png">
This could probably say "Welcome to our updated… | CERN Open Data portal". Just realised that my selection and suggestion seem to imply some sort of word play; that's not my intention. If the title of the page is too long for the tag, I would suggest we truncate it if needed. No strong feelings.

---

For search pages, it could show "Search: [insert search keywords/facets here] | CERN Open Data portal".

**Comment by katilp** [comment]
👍 True, would be helpful also in navigating back through the page history, now they all look the same.

**Comment by psaiz** [comment]
This was done in https://github.com/cernopendata/opendata.cern.ch/pull/3544 
Closing the ticket
