### ISSUE TITLE
UI: make buttons in records clickable

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#2238]
Because of how the HTML is set up, one can only click the text within navigation buttons in records &mdash; clicking the button boxes themselves does nothing:

![clickablebuttons](https://user-images.githubusercontent.com/7623019/34223991-91f039ae-e5c1-11e7-85a7-2b7920b66a3c.gif)

**Comment by katilp** [comment]
👍 I have observed the same - or actually I only observed that clicking did not always change the page as I would have expected. Thanks @RaoOfPhysics for the explanation!

**Comment by psaiz** [comment]
This was fixed with the move from Angular to REACT. Now, we can click anywhere in the box
