### ISSUE TITLE
Download link to actual data not obvious

### ISSUE THREAD

**Issue by cbourjau** [cernopendata/opendata.cern.ch#2241]
I have been trying to download some ALICE data. The datasets point to json files[1] which only specify relative paths to the files. But I have not been able to find the absolute path to them. Maybe I'm missing something obvious. If not, I think that the actual location of the data should be trivial to find.

[1] http://opendata.cern.ch/record/1102

**Comment by RaoOfPhysics** [comment]
Hi @cbourjau. Thanks for flagging this and sorry about the problems getting to the datasets. Most of us at CERN are on break over the annual winter closure of the lab, but we'll be back from tomorrow. I hope some of our ALICE experts can jump in then and help you get access to the data. I think we may need to update the instructions on our portal.

**Comment by tiborsimko** [comment]
@cbourjau Indeed, it seems we are not publishing the full URLs for ALICE records on the new CERN Open Data portal pages. We'll fix this.

The files themselves are hosted on EOSPUBLIC, so for example for a file such as `/eos/opendata/alice/2010/LHC10h/000139038/ESD/3349/AliESDs.root`, one can use EOSPUBLIC HTTP gateway:

- `https://eospublichttp.cern.ch/eos/opendata/alice/...`

or download it via XRootD:

```console
$ xrdcp -v root://eospublic.cern.ch//eos/opendata/alice/2010/LHC10h/000139038/ESD/3349/AliESDs.root .
```

**Comment by katilp** [comment]
@tiborsimko NB, this is true for the CMS records as well. The direct file list is not there, only the indexes (e.g. http://opendata.cern.ch/record/5)

**Comment by tiborsimko** [comment]
- [ ] alice-analysis-modules.json
- [ ] alice-derived-datasets.json
- [ ] alice-learning-resources.json
- [ ] alice-reconstructed-data.json
- [ ] alice-vm-image.json
