### ISSUE TITLE
installation: harmonise service names

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2244]
Currently-used container names in our docker setup are:

- wdb
- web
- worker
- web-files
- postgresql
- redis
- elasticsearch
- elasticsearch-proxy
- rabbitmq
- nginx
- static

This has some drawbacks, e.g. the notion of "web" is wider than the sole application node, e.g. sometimes we use technology-based names ("nginx", "redis") and sometimes function-based names ("proxy", "cache").

We can standardise all names to use some homogeneous schema, for example:

- ``<service>-<function>`` 

to have `web-app`, `web-files`, `web-proxy`, denoting web service and various containers serving various aspects of the service.

The attention should be paid to the OpenShift service naming as well.

**Comment by psaiz** [comment]
And this might be a good moment to move from two independent docker compose files to a merging of files. The [example](https://docs.docker.com/compose/multiple-compose-files/merge/#example) is exactly what we want
