### ISSUE TITLE
CMS: LHE configs/instructions for 2012 MC

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2249]
Complete the provenance information (i.e. the configs of the data processing steps) for 2012 MC.
- Example of a complete provenance information for 2011: http://opendata.cern.ch/record/1330 (configs for LHE, SIM, HLT, RECO stesp extracted from DAS)

- [x] Check with MC experts that all MC files which have Pythia6HadronizerFilter as the generator process in the SIM config i.e.
`process.generator = cms.EDFilter("Pythia6HadronizerFilter",`
- example http://opendata.cern.ch/record/3030/files/c8c18849c66ed34bafa1f8cb42279272.configFile.py
should have a corresponding LHE step.
- Update (see below): EmptySource in process.source indicates no LHE
- [ ] Then find out if this LHE config file can still be found somewhere (not present in DAS for 2012 MC as the parent dataset(s) of AODSIM have been deleted?)

NB, that the LHE config file itself does not give any relevant information about the generator parameters
- example http://opendata.cern.ch/record/3372/files/947fc12e45a0789d78f4cf2e4a6cf6f4.configFile.py

so for the information chain it is not necessary (although would be very nice to have for full provenance). More importantly, the users should be instructed to check the LHE configuration with

![lhe](https://user-images.githubusercontent.com/5859918/34758322-be59cd46-f5d6-11e7-861f-dbd0bfb14272.PNG)

- [x] Add this piece of instruction for the 2012 MC files with Pythia6HadronizerFilter as the generator process

NB: the link http://opendata.cern.ch/docs/cms-getting-started does not work (made a separete issue #2250)

**Comment by katilp** [comment]
From https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePythia6Interface#Example_10_How_to_Process_Extern (and  cms-pag-conveners-generators )

`source = cms.Source("LHESource"`

indicates that an external generator is in use, but this is for the LHE step config itself.

The input to SIM for LHE cases is
# Input source
```
process.source = cms.Source("PoolSource",
    secondaryFileNames = cms.untracked.vstring(),
    fileNames = cms.untracked.vstring('/store/generator/Summer11LegpLHE/WHiggs0PHToBB_M-125p6_7TeV-JHUGenV4-pythia6-tauola/GEN/START53_LV4-v1/00000/88F21AB6-6CDA-E311-912C-02163E00E95E.root')
)

```
while in other cases

`source = cms.Source("EmptySource")`

**Comment by tiborsimko** [comment]
For each MC dataset, let's return the first ROOT file, which can be suitable for reading the LHE header information.

**Comment by tiborsimko** [comment]
... and use it for running `dumpLHEHeader.py input=file:somefile.root output=testout.lhe` commands in the CMS VM 2011.

**Comment by tiborsimko** [comment]
.. and check `mgproccard` and `MGRunCard` blocks in the LHE header.  (note that the latter might be unnecesserily repeated in the file)

**Comment by heitorPB** [comment]
after each `<MGRunCard>` block, there's a `MGGenerationInfo` block. This block is different each time it appears. To list all the blocks run `grep -A 5 -e "<MGGenerationInfo>" testout.lhe`:

```
[...]
<MGGenerationInfo>
#  Number of Events        :        5000
#  Integrated weight (pb)   : 84.4147976155
#  Truncated wgt (pb)       : 0.0337745828982
#  Unit wgt                 : 0.0168834038232
</MGGenerationInfo>
--
<MGGenerationInfo>
#  Number of Events        :        5000
#  Integrated weight (pb)   : 84.1004552943
#  Truncated wgt (pb)       : 0.04839983146
#  Unit wgt                 : 0.0168200910589
</MGGenerationInfo>
```

**Comment by heitorPB** [comment]
That was only for the [MadGraph generator](http://madgraph.physics.illinois.edu/).

For the dataset http://opendata.cern.ch/record/1352, made with [JHUGenerator](http://spin.pha.jhu.edu/), this is the output of `dumpLHEHeader.py`: [out.txt](https://github.com/cernopendata/opendata.cern.ch/files/2290219/out.txt):

```
<LesHouchesEvents version="1.0">
<header>
<!--
Output from the JHUGenerator v4.3.1 described in arXiv:1001.3396 [hep-ph],arXiv:1208.4018 [hep-ph],arXiv:1309.4819 [hep-ph]

   
   Command line: ./JHUGen Collider=1 PChannel=0 Process=0 Unweighted=1 ReadLHE=/afs/cern.ch/user/h/hroskes/work/public/HiggsPropertiesMC/JHUGen/H/VBFHiggs0M_M-125p6_7TeV-JHUGenV4/VBFHiggs0M_M-125p6_7TeV-JHUGenV4_0.lhe DecayMode1=0 DecayMode2=0 OffXVV=011 DataFile=VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4/VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4_0
   
   Input Parameter:
    Collider: P-P, sqrt(s)= 7000.00
    Resonance: spin=0, mass= 125.60 width= 0.004
               (This is ReadLHEFile mode. Resonance mass is read from LHE input file.)
    DecayMode1: 0  DecayMode2: 0
    Z-boson: mass=91.188, width=2.4952
    Interference: T
    
    spin-0-VV couplings: 
      generate_as=F
      ghg2= 0.10000000E+01 0.00000000E+00i
      ghg3= 0.00000000E+00 0.00000000E+00i
      ghg4= 0.00000000E+00 0.00000000E+00i
      ghz1= 0.00000000E+00 0.00000000E+00i
      ghz2= 0.00000000E+00 0.00000000E+00i
      ghz3= 0.00000000E+00 0.00000000E+00i
      ghz4= 0.10000000E+01 0.00000000E+00i
      ghz1_prime= 0.00000000E+00 0.00000000E+00i,    Lambda_z1=  1.0000E+04
      ghz2_prime= 0.00000000E+00 0.00000000E+00i,    Lambda_z2=  1.0000E+04
      ghz3_prime= 0.00000000E+00 0.00000000E+00i,    Lambda_z3=  1.0000E+04
      ghz4_prime= 0.00000000E+00 0.00000000E+00i,    Lambda_z4=  1.0000E+04
      Lambda=  1000.0
    
    LHE output: VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4/VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4_0.lhe
    Histogram output: VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4/VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4_0.dat
    Log file: VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4/VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4_0.log
    LHE input: /afs/cern.ch/user/h/hroskes/work/public/HiggsPropertiesMC/JHUGen/H/VBFHiggs0M_M-125p6_7TeV-JHUGenV4/VBFHiggs0M_M-125p6_7TeV-JHUGenV4_0.lhe
    

Output from the JHUGenerator v4.3.2 described in arXiv:1001.3396 [hep-ph],arXiv:1208.4018 [hep-ph],arXiv:1309.4819 [hep-ph]


   Command line: ./JHUGen Collider=1 Process=60 Unweighted=1 ReadCSmax=1 VegasNc2=2000 OffXVV=011 DataFile=7TeV0minus250

   Input Parameter:
    Collider: P-P, sqrt(s)= 7000.00
    Resonance: spin=0, mass= 125.60 width= 0.004
    DecayMode1: 0  DecayMode2: 0
    Z-boson: mass=91.188, width=2.4952

    OffXVV: FTT
    PChannel: 2
    PDFSet: 1
    Unweighted: T
    Interference: T

    spin-0-VV couplings:
      generate_as=F
      ghg2=  0.10000000E+01  0.00000000E+00i
      ghg3=  0.00000000E+00  0.00000000E+00i
      ghg4=  0.00000000E+00  0.00000000E+00i
      ghz1=  0.00000000E+00  0.00000000E+00i
      ghz2=  0.00000000E+00  0.00000000E+00i
      ghz3=  0.00000000E+00  0.00000000E+00i
      ghz4=  0.10000000E+01  0.00000000E+00i
      Lambda=  1000.0

    LHE output: 7TeV0minus250.lhe
    Histogram output: 7TeV0minus250.dat
    Log file: 7TeV0minus250.log

-->
</header>
<init>
    2212  2212  3.5000000E+03  3.5000000E+03  0  0  10042  10042  3  1
	4.3538821E-03	7.2559368E-06	1.0000000E+00	100
</init>
</LesHouchesEvents>
```

It refers to an input file `/afs/cern.ch/user/h/hroskes/work/public/HiggsPropertiesMC/JHUGen/H/VBFHiggs0M_M-125p6_7TeV-JHUGenV4/VBFHiggs0M_M-125p6_7TeV-JHUGenV4_0.lhe` which I don't have access to or doesn't exist anymore.
It contains all the information needed?

**Comment by heitorPB** [comment]
PR #2432 addresses all of this, right @katilp ?
