### ISSUE TITLE
CMS: link http://opendata.cern.ch/docs/cms-guide-to-the-cms-condition-database

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2251]
The link http://opendata.cern.ch/docs/cms-guide-to-the-cms-condition-database
in http://opendata.cern.ch/docs/cms-getting-started-2011 does not work.

Should be: http://opendata.cern.ch/docs/cms-guide-for-condition-database

**Comment by katilp** [comment]
@tiborsimko Can you have a look? In the production branch https://github.com/cernopendata/opendata.cern.ch/blob/production/cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, this is already correct:

`See detailed instructions for the use of condition data for different data-taking years in [the guide to the CMS condition database](/docs/cms-guide-for-condition-database).`

but the link is wrong in http://opendata.cern.ch/docs/cms-getting-started-2011

How's that possible or am I looking in the wrong file?

**Comment by katilp** [comment]
The fix was done in https://github.com/cernopendata/opendata.cern.ch/pull/2236

**Comment by tiborsimko** [comment]
This will be fixed on PROD once we deploy the QA branch there.
