### ISSUE TITLE
records: proper file serialisation

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2252]
There are indeed several cases of records having "directly attached files" and records having "files attached indirectly via file indexes". They behave differently, which is not ideal. We should clean the situation so that you would be able to access any known file using the same set of REST API procedures.

See also #2241 and #2247.

**Comment by tiborsimko** [comment]
Here are some more musings.

### 1. Simple records

Example: record ID 5001.

Currently, when somebody hits `/api/records/5001`, they see information about buckets:

```
 "_files": [
      {
        "bucket": "9c421a9a-b1ce-46ab-ac1f-d799b360c85d", 
        "checksum": "adler32:19ce6f2b", 
        "key": "BuildFile.xml", 
        "size": 331, 
        "version_id": "1ff6673a-4ac8-45ae-a137-37d925f905bc"
      }, 
```

and later down:

```
  "files": [
      {
        "bucket": "9c421a9a-b1ce-46ab-ac1f-d799b360c85d", 
        "checksum": "adler32:19ce6f2b", 
        "key": "BuildFile.xml", 
        "size": 331, 
        "uri": "root://eospublic.cern.ch//eos/opendata/cms/software/dimuon-spectrum-2011/BuildFile.xml", 
        "version_id": "1ff6673a-4ac8-45ae-a137-37d925f905bc"
      }, 
```

Since we only host open files that are all reachable on EOS, I think we don't really need to expose the concept of buckets.  That would complicate things for the end users. Hence proposing: 

- **Task One:** hide `_files`
- **Task Two:** keep `files` but hide the notion of buckets in there

Ideally we could show what we have in the fixtures:

```
  "files": [
    {
      "checksum": "adler32:ff63668a",
      "size": 305,
      "uri": "root://eospublic.cern.ch//eos/opendata/cms/software/HiggsExample20112012/BuildFile.xml"
    },
```

However, this shows the final ROOT endpoint, which is good for some users, but not exactly `wget` friendly for general public users.  These would rather expect a URL like:

```
http://opendata.cern.ch/record/5001/files/BuildFile.xml
```

which is exactly the URL that they see in the COD web interface.

- **Task Three:** consider exposing files with HTTP protocol, like:

```
  "files": [
    {
      "checksum": "adler32:ff63668a",
      "size": 305,
      "uri": "http://opendata.cern.ch/record/5001/files/BuildFile.xml",   
    },
```

However this would have a disadvantage for power users using XRootD.

Hence I'd propose to expose *both* HTTP and XRootD endpoints:

- **Task Three++:** think of nice JSON snippet that would expose both HTTP and XRootD endpoints for the same file, for example a convoluted one: 

```
 "files": [
    {
        "checksum": "adler32:ff63668a",
        "size": 305,
        "uris": [
            {
                "type": "http",
                "uri": "http://opendata.cern.ch/record/5001/files/BuildFile.xml"
            },
            {
                "type": "xrootd",
                "uri": "root://eospublic.cern.ch//eos/opendata/cms/software/HiggsExample20112012/BuildFile.xml"
            },
        ]
    },

```

or a flatted one:

```
"files": [
    {
        "checksum": "adler32:ff63668a",
        "size": 305,
        "uri_http": "http://opendata.cern.ch/record/5001/files/BuildFile.xml"
        "uri_xrootd": "root://eospublic.cern.ch//eos/opendata/cms/software/HiggsExample20112012/BuildFile.xml"
    },
```

Just for illustration.

**Comment by tiborsimko** [comment]
### 2. Records with index files

Example: record ID 6034.

The complexity is that the record stores only "index files", i.e. pointers to files that has file locations.

Example of an index file:

- http://opendata.cern.ch/record/6034/files/CMS_Run2012C_HTMHTParked_AOD_22Jan2013-v1_20000_file_index.txt

Current situation: `/api/records/6034` shows:

```
   "files": [
      {
        "bucket": "fc424b72-26e6-4f08-9e9e-8b5f41f46b9f",
        "checksum": "sha1:1086c34d1376bd7867dae12e35bd2a394ef5be1c",
        "description": "HTMHTParked AOD dataset file index (1 of 27) for access to data via CMS virtual machine",
        "key": "CMS_Run2012C_HTMHTParked_AOD_22Jan2013-v1_20000_file_index.json",
        "size": 288145,
        "type": "index.json",
        "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012C/HTMHTParked/AOD/22Jan2013-v1/file-indexes/CMS_Run2012C_HTMHTParked_AOD_22Jan2013-v1_20000_file_index.json",
        "version_id": "cf7d2203-80c9-411f-91c9-68c1f43b53ce"
      },
```

We can clean this as in the first use case of simple records, but we have to advertise that these are index files:


- **Task Four** expose index files, see Task Three++ but with different key, for example:

```
"index_files": [
    {
        "checksum": "adler32:...",
        "size": ...,
        "uri_http": "..."
        "uri_xrootd": "...
    },
```

(either flat or composed structure similarly to Task Three++)

- **Task Four++** For each "text" index file, we also have corresponding "rich"
  index file, which basically contains the same information, but in the JSON
  format. We can choose to expose these as well.


Example of a rich index file:

- http://opendata.cern.ch/record/6034/files/CMS_Run2012C_HTMHTParked_AOD_22Jan2013-v1_20000_file_index.json

containing:

```
  {
    "checksum": "adler32:7d78c4b2",
    "filename": "FEF4EBB3-A47F-E211-A432-00304867929E.root",
    "size": 4268374493,
    "uri": "root://eospublic.cern.ch//eos/opendata/cms/Run2012C/HTMHTParked/AOD/22Jan2013-v1/20000/FEF4EBB3-A47F-E211-A432-00304867929E.root"
  },
```

(The side complexity: we are using only "uri" there, not "uri_xrootd". We should think of this when deciding about "url_http", "uri_xrootd" highlighted above.)

For example, in the flat structure, we could expose:

```
"index_files_json": [
    {
        "checksum": "adler32:...",
        "size": ...,
        "uri_http": "..."
        "uri_xrootd": "...
    },
```

- **Task Five:** expose files behind the rich index files. When a user hits `/api/records/NNN`, the expectation is to see the full record content, i.e. all files belonging to a dataset.  This can be ~20,000 files.  Ideally, the serialiser should go through record "files" key, and if it sees we have text index files, it should download their JSON counterparts, and inject it into the serialised JSON output.

In this case, we would do the "rich file dereferencing" on the server side, so that the client does not have to bother about this on the client side.

Note that this need is similar to creating `distribution.DataDownload` information in the JSON-LD schema.org output that @hahirvon is working on. (#2275)

- **Task Six:** exposing `/record/NNN/files/XXX.CSV` for files resolved via rich file indexes.

It may be problematic to expose files behind rich file indexes via `.../files/...` URL` "as is", because they contain directories, for example:

`/22Jan2013-v1/20000/00321174-D57F-E211-A7F7-0026189438A5.root`

We could expose HTTP endpoints using EOSPUBLIC, but this would only have to be HTTPS, which does not work for old CMS 2012 VM. It would be suitable to offer downloads from opendata.  Option 1: reverse proxy to EOSPUBLIC via opendata.  Option 2: massage `.../files/...` to accept the concept of sub-directories. This is similar to the notion of "file assets" (`/record/NNN/files/assets/<path>`) that the UI front-end uses.  It would be good to harmonise both.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed by @pamfilos .
