### ISSUE TITLE
CMS: 2010 VM downloaded  from record 250 corrupted?

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2255]
If downloaded from http://opendata.cern.ch/record/250
the VM record for 2010 does not open(*) in VirtualBox.

Jakob pointed out that the size of the file is smaller than expected, so it could be corrupt.
The versions downloaded previously continue working.

Any possible reasons for changes in this file?

(*) Error:

> Failed to import appliance C:/Users/koti/Downloads/CMS-OpenData-1.0.0-rc7.ova.
>
> Could not create the imported medium 'C:\Users\koti\VirtualBox VMs\CMS-OpenData-1.0.0-rc7_1\CMS-OpenData-1.0.0-rc7-disk1.vmdk' (VERR_EOF).
>
> Result Code:    VBOX_E_FILE_ERROR (0x80BB0004)
> Component:      ApplianceWrap
> Interface:      IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

**Comment by katilp** [comment]
NB: the original is in 
http://cernvm.cern.ch/releases/CMS-OpenData-1.0.0-rc7.ova
and loads without problems.

**Comment by tiborsimko** [comment]
Indeed, the file was corrupted.  Fixed.
