### ISSUE TITLE
CMS: 2010 collision data records, rcommended release for analysis is wrong, links wrong

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2257]
In all 2010 collision data records:

http://opendata.cern.ch/search?page=1&size=20&type=Dataset&subtype=Collision&experiment=CMS&year=2010

- [x] the recommended release for analysis is wrong. Should be CMSSW_4_2_8 as in the instructions

**Comment by atrisovic** [comment]
@katilp This means that `CMSSW_4_2_1_patch1` should be replaced with `CMSSW_4_2_8` ?

**Comment by katilp** [comment]
@atrisovic Yes, that's correct!
