### ISSUE TITLE
CMS: update disclaimer to explicitly cover item on/linked from the portal

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2263]
In http://opendata.cern.ch/docs/about-cms
under Disclaimer, update

- [x] "Neither CMS nor CERN endorse any works, scientific or otherwise, produced using these data." to  "Neither CMS nor CERN endorses any works, scientific or otherwise, produced using these data, even if available on, or linked from, this portal.

- [x] "If you are interested in more, please contact nearest CMS university/institute" to "If you are interested in joining the CMS Collaboration, please contact your nearest CMS university/institute."

**Comment by tiborsimko** [comment]
Closed by #2325.
