### ISSUE TITLE
CMS: update troubleshooting guide with information about restricted internet connections

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2265]
If the internet connection from the user's side is restricted, it may be that some ports and IPs need to be whitelisted so that VM installs properly (download from cvmfs)

The list may change in time, so it is probably best to describe the problem in
http://opendata.cern.ch/docs/cms-guide-troubleshooting
under "Virtual machine"
and ask users to contact opendata-support.

In Jan 2018, the VM installation got working with the list provided in
https://cern.service-now.com/service-portal/view-request.do?n=RQF0926154

Another similar issues for file access through xrootd was taken care of in Dec 2017
https://cern.service-now.com/service-portal/view-incident.do?n=INC1543036

**Comment by tiborsimko** [comment]
Closed by #2326.
