### ISSUE TITLE
records: split Configurations into RECO/HLT/LHE/SIM...

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2270]
"Configurations" should be split into RECO, HLT, LHE, SIM... to ease the navigation in facet value list.

**Comment by atrisovic** [comment]
I don't understand what configurations? (records don't have configurations)

**Comment by katilp** [comment]
@atrisovic 
http://opendata.cern.ch/search?page=1&size=20&type=Supplementaries&subtype=Configuration&experiment=CMS

**Comment by tiborsimko** [comment]
Example: for `cernopendata/modules/fixtures/data/records/cms-configuration-files-2012.json`, see:

```json
  "title": "Configuration file for RECO step HIG-Summer12DR53X-01500_2_cfg",
    "type": {
      "primary": "Supplementaries",
      "secondary": [
        "Configuration"
      ]
```

which should be transformed into:

```json
  "title": "Configuration file for RECO step HIG-Summer12DR53X-01500_2_cfg",
    "type": {
      "primary": "Supplementaries",
      "secondary": [
        "Configuration RECO"
      ]
```

based on the RECO found in the title in 4th position.
