### ISSUE TITLE
CMS: pileup sample for 2011 and 2012 MC generation

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2272]
Transfer of /MinBias_TuneZ2_7TeV-pythia6/Summer11Leg-START53_LV4-v1/GEN-SIM

 https://cmsweb.cern.ch/phedex/prod/Request::View?request=1205370

This is the pileup sample to be used for MC generation for 2011 data

**Comment by tiborsimko** [comment]
The files are available on EOS under /eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM but we don't seem to have a record created yet...

**Comment by katilp** [comment]
Closing as the transfer is done and dublicate of #2331
