### ISSUE TITLE
global: add opendata.cern.ch to datacite/freya when JSON-LD fully implemented

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#2303]
Here is the link https://github.com/datacite/freya/blob/master/schema_org.csv
where we should add the opendata service when json-ld is ready.

**Comment by tiborsimko** [comment]
This is now ready, the schema.org and JSON-LD are now deployed. Would you like to add it yourself?

**Comment by ioannistsanaktsidis** [comment]
I have already an open PR for this waiting to be merged.

**Comment by ioannistsanaktsidis** [comment]
Closing as opendata is added to the list.
