### ISSUE TITLE
views: sanitise arguments

### ISSUE THREAD

**Issue by atrisovic** [cernopendata/opendata.cern.ch#2315]
- [x] the arguments should be sanitised so that people are not tempted to try to trick the redirector (check whether year is a four digit integer and whether exp is from the allowed list).

- [x] CMS 2010 records use /vm/cms which would redirect them to 2011 (latest status). We therefore need to amend 2010 records to use /vm/cms/2010 there.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed.
