### ISSUE TITLE
CMS: new record for the contextualization file on the new 2010 VM CMS-OpenData-1.1.0.ova

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2322]
Need a new record (as http://opendata.cern.ch/record/253)

The files are in

https://github.com/cernvm/public-contexts/blob/master/cms-opendata.context

Need to check with @jblomer:

- [ ] if this file contains everything that we currently have in  three separate files  in record 253

- [ ] if the current text under "How to use?" is OK (a part from the VM version CMS-OpenData-1.3.0.ova -> CMS-OpenData-1.1.0.ova):

 

> First, you need to run a normal Micro-CernVM, using your own context so you can login. Copy the attached files to the running VM and then login.
> 
> Inside the VM, you first need a copy of the latest Micro-CernVM release as a template for the Open Data image. Download it, inside the running VM, from: http://cernvm.cern.ch/releases/production/cernvm3-micro-2.8-6.hdd placing it in the same directory as the other files.
> 
> Run the script:./cernvm-script which will produce some output on the terminal, and then finish.
> 
> The result should be a file with the title coming from the -n field in the script. In this case, the file we're interested in is: CMS-OpenData-1.3.0.ova which can be copied from the running VM to elsewhere. 

To be linked to http://opendata.cern.ch/record/250 (see https://github.com/cernopendata/opendata.cern.ch/issues/1298#issuecomment-364096950)

**Comment by jblomer** [comment]
@katilp The https://github.com/cernvm/public-contexts/blob/master/cms-opendata.context file is only replacing the cms-user-data.txt from record 253, not the other two files.

The description is fine, I think.  In the cernvm-script file, I'd replace the last line by

    # The cvm2ova utility is part of CernVM and can be independently downloaded from
    # https://github.com/cernvm/cernvm-config/blob/master/usr/bin/cvm2ova

**Comment by tiborsimko** [comment]
Note: the version is now 1.1.2.

**Comment by katilp** [comment]
@tiborsimko Can we close this? The earlier VM versions are deprecated and we have the contextualization script record for the latest image 1.1.4 in http://opendata-dev.cern.ch/record/248
