### ISSUE TITLE
records: missing CMS 2011 HT single file

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2324]
Check missing file for the CMS 2011 HT dataset:

```/eos/opendata/cms/Run2011A/HT/AOD/12Oct2013-v1/20000/76CFA6F2-0A40-E311-8EF4-0026189438AA.root```

It was there in the past.

(stemmed from https://github.com/cernopendata/opendata.cern.ch/pull/2314#issuecomment-364014925)

**Comment by katilp** [comment]
Checking in DAS: 

file dataset=/HT/Run2011A-12Oct2013-v1/AOD

file= /store/data/Run2011A/HT/AOD/12Oct2013-v1/*/76CFA6F2-0A40-E311-8EF4-0026189438AA.root

https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fdata%2FRun2011A%2FHT%2FAOD%2F12Oct2013-v1%2F20000%2F76CFA6F2-0A40-E311-8EF4-0026189438AA.root&instance=prod%2Fglobal

**Comment by katilp** [comment]
Transfer request done:
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1216596

**Comment by tiborsimko** [comment]
File copied:

```console
$ eos file rename /eos/opendata/cms/upload/data/Run2011A/HT/AOD/12Oct2013-v1/20000/76CFA6F2-0A40-E311-8EF4-0026189438AA.root /eos/opendata/cms/Run2011A/HT/AOD/12Oct2013-v1/20000/76CFA6F2-0A40-E311-8EF4-0026189438AA.root
```

We still have to amend the fixtures and file listings.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko @katilp which fixtures we need to amend ?

**Comment by tiborsimko** [comment]
File listings regenerated, fixture amendment coming...
