### ISSUE TITLE
CMS: MC pile-up in GEN-SIM formart

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2331]
The dataset needed for adding pile-up on the top of any newly produced MC has now been transferred
/MinBias_TuneZ2_7TeV-pythia6/Summer11Leg-START53_LV4-v1/GEN-SIM

https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1516101583%3Bnode%3D2241%3Brequest%3D1205370

We will use it for testing MC production on the open data setup and it will become available together with an example and possibly a guide page.

This dataset can be placed under https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM

Or @tiborsimko do you have other preferences?

**Comment by tiborsimko** [comment]
@katilp Done. I have transferred the files and created indexes:

- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM/START53_LV4-v1/file-indexes

P.S. Please note that this dataset was transferred from `Summer11Leg/...` to `Summer11LegDR/...` Hope that's OK.

**Comment by katilp** [comment]
Record still needs to be created in COPD

**Comment by katilp** [comment]
WIP: Tentative record in https://github.com/katilp/sandbox/blob/master/cms-pileup-data-2011 to be udates with the template updates

Generator parameters:

`edmProvDump -f "Module: generator SIM" root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM/START53_LV4-v1/10000/00064CCC-A218-E311-A2E9-D485646A4E1A.root`

Event filtering information for 1 processing steps is available.
The ParameterSets will be printed out, with the oldest printed first.
ParameterSetID: ea0972193530f531086947d06eb0f121
{
  EndPathPositions: vint32 tracked  = {+0}
  EndPaths: vstring tracked  = {'RAWSIMoutput_step'}
  InProcessHistory: bool tracked  = true
  SelectEvents: vstring tracked  = {'generation_step'}
 }
     -------------------------
Processing History:
  SIM '' '"CMSSW_5_3_11_patch6"' (4d40a28013bf054c4c058f4cda4aec2b)
---------Producers with data in file---------
Module: generator SIM
 PSet id:9c83f39671bfdda77a94b3990f945a84
 products: {
  GenEventInfoProduct_generator__SIM.
  GenRunInfoProduct_generator__SIM.
  edmHepMCProduct_generator__SIM.
 }
 parameters: {
  @module_edm_type: string tracked  = 'EDFilter'
  @module_label: string tracked  = 'generator'
  @module_type: string tracked  = 'Pythia6GeneratorFilter'
  comEnergy: double tracked  = 7000
  PythiaParameters: PSet tracked = ({
   parameterSets: vstring tracked  = {'pythiaUESettings','processParameters'}
   processParameters: vstring tracked  = {'MSEL=0         ! User defined processes','MSUB(11)=1     ! Min bias process','MSUB(12)=1     ! Min bias process','MSUB(13)=1     ! Min bias process','MSUB(28)=1     ! Min bias process','MSUB(53)=1     ! Min bias process','MSUB(68)=1     ! Min bias process','MSUB(92)=1     ! Min bias process, single diffractive','MSUB(93)=1     ! Min bias process, single diffractive','MSUB(94)=1     ! Min bias process, double diffractive','MSUB(95)=1     ! Min bias process'}
   pythiaUESettings: vstring tracked  = {'MSTU(21)=1     ! Check on possible errors during program execution','MSTJ(22)=2     ! Decay those unstable particles','PARJ(71)=10 .  ! for which ctau  10 mm','MSTP(33)=0     ! no K factors in hard cross sections','MSTP(2)=1      ! which order running alphaS','MSTP(51)=10042 ! structure function chosen (external PDF CTEQ6L1)','MSTP(52)=2     ! work with LHAPDF','PARP(82)=1.832 ! pt cutoff for multiparton interactions','PARP(89)=1800. ! sqrts for which PARP82 is set','PARP(90)=0.275 ! Multiple interactions: rescaling power','MSTP(95)=6     ! CR (color reconnection parameters)','PARP(77)=1.016 ! CR','PARP(78)=0.538 ! CR','PARP(80)=0.1   ! Prob. colored parton from BBR','PARP(83)=0.356 ! Multiple interactions: matter distribution parameter','PARP(84)=0.651 ! Multiple interactions: matter distribution parameter','PARP(62)=1.025 ! ISR cutoff','MSTP(91)=1     ! Gaussian primordial kT','PARP(93)=10.0  ! primordial kT-max','MSTP(81)=21    ! multiple parton interactions 1 is Pythia default','MSTP(82)=4     ! Defines the multi-parton model'}
  })
 }

**Comment by katilp** [comment]
Update FIXME in the current http://opendata-dev.web.cern.ch/record/37 with the link to the config/ gen fragment

**Comment by katilp** [comment]
In a similar way as for 2012 pile-up sample #2446:

To do:
- [ ] add the production script to the record https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/EWK-Summer11Leg-00012
- [ ] prepare a separate record for the sim config file https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/af4431aa75037618429e3164db9f3415/configFile (NB this is the same file as for 2012 pileup - makes sense as same legacy production)
- [ ] see if gen. fragment https://raw.githubusercontent.com/cms-sw/genproductions/V01-00-46/python/MinBias_TuneZ2_7TeV_pythia6_cff.py could be directly  displayed in a similar way as production script
