### ISSUE TITLE
CMS: 2010 MC - initial considerations

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2339]
MC samples corresponding to 2010 data have been identified and could be possibly released during 2018.

A full set is (`dataset=/*/*START42*/AODSIM`): 
https://cmsweb.cern.ch/das/request?instance=prod%2Fglobal&view=list&input=dataset%3D%2F%2A%2F%2ASTART42%2A%2FAODSIM&idx=200&limit=50
resulting to [731 TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2F*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29)

Limited "general purpose" subsets can be identified for different processes
- QCD (with TuneZ2*): https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*QCD*TuneZ2*%2F*START42*%2FAODSIM
resulting to 64 datasets and [118.3 TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2F*QCD*TuneZ2*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29)
- DY (with TuneZ2*): https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*DY*TuneZ2*%2F*START42*%2FAODSIM
resulting to 36 datasets and [50.9TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2F*DY*TuneZ2*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29)
- Z: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FZ*%2F*START42*%2FAODSIM
resulting to 215 datasets and [47.1TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2FZ*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29) (can exclude "prime" and "Dark" but reduces only 3 TB, excluding ZH reduces 6 TB)
- W: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FW*%2F*START42*%2FAODSIM
resulting to 278 datasets and [122.9TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2FW*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29) (can exclude "prime" and "Dark" but reduces only 4 TB, excluding WH reduces 10TB)
- T: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FT*%2F*START42*%2FAODSIM
resulting to 283 datasets and [84.4TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2FT*%2F*START42*%2FAODSIM+%7C+sum%28block.size%29)

Total of these:  423.6 TB

NB:
- does selecting TuneZ2 for all these subset select only the bg samples? 
- not all configs available through CMSDAS (showstopper, if no alternative way to find generator parameters)
   - configs available in https://github.com/cms-sw/cmssw/tree/CMSSW_4_2_X/Configuration/Generator/python, but is it possible to match them with the dataset by the dataset name (or other information available through CMSDAS)?
   - some gen done with an earlier CMSSW, branches starting only from 4_1_X are available in cms-sw/cmssw
   - Shahzad has made several CMSSW version needed for data taking available in https://github.com/cms-sw/cmssw-cvs, e.g. and there the config are available e.g. https://github.com/cms-sw/cmssw-cvs/tree/CMSSW_3_8_5_onlpatch3/Configuration/Generator/python 
   - if the gen processing CMSSW version is known, can ask these versions to be added to https://github.com/cms-sw/cmssw-cvs if needed

Update from Hannes (15.3.2018)
Summer12-LowPU2010_DR42 would be a reasonable subset
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Summer12-LowPU2010_DR42*%2FAODSIM
Sums to 72 TB

**Comment by katilp** [comment]
Use the data popularity monitor to judge 
- https://cmsweb.cern.ch/popdb/popularity/dataSetTable
- set the relevant time range (up to beg 2012?)
- generate the table and read out as json (OK)
- read in a jupyter notebook as a pandas dataframe (OK)
- sort by the most popular (by n users) (OK)
- read the list of [datasets](https://cmsweb.cern.ch/das/request?view=plain&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*START42*%2FAODSIM) (OK)
- pick the corresponding entries from the dataframe  (slightly beyond my skills... WIP)

Problems:
- the popularity of the exact dataset (with a defined reprocessing) does not necessarily reflect the real relevance of the dataset. Studies may have been completed with an earlier version of the sample.
- is the n users the best popularity criteria? or n of accesses? Not certainly the cpu time.

**Comment by katilp** [comment]
Updates done in https://github.com/katilp/cms-data-popularity/blob/master/compare-data-popularity.ipynb

- find out the popularity by the process name (summing all different reprocessing together)
- for the moment, summing up all dataset types together (AODSIM, GEN-SIM-RECO, USER...)

**Comment by heitorPB** [comment]
@katilp i got this list of cmsDriver scripts:

```
/CEPDijets_M-100_7TeV-exhume/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/CEPDijets_M-100_7TeV-exhume/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/DPEDijets_Pt30_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/DPEDijets_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
/QCD_HT-1000ToInf_TuneZ2Star_7TeV-madgraph-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/QCD_HT-1000ToInf_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_HT-100To250_TuneZ2Star_7TeV-madgraph-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/QCD_HT-100To250_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_HT-250To500_TuneZ2Star_7TeV-madgraph-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/QCD_HT-250To500_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_HT-500To1000_TuneZ2Star_7TeV-madgraph-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/QCD_HT-500To1000_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_HT-50To100_TuneZ2Star_7TeV-madgraph-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/QCD_HT-50To100_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_7TeV_pythia8/LowPU2010-START42_V17B-v3/GEN-SIM.sh
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_Pt-15to1000_fwdJet_bwdJet_TuneEE3C_Flat_7TeV_herwigpp/LowPU2010-START42_V17B_BS2011-v2/GEN-SIM.sh
/QCD_Pt-15to1000_fwdJet_bwdJet_TuneEE3C_Flat_7TeV_herwigpp/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_Pt-15to1000_TuneEE3C_Flat_7TeV_herwigpp/LowPU2010-START42_V17B_BS2011-v2/GEN-SIM.sh
/QCD_Pt-15to1000_TuneEE3C_Flat_7TeV_herwigpp/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_Pt-15to3000_Tune23_Flat_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010-START42_V17B-ext-v1/GEN-SIM.sh
/QCD_Pt-15to3000_Tune4C_Flat_HFshowerLibrary_7TeV_pythia8/LowPU2010-START42_V17B-v3/GEN-SIM.sh
/QCD_Pt-15to3000_Tune4C_Flat_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/QCD_Pt-15to3000_Tune4C_Flat_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveDijetsMinus_Pt30_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/SingleDiffractiveDijetsMinus_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
/SingleDiffractiveDijetsPlus_Pt30_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v3/GEN-SIM.sh
/SingleDiffractiveDijetsPlus_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveWToENu_eta-minus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v2/GEN-SIM.sh
/SingleDiffractiveWToENu_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveWToENu_eta-plus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/SingleDiffractiveWToENu_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveWToMuNu_eta-minus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/SingleDiffractiveWToMuNu_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveWToMuNu_eta-plus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v2/GEN-SIM.sh
/SingleDiffractiveWToMuNu_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveZToEE_M-20_eta-minus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/SingleDiffractiveZToEE_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveZToEE_M-20_eta-plus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/SingleDiffractiveZToEE_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-minus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v4/GEN-SIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-plus_7TeV-pomwig/LowPU2010-START42_V17B_BS2011-v4/GEN-SIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM.sh
/SingleDiffractiveZToMuMu_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
/WToENu_TuneZ2star_7TeV-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/WToENu_TuneZ2star_7TeV-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
/WToMuNu_TuneZ2star_7TeV-pythia6/LowPU2010-START42_V17B_BS2011-v1/GEN-SIM.sh
/WToMuNu_TuneZ2star_7TeV-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM.sh
```

50 scripts in total, 1/4 of the list...

**Comment by heitorPB** [comment]
More information about those datasets here:
http://hpascoal.web.cern.ch/hpascoal/tmp/lowPU.html

**Comment by katilp** [comment]
Transfer requests done
- https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1541949079%3Bnode%3D2241%3Brequest%3D1555481
- 
https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1541949109%3Bnode%3D2241%3Brequest%3D1555480

**Comment by katilp** [comment]
@tiborsimko This is the list of datasets to be included in 2010 MC (now in transfer)

/WToMuNu_TuneZ2star_7TeV-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/WToENu_TuneZ2star_7TeV-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/SingleDiffractiveZToMuMu_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/SingleDiffractiveZToMuMu_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveZToMuMu_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/SingleDiffractiveZToMuMu_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveZToEE_M-20_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveZToEE_M-20_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveWToMuNu_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveWToMuNu_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveWToENu_eta-plus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveWToENu_eta-minus_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveDijetsPlus_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/SingleDiffractiveDijetsMinus_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/QCD_Pt_80to150_fwdJet_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_80to150_fwdJet_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_80to150_fwdJet_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_80to150_fwdJet_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_80to120_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_80to120_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_600to800_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_600to800_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_5to15_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_50to80_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_50to80_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_470to600_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_470to600_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_40to80_fwdJet_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_40to80_fwdJet_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_40to80_fwdJet_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_40to80_fwdJet_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_30to50_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_30to50_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_300to470_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_300to470_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_25to40_fwdJet_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_25to40_fwdJet_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_25to40_fwdJet_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_25to40_fwdJet_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_170to300_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_170to300_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_15to30_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_15to30_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_150toInf_fwdJet_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_150toInf_fwdJet_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v2/AODSIM
/QCD_Pt_150toInf_fwdJet_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_150toInf_fwdJet_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_120to170_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_120to170_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_10to25_fwdJet_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_10to25_fwdJet_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_10to25_fwdJet_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_10to25_fwdJet_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt_0to5_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-80to120_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-600to800_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-50to80_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-470to600_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-30to50_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-300to470_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-170to300_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to30_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to3000_TuneZ2star_Flat_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v2/AODSIM
/QCD_Pt-15to3000_TuneZ2star_Flat_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to3000_Tune4C_Flat_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to3000_Tune4C_Flat_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to3000_Tune23_Flat_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v2/AODSIM
/QCD_Pt-15to3000_Tune23_Flat_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to1000_fwdJet_bwdJet_TuneEE3C_Flat_7TeV_herwigpp/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-15to1000_TuneEE3C_Flat_7TeV_herwigpp/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_Pt-120to170_Tune23_HFshowerLibrary_7TeV_herwigpp/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/QCD_HT-50To100_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_HT-500To1000_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_HT-250To500_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_HT-100To250_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/QCD_HT-1000ToInf_TuneZ2Star_7TeV-madgraph-pythia6/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIM
/MinBias_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v2/AODSIM
/MinBias_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_NoPileUp_START42_V17C-v1/AODSIM
/MinBias_TuneZ2star_Castor_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17C-v1/AODSIM
/MinBias_TuneZ2star_Castor_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/MinBias_TuneZ2star_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17C-v1/AODSIM
/MinBias_TuneZ2star_7TeV_pythia6/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/MinBias_TuneZ1_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/MinBias_TuneZ1_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_NoPileUp_START42_V17C-v1/AODSIM
/MinBias_TuneD6T_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_NoPileUp_START42_V17C-v1/AODSIM
/MinBias_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_NoPileUp_START42_V17C-v1/AODSIM
/MinBias_Tune4C_Castor_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17C-v1/AODSIM
/MinBias_Tune4C_Castor_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/MinBias_Tune4C_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17C-v1/AODSIM
/MinBias_Tune4C_7TeV_pythia8/Summer12-LowPU2010_DR42-PU_S0_START42_V17B-v1/AODSIM
/DYToMuMu_M-20_TuneZ2Star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/DYToEE_M_50To130_Tune4C_HFshowerLibrary_7TeV_pythia8/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/DYToEE_M-20_TuneZ2star_HFshowerLibrary_7TeV_pythia6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/DPEDijets_Pt30_7TeV-pomwig/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v2/AODSIM
/CS_Pt_80to120_CTEQ6L1_HFshowerLibrary_7TeV_herwig6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/CS_Pt_50to80_CTEQ6L1_HFshowerLibrary_7TeV_herwig6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/CS_Pt_30to50_CTEQ6L1_HFshowerLibrary_7TeV_herwig6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/CS_Pt_120to9999_CTEQ6L1_HFshowerLibrary_7TeV_herwig6/Summer12-LowPU2010_DR42_PU_S0_START42_V17B-v1/AODSIM
/CEPDijets_M-100_7TeV-exhume/Summer12-LowPU2010_DR42_BS2011_PU_S0_START42_V17B-v1/AODSIMo

**Comment by tiborsimko** [comment]
@katilp Thanks, I started the new data ingestion project in https://github.com/cernopendata/data-curation/tree/master/cms-2010-simulated-datasets

@ArtemisLav Can you please supply 100 DOIs for these datasets? E.g. create `inputs/dois.txt` file in that place...

**Comment by ArtemisLav** [comment]
> @ArtemisLav Can you please supply 100 DOIs for these datasets? E.g. create `inputs/dois.txt` file in that place...

@tiborsimko Since the number is this large, it would be much faster/better if we used the DOI minting script for this, no?

**Comment by tiborsimko** [comment]
Yes, the script can generate the required number of unique DOIs that we can then use for these datasets,  the given file would simply hold them (because we don't have central DB for these until the records are created and uploaded), e.g. following what we did for OPERA lately https://github.com/cernopendata/data-curation/blob/master/opera-2017-multiplicity-studies/inputs/dois-opera-818.txt

**Comment by ArtemisLav** [comment]
@annatrz Could you please generate these 100 DOIs for CMS (via script)?

**Comment by tiborsimko** [comment]
@heitorPB The record IDs can be `710, 711, ..., 810` for these records.

**Comment by heitorPB** [comment]
Records are in the master branch (PR #2493) with record IDs `710, 711, ..., 809` and the DOIs from https://github.com/cernopendata/data-curation/pull/20

**Comment by ArtemisLav** [comment]
Just leaving a note here that we'll need to mint the DOIs before/when these datasets show on PROD.

**Comment by tiborsimko** [comment]
@ArtemisLav The file transfer is also not finished, so the addition of files and indexes is also to be done still...

**Comment by katilp** [comment]
To do:
- [ ] build the file listing indexes
- [ ] add them to the records in `cms-simulated-datasets-2010.json`
