### ISSUE TITLE
CMS: update instructions in the luminosity records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2342]
Update instructions in the luminosity records 
http://opendata.cern.ch/search?page=1&size=20&type=Software&type=Supplementaries&subtype=Luminosity

- [x] In [the 2011 record](http://opendata.cern.ch/record/1051) 
Replace: 

> If you are using prescaled triggers, you can find the HLT trigger prescale factors for different run ranges in trigger configuration files listed in this record (under "PrescaleService"). Note that these factors may change during a run, and the change of prescales (run, lumi section, index of prescales) is recorded in prescale2011.txt. In this case you may also need detailed list of luminosity by lumi section in 2011lumibyls.csv for the list of validated runs and lumi sections.

with:

> If you are using prescaled triggers, you can find the trigger prescale factors in the event loop as shown in [the trigger example](http://opendata.cern.ch/record/5004). The change of prescales (run, lumi section, index of prescales) is also recorded in prescale2011.txt.

> For luminosity calculation, a detailed list of luminosity by lumi section is provided in 2011lumibyls.csv for the list of validated runs and lumi sections.

- [x] Idem for [the 2012 record](http://opendata.cern.ch/record/1052) , as above with 2011->2012

- [x] In [the 2010 record](http://opendata.cern.ch/record/1050) , add

> If you are using prescaled triggers, you can find the trigger prescale factors as shown in [the trigger example](http://opendata.cern.ch/record/5003).

@caredg Does that make sense? The prescale listing is actually not needed anywhere, but can be still kept in the lumi records, it does no harm either...

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
