### ISSUE TITLE
CMS: instructions and examples for MC generation

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2344]
We should provide:
- guide page for MC generation (docs cfr http://opendata.cern.ch/docs/cms-guide-trigger-system)
- examples for 2010 and 2011-2012 (records cfr  http://opendata.cern.ch/record/5003 and http://opendata.cern.ch/record/5004).
  
Should cover:
- cmsdriver (cfr page 7 in @caredg 's [slides](https://indico.cern.ch/event/707169/contributions/2906362/attachments/1607580/2551373/LongLivedAndExamples_DPOA_ECarreraFNavarro.pdf))
- use of built-in pythia
- use of external generators and input as an LHE file?
- pile-up (see #2272 for file transfer and http://opendata.cern.ch/docs/cms-guide-pileup-simulation for the pile-up guide page)

Needs:
- pile-up samples (see #2272, 2011 sample transferred)

**Comment by katilp** [comment]
See also cmsdriver in context of config file creation for data rereco in #2439.
Maybe a separate instruction page for it?

**Comment by heitorPB** [comment]
PR #2432 adds information on how to extract the gen parameters. Both pages should be a complement to each other.

**Comment by katilp** [comment]
GT START42_V17B for 2010 MC now available on /cvmfs

**Comment by katilp** [comment]
@caredg Would you have a time estimate for this? We now have @heitorPB 's page, with a general overview of the MC production steps and detailed instructions for finding the generator parameters for existing open data MC, available in http://opendata-dev.cern.ch/docs/cms-mc-production-overview
The pile-up gen-sim samples will appear as records 36 and 37, for 2011 and 2012 respectively.

**Comment by caredg** [comment]
@katilp I am hoping instructions and examples for MC generation will be ready next week.  I am starting to grab everything we have and put all together now!

**Comment by katilp** [comment]
@caredg thanks, very good! Note also some GEN-SIM production testing (connected to upgrade ML samples in CMSSW_10_2_5 and reading of GT: 102X_upgrade2018_design_v9) in https://github.com/cernopendata/opendata.cern.ch/issues/2459#issuecomment-447324968

**Comment by katilp** [comment]
@caredg Would you make a PR for the instruction page and for a corresponding code example?

**Comment by caredg** [comment]
> @caredg Would you make a PR for the instruction page and for a corresponding code example?

Yes, I can do that.  Now, I am not sure if each example that we have managed to put together should get its own record in the open portal, like we did at the bottom of [these instructions](http://opendata.cern.ch/docs/cms-guide-trigger-system) , for instance.  Or should I just point directly to the corresponding github areas?  Also, we should probably move the repository with the examples to the cms-opendata area instead of the cms-legacydata (or should we do that later?)  if the former, I shall check with @CesMon so we don't leave anything off

**Comment by katilp** [comment]
@caredg I think it is good to have the examples as portal records, like it was done for trigger examples. It has the advantage of taking care of the DP aspect (i.e. zipped versioned directory in addition to the link to the github repo)

**Comment by caredg** [comment]
Ok, I have finally made the pull request.  I actually ran this through the dockerized version of the portal locally, and it seems to work.  I have a couple of questions:
1. Who will make the records for the 2010, 2011, 2012 example bundles mentioned in the guide? Should I initiate the request or make them myself? Is there an automatic procedure?  The examples now reside at:
https://github.com/cms-opendata-analyses/EventProductionExamplesTool/tree/2010
https://github.com/cms-opendata-analyses/EventProductionExamplesTool/tree/2011
https://github.com/cms-opendata-analyses/EventProductionExamplesTool/tree/2012

2. Some of the above have a few examples, like the 2011, distributed in packages.   Actually we have a couple more in mind which we will need to integrate later.  Will adding those mess up the records?

**Comment by katilp** [comment]
Very good, thanks!

For the SW records, no automatic procedure yet, we should come up with one (i.e. what we've discussed e.g. from a templated readme or else)

For now, pls make a PR, you can create a new cms-tools-eventproduction-examples.json (or similar as long as it starts with cms-tools as discussed). The three records can go to that same file.
You can use https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-trigger-examples.json as the base structure, and leave FIXMEs for recids, and leave "files" out, Tibor will complete it when attaching the zip of the repo.
NB that we use data_created to refer to the data-taking year (it is a bit confusing, but comes from the collision data records)

For the changes in the future, a new release can be made and the record updated correspondingly, or a new record added (@tiborsimko ?)

**Comment by tiborsimko** [comment]
> For the changes in the future, a new release can be made and the record updated correspondingly, or a new record added (@tiborsimko ?)

For changes to 2010-2012 example records, in case of minor changes, we could take a new snapshot and attach the new tarball to the same record. We already do that for VM records actually (even for bigger changes there!)  

For new records, say 2016, or in case the policy change how the examples are developed, we could new bibliographic records and  "deprecate"  current ones and point them to new ones.  

Both techniques are basically possible, so we can select what suits the best when the time comes.

**Comment by katilp** [comment]
To do:
- attach the zips to the three SW records (now in `/eos/opendata/cms/upload/kati/zips`
