### ISSUE TITLE
CMS: raw data record, remove "Recommended release for analysis:"

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2346]
In the RAW data record http://opendata.cern.ch/record/35
there is a double description under System details:

"Recommended release for analysis: Recommended release for reconstruction: CMSSW_5_3_32"

should be:

"Recommended release for reconstruction: CMSSW_5_3_32"

**Comment by tiborsimko** [comment]
This needs to change the record fixtures:

```json
  "system_details": {
    "global_tag": "FT_53_LV5_AN1",
    "release": "Recommended release for reconstruction: CMSSW_5_3_32"
  },
```

and the display template:

```jinja
{% if record.system_details.release %}
    {% if record.type.primary == 'Software' %}
    <label>Software release:</label>
    {% else %}
    <label>Recommended release for analysis:</label>
    {% endif %}
    <span>{{record.system_details.release}}</span>
{% endif %}
```

so that "reconstruction" is mentioned for RAW datasets, and "analysis" for AOD datasets.

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed.
