### ISSUE TITLE
CMS: upload the updated CMS data policy

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2414]
The updated CMS data policy to be added, now available from
https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/ShowDocument?docid=6032

It would be good to have it before next conferences, if possible (e.g. an outreach session at LHCP next week).

Either new record, or a new versions to the existing 411, both are OK, as long as google search
"cms data policy" brings to the updated version.

Assigned @tiborsimko for the decision 😃

**Comment by tiborsimko** [comment]
@ArtemisLav Can you please create a new record with a new DOI and "deprecate" the old record so that it would point to the new one?  (or just add the new version file with a different DOI to the same record ID...)

Here's the file information:

```
path=root://eospublic.cern.ch//eos/opendata/cms/documentation/CMS-Data-Policy-1.2.pdf size=95934 checksum=7d6888b9
```

**Comment by ArtemisLav** [comment]
@tiborsimko I have amended the record and added a new DOI, but in both the options the old DOI would point to nothing. I guess that will be part of the versioning discussion. It would be good to figure that out soon.

**Comment by katilp** [comment]
Any news of this @tiborsimko ?
