### ISSUE TITLE
RFC default sort order

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2418]
Discussing with @artfisica the default ranking when people only browse the site, i.e. for empty query patters.

Currently, the order looks sort of "random" in this case. Perhaps "most recent" would make more sense in this case.

Investigate options.

**Comment by heitorPB** [comment]
For `glossary` and `documentation`, alphabetical order seems a good idea as it makes easier to find something specific. Maybe also for `software` and `environment`.

**Comment by heitorPB** [comment]
Alphabetical order is case sensitive. See the [glossary](http://opendata.cern.ch/search?page=1&size=20&type=Glossary&sort=title) for an example: `Run` is before `derived`.

**Comment by tiborsimko** [comment]
Now that we advertise only home page, this is essentially about best default order for `/search`, which could be latest first.

**Comment by tiborsimko** [comment]
After upgrading to the new Invenio search, the default order is now "latest first" (aka "most recent"), giving the following:

![most-recent](https://user-images.githubusercontent.com/517546/107484778-317b8b00-6b83-11eb-9614-4c9aff7f8b42.png)

Strictly speaking, records shown last are not "most recently created", but rather "most recently uploaded". 

Two possibilities: (i) keep the sort logic and amend the order of loading fixtures so that latest would be imported last;  (ii) change the sort logic so that the "most recent" would be based on record IDs.  (Since we usually use higher ones for new content.)
