### ISSUE TITLE
CMS: missing MC

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2421]
From @zenaiev: It would be useful to add 
`dataset=/GluGluToHToGG_M-125_7TeV-powheg-pythia6/Fall11-PU_S6_START44_V9B-v1/AODSIM
`
to the 2011 MC open data to complete the H->gg example

**Comment by katilp** [comment]
@zenaiev sorry for the delay, I'll have a look and let you know

**Comment by katilp** [comment]
@zenaiev Transfer request done, waiting for it to get approved.

**Comment by tiborsimko** [comment]
The dataset is now available on the EOSPUBLIC under:

- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarlo2011/Fall11

The bibliographic record is still to be created for the dataset to be listed on the portal.

**Comment by tiborsimko** [comment]
The file indexes are ready:

- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarlo2011/Fall11/GluGluToHToGG_M-125_7TeV-powheg-pythia6/AODSIM/PU_S6_START44_V9B-v1/file-indexes

@ArtemisLav Can you please create the bibliographic record?  It should go to `cms-simulated-datasets-Run2011A.json`.  The record ID could be 1681 which is still free. The DOI is to be invented and minted.

@heitorPB We can then use the new technique to get the generation information for this record.

**Comment by heitorPB** [comment]
Generated this json snippet using recID 1681:

http://hpascoal.web.cern.ch/hpascoal/tmp/rec1681-heitor.json

Missing DOI

**Comment by ArtemisLav** [comment]
Here is one (reserved): `10.7483/OPENDATA.CMS.6D1T.JT47`
Once the PR is merged I can mint it.

**Comment by tiborsimko** [comment]
Deployed on DEV: http://opendata-dev.cern.ch/record/1681
