### ISSUE TITLE
CMS: new VM for 2011-2012 with slc6 container

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2426]
A new version of VM for 2011-2012 is available for testing.
It has the CMS shell as slc6 shell as a singularity container (similar to VM 1.1.2 in http://opendata.cern.ch/record/250)

UPDATE, see below https://github.com/cernopendata/opendata.cern.ch/issues/2426#issuecomment-447997789

https://cernbox.cern.ch/index.php/s/omF4JNCPMDigQk8

It corresponds to the image

http://cernvm.cern.ch/releases/production/cernvm4-micro-2018.06-2.hdd

with the context from

https://github.com/cernvm/public-contexts/blob/master/cms-opendata-2011.context

Testing needed.

**Comment by katilp** [comment]
@jblomer Were there some updates needed to this VM (image and/or contextualization) for the eos mount issue?

**Comment by jblomer** [comment]
@katilp Yes, I'm still working on it.  The `df` issue is sorted out, eos still needs an update.

**Comment by katilp** [comment]
@jblomer Thanks! It seems many of the testers do not open the slc6 shell, would it be possible to have the OS visible in the prompt for both shells?

**Comment by katilp** [comment]
Update from @jblomer 

> a new version of the VM (CMS OpenData VM 1.5.0):
> 
>     https://cernbox.cern.ch/index.php/s/YJeRKF5hIXLpnIy
> 
> from the sources
> 
> 
> http://cernvm.cern.ch/releases/ucernvm-images.2018.10-2.cernvm.x86_64/ucernvm-v4testing.2018.10-2.cernvm.x86_64.hdd
> 
> and
> 
> https://github.com/cernvm/public-contexts/blob/master/cms-opendata-2011.context
> 
> This VM has the following changes/fixes:
> 
>   o) Update to and EL 7.6 based OS
> 
>   o) df in the CMS shell works
> 
>   o) The standard shell now has a prompt "[Outer Shell]".
> 
> For in-house use, EOS volume can be mounted:
> 
> sudo service eosd start
> kinit yourcernlogin@CERN.CH # <-- your CERN login
> eosfusebind -g

**Comment by katilp** [comment]
Testing:

- [x] https://github.com/cms-opendata-analyses/trigger_examples/tree/2011/TriggerInfo/TriggerInfoAnalyzer (/record/5004) on CMSSW_5_3_32 reading GT FT_53_LV5_AN1_RUNA 
- [ ] RAW rereco #2439
- [ ] Run2 jettuples #2447
- [ ] Upgrade ML #2459

**Comment by katilp** [comment]
When this is available update 
- [ ] https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
- [ ] http://opendata-dev.web.cern.ch/docs/cms-virtual-machine-2011 (as in 2010: i.e. equivalent to

> In the "CMS-OpenData-1.1.2" VM, open a terminal from the "CMS Shell" icon from the desktop (only if using the VM version "CMS-OpenData-1.0.0-rc7", open a terminal with the X terminal emulator from an icon bottom-left of the VM screen).

but the check the Shell name in 1.5.0

**Comment by katilp** [comment]
The new description for the record:

```
    "abstract": {
      "description": " <p>The virtual machine image is based on CernVM (cernvm.cern.ch), with Scientific Linux CERN 6 (slc6), which is the environment needed for the CMSSW release to be used with the 2011 and 2012 CMS open data. It gets the CMS software (CMSSW) from /cvmfs/cms.cern.ch and the jobs running on the CMS open data VM read the condition data from /cvmfs/cms-opendata-conddb.cern.ch. Access to the data is through XRootD.</p> <p>CMS-OpenData-1.5.0.ova is recommended. It has a 40G virtual hard disk and a 20G cvmfs cache, which is large enough for condition data for full event range for 2012 data (see <a href=\"/docs/cms-guide-for-condition-database\">the CMS guide to the condition database</a> for further details). It has an embedded slc6 shell, where all CMS software specific commands should be executed. Additionally, it has a slc7 shell, which can be used in the same session.</p> <p>The earlier versions CMS-Open-Data-1.2.0.ova and Open-Data-1.3.0.ova are slc6 only.  CMS-Open-Data-1.2.0.ova has a 20G virtual hard disk and a 10G cvmfs cache. CMS-Open-Data-1.3.0.ova has a 40G virtual hard disk and a 20G cvmfs cache. </p>  <p>For known issues and limitations see</p>", 

```

**Comment by katilp** [comment]
The final version is 


    http://cernvm.cern.ch/releases/CMS-OpenData-1.5.1.ova

The sources are

    http://cernvm.cern.ch/releases/production/cernvm4-micro-2018.10-1.hdd

and


https://github.com/cernvm/public-contexts/blob/master/cms-opendata-2011.context

**Comment by tiborsimko** [comment]
Note that we have a discrepancy, the files in record 252 are named `CMS-Open-Data-1.3.0.ova` (with dash), while the docs sometimes refer also to `CMS-OpenData-1.3.0.ova` (without dash).

**Comment by katilp** [comment]
Thanks for pointing it out, I'll fix that on the next occasion

**Comment by katilp** [comment]
The file name, when downloaded, shows actually as CMS-OpenData-N.N.N so we may want to keep it as such in instructions:
![vmview](https://user-images.githubusercontent.com/5859918/59017190-41d25300-8843-11e9-8acd-486c99b996ee.JPG)
