### ISSUE TITLE
Broken link with trailing slash: record 5103

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#2429]
On http://opendata.cern.ch/record/5103 there is a link to the CMS event display, but the link is broken:

- The link on the page is [`http://opendata.cern.ch/visualise/events/cms/`](http://opendata.cern.ch/visualise/events/cms/) -- note the trailing `/`.
- The "correct" link should be [`http://opendata.cern.ch/visualise/events/cms`](http://opendata.cern.ch/visualise/events/cms) -- without the `/`.

I feel like we've discussed this before, so if you can find the appropriate issue, can you please cross-link to it? :)

**Comment by ArtemisLav** [comment]
I checked and as far as I can tell this was the only record where this link was broken
