### ISSUE TITLE
Dataset and disclaimer modifications for ALICE open data

### ISSUE THREAD

**Issue by mgheata** [cernopendata/opendata.cern.ch#2437]
We realized that few fixes are needed for the ALICE dataset descriptions plus some modifications in the disclaimer page, as follows:

1. In the page: http://opendata.cern.ch/search?page=1&size=20&experiment=ALICE

correct all the energies specified on the page with:
-> “at the collision energy of 7 TeV” instead of “at 3.5 TeV” in the case of “Proton-Proton”;
-> “at the collision energy of 2.76 TeV per nucleon pair” instead of “at 3.5 TeV” in the case of “Pb-Pb”;

2. The filtering by collision energy in the same page (left side) should be updated accordingly, i.e. there should be 2 check-boxes, one with 2.76 TeV and one with 7 TeV.
This should be updated also in the page: http://opendata.cern.ch/search?page=1&size=20&type=Dataset
The "Filter by collision energy" should have check-boxes with the same values above

3. In the page: http://opendata.cern.ch/docs/about-alice
we need a small addition under "About ALICE data" in the line:

“These datasets are not **corrected for detector inefficiency nor** statistically representative…”
Note the addition between **.

Please reassign as needed

**Comment by mgheata** [comment]
I have made a pull request fixing points 1 and 3, but for point 2 I could not find the file responsible of filtering datasets by collision energy (3.5 TeV should become 2.76 TeV, affects only ALICE datasets selection)

**Comment by tiborsimko** [comment]
@mgheata Thanks! The search facet filtering is automatically taking values from the record fields, so if you have edited all the records and amended the 3.5 TeV collision information, the facet will "solve itself" automatically too.

```diff
     "collision_information": {
-      "energy": "3.5TeV",
+      "energy": "2.76TeV",
       "type": "PbPb"
     },
```

**Comment by tiborsimko** [comment]
... I started a build on DEV so that you can check the final result.  Should be finished within a couple of hours...

**Comment by tiborsimko** [comment]
... done:

http://opendata-dev.cern.ch/search

I'll now deploy on QA and PROD.
