### ISSUE TITLE
CMS: Add RAW samples for existing AOD datasets

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2439]
Add RAW samples of O(Mevent) corresponding to the existing CMS AODs

- [x] Select the samples (priority list Single/Double Electron/Muon Jets, 2012, 2011, (2010))
  - RunA 2011 run period 160404 to 173692:
    - [RAW for /SingleMu/Run2011A-12Oct2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FSingleMu%2FRun2011A-v1%2FRAW) - http://opendata.cern.ch/record/32 ok
    - [RAW for /SingleElectron/Run2011A-12Oct2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FSingleElectron%2FRun2011A-v1%2FRAW) - http://opendata.cern.ch/record/31 ok
    - [RAW for /DoubleElectron/Run2011A-12Oct2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleElectron%2FRun2011A-v1%2FRAW) - http://opendata.cern.ch/record/16 ok
    - [RAW for /DoubleMu/Run2011A-12Oct2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleMu%2FRun2011A-v1%2FRAW) - http://opendata.cern.ch/record/17 ok
    - [RAW for /Jet/Run2011A-12Oct2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FJet%2FRun2011A-v1%2FRAW) - http://opendata.cern.ch/record/21 ok
  - RunB 2012, run period 193833 to 196531:
    - [RAW for /MinimumBias/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FMinimumBias%2FRun2012B-v1%2FRAW) http://opendata.cern.ch/record/6013 ok
    - [RAW for /SingleMu/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FSingleMu%2FRun2012B-v1%2FRAW) - http://opendata.cern.ch/record/6021 ok
    - [RAW for /SingleElectron/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FSingleElectron%2FRun2012B-v1%2FRAW) -  http://opendata.cern.ch/record/6020 ok
    - [RAW for /DoubleMuParked/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleMuParked%2FRun2012B-v1%2FRAW) -  http://opendata.cern.ch/record/6004 ok
    - [RAW for /DoubleElectron/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDoubleElectron%2FRun2012B-v1%2FRAW) -  http://opendata.cern.ch/record/6003 ok
    - [RAW for /JetHT/Run2012B-22Jan2013-v1/AOD](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FJetHT%2FRun2012B-v1%2FRAW) -  http://opendata.cern.ch/record/6010 ok
  - RunB 2010, run period 146428 to 149294:
    - [RAW for /MinimumBias/Run2010B-Apr21ReReco-v1/AOD](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FMinimumBias%2FRun2010B-v1%2FRAW&instance=prod/global) - http://opendata.cern.ch/record/8 ok
    - [RAW for /Mu/Run2010B-Apr21ReReco-v1/AOD](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FMu%2FRun2010B-v1%2FRAW&instance=prod/global) http://opendata.cern.ch/record/14 ok
    - [RAW for /Electron/Run2010B-Apr21ReReco-v1/AOD](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FElectron%2FRun2010B-v1%2FRAW&instance=prod/global) http://opendata.cern.ch/record/4 ok
    - [RAW for /Jet/Run2010B-Apr21ReReco-v1/AOD](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FJet%2FRun2010B-v1%2FRAW&instance=prod/global) http://opendata.cern.ch/record/5 ok
- [x] Select the events range, check list of validated runs to make sure that validated events are included
  - 2010: runs between 146428 and 149294 in http://opendata.cern.ch/record/1000
  - 2011: runs between 160404 and 173692 in http://opendata.cern.ch/record/1001
  - 2012: runs between 193833 and 196531 in http://opendata.cern.ch/record/1002
- [x] Transfer the blocks to T3_CH_CERN_OpenData (upload area), then ask @tiborsimko to move the to the final location
   - all transferred, all moved, file indexes to be done
- [x] Check that RAW can be rerecoed to AOD and compare to the existing open data AOD
  - use http://opendata.cern.ch/record/463 for the processing step (for 2011 samples no changes needed, for 2012 samples, change the GT)
  - use http://opendata.cern.ch/record/464 (this runs also on 2010 data on slc5 VM, removing python/demoanalyzer_cfi.py, which is a leftover and can be removed in any case) or the object selector (WIP @caredg ) to compare
  - test 
    - on small scale on VM (one file) using the new VM ( see #2426), increase the memory if needed
    - running on batch
    - runnning on ReANA
- [x] Prepare the records
  - see the existing RAW record in http://opendata.cern.ch/record/35 and note comments below in https://github.com/cernopendata/opendata.cern.ch/issues/2439#issuecomment-469695565

**Comment by katilp** [comment]
NB: example CMSDAS query for number of events in a block
`file block=/DoubleElectron/Run2011A-v1/RAW#7b371490-b471-11e0-927a-003048caaace | sum(file.nevents)`

**Comment by diyaselis** [comment]
2010 Selected RAW files:
	•	/MinimumBias/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146428,146514] - Number of events: 2451242

	•	/Mu/Run2010B-Apr21ReReco-v1/RAW 
		Event Range:  [146589,146710] - Number of events: 2102829

	•	/Electron/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146712,146804] - Number of events: 2554874

	•	/Jet/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146807, 147043] - Number of events: 2415753

2011 Selected RAW files:
	•	/SingleMu/Run2011A-12Oct2013-v1/RAW 
		Event Range:  [163289,163370] - Number of events: 2079006

	•	/SingleElectron/Run2011A-12Oct2013-v1/RAW 
		Event Range: [161224,163286] - Number of events: 2064298

	•	/DoubleElectron/Run2011A-12Oct2013-v1/RAW
		Event Range:  [160431,161223] - Number of events: 2035725

	•	/DoubleMu/Run2011A-12Oct2013-v1/RAW
		Event Range:  [163371,163588] - Number of events: 2070977

	•	/Jet/Run2011A-12Oct2013-v1/RAW 
		Event Range:  [163589,165121] - Number of events: 2177197

2012 Selected RAW files:
	•	/MinimumBias/Run2012B-22Jan2013-v1/RAW 
		Event Range:  [193834, 194050] - Number of events: 2745751

	•	/SingleMu/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194051,194115] - Number of events: 2301668

	•	/SingleElectron/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194117, 194199] - Number of events: 2125485

	•	/DoubleMuParked/Run2012B-22Jan2013-v1/RAW 
		Event Range:  [194210,194429] - Number of events: 2047989

	•	/DoubleElectron/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194439,194691] - Number of events: 2060895

	•	/JetHT/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194699,195112] - Number of events: 2096284

**Comment by diyaselis** [comment]
2010 Selected RAW files:

	•	/MinimumBias/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146428,146514] - Number of events: 2451242

	•	/Mu/Run2010B-Apr21ReReco-v1/RAW 
		Event Range:  [146589,146710] - Number of events: 2102829

	•	/Electron/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146712,146804] - Number of events: 2554874

	•	/Jet/Run2010B-Apr21ReReco-v1/RAW 
		Event Range: [146807, 147043] - Number of events: 2415753

2011 Selected RAW files:

	•	/SingleMu/Run2011A-12Oct2013-v1/RAW 
		Event Range:  [163289,163370] - Number of events: 2079006

	•	/SingleElectron/Run2011A-12Oct2013-v1/RAW 
		Event Range: [161224,163286] - Number of events: 2064298

	•	/DoubleElectron/Run2011A-12Oct2013-v1/RAW
		Event Range:  [160431,161223] - Number of events: 2035725

	•	/DoubleMu/Run2011A-12Oct2013-v1/RAW
		Event Range:  [163371,163588] - Number of events: 2070977

	•	/Jet/Run2011A-12Oct2013-v1/RAW 
		Event Range:  [163589,165121] - Number of events: 2177197

2012 Selected RAW files:

	•	/MinimumBias/Run2012B-22Jan2013-v1/RAW 
		Event Range:  [193834, 194050] - Number of events: 2745751

	•	/SingleMu/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194051,194115] - Number of events: 2301668

	•	/SingleElectron/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194117, 194199] - Number of events: 2125485

	•	/DoubleMuParked/Run2012B-22Jan2013-v1/RAW 
		Event Range:  [194210,194429] - Number of events: 2047989

	•	/DoubleElectron/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194439,194691] - Number of events: 2060895

	•	/JetHT/Run2012B-22Jan2013-v1/RAW 
		Event Range: [194699,195112] - Number of events: 2096284

**Comment by katilp** [comment]
For running on batch:
- on 2011-2012 samples, the new VM (slc6 shell encapsulated in the VM) can be used: #2426 
- on 2010 samples, use the VM available on the portal (CMS-OpenData-1.1.2.ova).

**Comment by katilp** [comment]
The configuration files can be created with `cmsDriver.py` script (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriver) in the respective working areas:
- `CMSSW_5_3_32/src/WorkDir` on 2011-2012 VM (use  #2426) for 2011 and 2012 RAW with `cmsDriver.py reco -s RAW2DIGI,L1Reco,RECO --data --conditions FT_R_53_LV5::All --eventcontent AOD --no_exec --python reco_cmsdriver2011.py`
- `CMSSW_4_2_8/src/WorkDir` on 2010 VM (CMS-OpenData-1.1.2) for 2010 RAW with `cmsDriver.py reco -s RAW2DIGI,L1Reco,RECO --data --conditions FT_R_42_V10A::All --eventcontent AOD --no_exec --python reco_cmsdriver2010.py`

In the resulting config file, the global tag part needs to be changed for the VM, e.g for 2010 config:
# Other statements
#process.GlobalTag.globaltag = 'FT_R_42_V10A::All'
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT_R_42_V10A.db')
process.GlobalTag.globaltag = 'FT_R_42_V10A::All'

**Comment by katilp** [comment]
@caredg To which extent you plan to document cmsDriver in the context of MC generation? As it is a tool valid both for data and MC, maybe a independent short guide page would make sense, what do you think?
It could be based on https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriver

**Comment by caredg** [comment]
I think it should be documented.  We can incorporate it under the Tools section.  This is something that is not terribly hard to do and should be crystallized soon.  We can definitely based it on the twiki public pages.

**Comment by katilp** [comment]
@diyaselis Very good! Do you already have the plots comparing the new AOD and existing ones?

**Comment by tiborsimko** [comment]
Here is the full list of transferred RAW samples:

- 2010B: Electron, Jet, MinimumBias, Mu
- 2011A: DoubleElectron, DoubleMu, Jet, SingleElectron, SingleMu 
- 2012B: DoubleElectron, DoubleMuParked, JetHT, MinimumBias, SingleElectron, SingleMu

The file indexes and records are still to be created.

**Comment by diyaselis** [comment]
Process for 2011 RAW samples reconstruction test:

- Select input RAW sample from the [EOS HTTP Browser](https://eospublichttp01.cern.ch/eos/opendata/cms/Run2011A/). For example, your input can be **root://eospublic.cern.ch//eos/opendata/cms/Run2011A/DoubleElectron/RAW/v1/000/160/431/080D15C9-FF4D-E011-9484-0030487C7828.root**
- The reconstruction will be executed in the new VM (use #2426) for which a `CMSSW_5_3_32/src/WorkDir` area will be created.
- To create the configuration files (after `cmsenv`) run: 
`cmsDriver.py reco -s RAW2DIGI,L1Reco,RECO,USER:EventFilter/HcalRawToDigi/hcallaserhbhehffilter2012_cff.hcallLaser2012Filter --data --conditions FT_R_53_LV5::All --eventcontent AOD --customise Configuration/DataProcessing/RecoTLR.customisePrompt --no_exec --python reco_cmsdriver2011.py`
- In the default configuration file some parameters must be corrected, such as:
   1) Change maxEvents parameter (default is 1) to -1, to process all events: 
       ```process.maxEvents = cms.untracked.PSet(input = cms.untracked.int32(-1))```
   2) Establish input from the eospublic datasets. For example:
       ```ruby
       # Input source
       process.source = cms.Source("PoolSource",
           secondaryFileNames = cms.untracked.vstring(),
           fileNames = cms.untracked.vstring('root://eospublic.cern.ch//eos/opendata/cms/Run2011A/DoubleElectron/RAW/v1/000/160/431/080D15C9-FF4D-E011-9484-0030487C7828.root')
       )
       ```
   3) Correct GlobalTag according to the [Guide for Condition Data](http://opendata.cern.ch/docs/cms-guide-for-condition-database).
       ```ruby
       #Additional statements
       process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA.db')
       process.GlobalTag.globaltag = 'FT_53_LV5_AN1::All'
       ```
- Proceed to do `cmsRun` to your configuration file (Run time could be up to 12 hours)
- As an output of the reconstruction, we would get a root file such as "**reco_RAW2DIGI_L1Reco_RECO_USER.root**". This file can be transfered to EOS, since it can be a large file, following these [instructions](https://cern.service-now.com/service-portal/article.do?n=KB0001998). 
- As an analyzer the [validation code to plot basic physics objects from AOD](http://opendata.cern.ch/record/464) from the CERN Open Data Portal works successfully apart from minor changes such as:
   1) Change input name as `'file:reco_RAW2DIGI_L1Reco_RECO_USER.root'` or whichever your local AOD root file is called from the output of the reconstruction.
   2) Modify luminosity range accordingly (get lumi sections and runs in your input file using `edmLumisInFile.py`). For example: 
        `lumisToProcess = cms.untracked.VLuminosityBlockRange('163589:1-165121:max')`
       Selected run ranges for each of the RAW samples were stated above.
- Run analyzer using `cmsRun`, and view histograms by writing in the command line `root -l` followed by the name of your analyzer's output.

**Comment by tiborsimko** [comment]
The file indexes have been added for all RAW samples, for example:

- https://eospublichttp.cern.ch/eos/opendata/cms/Run2011A/SingleElectron/RAW/v1/file-indexes

@katilp Is it OK that the dataset name above is named `/SingleElectron/Run2011A-12Oct2013-v1/RAW` but the files are stored under `/eos/opendata/cms/Run2011A/SingleMu/RAW/v1/` i.e. `12Oct2013` is apparently missing from the path?

**Comment by tiborsimko** [comment]
As discussed live, `/SingleElectron/Run2011A-v1/RAW` etc are the good names, no date or rereco in names there.

**Comment by katilp** [comment]
Suggested changes for the RAW data records:

The current RAW record http://opendata.cern.ch/record/35 points to two separate SW records under "How can you use these data?" (i.e. `description` of `usage` in python) to describe
1. how this RAW can be rerecoed (a single config file sw record)
2. how to compare the rerecoed AOD to the existing AOD (simple plotter)

I suggest that the new RAW records **contain** the config file to be used for rereco, instead of pointing to a separate SW record containing only that config file. 

Motivation for this change:
- RAW records are particular: they are not usable as they are but have to be rerecoed and it is done with a well-defined (and tested) config file
  - NB the difference between AOD records where the config files to **produce** the file are linked to record the provenance information, but no config file **to be used with this data** will be linked or attached because the contents of the config depends of the intended analysis
- we can eventually use this approach also for those intermediate GEN-SIM datasets which will be released together with the ML samples

The config files to rereco the RAW samples are available in
https://github.com/cms-legacydata-validation/RAWToAODValidation (will be move to cms-opendata-validation for the release).

The usage description field for the RAW data records could then be something like:

`<p> These data are in RAW format and not directly usable in analysis. The reconstructed data reprocessed from these RAW data are included in the data of <a href=\"/record/FIXME=corresponding AOD\">this record</a>. \n      The reconstruction step can be repeated with the configuration file attached to this record and the resulting AOD has been confirmed to be identical with the original one with comparison code available in <a href=\"/record/464\">Validation code to plot basic physics objects from AOD</a></p>
`
If PhysicsObjectExtractor code makes it in time for the next release, and if is will be used to test, we can then have the link to it instead to reocrd 464 in the description above.

@tiborsimko @mantasavas any thoughts?

**Comment by tiborsimko** [comment]
I think it makes a very good sense to store rereco together with the raw sample, especially now that we are going to have cmsdriver and genfragments stored with the datasets directly, as well.  So, OT1H, this goes very well with the trend to store supplementary information directly "inside" the datasets. However, OTOH, we also have "Configuration HLT", "Configuration SIM" etc stored in separate collections "outside" the datasets, so it may start to become a bit confusing to users as to where to find what... There is a danger that some configuration files will be seen as first-class objects and some as second-class objects regarding information discovery. That's one thing I could see as a possible downsize. It does not seem to be a big concern, but we can try to ponder the various pros/cons live...

**Comment by tiborsimko** [comment]
@ArtemisLav Can you please prepare free DOIs?   Here is the list:

-  2010B: Electron, Jet, MinimumBias, Mu
- 2011A: DoubleElectron, DoubleMu, Jet, SingleElectron, SingleMu
-  2012B: DoubleElectron, DoubleMuParked, JetHT, MinimumBias, SingleElectron, SingleMu

**Comment by tiborsimko** [comment]
As discussed with @katilp we can attach the configuration files to raw sample as we do for software records, i.e. not inside JSON, not as separate records, but attached files only.  The future command line client (see #2592) will help in automatising downloads.

**Comment by katilp** [comment]
2012 RAW-to-AOD needs still to be checked. With the current reco config, not all objects appear.

**Comment by katilp** [comment]
Problem above solved: if no good lumi selection applied at re-reco step, it may well happen that first n events (in a small-scale test) come from a non-validated lumi section (in this case with tracker off)

**Comment by katilp** [comment]
Config files to be added to the dataset provenance are linked in
https://github.com/cernopendata/opendata.cern.ch/pull/2596#issuecomment-499025694

**Comment by katilp** [comment]
Check how the RAWtoAOD config files are displayed/linked in the RAW records. Now:

![rawrec](https://user-images.githubusercontent.com/5859918/60167766-056f9280-9804-11e9-9bc9-38ab526d3b95.JPG)

but no link
