### ISSUE TITLE
CMS: GTs for the data science samples

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2443]
GTs for data science samples (#2440) are uploaded under /cvmfs/cms-opendata-conddb.cern.ch

- 80X_mcRun2_asymptotic_2016_TrancheIV_v8 (confirmed)
- 102X_upgrade2018_design_v9 (confirmed)

- [x] upload the sqlite files corresponding to GTs under /cvmfs/cms-opendata-conddb.cern.ch
- [x] test the reading
    - [x] 80X_mcRun2_asymptotic_2016_TrancheIV_v8
    - [x] 102X_upgrade2018_design_v9
- [x] create the corresponding records (similar to http://opendata.cern.ch/record/1804) with names
  - Condition data for 2016 CMS simulated datasets 
  - Condition data for Phase2 CMS simulated datasets 

  (To be considered: the GT for 2016 may or may not stay the same in the future, depending on 2016 data rereco.)

- [x] update the docs in http://opendata.cern.ch/docs/cms-guide-for-condition-database correspondingly

**Comment by katilp** [comment]
@tiborsimko As discussed earlier, we can maybe "link" to /cvmfs for the condition data in the COPD records.
Now out of 5 records in 
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&subtype=Condition&type=Environment

- 2011 ones have the full zip of the condition data
- 2012 ones have just a db file
- 2010 one has nothing

They could just maybe point to the /cvmfs/cms-opendata-conddb.cern.ch area.
The disadvantage is that (to my knowledge) it cannot be a real link but just a text explanation how to find them when cvmfs volume is mounted (i.e on OpenDataVM or on eventual containers)

**Comment by tiborsimko** [comment]
I see it similarly WRT hosting condition data. Do we have several use cases where people would like to access DB outside of the CMSSW environment? If yes, then it makes sense to publish them completely separately (and to fix the past records where it is missing). If not, we can indeed explain in words how people could download DB files from within CVMFS. For simplicity's sake, I'd go for the latter, unless we already know of some strong use cases for the former?

**Comment by katilp** [comment]
Explaining in words is fine, I do not see any use of these data outside the  CMSSW context.
