### ISSUE TITLE
CMS: add MC pile-up in GEN-SIM for 2012

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2446]
- [x] Confirm that the dataset needed for adding pile-up on the top of any newly produced MC for 2012  is /MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FMinBias_TuneZ2star_8TeV-pythia6%2FSummer12-START50_V13-v3%2FGEN-SIM
  - check from 2012 MC configs (edmProvDump gives all parameters for pile-up Mixing but not the input file): 
    - yes in e.g. http://opendata.cern.ch/record/11087 from http://opendata.cern.ch/record/7738 `--pileup_input dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM`
    - but not visible in http://opendata.cern.ch/record/11240 from http://opendata.cern.ch/record/8000
- [x] Transfer
  -  [transfer request](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1538410010%3Bnode%3D2241%3Brequest%3D1502778)
- [x] Move it (cfr #2331 for 2011 MinBias sample)
- [x] Prepare record (NB 2011 sample #2331 is not yet visible on the portal either )

**Comment by katilp** [comment]
@heitorPB Would you be able to check if you can confirm that the same input file for pile-up has been used for all 2012 MC. Normally visible in the cmsDriver command parameter  `--pileup_input`
Can you search that in McM?

**Comment by heitorPB** [comment]
```
$ sed -r "s|\/.*\/(.*)\/.*|\1|gm" CMS-2012-mc-datasets.txt | sort | uniq
Summer12_DR53X-castor_PU_S10_START53_V19-v1
Summer12_DR53X-Ext30_PU_S10_START53_V19-v1
Summer12_DR53X-ExtFlat10_PU_RD1_START53_V7N-v1
Summer12_DR53X-ExtFlat20_PU_RD1_START53_V7N-v1
Summer12_DR53X-ExtFlat30_PU_RD1_START53_V7N-v1
Summer12_DR53X-ExtFlat30_PU_RD1_START53_V7N-v2
Summer12_DR53X-NewG4Phys_PU_RD1_START53_V7N-v1
Summer12_DR53X-NoPileUp_START53_V19-v1
Summer12_DR53X-NoPileUp_START53_V7N-v1
Summer12_DR53X-No_PU_RD1_START53_V7N-v1
Summer12_DR53X-PU_RD1_START53_V7N_ext1-v1
Summer12_DR53X-PU_RD1_START53_V7N-v1
Summer12_DR53X-PU_RD1_START53_V7N-v2
Summer12_DR53X-PU_RD1_START53_V7N-v3
Summer12_DR53X-PU_RD1_START53_V7N-v4
Summer12_DR53X-PU_RD1_START53_V7N-v5
Summer12_DR53X-PU_RD2_START53_V19F-v1
Summer12_DR53X-PU_RD2_START53_V19F-v2
Summer12_DR53X-PU_RD2_START53_V19F-v3
Summer12_DR53X-PU_S10_START53_V19E-v1
Summer12_DR53X-PU_S10_START53_V19-v1
Summer12_DR53X-PU_S10_START53_V19-v2
Summer12_DR53X-PU_S10_START53_V19-v3
Summer12_DR53X-PU_S10_START53_V19-v6
```

PU profiles: `PU_S10`, `PU_RD1`, `PU_RD2`, `NoPileUp` and `NO_PU_RD1`.

- /GluGluToAToZhToLLTauTau_mA-280_mh-125_8TeV-pythia6-tauola/Summer12_DR53X-PU_S10_START53_V19-v6/AODSIM
   `--pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM"`
- /JPsiToMuMu_JPsiPt20_2MuPtEtaFilter_tuneD6T_8TeV-pythia6-evtgen/Summer12_DR53X-PU_RD2_START53_V19F-v1/AODSIM
   `--pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM"`
-   /VBFHiggs0PToGG_M-125p6_8TeV-JHUGenV4-pythia6-tauola/Summer12_DR53X-PU_RD1_START53_V7N-v3/AODSIM
   `--pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM"`
- /DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-No_PU_RD1_START53_V7N-v1/AODSIM
   `--pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM"`
- /DYToMuMu_M-15To50_Tune4C_8TeV-pythia8/Summer12_DR53X-NoPileUp_START53_V19-v1/AODSIM
   `--pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2012_Summer_50ns_PoissonOOTPU`

Only looked 5 datasets, but It appears they all use the same pile-up input file.

**Comment by katilp** [comment]
Closing as now available on dev: http://opendata-dev.web.cern.ch/record/37

**Comment by katilp** [comment]
Reopen for a FIXME in the record.
NB however that the production config cannot be found in CMSDAS (it only gives configs for further production steps), so either find the config from McM or use the generator fragment from the provenance dump.

**Comment by katilp** [comment]
To do:
- [ ] add the production script to the record https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/QCD-Summer12-00002
- [ ] prepare a separate record for the sim config file https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/af4431aa75037618429e3164db9f3415/configFile
- [ ] see if gen. fragment https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/af4431aa75037618429e3164db9f3415/configFile could be directly  displayed in a similar way as production script

**Comment by katilp** [comment]
The config files to be linked to the SIM steps for the 2011 (/record/36) and 2012 (/record/37) pileup records are now in
```
/eos/opendata/cms/upload/kati/pileup_configs/2011/e75da0ef8a4c51a102040e9de55704a4.configFile.py
/eos/opendata/cms/upload/kati/pileup_configs/2012/af4431aa75037618429e3164db9f3415.configFile.py

```
Extracted from McM.

**Comment by tiborsimko** [comment]
Configuration files moved to the usual destination (`/eos/opendata/cms/configuration-files/MonteCarloYYYY/`) and the linking for the two pileup records work.
