### ISSUE TITLE
CMS: Run2010A collision data to be released

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2451]
The rest of 2010 data, RunA datasets, now to be released are
`dataset=/*/Run2010A-Apr21ReReco-v*/AOD`
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2010A-Apr21ReReco-v*%2FAOD

12  datasets - NB in RunB ZeroBias no events pass the validated events filter, but for RunA it is OK

```
/ZeroBias/Run2010A-Apr21ReReco-v1/AOD
/MuOnia/Run2010A-Apr21ReReco-v1/AOD
/MuMonitor/Run2010A-Apr21ReReco-v1/AOD
/Mu/Run2010A-Apr21ReReco-v1/AOD
/MinimumBias/Run2010A-Apr21ReReco-v1/AOD
/JetMETTauMonitor/Run2010A-Apr21ReReco-v1/AOD
/JetMETTau/Run2010A-Apr21ReReco-v1/AOD
/JetMET/Run2010A-Apr21ReReco-v1/AOD
/EGMonitor/Run2010A-Apr21ReReco-v1/AOD
/EG/Run2010A-Apr21ReReco-v1/AOD
/Commissioning/Run2010A-Apr21ReReco-v1/AOD
/BTau/Run2010A-Apr21ReReco-v1/AOD
```

To do

- [x] transfer the datasets
   - transfer request done https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1542124296%3Bnode%3D2241%3Brequest%3D1557490 Transfer completed!
- [x] prepare the short description of the contents (as in Run2010B)
   - E.g.

>  Events stored in this primary dataset were selected because of presence of at least one high-energy jet in the event.

- [x] extract the metadata and provenance from CMSDAS (see #2450)

**Comment by katilp** [comment]
@tiborsimko With the help of transfer teams, the last pending datasets have now been completed and the datasets above can be moved to `/eospublic/cms`

**Comment by katilp** [comment]
To do:
- move files from upload
- create file listing indexes

**Comment by tiborsimko** [comment]
Number of files and size on EOS:

```
/BTau/Run2010A-Apr21ReReco-v1/AOD 2067   2193478806310
/Commissioning/Run2010A-Apr21ReReco-v1/AOD 4716   5252574106904
/EG/Run2010A-Apr21ReReco-v1/AOD 3503   4486583998147
/EGMonitor/Run2010A-Apr21ReReco-v1/AOD 1907   3014222017833
/JetMET/Run2010A-Apr21ReReco-v1/AOD 2048   2299653921999
/JetMETTau/Run2010A-Apr21ReReco-v1/AOD 529   1023722573699
/JetMETTauMonitor/Run2010A-Apr21ReReco-v1/AOD 953   1617738934008
/MinimumBias/Run2010A-Apr21ReReco-v1/AOD 3799   4184825186174 
/Mu/Run2010A-Apr21ReReco-v1/AOD 1588   2429704559456
/MuMonitor/Run2010A-Apr21ReReco-v1/AOD 1409   1898409317210
/MuOnia/Run2010A-Apr21ReReco-v1/AOD 2586   2603503059480
/ZeroBias/Run2010A-Apr21ReReco-v1/AOD 755   979720468256
```
