### ISSUE TITLE
CMS: add GT for 2012 run-dependent MC 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2456]
START53_V7N, GT for run-dependent MC needs to be uploaded under /cvmfs/cms-opendata-conddb.cern.ch

- [x] upload the sqlite files corresponding to GTs under /cvmfs/cms-opendata-conddb.cern.ch
      Reminder for copying the files:
> You'd login to cvmfs-cms-opendata-conddb.cern.ch and then do
> 
>     sudo -i -u cvcmso
>     cvmfs_server transaction cms-opendata-conddb.cern.ch
> 
>     Now /cvmfs/cms-opendata-conddb.cern.ch is writable and you can use the
>     shell to copy all the files you need. Once finished, you'd do
> 
>     cvmfs_server publish cms-opendata-conddb.cern.ch
> 
>     And ~1h later the content appears at the clients.

- [x] test the reading #2444 
- [ ] create the corresponding records (similar to http://opendata.cern.ch/record/1804) with name
  - Condition data for 2012 run-dependent MC production
  - Description in abstract:
`"description": "<p>Condition database includes non-event-related information (Alignment, Calibration, Temperature, etc.) and parameters for simulation/reconstruction/analysis software.</p>\n      <p> These files are needed when running a CMSSW job on the Open Data VM. They are automatically read from the /cvmfs/cms-opendata-conddb.cern.ch runtime, you do not need to download these files from here separately.</p>\n      <p>START53_V7N was used to generate the simulated data used in the Higgs discovery analysis with dose-dependent detector characteristics, run-dependent pile-up and beam spot conditions.</p>\n  These condition data are only needed for production of samples and not for analysis of the already available simulated data. <p>See further information in <a href=\"/docs/cms-guide-for-condition-database\">the guide to CMS condition database</a>.</p>\n    <p>For 2012 CMS collision data see:</p>", `
- [x] update the docs in http://opendata.cern.ch/docs/cms-guide-for-condition-database correspondingly

**Comment by emanueleusai** [comment]
I tried the START53_V7N GT from the opendata repo. I this a full copy of the original GT? It seems like I'm not able to produce files with it. The same config using the "internal" version of START53_V7N works perfectly fine. I did the usual symlink of the folder and db. This is the error I get. Let me know if you need more details.

[eusai@lxplus044 src]$ cmsRun step1_V7N_run_dependent_PU_profile.py
 
MixingModule will be configured from db; this is mix.readDB :  cms.bool(True)
setting runNumber to:  200519
28-Nov-2018 17:54:27 CET  Initiating request to open file file:../../step0_qcd8_V27.root
28-Nov-2018 17:54:27 CET  Successfully opened file file:../../step0_qcd8_V27.root
%MSG-e BMixingModule:  MixingModule:mix@ctor 28-Nov-2018 17:54:27 CET pre-events
Will read from DB: reset to a dummy PileUp object.
%MSG




%MSG-w SiStripQuality:  EventSetupRecordDataGetter:hltGetConditions@beginRun  28-Nov-2018 17:56:04 CET Run: 200519
The cabling should always include the active feds in runInfo and possibly have some morethere are instead 59 feds only active in runInfo
%MSG
Begin processing the 1st record. Run 200519, Event 1, LumiSection 1 at 28-Nov-2018 17:57:07.436 CET
28-Nov-2018 17:57:07 CET  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2012/Summer12/MinBias_TuneZ2star_8TeV-pythia6/GEN-SIM/START50_V13-v3/0002/FEF2F4CC-0E6A-E111-96F6-0030487F1C57.root
28-Nov-2018 17:57:08 CET  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2012/Summer12/MinBias_TuneZ2star_8TeV-pythia6/GEN-SIM/START50_V13-v3/0002/FEF2F4CC-0E6A-E111-96F6-0030487F1C57.root
Begin processing the 2nd record. Run 200519, Event 2, LumiSection 1 at 28-Nov-2018 17:57:32.082 CET
Begin processing the 3rd record. Run 200519, Event 3, LumiSection 1 at 28-Nov-2018 17:57:42.850 CET
Begin processing the 4th record. Run 200519, Event 4, LumiSection 1 at 28-Nov-2018 17:57:49.326 CET
Begin processing the 5th record. Run 200519, Event 5, LumiSection 1 at 28-Nov-2018 17:57:56.047 CET
Begin processing the 6th record. Run 200519, Event 6, LumiSection 1 at 28-Nov-2018 17:58:03.230 CET
Begin processing the 7th record. Run 200519, Event 7, LumiSection 1 at 28-Nov-2018 17:58:09.406 CET
Begin processing the 8th record. Run 200519, Event 8, LumiSection 1 at 28-Nov-2018 17:58:15.510 CET
Begin processing the 9th record. Run 200519, Event 9, LumiSection 1 at 28-Nov-2018 17:58:27.262 CET
Begin processing the 10th record. Run 200519, Event 10, LumiSection 1 at 28-Nov-2018 17:58:35.500 CET
28-Nov-2018 17:58:42 CET  Closed file file:../../step0_qcd8_V27.root
28-Nov-2018 17:58:43 CET  Closed file root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2012/Summer12/MinBias_TuneZ2star_8TeV-pythia6/GEN-SIM/START50_V13-v3/0002/FEF2F4CC-0E6A-E111-96F6-0030487F1C57.root
TimeReport> Time report complete in 243.922 seconds
 Time Summary: 
 - Min event:   6.04399
 - Max event:   24.513
 - Avg event:   24.3922
 - Total job:   243.922
 CPU Summary: 
 - Min event:   4.90125
 - Max event:   14.4928
 - Avg event:   7.35908
 - Total job:   109.178
 - Total event: 73.5908


=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 SiStripQuality       -w EventSetupRecord                       1        1
    2 BMixingModule        -e MixingModule:mix                       1        1
    3 TimeReport           -e AfterModEndJob                         1        1
    4 fileAction           -s MixingModule:mix                       2        2
    5 fileAction           -s MixingModule:mix                       1        1
    6 fileAction           -s file_close                             1        1
    7 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 SiStripQuality       Run: 200519                       
    2 BMixingModule        pre-events                        
    3 TimeReport           PostEndRun                        
    4 fileAction           200519/1         200519/1         
    5 fileAction           PostEndRun                        
    6 fileAction           PostEndRun                        
    7 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning                 1                   1
Error                   2                   2
System                  6                   6
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ 
[eusai@lxplus044 src]$ cmsRun step1_V7N_run_dependent_PU_profile.py
 
MixingModule will be configured from db; this is mix.readDB :  cms.bool(True)
setting runNumber to:  194533
28-Nov-2018 17:59:46 CET  Initiating request to open file file:../../step0_qcd8_V27.root
28-Nov-2018 17:59:47 CET  Successfully opened file file:../../step0_qcd8_V27.root
%MSG-e BMixingModule:  MixingModule:mix@ctor 28-Nov-2018 17:59:47 CET pre-events
Will read from DB: reset to a dummy PileUp object.
%MSG
----- Begin Fatal Exception 28-Nov-2018 18:00:10 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing run: 194533
   [1] Running path 'HLTriggerFirstPath'
   [2] Calling beginRun for module EventSetupRecordDataGetter/'hltGetConditions'
   [3] Using EventSetup component PixelCPEGenericESProducer/'hltESPPixelCPEGeneric' to make data PixelClusterParameterEstimator/'hltESPPixelCPEGeneric' in record TkPixelCPERecord
   [4] Using EventSetup component TrackerDigiGeometryESModule/'' to make data TrackerGeometry/'' in record TrackerDigiGeometryRecord
   [5] Using EventSetup component TrackerGeometricDetESModule/'' to make data GeometricDet/'' in record IdealGeometryRecord
   [6] Using EventSetup component PoolDBESSource/'GlobalTag' to make data PGeometricDet/'' in record IdealGeometryRecord
Exception Message:
Fatal Root Error: @SUB=TBufferFile::ReadVersion
Could not find the StreamerInfo with a checksum of 0x1b67bac5 for the class "PGeometricDet::Item" (buffer with no parent)
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
28-Nov-2018 18:00:10 CET  Closed file file:../../step0_qcd8_V27.root
TimeReport> Time report complete in 10.3494 seconds
 Time Summary: 
 - Min event:   0
 - Max event:   0
 - Avg event:   inf
 - Total job:   10.3494
 CPU Summary: 
 - Min event:   0
 - Max event:   0
 - Avg event:   -nan
 - Total job:   8.42172
 - Total event: 0


=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 BMixingModule        -e MixingModule:mix                       1        1
    2 TimeReport           -e AfterFile                              1        1
    3 Additional Exception -s PostBeginRun                           1        1
    4 Fatal Exception      -s PostPathBeginRun                       1        1
    5 fileAction           -s file_close                             1        1
    6 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 BMixingModule        pre-events                        
    2 TimeReport           PostBeginRun                      
    3 Additional Exceptions PostBeginRun                      
    4 Fatal Exception      Run: 194533                       
    5 fileAction           PostBeginRun                      
    6 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Error                   2                   2
System                  5                   5

**Comment by ggovi** [comment]
@emanueleusai 
what release are you using?

**Comment by emanueleusai** [comment]
@ggovi 
CMSSW_5_3_32

**Comment by ggovi** [comment]
@emanueleusai 
I have re-exported the GT START53_V7N using 5_3_32 ( previously it was done with 4_2_8 ) . The files have been replaced in CVMFS. Hope this fixes.  Please let me know.

**Comment by emanueleusai** [comment]
@ggovi 
Works perfectly now.
GT is tested and working in open data.
