### ISSUE TITLE
CMS: Add instructions to find how HLT trigger paths are defined

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2460]
Lacking more comprehensive information, add instructions (as a separate guide, add in the trouble shooting page, else?) on how to find the HLT trigger path definitions.

A recent tentative in opendata-support (as an answer to a question about triggers for 
http://opendata.cern.ch/record/6017 (/MuOniaParked/Run2012B-22Jan2013-v1/AOD):

> For each trigger path, you can find basic information of their use range under respective records, i.e.
> for one of the trigger paths for this sample:
> 
> http://opendata.cern.ch/record/6296
> 
> which is the first record if you follow the link HLT_Dimuon10_Jpsi
> in HLT trigger path of the listing (I take this as an example)
> 
> This shows in which runs this particular trigger path has been used.
> 
> Furthermore, you can find the software definition of the trigger paths in the data-taking configuration file which is linked to the trigger path records above. You can have a look in
> a configuration file, for example in http://opendata.cern.ch/record/6123 and look for process.HLT_Dimuon10_Jpsi. 
> You'll find the "ingredients" of the trigger in question, and  you can further dig in to the file to find where the different constituents of the trigger have been defined...
> When you come down to the class instantiation such as (this is just one of the components that went to the definition of the trigger process, I take this as an example):
> 
> process.hltDimuon10JpsiL3Filtered = cms.EDFilter( "HLTMuonDimuonL3Filter",
> 
> etc, you will see the parameters used (in this case note for example MaxInvMass = cms.vdouble(3.35) and MinInvMass - cms.vdouble(2.8) to restrict the trigger around J/Psi mass), and you can then find the class e.g. HLTDMuonDiMuonL3Filter in this case in the open source CMSSW code in https://github.com/cms-sw/cmssw/tree/CMSSW_5_3_X/  and see how the algorithm is defined in
> https://github.com/cms-sw/cmssw/blob/CMSSW_5_3_X/HLTrigger/Muon/interface/HLTMuonDimuonL3Filter.h
> 
> Note also that we have a guide for using the trigger information in http://opendata.cern.ch/docs/cms-guide-trigger-system but it does not cover the definition of different triggers, but the instructions  on how to get access to the trigger decisions. 
>

**Comment by katilp** [comment]
@caredg Would it make sense to add this in http://opendata.cern.ch/docs/cms-guide-trigger-system or have it separately somewhere?

**Comment by caredg** [comment]
I think it would.  But after it is added, a link pointing to it from, say http://opendata.cern.ch/record/1701, would also be beneficial, I think.

**Comment by katilp** [comment]
Fix FIXME in the HLT listing recid to 1699
