### ISSUE TITLE
RFC run_period string or list

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2463]
**Problem**

Currrently `run_period` is a string:

```
"run_period": "Run2011K",
```

However this also leads to:

```
"run_period": "Run2012B-Run2012C",
"run_period": "2012A-2012D"
```

This may be getting even longer with A, B, C, D ... and may get into troubles regarding searching and faceting, see for example also:

![2018-12-06-110337_4480x1440_scrot](https://user-images.githubusercontent.com/517546/49577056-e502e800-f946-11e8-8e62-ff1cef7a9b1a.png)

**Proposal**

Shall we make `run_period` to be a list of strings?

CC @ArtemisLav @katilp

**Comment by heitorPB** [comment]
This is related to #1944

**Comment by tiborsimko** [comment]
BTW let's also standardise values, because we have "Run...":

```
 "run_period": "Run2012B",
```

but also naked "...":

```
 "run_period": "2012A-2012D",
```

**Comment by heitorPB** [comment]
I think I need a clarification about what are the fields:
- `date_created`
- `date_published`
- `date_reprocessed`
- `run_period`

**Comment by ArtemisLav** [comment]
We can also use this opportunity to fix the confusion with `date_created` having the meaning of `creation year` in some places and `data-taking year` in others. It would be best if it meant the former everywhere.

**Comment by tiborsimko** [comment]
@heitorPB See https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/jsonschemas/records/record-v1.0.0.json#L156 for the documentation about various fields.  If it is unclear, we should complete it there..

@ArtemisLav Here are some comments regarding `date_created` cleanup:

- A quick solution to remove "2010-2012" values in the "year" facet would be to keep `date_created` field in the current meaning and simply change it to a list, as we did for `run_period`.   This would mean that a dataset could have more than one creation date year, as it were.  (More on this below.) 

- A proper solution, as you propose, would be to keep `date_created` a string with the strict meaning of "creation date", and introducing new `date_datataking` field (or somesuch) with the strict meaning  of "data-taking year".  However, in this case, someone should go through all records and fix the years manually, plus we could have troubles what to do regarding resources that span over several years.  (More on this below.)

- In any case, I am not sure whether we really need a new field?  It seems perfectly plausible that the creation date for some resource may be a time interval, for example data were being recorded from September 2012  to January 2013.  What is the proper value for "creation date" then?  One could argue that it is both 2012 and 2013. It would not be strictly correct to say that the creation date is 2013 only, or 2012 only.  Do you know how other data repositories in other fields handle these kinds of situations? E.g aggregated astronomical data or seismic data taken over some larger periods of time?

**Comment by tiborsimko** [comment]
Since `run_period` change is approved and implemented, I am closing this RFC issue. @ArtemisLav Please create a new RFC for `date_created` if you would like to change the field in one or the other of discussed directions.
