### ISSUE TITLE
RFC on-demand distribution availability field

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2466]
We should find a way how to mark records where data will be only available on demand.

We could use the current `distribution` field:

```json
   "distribution": {
      "formats": [
        "aodsim", 
        "root"
      ], 
      "number_events": 296304, 
      "number_files": 35, 
      "size": 97943447759
    }, 
```

We could for example introduce ne `distribution.availability` subfields:

```json
       "availability": "onrequest",
       "note": "Please note that this dataset....",
```

@ArtemisLav Any official DCAT/DC/etc suggestions how to handle this?

**Comment by heitorPB** [comment]
What about a field `availability_note` under `distribution` with the information about whom to contact in case `file not available`

**Comment by ArtemisLav** [comment]
> We should find a way how to mark records where data will be only available on demand.
> 
> We could use the current `distribution` field:
> 
> ```json
>    "distribution": {
>       "formats": [
>         "aodsim", 
>         "root"
>       ], 
>       "number_events": 296304, 
>       "number_files": 35, 
>       "size": 97943447759
>     }, 
> ```
> 
> We could for example introduce ne `distribution.availability` subfields:
> 
> ```json
>        "availability": "onrequest",
>        "note": "Please note that this dataset....",
> ```
> 
> @ArtemisLav Any official DCAT/DC/etc suggestions how to handle this?

This looks fine to me 👍

**Comment by heitorPB** [comment]
And in the case the files are available: `"availability": "available"`?

**Comment by ArtemisLav** [comment]
If we can only have this populated for these on-demand records, then I would keep it as it is in Tibor's example: `"availability": "onrequest"` or `ondemand`. If we add this to every record, then perhaps we could go for `true` and `false` (where `false` means "upon request" because I don't think there would be any other use case for a "normal" `false`, meaning records whose files we wouldn't show/provide even when requested).

**Comment by tiborsimko** [comment]
Discussion with @ArtemisLav:

- `availability` field with string values such as `online`, `ondemand`, with possible future values like `tape`, `disk`, etc if needed.
