### ISSUE TITLE
RFC data model topic

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2468]
Currently we use for the MC categorisation:

```json
    "topic": {
      "category": "BSM Higgs", 
      "source": "CMS Collaboration"
    }, 
```

We shall need to allow categories and subcategories, see the discussion in #1229 

One possibility:

```json
    "topic": {
      "category": "Higgs Physics",
      "subcategory":  "BSM",
      "source": "CMS Collaboration"
    }, 
```

If we need multiple values, some of the above can be list e.g. "topics".

We may also want to rename this because "topic" is general and if we only use MC, we could say:

```json
    "simulated_dataset_categories": {
      "primary": "Higgs Physics",
      "secondary":  "BSM",
      "source": "CMS Collaboration"
    }, 
```

CC @ArtemisLav @heitorPB @katilp 

P.S. See also `type.primary` and `type.secondary` fields.

**Comment by tiborsimko** [comment]
Another thing: do we want to start tagging also analysis examples etc with BSM physics etc?  In this case the top-level field could stay being called `topic`...

**Comment by heitorPB** [comment]
Should we have a list only for `categories.secondary`? Or also for `categories.primary`?

**Comment by tiborsimko** [comment]
RFC decided, task created, closing.
