### ISSUE TITLE
CMS: add documentation for how to compute cross section for a dataset

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2476]
For CMS MC datasets, we can the cross-section values from the McM database, but these values can also be read from the files as well. Good instructions exist for how to read the cross section values in
https://twiki.cern.ch/twiki/bin/view/CMS/HowToGenXSecAnalyzer
and listing of more precise values (in case of higher order corrections) are available
(and should be used whenever possible):
https://twiki.cern.ch/twiki/bin/viewauth/CMS/StandardModelCrossSections
https://twiki.cern.ch/twiki/bin/viewauth/CMS/StandardModelCrossSectionsat8TeV

Instead of displaying the cross-section value (which may or may not be there, and in many case should be updated with the corrections), we will rather point to more information under "Description"

See the instructions on  how calculate the cross section  for the physics analysis: CMS Guide to calculating cross sections

**Comment by katilp** [comment]
This will be only for Run2 as this information is available in the data format only starting from CMSSW_5_3_21:

Indeed, following instructions in https://twiki.cern.ch/twiki/bin/view/CMS/HowToGenXSecAnalyzer
work on the Open Data VM:

```
cmsrel CMSSW_5_3_32
cd CMSSW_5_3_32/src
cmsenv
curl https://raw.githubusercontent.com/syuvivida/generator/master/cross_section/runJob/ana.py  -o ana.py
# change the global tag i ana.py as instructed in http://opendata.cern.ch/docs/cms-guide-for-condition-database + add the symbolic links
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_V27 START53_V27
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_V27.db START53_V27.db
cmsRun ana.py inputFiles="root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2012/Summer12_DR53X/DiPhotonBorn_Pt-10To25_8TeV_ext-pythia6/AODSIM/PU_RD1_START53_V7N-v2/10000/00E9331C-F1E1-E211-8C43-0025B3E06528.root" maxEvents=-1
```
This gives a warning:
```
%MSG-w LocalFileSystem::initFSList():  (NoModuleName) 11-Dec-2018 15:42:27 CET  pre-events
Cannot read '/etc/mtab': No such file or directory (error 2)
%MSG
[......]
-----------------------------------
GenXsecAnalyzer:
------------------------------------
------------------------------------
Cross-section summary not available
------------------------------------

```

**Comment by tiborsimko** [comment]
@katilp We would need a public version of the above page (that is available to CMS only.)

**Comment by jmhogan** [comment]
Since she's been running XsecAnalyzer, Xiaohe will work on making this page. We'll do something like cms-guide-cross-sections with two main sections: 
* Run 2: how to process the XsecAnalyzer in the 7-6-7 and 10-6-30 environments
* Run 1: we can copy/paste into markdown the tables on these TWikis for 7 and 8 TeV. 
We'll check in with GEN about whether or not these pages can be made public so that we can link to them for extra info.

**Comment by katilp** [comment]
Closing as now in https://opendata.cern.ch/docs/cms-guide-xsec
