### ISSUE TITLE
CMS: combine "Description" and "Notes" in data records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2477]
For CMS records, it would be best to combine the two distinct areas now under
"Description", e.g. now:
```
    "abstract": {
      "description": "<p>Simulated dataset DiPhotonBorn_Pt-10To25_8TeV_ext-pythia6 in AODSIM format for 2012 collision data.</p><p>See the description of the simulated dataset names in: <a href=\"/about/CMS-Simulated-Dataset-Names\">About CMS simulated dataset names</a>.</p>"
    }, 
```
and "Notes", e.g now
```
    "note": {
      "description": "These simulated datasets correspond to the collision data collected by the CMS experiment in 2012."
    }, 
```
 in a single "Description", both for collision data and MC

**Comment by ArtemisLav** [comment]
> I would be in favour of doing this for every record i.e. non-CMS as well. @ArtemisLav Do we need a `note` field separate from the `abstract` field?

I like this idea as well. I don't think we need them separate - it's this way because they were separate fields in the old system.

**Comment by tiborsimko** [comment]
- [ ] amend data model
- [ ] amend mappings
- [ ] amend fixtures
- [ ] amend display templates
