### ISSUE TITLE
CMS Open Data also accompany publications: Mention on "About CMS Data"

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#249]
- [x] Add disclaimer text: **TODO** @RaoOfPhysics
- [ ] [Tom's "papers' timeline"](http://cms.web.cern.ch/org/physics-papers-timeline) modified to point to INSPIRE, and highlight papers with data: **TODO** @tpmccauley

**Comment by suenjedt** [comment]
I am closing this for now. With the redesign I don't see this as a priority right now. If we reconsider options, we can reopen, of course.
