### ISSUE TITLE
Truncated files in records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2509]
A user reports truncated files in records:

http://opendata.cern.ch/record/460
http://opendata.cern.ch/record/461
http://opendata.cern.ch/record/462

This has been unresolved for a while now, but there was a fix earlier the the same/similar problem but I could not find that 
@diegodelemos Did you fix that last time?

**Comment by tiborsimko** [comment]
XRootD access seems OK, only HTTP leads to truncated files. Need to check `nginx` behaviour regarding compression and friends and to double confirm `nginx` buffering fix.

**Comment by katilp** [comment]
@tiborsimko Did you have the occasion to check further?

**Comment by tiborsimko** [comment]
Confirming that `xrootdpyfs` works fine... The problem is due to wrong file sizes.

**Comment by tiborsimko** [comment]
Checked all the CMS software records, found the following ones differ:

```
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Mu/readme.txt 2348 3161
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Mu/DemoAnalyzer.cc 14689 29227
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Mu/demoanalyzer_cfg.py 3525 5088
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Commissioning/readme.txt 2348 2971
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Commissioning/DemoAnalyzer.cc 14689 29410
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-Commissioning/demoanalyzer_cfg.py 3525 5228
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-MinimumBias/readme.txt 2348 2980
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-MinimumBias/DemoAnalyzer.cc 14689 35250
root://eospublic.cern.ch//eos/opendata/cms/software/validation-2010-MinimumBias/demoanalyzer_cfg.py 3525 5093 
```
