### ISSUE TITLE
Errors in record 5500

### ISSUE THREAD

**Issue by clelange** [cernopendata/opendata.cern.ch#2517]
Hello,

While running the full [5500](http://opendata.cern.ch/record/5500) example (levels 3 and 4 if you check the corresponding [GitHub repo](https://github.com/cms-opendata-analyses/HiggsExample20112012)), I realised that there are a few bugs:

- There are two links to [/DoubleMuParked/Run2012B-22Jan2013-v1/AOD](http://opendata.cern.ch/record/6004) while one of them should be to [/DoubleMuParked/Run2012C-22Jan2013-v1/AOD](http://opendata.cern.ch/record/6030) - mind *B* vs. *C*
- [5501](http://opendata.cern.ch/record/5501) should be linked from 5500, since these files are needed to make the plots in Level3
- There are files in [5501](http://opendata.cern.ch/record/5501) that are actually not needed/used at all, which I removed in this [PR](https://github.com/cms-opendata-analyses/HiggsExample20112012/pull/2)

**Comment by ArtemisLav** [comment]
https://github.com/cernopendata/opendata.cern.ch/pull/2522 addresses the first 2 points. Record 5501 is already published and has a DOI, so it is not possible to remove files from there.

**Comment by clelange** [comment]
Thank you @ArtemisLav - regarding the superfluous files, and before closing the issue, what about adding a comment to [5501](http://opendata.cern.ch/record/5501) stating which files are actually needed or not?

**Comment by ArtemisLav** [comment]
@clelange Sure, if it's useful, I could add a note under 'How can you use these data?'. Could you please provide the text for the note?

**Comment by clelange** [comment]
What about adding:
```
Mind that the following files are not needed to produce the plot but are only the products of intermittent processing steps:

- DY101Jets12.root
- DY50Mag12.root
- DYTo2mu12.root
- TTJets11.root
- TTJets12.root
```
