### ISSUE TITLE
CMS: prepare data records for upgrade MC samples used in ML

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2520]
NB: update for the corrected files below https://github.com/cernopendata/opendata.cern.ch/issues/2520#issuecomment-476547607

From #2459: Prepare data records for 

- /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/GEN-SIM-RAW
- /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/GEN-SIM-RECO
- /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/AODSIM

in

- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/AODSIM/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000
- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/GEN-SIM-RAW/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000
- https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/GEN-SIM-RECO/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000

Provenance in
provenance in https://cms-pdmv.cern.ch/mcm/requests?prepid=PPD-RunIIAutumn18DR-00001&page=0&shown=127

**Comment by katilp** [comment]
@felicepantaleo are these the samples that will be substituted with the new production?

**Comment by felicepantaleo** [comment]
@katilp , yes these will be replaced as the others have a bug.
It is important to have DIGI as well as the new ones will have MC information for the Pileup, so that people can run their reconstruction and validate correctly the result.

**Comment by katilp** [comment]
@felicepantaleo OK, let me know when done and we'll transfer and prepare the records on the portal. Do you have a link to the provenance of the new production (as above) or should I get it from the e-mail thread?

**Comment by felicepantaleo** [comment]
@katilp I cannot find in the emails, let me know if you find it :)

**Comment by katilp** [comment]
Provenance for the new production 

https://cms-pdmv.cern.ch/mcm/chained_requests?prepid=PPD-chain_RunIIFall18GS_flowRunIIAutumn18DRPUAvg50IdealConditionsRECO-00004&page=0&shown=15

https://cms-pdmv.cern.ch/mcm/chained_requests?contains=PPD-RunIIAutumn18DR-00008&page=0&shown=15

**Comment by katilp** [comment]
@felicepantaleo we can find the provenance from the McM entries above, thanks Paolo. A further question: should we also transfer the pile-up sample /MinBias_TuneCP5_13TeV-pythia8/RunIIFall18GS-IdealGeometry_102X_upgrade2018_design_v9-v1/GEN-SIM for full reproducibility?

**Comment by katilp** [comment]
@felicepantaleo Do we provide both ttbar and single mu samples as open data?

**Comment by felicepantaleo** [comment]
single muon maybe just the gen sim.
We asked it without pileup, but we got it with it... :-)

**Comment by katilp** [comment]
@felicepantaleo @adrianoDee For the ttbar is there also an AODSIM file. I see only GEN-SIM-DIGI-RAW and FEVDEBUGHLT in DAS?

**Comment by katilp** [comment]
[transfer request done](https://cmsweb.cern.ch/phedex/prod/Request::Admin?request=1714617) for GEN-SIM, GEN-SIM-DIGI-RAW ttbar, and GEN-SIM pileup sample

**Comment by katilp** [comment]
To do (in addition to #2599) 
- [ ] create a config record for SIM step  (for the GEN-SIM record) https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/439614e270574edc46f517339338188e/configFile
- [ ] create a config record for HLT step (for the GEN-SIM-DIGI-RAW record) https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/439614e270574edc46f51733936d93c8/configFile
- [ ] create a config record for SIM step (for the pileup GEN-SIM record) https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/3c6407f267a8f03cbd0cbc319a685a1f/configFile

@tiborsimko

**Comment by katilp** [comment]
Adding  FEVDEBUGHLT 
- [ ] transfer [request](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1555251794%3Bnode%3D2241%3Brequest%3D1761433) done
- [ ] config for FEVHLTDEBUG: https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/439614e270574edc46f51733936d93c8/configFile
- [ ] production script https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/PPD-RunIIAutumn18DR-00008 (already in the GEN-SIM-DIGI-RAW record, but cross-check)

**Comment by katilp** [comment]
To clarify (for academic interest..): GEN-SIM-DIGI-RAW comes out of a RECO step.:
https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/dbde940aa8762e4da0bac23833d80c27/configFile

 Why doesn't it have RECO in the file ending? Because it keeps more content than usual (FEVTDEBUG)?

**Comment by katilp** [comment]
Make sure that the correct files are displayed, see the provenance in

https://cms-pdmv.cern.ch/mcm/requests?produce=%2FTTToHadronic_TuneCP5_13TeV-powheg-pythia8%2FRunIIAutumn18DR-PUAvg50IdealConditions_IdealConditions_102X_upgrade2018_design_v9_ext1-v2%2FFEVTDEBUGHLT&page=0&shown=70368744177663

for. http://opendata-dev.web.cern.ch/record/12303
and check that the parent files are correct (now different production)

**Comment by katilp** [comment]
To do:
- move files
- add file index listing
