### ISSUE TITLE
CMS: update the getting started instructions for docker usage

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2523]
We have docker images available and usable for open data. We can as well give instructions to external users for them

- [x] update http://opendata.cern.ch/docs/cms-getting-started-2011 and http://opendata.cern.ch/docs/cms-getting-started-2010 
      -  i.e. in the first step either add instructions on how to use the docker containers, or add a "parallel" pages to http://opendata.cern.ch/docs/cms-virtual-machine-2011 and http://opendata.cern.ch/docs/cms-virtual-machine-2010 (depends on how much instructions are needed, the current pages for VM are longer as they include the VirtualBox download instructions as well)
- [x] update the top part of http://opendata.cern.ch/docs/cms-guide-for-research
- [x] add a mention of it in under "Tools" in http://opendata.cern.ch/docs/about-cms
- [ ] build records similar to VM image records http://opendata.cern.ch/record/252 and http://opendata.cern.ch/record/250, and eventually for the scripts needed to create them (similar to http://opendata.cern.ch/record/251)

**Comment by RaoOfPhysics** [comment]
Amazing stuff! Looking forward to trying this out. Congratulations to everyone involved in preparing this. :D

**Comment by katilp** [comment]
@RaoOfPhysics Thanks for volunteering for testing :wink:

**Comment by RaoOfPhysics** [comment]
With pleasure! Where can I pull the image from? :D

**Comment by katilp** [comment]
https://hub.docker.com/search?q=cmssw&type=image but I let @clelange indicate which ones should be used for slc5 and slc6 based releases

**Comment by katilp** [comment]
@tpmccauley you could update the policy links #2524 at the same time when you make a PR

**Comment by clelange** [comment]
There are different versions of the containers available, see https://github.com/clelange/cmssw-docker

I guess for OpenData purposes we want the releases containing the full CMSSW releases, i.e. the standalone versions? In this case, they are listed at https://hub.docker.com/r/clelange/cmssw/tags, and an example would be `clelange/cmssw:5_3_32`

**Comment by tpmccauley** [comment]
I tried `clelange/cmssw:5_3_32` and ran [this code](https://github.com/cms-opendata-analyses/DimuonSpectrum2011) which corresponds to [this record](http://opendata.web.cern.ch/record/5001) right out-of-the-box. Need to figure out how to run ROOT browser (i.e. sort out DISPLAY).

**Comment by clelange** [comment]
The display is unfortunately a bit more tricky... In the past, I've used this on MacOS:
https://gist.github.com/kiki67100/5e1568ac783e8e4942b672f1090db2cd

On Linux this might be easier, no idea for Windows.

And then before running from a new terminal:
```
p=0
for port in $(seq 0 10); do
  echo "Check :$((6000+$p)) (:$p)"
  nc -w0 127.0.0.1 $((6000+$p)) && DISPLAY="$IP:$p"
  let p=p+1
done
/usr/X11/bin/xhost + $IP
docker run -e DISPLAY=$DISPLAY clelange/cmssw:5_3_32
```

**Comment by katilp** [comment]
@clelange the lighter version would be good as well, it would give the freedom for the user to choose the CMSSW version and build it from /cvmfs. In any case, the condition data come from /cvmfs runtime, so even the container with CMSSW is not really stand-alone. But no strong opinions.

**Comment by clelange** [comment]
For the "lighter" versions, you either need to have `/cmvfs` mounted already, or you need to start the container in privileged mode. I guess the latter method is significantly easier.

**Comment by katilp** [comment]
@clelange @tpmccauley whichever is good as long as instructions are provided (+ pros and cons explained if more than one option is provided)

**Comment by tiborsimko** [comment]
Besides providing Docker containers and usage instructions, some easily runnable REANA examples would be handy :wink: permitting to make sure things are reproducible.

**Comment by katilp** [comment]
@tpmccauley How does this look like, will this make it in time for the current release (in a time scale of 2 weeks)? No problem if it does not, but if it is an easy addition, we can include it.

**Comment by tiborsimko** [comment]
@katilp Note that the PR closed the issue, but the last item is still unchecked, so if you'd like to have build recipes on the portal, we can reopen...
