### ISSUE TITLE
CMS: Prepare data records for tracker-hit-enriched Run1 AOD for ML

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2526]
prepare data records for the intermediate steps for tracker-hit-enriched Run1 AODs

(from #2444 )

Corresponding open datasets are

http://opendata.cern.ch/record/9582 (ttbar all jets)
http://opendata.cern.ch/record/8882 (QCD flat)
http://opendata.cern.ch/record/8898 (QCD EM Enriched)

The newly produced ones, tracker hits added, are being uploaded to
https://eospublichttp.cern.ch/eos/opendata/cms/upload/emanuele

and have the following configs (step0 SIM, step1 HLT, step2 RECO, step3 Demo):

record 9582 (ttbar all jets):
https://github.com/emanueleusai/opendatadnn/blob/master/step0_ttbar_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step1_ttbar_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step2_ttbar_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step3_ttbar_V27.py

record 8882 (QCD flat):
https://github.com/emanueleusai/opendatadnn/blob/master/step0_QCDPt_15_3000_Flat_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step1_QCDPt_15_3000_Flat_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step2_QCDPt_15_3000_Flat_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step3_QCDPt_15_3000_Flat_V27.py

record 8898 (QCD EM Enriched):
https://github.com/emanueleusai/opendatadnn/blob/master/step0_QCDPt_80_170_EM_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step1_QCDPt_80_170_EM_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step2_QCDPt_80_170_EM_V27.py
https://github.com/emanueleusai/opendatadnn/blob/master/step3_QCDPt_80_170_EM_V27.py

Release: CMSSW_5_3_32 Global Tag: START53_V27

In the dataset description of the record it should be mentioned that these datasets have been specially prepared in order to keep tracker hit that are needed for the ML studies.

To do:

- [x] prepare records
- [x] complete metadata (nevents)

**Comment by katilp** [comment]
@emanueleusai I see that the files are in transfer and coming to the upload area. This issue is for preparing the data records for them. Can you just confirm that the configs above are the ones that were used to produce them?

And do I understand correctly that:
- step0 produces GEN-SIM
- step1 produces GEN-SIM-RAW
- step2 produces AODSIM
- step3 produces root file good for ML studies ?

In the upload area, I see directories for step2 and step3, which I assume contain AODSIM and ML study root files, respectively.
Will you transfer also the file for step0 and step1?

For the data records, in addition to n_files and volume, which we can get from the files once upload is done, we also give number of events. Would you provide event numbers. Thanks!

**Comment by emanueleusai** [comment]
Hi Kati,

Thank you for restarting the discussion. Answers inline:

> @emanueleusai I see that the files are in transfer and coming to the upload area. This issue is for preparing the data records for them. Can you just confirm that the configs above are the ones that were used to produce them?

The configs have been slightly changed with respect to the ones in here. 
I am preparing the updated repo here (still empty now): https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool
I'll push a cleaned-up version by Monday. 

> 
> And do I understand correctly that:
> 
> * step0 produces GEN-SIM
> * step1 produces GEN-SIM-RAW
> * step2 produces AODSIM
> * step3 produces root file good for ML studies ?
> 

Yes this is correct!

> In the upload area, I see directories for step2 and step3, which I assume contain AODSIM and ML study root files, respectively.

Yes, this is correct. The transfer is proceeding somewhat slowly (30-50M/s). Do you know if there's a quicker way than running a very long list of xrdcp commands? I'm currently running 4 concurrent transfer jobs at different machines. I predict it might take another 7-10 days before the transfer is complete at this transfer rate. The data isn't on DAS, so I guess Phedex wouldn't work.

> Will you transfer also the file for step0 and step1?

We thought that the relevant files for ML studies are the step3 (the Ntuples themselves with only tracking information) and step2 the AOD+RecHits useful to reproduce and, more importantly, extend the ntuples in case more collections are required by the user (e.g. calorimetric information). 
I will provide the full list of instructions to reproduce step0,1,2 on the opendata release. Unfortunately we had to delete the original step0 and 1 as we did not have enough space to store all the steps (~100-150T). 
However, if this is needed we can re-generate a reduced amount of events (say 10-100k) at step0 and step1 for every sample. 

> 
> For the data records, in addition to n_files and volume, which we can get from the files once upload is done, we also give number of events. Would you provide event numbers. Thanks!
Yes, we will add the number of events.

Cheers,
Emanuele

**Comment by katilp** [comment]
@emanueleusai perfect, thanks, makes sense. It would be nice if you could provide a brief description of the samples to be added to the record to explain what is different from the standard samples. It will go under the title "Description" (something like in http://opendata-dev.web.cern.ch/record/37 but specific to these samples). Each step will have their own record, and they will be linked to each other.

For the transfer, maybe @tiborsimko can advise.

**Comment by emanueleusai** [comment]
@katilp Ok! I'll add the description of the samples.

**Comment by katilp** [comment]
@emanueleusai For the 4 configs (step0-3), are the trakcer-hit related changes with compared to the standard CMS config files in step 1 "HLT2":
`outputCommands = process.RAWSIMEventContent.outputCommands+cms.untracked.vstring('keep *_simSiPixelDigis_*_*','keep *_simSiStripDigis_*_*','drop *_*_*_HLT'),` 
and in step 2 "RECO2":
`outputCommands = process.AODSIMEventContent.outputCommands+cms.untracked.vstring('keep *_simSiPixelDigis_*_*','keep *_simSiStripDigis_*_*','keep *_siPixelClusters_*_*','keep *_siStripClusters_*_*','keep *_g4SimHits_*_*','keep *_generalTracks_*_*','drop *_*_*_RECO'),` ?

And step 0 is otherwise as the usual production SIM apart from the fact that it has been tested to work on the Open Data env? Or are there tracker-hit related changes there already?

Thanks!

**Comment by emanueleusai** [comment]
Hi @katilp ,

step0,1,2 are exactly the standard production config except for the added "keep" statements in the relative output commands. We are keeping the tracker clusters (to reconstruct the rechits on the fly) and the simtracks (to match the hits to sim objects).

In terms of generated processes we had to make some changes (and this is why the codebase needs to be updated by me asap):
1) for QCD we used QCD pTHat 15 to 3000 (record 8882) as a basis and produced three samples with QCD pTHat 600 to 3000, 300 to 600 and 400 to 600.
2) for ttbar we used the standard MG configuration (as in e.g. record 9582), modified to force all-jets decays and pT of both of the tops > 400 GeV. I will add the MG datacards to the repo. 
The changes were necessary in order to produce a useful amount of "boosted jets". Which is the aim of our study, and we think is also a rather interesting benchmark for ML-related studies.
The configs are flexible enough that can be configured to produce events inclusively.

Cheers,
Emanuele

**Comment by emanueleusai** [comment]
Hi @katilp ,

the links in the first post are now obsolete. The new configs can be found in:
https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool/tree/master/configs

Instructions on how to reproduce the dataset, the content of the datasets, and other metadata can be found here:
https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool/blob/master/README.md 

Cheers,
Emanuele

**Comment by katilp** [comment]
To do:
- clean the text in the config file links, now:
![configlink](https://user-images.githubusercontent.com/5859918/60336908-ed357a00-99a1-11e9-9ce4-3f024abb232a.JPG)
