### ISSUE TITLE
CMS: file is missing in dataset 2011 MC WJetsToLNu

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2531]
1 file is missing in dataset 2011 MC WJetsToLNu http://opendata.cern.ch/record/1633. 
It should be 3214 files but only 3213 files are in the portal. 

The missing file is 
Summer11LegDR/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/AODSIM/PU_S13_START53_LV6-v1/00001/4EF4882B-D8B4-E311-A42C-0026189438D4.root
(found in in DAS)

**Comment by tiborsimko** [comment]
Created `INC1949890` for three missing AODSIM files (including this one) and `INC1949829` for ten missing masterclass files. (Found after checking everything.)

**Comment by katilp** [comment]
Transfer request done: https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1555941193%3Bnode%3D2241%3Brequest%3D1772245

**Comment by katilp** [comment]
The missing file is
`/eos/opendata/cms/upload/mc/Summer11LegDR/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/AODSIM/PU_S13_START53_LV6-v1/00001/4EF4882B-D8B4-E311-A42C-0026189438D4.root`

and it does not appear in the file index in

`/eos/opendata/cms/MonteCarlo2011/Summer11LegDR/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/AODSIM/PU_S13_START53_LV6-v1/file-indexes/CMS_MonteCarlo2011_Summer11LegDR_WJetsToLNu_TuneZ2_7TeV-madgraph-tauola_AODSIM_PU_S13_START53_LV6-v1_00001_file_index.txt`

**Comment by tiborsimko** [comment]
File moved, indexes recreated, PR for fixtures coming...
