### ISSUE TITLE
templates: warning for on-demand datasets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2562]
After introducing on-demand datasets (#2508), we shall have to amend detailed record page templates to display a big warning in case `availability` field is set to "ondemand".

The text could go in a nicely framed box with a text like

```
DATASET WITH ON-DEMAND FILES

Please note that this dataset is released with the bibliographic information content only.
The dataset contains NNNN files of SSSS size that are not available online as of yet. If you 
are interested in accessing the files, please contact opendata-support AT cern DOT ch. Note 
that the file transfer to online storage may take several weeks or months.
```

CC @pamfilos for the UI

CC @katilp for the text

Stems from #2466 #2508

**Comment by katilp** [comment]
@tiborsimko Looks good, maybe "weeks or months in case of large amount of data, and depends on the availability of the transfer system." or similar...
@caredg How does that sound?
