### ISSUE TITLE
templates: spaces in 'List of files"

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2572]
The "List of files" modal window should break long filenames according to underscores, not only dashes.

Compare the display of record 12100:

![2019-04-05-175632_480x422_scrot](https://user-images.githubusercontent.com/517546/55640562-34113a80-57cc-11e9-8595-5741b5bdd03e.png)

with the usual record 14:

![2019-04-05-175646_451x427_scrot](https://user-images.githubusercontent.com/517546/55640584-3b384880-57cc-11e9-9811-9478e01b6f96.png)

Line break by underscore would make the display nicer.

**Comment by katilp** [comment]
NB also #2689  (e.g. http://opendata-dev.web.cern.ch/record/12004):

The files in those records are have dashes but the list of file does not break properly:

Full paths are
 
```
root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2016/RunIISummer16MiniAODv2/BulkGravTohhTohbbhbb_narrow_M-1600_13TeV-madgraph/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/70000/12E5E6D8-7DB5-E611-B85C-A0000420FE80.root
root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2016/RunIISummer16MiniAODv2/BulkGravTohhTohbbhbb_narrow_M-1600_13TeV-madgraph/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/70000/E4262904-7FB5-E611-9F3A-24BE05BDBE61.root
```

so the file names shown should be like the usual ones i.e. E4262904-7FB5-E611-9F3A-24BE05BDBE61.root but it still does not break properly.
