### ISSUE TITLE
CMS: Record for ML samples (Run2 Hbb and QCD MC for ML studies)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2574]
From #2448 
Prepare the record for the root/h5 output.

This will appear as a separate record (similar to http://opendata-dev.cern.ch/record/12100).
The underlying json can be added in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json

If you are comfortable with the json description, you can suggest the contents directly to @ArtemisLav in json format (see  either in http://opendata-dev.cern.ch/record/12100/export/json or the link above), or you can give the content to the different fields here.

Needed in particular:

- Dataset name from @jmduarte 
- Author is Javier Duarte, others? orcid?
-  @jmduarte  will provide a description (for "abstract")
- Dataset characteristics (@jmduarte can provide N events/entries -  @tiborsimko will check n files)
- Dataset semantics table from @jmduarte
- Parent datasets, are these all http://opendata-dev.cern.ch/search?page=1&size=20&q=&file_type=miniaodsim apart from the flat sample http://opendata-dev.cern.ch/record/12021?
- "How were these data generated?" (or produced) with a link to SW record to be created from https://github.com/cms-legacydata-analyses/HiggsToBBNtupleProducerTool 
- How can you use these data? @jmduarte can you give a brief text and and eventually a link to an example code?

**Comment by katilp** [comment]
@jmduarte I'm preparing the record, would you have the abstract. 
Can the beginning be the same/similar to what Kimmo has in http://opendata-dev.web.cern.ch/record/12100 and then complemented by what you have in https://github.com/cms-legacydata-analyses/HiggsToBBNtupleProducerTool/blob/opendata_80X/README.md#data-set-conten? It does not need to be the same, just let me know what you prefer.

**Comment by tiborsimko** [comment]
@tiborsimko To add files after #2604 is merged...

**Comment by katilp** [comment]
Close as completed.
