### ISSUE TITLE
CMS: SW record for ML sample production (using tracker-hit-enriched Run1 AOD)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2588]
From #2444 
The structure can be as in http://opendata-dev.cern.ch/record/5104

Needed:
- title: TrackerRecHitProducerTool - an example workflow to add tracker hits to CMS Run1 AOD @emanueleusai The title should probably be extended to include the ML production part
- authors: Emanuele Usai @emanueleusai do we use the same list here as for the resulting ML samples #2575 
- @emanueleusai pls complete the brief description below in json
- tags/keywords: Software, Tool
- the datasets that are used as input: None as this explains to full production chain, or maybe the tracker-hit-enriched AODSIM #2526 can be indicated as an input for the ML production part? 
- System details 
   - VM recid 252
   - CMSSW version: CMSSW_5_3_32 (check)
- how can you use, the github repo is in 
https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool
but it will be a placeholder as it will be moved to https://github.com/cms-opendata-analyses/TrackerRecHitProducerTool and have a release tag there
- licence @emanueleusai do you agree with GNU General Public License (GPL) version 3

@ArtemisLav @tiborsimko  :
- this ML SW record produces datasets which will be on the portal, the ones in preparation in #2526 and #2575 
   - do we have an appropriate json field for that?
   - it should have as description "The ouput datasets of step2 and step3 of this software tool is available in:"

json could be:

```
{
  "created": "FIXME", 
  "id": FIXME, 
  "metadata": {
    "$schema": "http://opendata.cern.ch/schema/records/record-v1.0.0.json", 
    "abstract": {
      "description": " <p> An example workflow to produce CMS Run1 AODSIM enriched with tracker RecHits. All steps from event generation to reconstruction (step0-step2) are provided, and the tool to extract the information in a format appropriate to ML studies (step3) is included. The code can be run inside the CMS Open Data environment</p>"
    }, 
    "accelerator": "CERN-LHC", 
    "authors": [
      {
        "name": "Usai, Emanuele"
      }
FIXME, other authors as in #2575
    ], 
    "collections": [
      "FIXME Is this needed/necessary, can it be removed: CMS-Validation-Utilities"
    ], 
    "control_number": "FIXME", 
    "date_created": [
      "2019"
    ], 
    "date_published": "2019", 
    "distribution": {
      "formats": [
        "gz"
      ], 
      "number_files": 1, 
      "size": FIXME
    }, 
    "doi": "FIXME", 
    "experiment": "CMS", 
    "files": [
      {
        "checksum": "FIXME", 
        "filename": "FIXME check TrackerRecHitProducerTool-1.0.0.tar.gz", 
        "size": 16966, 
        "uri_http": "FIXME", 
        "uri_root": "FIXME"
      }
    ], 
    "index_files": [], 
    "license": {
      "attribution": "GNU General Public License (GPL) version 3"
    }, 
    "publisher": "CERN Open Data Portal", 
    "recid": "FIXME", 
    "run_period": [
      "Run2"
    ], 
    "system_details": {
      "description": "Use this code with the CMS Open Data VM environment", 
      "recid": "252", 
      "release": "CMSSW_5_3_32"
    }, 
    "title": "TrackerRecHitProducerTool - an example workflow to add tracker hits to CMS Run1 AOD", 
    "type": {
      "primary": "Software", 
      "secondary": [
        "Tool"
      ]
    }, 
    "usage": {
      "description": " <p>If you do not have the CERN Virtual Machine for CMS open data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2011\">How to install a CERN Virtual Machine</a>.  <p>To run the analysis, follow the instructions in FIXME <a href=\"https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool\">https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool</a>.</p> "
    }, 
    "use_with": {
      "description": "The ouput of step2 (FIXME check step numbers) can be used as an input to step3 :", 
      "links": [
        {
          "recid": "FIXME" #2526  
        }
      ]
    }
  }, 
  "updated": "FIXME"
}
```

**Comment by emanueleusai** [comment]
Hi @katilp ,

> From #2444
> The structure can be as in http://opendata-dev.cern.ch/record/5104
> 
> Needed:
> 
> * title: TrackerRecHitProducerTool - an example workflow to add tracker hits to CMS Run1 AOD @emanueleusai The title should probably be extended to include the ML production part
> * authors: Emanuele Usai @emanueleusai do we use the same list here as for the resulting ML samples #2575

yes

> * @emanueleusai pls complete the brief description below in json

Can it be copied or adapted from #2575 ? 

The dataset consists of hits from the tracking detector, reconstructed tracks, simulated tracks, generated particles, and jets clustered from the generated particles. The various objects are matched in order to reconstruct the provenance of the various hits.
Samples of events containing light jets (QCD) in various energy ranges have been produced. Additionally a sample containing all-hadronic high transverse momentum decays of top quarks have been produced.
The dataset consists of events extracted from simulated proton-proton collision events at a center-of-mass energy of 8 TeV generated with Pythia 6 (QCD) or MadGraph2.6 and Pythia6 (top-antitop pair sample). The particles emerging from the collisions traverse through a simulation of the CMS detector.
Samples labeled as "step2" are in the standard CMS format "AOD" plus a series of low-level tracker-related collections that allow the extraction of the tracker hits. Samples labeled as "step3" are in a custom root ntuple format and contain the position of the hits and information from the generator-level objects associated to the tracker hits.
The samples can be used to study top quark identification algorithms that use low-level detector information such as tracker hits. Machine learning algorithms are suitable for this classification task.

> * tags/keywords: Software, Tool
> * the datasets that are used as input: None as this explains to full production chain, or maybe the tracker-hit-enriched AODSIM #2526 can be indicated as an input for the ML production part?

The production chain is now explained in
https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool/blob/master/README.md
and related configs in the same repo. 

However I would still link to the datasets in #2526 

> * System details
>   
>   * VM recid 252
>   * CMSSW version: CMSSW_5_3_32 (check)

correct

> * how can you use, the github repo is in
>   https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool
>   but it will be a placeholder as it will be moved to https://github.com/cms-opendata-analyses/TrackerRecHitProducerTool and have a release tag there

I'll tag it once the files have been moved to the final position, so I can update the links in the README/instructions

> * licence @emanueleusai do you agree with GNU General Public License (GPL) version 3
> 

Yes I do.

> @ArtemisLav @tiborsimko :
> 
> * this ML SW record produces datasets which will be on the portal, the ones in preparation in #2526 and #2575
>   
>   * do we have an appropriate json field for that?
>   * it should have as description "The ouput datasets of step2 and step3 of this software tool is available in:"
> 
> json could be:
> 
> ```
> {
>   "created": "FIXME", 
>   "id": FIXME, 
>   "metadata": {
>     "$schema": "http://opendata.cern.ch/schema/records/record-v1.0.0.json", 
>     "abstract": {
>       "description": " <p> An example workflow to produce CMS Run1 AODSIM enriched with tracker RecHits. All steps from event generation to reconstruction (step0-step2) are provided, and the tool to extract the information in a format appropriate to ML studies (step3) is included. The code can be run inside the CMS Open Data environment</p>"
>     }, 
>     "accelerator": "CERN-LHC", 
>     "authors": [
>       {
>         "name": "Usai, Emanuele"
>       }
> FIXME, other authors as in #2575
>     ], 
>     "collections": [
>       "FIXME Is this needed/necessary, can it be removed: CMS-Validation-Utilities"
>     ], 
>     "control_number": "FIXME", 
>     "date_created": [
>       "2019"
>     ], 
>     "date_published": "2019", 
>     "distribution": {
>       "formats": [
>         "gz"
>       ], 
>       "number_files": 1, 
>       "size": FIXME
>     }, 
>     "doi": "FIXME", 
>     "experiment": "CMS", 
>     "files": [
>       {
>         "checksum": "FIXME", 
>         "filename": "FIXME check TrackerRecHitProducerTool-1.0.0.tar.gz", 
>         "size": 16966, 
>         "uri_http": "FIXME", 
>         "uri_root": "FIXME"
>       }
>     ], 
>     "index_files": [], 
>     "license": {
>       "attribution": "GNU General Public License (GPL) version 3"
>     }, 
>     "publisher": "CERN Open Data Portal", 
>     "recid": "FIXME", 
>     "run_period": [
>       "Run2"
>     ], 
>     "system_details": {
>       "description": "Use this code with the CMS Open Data VM environment", 
>       "recid": "252", 
>       "release": "CMSSW_5_3_32"
>     }, 
>     "title": "TrackerRecHitProducerTool - an example workflow to add tracker hits to CMS Run1 AOD", 
>     "type": {
>       "primary": "Software", 
>       "secondary": [
>         "Tool"
>       ]
>     }, 
>     "usage": {
>       "description": " <p>If you do not have the CERN Virtual Machine for CMS open data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2011\">How to install a CERN Virtual Machine</a>.  <p>To run the analysis, follow the instructions in FIXME <a href=\"https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool\">https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool</a>.</p> "
>     }, 
>     "use_with": {
>       "description": "The ouput of step2 (FIXME check step numbers) can be used as an input to step3 :", 
>       "links": [
>         {
>           "recid": "FIXME" #2526  
>         }
>       ]
>     }
>   }, 
>   "updated": "FIXME"
> }
> ```

Let me know if you need further info.
Cheers,
Emanuele

**Comment by katilp** [comment]
To do:
- change legacydata -> opendata in the guthub link
- attach zip of the repositry
