### ISSUE TITLE
CMS: SW record for ML sample production (upgrade MC for tracking GPU studies)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2589]
From #2459 
The structure can be as in http://opendata-dev.cern.ch/record/5104

Needed:
- title: @adrianodee Pls provide a title: the others have repo name (see also with @caredg) - description (see #2584, #2585, #2588) , could it be "repo name - an example workflow to apply machine learning techniques in track reconstruction in CMS Phase2 simulated data" or similar
- authors: Adriano Di Florio, Felice Pantaleo, Maurizio Pierini? @AdrianoDee  do we use the same list here as for the resulting ML samples #2576 , pls confirm both lists
- @adrianodee pls complete the brief description below in json
- tags/keywords: Software, Tool
- the datasets that are used as input:  those in preparation in #2520
- System details 
   - VM recid 252
   - CMSSW version: CMSSW_10_3_5
- how can you use, the github repo is in 
https://github.com/cms-legacydata-analyses/FIXME
but it will be a placeholder as it will be moved to https://github.com/cms-opendata-analyses/FIXME and have a release tag there
- licence @adrianodee all authors, do you agree with GNU General Public License (GPL) version 3

@ArtemisLav @tiborsimko  :
- this ML SW record produces datasets which will be on the portal, the one in preparation in #2576
   - do we have an appropriate json field for that?
   - it should have as description "The ouput datasets of this software tool is available in:"

json could be:

```
{
  "created": "FIXME", 
  "id": FIXME, 
  "metadata": {
    "$schema": "http://opendata.cern.ch/schema/records/record-v1.0.0.json", 
    "abstract": {
      "description": " <p> An example workflow to apply machine learning techniques in tracking algorithms for CMS Phase2 simulated data.  The code can be run inside the CMS Open Data environment</p>"
    }, 
    "accelerator": "CERN-LHC", 
    "authors": [
      {
        "name": "Di Florio, Adriano"
      }
FIXME, other authors as in #2576?
    ], 
    "collections": [
      "FIXME Is this needed/necessary, can it be removed: CMS-Validation-Utilities"
    ], 
    "control_number": "FIXME", 
    "date_created": [
      "2019"
    ], 
    "date_published": "2019", 
    "distribution": {
      "formats": [
        "gz"
      ], 
      "number_files": 1, 
      "size": FIXME
    }, 
    "doi": "FIXME", 
    "experiment": "CMS", 
    "files": [
      {
        "checksum": "FIXME", 
        "filename": "FIXME-1.0.0.tar.gz", 
        "size": 16966, 
        "uri_http": "FIXME", 
        "uri_root": "FIXME"
      }
    ], 
    "index_files": [], 
    "license": {
      "attribution": "GNU General Public License (GPL) version 3"
    }, 
    "publisher": "CERN Open Data Portal", 
    "recid": "FIXME", 
    "run_period": [
      "Phase2"
    ], 
    "system_details": {
      "description": "Use this code with the CMS Open Data VM environment", 
      "recid": "252", 
      "release": "CMSSW_10_3_5"
    }, 
    "title": "FIXME Repo name - an example workflow to apply machine learning techniques in track reconstruction in CMS Phase2 simulated data", 
    "type": {
      "primary": "Software", 
      "secondary": [
        "Tool"
      ]
    }, 
    "usage": {
      "description": " <p>If you do not have the CERN Virtual Machine for CMS open data installed, follow the instructions in step 1 at <a href=\"/VM/CMS/2011\">How to install a CERN Virtual Machine</a>.  <p>To run the analysis, follow the instructions in FIXME <a href=\"https://github.com/cms-opendata-analyses/FIXME\">https://github.com/cms-opendata-analyses/FIXME</a>.</p> "
    }, 
    "use_with": {
      "description": "Use this with CMS Phase2 ttbar GEN-SIM-DIGI-RAW and pile-up GEN-SIM datasets:", 
      "links": [
        {
          "recid": "FIXME" #2520   
        }
      ]
    }
  }, 
  "updated": "FIXME"
}
```

**Comment by katilp** [comment]
@adrianoDee What's your orcid id? https://orcid.org/orcid-search/quick-search/?searchQuery=Adriano%20di%20florio ?

**Comment by AdrianoDee** [comment]
@katilp Here is https://orcid.org/0000-0003-3719-8041 . Thanks!

**Comment by katilp** [comment]
Thanks! 

For the code repo, two questions:

1. I see that the input files are hardcoded 
in CNNFiltering/CNNAnalyze/test/step3_ML_pixelOnly.py and 
in CNNFiltering/CNNAnalyze/test/step3_ML_trackingOnly.py and refer to your own area
To which datasets these root files belong to?
Could you change them to point to the open data eospublic location of the files? (We will produce a file listing which will be available from the portal record)

2. Do you use the single muon dataset? It is not mentioned in the Readme of the repo, but it seems to be in L1Trigger/L1TMuon/test/runMuon.py . Is this part needed? We have no transferred it yet to open data eospublic area but it can be done if needed.

Thanks!

**Comment by AdrianoDee** [comment]
1. This was something I wanted to ask you and I forgot to: these files comes from the FEVTDEBUGHLT mentioned here (https://github.com/cernopendata/opendata.cern.ch/issues/2520) [[DAS](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FTTToHadronic_TuneCP5_13TeV-powheg-pythia8%2FRunIIAutumn18DR-PUAvg50IdealConditions_IdealConditions_102X_upgrade2018_design_v9_ext1-v2%2FFEVTDEBUGHLT&instance=prod/global)] but I couldn't find an eospublic link to them, is it me?

2. No I didn't the stuff under L1Trigger is needed in order to solve the db problem I was facing [here](https://github.com/cernopendata/opendata.cern.ch/issues/2459)

**Comment by katilp** [comment]
We've transferred:

- /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIFall18wmLHEGS-IdealConditions_102X_upgrade2018_design_v9_ext1-v2/GEN-SIM 
- /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_IdealConditions_102X_upgrade2018_design_v9_ext1-v2/GEN-SIM-DIGI-RAW |  
- /MinBias_TuneCP5_13TeV-pythia8/RunIIFall18GS-IdealGeometry_102X_upgrade2018_design_v9-v1/GEN-SIM

Are they needed in your workflow?

/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_IdealConditions_102X_upgrade2018_design_v9_ext1-v2/FEVTDEBUGHLT was not yet transferred, I'll do the request then.

And do I understand correctly, that the muon sample is not needed for reproducing the workflow, just for testing?

**Comment by katilp** [comment]
https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1555251794%3Bnode%3D2241%3Brequest%3D1761433

**Comment by AdrianoDee** [comment]
Thanks!

> Are they needed in your workflow?

The GEN-SIM (TTToHadronic & MinBias) may be usefull in future for PU studies.

> And do I understand correctly, that the muon sample is not needed for reproducing the workflow, just for testing?

Yes

**Comment by katilp** [comment]
To do:
- replace github link legacydata -> opendata
 - attach zip of the repository
