### ISSUE TITLE
templates: download index

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2618]
When offering download for index files, the button should say "Download index" rather than "Download" in order to avoid misunderstandings.  This would give "List files - Download index".

Example: http://opendata-dev.cern.ch/record/12100

**Comment by psaiz** [comment]
Just to make sure that I change the correct one, since the ticket is a bit old. You mean the `Download` button here, isn't it?

![Image](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/896ab801-a770-4114-92bb-0a36a6c15577)

**Comment by psaiz** [comment]
So, it would look like

![Image](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/17a311b8-9972-467f-bc28-6c7a1387c1ee)
