### ISSUE TITLE
templates: nicer page titles

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2620]
The page titles should be nicely created, the browser history is not very usable right now:

![2019-05-16-150350_2560x1440_scrot](https://user-images.githubusercontent.com/517546/57856028-66ab4b80-77ec-11e9-9d11-40c43d63cfe4.png)

**Comment by psaiz** [comment]
Something like this? 
![Screenshot 2024-01-29 at 14 04 32](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/70d402b2-2508-41c8-a51f-1a6a87a52484)

**Comment by tiborsimko** [comment]
> Something like this? 

Looks nice :+1:  Just one comment about the "COD" acronym that is a very internal abbreviation. I would suggest using the full name, which would give:

- CERN Open Data: About ALICE

Or, since the titles may be quite long, perhaps in inverted order as some sites are doing:

- About ALICE - CERN Open Data
