### ISSUE TITLE
CMS: Add example and files for outreach/education Run1 NanoAOD-type format

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2636]
w.r.t #2633 

Add 
- a SW record with an example producer for a simple NanoAOD-type from Run1
- the resulting root data files for selected datasets 
- a SW record with an example analysis using them

@caredg @tiborsimko @stwunsch In addition to the naming of the SW repositories which was discussed in the PR, we should think of how to place the files on the portal. There are two aspects to be decided: the location of the json description for the records and the location of the data files on eospublic.

Some options:

A. As in the H4l example (and as now in the PR #2633): 
  - the record description (for the two sw records, and the data file record) is all in the same underlying json "cms-tools-..." (as in the Higgs example: https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json)
  - the root files are displayed all together in [a separate record](http://opendata-dev.web.cern.ch/record/5501) linked to [the sw record](http://opendata-dev.web.cern.ch/record/5500)  and are located on eospublic in a sw specific directory (as currently done for the H4l example files in https://eospublichttp01.cern.ch/eos/opendata/cms/software/HiggsExample20112012)
   - this solution indicates that the root files are intended to be used mainly in the context of this example analysis

B. As in the ML examples
  - the software and root data files have a separate json definitions "cms-tools-... " and "cms-derived-..." (see all records in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records)
  - the data files reside in their own specific directory on eospublic (as currently deon for the datascience files in https://eospublichttp01.cern.ch/eos/opendata/cms/datascience)
  - this solution indicates that the root files can be used in different contexts but they have been produced with the use case in the usage example in mind

C. As currently done for the event display records and other derived data which have been produced from an existing public data record
   - the two software records would be in json "cms-tools-..."
   - the root files would reside on eospublic under the respective AOD from which they have been produced (see an example of https://eospublichttp01.cern.ch/eos/opendata/cms/Run2011A/DoubleElectron ) and thy could have a record of they own for each dataset
  - this solution gives the impression that the root files are a more of an "official" product, and usable as a general alternative to the respective AOD 

In the decision, we should take into consideration the future developments of a more complete and validated NanoAOD-like format for Run1and it will appear as in C.

**Comment by stwunsch** [comment]
Thanks for creating the issue! I'm picking this up again today. The renaming of the repositories is done, see here:

https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis

https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool

**Comment by stwunsch** [comment]
Regarding the options for placing the files, I would strongly prefer case B!
Case C would be appropriate for the official NanoAODs and case A does not seem well structured (and I copied from the H4l example ;) ).

@caredg @tiborsimko What are your opinions as experts?

**Comment by stwunsch** [comment]
@tiborsimko Could you explain me how we proceed with the `recid`s and the DOIs? That would be the last missing piece.

**Comment by katilp** [comment]
If we go for option B, we should then come up with the proper logic for placing the root files on eos.
For the moment, the only special directory we have is the `datascience` directory under https://eospublichttp01.cern.ch/eos/opendata/cms/.
Will we add another directory for for this type of files, something like `derived-data` or `example-derived-data` or `derived-analysis-data`? 
I could think that some of the already existing example files, such as the old di-muon, dielectron or jet pattuples should have indeed resided in such directory, instead of directly under the "official" AODs, although we may not want to change their location for backward compatibility issues.
@caredg , @tiborsimko  what do you think?

**Comment by caredg** [comment]
I have tried to read and understand this carefully.  After much consideration, I think I agree with option B, as well, as @stwunsch already stated.  As far as the directory for files, I would be in favor of adding a directory for this kind of files with the name `derived-data` or `derived-analysis-data` (perhaps I would favor the first one as it is a more general one).  Indeed we could try to rearrange everything so pattuples and similar files can reside there as well.  

On another topic, @tiborsimko, I would also be interested in seeing if I can learn how to deal with recid's and DOIs (if possible) as I plan to go repo by repo and reorganize everything during this summer.  I might open a different discussion for this in the following days.

**Comment by stwunsch** [comment]
I've splitted in #2633 the jsons in a `cms-tools-*.json` and `cms-derived-*.json`. Still missing are

- [ ] DOIs
- [ ] recids
- [ ] Folder for the ROOT file so that I can update the path

**Comment by katilp** [comment]
Dicussing with @tiborsimko for the naming of the directory, we would propose `derived-data/toolname` i.e 
`derived-data/AOD2NanoAODOutreachTool`

**Comment by stwunsch** [comment]
Sound good to me! So basically putting the derived files in folders named after the tool which created it. Makes sense!

**Comment by katilp** [comment]
OK, @tiborsimko will create the directory and move the file (1 file, or are there more?), maybe you can change the path in the code

**Comment by stwunsch** [comment]
The file is located here: `root://eospublic.cern.ch//eos/opendata/cms/upload/stefan/Run2012BC_DoubleMuParked.root`

What will be the new path? Is it the following?

`root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked.root`

**Comment by tiborsimko** [comment]
@stwunsch Yes, that't the correct path. I have just moved the file there, you can amend all the examples etc.

**Comment by stwunsch** [comment]
Thanks! I've updated the PR.

**Comment by stwunsch** [comment]
Note to myself:

- Add proper `git clone git://...` statement to the records to explain how to fetch the files if not download via the browser
- Evaluate adding a IPython notebook

**Comment by stwunsch** [comment]
Added the git statement and an IPython notebook.

**Comment by katilp** [comment]
Sorry for the late remark, but I now see that the root file contains only muons. That's fine, but  it would be good to reflect that in the file name. I was somehow thinking - probably based on the tau example presented at the DPOA meeting that it would also contain other objects. 
From the current naming `Run2012BC_DoubleMuParked.root` one could think that it contains all objects.

(As a side remark, it would be nice to have MET as well for W reconstruction, but no need to worry about it now)

**Comment by stwunsch** [comment]
Valid point! What do you suggest? `Run2012BC_DoubleMuParked_Muons.root`?

**Comment by katilp** [comment]
@stwunsch Sounds good. It would then make sense to attach the config file with which these data were produced to the data file? As sort of provenance. 
https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/configs/data_cfg.py keeps all objects, doesn't it?

**Comment by stwunsch** [comment]
Yes correct, the version I commited keeps all objects since I want to reuse the record for the di-tau example later on. But the config is the correct one, the path to the files are replaced during the jobs.

**Comment by katilp** [comment]
OK, it is good to have the full config in the tool repository. That's perfect.
But do you also  have the one which drops other objects for the muons-only  dataset so that we could add it to the data record?

**Comment by stwunsch** [comment]
The dropping is done "manually" by removing the write-out in the code itself. I could add such a sentence to the record of the file explaining this? I agree that this is currently not very clear.

**Comment by stwunsch** [comment]
I'm not in office next week, going to pick this up again as soon as I'm back.

**Comment by katilp** [comment]
@stwunsch @caredg pls check the new records
http://opendata-dev.web.cern.ch/record/12340
http://opendata-dev.web.cern.ch/record/12341
http://opendata-dev.web.cern.ch/record/12342

For the root file, it would be good to have the provenance information under "How were these data selected" (NB that this title will become "How were these data produced", see #2623) the http://opendata-dev.web.cern.ch/record/12100.
I.e.
 ```
 "methodology": {
      "description": "This dataset was produced with the software available in:", 
      "links": [
        {
          "recid": "12340"
        }
      ]
    }, 

```
and adding a brief notion of what was changed i.e. that all other products than muons were manually dropped.

**Comment by caredg** [comment]
It looks good to me.  I only spot a typo in 12342, at the end of the Description section:
"The result of this analysis can be compare" --> "The result of this analysis can be compare**d**"

**Comment by katilp** [comment]
Few more points:

- for ease of use, the producer tool and the analysis should have a link to the github repo, downloading and copying files from the portal record is somewhat more error prone 
- for the sake of completeness, the root file could have a mention that the god lumi mask has been applied in the production step, for example, sommething like following in a validation section:

```
 "validation": {
      "description": "These data were derived from the 2012 DoubleMuParked primary datasets using only the validated runs. No further validation was done for the output."
    }
```

**Comment by stwunsch** [comment]
Create PR #2682 with following changes:

- Fixes typo
- Added additional information about the data selection
- Linked the dataset explicitely to the software used to produce it

The link to the github repo is included in the analysis record in the section "How can you use this?".

**Comment by stwunsch** [comment]
Just to keep this here as an reminder @tiborsimko @katilp:

Do you plan to add DOIs to the records?

**Comment by katilp** [comment]
Yes, it is planned, will be done as the last thing before the release.

**Comment by katilp** [comment]
@stwunsch pls make a release tag for https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis as well so we can can attach the zip of it to the record. Thanks!

**Comment by stwunsch** [comment]
@katilp You can find the changes in #2708! I've created v1.0 releases for the analysis and the conversion tool and changed the respective sections in the records.

**Comment by tiborsimko** [comment]
To do:

- DOI for records
