### ISSUE TITLE
CMS: figure for the SW record for ML sample production (tracker-hit-enriched Run1 AOD)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2654]
Figure to add to SW record /record/12210 to explain different steps

![opendata_cartoon](https://user-images.githubusercontent.com/5859918/58973850-3fc7b000-87c1-11e9-9843-b73f718c070d.png)

See if the description reads well with it

**Comment by tiborsimko** [comment]
Depends also on #2658

**Comment by tiborsimko** [comment]
@katilp Dependency solved, so we can now host the picture on EOS.  

Alternatively, you can upload it to GitHub https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool and we can use the link to display it from there.  (Like we are doing for `DimuonSpectrumNanoAODOutreachAnalysis`.) This seems preferable e.g. for those people who will come over to the GitHub example repository without passing by the CERN Open Data portal.

**Comment by katilp** [comment]
True, I've now uploaded it there, @emanueleusai is that OK?
It can then be show in the readme as well.

**Comment by emanueleusai** [comment]
Sure! That's ok for me.
