### ISSUE TITLE
CMS: Docs texts to proofread

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2679]
We have new documentation in
- [x] http://opendata-dev.web.cern.ch/docs/cms-mc-production-overview
- [x] http://opendata-dev.web.cern.ch/docs/cms-guide-event-production
- [x] http://opendata-dev.web.cern.ch/docs/cms-guide-docker
- [x] http://opendata-dev.web.cern.ch/docs/simulated-dataset-categories

@RaoOfPhysics I did not pick up anything in them, but it would be very nice, though, if you could read them through and make a PR for eventual corrections. Thanks!

**Comment by RaoOfPhysics** [comment]
@tiborsimko, it's been a while since I poked around the codebase. Can you please let me know which branch I should look in, for these docs?

**Comment by katilp** [comment]
@RaoOfPhysics I know 😄 it's `master` !

**Comment by RaoOfPhysics** [comment]
Perfect, @katilp. :D Will check it out ASAP. :)

**Comment by RaoOfPhysics** [comment]
@tiborsimko, does the highlighter used for code chunks support language specification?

i.e., can we say, e.g.:

````
```python
from numpy import numpy
```
````

so it renders "prettily":

```python
from numpy import numpy
```

**Comment by tiborsimko** [comment]
Mistune with highlighting extension should support it, but I had a look and we seem to have all-black Python code displayed in `/docs/cms-getting-started-2010` so we'd need to dig deeper into the highlighting extension...

**Comment by RaoOfPhysics** [comment]
Thanks, @tiborsimko. Maybe I'll add it in for whenever the support is available.
