### ISSUE TITLE
records: empty system details for CMS datasets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2692]
System details is not well populated for Run2 datascience records:

```console
$ cat cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json | jq -S '.[].system_details' | head -10
{
  "global_tag": "",
  "release": ""
}
{
  "global_tag": "",
  "release": ""
}
```

Note that we have similar troubles with Run1, Run2 and 2012 MC datasets:

- see https://github.com/cernopendata/opendata.cern.ch/pull/2685#issuecomment-505530003)

**Comment by katilp** [comment]
For all Run2 datascience MC (miniaodsim)
- release: CMSSW_8_0_26
- global tag: 80X_mcRun2_asymptotic_2016_TrancheIV_v8

For all Run1 2011-2012 (`date_created`)
- release: CMSSW_5_3_32
- For 2011 MC global_tag:  START53_LV6A1
- For 2012 MC global tag: START53_V27

**Comment by katilp** [comment]
Checked: 

- cms-simulated-datasets-2012.json, it has 
```
"system_details": {
      "global_tag": "START53_V27::All",
      "release": "CMSSW_5_3_32"
    },
```
- cms-simulated-datasets-Run2011A.json

```
 "system_details": {
      "global_tag": "START53_LV6A1::All",
      "release": "CMSSW_5_3_32"
    },
```
- cms-simulated-datasets-Run1-datascience.json

 ```
  "system_details": {
      "global_tag": "START53_V27",
      "release": "CMSSW_5_3_32"
    },

```
so the empty global tag maybe comes from another json field (methodology?)

**Comment by katilp** [comment]
@tiborsimko : the empty global tags which were found in  https://github.com/cernopendata/opendata.cern.ch/pull/2685#issuecomment-505530003 are due to an unused `generator` field

   ```
"generator": {
      "global_tag": "",
      "names": []
    },
```

As there's a `"generators"` filed in `methodology` (which is in use), the one above could be removed.

**Comment by tiborsimko** [comment]
Indeed... Looking at the whole record set, we have this field still being used in some places:

```
*  cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json
{
  "global_tag": "START53_LV4::All",
  "names": [
    "pythia6"
  ]
}
*  cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json
{
  "global_tag": "START50_V13::All",
  "names": [
    "pythia6"
  ]
}
*  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
{
  "global_tag": "",
  "names": []
}
*  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json
{
  "global_tag": "",
  "names": []
}
*  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
{
  "global_tag": "START53_LV6",
  "names": [
    "pythia6",
    "powheg-minlo"
  ]
}
```

E.g. CMS 2011 MC where we needed to port the old XML/HTML based information as we couldn't find info in DAS/McM.

So we can remove the empty ones and also check the non-empty ones in the above files...
