### ISSUE TITLE
files: some 2012 configs not found

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2704]
To check, some 2012 records have links to config but bring to 404

e.g. from records

 http://opendata-dev.web.cern.ch/record/7721:

 - http://opendata-dev.web.cern.ch/eos/opendata/cms/configuration-files/MonteCarlo2012/b31348c308254b46589d683f53afcbdf.configFile.py
- http://opendata-dev.web.cern.ch/eos/opendata/cms/configuration-files/MonteCarlo2012/8119c367dee83f4172eac646b0c7560e.configFile.py
- http://opendata-dev.web.cern.ch/eos/opendata/cms/configuration-files/MonteCarlo2012/8119c367dee83f4172eac646b0cae31b.configFile.py

 http://opendata-dev.web.cern.ch/record/7728 (which for some reason has two LHE configs):

- http://opendata-dev.web.cern.ch/eos/opendata/cms/configuration-files/MonteCarlo2012/59687d1d79393aecf64d6439b6bfa710.configFile.py
- etc

Maybe a problem when copying from local?

**Comment by tiborsimko** [comment]
Whoops, my mistake regarding `*.configFile` vs `*.configFile.py`. All fixed now.
