### ISSUE TITLE
CMS: add a link from primary datasets to HLT definition instructions

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2732]
We could add to all CMS primary dataset records a link to instructions on how to find the HLT path definition:

http://opendata-dev.web.cern.ch/docs/cms-guide-trigger-system#hlt-trigger-path-definitions

Could be placed after the list, or in the description line:

> The possible HLT trigger paths (see [finding the definitions](/docs/cms-guide-trigger-system#hlt-trigger-path-definitions)) in this dataset are

or HLT trigger paths could be made a link pointing there:

> The possible [HLT trigger paths](/docs/cms-guide-trigger-system#hlt-trigger-path-definitions)  in this dataset are

**Comment by tiborsimko** [comment]
@katilp I went for the latter shorter version, see the screenshot below.  If you prefer the former longer version, please let me know.

![2019-07-15-175400_420x536_scrot](https://user-images.githubusercontent.com/517546/61230091-abd6f580-a729-11e9-8fdb-4239c0f68720.png)
