### ISSUE TITLE
CMS: container location

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2734]
See if the cmssw container should be moved from a private area to some "official" location.
If so, update http://opendata-dev.web.cern.ch/docs/cms-guide-docker accordingly.

**Comment by RaoOfPhysics** [comment]
Can we create a `CMS Experiment` organisation on Docker Hub and push the image there?

**Comment by katilp** [comment]
@clelange @tiborsimko will follow up - we already have `cmssw/cms` but may want to keep these containers in a separate `CMS Open Data` or `CERN Open Data` areas

**Comment by katilp** [comment]
The images will go to https://cloud.docker.com/u/cmsopendata/

**Comment by clelange** [comment]
BTW, whoever would like to be able to push to this [team/organisation](https://cloud.docker.com/orgs/cmsopendata/teams) or e.g. change the description of the [repositories](https://cloud.docker.com/u/cmsopendata/repository/list) etc. should send me their docker username.
