### ISSUE TITLE
CMS: update luminosity values

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2737]
The luminosity values in the current records were obtained with (e.g. 2012):

```
cmsrel CMSSW_5_3_32 (although the exact version is not relevant)
cd CMSSW_5_3_32
cmsenv

setenv PATH $HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH

# if needed, if not installed: 
pip install --install-option="--prefix=$HOME/.local" brilws
 rehash

brilcalc lumi -i Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt > 2012lumi.txt
brilcalc lumi -i RunB2012_JSON.txt > 2012RunBlumi.txt
brilcalc lumi -i RunC2012_JSON.txt > 2012RunClumi.txt
brilcalc lumi --byls -i Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt -o 2012lumibyls.csv

```

This  gives the luminosity as measured online.
More accurate values can be obtained with a different option in brilcalc command.

To do:

- [x] produce the new listings for 2010, 2011 , 2012 data taking 
  - full run range for simple listing (txt) and for  lumi-by-ls full listing (csv)
  - simple listing for run range of public data  separately (RunA 2011, RunB and RunC 2012)
- [x] create new records for the calibrated luminosity values
- [x] ~~modify the title~~ (did not do this as it does not seem necessary and was not sure if this alters the doi reference) and description of [the current records](http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&subtype=Luminosity&type=Supplementaries), and add a link to the new records
  - e.g. CMS luminosity information -> CMS online luminosity information

**Comment by caredg** [comment]
Log as work develops:
=====================

On lxplus, after setting up for brilcalc:
setenv PATH $HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH


2010
====
The globa dump:
brilcalc lumi -i --type hfoc /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions10/7TeV/Reprocessing/Cert_136033-149442_7TeV_Apr21ReReco_Collisions10_JSON_v2.txt > 2010lumi_calib.txt

By lum dump:
brilcalc lumi --byls --type hfoc -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions10/7TeV/Reprocessing/Cert_136033-149442_7TeV_Apr21ReReco_Collisions10_JSON_v2.txt -o 2010lumibyls_calib.csv

Almost no difference observed.  The only difference seems to be in the precision of the recorded lumi at the order of 0.005 /ub, which is absolutely negligible.  I would not update any record for 2010.

To be continued ...

**Comment by caredg** [comment]
@katilp do you have a blessed Run2011A json file somewhere? (and the likewise for 2012) I am always reluctant to chop out json files by hand, although I could try a semiautomatic chop-out for Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt
Thanks.

**Comment by katilp** [comment]
Only the full ones are on the portal: http://opendata-dev.web.cern.ch/search?page=1&size=20&type=Environment&subtype=Validation
I chopped by hand, and it was tedious to check, I  agree, but you can actually use
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGoodLumiSectionsJSONFile#filterJSON_py

**Comment by caredg** [comment]
@katilp This page http://opendata-dev.web.cern.ch/record/1001 tells us that RunA goes from 160431 and 173692, which is not at the boundary of the Cert_*.txt file in there.  Do you happen to know exactly what is Run B?  Perhaps it is not needed, but now that I am looking into this, it would be good to make that json file as well. Thanks.

**Comment by katilp** [comment]
@caredg  The Cert_*.txt covers all data taking. 173692 comes lrom the run range given in http://opendata-dev.web.cern.ch/record/1700 e.g. from https://fwyzard.web.cern.ch/fwyzard/hlt/2011/summary.
RunB would then be from 175832 on.

I'll re-check in DAS and confirm.

**Comment by katilp** [comment]
Yes:
- run=173692 https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+run%3D173692 gives RunA datasets
- run=175832: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+run%3D175832 gives RunB datasets

**Comment by caredg** [comment]
@katilp I was actually looking more intrigued by the lower boundary for Run A.  Because the Cert file starts at 160404 but the RunA is declared in http://opendata-dev.web.cern.ch/record/1001 starts at 160431, i.e., the runs taken with the first hlt menus were not considered?  So I think the range of Run A which is public seems not to be the same as the Run A (internal), is this right?

**Comment by katilp** [comment]
No, the runs may be taken but just no passed the validation

**Comment by katilp** [comment]
http://opendata-dev.web.cern.ch/record/1001/files/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt starts at 160431.

**Comment by caredg** [comment]
> http://opendata-dev.web.cern.ch/record/1001/files/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt starts at 160431.
> I.e. the certification starts at 160404 but the first certified run is 160431, correct?

Oh, that's right.  I was tricked by the name of the file. Never mind, thanks.  Sorry for the confusion.

**Comment by katilp** [comment]
Thanks for the detailed checking, this is very useful. Should we then add new records with the recommended  pxl values for 2011 and 2012?
Do you know what is the reason for more LS not in the pxl lumi dump while being in the Cert file?
These LS are certified, but no lumi computed for them ? How should they be handled in the luminosity calculation?
Would they count for  the difference in total between "no flag" and "pxl" listing, i.e. would 

Sum(Certified LS in "no flag" but not in "pxl") = Lumi("no flag") - Lumi("pxl")

**Comment by caredg** [comment]
I think it might be a combination of several things.  Because I can clearly see some instances by eye, this definitely happens:

- in "pxl" there are many LS that are not in "no flag" and we loose lumi for those (I do not know exactly the reason for this, but I checked with Paul last week and he confirmed the possibility that, while there is nothing wrong with the detectors for those LS, there could have been some issues with the DAQ, maybe the trigger info is not retrievable.  That is know to have happened.)
- for many runs, the same number of LS are in "pxl" and "no flag" but the luminosity numbers change (this is perhaps due to the calibration itself)

Now, it could also be that in the "pxl" version some LS are actually recovered, but I can't find an example just by eye.

In order to know for sure I would have to write a little (but tricky script).

**Comment by katilp** [comment]
The new records will be created with a proper explanation of the listings and of the validated LSs without luminosity values. 

The output listings from the commands  above are copied to eospublic to  /eos/opendata/cms/upload/kati/lumi

**Comment by katilp** [comment]
Just an update on brilcalc installation, see 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BrilcalcQuickStart

NB:

```
setenv PATH $HOME/.local/bin:/cvmfs/cms-bril.cern.ch/brilconda/bin:$PATH
pip install --user --upgrade brilws

```

**Comment by katilp** [comment]
@caredg Is there something we should change in the description of the lumi records. I'm updating the description in http://opendata-dev.cern.ch/record/1051  to take into account that all 2011 is now public http://opendata-dev.cern.ch/record/1051 but I've made no other changes. (#2865)

Should we change the wording that these numbers are from "CMS online luminosity information"?

**Comment by caredg** [comment]
@kati: This is not conclusive yet.  I am not exactly sure what to state. After you comment I went back to check on those missing LS.  I finally was able to compare the pixel results with the hfoc results and there are still LS that are in the json overall file but that do not give any result for luminosity for neither of the types.  I just wrote back to Paul.  Maybe now we will get to the bottom of this.

For the record:
I obtained [2011lumibyls_pxl.csv](https://cernbox.cern.ch/index.php/s/WVPqZ8hchvmOhzp) with:
`brilcalc lumi --byls --type pxl -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt -o 2011lumibyls_pxl.csv`

and [2011lumibyls_hfoc.csv](https://cernbox.cern.ch/index.php/s/A6YTyu7G2Snjr9Q) with:
`brilcalc lumi --byls --type hfoc -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt -o 2011lumibyls_hfoc.csv`

Then I compared the two files, concentrating in the missing LS.  [These are the results](https://cernbox.cern.ch/index.php/s/eLGpQIV8kHiHCAk), with the list of runs and LS (from the list at the bottom) that cannot be found with a lumi value in the other file.  This is a summary:
There were 159033 LS results in 2011lumibyls_pxl.csv
There were 159872 LS results in 2011lumibyls_hfoc.csv
There were 1493 LS in the not-in-results listing (at the bottom) of 2011lumibyls_pxl.csv (but that are in json quality file).
There were 654 LS in the not-in-results listing (at the bottom) of 2011lumibyls_hfoc.csv (but that are in json quality file).
There were 628 LS in the not-in-results listing (at the bottom) of 2011lumibyls_pxl.csv that were neither in the results of 2011lumibyls_hfoc.csv
There were 628 LS in the not-in-results listing (at the bottom) of 2011lumibyls_hfoc.csv that were neither in the results of 2011lumibyls_pxl.csv

**Comment by katilp** [comment]
@caredg Any updates needed for the lumi record wording in
http://opendata-dev.cern.ch/record/1050
http://opendata-dev.cern.ch/record/1051
http://opendata-dev.cern.ch/record/1052 ?

**Comment by caredg** [comment]
@kati, yes.  From the top of my head, we need 
- pxl and hfoc lumi and byls lumi listings text files for all of them
- Do we want to delete the statements in 2010 and 2011 saying something like "The values for 2010 RunB data taking are also available separately in ..."? Or include a 2010 Run A statement, i.e., complete? Likewise for 2011.  Is there a reason for only quote the last set of data?  Is it needed?
- Explain to favor pxl lumi values and that for the LS that do not have a pxl value, use the hfoc value.
- Maybe explain that the older version (currently online) is very close to the hfoc (but actually has no tag)
- Explain that the valid LS (i.e. in the json file) with no lumi value at all correspond to the last LS in a given run with STABLE BEAM flag but that actually did not produce events.  So they are safe to ignore.

**Comment by katilp** [comment]
@caredg The current statement e.g.

> The integrated luminosity for validated runs and luminosity sections of all 2010 p-p data taking is available in the table 2010lumi.txt. It includes 2010 RunA and RunB. The values for 2010 RunB data taking are also available separately in 2010RunBlumi.txt.

reflects the actual state of the files. The separate listing for RunB (or RunA for 2011) was there because that was the public data at the time of the release. I do not think we need to add a separate listing for the newly released part, and on the other hand, we do not want to delete existing files. So I think that part is OK.

These are DOI'ed records so we should keep the changes very minimal and rather have new records for the updated listings. I would therefore just add to these records that a mention that the values are close to hfoc values (with an explanation of what it is). Would you have a suggestion for that sentence?

Then the new records with pxl and hfoc lumi and byls lumi listings text files could be called 
"CMS detailed luminosity information, for YYYY CMS open data". I'll make a separate issue for that.

Maybe the detailed explanations should go to the guide page (#2845) and only the minimal explanation to the listing record?

**Comment by caredg** [comment]
So, I was thinking of putting this statement at the end of the description of the old lumi records:

"CMS measures the luminosity with different luminometers (luminosity detectors) and algorithms.  The luminosity values presented here correspond to an early version of those obtained with the  Hadron Forward calorimeter's Zero Counting algorithm (hfco).  An upgraded and more detailed version of the luminosity information, however, should be found [elsewhere](new records)"

I am preparing the new ones in a separate PR.  Would it be ok, as I did in the last sentence of the quoted text above, to point to the new, corresponding lumi records?

**Comment by katilp** [comment]
Sure, looks good, thanks! It is very good to have a link to the new records.

**Comment by caredg** [comment]
Exact Brilcalc lines used for obtaining files for upgraded lumi records:

2012:
`brilcalc lumi --type pxl --precision 3f -i 2012RunB_JSON.txt > 2012RunBlumi_pxl.txt`
`brilcalc lumi --type pxl --precision 3f -i 2012RunC_JSON.txt > 2012RunClumi_pxl.txt`
`brilcalc lumi --type hfoc --precision 3f -i 2012RunB_JSON.txt >  2012RunBlumi_hfoc.txt`
`brilcalc lumi --type hfoc --precision 3f -i 2012RunC_JSON.txt > 2012RunClumi_hfoc.txt`
`brilcalc lumi --type pxl --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions12/8TeV/Reprocessing/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt > 2012lumi_pxl.txt`
`brilcalc lumi --type hfoc --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions12/8TeV/Reprocessing/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt > 2012lumi_hfoc.txt`
`brilcalc lumi --byls --type pxl --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions12/8TeV/Reprocessing/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt -o 2012lumibyls_pxl.csv`
`brilcalc lumi --byls --type hfoc --precision 3f -i  /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions12/8TeV/Reprocessing/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt -o 2012lumibyls_hfoc.csv`

2011:
`brilcalc lumi --type pxl --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt > 2011lumi_pxl.txt`
`brilcalc lumi --type hfoc --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt > 2011lumi_hfoc.txt`
`brilcalc lumi --byls --type pxl --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt -o 2011lumibyls_pxl.csv`
`brilcalc lumi --byls --type hfoc --precision 3f -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt -o 2011lumibyls_hfoc.csv`

**Comment by caredg** [comment]
For 2010, there is no pxl information.  The current online 2010 record is, as noted [above](https://github.com/cernopendata/opendata.cern.ch/issues/2737#issuecomment-510469998) is extremely close to using --type hfoc.  I will, therefore, not make a new record for this one, but just update the current record with a bit more information about the missing LS (the ones at the end of the runs)
