### ISSUE TITLE
records: check which records go from "on-demand" to normal

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2741]
The "B-physics" datasets which were recently moved to`/eos/opendata/cms/MonteCarlo2012/Summer12_DR53X` appear as on-demand.

As the files are there, they can become normally available (with the file index listing).

NB: many of them are actually not B-physics according to the current categorization, but at the time of transfer request they ended up to what was meant B-physics because "Lambda" in the name: the categorization script was improved after.

**Comment by tiborsimko** [comment]
@katilp The ondemand availability is fixed now.  Shall we look tomorrow at rerunning and updating the categories? Might need some iterations so best to do it IRL...

**Comment by tiborsimko** [comment]
After discussion, no changes are necessary. Closing.
