### ISSUE TITLE
Broken links in CERN Open Data Portal

### ISSUE THREAD

**Issue by DBustamante98** [cernopendata/opendata.cern.ch#2751]
Good day,

Reviewing the CERN Open Data Portal datasets, @clelange and I have found that there are some missing files. Precisely, in the following records, the links listed are broken:

**[Record 25:](http://opendata.cern.ch/record/25/files/CMS_Run2011A_MuEG_AOD_12Oct2013-v1_20001_file_index.txt)**
root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MuEG/AOD/12Oct2013-v1/20001/242E37AC-7E3E-E311-9EDA-003048F01190.root

**[Record 27:](http://opendata.cern.ch/record/27/files/CMS_Run2011A_MuOnia_AOD_12Oct2013-v1_20000_file_index.txt)**
root://eospublic.cern.ch//eos/opendata/cms/Run2011A/MuOnia/AOD/12Oct2013-v1/20000/04B92898-4944-E311-8347-00261894396B.root

**[Record 1390:](http://opendata.cern.ch/record/1390/files/CMS_MonteCarlo2011_Summer11LegDR_DY2Jets_M-10To50_TuneZ2_7TeV-madgraph_AODSIM_PU_S13_START53_LV6-v1_010000_file_index.txt)**
root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2011/Summer11LegDR/DY2Jets_M-10To50_TuneZ2_7TeV-madgraph/AODSIM/PU_S13_START53_LV6-v1/010000/C25341F8-2DB6-E311-9A4E-003048FFCC18.root

**[Record 1475:](http://opendata.cern.ch/record/1475/files/CMS_MonteCarlo2011_Summer11LegDR_Bd2KstarMuMu_EtaPtFilter_TuneZ2star_7TeV-pythia6-evtgen_AODSIM_PU_S13_START53_LV6-v2_00000_file_index.txt)**
root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2011/Summer11LegDR/Bd2KstarMuMu_EtaPtFilter_TuneZ2star_7TeV-pythia6-evtgen/AODSIM/PU_S13_START53_LV6-v2/00000/44CA317B-7EB3-E311-BFE9-00266CFFA6F8.root

**Comment by katilp** [comment]
Thanks!

Transfer request done: 
https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1560666407%3Bnode%3D2241%3Brequest%3D1844388

**Comment by katilp** [comment]
@tiborsimko One transfer (`Bd2KstarMuMu_EtaPtFilter_TuneZ2star_7TeV-pythia6-evtgen`) is still ongoing but all four missing files are already in the upload area.

**Comment by tiborsimko** [comment]
Thanks, the files have been recovered and I have verified that they are well present in indexes.
