### ISSUE TITLE
CMS: update and rename records for csv files for education

### ISSUE THREAD

**Issue by JuhaTeuho** [cernopendata/opendata.cern.ch#2776]
In preparation for an improved search of different CMS derived datasets in csv format
http://opendata.cern.ch/search?page=1&size=20&q=&subtype=Derived&type=Dataset&experiment=CMS&file_type=csv

- add number_events to all records
- create new records for each csv-file in record 545 (http://opendata.cern.ch/record/545)
- create new records for each csv-file in record 300 (http://opendata.cern.ch/record/300)
- rename records to uniform forms

**Comment by JuhaTeuho** [comment]
There is still the problem with splitting the records. If some file in a record already exists, then the new record with the same file won't work.

**Comment by katilp** [comment]
Closing as implemented in #2784 😃
