### ISSUE TITLE
CMS: Higgs boson to two tau leptons outreach analysis

### ISSUE THREAD

**Issue by stwunsch** [cernopendata/opendata.cern.ch#2777]
Hi all,

I'm currently implementing the records describing the outreach analysis in [this repository](https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis) and I'll use this issue to track the progress. See the plot below for an example result:

![](https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis/raw/master/plots/m_vis.png)

**First question:** The analysis uses 9 derived datasets in reduced NanoAOD format. Should I make a separate record for each of these or one for all of them? If I do a separate record for each derived dataset, I would have to copy the dataset semantics many times. Is it ok to put all of them into a single record?

Best
Stefan

**Comment by katilp** [comment]
Hi Stefan, if the format is generic (i.e. usable also with other examples), I would be in favour of having them in separate records. It is then easier to describe the dataset provenance (i.e. derived from NNN dataset etc). 

Are these dataset the output of recid 12340 or the output of skim.cxx which is in https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis?

The skims (specific to this analysis) could eventually be in one record, but the "NanoAOD"s (outputs of the producer) would preferably have their own records.

Does that make sense?

**Comment by stwunsch** [comment]
Alright, thanks! So the files are not the output of the skims, I do not plan to put them on the portal (?).

So mainly my problem is the following: Shall I copy the dataset semantics (about 40 variables) for each record in each json file? This is not maintainable on long term since you have to change things in 9 different places.

**Comment by katilp** [comment]
If they are on the portal they will have a certain stability. We do not expect them to change that often, and if the contents change, there will be a new set of records.
Independent of that, pinging @tiborsimko to see if there's a possibility to have the dataset semantics for a set of files to be defined in a single source location. That would be the best in any case. Thinking forward also to the full NanoAOD: we will certainly not repeat full variable description for all records.

**Comment by stwunsch** [comment]
@tiborsimko I could do a "description record" and link the record from all other records. Otherwise I don't see a solution (or I copy everything around).

**Comment by stwunsch** [comment]
I've put an example setup in the PR #2778.

**Comment by katilp** [comment]
Chatting with @tiborsimko yesterday: we could have the semantics description in the sister `data-curation` repository, which is used for records (most data records) that are generated by a script. And then have a simple script to generate the records.

**Comment by tiborsimko** [comment]
The motivation is that once records are living on the portal, and each has its own DOI, they should be "well encapsulated entities", so the field descriptions had better live together with the data. Moreover, once the records are published, and have DOI minted, the dataset semantics is not going to change anymore, since the data is not going to change, so it should not be necessary to have parts of JSON "linked live" from another place using JSON reference like techniques.

As @katilp mentioned, for any non-trivial record preparation campaign we are using a sister `data-curation` repository, where we host any kind of scripts that help with preparing records, so in theory we could create a new directory there with appropriate Htt record template to ease the creation of records.

Practically speaking, since there are only a dozen of records, if we prepare one complete record with everything, and the other records containing only the specific bits, I can propagate the rest of the fields (such as dataset semantics) to the other records during merge time via some easy *ad hoc* scripting (so we don't really need a new `data-curation` directory unless you think of producing other similar datasets later on?!)

**Comment by stwunsch** [comment]
Alright, thanks for giving some insights into this :) So I'll prepare the records and we copy over the semantics during the merge. Fair enough!

**Comment by stwunsch** [comment]
@katilp @tiborsimko I've updated the PR and finalized the setup for a first review. Could you have a look?

I would also like to get some opinions from other people about the content. Could we keep the records published on the development server for some time so that I can iterate once with a broader audience?

**Comment by tiborsimko** [comment]
Ready on DEV: http://opendata-dev.cern.ch/record/12350

Keeping the issue open if we need to make any amendments.

**Comment by tiborsimko** [comment]
@stwunsch Are there any amendments needed? Otherwise we can think of minting DOIs and moving to PROD before CHEP...

**Comment by stwunsch** [comment]
I've received some comments these day and I'll make a PR until end of the week. I'll ping you here as soon as I've integrated the changes. Thanks!

**Comment by stwunsch** [comment]
I've integrated all changes that I got from reviews. In addition, I've tagged the release v1.0 of the related repository and linked to this release in the record.

**Comment by stwunsch** [comment]
I would love to see this going into production before CHEP. Thanks for working on this!

**Comment by stwunsch** [comment]
@tiborsimko Gentle ping! ;)

**Comment by stwunsch** [comment]
@tiborsimko Gentle ping :)

**Comment by tiborsimko** [comment]
@stwunsch DEV updated, please check the changes there, and if you give me the green light we can go PROD. We can then recheck on PROD, and finally mint DOI if everything will be fully good.

**Comment by stwunsch** [comment]
@tiborsimko Thanks for putting work into this! Here are two remaining issues:

1. The field `Characteristics` says 4 files with 12.1 MB, however, the files at the bottom sum up to only a fraction of it. To be checked!
2. The latex expression `$W+\mathrm{jets}$` is not properly compiled since the link to the explanation of `jets` seems to interfere with the compilation of the math expression. This is related to #2781 .

Here a list of typos I've found. That's a note to myself, I'll do a PR tomorrow morning.
1. "With a probably of about 20% each" -> probability
2. "Follow the respective link in the related items section for the VM or go to root.cern for instructions how to install the software locally." -> "Alternatively, go to root.cern for instructions how to install the software locally."
3. "the runtime is mainly dependend on" -> dependent

Thanks!

**Comment by tiborsimko** [comment]
Whoops, forgot to update the total size... Done now.  I have also updated those minor typos, so that you don't have to.  (This means that only the MathJax problem remains; it will be addressed separately.)  Please check and approve my PR and I'll merge and deploy later.

**Comment by stwunsch** [comment]
See above for the PR with the fixes of the typos.

**Comment by stwunsch** [comment]
Oh ok you did it already :D Perfect! Didn't expect that at this time ;)

**Comment by stwunsch** [comment]
Perfect, thanks :)

**Comment by tiborsimko** [comment]
Deployed on PROD.  Keeping this issue open in order to mint DOIs.

**Comment by stwunsch** [comment]
@tiborsimko Could you add the DOIs to the record? I would like to derive a hands-on from the record and would need the DOI to cite it properly. Not super urgent, timescale is around January. Thanks!

**Comment by stwunsch** [comment]
@tiborsimko I would need the DOI soon since I've to submit the proceedings paper for CHEP! Thanks :)

**Comment by tiborsimko** [comment]
The DOIs to use:

```
recid doi
12350 10.7483/OPENDATA.CMS.GV20.PR5T
12351 10.7483/OPENDATA.CMS.VLQO.U950
12352 10.7483/OPENDATA.CMS.EA1T.GVAF
12353 10.7483/OPENDATA.CMS.SRRA.2GON
12354 10.7483/OPENDATA.CMS.A6WH.U343
12355 10.7483/OPENDATA.CMS.QQZ2.FJZ3
12356 10.7483/OPENDATA.CMS.3YJW.P203
12357 10.7483/OPENDATA.CMS.3PB3.MNO2
12358 10.7483/OPENDATA.CMS.H95X.G286
12359 10.7483/OPENDATA.CMS.1O08.0PTD
```

**Comment by stwunsch** [comment]
Perfect, thanks!
