### ISSUE TITLE
facets: Add 'event number' -facet

### ISSUE THREAD

**Issue by JuhaTeuho** [cernopendata/opendata.cern.ch#2785]
In preparation a new search facet for the Open Data Portal. This facet is called "event number" and it searches the records for a range of events in the record file. In the current jsonschema there is a field called 'distribution.number_events' which will be used to determine the number of events in the record. Facet would look like this:

![Screenshot from 2019-08-21 12-17-31](https://user-images.githubusercontent.com/51369786/63426287-bd8b7700-c412-11e9-906b-4af2a51edf50.png)

This facet requires changes to the following files:

- cernopendata/config.py    addition of the facet itself and the filter
- cernopendata/templates/cernopendata/search.html    addition of the facet
- Possibly some other changes for filter implementation

**Comment by tiborsimko** [comment]
Closed by #2787.
