### ISSUE TITLE
CMS: Docker hub link in brings to a page requiring login

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2786]
In the docker guide (http://opendata.cern.ch/docs/cms-guide-docker),
the link to docker hub repository brings to 
https://hub.docker.com/ 
asking for a sing up/login

Should it bring to https://hub.docker.com/u/cmsopendata ?

**Comment by tpmccauley** [comment]
Yes, you are correct. Will fix.
