### ISSUE TITLE
CMS: Docker instructions for cvmfs and conddb

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#2788]
Instructions should be included for using docker with access to cvmfs and conddb (as pointed out by the CMS Open Data users at MIT).

**Comment by katilp** [comment]
@tpmccauley NB that the docker images access the conddb through frontier so if 
`process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL.db')
`
is **not** set, the db access is OK. However, it would be best to add the instructions for cvmfs in any case.
