### ISSUE TITLE
CMS: add publication links in CMS reseach guide

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2791]
Add under the "Performing an analysis" section of the CMS Guide for Research  two additional recent papers (https://arxiv.org/abs/1902.04222, https://arxiv.org/abs/1908.08542)

**Comment by jmduarte** [comment]
Also:
- https://arxiv.org/abs/1909.12285 (not yet published)
- https://arxiv.org/abs/1902.08276 (not yet published)
- https://arxiv.org/abs/1807.11916 (published in Comput Softw Big Sci 4, 6 (2020). https://doi.org/10.1007/s41781-020-00038-8)
- https://arxiv.org/abs/1704.05842 (published in Phys. Rev. D 96, 074003 (2017). https://doi.org/10.1103/PhysRevD.96.074003)

**Comment by jmhogan** [comment]
Version in PR #3585 will provide a general link to the InspireHEP page linked to the DOI -- an easy way to capture the recent papers without the page getting stale.
