### ISSUE TITLE
OPERA: publish a new release of demobbed-viewer in npm

### ISSUE THREAD

**Issue by mvidalgarcia** [cernopendata/opendata.cern.ch#2813]
Publish a new release of [demobbed-viewer](https://www.npmjs.com/package/demobbed-viewer) and not forget to point at it [here](https://github.com/cernopendata/opendata.cern.ch/blob/431325de9caffd73d55ea175a854ffa141aa1557/cernopendata/modules/theme/bundles.py#L154) when creating the npm bundle.

**Comment by tiborsimko** [comment]
I've checked and this still needs to be done. The release would eliminate the need for a custom install command in `create-instance.sh`:

```
npm install git+https://github.com/cernopendata/demobbed-viewer.git --prefix $INVENIO_INSTANCE_PATH/static
```

However the demobbed-viewer package source lives under `cernopendata` organisation, so the risk of keeping installing it from source is small.

**Comment by psaiz** [comment]
I talked to Zach, and since he also knows how this thing is done for invenio, he might be a better candidate to take care of this. Passing the ticket to him
