### ISSUE TITLE
CMS: search issues for nanoAOD-type 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2822]
For search, now 

http://opendata.cern.ch/search?page=1&size=20&q=&subtype=Derived&type=Dataset&file_type=nanoaod

finds only the muon sample. I would expect it to find also other nanoaod datasets.
This is because of
```
 "distribution": {
      "formats": [
        "root", 
        "nanoaod"
      ], 
```
in the muon json, and 

```
    "distribution": {
      "formats": [
        "root"
      ], 
```
in the others.

Currently, I can find the other samples by searching:

http://opendata.cern.ch/search?page=1&size=20&q=NanoAOD

Curiously, this search finds only one of the analysis sw records. I would expect it find both (or none), and I can't see the difference that causes it in the sw records. 

Thinking for the future, and Run2 nanoAOD release,  I'm wondering if we should use a special notation for these samples instead just nanoaod, such as custom-nanoaod.
In the current schema, they would be differentiated from the official Run2 nanoAOD by the fact that they are in the derived data, and the official ones would be in the collision data, but it would maybe help to be more explicit. 

And as mentioned by @stwunsch in https://github.com/cernopendata/opendata.cern.ch/issues/2777#issuecomment-560309189 would be good to have DOI for these derived data.

**Comment by tiborsimko** [comment]
> Thinking for the future, and Run2 nanoAOD release, I'm wondering if we should use a special notation for these samples instead just nanoaod, such as custom-nanoaod.

That would be good indeed. Perhaps `nanoaodcustom` so that the `nanoaod` prefix will remain the same; it would help to localise them next to each other in the search facet. Let's remember to update this once CMS's NanoAODs will be ready for public release.

> And as mentioned by @stwunsch in #2777 (comment) would be good to have DOI for these derived data.

The records already have DOIs minted and activated, e.g. see http://opendata.cern.ch/record/12357. Do we need to add some more to some other records?

**Comment by katilp** [comment]
OK, thanks, that's all fine then.
