### ISSUE TITLE
CMS: Update dimuon spectrum example using reduced NanoAODs

### ISSUE THREAD

**Issue by stwunsch** [cernopendata/opendata.cern.ch#2828]
Hi!

I've done a new release for the dimuon example, you can find them here:

https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/releases

Besides fixing typos, the release sets the number of threads per default to 1, so that we run reliably on all systems. Especially dockerized environments are problematic with the automatic detection of the resources from ROOT.

@tiborsimko I've seen your PR a little too late, so the release v1.2 has also the reana workflow integrated.

Could you update the files on the portal?

Thanks!
Stefan

**Comment by stwunsch** [comment]
I've changed the repo now to using tags instead of branches to be more flexibel.

**Comment by stwunsch** [comment]
You can find the PR for the record [here](https://github.com/cernopendata/opendata.cern.ch/pull/2829).

**Comment by tiborsimko** [comment]
Done via #2829.
