### ISSUE TITLE
CMS: Update AOD2NanoAODOutreachTool to v1.3

### ISSUE THREAD

**Issue by stwunsch** [cernopendata/opendata.cern.ch#2830]
Hi!

Could you please update the files of the `AOD2NanoAODOutreachTool` to v1.2? This fixes the issue [here](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/issues/1) that you cannot run the code in the VM.

Best
Stefan

**Comment by katilp** [comment]
@stwunsch Can we make v1.3 with the workflow files included? @tiborsimko the record http://opendata-dev.cern.ch/record/12340 can then be updated with the new zip. No other changes needed and no need to change DOI, because no code functionality changes.

**Comment by stwunsch** [comment]
@katilp Which workflow files do you mean?

**Comment by katilp** [comment]
@stwunsch the github workflow files that are in the master branch already:

- https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/tree/master/.github/workflows
- https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/commands.sh
- https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/argo-workflow.yaml
- https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/volumes.yaml
