### ISSUE TITLE
CMS: new VM to replace the failing one

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2847]
[cernvm-script.txt](https://github.com/cernopendata/opendata.cern.ch/files/4823748/cernvm-script.txt)
A new VM http://cernvm.cern.ch/releases/CMS-OpenData-1.5.2.ova
needs to be added to http://opendata.cern.ch/record/252 to replace 1.5.1.

Add the contextualization script record, the vm uses
- [cernvm-script.txt](https://github.com/cernopendata/opendata.cern.ch/files/4823748/cernvm-script.txt)
- the images from http://cernvm.cern.ch/releases/production/cernvm4-micro-2020.04-1.hdd

Update the instructions in http://opendata.cern.ch/docs/cms-virtual-machine-2011
- [x] 1.5.1 -> 1.5.2
- [x] update the latest tested VirtualBox to 6.0.22 
- [x] add instructions how to open the image in VirtualBox (see also https://github.com/cernopendata/opendata.cern.ch/issues/2602#issuecomment-513564792) (de-select "import disks as VDI" on initial import screen)

@jblomer Are the old VMs 1.2.0 and 1.3.0 affected as well? If needed, we can mark them deprecated.

**Comment by tiborsimko** [comment]
I haven't tested the old VMs but I think it should be sufficient to start recommending 1.5.2 and saying in general that "previous VM releases such as 1.3.0 are deprecated; please always use the latest version" somewhere in the description text in a very visible e.g. bold style.

**Comment by katilp** [comment]
Sorry, I missed that from the PR. Maybe just replace the last description paragraph:
"The earlier versions CMS-Open-Data-1.2.0.ova and Open-Data-1.3.0.ova are slc6 only. CMS-Open-Data-1.2.0.ova has a 20G virtual hard disk and a 10G cvmfs cache. CMS-Open-Data-1.3.0.ova has a 40G virtual hard disk and a 20G cvmfs cache. "
with 
"The earlier versions are deprecated, please use the latest verision"

**Comment by tiborsimko** [comment]
@katilp The `cernvm-script` contains:

```
cvm2ova -n "CMS-OpenData-1.5.1" -d 40000 -m 2048 \
-i cernvm4-micro-2018.10-1.hdd \
-u cms-user-data.txt

https://github.com/cernvm/cernvm-config/blob/master/usr/bin/cvm2ova
```
Two things:

- I guess we should use `1.5.2` there?
- `cms-user-data.txt` is exactly the same as for 1.5.1?

**Comment by jblomer** [comment]
@tiborsimko @katilp I think the older versions 1.2 and 1.3 are affected as well, it would certainly help if we can deprecate them. Note that version 1.1.2 (with the SLC5 shell) is _not_ affected and should continue to work.

For the `cernvm-script` changes: 1.5.1 needs to be replaced by 1.5.2 and the image version is now `cernvm4-micro-2020.04-1.hdd`.  The user data remains unchanged.

**Comment by tiborsimko** [comment]
@katilp FWIW I have tested the 1.5.2 image on VirtualBox 6.1.10 and everything works well. (Just for the record, no need to update docs.)

**Comment by katilp** [comment]
@tiborsimko @jblomer This VM fails to start in VirtualBox 6.0.22 (Windows10), as well as on 6.1.10
The first error is
![fail1](https://user-images.githubusercontent.com/5859918/85584773-bd19c900-b63f-11ea-9496-e21a2cca7c48.PNG)

Any advise?
I have unselected "import disk as VDI" and change to NAT.

**Comment by tiborsimko** [comment]
Works well for me in Linux importing as follows:

```console
$ wget http://opendata.cern.ch/record/252/files/CMS-OpenData-1.5.2.ova
$ vboxmanage import ./CMS-OpenData-1.5.2.ova
$ virtualbox    # ... and "Start" imported VM in GUI mode 
```

You can perhaps launch similar import command in MS Windows shell? I'll see whether I can test it...

**Comment by katilp** [comment]
Is there any alternative way on Windows than double-click on the downloaded image (this opens it in VirtualBox by default for me)? 
I cannot open it any more from "Add" on GUI as it does not list that file type in the selection menu.

I get a warning of an invalid graphics controler in the popup window fro changing the adapter whether that matters.

**Comment by katilp** [comment]
more messages if of any help

![fail3](https://user-images.githubusercontent.com/5859918/85590100-6cf13580-b644-11ea-9ba3-26e299c6559d.PNG)

**Comment by tpmccauley** [comment]
I got 1.5.2 working on Mac using VirtualBox 6.0.22 (once I unselected "Import disk as VDI").

I imported from the GUI as I don't seem to have command-line tools for VirtualBox installed.

**Comment by katilp** [comment]
So this is Windows-related trouble.... but a solution would be needed as a WLS2 user reports problems with docker with opendata and cern/slc6-base containers  on Windows and VM is a back-up for those users who cannot run docker.
I have a recipe to run docker on Windows without WLS but normal straight-forward usage would be so much better.

@jblomer Is there anything I can do to debug further?

**Comment by jblomer** [comment]
This might be network related.  I tried here with Windows 10 and VBox 6.1 and couldn't reproduce it.  Is it reproducible for you?  Could you create a snapshot of one of the failed VMs and make it available to me so that I can check the system log?

**Comment by tpmccauley** [comment]
When one starts the VM didn't it used to go right to a terminal? (I could be mistaken). I now see a CernVM User/Password prompt.

**Comment by jblomer** [comment]
@tpmccauley That would mean that the VM did not get contextualized.  Did you use [this](https://cernvm.cern.ch/releases/CMS-OpenData-1.5.2.ova) image?

**Comment by tpmccauley** [comment]
I used http://opendata.cern.ch/record/252/files/CMS-OpenData-1.5.2.ova which is the same, no? I was able to log in as user `cms-opendata` and then clicked on `CMS Shell`. Seems to work. I had to search old emails to find proper user name. I couldn't find this information on CODP pages.

**Comment by jblomer** [comment]
That's the correct (and same) image.  The image is supposed to boot directly into a logged in graphical session.  After your first boot, did it stop at the graphical login screen or was it a console login screen?

**Comment by tpmccauley** [comment]
<img width="334" alt="Screen Shot 2020-06-25 at 15 20 34" src="https://user-images.githubusercontent.com/496503/85738109-10535080-b700-11ea-8eff-4ce88e53be52.png">

**Comment by katilp** [comment]
@jblomer You can find the snapshot (if I got it right) in 
https://cernbox.cern.ch/index.php/s/wTFw8TvJQxeioGl
(it looks that the date of the VM is wrong as this file has timestamp from 7 month ago while I just did it)

**Comment by katilp** [comment]
@tpmccauley Did you check the messages during the build, and did you see anything [FAILED] as in the screenshot of https://github.com/cernopendata/opendata.cern.ch/issues/2847#issuecomment-648891235 (that was the 1st such message, others followed)?

**Comment by tpmccauley** [comment]
Nothing failed for me. It was all green OKs.

**Comment by katilp** [comment]
@jblomer OK, I got VirtualBox working again and the image fails in the same way as before  (for information, if anyone is interested https://www.tenforums.com/tutorials/139405-run-hyper-v-virtualbox-vmware-same-computer.html) .
I've made a snapshot, do you need the logs or something else?
The logs of that image are in https://cernbox.cern.ch/index.php/s/BVraWMfQB0aLsKk

**Comment by jblomer** [comment]
@katilp Thanks for the VirtualBox log!  I think the actual problem can only be found in the logs inside the machine though.  Could you perhaps zip the directory `C:\Users\koti\VirtualBox VMs\CMS-OpenData-1.5.2 1` so that I can open the VM's hard disks and check the logs?

**Comment by katilp** [comment]
@jblomer The snapshot is now available in https://cernbox.cern.ch/index.php/s/YoTTPPIrWpm6aCv

**Comment by jblomer** [comment]
@katilp Many thanks!  I got it, so you can delete it from your CERNbox if you like.  I'll let you know what I can find out.

**Comment by jblomer** [comment]
@katilp I can see that plenty of HTTP errors explain why the system could not be loaded properly from cvmfs (from the network).  The first bunch of messages is 

    Fri Jun 26 07:25:34 2020 (cernvm-prod.cern.ch) CernVM-FS: using HTTP proxy server(s) DIRECT from pac file http://cernvm-wpad.fnal.gov/wpad.dat
    Fri Jun 26 07:25:34 2020 (cernvm-prod.cern.ch) geographic order of servers retrieved from s1cern-cvmfs.openhtc.io
    Fri Jun 26 07:25:34 2020 (cernvm-prod.cern.ch) CernVM-FS: linking /root.ro to repository cernvm-prod.cern.ch
    Fri Jun 26 07:25:34 2020 (cernvm-prod.cern.ch) set nameserver to 10.0.2.3
    Fri Jun 26 07:26:50 2020 (cernvm-prod.cern.ch) set nameserver to 10.0.2.3
    Fri Jun 26 07:26:58 2020 (cernvm-prod.cern.ch) set nameserver to 10.0.3.3
    Fri Jun 26 07:27:04 2020 (cernvm-prod.cern.ch) switching host from http://s1cern-cvmfs.openhtc.io/cvmfs/cernvm-prod.cern.ch to http://s1ral-cvmfs.openhtc.io
    Fri Jun 26 07:27:04 2020 (cernvm-prod.cern.ch) switching host from http://s1ral-cvmfs.openhtc.io to s1bnl-cvmfs.openhtc.io
    Fri Jun 26 07:27:05 2020 (cernvm-prod.cern.ch) failed to fetch /cvm4/etc/python/cert-verification.cfg (hash: cd5fa0b37910c47b960e1c5854380a7adc956d39, error 9 [host returned HTTP error])

@DrDaveD There seems to be an issue with the OpenHTC servers.  Perhaps we get throttled.  Do we have a means to get monitoring or failure logs from the machines?

**Comment by DrDaveD** [comment]
Unfortunately the Cloudflare monitoring is terribly coarse-grained, and it is not of much use in debugging.  All we get out of Cloudflare is total requests & bandwidth over the last 24 hours, week, and month for all traffic with the whole domain.

Aren't we supposed to get more details on http errors in recent clients?  Is the client version too old for that?

I have not heard of Cloudflare doing any throttling.  I would sooner suspect ISP problems if the issue isn't terribly widespread.  We have been pretty steadily having around 30 million requests and 4TB data per day over the last month.  The hit rate has been quite good, over 90% on both.

**Comment by jblomer** [comment]
Ok, thanks for the information!

@katilp Is this issue reproducible for you?  In this case I can give you a VM image that produces more verbose output.

I'll anyway update the client in the images and I can also set the CERN stratum 1 as a backup.

**Comment by katilp** [comment]
@jblomer yes and no. It fails every time, but  I observed that this time the first fail is in Permit User Sessions, while earlier it was in a different step https://github.com/cernopendata/opendata.cern.ch/issues/2847#issuecomment-648891235

**Comment by DrDaveD** [comment]
@jblomer please do not set the CERN stratum 1 as a direct backup for large numbers of clients in an image that can take a long time to update.  The WLCG Web Proxy Auto Discovery already includes the backup proxies at CERN & FNAL as backups when at a grid site.  If any backup needs to be set for Cloudflare I'd rather do it there so we can quickly change it for everybody, and I'd rather send them to the backup proxies than to stratum 1s.

**Comment by katilp** [comment]
@jblomer The most recent is in (the first fail):

![vm152-f1](https://user-images.githubusercontent.com/5859918/86260040-0d9fa200-bbbd-11ea-9153-021fd3805fba.PNG)

I'm not sure any more if it is always in the same place but it fails always.

**Comment by jblomer** [comment]
@katilp I created an image that should give us better debugging information: https://cernvm.cern.ch/releases/CMS-OpenData-1.5.2-Debug.ova

Could you try with this one and, if it also fails, once more upload the VM to CERNBox?

**Comment by katilp** [comment]
This gives right at the start 
![vm152debug1](https://user-images.githubusercontent.com/5859918/86271959-1fd60c00-bbce-11ea-86ad-97ec6780e1d6.PNG)
but no fails at boot, and it starts without problems 🎉 
Was there some other change than the debugging info?

**Comment by jblomer** [comment]
Great!  I updated the cvmfs client in the VM to get more verbose logs, but if it fixes the original problem, even better.

I fixed the remaining issue at the VM start as well and put it together as 1.5.3 release:
https://cernvm.cern.ch/releases/CMS-OpenData-1.5.3.ova

That's the same as 1.5.2 except for the base image, which now uses
https://cernvm.cern.ch/releases/ucernvm-images.2020.07-1.cernvm.x86_64/ucernvm-v4prod.2020.07-1.cernvm.x86_64.hdd

Cheers,
Jakob

**Comment by katilp** [comment]
Thanks! That works fine. @tiborsimko I'll make a new PR to address the name change in the record and in the docs. Will we replace 1.5.2 with this or add this to the list?

**Comment by katilp** [comment]
New VM is now available also for 2010 data in 

https://cernvm.cern.ch/releases/CMS-OpenData-1.1.4.ova

created from context
https://raw.githubusercontent.com/cernvm/public-contexts/master/cms-opendata.context

NB the record http://opendata.cern.ch/record/249 refers to the old slc5 VM version without CMS shell, there's no context record for the more recent 2010 VMs 
http://opendata.cern.ch/search?page=1&size=20&type=Environment&subtype=VM&experiment=CMS

**Comment by tiborsimko** [comment]
@katilp We'll have to add 1.5.3 to the list. If there is no text to update, I can transfer the file update checksums etc.

**Comment by katilp** [comment]
Update 2011 vm records with 1.5.3 in cms-tools-vm-image-Run2011A.json
- [ ] new description for the vm record 252
- [ ] new context script record 257 (new record number +1 from 1.5.2)

Update the instructions in http://opendata.cern.ch/docs/cms-virtual-machine-2011
- [ ] 1.5.2 -> 1.5.3
- [ ] update the latest tested VirtualBox to 6.1.10 

Update 2010 vm records in cms-tools-vm-image.json
- [ ] new description for the vm record 250
- [ ] new context script record 248 (new record number -1 from 1.0.1 - the most recent do not have one)

Update the instructions in http://opendata.cern.ch/docs/cms-virtual-machine-2011
- [ ] 1.1.2 -> 1.1.4
- [ ] update the latest tested VirtualBox to 6.1.10

**Comment by tpmccauley** [comment]
I tried both new images with VirtualBox 6.1.12 on my Mac (Catalina 10.15.5) and :+1:
