### ISSUE TITLE
CMS: correct Phase2 -> Run2 in CMS ML records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2852]
As notified by @felicepantaleo, a correction Phase 2 - Run2 is needed in records
http://opendata.cern.ch/record/12303 (MC)
http://opendata.cern.ch/record/12300 (MC)
http://opendata.cern.ch/record/12302 (MC)
http://opendata.cern.ch/record/12301 (MC)
http://opendata.cern.ch/record/12310 (SW)
http://opendata.cern.ch/record/1807 (condition data)

in all relevant fields:
"abstract"'s "description", "date_created", "run_period" and "title_additional"
The simulated data corresponds to 2018.

In http://opendata.cern.ch/docs/cms-guide-for-condition-database
change:
- For Run2 Montecarlo data -> For 2016 Montecarlo data
- For Upgrade Montecarlo data -> For 2018 Montecarlo data

No changes needed for http://opendata.cern.ch/record/12320 (ML sample)

@tiborsimko for the file location, do we leave the files where they are or move them as well?
If we move, the correct location would be
- /eos/opendata/cms/MonteCarloUpgrade -> /eos/opendata/cms/MonteCarlo2018 (new area)

**Comment by katilp** [comment]
@tiborsimko Should we change the internal json file names or do we leave them as they are?
If we follow the current logic:
- the contents of cms-*-Phase2-datascience.json should be included in cms-*-Run2-datascience.json 
- this concerns cms-condition-data-Phase2-datascience.json  cms-derived-Phase2-datascience.json  cms-simulated-datasets-Phase2-datascience.json  cms-tools-Phase2-datascience.json

**Comment by fwyzard** [comment]
the GEN-SIM-DIGI-RAW dataset has the same issue: http://opendata.cern.ch/record/12301 .

**Comment by fwyzard** [comment]
Also, the description of GEN-SIM-DIGI-RAW dataset (http://opendata.cern.ch/record/12301) states that

> The input dataset to this step is in Simulated dataset TTToHadronic_TuneCP5_13TeV-powheg-pythia8 in FEVTDEBUGHLT format

while the input is actually in the GEN-SIM format (the link is correct, only the description is wrong).

While the description for the FEVTDEBUGHLT dataset (http://opendata.cern.ch/record/12303) states that

> The input dataset to this step is in Simulated dataset TTToHadronic_TuneCP5_13TeV-powheg-pythia8 in GEN-SIM format

while the previous step was the GEN-SIM-DIGI-RAW dataset (both the description and the link should be updated).
