### ISSUE TITLE
CMS: add the SW record for CASTOR analysis

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2854]
The usage example for CASTOR data is currently [a twiki page](https://twiki.cern.ch/twiki/bin/view/CMSPublic/CASTOROpenData2010) linked from [the relevant records](http://opendata.cern.ch/search?page=1&size=20&q=castor)

@hvanhaev has now prepared a github repository in
- https://github.com/cms-legacydata-validation/CastorDataValidation

I have a github workflow testrun implemented in my fork in
- https://github.com/katilp/CastorDataValidation

@caredg Do you agree that we add the github workflow and then move the  the repo to cms-opendata-validation? 

A SW record can be prepared for this 
- json name: - either in a separate cms-validation-code-Castor2010.json (*) or in the existing cms-validation-code-Run2010B.json
- a basic validation sw record structure is http://opendata.cern.ch/record/460

(*) In agreement with a reflection **github repository name -> json file naming** done earlier (a mail exchange 16 May 2019

- cms-opendata-validation  -> "cms-validation-code-..."
- cms-opendata-analyses/*Tool  -> "cms-tools-.."
- cms-opendata-analyses/[real analysis example] -> "cms-analysis-..."

**Comment by caredg** [comment]
@katilp, I think this is ok.  Adding your github workflow to the repository is a good thing too.

**Comment by katilp** [comment]
To do:
- upload the CMSSW_4_2_8_lowpupatch1 to  https://hub.docker.com/u/cmsopendata
- update the docker instructions with this version

**Comment by katilp** [comment]
@hvanhaev The SW record has a notion of licence. Do you agree of the proposed one (GNU General Public License (GPL) version 3)? You can pick up one for the repository by:

> Go to your repository
> Add a new file by clicking the blue plus icon
> Type the file name as License.txt or License.md after which a license picker will show up. Then you can choose the type of license.

Thanks!

**Comment by hvanhaev** [comment]
Dear Kati,

Sure, I added the GPL v3 license to the repository.

Cheers,
Hans


On 3 Aug 2020, at 15:47, Kati Lassila-Perini <notifications@github.com<mailto:notifications@github.com>> wrote:



@hvanhaev<https://github.com/hvanhaev> The SW record has a notion of licence. Do you agree of the proposed one (GNU General Public License (GPL) version 3)? You can pick up one for the repository by:

Go to your repository
Add a new file by clicking the blue plus icon
Type the file name as License.txt or License.md after which a license picker will show up. Then you can choose the type of license.

Thanks!
