### ISSUE TITLE
Improve documentation/webpage information on how to get help

### ISSUE THREAD

**Issue by clelange** [cernopendata/opendata.cern.ch#2855]
I recently had someone ask how one can report issues or even generally get help when using the Open Data Portal, and when I checked myself I found it surprisingly difficult to find information on that. 
There is a "Contact" link at the bottom, which just links to the general email support list, but there is no general "help" link nor documentation. I would suggest to add a dedicated and easily discoverable "Help page" that lists more detailed information (could also link to this repository) and also links to https://opendata-forum.cern.ch/
One could also think about having experiment-specific support addresses.

**Comment by tiborsimko** [comment]
Yes, it is good to centralise user questions in the direction of the forum, now that we have it... We can also amend the top banner menu in this sense. A good first issue for @ParthS007 that will be joining our team soon.

**Comment by katilp** [comment]
@tiborsimko @ParthS007 Is this something we could add to the release now?

**Comment by tiborsimko** [comment]
Yes, @ParthS007 is currently away on an Invenio sprint, so I'll take care of this.
