### ISSUE TITLE
Add "Workflow" key word in the Software type field

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2867]
For the SW records having ReANA or github workflow, add a keyword "Workflow"
- [x] AOD2NanoAODTool  http://opendata.cern.ch/record/12340 (github wf in the code repo, pr done)
- [x] Htautau http://opendata.cern.ch/record/12350 (reana wf in the code repo)
- [x] Hl4 http://opendata.cern.ch/record/5500 (reana wf in https://github.com/reanahub/reana-demo-cms-h4l, maybe link to it from the code repo?)
- [x] the new castor record pr #2859 (github wf in the code repo)
- [x] the trigger example http://opendata.cern.ch/record/5004 (github wf in the code repo)
- [ ] rereco wf https://github.com/reanahub/reana-demo-cms-reco/ but it does not have a sw record yet.
  

@caredg Will you update http://opendata.cern.ch/record/5004 with what is now in 
https://github.com/cms-legacydata-analyses/TriggerInfoTool or will it be a record of its own?

**Comment by caredg** [comment]
Yes, I will have to make sure everything in the new Trigger repository works, then I will move it (to replace the old one) and update the record 5004 to point to the new one.

**Comment by katilp** [comment]
@caredg Thanks! Ping me when you've updated so I can make the PR from my fork for the github workflow. Or if you prefer, I can make it now, just let me know.

**Comment by caredg** [comment]
@katilp, I have moved the new TriggerInfoTool repository the cms-opendata-analyses organization.  The master branch is working for 2011, but I have not yet created a specific 2011 or 2010 branches yet.  I will do that this weekend and change the specifics details in the instructions (and GTs) for these data epochs.  There is a dev branch for the work that is still going, but that is another story.  You could safely push or PR to the master.  Once I am done with this (it should not take long) I will make the PR for the CODP record.

**Comment by caredg** [comment]
Finished all the checks on the new TriggerTools repo.  The records update will be tracked in #2878

**Comment by katilp** [comment]
Closing, I'll follow up setting up a proper rereco record on the portal afterwards.
