### ISSUE TITLE
Update trigger examples

### ISSUE THREAD

**Issue by caredg** [cernopendata/opendata.cern.ch#2878]
Update trigger repository in the 2010 and 2011 records (as mentioned in #2867)
http://opendata.cern.ch/record/5003
http://opendata.cern.ch/record/5004

**Comment by katilp** [comment]
@caredg How will this go: does what is  in https://github.com/cms-opendata-analyses/TriggerInfoTool replace what is now in https://github.com/cms-opendata-analyses/trigger_examples/tree/master/TriggerInfo/TriggerInfoAnalyzer (to which the current record points to)? We can consider TriggerInfoTool as an enhancment of TriggerInfo/TriggerInfoAnalyzer, right?

In this case, would we update the existing records 5003 and 5004, or is the functionality so much changed that we should have  new records. @tiborsimko What's the guideline with this?

**Comment by tiborsimko** [comment]
From the DOI point of view, we guarantee to serve the same files, so if only the GitHub location changed, we can simply update the link field and be done. If also content changed, then will there be a new release? E.g. old one was `trigger_examples-10.0.0.tar.gz`, and a new one will be `trigger_examples-10.0.1.tar.gz` or some such? Then we could add it to the same record. If you'd like to change the tarball name and change something major inside, then it is better to create a completely new record.

**Comment by caredg** [comment]
I do not think the new repository has any major change.  It is basically the same code, organized differently, so it is easier to follow (hopefully).  Then, unless there is a problem with keeping the same filename for the tar balls, I will just update the records with just a couple of things:
1. Mention the docker instructions (so far there is only a mention of the VM)
2. Update the link to the new repository

**Comment by katilp** [comment]
Sounds good to me then, is it OK for you @tiborsimko ?

**Comment by tiborsimko** [comment]
> Sounds good to me then, is it OK for you @tiborsimko ?

The new tarball is called `TriggerInfoTool-11.1.0.tar.gz`, which is not ideal, since both the name and the major version change, so people may be wondering about connections between the two...But I'll attach it "as is" anyway.

**Comment by caredg** [comment]
> > Sounds good to me then, is it OK for you @tiborsimko ?
> 
> The new tarball is called `TriggerInfoTool-11.1.0.tar.gz`, which is not ideal, since both the name and the major version change, so people may be wondering about connections between the two...But I'll attach it "as is" anyway.

Thanks Tibor.  Ok, but couldn't the name be changed or it has to have the name of the repository? Anyway, whatever works.
