### ISSUE TITLE
CMS: architecture clash in CMS-OpenData-1.1.4

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#2886]
I attempted to build some code in 2010 VM but ran into the SCRAM warning
`You are trying to compile/build for architecture slc5_amd64_gcc434 on SLC7 OS which might not work`

It in fact did not work, even for a simple DemoAnalyzer (I had the same error for event display file production code). I've added a screenshot below. I am using VirtualBox 6.1.12 on OSX 10.15.5[
<img width="953" alt="Screenshot 2020-09-16 at 14 51 19" src="https://user-images.githubusercontent.com/496503/93347007-84e3ea00-f82c-11ea-9f77-5edb037887d3.png">
](url)

**Comment by katilp** [comment]
It is not that you're in the slc7 shell (opens from the icon from the botton) and not in the slc5 shell (opens from the destop icon)?

**Comment by tpmccauley** [comment]
:man_facepalming: 

yes it is. thanks.
