### ISSUE TITLE
CMS: change docker image references from Dockerhub to CERN GitLab CMS Cloud 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2887]
As suggested by @clelange, change the reference to the CMS open data docker images to avoid download  (or other) limits on dockerhub.
We could point to https://cmssw-docker.web.cern.ch/available-images or https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry (this page is slow to load)

Concerns http://opendata.cern.ch/docs/cms-guide-docker and requires changing
- [x] from dockerhub  -> from the container registry 
- [x] container names `cmsopendata/cmssw_5_3_32` and `cmsopendata/cmssw_4_2_8` in the docker commands
- [x] the example outputs

The changes need to be propagated to the workshop material as well

**Comment by clelange** [comment]
Mind that https://cmssw-docker.web.cern.ch/available-images is not yet accessible outside CMS. We could publish it though if needed.

**Comment by katilp** [comment]
Would it be useful / possible to limit the images visible outside to those relevant to OD?

**Comment by clelange** [comment]
> Would it be useful / possible to limit the images visible outside to those relevant to OD?

In the long run, yes, but this would probably have to be a separate page. For now, I would suggest to manually maintain the names of the 2-3 images on the portal (pointing to the registry directly).

**Comment by katilp** [comment]
OK, For the instructions, if no tag, `:latest ` is the default, right?

**Comment by katilp** [comment]
Closing as this has been addressed in the docker guide updates for the 2015 release.
