### ISSUE TITLE
orcid: add orcid ids globally

### ISSUE THREAD

**Issue by ArtemisLav** [cernopendata/opendata.cern.ch#2888]
ORCID iDs can be added retrospectively for all records that have individuals as authors. Currently they are only present in a subset or records. 

We should first establish: 
- how many records there are with individual authors
- how many of those records have an ORCID iD

**Comment by tiborsimko** [comment]
Here is the list of all individual authors with and without ORCIDs, for both "data records" and for all records including lengthy author lists.

Each line shows an author with his/her affiliation and his/her ORCID, followed by the given record URL and given source file to edit where this information appears.

[author-information-data-records.txt](https://github.com/cernopendata/opendata.cern.ch/files/5333665/author-information-data-records.txt)

[author-information-all-records.txt](https://github.com/cernopendata/opendata.cern.ch/files/5333663/author-information-all-records.txt)

**Comment by tiborsimko** [comment]
Example:

```
Guyon, Isabelle --- ChaLearn --- MISSING_ORCID --- http://opendata.cern.ch/record/329 --- cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json
Haapalehto, Matias --- MISSING_AFFILIATION --- MISSING_ORCID --- http://opendata.cern.ch/record/5104 --- cernopendata/modules/fixtures/data/records/cms-validation-code-jet-tuple.json
Hategan, Mihael --- MISSING_AFFILIATION --- MISSING_ORCID --- http://opendata.cern.ch/record/555 --- cernopendata/modules/fixtures/data/records/cms-tools-ispy.json
Hirvonsalo, Harri --- MISSING_AFFILIATION --- MISSING_ORCID --- http://opendata.cern.ch/record/460 --- cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
```

@ArtemisLav Will this do? Would you prefer another format?

**Comment by ArtemisLav** [comment]
I don't think it can be done manually for the author lists .. is there another way?

Regarding the affiliations, where should this information come from? I would be a bit hesitant to add those without checking with the authors as they might have switched even if they have added one in their ORCID or INSPIRE profile.

**Comment by tiborsimko** [comment]
WRT past affiliations, yes one would have to check very carefully each case.  However we can just add a few example RORs for some of the authors that we know about easily and that appear frequently...

For adding ORCIDs, this would be OK without too much additional checks, provided INSPIRE proflie has it and/or provided ORCID public profile page points to the right person.

WRT big collaboration lists, this was generated via a script from INSPIRE, I believe...Do you still have it around? We could commit to `data-curation` repository. Fully agree about not doing those manually.

**Comment by ArtemisLav** [comment]
Here is a file with a summary of the ORCID matching: 
[cod-authors-orcid-matching.txt](https://github.com/cernopendata/opendata.cern.ch/files/5347312/cod-authors-orcid-matching.txt)

I searched for each author in the INSPIRE author profiles and the ORCID database. ORCID iDs were matched if the author had added it to their INSPIRE profile (strong match) but also if there was **only one** name matching in the ORCID registry (weaker match).
