### ISSUE TITLE
ror: add to schema 

### ISSUE THREAD

**Issue by ArtemisLav** [cernopendata/opendata.cern.ch#2891]
- Add new field for ROR IDs to the `record-v1.0.0.json` schema
- It should go under the `authors` property

**Comment by ArtemisLav** [comment]
The simplest solution would be the following:

``` 
"authors": {
  "items": {
    "properties": {
      "affiliation": {
        "description": "The affiliation of the author",
        "type": "string"
      },
      "ror": {
        "description": The ROR ID for the author's affiliation",
        "type": "string"
      },
      "ccid": {
        "description": "The author's CCID",
        "type": "string"
      },
      "inspireid": {
        "description": "The author's inspire ID",
        "type": "string"
      },
      "orcid": {
        "description": "The author's ORCID iD",
        "type": "string"
        },
      "name": {
        "description": "The name of the author",
        "type": "string"
      }
    },
    "type": "object"
  },
  "type": "array"
}
```


Another option would be to nest `ror` under `affiliation`. 

What do you think @tiborsimko ?

**Comment by tiborsimko** [comment]
1) This seems perfectly OK to me. However, it could happen that a person is associated with more than one institution... So perhaps affiliation and ROR should be lists?  That would however be a bigger change; for now, for a Minimum Viable Product, the above will perfectly do.  (Unless we already have a case of an author with multiple affiliations.)

2) In analogy with `ccid`, `inspireid`, `orcid`, what about calling the new property `rorid`?

3) Can you please also fix the case (inspire -> INSPIRE) while we are at it?

**Comment by ArtemisLav** [comment]
> In analogy with ccid, inspireid, orcid, what about calling the new property rorid?

Actually, I thought about this a bit more and we could also leave it more generic as `orgid` as in 'organisational identifier'? I thought in case someone wants to use a GRID or something else. DataCite call it `affiliationIdentifier` in their schema which is another option.

**Comment by tiborsimko** [comment]
It's a choice between nested outlook, such as:

```json
[
    {
	"affiliation_id": "1",
	"affilation_type": "ror"
    },
    {
	"affiliation_id": "2",
	"affilation_type": "grid"
    }
]
```
and flattened one, such as:

```
[
	"affiliation_orcid": "1",
	"affiliation_grid": "2"
]
```

for each author.

Since we already have the second flat structure regarding CCID/INSPIREID/ORCID, let's perhaps simply add the new `rorid` alongside?

**Comment by tiborsimko** [comment]
ROR has been well added to the schema in the above PRs.
