### ISSUE TITLE
CMS: record for the revised CMS open data policy

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2892]
The CMS Open data policy was revised and approved in September 2020. The new version is available in https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/ShowDocument?docid=6032

Create a new record as w.r.t 
- http://opendata.web.cern.ch/record/411
- http://opendata.web.cern.ch/record/414

and add a reference to the new record in the old ones

**Comment by katilp** [comment]
@tiborsimko We  have this as well

**Comment by caredg** [comment]
I was just wondering about this due to the upcoming LHCP talk where I will mention the timelines.  But I see that the request has been already made.  Thanks @katilp and @tiborsimko

**Comment by caredg** [comment]
Hi @tiborsimko, do you think we can bump up this request in the priority list?   Now with the workshop ahead, I am sure people will be looking at the policy and it is becoming a very old document.  Thanks a lot.
