### ISSUE TITLE
ror: add to a sample of records for as an MVP

### ISSUE THREAD

**Issue by ArtemisLav** [cernopendata/opendata.cern.ch#2894]
* After the schema is updated we can add ROR IDs to a few records to start

**Comment by ArtemisLav** [comment]
A ROR ID looks like so: `https://ror.org/00mkhxb43`. Should we add the entire thing in the metadata or just `00mkhxb43`? We have been doing the latter for the ORCID iDs, but it might not be the best option.

**Comment by ArtemisLav** [comment]
@tiborsimko which standardisation should the affiliations follow? INSPIRE institutions, ROR/GRID database, other? I noticed there are some that follow INSPIRE (e.g. `U. Edinburgh`) and others that don't (e.g. `Physics Department, Royal Holloway, University of London, UK`). 

I could normalise a bit while I'm working on this.

BTW, a couple of cases have 3 affiliations (for one author): `LAL, IN2P3/CNRS & University Paris-Sud, France` (not standardised either).

**Comment by tiborsimko** [comment]
> Which standardisation should the affiliations follow? INSPIRE institutions, ROR/GRID database, other?

No strong feelings... I think that following INSPIRE as the well-known information source in our field would be probably the most natural.

> I could normalise a bit while I'm working on this.

That would be great :+1: 

> BTW, a couple of cases have 3 affiliations (for one author)

... and unfortunately our data model currently does not support having multiple affiliations for an author :worried: Changing this would be a bigger change, so perhaps keeping the current technique ("aff1 & aff2 & aff3") might do... And we could refactor later.

**Comment by tiborsimko** [comment]
A ROR ID looks like so: https://ror.org/00mkhxb43. Should we add the entire thing in the metadata or just 00mkhxb43?

**Comment by ArtemisLav** [comment]
> No strong feelings... I think that following INSPIRE as the well-known information source in our field would be probably the most natural.

I think the only issue I see with this is organisations outside the discipline which might not be indexed. I found one case in the affiliations we currently have (Lapland University of Applied Sciences) which isn't in INSPIRE. So either we say that we are fine with some exceptions or we go with a different database. 

> (Also, leaving FQDN out would be nicely harmonious with other IDs we store, such as ORCIDs or INSPIREIDs, as you mentioned.)

As long as this does not create any issues with making the IDs actionable later, I agree.

> ... and unfortunately our data model currently does not support having multiple affiliations for an author 😟 Changing this would be a bigger change, so perhaps keeping the current technique ("aff1 & aff2 & aff3") might do... And we could refactor later.

So, for multiple affiliations it would look like this then: 
``"affiliation":` "Orsay, LAL; Paris, IN2P3; Orsay",``
``"rorid": "046w3ze59; 03fd77x13; 028rypz17"``

**Comment by tiborsimko** [comment]
> So either we say that we are fine with some exceptions or we go with a different database.

OT1H, do you have a feeling how many exceptions (i.e. institutes not in INSPIRE) there are? Perhaps not so many, since most of particle physics data co-authors should be already covered by some known institute... And we could theoretically add the rest to INSPIRE should some institute come up a lot.

OTOH, do you have a feeling how many physics institutes we might be having to add to that different database? Since I guess  GRID/ROR won't be totally complete either...

This may inform about the decision which one to take.

> So, for multiple affiliations it would look like this then

Yes, exactly. It is not ideal, but would do for now...

**Comment by ArtemisLav** [comment]
> OT1H, do you have a feeling how many exceptions (i.e. institutes not in INSPIRE) there are? Perhaps not so many, since most of particle physics data co-authors should be already covered by some known institute... And we could theoretically add the rest to INSPIRE should some institute come up a lot.

Re: exceptions, I only found the one I mentioned above and `ChaLearn` which is a different type of organisation and I guess wouldn't be in any of those databases. 

> OTOH, do you have a feeling how many physics institutes we might be having to add to that different database? Since I guess GRID/ROR won't be totally complete either...

So far I was able to find all of them and as far as I know the main issue with ROR is the granularity (it's more high-level than INSPIRE), and for those cases we could just use the 'parent' organisation.

By my count, there are only 9 authors with a known affiliation in our records, so it's a very small number. Generally I would be keen to use INSPIRE so that we remain in the CERN 'ecosystem'. What I could do about Lapland is to try and match the structure of the database as much as possible.

**Comment by tiborsimko** [comment]
Fully agree.  (And, besides, we also have those complete collaboration author lists, and there it is INSPIRE affiliation naturally...)
