### ISSUE TITLE
records: update ATLAS 13 TeV release ROOT files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2926]
Update ATLAS 13TeV release ROOT files with latest versions.

**Comment by artfisica** [comment]
Thank you very much, @tiborsimko ! :)

**Comment by tiborsimko** [comment]
@artfisica Sorry for the long delay! I'll be registering the DOIs later today, I'll let you know when everything is finished.

**Comment by tiborsimko** [comment]
@artfisica The DOIs are active now. I'll also reply on the old email thread.
