### ISSUE TITLE
search: exact dataset title

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2930]
Revise tokenisers and analysers so that exact searches would work.

For example, for the dataset http://opendata.cern.ch/record/1, the following query does not give anything:

```
/BTau/Run2010B-Apr21ReReco-v1/AOD
```

even though this is exact match with record title.

It even leads to *Error: Invalid query", most probably due to the use of slashes.

The users have to use double quotes:

```
"/BTau/Run2010B-Apr21ReReco-v1/AOD"
```

which finds the record.

However, forcing the use of double quotes is not very user-friendly.

Let's see if we can amend Elasticsearch mappings and analysers so that exact matches will be returned directly.

**Comment by utkarsh147-del** [comment]
BTau//Run2010B-Apr21ReReco-v1//AOD

By putting double slash,maybe it can work

**Comment by tiborsimko** [comment]
@ParthS007 When changing ES7analysers,tokenisers, in addition to the full version "/BTau/Run2010B-Apr21ReReco-v1/AOD", please pay atenttion that the the whole thing should be treated as one word (with `/` being a normal character), but also the string should get parsed into substrings like "BTau" (with `/` being a separator), so that when user search for the word BTau, they would also find this title.
