### ISSUE TITLE
devops: ship logs to central monitoring

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2933]
Instead of OpenShift volatile storage, use central monitoring for logs.

Implement 3-month retention as per OC11.

**Comment by diegodelemos** [comment]
If we would use the new [Invenio Helm](https://github.com/inveniosoftware/helm-invenio) we would get a [Logstash instance instance inside the cluster](https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/services/logstash.yaml) and [its configuration](https://github.com/inveniosoftware/helm-invenio/blob/76f4146375dec8b1e1e52d75ecea26fb83e78829/invenio/templates/configuration.yaml#L135-L252) ready. The logs would be shipped from the application to logstash through a [filebeat sidecar](https://github.com/inveniosoftware/helm-invenio/blob/4509f63dfb2a203d323565b4c1e56217a392bef7/invenio/templates/application.yaml#L142-L163).

**Comment by psaiz** [comment]
The sidecar that Diego mention is in place for the nginx logs. 
Note that the output of the containers is also sent to the central monitoring by our openshift colleagues.
Therefore, I have the feeling that this ticket can be closed
