### ISSUE TITLE
nginx/uwsgi: configuration

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2934]
Reverse proxy leads to several problems when serving files, see https://github.com/cernopendata/cernopendata-client/issues/98#issuecomment-732281262

Check uwsgi configuration for direct file serving.

Check nginx configuration for reverse proxy from EOSPUBLIC.

**Comment by wahaj** [comment]
Can I get assigned to this ?

**Comment by tiborsimko** [comment]
We can close this issue. Nginx and uWSGI configurations were improved e.g. in #3331 and #3334. This alleviated the problems, but they still remain at times. We can look into improving things some more and also test an alternative file serving technique (#3464).
