### ISSUE TITLE
records: update ATLAS 13 TeV description text 

### ISSUE THREAD

**Issue by artfisica** [cernopendata/opendata.cern.ch#2936]
Hi!

We at the ATLAS Open Data project, want to update the description text in the following records:

http://opendata.cern.ch/record/15000
http://opendata.cern.ch/record/15001
http://opendata.cern.ch/record/15002
http://opendata.cern.ch/record/15003
http://opendata.cern.ch/record/15004
http://opendata.cern.ch/record/15005
http://opendata.cern.ch/record/15006
http://opendata.cern.ch/record/15007

All the eight records have the same description (for simplification)
We should have the final text by Monday.

**Comment by artfisica** [comment]
Hi!

We have the final text to replace the content of the mentioned records:

---

# Description
The ATLAS Collaboration has released 10/fb of collision data at a centre-of-mass energy of 13 TeV from the 2016 data-taking period, intended solely for educational purposes, to the general public. This set of real data is accompanied by matching simulated samples of Standard Model processes and a selection of Beyond the Standard Model signals.

# How were these data selected?
Events selected contain at least 1 lepton (electron or muon) or at least 2 photons. Both real data and simulated samples are subjected to a loose event preselection to reduce the processing time by reducing the overall number of events that have to be analysed. The preselection consists of a set of object selection criteria and a subsequent event selection acting on these preselected objects.

# How can you use these data?
This dataset is provided by the ATLAS Collaboration only for educational purposes [maybe with examples] and is not suited for scientific publications. [Later we could possibly add here something about example analyses documented on Zenodo or similar.]
You can access these data through the ATLAS Virtual Machine and Software.
More documentation is available at http://opendata.atlas.cern/release/2020/documentation/

# Disclaimer
The open data are released under the Creative Commons CC0 waiver. Neither ATLAS nor CERN endorses any works produced using these data, which is intended only for educational use. All releases will have a unique DOI that you are requested to cite in any (non-scientific) applications or publications.

---

**Comment by tiborsimko** [comment]
> [maybe with examples]

I'd leave this out until we have examples really included.

> [Later we could possibly add...]

Is there something we can refer to already now? If not, I'd leave it out.

> Disclaimer...

I'm not sure about this one. There are three warnings about educational/non-scientific purposes already, one in Description and two in Usage sections. Do we really need to add two more in the Disclaimer section as well? If so, what about the other hundred or so of ATLAS records on the portal? (They are also for meant for education purposes mostly.) I think it would be preferable to keep the current standard, generic disclaimer, that applies to all records and situations.

**Comment by tiborsimko** [comment]
To explain my last point better, please see [Open Data definition](https://opendatahandbook.org/guide/en/what-is-open-data/):

```
For example, ‘non-commercial’ restrictions that would prevent ‘commercial’ use, or 
restrictions of use for certain purposes (e.g. only in education), are not allowed.
```

**Comment by artfisica** [comment]
Hi @tiborsimko, 

Sorry for the delay, and sorry also because the text between the square brackets should not be there, I copy&paste a non-final version.

Thanks for the feedback. I understand your point; I also shared the same view to the group a couple of weeks ago.
I will need to come back to you on this after I propagate your observations.
This was a text decided by several members inside the ATLAS to reinforce that idea of the educational/non-scientific of the current ATLAS Open Data.

Trying to reply to your question, ideally, it would be good to have the same disclaimer on ALL the ATLAS data records in the CERN Open Data.

So, I was looking into the CERN Open Data repo where this is defined, and I found a template that constructs that message.
Can I ask, only from the technical point of view:
the use of a new version of the Disclaimer in all the records looks easier to apply that just on some of them, right?

cheers,
Arturo

**Comment by artfisica** [comment]
Hi @tiborsimko,

Regarding the text before the Disclaimer, I mean, the:

# Description
# How were these data selected?
# How can you use these data?

Because that text is included in the individual records (i.e. it's created independently of the Disclaimer)
is OK for you if I create a PR for the update of those fields for those records?

Files that I am referring are:
```opendata.cern.ch/cernopendata/modules/fixtures/data/records/atlas-2020-*.json```

Thanks for your feedback,
Arturo

**Comment by artfisica** [comment]
Hi @tiborsimko, All,

I created PR [#3094](https://github.com/cernopendata/opendata.cern.ch/pull/3094), following the guidelines.
Hopefully, it is correct.

As usual, any feedback is welcome.

Thanks!
Arturo

**Comment by tiborsimko** [comment]
Hi @artfisica, thanks for the PR, it is now merged and deployed. Shall we close the issue?

**Comment by artfisica** [comment]
Hi @tiborsimko, yes, I took a look at each of them, and they look good. Thanks again!

I also notice that some URL in the old 8 TeV samples need to be replaced. But this is a matter for another specific issue.

This one can be close, and thank you on behalf of the team also.

Cheers,
Arturo

**Comment by tiborsimko** [comment]
@artfisica Thanks, closing this one then, and see you soon in that about-to-be-born 8 TeV issue :wink:
