### ISSUE TITLE
CMS: change description for the pp reference for HI, add tag

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2943]
Change "reference pp data" to 
"These pp data have are at the same centre-of-mass energy and have a similar trigger menu to those in PbPb collisions. "

Add a keyword "Heavy-ion physics" to all PbPb and ref pp datasets and to the list of validated runs:

```
"keywords": [
      "heavy-ion physics"
    ],
```

**Comment by tiborsimko** [comment]
- pp -> proton-proton ?
- keywords are usually all lower-case, so "heavy-ion physics"?
