### ISSUE TITLE
CMS: update the docker guide with the HI images

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2953]
- Add the two HI images to the docker guide
- Update "As described in this GitHub repository," to point to  https://gitlab.cern.ch/cms-cloud/cmssw-docker#running-the-standalone-version (although maybe this link is not necessary as the instructions in this page are enough)
- NB the two HI images are not (yet) in dockerhub but in
   - [gitlab registry folder for 4_4_7](https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry/eyJuYW1lIjoiY21zLWNsb3VkL2Ntc3N3LWRvY2tlci9jbXNzd180XzRfNy1zbGM1X2FtZDY0X2djYzQzNCIsInRhZ3NfcGF0aCI6Ii9jbXMtY2xvdWQvY21zc3ctZG9ja2VyL3JlZ2lzdHJ5L3JlcG9zaXRvcnkvODIzNy90YWdzP2Zvcm1hdD1qc29uIiwiaWQiOjgyMzd9)
  - [gitlab registry folder for 3_9_2_patch5](https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry/eyJuYW1lIjoiY21zLWNsb3VkL2Ntc3N3LWRvY2tlci9jbXNzd18zXzlfMl9wYXRjaDUtc2xjNV9hbWQ2NF9nY2M0MzQiLCJ0YWdzX3BhdGgiOiIvY21zLWNsb3VkL2Ntc3N3LWRvY2tlci9yZWdpc3RyeS9yZXBvc2l0b3J5LzgyMjUvdGFncz9mb3JtYXQ9anNvbiIsImlkIjo4MjI1fQ==)
- To reflect: 
   - we should consider the CERN gitlab registry (instead of dockerhub) as the main location for the images (considering the dockerhub download restrictions and the eventual expiry policy)
   - would it be useful to have a separate CERN gitlab registry for open data related images? Useful for displaying them, but not necessary for pull.

**Comment by Ayushsunny** [comment]
I wanna work on this issue.
