### ISSUE TITLE
elasticsearh: upgrade to Elasticsearch 7

### ISSUE THREAD

**Issue by diegodelemos** [cernopendata/opendata.cern.ch#2978]
Deprecation warnings about Elasticsearch5:
```console
web_1            | /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/invenio_search/ext.py:59: DeprecationWarning: Elasticsearch v2 and v5 support will be removed.
web_1            |   DeprecationWarning)
```

_Originally posted by @diegodelemos in https://github.com/cernopendata/opendata.cern.ch/pull/2968#discussion_r545063894_

Upgrade to a supported Elasticsearch version. At CERN the latest recommended version is `7`.

Note: maybe we can use [these docs](https://invenio.readthedocs.io/en/master/releases/upgrading/upgrade-3_1-3_2.html#upgrade-to-v7-by-reindexing) (:warning:  -  I haven't tested myself).

**Comment by ParthS007** [comment]
@diegodelemos  @tiborsimko  I tested with `elasticsearch 7.10.1` and I see no warnings in the logs mentioned above in `web_1` container.

It worked with just moving the mappings to v7
