### ISSUE TITLE
Change link in CMS HI release announcement

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#2982]
Hi @katilp, @tiborsimko!

In the opening line of [the announcement](https://opendata.cern.ch/docs/cms-releases-heavy-ion-data), instead of linking the text “open data from heavy-ion collisions” to <https://opendata.cern.ch/search?q=&keywords=heavy-ion%20physics> could we link the text “its first batches of open data from heavy-ion collisions” to <https://opendata.cern.ch/search?q=&keywords=heavy-ion%20physics&year=2010&year=2011&experiment=CMS>?

**Comment by katilp** [comment]
Fine with me. That would be more future proof, in case heavy-ion tags are added to the Alice records.
