### ISSUE TITLE
files: ROOT vs BIN file types

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#30]
ROOT demo files (see #25) were uploaded on the SLC6 box as BIN type ones.  The "automagic" recognition of file content vs file extension to be checked and amended...

**Comment by pherterich** [comment]
Can this be closed?

**Comment by tiborsimko** [comment]
The type is still displayed as BIN, but since it's not really affecting their usage, I agree we can close this.
