### ISSUE TITLE
search: range aggregations fails on latest invenio-search-ui

### ISSUE THREAD

**Issue by mvidalgarcia** [cernopendata/opendata.cern.ch#3021]
In our PROD config, we have a facet with [range aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html) (apart from typical [term aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html)):

https://github.com/cernopendata/opendata.cern.ch/blob/101c8942b621c69a7d57e85f5bf28314c50c0a86/cernopendata/config.py#L318-L353

After upgrading to the latest `invenio-search-ui`, which uses `react-searchkit` when using the `semantic-ui` theme, this term aggregation breaks the search as [it's not taken into account](https://github.com/inveniosoftware/invenio-search-ui/blob/44b6122d8f066a92344f1c1a58b4d18e888b690c/invenio_search_ui/views.py#L207) when generating the Search App configuration. Note how it's always taking `terms` as key, thus producing an exception when a range agg is parsed.

In order to fix this, we need to contribute upstream to make it more flexible and accept multiple [bucket aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket.html).

[_Original discussion here._](https://github.com/cernopendata/opendata.cern.ch/pull/3015#discussion_r562573689)

**Comment by diegodelemos** [comment]
After [discussing with upstream Invenio](https://discord.com/channels/692989811736182844/724974365451747329/803638831290646529), it is clear we can go ahead and subclass InvenioSearchUI's `SearchAppInvenioRestConfigHelper` to get range aggregations displayed in Opendata. Moving the issue to `Ready for work`.
