### ISSUE TITLE
search: query error when selecting multiple event number facets

### ISSUE THREAD

**Issue by diegodelemos** [cernopendata/opendata.cern.ch#3028]
Currently, there is a problem when querying for two range aggregations (event number), e.g. http://0.0.0.0:5000/search?q=&f=event_number%3A1000--9999&f=event_number%3A10000--99999&l=list&order=asc&p=1&s=10&sort=mostrecent.

https://user-images.githubusercontent.com/9035606/106131546-1ceeca00-6163-11eb-9e0e-c4fa24f7269f.mov

**Comment by tiborsimko** [comment]
Visible on DEV: https://opendata-dev.cern.ch/search?q=&f=event_number%3A1000--9999&f=event_number%3A10000--99999&l=list&order=asc&p=1&s=10&sort=mostrecent

**Comment by tiborsimko** [comment]
@ParthS007 Another search-related issue you could have a look at.

**Comment by ParthS007** [comment]
This error can also be reproduced on Prod as well.
