### ISSUE TITLE
UI: Support old URLs recognition

### ISSUE THREAD

**Issue by ParthS007** [cernopendata/opendata.cern.ch#3030]
What is happening?
- All records are listed when we search by this URL - `http://localhost:5000/search?keywords=education`.
- When querying in the search bar, we are getting expected results.

What is expected?
- Searching by entering direct URL and querying in the search bar should give same number of results.

Example:
- new: `localhost:5000/search?q=&f=type%3ADataset`
- old: `localhost:5000/search?type=Dataset`

**Comment by tiborsimko** [comment]
Example from the home page: the Glossary link points to: `/search?type=Glossary&sort=title`, while with the new search UI we should rather point to: `?q=&f=type%3AGlossary` (plus sorting by title that is currently broken; see another issue).

While we could change the links internally, there may be many in CMS web site, CERN web site, etc.

Hence it would be good to make a URL redirector to recognise old URLs arguments (such as `type=Glossary`, `keywords=education`, etc) and redirect to the new URLs to ensure they are working.
