### ISSUE TITLE
ci: migrate GitHub Actions tests to py36

### ISSUE THREAD

**Issue by mvidalgarcia** [cernopendata/opendata.cern.ch#3038]
Since we're using a Python 3.6 base image to run CERN Open Data, we don't have to support py2 anymore on GA.

Together with this we can get rid of all the [future imports](https://docs.python.org/3/library/__future__.html) such as  `from __future__ import absolute_import, print_function
`

**Comment by tiborsimko** [comment]
We should also update Trove classifiers in `setup.py` to say Python 3.6 instead of 2.7.
