### ISSUE TITLE
search: apparent missing "CMS Derived Datasets" content

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#305]
From @jottCern:

> For the CMS derived datasets, clicking on "more" redirects to http://opendata.cern.ch/search?cc=CMS-Derived-Datasets&ln=en&jrec=11 which shows a empty box on the left titled "CMS Derived Datasets". It looks like it should not be empty.

![screen shot 2014-09-23 at 11 17 23](https://cloud.githubusercontent.com/assets/7623019/4369910/72f8d390-4302-11e4-94da-333428ac436d.png)

**Comment by tiborsimko** [comment]
The faceting is rewritten in Invenio v2.2+ so this will be solved when we'll upgrade to that Invenio version.

**Comment by suenjedt** [comment]
Part of the Invenio 3 upgrade anyway. Not a pressing for current prod version.
