### ISSUE TITLE
ui: fix `unsafe-inline` console warning

### ISSUE THREAD

**Issue by audrium** [cernopendata/opendata.cern.ch#3079]
We need to fix console warnings:
```
Content Security Policy: Ignoring duplicate source 'unsafe-inline'
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'
```
![Screenshot from 2021-02-19 10-01-49](https://user-images.githubusercontent.com/4990025/108482497-d7bd4400-7299-11eb-8215-58aae25a7488.png)
![Screenshot from 2021-02-19 10-02-17](https://user-images.githubusercontent.com/4990025/108482509-db50cb00-7299-11eb-88b4-c7d8ccfe0c68.png)

Related [PR](https://github.com/cernopendata/opendata.cern.ch/pull/3076)

**Comment by psaiz** [comment]
The related PR has been merged. And the warning does not appear. The ticket has been addressed.
