### ISSUE TITLE
download: UI stays at warning window

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3086]
**Current behaviour**

When downloading a big file over web, e.g. from https://opendata-dev.cern.ch/record/1, the user is presented a warning:

![download](https://user-images.githubusercontent.com/517546/108686770-29620a80-74f6-11eb-9fa4-9ac821ddec0d.png)

When the user clicks on Download, the download is happening, but the warning window stays displayed on.

**Expected behaviour**

When user confirms the popup and the download starts, the user should be brought back to the list of all files, e.g. to start new download, or browse away.  (See also the behaviour on PROD.)

**Comment by mvidalgarcia** [comment]
Should be easy to fix. Adding [here](https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/theme/assets/semantic-ui/js/records/components/DownloadWarningModal.js#L66) the same `onClose` that the "Cancel" button has should be sufficient.
