### ISSUE TITLE
CMS: Install VM link from 2012 records broken

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3088]
2012 MC records in `records/cms-simulated-datasets-2012.json` link to

https://opendata-dev.cern.ch/docs/cms-virtual-machine-2012

for instructions to install to VM. This page does not exist, it should be

https://opendata-dev.cern.ch/docs/cms-virtual-machine-2011 (or redirect)

**Comment by tiborsimko** [comment]
Note: this problem also exists on PROD. I'll make a quick fix there...

**Comment by tiborsimko** [comment]
... and now also deployed on PROD, QA, DEV.
