### ISSUE TITLE
search: search terms not shown graphically

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3099]
The search term display in the production search has been really helpful

![image](https://user-images.githubusercontent.com/5859918/110696063-e3da5880-81ea-11eb-83a4-806d60cff6f5.png)

Will it be made available in the new search as well?

**Comment by psaiz** [comment]
![Screenshot 2024-02-12 at 16 31 25](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/3d9bb268-aadc-4b1c-8fad-a674363c9032)


The terms are still there. Closing the ticket
