### ISSUE TITLE
Record for simulated Open Data dataset for ATL-PHYS-PUB-2021-002

### ISSUE THREAD

**Issue by artfisica** [cernopendata/opendata.cern.ch#3100]
Hi!

We would like to add a new record to the CERN Open Data portal.

This time is a dedicated simulated sample related to publication ATL-PHYS-PUB-2021-002

The file is called `z2e2j_zz4e_csv_test_data.tgz`, and it was copied in the upload EOS area for ATLAS:
`/eos/opendata/atlas/upload/datascience/ATL-PHYS-PUB-2021-002/data`

I understand there is also a piece of code, and I will copy it in `/eos/opendata/atlas/upload/datascience/ATL-PHYS-PUB-2021-002/code` (still to come).

But I want to profit from asking how you would like to proceed better:
* I create and attach a JSON file for this record
or
* Create such a file inside the repo and make a PR

I think both objects -- dataset and code-- can leave in a single record since they refer to the same specific publication. But please, let me know if you prefer two records.

Thanks for your feedback,
Cheers,
Arturo

**Comment by tiborsimko** [comment]
Handled via email and closed by #3103  and #3104.

**Comment by artfisica** [comment]
Hi!

Thank you, @tiborsimko, for all this. I was just writing the same right now :)

Cheers,
Arturo
