### ISSUE TITLE
ATLAS Policy record update

### ISSUE THREAD

**Issue by artfisica** [cernopendata/opendata.cern.ch#3101]
Dear All,

We at ATLAS want to update the document (and some of the text)  in record http://opendata.cern.ch/record/413

I want to kindly
[ATLAS-Data-Access-Policy-Feb2021.pdf](https://github.com/cernopendata/opendata.cern.ch/files/6137880/ATLAS-Data-Access-Policy-Feb2021.pdf)
 ask if it is possible to simply change the PDF file for the newest one (attached here for reference)?
Or
If a need record is needed?

Thanks and cheers,
Arturo

PS: I will also update the JSON to update the ext, but before, I would like to ask if this will update the existing record (it seems more natural) or a new one.

**Comment by artfisica** [comment]
Hi again,

Sorry, can we tackle this one first to create other issues?

Thanks!
Arturo

**Comment by tiborsimko** [comment]
Hi @artfisica, we can do one of the following:

1. Keep the same record http://opendata.cern.ch/record/413 and attach new PDF there under a file name like `ATLAS-Data-Policy-2020.pdf` or `ATLAS-Data-Policy-v2.pdf`.  This is what LHCb opted for, please see http://opendata.cern.ch/record/410

2. Create a  new record with a new DOI and link the two data policies records together. This is what CMS opted for, please see http://opendata.cern.ch/record/411 and http://opendata.cern.ch/record/414

If you'd like to attach the new file and update the description text, we could do the former (more simple) solution.
If you'd like to have a new DOI, then we need do the latter (more complex) solution.

Which one would you prefer?

**Comment by artfisica** [comment]
Hi @tibor,

Thank you very much for the proposal. I will ask you, please, to go for the first option, (more simple) solution.

The modified text is:

> This document contains the policy document regarding the access to ATLAS data by non-ATLAS members, which was endorsed by the ATLAS Collaboration Board in June 2014. The current revised version below was endorsed in February 2021.

And the file can be called or as it is now, or `ATLAS-Data-Policy-2021.pdf`.

**Comment by tiborsimko** [comment]
@artfisica Thanks, merged and deployed.
