### ISSUE TITLE
Enhancement: Swap Download/Preview buttons in “Files” boxes

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#3107]
Take [/record/300](https://opendata.cern.ch/record/300) for example.

The “Files” box offers both Download and Preview, but the latter is only available for `.ig` files. The resulting display of the buttons is jagged:

![Screenshot_2021-04-14 CERN Open Data Portal](https://user-images.githubusercontent.com/7623019/114788799-61f9c400-9d82-11eb-8ef8-cea9a42cb5d3.png)

I played with the developer tools and swapped the buttons and it looks much nicer:

![Screenshot_2021-04-14 CERN Open Data Portal update](https://user-images.githubusercontent.com/7623019/114788852-7dfd6580-9d82-11eb-9499-74ae88c842bf.png)

I can poke around the HTML at some point and submit a PR.

---

Edit:

Do I have to edit `cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html`?

There are two similar chunks of code; is this the change to make?

```diff
 <div class="btn-group" role="group" aria-label="Button group" ng-init="download_uri = '/record/{{pid.pid_value}}/files/'+file.key">
+  <a
+    ng-if="previewable = (file.key.split('.').pop() == 'ig')"
+    ng-href="#previewer"
+    ng-click="$ctrlTbl.previewFile(file.key)"
+    class="btn btn-outline-primary">
+    <span class="oi" data-glyph="eye"></span> Preview
+  </a>
   <a
     ng-controller="indexFileListModalCtrl as $ctrlIndexList"
     ng-click="$ctrlIndexList.openModal({{pid.pid_value}}, file.key)"
     ng-if="file.type == 'index.txt'"
     class="btn btn-outline-primary">
     <span class="oi" data-glyph="list"></span> List Files
   </a>
   {{ download_btn() }}
-  <a
-    ng-if="previewable = (file.key.split('.').pop() == 'ig')"
-    ng-href="#previewer"
-    ng-click="$ctrlTbl.previewFile(file.key)"
-    class="btn btn-outline-primary">
-      <span class="oi" data-glyph="eye"></span> Preview
-  </a>
 {% raw %}
 </div>
```

**Comment by tiborsimko** [comment]
Hi @RaoOfPhysics, we have updated underlying Invenio technology, so PROD looks different than DEV.  So you may want to look at the DEV site. E.g. the record there does not show preview anymore, since the event was previewed in the main page body.  (We now do the same for OPERA.)

**Comment by RaoOfPhysics** [comment]
Aaaaaah, makes sense, @tiborsimko. Should've checked DEV first anyway. Oops. I see that the formatting has also changed so it addresses some of the comments in #3108 too (width of the Size column, e.g.)!
