### ISSUE TITLE
records: standardise license strings

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3111]
Amend record fixtures to standardise on some widely-used license strings. Example: [SPDX license list](https://spdx.org/licenses/) that is used by [F-UJI](https://f-uji.net/) would help to improve F-UJI's FAIR assessment findings.

**Comment by tiborsimko** [comment]
The current distribution of license values seems to be:

```
   12420 CC0
    6052 null
     46 GNU General Public License (GPL) version 3
      2 Apache License, Version 2.0
      1 MIT Open Source license
      1 MIT License (MIT)
      1 CC0 license
      1 BSD License
```

After we update the values to SPDX, we'd also need to amend the portal infrastructure repository's output templates to display the CC0 copyright message accordingly.

**Comment by Biscgit** [comment]
Created adjustments for the Portal already regarding the upcoming license changes. Please follow PR in cernopendata/cernopendata-portal#83 on that.

**Comment by psaiz** [comment]
The PR on the portal is there. The one of opendata.cern.ch is still open
