### ISSUE TITLE
CMS: docker image links broken in analysis guide

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#3128]
In the [Running CMS analysis code using Docker](https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry/8237) guide the links to the CMSSW_4_4_7 and CMSSW_3_9_2_patch5 images in the GitLab registry are broken (it looks like they link to image tags that no longer exist). 

Perhaps we should provide links to the registry for the image name and have the user select an image (like [CMSSW_4_4_7](https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry/8237) and [CMSSW_3_9_2_patch5](https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry/8225))? If so, then which tag? If `:latest` then always use that? If there is no `:latest` then use the newest one? Should we make sure that there is always a `:latest`?

Alternatively, we could link to the tags themselves but then how do we ensure that they don't become obsolete links?

Note that dockerhub vs. gitlab is covered in #2887

**Comment by katilp** [comment]
Thanks for pointing this out, this indeed needs thinking and cleaning. And would be good to set up regular testing.

For the record, in [the workflows](http://opendata.cern.ch/search?page=1&size=20&type=Software&subtype=Workflow&experiment=CMS) we have

AOD2NanoAODOutreach (http://opendata.cern.ch/record/12340)
cmsopendata/cmssw_5_3_32
https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/argo-workflow.yaml#L15
https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/.github/workflows/main.yml#L20

TriggerInfoTool 2010 (http://opendata.cern.ch/record/5003)
cmsopendata/cmssw_4_2_8 
https://github.com/cms-opendata-analyses/TriggerInfoTool/blob/2010/argo-workflow.yaml#L57

TriggerInfoTool 2011 (http://opendata.cern.ch/record/5004)
cmsopendata/cmssw_5_3_32 
https://github.com/cms-opendata-analyses/TriggerInfoTool/blob/2011/argo-workflow.yaml#L57

CASTOR example ( http://opendata.cern.ch/record/465) : 
cmsopendata/cmssw_4_2_8_lowpupatch1
https://github.com/cms-opendata-validation/CastorDataValidation/blob/master/argo-workflow.yaml#L48

HI 2010 example (http://opendata.cern.ch/record/466)
gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_3_9_2_patch5-slc5_amd64_gcc434:2020-11-17-e0b0b7a6
https://github.com/cms-opendata-analyses/HiForestProducerTool/blob/2010/.github/workflows/main.yml#L21

HI 2011 example (http://opendata.cern.ch/record/467)
gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_4_4_7-slc5_amd64_gcc434:2020-11-19-89e805d7
https://github.com/cms-opendata-analyses/HiForestProducerTool/blob/2010/.github/workflows/main.yml#L21

So not a great consistency there, either. And after having collected this information I really think it would be nice to have a proper API for getting the image names. 

@tiborsimko we could think of adding an image name field for SW records

**Comment by katilp** [comment]
The image name is now included in the dataset records. Closing now,  would be good to clean the example repositories
