### ISSUE TITLE
facets: investigate multi-selection issues

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3131]
Click on empty search, leading to 5112 hits.

Click on ATLAS, 123 hits.

Click on Documentation,  4 hits.

Click on VM, 5 hits.

Current behaviour: the number of results is small, e.g. the documentation this are gone. It is irrelevant if you tick on or off the Documentation facet.

Expected behaviour: ticking on or off the documentation facet should bring more or less results.

Compare how PROD behaves.

P.S. Is this a facet composition problem, i.e. how the query is constructed and then resolved? Or is this a nginx query caching problem, since we aggresively cache everything from the search side?

**Comment by psaiz** [comment]
Note that this requires a new version of invenio_records_rest
