### ISSUE TITLE
facet: selecting parent facet category should select daugther categories

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3132]
Do an empty search.

Select a parent facet category such as "Documentation".

On PROD, the daughter categories such as "Guide" and "Help" will be also pre-selected automatically.  (I.e. checkboxed ticked.) This is quite understandable behaviour, because by selecting parent category you select all daughter categories.

On DEV, the daugther categories such as "Guide" are not ticked. This may make some users perplexed as to what happens when you click on some.

The counts are good, but the checkboxes being off may lead to UX issues.

**Comment by ParthS007** [comment]
Same behavior is observed here:

https://user-images.githubusercontent.com/24358501/128350303-7ea4d646-0d8e-45ac-8f95-2bb93f34da4d.mov

Related to react Searchkit

**Comment by tiborsimko** [comment]
Thanks for testing this out! When you mention "local instance", is this "qa" branch or "master" branch?

We have fixed quite a few search-related issues in the "master" branch that you may still observe in production.

WRT 1, the amount should basically just be jumping between 16354 and 45 results. It's weird that "later" it shows 22 results only. The problem goes away when you reload the page. Have you tried to reproduced locally using `qa` branch whether it is also happening locally in DEV mode?  Just trying to see whether it's related to our quite aggressive nginx caching, or whether the issue is also present in the Angular layer.

WRT 3, if on an empty page you select some sub-facet such as "Guide", this will also automatically select the parent "Documentation".  It's a kind of breadcrumb trail showing what is selected.  I see that it may be confusing is someone unselects all the sub-facets, but note that if on a new empty search you only select "Documentation", then all sub-facets are automatically selected.  So it may be understandable... Though it would be better indeed if the parent facet is automatically unselected if someone unselects all daughter facets.

WRT 2 and 4, yes that's not very good. :)

WRT 5 and 6, this may be due to special parent/daugther facet behaviour. We can definitely change the behaviour to be more consistent across the field. 

We can see IRL about these?

**Comment by psaiz** [comment]
It might be better to check this one again after https://github.com/cernopendata/opendata.cern.ch/pull/3450 has been merged. The initial topic described in this issue (selecting parent should select children) is not addressed there. The other issues described later on are. 

I would argue that selecting the parent should not select the kids (even if that is the behaviour of the legacy).  Imagine that the parent is selected, and then all the kids are deselected. What should that return?

**Comment by tiborsimko** [comment]
> I would argue that selecting the parent should not select the kids (even if that is the behaviour of the legacy). Imagine that the parent is selected, and then all the kids are deselected. What should that return?

The original logic behind selecting kids as well was that, once you select a parent category, the search results are automatically including hits also representing daughter categories, as if they were "automatically selected" for the user when the user selected the parents, so to speak.

BTW the situation you describe could be helpful in cases when the parent facet value is present in the record for many records, and when some records have daughter value, and some don't, for example: 

```json
  "categories": {
      "primary": "Standard Model Physics",
      "secondary": [
        "QCD"
      ]
  }
```

and another record having:


```json
  "categories": {
      "primary": "Standard Model Physics",
  }
```

This is theoretically possible, However, I personally do not like cases like that as well, because these latter records don't appear under a dedicated daughter category, and remain hidden "hidden" under the parent, so to speak. So we could think of considering these cases as a "bug" rather than a "feature" and an incentive to amend the metadata :wink:

**Comment by psaiz** [comment]
Imagine that there are no `hidden`entries as you mentioned. What would be expected result in these two screenshots?

If the result is the same (as it happens to be), then the user should understand that all the children are selected if the parent is selected, so I still do not see the point of autoselecting the kids. 

If, on top of this, we add the `hidden`, not selecting the kids automatically makes even more sense


![Screenshot 2023-12-05 at 15 15 27](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/d73c2c29-c77f-45d0-aea6-6d617e4c90fb)
![Screenshot 2023-12-05 at 15 15 20](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/a9d09184-a713-4788-a96d-18bead098102)

**Comment by psaiz** [comment]
For the time being, we will stay with the default behaviour of indico, of not selecting the kids when the parent is selected
