### ISSUE TITLE
facet: unselecting daugther facets unselects parent facets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3133]
As an example UX issues behind #3132, try the following:

- Do an empty search.
- Select "Documentation" facet by ticking the checkbox.
- Select "Authors" facet by ticking the checkbox.
- Select "Guide" facet by ticking the checkbox.
- Unselect "Guide" facet by unticking the checkbox.

Current behaviour: all the facet selection is gone and one gets to see full 7624 hits.

Expected behaviour: we would be at the state where Documentation and Guide are selected... Basically going back in the stack if the last fact selection was undone.

**Comment by tiborsimko** [comment]
Note: it also unselected sibling facets, not only parent facets... So the issue description is not fully complete. Basically, unselecting a daughter facet made the whole facet selection set to be removed.

**Comment by ParthS007** [comment]
Same behavior is observed here:


https://user-images.githubusercontent.com/24358501/128349950-334f6a20-7fe4-4a93-b79c-ba5bffc8b593.mov
