### ISSUE TITLE
CMS: build the record for 2015 trigger information summary

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3152]
Build the record for
- 2015 HLT summary 
  - as in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-trigger-information-2012.json 
  - using the HTML snippet from cms-trigger-information-run2-helper.html
  - display only the open data run range 246909 - 260627

Prepared with the script from https://github.com/cernopendata/data-curation/tree/master/cms-run2-hlt-triggers
(NB requires changing ConvertMe! -> convertMe!  in `CMSSW_10_6_10/src/HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py` )

Ouput in `/eos/opendata/cms/configs2015`, to be moved to `/eos/opendata/cms/configuration-files/2015`

**Comment by tiborsimko** [comment]
> Ouput in /eos/opendata/cms/configs2015, to be moved to /eos/opendata/cms/configuration-files/2015

Moved, for 2015, 2016, 2017, 2018.

**Comment by tiborsimko** [comment]
Reserved record ID: 23900

**Comment by tiborsimko** [comment]
> Where would that files/ point to?

We'll replace them with links to created records. If the table is good to go "as is", I'll take it as an input and just replace those file links with links to proper record IDs.

**Comment by katilp** [comment]
@tiborsimko Minor fix to the text:

Now: The list of trigger configuration files for the CMS Run2015D proton-proton collision data (from run number 256630 to run number 260627)

Change to: The list of trigger configuration files for the CMS Run2015 proton-proton collision data (Run2015D from run number 256630 to run number 260627)

**Comment by tiborsimko** [comment]
> The list of trigger configuration files for the CMS Run2015 proton-proton collision data (Run2015D from run number 256630 to run number 260627)

Changed.
