### ISSUE TITLE
CMS: create a record for the dimuon analysis in Julia

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3167]
Add a record for [the Julia example](https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysisJulia) by @grasph in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json 

@grasph, once the versioning issue mentioned by @clelange is addressed would you give a release tag and choose a license in the repository and let me know. I can then upload the zip to the `/eos/opendata/cms/upload`.
Would you then be able to add the json description of the new record in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json?

You can add the json fields after the fields of the already existing records. Let us know if you have questions about the contents of the fields. @tiborsimko can indicate the `recid` to be used and will add the DOI.

**Comment by grasph** [comment]
Release created: https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysisJulia/releases/tag/v1.0.0

**Comment by tiborsimko** [comment]
@katilp We can take record ID 22350.

**Comment by grasph** [comment]
@katilp how can I can list files from /eos/opendata/cms/upload? I cannot see the directory on lxplus. I expect I need it to obtain the adler checksums that go in the json file. 

How many file we will have only the zip file or also some extra individual files, like the notebook? For the doi, did I understand correctly, that I let the field empty and @tiborsimko will update it?

Final question, what the information filled in the json file used for ? For the search engine ? To build the opendata page?

**Comment by katilp** [comment]
@grasph You can leave the file listing fields out and @tiborsimko will take care of them (as well as that of DOI).

We only need the zip, we expect the main access to the notebook to be through the repository link and the zip is there for data preservation purposes.

The open data portal record is built from the json file. Some fields are also used for the search.

Thanks!

**Comment by katilp** [comment]
@grasph Let me know if you can create the json file, or if you like me to do it. We would need to get it soon to include it in the release. It will result in a record on the open data portal, similar to https://opendata-qa.cern.ch/record/12342

**Comment by katilp** [comment]
@grasph I've built the json and the record would look like this

![image](https://user-images.githubusercontent.com/5859918/146509062-b171baa8-a972-4ec4-a434-ac36ff6b9a76.png)

The fields that show "None" in this will refer to the dataset to be used, to the other di-muon record, and to the original AOD

**Comment by grasph** [comment]
Perfect. Thanks, Kati. I'm happy you did it, because I started something on Wednesday, but I didn't know how to have the plot  and all the information displayed on the generated page.
