### ISSUE TITLE
Badges are not separated by spaces in the 'News & Updates'

### ISSUE THREAD

**Issue by avivace** [cernopendata/opendata.cern.ch#3232]
This is how a record looks like in the Search results:
![immagine](https://user-images.githubusercontent.com/14352721/157767023-7fee5215-83de-4690-bcb9-ace2036cec77.png)
However, in the cards rendered in the "News & Updates" from the landing page, the badges/labels are not separated between each other:
![immagine](https://user-images.githubusercontent.com/14352721/157767099-93066f28-5375-4f8f-9a97-1797f54bb8ee.png)

**Comment by sksDonni** [comment]
I think the issue is still persistent. Would like to take this up.

**Comment by tiborsimko** [comment]
Closed in #3277

**Comment by sksDonni** [comment]
Please let me know if there are any other issues that I can work on. Will be more than happy to!
