### ISSUE TITLE
CMS: improve 2015 VM documentation

### ISSUE THREAD

**Issue by clelange** [cernopendata/opendata.cern.ch#3236]
The documentation at http://opendata.cern.ch/docs/cms-virtual-machine-2015 currently says:

> Next download the CMS-specific CernVM image as OVA file from: [CMS VM Image for 2011 CMS Open Data](http://opendata.cern.ch/record/252).

The [linked record](http://opendata.cern.ch/record/252) then mentions that this VM is for 2011 and 2012 CMS Open Data, but it's actually also valid for 2015. It would be nice to change the title of the record accordingly.

**Comment by katilp** [comment]
Done: http://opendata.cern.ch/record/252
