### ISSUE TITLE
search: Filter by Event Number facet should auto-hide

### ISSUE THREAD

**Issue by MindaugasSarpis** [cernopendata/opendata.cern.ch#3263]
`Filter by Event Number` Section appears even if other selected filters leave 0 records or docs for each facet in the section.

**Comment by tiborsimko** [comment]
Example: http://opendata.cern.ch/search?page=1&size=20&q=xyzzy

![xyzzy](https://user-images.githubusercontent.com/517546/187613230-ed932abb-0633-402c-9bb2-d01700e4084b.png)

The facet should now be shown when no hits match anything, as the other facets do.

**Comment by sksDonni** [comment]
@tiborsimko, could you please review pull request #3274 ?
