### ISSUE TITLE
CMS: Record 1052 should point to 1054 more clearly

### ISSUE THREAD

**Issue by clelange** [cernopendata/opendata.cern.ch#3282]
Record [1052](http://opendata.cern.ch/record/1052) describes 2012 luminosity, but it's an old version of the luminosity estimation. There's an updated one in record [1054](http://opendata.cern.ch/record/1054) that people should be pointed to at the very top of the record, in particular since there's no connection to 2012 in the first paragraph. 1052 should be considered as deprecated.

**Comment by katilp** [comment]
Idem for 2011: records [1051](http://opendata.cern.ch/record/1051) and [1053](http://opendata.cern.ch/record/1053)

**Comment by tiborsimko** [comment]
We have a "Related dataset" section pointing to the full information, but perhaps @katilp you can edit the record to start the body in the usual style like:

```
<p><em>Updated on November 30th 2022. This record contains incomplete luminosity information, please use ... instead. </em></p>
```

to make it more obvious from the start?

**Comment by katilp** [comment]
Yes, I can do that. 

Also, attach the prescale files to the newer records [1053](http://opendata.cern.ch/record/1053) and [1054](http://opendata.cern.ch/record/1054) (instead of referring to them in the old record)
