### ISSUE TITLE
CMS: fix collision energy unit in validated records title (HI-related data)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3364]
Change unit from GeV to TeV for
- http://opendata.cern.ch/record/14208 
- http://opendata.cern.ch/record/14206
- http://opendata.cern.ch/record/14209
- http://opendata.cern.ch/record/14207

in cms-validated-runs-HIRun1.json

Fields: `title_additional` and `description` of `abstract`

**Comment by katilp** [comment]
@tiborsimko This is done but not deployed. Will it get deployed with the release? Can I close?

**Comment by tiborsimko** [comment]
We can close this, since it was done in #3371.  Deployed on QA for now.

**Comment by tiborsimko** [comment]
BTW found two more examples of this typo; PR coming.
