### ISSUE TITLE
Developing guide: fix container name typo

### ISSUE THREAD

**Issue by nancyhamdan** [cernopendata/opendata.cern.ch#3388]
In DEVELOPING.rst, the container name `opendatacernch-web-1` should be used instead of `opendatacernch_web_1`

**Comment by tiborsimko** [comment]
@nancyhamdan This is something which is related to the docker-compose version 1 (that uses underscores) vs docker-compose version 2 (that uses dashes).  v1 comes by default on a lot of Linux distributions, v2 comes by default with Docker Desktop (on macOS).

We have basically two solutions:

- You could use `docker compose --compatibility` which should create containers with the old behaviour (with underscores). 
- I can test docker compose v2 on Linux and we can switch to using `docker compose` everywhere, using the new behaviour (with dashes).

**Comment by tiborsimko** [comment]
> I can test docker compose v2 on Linux and we can switch to using docker compose everywhere, using the new behaviour (with dashes).

Tested, and everything is OK; so that we can switch instructions to using dashes everywhere, and perhaps at the same time you can replace `docker-compose` by `docker compose` everywhere as well, so that it is fully clear that we are using docker compose v2 and not v1.

**Comment by psaiz** [comment]
Deployed in production as well
