### ISSUE TITLE
CMS - write a HI-specific getting started page

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3397]
In comparison to http://opendata.cern.ch/docs/cms-getting-started-2015, the HI-specific page should tell
- HI data are in a different format (RECO vs AOD for Run-1)
- some code in addition to the usual CMSSW is needed and available in the HI containers
- HI data are usually processed in a special ntuple ("HiForest") but its contents depend on the type of analysis
- can point to config examples but must be clear that those were used for testing purposes and the users must dive into the details and make sure to understand what they need in their particular study case

**Comment by katilp** [comment]
Testing in VM image:

- [ ] `CMSSW_VERSION` is not set in the Outer Shell, need to set explicitly `CMSSW_VERSION=CMSSW_5_3_20`
- [ ] git in the outer shell and compile in cms shell ok
- [ ] test both git and compile in cms shell

**Comment by katilp** [comment]
Testing in the VM:
- CMSSW_5_3_20 OK
- CMSSW_7_5_8_patch3
 
  ```
  CMS Shell > scram b
  Parse Error in src/HeavyIonsAnalysis/VectorBosonAnalysis/BuildFile.xml, line 
  Invalid value 'MYFILE_CHECKSUM=$$(shell git hash-object $$< | sed 's| .*||')' found.
  ```

**Comment by katilp** [comment]
VectorBosonAnalysis is needed:

```
CMS Shell > cmsRun runForestAOD_pp_DATA_75X_cvmfs.py 
fatal: Not a valid object name HEAD
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
Added 'egmGsfElectronIDs' to process definition (AOD format)!
Added ID 'cutBasedElectronID-Spring15-25ns-V1-standalone-loose' to egmGsfElectronIDs
Added ID 'cutBasedElectronID-Spring15-25ns-V1-standalone-medium' to egmGsfElectronIDs
Added ID 'cutBasedElectronID-Spring15-25ns-V1-standalone-tight' to egmGsfElectronIDs
Added ID 'cutBasedElectronID-Spring15-25ns-V1-standalone-veto' to egmGsfElectronIDs
----- Begin Fatal Exception 31-Jul-2023 19:39:54 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named runForestAOD_pp_DATA_75X_cvmfs.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named VectorBosonAnalysis.tupelSequence_pp_cff
----- End Fatal Exception -------------------------------------------------
```

So fix whatever is wrong in that Buildfile...

**Comment by katilp** [comment]
Completed with
- get package lists (the shorter one for 75X above to avoid hours-long compilation) from https://github.com/cms-opendata-validation/HeavyIonDataValidation/tree/main
- instruct to remove the first preprocessor definition flag line (CPPDEFINES) in VectorBosonAnalysis BuildFile.xml

**Comment by tpmccauley** [comment]
> Testing in the VM:
> 
>     * CMSSW_5_3_20 ✅
> 
>     * CMSSW_7_5_8_patch3
>       ```
>       CMS Shell > scram b
>       Parse Error in src/HeavyIonsAnalysis/VectorBosonAnalysis/BuildFile.xml, line 
>       Invalid value 'MYFILE_CHECKSUM=$$(shell git hash-object $$< | sed 's| .*||')' found.
>       ```
> 
> 
> Removing HeavyIonsAnalysis/VectorBosonAnalysis from the list makes it compile
> 
> but it fails after almost two hours of compiling with
> 
> ```
> >> Compiling edm plugin /home/cms-opendata/CMSSW_7_5_8_patch3/src/DQMOffline/Trigger/src/FSQDiJetAve.cc 
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> gmake: *** [tmp/slc6_amd64_gcc491/src/DQMOffline/Trigger/src/DQMOfflineTrigger/FSQDiJetAve.o] Error 1
> gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
> ```
> 
> @tpmccauley Did `HeavyIonsAnalysis/VectorBosonAnalysis` package compile properly in the container? This is in the VM. And also, are all those packages really needed in the package list? DQM, SLHCUpgradeSimulations etc included? Earlier, when I tried with `(/code/CMSSW_7_5_8_patch3/src) git cms-merge-topic CmsHI:forest_CMSSW_7_5_8_patch3` in a base container, I saw this output "only": [fork.1.txt](https://github.com/cernopendata/opendata.cern.ch/files/12216849/fork.1.txt) and that looks much shorter.
> 
> ```
> CondFormats/JetMETObjects
> HeavyIonsAnalysis/CentralityAnalysis
> HeavyIonsAnalysis/Configuration
> HeavyIonsAnalysis/EventAnalysis
> HeavyIonsAnalysis/JetAnalysis
> HeavyIonsAnalysis/MuonAnalysis
> HeavyIonsAnalysis/PhotonAnalysis
> HeavyIonsAnalysis/TrackAnalysis
> HeavyIonsAnalysis/VectorBosonAnalysis
> HeavyIonsAnalysis/VertexAnalysis
> JetMETCorrections/Algorithms
> JetMETCorrections/Modules
> PhysicsTools/PatAlgos
> RecoBTag/CSVscikit
> RecoHI/HiJetAlgos
> RecoJets/Configuration
> RecoJets/JetProducers
> RecoMET/METPUSubtraction
> ```

I tried this collection of packages and it compiles. I've made a MR in GitLab: https://gitlab.cern.ch/cms-cloud/cmssw-docker-opendata/-/merge_requests/12

**Comment by katilp** [comment]
@tpmccauley Thanks! Cross-posting in https://gitlab.cern.ch/cms-cloud/cmssw-docker-opendata/-/issues/15 : add also RecoEgamma/ElectronIdentification
