### ISSUE TITLE
CMS - update CMSSW link in recid 1702

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3436]
The link to the data-taking CMSSW version is https://github.com/cms-sw/cmssw-cvs/releases/tag/CMSSW_5_2_7_onlpatch3

**Comment by katilp** [comment]
There's no cernopendata/modules/fixtures/data/records/cms-trigger-information-2013.json on `qa`, should I update it in another branch?

**Comment by tiborsimko** [comment]
Fixed here:
- https://github.com/cernopendata/opendata.cern.ch/pull/3435
- https://github.com/cernopendata/data-curation/pull/198

BTW I have also programmatically removed the `_ONLINE` suffix, because the value in the `inputs/summary.txt` file was `CMSSW_5_2_7_onlpatch3_ONLINE`.
