### ISSUE TITLE
Markdown "tabs" support?

### ISSUE THREAD

**Issue by jmhogan** [cernopendata/opendata.cern.ch#3451]
This might be a non-issue...

We plan to update the CMS documentation and want to collapse all the "AOD" data years together in one "Getting Started" page. 

In the Open Data Guide repo we can get clickable tabs in the markdown. Example here:
https://raw.githubusercontent.com/cernopendata/cms-opendata-guide/master/docs/analysis/selection/objects/muons.md

The key for tabs is the "===" symbol. It doesn't render in Github, but I guess exists in the Ruby environment used to render the Github.io page. Short example from the raw markdown:

=== "Run 1 Data"

    Information and code examples specific to Run 1

=== "Run 2 Data"

    Information and code examples specific to Run 2

Is this feature available in the software used to render markdown for the portal? It would be a big enhancement for our documentation.

**Comment by tiborsimko** [comment]
Hi @jmhogan We are basically using [python-markdown](https://python-markdown.github.io/) to display Markdown, with some [extensions](https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/markdown/ext.py) to display nice TeX math.  

I'm not sure whether there exist a support for `===` tabs amongts [official extensions](https://python-markdown.github.io/extensions/) or [unofficial extensions](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions), but upon a cursory look it seems nothing pops up when I look for "tabs". 

Perhaps the "===" content tabs feature is [mkdocs-specific](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-other-content) only?

We could try to look for some of the existing plugins or even look for mixing HTML and Markdown, but that may not be the best...

The easiest for now would be to create the new umbrella guide page and simply link the other year-dependent pages in there.

**Comment by jmhogan** [comment]
For now we've used the HTML "details" method to create clickable hide/show panels. 

```
<details>
<summary> 2015 </summary>
text in here about 2015 usage
</details>
```

Clickable example in Github markdown:
<details>
<summary> 2015 </summary>
text in here about 2015 usage
</details>


It also appears to render well in the docker webpage viewing environment:

![image](https://github.com/cernopendata/opendata.cern.ch/assets/11163428/f0ccebe2-1951-42b1-9149-62bb4656f2c4)
