### ISSUE TITLE
CMS - add a guide page for CMS cross-section values

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3455]
Write a guide page "CMS cross-section values" (or similar) to be linked to in all MC records with cross-section values (see #3454 )

The page should explain:

- where the values come from
- what are the different efficiency numbers
- where to find NLO-corrected values (a new page in the CMS open data guide?)

See also #3452

**Comment by Shruti-codes236** [comment]
Hey @katilp , I have been following along with this repo, and I think I can do this, can you assign it to me?
