### ISSUE TITLE
records: prepare JADE notes file information

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3492]
(1) In order to publish JADE notes, we have to decide upon destination directory. I would propose `/eos/opendata/jade/documentation/notes` similarly to logbooks. @andriish @rdebrand OK with you?

(2) The current folder contains many files which may be perhaps left out (e.g. `1Doesntexist.pdf`), perhaps renamed (e.g. `74multiple.pdf`), and perhaps checked how to include those  (e.g. `XStatusOfTPDatasets.pdf`). 

Please let me know which input files you desire to copy and what should be the final published name of the file.

**Comment by rdebrand** [comment]
The directory looks good to me for the computing notes.

1Doesntexist.pdf &rarr; ~~1Doesntexist.pdf~~ (delete)
22multiple.pdf &rarr; 22.pdf
54multiple.pdf &rarr; 54.pdf
74multiple.pdf &rarr; 74.pdf
98mixed.pdf &rarr; 98.pdf
102multiple.pdf &rarr; 102.pdf

The other files should maybe not be included, as they are not computing notes per se. This would imply that we have the notes 0Index.pdf and then 2.pdf-103.pdf, with the renames mentioned above. @andriish do you approve?

**Comment by andriish** [comment]
Him @rdebrand! Great!
