### ISSUE TITLE
CMS: prepare the SW record for NanoAODRun1 usage examples

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3495]
Information and code currently in https://twiki.cern.ch/twiki/bin/view/CMSPublic/NanoAODRun1Examples
It should be brought to a repository under https://github.com/cms-opendata-analyses/
To follow the naming scheme, the repository should be called `NanoAODRun1ExampleAnalysis`

Then, prepare a SW record to refer to this repository. 
The extensive information can stay on the GitHub repository readme, and the portal record can brief explanation to avoid duplication.

**Comment by jmhogan** [comment]
Updating this one: github repository exists in our area now and has been tested. I've got a record in the works but not pushed yet

**Comment by katilp** [comment]
@jmhogan do you already recid for this? Asking because of [this](https://github.com/cernopendata/data-curation/blob/cms-nancy-derived-datasets/cms-derived-data/config.yaml#L42)

**Comment by jmhogan** [comment]
@katilp I will plan to use 12506 for this and 12507 for nanoAODtools

**Comment by katilp** [comment]
@jmhogan We might want to make https://opendata-qa.cern.ch/docs/cms-getting-started-nanoaod to point to 12507 then. In particular, if we make a cms-opendata-analyses repo out of https://github.com/cms-nanoAOD/nanoAOD-tools/ 
If we do so, we need to handle eventual updates if the original repo gets updated.

**Comment by jmhogan** [comment]
@katilp sounds good, I like that plan for the "how to use" section.

And yes, I will relink in the nano instructions.

**Comment by katilp** [comment]
Closing, the [record](https://opendata.cern.ch/record/12507) exists and has the zip of repo attached
