### ISSUE TITLE
search: displayed text for the ondemand facet switch in "current filters" 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3508]
Seen on DEV:

![ondemand](https://github.com/cernopendata/opendata.cern.ch/assets/517546/22bc6add-debf-4d38-9c16-3758eb872474)

The "current filter" for the "include on-demand datasets" switch is being displayed as "true".

This can be misleading as to what "true" is referring to.

It would be nice if we could display something different such as "ondemand" in place of "true".

P.S. See also #3506.

**Comment by rookieCoder9** [comment]
Hi @tiborsimko , I am Sahil, a final year Frontend Dev. Is it possible for me to work on this issue? Also, there is no such issue in Production so how can I reproduce it ? 
I am already experienced in Open Source and am willing to contribute to CERN.
Thanks and Regards.

**Comment by psaiz** [comment]
Hi @rookieCoder9,
Thanks for your message. This one is already addressed. If you want, I can look for a different ticket that could be good as a starting point.
Best regards, 
pablo
