### ISSUE TITLE
Updates on qa: double entry displayed in system details

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3519]
In https://opendata-qa.cern.ch/record/12502 double entry for the CMSSW version:
  ![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/47e31f1f-5f63-4905-9160-b1fd05460320)

**Comment by psaiz** [comment]
Thanks!  I can reproduce the issue. Let me check why it happened, and what we can do to fix it
