### ISSUE TITLE
Updates on qa: Old link forwarding does not propagate

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3520]
Old link forwarding does not propagate e.g. 
  - https://opendata.cern.ch/record/12502 points (correctly) to https://opendata.cern.ch/record/252 
  - https://opendata-qa.cern.ch/record/12502 brings to https://opendata-qa.cern.ch/VM/docs/cms-virtual-machine-2015 (404)

**Comment by psaiz** [comment]
Hi Kati, 

Thanks a lot for the ticket. I'm sorry, but I can't reproduce this one.  If I go to `https://opendata-qa.cern.ch/record/12502`, I don't see any links to `https://opendata-qa.cern.ch/VM/docs/cms-virtual-machine-2015`.  I do see the link to /record/252 in the part of `Use this software in the CMS Open Data VM environment ([CMS VM Image for 2011, 2012 and 2015 CMS open data](https://opendata-qa.cern.ch/record/252))` 

Am I missing something?
Best regards, 
pablo

**Comment by katilp** [comment]
I see it from [How to install a CERN Virtual Machine](https://opendata-qa.cern.ch/VM/CMS/2015) in https://opendata-qa.cern.ch/record/12502:
![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/a2ac8470-96ee-4664-9d39-729f4aac4789)


However, that said: we might as well fix those links in the records themselves, the old forward remained there for some copy-paste from the past.

**Comment by katilp** [comment]
Correction: the link should go to https://opendata.cern.ch/docs/cms-virtual-machine-2015 (not to  https://opendata.cern.ch/record/252 as I wrote earlier)... sorry for the confusion.
