### ISSUE TITLE
Updates on qa: space between columns

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3522]
Records like https://opendata-qa.cern.ch/record/23900 or https://opendata-qa.cern.ch/record/1702 have HTML tables.
We might need to add spacing between the columns for a nicer display see https://opendata.cern.ch/record/23900

And for us in CMS: we might want to add column names to the table...

**Comment by tiborsimko** [comment]
Note that the formatting on PROD has some breathing space there:

![spaces](https://github.com/cernopendata/opendata.cern.ch/assets/517546/052520ec-51ba-4cac-bbed-5b19c1142d77)
