### ISSUE TITLE
CMS: "System details" for NanoAOD

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3525]
For now, we always have something like this for CMS data/MC records

![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/041a24b2-fac8-4bde-a2d3-9c3321aec653)

This is not valid for NANOAOD, we could have instead:

> NANOAOD datasets are in the [ROOT](https://root.cern.ch) tree format and their analysis does not require the use of CMSSW and CMS Open data environments. Recommended container images with the most common libraries for analysis with ROOT and Python tools are available in the following locations ([see guide](https://opendata.cern.ch/docs/cms-guide-docker)):
> 
> gitlab-registry.cern.ch/cms-cloud/root-vnc
> gitlab-registry.cern.ch/cms-cloud/python-vnc

Would that be OK @jmhogan @tpmccauley @clelange ?

**Comment by jmhogan** [comment]
Looks good. "their analysis" is duplicated. I might say "the ROOT tree format".

**Comment by katilp** [comment]
And  @jmhogan, similarly for Usage.

Now:

![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/177484c8-f3a0-48cd-92b2-b65992d86ee8)

Should we have:

You can access these data through XRootD protocol or direct download, and they can be analysed with common ROOT and Python tools. See the instructions for getting started in

- `[Using Docker containers](https://opendata-qa.cern.ch/docs/cms-guide-docker)` (pointing to the new part for ROOT/python containers)
- `[Getting started with CMS NanoAOD](https://opendata-qa.cern.ch/docs/cms-getting-started-nanoaod)` (the new nanoaod guide)

**Comment by tiborsimko** [comment]
> OK for me, we need to figure out how to maintain these.

Do you mean to maintain the information which image is suitable for which dataset, and updating record fixtures accordingly? This is scripted via `data-curation` repository, so if a change is needed, it'll be quick to update records by running a few scripts.
