### ISSUE TITLE
search: old SW record appears first in the list with "Most recent"

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3533]
https://opendata-qa.cern.ch/search?q=&f=type%3ASoftware&l=list&order=desc&p=1&s=10&sort=mostrecent shows this:

![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/b00dee43-6ca3-44ff-a54c-c0ba175d1f9f)

I could not figure out why https://opendata-qa.cern.ch/record/22350 would appear first.

**Comment by psaiz** [comment]
Hi Kati,
 Thanks for the ticket. Note that just after this ticket was opened, we deployed a new version with a couple of fixes regarding the sorting by `most recent`. Going to that link, I get now something like:
 
 
![Screenshot 2024-01-25 at 17 04 12](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/d6ae8477-2405-4f0b-8063-a017140fdb58)

The order in which records are presented there is: 
* First by `date_published`
* In case of tie, `recid`. 

If we look at the request for the [data](https://opendata-qa.cern.ch/api/records/?q=&sort=-mostrecent&page=1&size=10&type=Software), we see that the first two entries are from 2024 (and the first has a higher recid), and the third is from 2022. 

I have the feeling that now it is working as expected. Could you please confirm that this is the case?

**Comment by katilp** [comment]
Closing as fixed, thanks!
