### ISSUE TITLE
ALICE: enrich JSON format?

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#354]
Currently, ALICE datasets are described in JSON format looking like this:

``` json
{
   "Dataset": {
      "name":        "LHC2010h_PbPb_ESD_138275",
      "description": "Pb-Pb ESD data sample at 3.5 TeV",
      "path":        "/eos/opendata/alice/2010/LHC10h/000138275/ESD",
      "files":       3
   }
}
```

The file specifies where the dataset is located; but it does not say anything about individual files this dataset is composed of.

It would be useful to store further information about individual files themselves. Even if ALICE tools may not use it directly, such an information would be useful for housekeeping, bit preservation and integrity checking, exporting to third parties, etc.

Proposal:
- enrich JSON with section about individual files

Example:

``` json
{
    "Dataset": {
        "name": "LHC2010h_PbPb_ESD_138275",
        "description": "Pb-Pb ESD data sample at 3.5 TeV",
        "path": "/eos/opendata/alice/2010/LHC10h/000138275/ESD",
        "files": 3,
        "file_details": [
            {
                "file_path": "/eos/opendata/alice/2010/LHC10h/000138275/ESD/0000/AliESDs.root",
                "file_size": 200762886,
                "file_checksum": "41b466d6eb9bbe978ac70bb96c733ae7",
                "file_timestamp": "2014-09-24 12:32:31"
            },
            {
                "file_path": "/eos/opendata/alice/2010/LHC10h/000138275/ESD/0001/AliESDs.root",
                "file_size": 225890865,
                "file_checksum": "1548a2f4ffab8015c04f378ece2c9442",
                "file_timestamp": "2014-09-24 12:32:35"
            },
            {
                "file_path": "/eos/opendata/alice/2010/LHC10h/000138275/ESD/0002/AliESDs.root",
                "file_size": 222416778,
                "file_checksum": "c0a463c41b3629b2eff0866671887e93",
                "file_timestamp": "2014-09-24 12:32:38"
            }
        ]
    }
}
```

Note: this is just an illustration to stimulate discussion.  The JSON format is nicely evolutive, so we could put lots of useful technical information there, such as root version, etc.

@mgheata What do you think?

**Comment by tiborsimko** [comment]
@mgheata Are we going to update the old JSON files to the new JSON format as well?  See also my 2010 vs 10 comment:

- https://github.com/cernopendata/opendata.cern.ch/issues/772#issuecomment-121968163

**Comment by suenjedt** [comment]
@ArtemisLav @tiborsimko Is anything happening here or do we need to contact M. Zimmermann? Or can it be closed?

**Comment by tiborsimko** [comment]
The old ALICE JSON files are still using the old unenriched ALICE JSON format. Dunno if there are some  data consumers/tools out there for whom we'd have to keep the old format alive... but it's surely safer to keep it that way, unless it is explicitly wanted by ALICE to migrate the old format files.  Let's see about the formats when the forthcoming data batch comes?!

**Comment by tiborsimko** [comment]
FWIW Markus mentioned that the ALICE JSON format is not used by any consumers/tools he knows of, so we could go either way... I suggest to close this and let's see about the format during the next ALICE open data batch.
