### ISSUE TITLE
search: finding authors in the global index 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3555]
The author names do not seem to be indexed anymore in the global index.

E.g. typing "Wunsch" in the search box gives 0 results after the upgrade, whilst it used to find all the datasets and software records that were authored by Stefan Wunsch.

**Comment by psaiz** [comment]
This one is not working... checking

**Comment by psaiz** [comment]
It works on dev. It didn't work on prod, and I had the feeling that it was because the pod was restarted too soon after the configmap had changed, and the change of the INVENIO_SEARCH_INDEX_PREFIX wasn't propagated. After rolling out the web again, it started working
