### ISSUE TITLE
templates: fix display of external images

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3559]
We load external images to display on record pages such is this one:

- https://opendata.cern.ch/record/12360

or documentation pages such as this one:

- https://opendata.cern.ch/docs/observing-higgs-over-one-petabyte-new-cms-open-data

 This broke following recent upgrade.

Here is the list of images locations that we display from:

- `http://cds.cern.ch/record/1456510/files/pictures_samples_dimuonSpectrum_40pb-1_mod-combined.png`
- `http://cms-results.web.cern.ch/cms-results/public-results/publications/HIG-12-028/CMS-HIG-12-028_Figure_004.png`
- `http://cms-results.web.cern.ch/cms-results/public-results/publications/HIG-13-004/CMS-HIG-13-004_Figure_001-a.png`
- `http://cms-results.web.cern.ch/cms-results/public-results/publications/HIG-13-004/CMS-HIG-13-004_Figure_001-b.png`
- `https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=13467&filename=CMSOpenData2012Event.png`
- `https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=13467&filename=CMSOpenData2012H4l.png`
- `https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=13467&filename=CMSOpenData2012HiggsCandidate.gif`
- `https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=13467&filename=CMSOpenDataBinder.gif`
- `https://github.com/cms-opendata-analyses/DimuonSpectrum2012NanoAOD/blob/master/dimuonSpectrum.png?raw=true`
- `https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis/blob/2012/plots/eta_2.png?raw=true`
- `https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis/blob/2012/plots/m_vis.png?raw=true`
- `https://mybinder.org/badge_logo.svg`
- `https://www.github.com/cms-opendata-analyses/HiggsToFourLeptonsNanoAODOutreachAnalysis/blob/master/plots/combined_Higgs_mass.png?raw=true`
- `https://www.github.com/cms-opendata-analyses/HiggsToFourLeptonsNanoAODOutreachAnalysis/blob/master/plots/combined_Z1_mass.png?raw=true`
- `https://www.github.com/cms-opendata-analyses/HiggsToFourLeptonsNanoAODOutreachAnalysis/blob/master/plots/combined_Z2_mass.png?raw=true`

It is probable that this will continue.

Two possibilities how to solve the problem:

1. Allow loading images from anywhere, which may be a security risk, but considering that the web site does not offer any user accounts and any uploads and that all the content is curated before it hits the production, it could be acceptable.

2. Define a list of web sites from where it is allowed to load the images and we'll be simply enriching this list as the new records appear.  This might be preferable, because as we see above, the list of allowed web sites is not huge.

**Comment by psaiz** [comment]
I'll send a PR that goes in the second direction. 

At the same time, the main issue with that is that there is no assurance for the long-term preservation of those entries. There is no waranty that the images would be available in the future. 

For that reason, in my opinion the best way would be to possibiliy number 3:
3. During the creation of those records, upload the images to COD, and then serve them from there.

**Comment by psaiz** [comment]
This has been deployed. There are issues with some browsers with the http://cms-results. It might be better to change those entries  to https://.

I would still prefer the option 3 from the previous comment (putting those images directly in our web server, instead of having references to remote sites)
