### ISSUE TITLE
Decommission ES clusters and hostgroup

### ISSUE THREAD

**Issue by psaiz** [cernopendata/opendata.cern.ch#3566]
The virtual machines used for elasticsearch clusters for prod/qa/dev are no longer needed. The machines can be destroyed.

**Comment by tiborsimko** [comment]
The ES VMs have now been deleted.

Regarding the two OpenStack projects:

- IT CERN Open Data
- IT CERN Open Data - Container Pilot

In theory, these are deletable. In practice, perhaps we may want to keep at least the first one, in case we'd like to make use of OpenStack for a reason or another? I'm OK either way.
