### ISSUE TITLE
UI: unify link decoration across site

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#358]
Now that we have unified link decoration on the home page by introducing common hover effect, the same technique should be used on _all_ the links on the site, e.g. in "For Education", e.g. in on detailed record pages, and elsewhere, e.g. in the search facets perhaps, etc.

(see also past discussions about this in #72, #218, #344 and elsewhere)

**Comment by tiborsimko** [comment]
Moving to someday.

**Comment by suenjedt** [comment]
Something to keep in mind for Open Data on Invenio 3 @sefeg @daslerr. Unified links across site should be tested (once we have a beta-prototype). I am closing for now.
