### ISSUE TITLE
CMS - create the release announcement page

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3613]
Create the release announcement page.

It is a `doc` and the structure is similar to 
https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/docs/cms-completes-run1-heavy-ion-open-data-collection-2023

There seems to be a practice to have the release year at the end of the directory/file name so "CMS releases 13 TeV proton collision data from 2016" being the title, the directory/file name could be `cms-releases-13-tev-proton-collision-data-from-2016-2024`

The directory/file name is not visible to users, the actual link name comes from the field `slug` in the json file

**Comment by tiborsimko** [comment]
We should also update the home page information about having now more than five petabytes by editing the following file:

```
$ rg -i petabytes
• cernopendata/templates/cernopendata_pages/front/main.html
9:          Explore more than <span><strong>four petabytes</strong></span> <br />
```
