### ISSUE TITLE
CMS: Missing " in one of the commands in Getting Started with CMS NanoAOD Open Data

### ISSUE THREAD

**Issue by patinkaew** [cernopendata/opendata.cern.ch#3657]
On [Getting Started with CMS NanoAOD Open Data](https://opendata.cern.ch/docs/cms-getting-started-nanoaod), there is a missing " in one of the commands in section NanoAOD on the ROOT command line.

```t->Draw("Muon_pt,"Muon_pt < 2000")``` --> ```t->Draw("Muon_pt","Muon_pt < 2000")```

**Comment by jmhogan** [comment]
Addressed in #3665 , thanks for catching this!
