### ISSUE TITLE
theme: update download warning modal text

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3664]
**Current behaviour**

When a user would like to download a O(500MB) large file over HTTP web interface, a download warning modal pops up to inform the use that this may not be necessary:

![warning](https://github.com/user-attachments/assets/51d7c2bb-1114-400a-b076-a66d3341ee40)

This text originates from 2014 portal creation without many changes. There are two problems with it:

1. (Mandatory) The text speaks of CMS research-grade data and offers VM download. Now that we have large research-grade data files from ATLAS, the modal information is not fully appropriate. We should make it more experiment-agnostic.

2. (Mandatory) There are now container images offered to users, besides VM images.

3. (Optional) The internet speeds in the world are better now that ten years ago, so we may want to raise the warning file size limit perhaps?

**Expected behaviour**

The modal information should be more experiment-agnostic, so that it would fit both ATLAS and CMS file downloads (and in the future other large files from other experiments).

Alternatively, we should display ATLAS-specific text for ATLAS data, CMS-specific text for CMS data, etc.

**Comment by psaiz** [comment]
Thanks for the ticket. Let's start with the easy one (3):
* Current size: `"CERNOPENDATA_MAX_DOWNLOAD_SIZE", 200000000` (~200 MB). Shall we increases to 1GB?

For the other two, I'll change the message with a proposal and post it here for discussion.

**Comment by psaiz** [comment]
Regarding 2, where can we find the links to those containers? For the images, we have the redirections `/vm/[exp]`. And, on top of that, there is also the `Type -> Environment.VM`.

**Comment by psaiz** [comment]
Another inconsistency is that, since the images are also larger than the threshold, the user will get the same warning while attempting to download the images that we are suggesting :-)

**Comment by psaiz** [comment]
This has been deployed already. Closing the ticket
