### ISSUE TITLE
CMS: generator parameter files missing from eospublic btw records 67399 and 68001

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3701]
@tiborsimko @psaiz Could you check if there was a copy problem for generator parameter files after recid 67399 and before 68001?

E.g. https://opendata.cern.ch/eos/opendata/cms/lhe_generators/2016-sim/gridpacks/67645/powheg.input
for the record: https://opendata.cern.ch/record/67645

What I see in is indeed:

```
eos ls /eos/opendata/cms/lhe_generators/2016-sim/gridpacks
[...]
67395
67397
67399
68001
68003
68005
[...]
```

**Comment by psaiz** [comment]
Thanks for the ticket @katilp, and sorry that those files were missing. I did one more check between the two directories, and copied the missing ones. The link there for the example works for me. Could you please confirm that it also works for you?

**Comment by katilp** [comment]
Cool, thanks, that was quick!
Yes it works now!
