### ISSUE TITLE
Mu primary dataset is missing from the dataset listing

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#406]
http://opendata.cern.ch/search?cc=CMS-Primary-Datasets&ln=en&jrec=11
does not show Mu primary dataset. It only shows 13 even if it says that it is showing 14

**Comment by pherterich** [comment]
Still missing, something @pamfilos can fix when he touches the search part?

**Comment by suenjedt** [comment]
I believe this can be closed. At least for me the counts are correct. 33 primary datasets are shown/listed.

**Comment by katilp** [comment]
Nope, http://opendata.cern.ch/search?cc=CMS-Primary-Datasets&ln=en&jrec=31 now says that is showing 31 of 33, and shows finally only 2 (i.e. after 3*10 of the previous pages results in 3*10 + 2 = 32...)

**Comment by suenjedt** [comment]
Thanks - I don't know why I was not able to count. I also note if you click on the "primary dataset" facet/tag on the left, it adds another dataset (on the last page) so you get to 33. 
@tiborsimko is this a quick fix or need to postpone to Invenio 3?

**Comment by tiborsimko** [comment]
The search pagination is fixed in COD3.
