### ISSUE TITLE
metadata: introduce cross-experiment keywords

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#445]
Another thing we have discussed last week was the addition of cross-experiment keywords e.g. to quickly recognise masterclass datasets.  

@pherterich Can you please add "masterclass" keyword (I guess using the MARC tag 6531) in the corresponding records?  

@katilp @mgheata What other keywords would you suggest to add? E.g. "collision data" vs "simulated data"?  Something else of the kind?

@pamfilos Once keywords are added, you can foresee to amend output templates in order to create links, styled as tags.

**Comment by pherterich** [comment]
I close them as we have a few in place and more (such as simulated data) will be introduced whenever needed.
