### ISSUE TITLE
Redirect cern.ch/opendata to portal?

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#449]
Many CERN websites use the syntax http(s)://cern.ch/XYZ to redirect to the main website (usually http(s)://XYZ.web.cern.ch

Can we have http://cern.ch/opendata redirect to http://opendata.cern.ch

Related requests:
- Can we enable SSL on the portal and will downloads be accompanied by (SHA1?) hashes for verification?
- Can we redirect all old URLs (open-data-demo, open-data etc.) to the new one rather than having the old URLs display the new content? Will be better if we didn't accidentally circulate the old ones.

**Comment by pherterich** [comment]
Will that come with one of the next releases?

**Comment by tiborsimko** [comment]
Done.

**Comment by RaoOfPhysics** [comment]
@tiborsimko: I'm guessing all `opendata.cern.ch` links will re-direct to `opendata.web.cern.ch`, correct? Thanks for this!
