### ISSUE TITLE
data model: decide upon repetitive field instances

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#450]
Recently, MARC tag 581 was changed from non-repetitive single field instance to possibly-repetitive multiple field instances per record.  See PR #437.

As a result, the treatment of JSON data model for `material_publication_note` had to be amended in order to force using lists, followed by necessary amending of the output templates.  See 4de702b3b1a9c633809fed6561abad4654121963 and 9e2b33f73ebe7296700582194ce01c698a5e9140.

This can be tiresome, and, if we expect to export our JSON records to either general public or at least to some friendly third-party services for internal consumption, we would be forcing consumers to change their JSON consuming practices should we revisit this in the future after the open data service is in production.

Hence it would be good to proactively go through our data model file now:

- https://github.com/cernopendata/opendata.cern.ch/blob/pu/invenio_opendata/base/recordext/fields/opendata.cfg

and modify upfront all those field definitions where we expect to have multiple field instances to behave like lists as well.

@pherterich Let's get together and review this one day; best IRL as it will be more productive that way.

@egabancho @jirikuncar Something we may want to review generally for Invenio hefault configurations as well.

**Comment by pherterich** [comment]
Superseded by #779
