### ISSUE TITLE
Feedback mechanism for production use

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#51]
Need a feedback page (unless something else is preferred) for the testing. Can it 
be a button on every page which picks up automatically the page URL, and maybe proposes categories such as
- problems with display or layout
- problems with instructions
- does not provided the intended functionality
- problems with navigations
- purpose of the page unclear
  ...
- free text field 
- eventually a possibility for attaching a screen-shot

**Comment by pherterich** [comment]
Will we do anything else than the sentence we currently have on the about page or should we close this?

**Comment by tiborsimko** [comment]
@pherterich The page footer email link is still not proposing the URL of the given page in the Subject, so I guess we cannot close this yet... unless the points of view have changed?  CC @RaoOfPhysics @katilp 

P.S. My views were briefly summarised above at https://github.com/cernopendata/opendata.cern.ch/issues/51#issuecomment-60761649

**Comment by RaoOfPhysics** [comment]
> The page footer email link is still not proposing the URL of the given page in the Subject, so I guess we cannot close this yet...

FWIW, I concur. :)

**Comment by suenjedt** [comment]
plus forum discussion

**Comment by suenjedt** [comment]
I am closing this as @daslerr and @sefeg make sure that the feedback mechanisms on the new Invenio 3 prod system will become more prominent. I don't think anyone of us has the resources to implement a Forum this year anyway. If you have strong objections, please reopen.
