### ISSUE TITLE
Have "Higgs candidate" visible in the event display file menu?

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#534]
Are the Higgs candidates in diphoton.ig and in 4lepton.ig files? Would be best to have the names in the file menu so that people can easily identify them. Is that difficult?

**Comment by pherterich** [comment]
Any update on this (= which milestone to move it to) or can it be closed?

**Comment by tpmccauley** [comment]
I am in the process of getting my dev code back in sync with the latest. Will address this later.

**Comment by tiborsimko** [comment]
@tpmccauley @RaoOfPhysics Are we OK here?  The visibility of h4l may be achieved by featuring an article...

**Comment by tpmccauley** [comment]
I can address this first thing tomorrow morning
