### ISSUE TITLE
UI: site not working well for MSIE 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#59]
The site currently does not work well for MSIE users.  I'm testing with MSIE 9.0 via CERN WTS:

```console
$ alias wts="rdesktop -d cern.ch -g 1024x768 -a 16 -k en-us -T TS cernts.cern.ch"
```

We could:

1. improve the layout so that it would work with MSIE; this may be worth it if event display and reduced data set JS visualisation works well with MSIE.  @tpmccauley have you checked ?

2. detect the usage of MSIE and say something like:

          It seems you are using MS Internet Explorer 9 for which this site
          has not been optimised. Please consider using Firefox, Chromium, 
          or Safari instead.

   in a gentle way.

Due to the shortage of time, let's start by 2, and eventually implement 2 when time permits.

**Comment by espacial** [comment]
This is fine, we never closed the issue. @tiborsimko, can you do it? :)
