### ISSUE TITLE
system: puppetisation

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#6]
The demo system should be moved from Quattor to Puppet.

**Comment by pherterich** [comment]
Is this fixed?

**Comment by tiborsimko** [comment]
We are using naked OpenStack and/or Docker.  So the core issue (moving away from Quattor) is fixed, though via an unusual direction...

**Comment by tiborsimko** [comment]
(Keeping current architecture, but the move to Puppet can occur one day, in which case we can revive it from the "someday" closed pool.)
