### ISSUE TITLE
CMS and ATLAS logos on ODP

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#600]
CMS updated its official logo not too long ago, the latest version of which can be found here: https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/ShowDocument?docid=3045 (See, specifically, `CMSlogo_color_nolabel_*`.) Can this updated logo be used everywhere on the ODP instead of the much older one currently here?

In addition, I believe ATLAS are also updating their logo and design and might want us to use the latest logo on the ODP. @fsocher: Can you liaise with the ATLAS Communications Group to get the latest files? Claudia Marcelloni / Steve Goldfarb would be a good first-point-of-contact.

Please close this issue when the following are done:

- [x] Replace CMS logo
- [ ] Replace ATLAS logo

**Comment by pherterich** [comment]
I close this because I think this should be fixed once #789 is live
