### ISSUE TITLE
ATLAS higgs machine learning - metadata

### ISSUE THREAD

**Issue by pherterich** [cernopendata/opendata.cern.ch#660]
@tiborsimko I'm outsourcing my questions to an issue here. I had a look at https://www.kaggle.com/c/higgs-boson/data
Do I understand it correctly that the .csv files there get merged into one for the portal?
I guess the documentation is this: http://higgsml.lal.in2p3.fr/files/2014/04/documentation_v1.8.pdf
In terms of a collection, do you want to create a dedicated "ATLAS Higgs machine learning" collection or split the single pieces across the collections? 
I will be at IT tomorrow morning (if the tpg will bring me to work), so I can quickly drop by your office and we can discuss if needed.

**Comment by pherterich** [comment]
DOIs are minted, up to @tiborsimko to close this issue with the last commit to make this visible on prod.

**Comment by tiborsimko** [comment]
The Higgs Challenge 2014 was indeed deployed in January/February on production.
