### ISSUE TITLE
Software records fields in tools collection need reordering 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#663]
The records such as http://opendata.cern.ch/record/200 needs reordering, it is confusing to have
"Use with...", "System details", "Related items" before the actual software records.
It should also give the URL to github first as that's the place where the user will find the
instructions. It should be made clear that downloading the tar file is not necessary, it is there
for back-up/preservation purposes.

**Comment by suenjedt** [comment]
will be addressed after the next data release. Not forgotten!

**Comment by katilp** [comment]
I think this can be closed, for me it is OK, please check and re-open if needed.
