### ISSUE TITLE
CMS Getting started

### ISSUE THREAD

**Issue by espacial** [cernopendata/opendata.cern.ch#665]
Peter Igo-Kemenes has been kindly testing the CMS VM and the getting started tutorial and sent us his remarks. He has good ideas.

I already sent his comments about the visualisation tools to @tpmccauley a few days ago, @katilp what do you think about the rest?

**First experience with the Opendata setup of CMS**
(PIK, Nov. 18, 2014.)

- General remark about the tutorial: the choice of grey letters on grey may be elegant in arts and architecture … but a bit straining for the eyes. [ **#656** ]

**Education branch**
- Visualise detector event
It is very well done. It is nice to be able to see all detector elements separately and in superposition; to put events into the detector and see the activated detector elements, all together and detector-by detector.  All elements are brought together for performing a “visual” event analysis. – Highly educative.

- Visualise data histograms 
The current setup is very “minimal”. There is no statistics information in the histograms. At least, the number of entries should be given; perhaps also the mean-value of all entries …
There is no explanation of the purpose and of how to use the “Set” field. Is it not to select a sub-sample of the events? -  I tried, e.g., to select “M(mu-mu) > 50”, and also “M.GT.50.” … but it d dot work. Please provide precise information about purpose of the field and the format to use. Best: an example of how to select, e.g., events with the Z-boson mass ( 80 < M (mu-mu) < 100).
Small comment : In some cases the log-x scale is not readable; example:  E1-histogram (log-x scale)
A few more histograms could be educative/useful: e.g. missing-pT, number of identified particles/jets, some particle ID information … Also, a few 2D scatter-plots could be useful ( e.g. , in mu-mu events: p1 vs. p2, eta1 vs. eta2, …)

**Research branch**
The installation of the CMS Virtual machine was not obvious.  Using Windows, one needs a 64-bit machine (there is no software for 32-bit Windows). Also, during installation, some unexpected messages occurred (missing items, etc.). – The help of an expert was needed to set up the CMS-VM on a 64-bit laptop. 
Test and validate … was fine, as well as running the demoanalyzer.

**Getting started with CMS data**
- Access to CMS data
The description starts with the access to Analysis Object Data (AOD). On accedes easily to the root system and the long list of Collection of AOD events.  Fine;  but there is no indication of what type of events these collections contain. – It would be helpful if, clicking on one Collection name,  a sort summary would “pop up”.

- An Example  follows,  using the AOD collection of Electrons (recoGsfElectrons_gsfElectrons__RECO.obj.). 
Fine, but this example leads to a “dead end”.  There is a discouraging statement saying that it would be by far too time-consuming to process AOD-s, so Don’t do it, but rather go to derived data sets in the form of PATtuples.
It would be useful/educative to guide the user through the production of a small sample of PATtuples  (10, 100 events …), starting from the AOD sample selected, rather than sending him to the CMSSW Work Book and the CMSSW PAT WorkBook  where he gets lost easily.  - At the end, a few histograms should  be filled to show some of the PATtuple content, as a proof of success.

- Example of using the PATtuple
This is the OutreachExercise2010/DecaysToLeptons,  which is a good example, but the description is a bit short and incomplete.
It should be exemplified how the run.py can be customized.  (For example, use nano run.py to make your changes e.g. in the number of events  maxEv … and/or de desired channel into two or four leptons ).
It is proposed to run first over 100 000 events (a short run of a few minutes). Experience shows that it needs at least 500 000 events to get a meaningful  mass-peak in the Z to two-leptons channel, which takes about 30 minutes.  (How much time does it take to get a meaningful number of entries in the ZZ to four leptons mode?) This should be said.
Also, it would be very useful to get a message from time-to-time, saying that 10%, 20%, … of the requested events have been processed (so that you know that you have time for a coffee). The message which shows up now, stating that it took 0.00033… seconds to process one event is misleading since it is not “real time”.
At the end if the interactive ipython run.py, one gets indeed a mass-plot which one can visualize by typing analyser.makePlot (“massZ”). Fine. – But, what should be done at the end of a non-interactive python run.py ? – Please give instructions for saving and visualizing the histogram (e.g. using thunar . ).
The final mass histograms should hold a minimum of statistical information:  Nbr of events processed, Nbr of entries in the histogram.

**SUMMARY**
The CMS setup for OpenData is altogether well conceived and could be an example for other experiments.

------

Extracting his ideas:

1. 32-bit version of the VM
2. Improvements for the ROOT object viewer (out of our scope)
3. Create a small sample of PATtuples (10, 100 events... ) to test, so it doesn't require so much time to explore it
4. Show examples of customisation for the run.py file (OutreachExercise2010)
5. Propose more than 100000 events for the OutreachExercise2010, as they are not enough to show meaningful results.
6. Show examples on how to check results without ipython
7. Improve the histograms generated.

**Comment by suenjedt** [comment]
Closing - please keep details in mind for future release!
