### ISSUE TITLE
CMS: new release pattuples2010 v1.0.2

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#666]
Integrate new release of @ayrodrig's code pattuples2010 v1.0.2.

**Comment by pherterich** [comment]
@daslerr this is basically a versioning issue, would you like to follow up and keep an eye on it?

**Comment by katilp** [comment]
Is this being followed / done?

**Comment by katilp** [comment]
I believe this is addressed in http://opendata.cern.ch/record/200
Closing
