### ISSUE TITLE
UI: introduce "Take a tour!"

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#68]
Introduce "Take a tour!" facility offering optional guidance og new users through the web site, explaning its functionalities and content.  See prior example on Invenio Labs: https://labs.invenio-software.org/

**Comment by suenjedt** [comment]
Not relevant anymore

**Comment by RaoOfPhysics** [comment]
Is the closing related to #1187?

**Comment by suenjedt** [comment]
Yes. It is outdated. Priority is to move to Invenio3 now. WIth the new design/IA is there, we can decide how to help users to find what they are looking for and use the data/tools.
