### ISSUE TITLE
search: global index stemming

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#687]
As discussed in #570, the stemming behaviour should be improved via updating upstream Invenio. Canonical query example is for the word *multijets*.

**Comment by pherterich** [comment]
Will this be fixed by @pamfilos integrating elastic search?

**Comment by tiborsimko** [comment]
After the applied fix:

-  https://github.com/cernopendata/opendata.cern.ch/issues/570#issuecomment-63755198

the core of the UX problem went away.  And yes, more indexing and searching improvements will come with an Invenio upgrade that will bring Elasticsearch.
