### ISSUE TITLE
Workflow to add new records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#721]
We could define a workflow for adding new items to the portal:
1) express of interest (mail to support list, issue on github...)
2) an approval by the experiment/portal?
3) collect metadata
4) preview the new record
5) release
For point 2), in the CMS side, I will have a chat with the physics convenors next week (in particular, do we need to inform the CMS PAGs for code examples)
For point 4), it would be nice to have a possibility to review the new item with a limited access before it goes public. Would this be possible to implement?

**Comment by suenjedt** [comment]
@daslerr @sefeg relevant for Open Data on Invenio 3. Please close if/once this is adressed.

**Comment by tiborsimko** [comment]
I think we can close this, since we have been having DEV, QA and PROD chain nicely established. (although open, not restricted)
