### ISSUE TITLE
New entry for learning resources

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#756]
Thanks to Sami Lehti, we can propose a new entry for learning resources.
The intro text would be the following:

"Computing Methods in High Energy Physics
This introductory course by S. Lehti is aimed for students with no prior
knowledge of computing methods in high energy physics. Prior knowledge of
some programming language is needed. The course goes through basics of
programming languages in high energy physics (FORTRAN,
C++, python), software for analysis and visualisation (ROOT), some
software for calculating cross sections and branching ratios, simulation
of collisions (event generation), basics of CMS software (CMSSW)
and an introduction to grid computing.
This course is developed in the University of Helsinki for students
interested in experimental particle physics."

and the link to the resource is
http://www.helsinki.fi/~slehti/ComputingMethodsInHEP/ComputingMethodsInHEP.html

Sami is adding relevant warnings for the Univ. Helsinki specific part of the instructions
(e.g. use of local computing resources) and we think that all exercises can be done 
with the CMS open data image available from the portal.

**Comment by RaoOfPhysics** [comment]
One tiny bugbear on my side: Can we ensure that "high-energy physics" is hyphenated everywhere on the CODP and related materials? :)

**Comment by pamfilos** [comment]
@katilp @RaoOfPhysics : is there an image( and a caption) to use with "Computing Methods in High Energy Physics", in a similar way we did on other Learning Resources?

ex: http://opendata.cern.ch/collection/CMS-Learning-Resources

**Comment by RaoOfPhysics** [comment]
@pamfilos: Not that I know of.

@katilp: I looked at the website and I couldn't think of anything appropriate…

**Comment by katilp** [comment]
Nothing directly from the website, but a nice one could if you open some of the lecture note files on a screen and make a snapshot of them. Would that work?

**Comment by RaoOfPhysics** [comment]
@katilp: I considered this, but they look rather bland. They're just text-filled PDFs of the presentations, mostly. Maybe we can discuss this in person?

**Comment by katilp** [comment]
@RaoOfPhysics Ok, we can have a look in person - I'll be back on Monday. For the target audience (potentially univ. lecturers who are planning for a similar course) they still look quite attractive :-)

**Comment by tiborsimko** [comment]
FYI I merged the record, and once we have an illustrative image, we can edit templates of `/collection/CMS-Learning-Resources`.  CC @pamfilos

**Comment by RaoOfPhysics** [comment]
@katilp: Will do.

**Comment by RaoOfPhysics** [comment]
@katilp, @pamfilos, @tiborsimko: How about this?

![comphep](https://cloud.githubusercontent.com/assets/7623019/6043295/a137e258-ac8b-11e4-85dc-61c7ba6b07f3.png)

**Comment by RaoOfPhysics** [comment]
@pamfilos: As agreed with @katilp, can you please use a screenshot of the first page of the first document as the representative image?

http://www.helsinki.fi/~slehti/ComputingMethodsInHEP/CompInHEP_lect1.pdf
