### ISSUE TITLE
http://opendata.cern.ch/collection/ATLAS-Learning-Resources#

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#759]
... when hovering with the mouse over it, a window pops up with information on PAT, which seems to be connected to CMS

**Comment by tiborsimko** [comment]
Indeed, the glossary.js picks term "pat" out of the word "path".  @pamfilos Can you please check for word boundaries?

**Comment by pherterich** [comment]
It now also connects to the glossary from the detailed record pages and the metadata there: http://opendata.cern.ch/record/552 but not consistently in every field. Is that on purpose?

**Comment by tiborsimko** [comment]
Works better on DEV: 

- http://opendatadev.cern.ch/record/552

so this is now just a matter of deploying on PROD.

P.S. @pamfilos The underline style for glossary terms seems identical to the underline style for authors; see the title box which contains two style of links.  Can you amend?

**Comment by suenjedt** [comment]
link style discussed in another issue.
