### ISSUE TITLE
Collection of CMS publications relevant as legacy data & sw documentation

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#763]
Collecting CMS publications/PAS which can be relevant to link to the portal as documentation for CMS 2010 data and sw usage:

Muon identification: http://cds.cern.ch/record/1279140?ln=en
Muon reconstruction: https://cds.cern.ch/record/1456510/files/1748-0221_7_10_P10002.pdf

Particle flow: 
jets, photons: http://cds.cern.ch/record/1279341?ln=en
leptons http://cds.cern.ch/record/1279347/files/PFT-10-003-pas.pdf

Tau reconstruction (fake rates): http://cds.cern.ch/record/1279358/files/PFT-10-004-pas.pdf

Electron reconstruction and identification:http://cds.cern.ch/record/1299116?ln=en

Photon reconstruction and identificatio: http://cds.cern.ch/record/1324545?ln=en

**Comment by pherterich** [comment]
So this should go in CMS-Open-Data-Instructions ? Only the PDF? Or also all the Figures that are on CDS?

**Comment by katilp** [comment]
@pherterich We'll see - they may complement the CMS physics objects documentation. How we present this information depends on how complete a set of these documents can be formed (i.e. do we collect these links in a single page within a portal and will this appear in open-data-instruction ). I believe that a link to CDS should be enough (as we can presumably trust its long-term availability)

**Comment by pherterich** [comment]
Is this something we should start/think about as part of the next data release? @katilp ?

**Comment by katilp** [comment]
Closing as the topics are now covered in the [CMS open data guide](https://cms-opendata-guide.web.cern.ch/)
