### ISSUE TITLE
New entry for CMS tools collection

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#764]
The following proposal arrived to the opendata support from Maria Spiropulu can now be added to the CMS tools collections.

 
Dear Colleagues: 

Javier Duarte is my graduate student at CMS with Caltech and he built a great example analysis with the CMS open data. The code is documented and tested and committed at git and it would be great to include it at 
http://opendata.cern.ch/collection/CMS-Tools

Find the code information below with the README and you can ask Javier more details directly (on the cc). 

Maria Spiropulu | Professor of Physics | Division of Physics Mathematics and Astronomy 
California Institute of Technology  [Contact details REDACTED – @RaoOfPhysics]
 

https://github.com/jmduarte/SUSYBSMAnalysis-RazorFilter

and documented in the README. It outputs two formats one is a simple text file and the other is a ROOT tree. I made a Rsq vs. MR distribution for a small subset of the 2010 data (ran on 100k events).

**Comment by katilp** [comment]
@pherterich This is structurally same as http://opendata.cern.ch/record/552
@jmduarte Could you kindly have a look at the record above and provide the corresponding information for your example so that Patricia can complete the record?

**Comment by pherterich** [comment]
Should this get a DOI, too? Will we copy this in "our" GitHub repository/institution? I forgot already what we decided...

**Comment by jmduarte** [comment]
Hi all,

Here are some more details. One question is should I send you an example csv output to post as well?

csv file output ~20k events:
https://dl.dropboxusercontent.com/u/4694200/MultiJetRun2010B.csv
 
tar-ball of GitHub directory:
https://dl.dropboxusercontent.com/u/4694200/SUSYBSMAnalysis-RazorFilter.tar.gz

Thanks!

Javier

Description

This package is a filter that selects events from the MultiJet primary dataset from the CMS open data release, and computes the razor variables MR and Rsq, used in supersymmetric particle searches. More details on the razor variables can be found in http://dx.doi.org/10.1103/PhysRevD.90.112001. In particular, the event is selected if there are at least two "Paticle Flow" jets with pT\>60 GeV and |eta|\<3. A csv file and a ROOT file containing MR, Rsq, the four-momenta of the two megajets, HT, MET, the number of jets, and the number of b-jets (using the kinematic requirements of pT\>40 GeV and |eta|\<3) for each event is produced.

URLs

https://github.com/jmduarte/SUSYBSMAnalysis-RazorFilter

How can you use this?

See the run instructions in

https://github.com/jmduarte/SUSYBSMAnalysis-RazorFilter

Use with.. 

Use this with the MultiJet primary dataset in AOD format from Run B of 2010 /MultiJet/Run-2010B-Apr21ReReco-v1/AOD (http://opendata.cern.ch/record/609)

System Details 

Use this code with the CMS Open Data VM environment
Software release: CMSSW_4_2_8 
CMS VM Image (http://opendata.cern.ch/record/250)

Related items 

The output are files in csv format such as Dimuon event information derived from the Run2010B public Mu dataset (http://opendata.cern.ch/record/700)

Characteristics

Software: 1file 43 kB

Files

SUSYBSMAnalysis-RazorFilter.tar.gz

**Comment by katilp** [comment]
@pherterich Do you need more info on this? This should be similar to record 552.

**Comment by pherterich** [comment]
Sorry, fixing the last small things now and then it's on @tiborsimko to finish it. Should we create a separate entry for the csv file?

**Comment by katilp** [comment]
@pherterich @tiborsimko Would it be possible to have this before the end of the next week?

**Comment by tiborsimko** [comment]
> Should we create a separate entry for the csv file?

If we do store the output file and describe the meaning of its columns and show it in the previewer, then I'd say yes.

But @katilp @jmduarte are best positioned to decide whether it is worth storing and showing this concrete output file, or whether we'd just describe the generated content semantics...

**Comment by jmduarte** [comment]
It could be worthwhile to show the explicit output.

The columns are described by the header:
Run,Lumi,Event,MR,Rsq,E1,Px1,Py1,Pz1,E2,Px2,Py2,Pz2,HT,MET,nJets,nBJets

Run,Lumi,Event are the run number, lumi section, and event number for this event.
MR and Rsq are the values of the razor variables.
E1,Px1,Py1,Pz1 is the four-vector of the leading megajet (with the largest transverse momentum).
E2,Px2,Py2,Pz2 is the four-vector of the subleading megajet (with the largest transverse momentum).
HT is the scalar sum of the transverse momentum of the jets.
MET is the magnitude of the vector sum of the transverse energy of the particles in the event.
nJets it the number of jets with transverse momentum above 40 GeV.
nBJets is the number of b-tagged jets with transverse momentum above 40 GeV.

Thanks,

Javier

**Comment by tiborsimko** [comment]
@jmduarte Thanks, I'll create a new issue for this.
