### ISSUE TITLE
Change copyright in footer

### ISSUE THREAD

**Issue by pherterich** [cernopendata/opendata.cern.ch#784]
change the copyright in footer to 2015 (can that be something dynamic that automatically updates the year maybe?) @tiborsimko

**Comment by RaoOfPhysics** [comment]
@TimSmithCH can advise on this, but I don't believe dynamically changing the copyright is the right approach: copyright is assigned from the time of creation, so older content will still be copyright 2014…

**Comment by pherterich** [comment]
what about the 2014 - present version like http://hepdata.net/ does and then we have details for the single records? @RaoOfPhysics @TimSmithCH

**Comment by TimSmithCH** [comment]
The date refers to the date a work was first published, so should never be removed (otherwise you are dropping your claim), but can be added to when major revisions to the work are published. In terms of a dynamic website that is incrementally improved, this usually translates into either "2014, 2015" style or "2014-present". When the copyright refers to data that is not changed, it should simply be left stating the year the work was published

**Comment by tiborsimko** [comment]
Do we need to display a copyright statement on every single page?  Isn't it sufficient to simply expand  properly the Terms of Use or another appropriate About page?

**Comment by TimSmithCH** [comment]
Whilst not strictly necessary, it is common practice, and eases specification of licences on pages that require them. I would vote to keep it...

**Comment by pherterich** [comment]
We have it in the footer which is shown on every page anyway. And the records come with a disclaimer for each of them. However this is the CC0 standard one for most of the records currently which might not always be correct.

**Comment by tiborsimko** [comment]
OK, changing the copyright information in the general page footer to "© 2014, 2015 CERN", which is BTW what we do for the source code as well.

(Note that we had "© 2014 CERN Open Data" before, with the "service name" in the role of the visible "copyright holder", as it were. Unsure about the legal status of the CERN Open Data "entity" as a possible copyright holder?)

**Comment by TimSmithCH** [comment]
Thanks Tibor, indeed it is correct to change to use the "CERN" local entity, since "CERN Open Data" isn't a legal entity.
