### ISSUE TITLE
CMS Derived Datasets navigation and display

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#785]
I find the navigation confusing. There are 37 records in total. One sees 10 of the records at http://opendata.cern.ch/collection/CMS-Derived-Datasets (expected). When one clicks "more" it shows records 11-20 (expected) which is page 2. Pages 3 and 4 show the remaining records. So far, so good. 

What I find confusing is that I would have expected that the records shown on the main derived datasets page were the same ones on page 1 (i.e. records 1-10). This is not the case, and I initially thought that the masterclass file records (in 1-10) were missing.

Compare:

http://opendata.cern.ch/collection/CMS-Derived-Datasets
http://opendata.cern.ch/search?cc=CMS-Derived-Datasets&ln=en&jrec=1

Perhaps records 1-10 should be shown on the main page and then "more" goes to page 2 

or

keep the main page as it is and "more" goes to page 1. 

I have a slight preference for the latter as the main page currently shows files derived from the primary datasets.

**Comment by tiborsimko** [comment]
Yes, I agree the order should be kept equal. 

One might even wonder whether it is worth to display records on the first "static" collection page at all, and not point people to the second "dynamic" one?  E.g. we could display some static-like information on the collection splash pages, plus advertise the dynamic search more there.

**Comment by tiborsimko** [comment]
This has been addressed in the release of COD3.
