### ISSUE TITLE
Standardising language across the portal

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#786]
Should we use BrE (and related style) across the entire portal, independent of who is submitting the content to it? There seems to be inconsistency in things like comma placement (inside or outside quotation marks) and spellings due to a variety of content submitters.

CC for comment: @TimSmithCH, @tiborsimko.

**Comment by RaoOfPhysics** [comment]
If we decide to do so, I volunteer to check existing text and also future additions.

**Comment by tiborsimko** [comment]
:+1:

**Comment by TimSmithCH** [comment]
I agree to standardization :)
If you can agree on what BrE is, then go for it, I will help!

**Comment by RaoOfPhysics** [comment]
@TimSmithCH: I'll edit so we have BrE for spellings (we can agree on a convention when there are multiple possibilities -- -zation / -sation), and I will use a consistent style throughout. :)

**Comment by tiborsimko** [comment]
FWIW I like `-ise` that is recommended by many BrE guide styles and spell checker defaults. See also https://github.com/cernopendata/opendata.cern.ch/issues/160

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Indeed, and this is the recommendation at CERN as well (with the exception of the word "Organization" in the CERN's name).
