### ISSUE TITLE
Provide list of possible analyses, comparing with published papers

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#787]
For CMS data, can we suggest what kinds of analyses may be done, depending on which papers the collaboration published with a similar amount of data as released on the portal?

@tpmccauley presented some ideas at the IPPOG meeting (https://indico.cern.ch/event/354555/contribution/17/material/slides/0.pdf#32) and perhaps we could expand on this.

CC for comment: @katilp, @tiborsimko.

**Comment by katilp** [comment]
I strongly support. This would go somewhat in line with what we have been planning for CMS, i.e define for each physics object a corresponding (simplified) analysis, which can be offered as an analysis example on one hand, and part of which (or pieces of which) could be used for validation purposes on the other hand. Dilepton spectrum is an obvious candidate for electrons and muons,
we will need to define the others. Reproducing the published analysis may be difficult, but we should be able to refer to the published analyses and briefly discuss the eventual differences to simplifications.

**Comment by RaoOfPhysics** [comment]
@katilp: Great! How would you propose we pursue this? How may I help?

**Comment by katilp** [comment]
@RaoOfPhysics It would indeed be helpful if we could meet and draft a message to POG (and if relevant) PAG group conveners to ask them to nominate the simplest possible analysis which could be (and has been) undertaken with their physics object. Do you have time to meet this week?

**Comment by tiborsimko** [comment]
> define for each physics object a corresponding (simplified) analysis

Could be perhaps linked from the glossary, which may be considered as the current "canonical place" for information about physics objects...

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Wouldn't this be a better location? http://opendata.cern.ch/about/CMS-Physics-Objects

**Comment by tiborsimko** [comment]
@RaoOfPhysics Yes, indeed, but then we may want to link to that page from the glossary, to ease navigation (and information discovery) for casual visitors... BTW the current enriched glossary that was merged a few days ago is deployed on DEV, if you'd like to have a look.

**Comment by RaoOfPhysics** [comment]
> BTW the current enriched glossary that was merged a few days ago is deployed on DEV, if you'd like to have a look.

Looks good! One problem: the glossary doesn't seem to display the hover-text when looking at some plurals. So "electrons" works, but "muons" or "particle jets" doesn't. Creating a new issue.

**Comment by suenjedt** [comment]
@katilp @daslerr @sefeg regarding this "list of possible analyses, compared with published papers" 
- Is this something to keep in mind for the "stories" on the new Open Data?
- If so , what about a writing sprint to create the content, e.g. this one? I think we talked about that idea already, but wanted to bring it up in this context again.

**Comment by daslerr** [comment]
Yes, I think that's definitely something that would fit with the stories, as long as CMS is still interested. @katilp and @RaoOfPhysics Have example analyses already been nominated?

**Comment by tiborsimko** [comment]
@suenjedt @daslerr @sefeg Stories would be a good "general public entry point" to make awareness of the analyses, but the analyses themselves would still have their own records, in my eyes, such as http://opendata.cern.ch/record/234. In the record we'd express the analysis details almost in the CAP style, preserving analysis code, linking to particles, etc.  In my eyes, "stories" target the general public audience, and "records" target the advanced data science audience, as it were. Often the stories can live alone and target the two audiences.... but as soon as we have some software to preserve, and some DOIs to mint, then a record will be created in addition to stories.

**Comment by katilp** [comment]
Closing as the original suggestion is now covered in the updated https://opendata-qa.cern.ch/docs/cms-guide-for-research
