### ISSUE TITLE
Update W-path and Z-Path data

### ISSUE THREAD

**Issue by fsocher** [cernopendata/opendata.cern.ch#790]
The derived dataset currently available on the portal is the old masterclasses W-path dataset.

What needs to be done:
- upload the new datasets for the W-path and Z-Path
- create the needed metadata

**Comment by tiborsimko** [comment]
- [x] transfer files to EOS (@fsocher @tiborsimko)
- [ ] create descriptive records (@fsocher @tiborsimko)
