### ISSUE TITLE
Glossary terms not displaying on hover for plurals

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#797]
In the DEV channel, the glossary terms don't appear when the words are in plural form, for example here: http://opendatadev.cern.ch/about/CMS

- "electrons" works, but
- "muons" and "particle jets" don't

**Comment by tiborsimko** [comment]
We may need to enrich the glossary with plural terms.  E.g. compare electron:

```
"term": ["Electron","Electrons"],
		"anchor": "electron",
```

with muon:

```
	"term": "Muon",
		"anchor": "Muon",
```

https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/static/json/glossary.json

**Comment by tiborsimko** [comment]
@RaoOfPhysics Can you please take care of this?

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Ah ha! I see.

Ok, can work on this. From which branch should I start?

**Comment by tiborsimko** [comment]
The `master` branch, please.  The new ALICE data is going there soon, and then we should be ready for QA and final PROD deployment.

**Comment by RaoOfPhysics** [comment]
On it.
