### ISSUE TITLE
Author name format in Tools collection

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#800]
http://opendata.cern.ch/collection/CMS-Tools

Can it say

> `Rodriguez Marrero, Ana` and `McCauley, Thomas`

instead of

> `Rodriguez Marrero Ana` and `McCauley Thomas`?

i.e., in the `Last Name(s), First Name(s)` format with a comma separating them?

**Comment by katilp** [comment]
Closing as outdated and the CMS sw tools now have the CMS open data group as author.
