### ISSUE TITLE
Mint DOIs for ALICE data

### ISSUE THREAD

**Issue by pherterich** [cernopendata/opendata.cern.ch#802]
Mint DOIs for the newly uploaded reconstructed data

**Comment by pherterich** [comment]
Activate DOIs in DataCite

**Comment by pherterich** [comment]
@tiborsimko, I just had a look at the ALICE reconstructed datasets and they are all missing field 260 $b CERN Open Data Portal, 260 $c should become 2016 when we release them and 2012 as the year of data taking should go to 264_0$c. Is this something you can do automatically once we move the data to prod or should we fix it?

**Comment by tiborsimko** [comment]
@pherterich @AnxhelaDani I can do some of those easily, e.g. replacing year, but in order to add new fields here and there it may be better if you do it yourself.

**Comment by AnxhelaDani** [comment]
- [ ] Add missing fields & update records with more information [see https://github.com/cernopendata/opendata.cern.ch/pull/1186]

- [ ] Activate DOIs in DataCite
