### ISSUE TITLE
Publish presentations and other material on the CODP

### ISSUE THREAD

**Issue by pherterich** [cernopendata/opendata.cern.ch#812]
As mentioned in several conversations already, I thought it would be nice to have a collection on the portal that contains outreach material (such as conference presentations, the poster by @katilp 's summer student..) and publications (CHEP). People ask regularly for slides or more information and it would be great to have the material citable with a DOI.
@tiborsimko do you have a suggestion on how to name the collection or if there's a better way of including them nicely than a separate collection?

**Comment by RaoOfPhysics** [comment]
Can we perhaps use something like the [IPPOG Resources Database](http://www.espncricinfo.com/) or CDS for this instead, and keep the portal focused on data and tools?

**Comment by suenjedt** [comment]
Cricket?

**Comment by pherterich** [comment]
If something else, I vote for a zenodo community which we link to from the about page.

**Comment by suenjedt** [comment]
Yes, a Zenodo collection might be a good idea.

**Comment by RaoOfPhysics** [comment]
Thirded.

**Comment by pherterich** [comment]
As we see the need to put out our material in a citable way, if there's no contradiction to creating a Zenodo collection by tomorrow, @AnxhelaDani will set it up on Friday.

**Comment by AnxhelaDani** [comment]
If there are no objections, I will create a Zenodo community: "CAP-CODP Additional material" where we can collect all the documentation that is produced for CERN Analysis Preservation and Open Data. 
Please let me know, so I can set it up.

**Comment by AnxhelaDani** [comment]
As there are no objections so far, I will create the Zenodo community.

**Comment by pherterich** [comment]
The first content can be found here now: https://zenodo.org/collection/user-cap-codp Feel free to upload any material that you have or send it to us so we can add it. @katilp could we put Harri's poster there he presented in summer?

**Comment by katilp** [comment]
Yes, Harri's poster can go there. Thanks!

**Comment by pherterich** [comment]
Closing this as most of the content is shared there now.
