### ISSUE TITLE
Missing links in the VM record

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#815]
The CMS VM record http://opendata.cern.ch/record/250 does not show the links under Validation and
Issues and limitations, neither are the contextualisation scripts available under files as written.

**Comment by pherterich** [comment]
It's all in the MARCXML, @pamfilos / @tiborsimko can one of you check the template please?

**Comment by katilp** [comment]
Any news on that? We will soon setup the new VM and it would be very useful to have this information easily available

**Comment by katilp** [comment]
The text under "Data selection" is misleading. It is the image itself that is available under "Files" at the moment, not the scripts (those are the ones that  we would need now). In any case, it is probably not a good idea to have the contextualization scripts under Files in this record as it would be confusing for the users. But they need to be somewhere...

**Comment by tiborsimko** [comment]
- [x] Validation: the link is now shown on DEV http://opendatadev.cern.ch/record/250
- [ ] Issues and limitations: I see that `556_y` is a new field that is not in our data model.  @tiborsimko can take care of that.
- [ ] :+1: for putting contextualisation scripts into a separate record and link there. @pherterich @AnxhelaDani can you take care of this?

**Comment by katilp** [comment]
NB, the contextualisation script record needs a year as well (for 2010 data).
Can this be added to the title as well?
There will be another record for 2011.  Thanks!

**Comment by tiborsimko** [comment]
All done on my side, validation and issues are now displaying properly (locally).  Passing the issue to @pherterich for the creation of contextualisation records...

**Comment by pherterich** [comment]
@katilp with another record for 2011 (see #851 ) you mean a record for contextualisation scripts or should we always have a "double record" for each year with the VM image and the contextualisation scripts linked?

**Comment by katilp** [comment]
@pherterich Yes, I mean another set of contextualization scripts. I think it is better to keep the all the records separate (i.e. two separate records for VMs of 2010 and 2011 and two separate records for their contextualization scripts). Would that be OK?

**Comment by pherterich** [comment]
@katilp yes, that makes life for us way easier :-). We'll prepare something we can iterate on for Wednesday. Thanks!

**Comment by pherterich** [comment]
@tiborsimko a while back we also discussed having a record for the general CERN VM? Do you think that makes sense to have and link there from the contextualisation scripts?

**Comment by tiborsimko** [comment]
@pherterich We do have a particular CernVM record for 2010 http://opendatadev.cern.ch/record/250

**Comment by pherterich** [comment]
@tiborsimko that's the CMS VM, I was talking about the general CERN VM you have to apply the contextualisation scripts to to get the CMS VM. I think I even have that one in my inbox, which I can add here, then we can decide if we deploy it or not.

**Comment by tiborsimko** [comment]
@pherterich OK, I see what you mean.  WRT general CernVM, we only have some informative description in the About page:

- http://opendata.cern.ch/about

It would be good indeed to promote it more via independent records with DOIs (for each released version).

**Comment by pherterich** [comment]
@tiborsimko do you have a suggestion on how to name this not-experiment specific collection? In the info for the contextualisation scripts, I can't find which versions of the CernVM is used and which ones we should catalogue. We should definitely talk to the CernVM team if we want to assign any DOIs just to check if it's okay with them and to make sure they can update their homepage accordingly.

**Comment by tiborsimko** [comment]
The currently available non-experiment collections are:

- Author-Lists
- Data-Policies

We could create a new one e.g. "Tools", but it would seem empty... unless we put together the experimental tools there too? (ALICE-Tools, CMS-Tools, ATLAS-Tools, LHCb-Tools)  Just thinking out loud...

**Comment by pherterich** [comment]
@suenjedt @daslerr this is going the way of the DOI assignment discussion you started, I'll pass this on to you.

**Comment by katilp** [comment]
@suenjedt The original problem has been solved, can I close this or is there some further things to finalize in the discussion above?

**Comment by tiborsimko** [comment]
I'm attaching the contextualisation scripts...
