### ISSUE TITLE
Terms of Use link not clickable in Safari

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#816]
link at the bottom of the start page. it is clickable in other browsers though.

**Comment by tiborsimko** [comment]
Interesting... Is it the same on http://opendatadev.cern.ch/?

**Comment by jirikuncar** [comment]
The problem is that the logo overlaps the links.

![image](https://cloud.githubusercontent.com/assets/189798/9795481/3a35723e-57f1-11e5-80fa-84d3d4de9ad0.png)

The custom class/css should be removed from `<div class="center-block legal">` and moved inside same row to follow correct text flow.

**Comment by tiborsimko** [comment]
@pamfilos Have you looked at fixing this?

**Comment by katilp** [comment]
the links are not clickable on chrome either
