### ISSUE TITLE
CMS: create validation code records

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#819]
We will need a new category for "CMS validation code": each CMS primary dataset will have a connected validation job, which will reproduce some selected results.
Each validation code record will contain the code, brief instructions, the expected results (a plot or else), and the link to the primary dataset which it is meant to validate.
The primary dataset records should then have a link added to its validation code under "validation".
The primary purpose of the validation code is the validation, so not all of them are necessarily of "example" quality, but some of the can be and in that case can appear as examples in the "CMS tools" category as well.

The validation work has been done by Achim Geiser and his students in DESY group and we hope to have the validation records uploaded quite soon.

**Comment by katilp** [comment]
@tiborsimko @pamfilos ? Any news on this? Do you think it can be done?

**Comment by pherterich** [comment]
Can we "mix" this with the list of validated runs from last year? Rename the collection to CMS-Validation and then make clear in the keywords if it's a list of runs or a script or documentation etc. From the metadata needed, it doesn't sound overly complicated to me, we might need to adjust some templats. We can discuss it this afternoon.

**Comment by pherterich** [comment]
@katilp I leave the issue with you until you ping us for adding the validation scripts when they're ready.

**Comment by tiborsimko** [comment]
Note: we have introduced a new collection "CMS Validation Utilities", see https://github.com/cernopendata/opendata.cern.ch/issues/820#issuecomment-156970443

- http://opendatadev.cern.ch/collection/CMS-Validation-Utilities

so I'll change the issue to reflect that we only need records to populate it.
