### ISSUE TITLE
New 2011 CMS records 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#820]
How do we plan to proceed with the new records? I remember discussing whether moving away from the current scheme to something closer to CAP. Is this still an option?

Independently from that choice, from the CMS  side, we could start providing metadata for the collision primary datasets (24 in all)? Should we look how to do it in automated way, or rather do it by hand?
NB that the number of collision primary datasets will not be much larger than this for any release,
so it would not be a big problem to do it by hand. The efforts could then go in thinking how to extract the metadata for the MC (400 datasets), for which the information maybe slightly different than that of the collision data

**Comment by pherterich** [comment]
With the time we have left I don't see us moving to something like CAP. @tiborsimko  might have ideas on how to automate the procedure as much as possible (primary datasets and MC, especially getting metadata out of DAS) before @AnxhelaDani and me do the rest manually. Maybe you can start thinking already about the additional information we will need for MCs and where to get it and how much texts on limitations etc. have to be created manually and then we can have a short meeting on that?

**Comment by katilp** [comment]
The basic info for MC comes from DAS. I'm finding out how to extract the additional info for MC (generator settings i.e. the input parameters for the MC generator step). They are certainly extracted from two different sources: for pythia (the most commonly used generator program), they can be extracted from the CMS-internal McM-database, for other generators, they have to be extracted from the data file itself. I would like to do the latter step when the files have been transferred to eospublic, as the script that reads the event header from the file is actually a cmsRun job, which can then be used to test that everything is in order and the files are readable.

We could meet at the end of the week or early next week to discuss more in detail.

**Comment by katilp** [comment]
BTW for the move to another schema: if you think that you should do it, there is no pressure from our side not to do it (unless it takes months...). I do not know whether it has impact at all, but thinking simple-minded it looks easier to make this move before we load the system with hundreds of MC records and tens of other stuff :-)

**Comment by katilp** [comment]
@pherterich Could we meet to discuss?

**Comment by pherterich** [comment]
@tiborsimko we ran out of sensible fields, so we suggest a local note field. After consulting the Invenio MARC bible, we'd go for 593$a generator $b Global Tag. If it's fine to conflict with the other Invenio MARC, 938 analog to 538 would be nicer, I leave the decision to you. Other suggestions are welcome, too, obviously.

**Comment by tiborsimko** [comment]
Notes from live discussion: (can be spit away into separate tickets)
- data: create new collection "CMS Simulated Datasets" for MC
- data: create record template automatically
- UI: create yearly tabs (2010, 2011) for:
  - CMS splash page boxes for datasets/tools/instructions http://opendatadev.cern.ch/collection/CMS
  - CMS VM pages http://opendatadev.cern.ch/VM
  - CMS VM: besides tabs 2010, 2011, there should be directly anchored links to "how to test and validate" sections
  - Getting Started yearly tabs
- UI: bookmarkable URLs for 2010 and 2011
- data: create new collection "CMS Validation Utilities" containing both Runs and Code
- previewer: non-webgl compliant browsers?

**Comment by tpmccauley** [comment]
https://github.com/cms-outreach/ispy-analyzers/blob/Run2011A/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt

**Comment by pherterich** [comment]
@katilp Maybe the validated runs should also have a license? They are not really code or data, but it's better to have it if it's easy for you to decide on one.

**Comment by tiborsimko** [comment]
The primary datasets and event display files are now loaded on DEV:

- http://opendatadev.cern.ch/search?p=Run2011A

Some observations:

- There are 20 primary datasets but only 19 event display records. @katilp @tpmccauley Is this OK?

- There are two FIXMEs in the primary datasets metadata, (1) number of events, (2) how the data was selected (which requires a link).  @pherterich @AnxhelaDani can you take care of updating this?

- It would be good to retrieve all records when people type keyword "Run2011A" to the search, like in my above-mentioned link.  I'd propose to update all records (e.g. validation runs http://opendatadev.cern.ch/record/1001) to store this string "as is" somewhere in the record. 

- Ditto for past records to respond to "Run2010B" which currently gives:
   - http://opendatadev.cern.ch/search?p=Run2010B 

 We could use this "run" field later in fielded queries (`experiment:cms run:Run2010B`) and in search facets UI.  If you agree, let's make a new issue for this.

**Comment by tiborsimko** [comment]
Status update: new collections "CMS Simulated Datasets" and "CMS Validation Utilities" are created.
@pherterich Can you please provide MC data template so that I can generate records?

**Comment by pherterich** [comment]
template will come tomorrow morning. Some questions for @katilp:
- is there an easy way (similar to the primary datasets) to translate the dataset names into something human readable?
- does each MC dataset have limitations, selection criteria, re-use instructions? (for validation, there's a mail already to confirm)
- are MC datasets related to a specific run? They are linked to some in DAS, e.g. "Run 1", but is that helpful and should be included?
- I created a potential field for the pile up dataset. Let me know if we should keep and fill it.

**Comment by katilp** [comment]
@pherterich 
* Data set names: I'm trying to find the human readable names, but I'm afraid it is not straight-forward - is the document that I sent earlier of any use in this?

* "How were these data selected" of primary datasets should become "How were these data generated" and there we should provide the generator parameters we discussed earlier with Josh (wip)

* "How can you use these data?" can stay the same, but with a reference to the data-taking year (we need to add the year for the collision datasets as well, at least in the links)

"Issues & Limitations":
These datasets correspond to the collision data collected by the CMS experiment in 2011.

(indeed, the MC datasets are not tied to one run, but rather to a year of data-taking)

Then we have to add the information about the pile-up, but I will have to see where is the best place for it. This is independent of the fact whether we provide the pile-up file itself, the pile-up is already included in the datasets and we have to give some information about it.

**Comment by pherterich** [comment]
@katilp thanks for the quick reply!
We will investigate the human readable names. Nothing Tibor can easily create then, that's all I need to know for now. 
Year of data taking is included and I leave the title of the pile up dataset in, too. Then we can see if we link to records or some documentation there and play around with the display of things.

**Comment by tiborsimko** [comment]
Live discussion:
http://opendatadev.cern.ch/record/1304/export/xm
- need to add 538 "Recommended release for analysis: CMSSW_5_3_32"  (to all records)
- ditto for primary datasets
- ditto for 2010 datasets (`CMSSW_4_2_8`)

**Comment by tiborsimko** [comment]
Live discussion:
- populate CMS SW from DAS; there are two SWs:
  -  from inside MC files `"release": "CMSSW_5_3_23_patch1"` -> "Reconstruction step release: ..."
  -  from the parent dataset -> "Generation step release: ..."
  - ditto for global tag, extract from parent dataset name

**Comment by tiborsimko** [comment]
Live notes with @katilp about `output-config-1` mining from DAS:

- dataset
  - HLT
  - RECO
- parent
  - SIM
- grandparent
  - LHE

**Comment by katilp** [comment]
@tiborsimko In the record field "How were these data generated?", together with the different steps (LHE, GEN, RECO, HLT), for those records having LHE, we can add the following:

To extract the exact LHE configuration, you can use the following script available in the CMS working environment (link to the getting started instructions)  on the CMS Open Data VM (link to the VM instructions):
dumpLHEHeader.py input=file:somefile.root output=testout.lhe
where "somefile.foot" is one of the root files in this dataset.
