### ISSUE TITLE
"to pat" (a verb) referred to as PAT (format) in the instructions :-)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#821]
On page http://opendata.cern.ch/getting-started/CMS the verb "pat" is highlighted and hovering over it pops up the definition of PAT....

**Comment by RaoOfPhysics** [comment]
Can confirm:

![firefox - - screen shot 3 nov 2015 08 38 30](https://cloud.githubusercontent.com/assets/7623019/10903084/4b2df450-8206-11e5-9703-2dcdb3f64bb8.png)

**Comment by RaoOfPhysics** [comment]
@tiborsimko, @pamfilos: What should I do to fix this?

**Comment by tiborsimko** [comment]
Thanks, @pamfilos can take care of this from now.
