### ISSUE TITLE
Cataloguing of relevant CMSSW releases

### ISSUE THREAD

**Issue by pherterich** [cernopendata/opendata.cern.ch#823]
@katilp can you put the list of releases we should include here? Thanks!

**Comment by katilp** [comment]
The two releases for open data are

CMSSW_4_2_8
CMSSW_5_3_30

**Comment by pherterich** [comment]
None of them are in Zenodo yet. Who can point us to the GitHub release we should take the tarball of? @sextonkennedy maybe?

**Comment by katilp** [comment]
@sextonkennedy certainly knows best, what I can see is
https://github.com/cms-sw/cmssw/tree/CMSSW_4_2_X and
https://github.com/cms-sw/cmssw/tree/CMSSW_5_3_X 
are the areas for the second digit level releases, but I'm not sure how to handle the last digit

**Comment by sextonkennedy** [comment]
Is this for the 2010 data? or for the 2011?

Cheers, Liz

On Nov 12, 2015, at 12:03 PM, Patricia Herterich <notifications@github.com<mailto:notifications@github.com>> wrote:


None of them are in Zenodo yet. Who can point us to the GitHub release we should take the tarball of? @sextonkennedy<https://github.com/sextonkennedy> maybe?

**Comment by katilp** [comment]
4_2_8 is for the 2010 data, 5_3_30 will be for the 2011 data (and later 2012)

**Comment by sextonkennedy** [comment]
Yes, those will work.  We generally recommend that people take the latest tag along a branch which for these series would mean much higher last digits, but Kati has said that your use case is not sensitive to the bug fixes so maybe you do not need follow this recommendation…

On Nov 12, 2015, at 2:31 PM, katilp <notifications@github.com<mailto:notifications@github.com>> wrote:


4_2_8 is for the 2010 data, 5_3_30 will be for the 2011 data (and later 2012)

**Comment by pherterich** [comment]
@katilp I found the direct links :smile: I guess we have to take the tarballs available at https://github.com/cms-sw/cmssw/releases/tag/CMSSW_5_3_30 
and https://github.com/cms-sw/cmssw/releases/tag/CMSSW_4_2_8 ?

**Comment by pherterich** [comment]
@sextonkennedy Regarding metadata: do you have any information you think should be connected with an entry for the software? Links to papers, pages etc., anything people need to know to understand? Also, did you decide on a license already?

**Comment by sextonkennedy** [comment]
Hi @pherterich, Answering your questions in reverse order... 
1. We did not approve a license yet.  After much discussion within the HSF and other communities, I would like to get Apache 2 approved but to really claim that we are compliant with that we need to move some GPL'd code into a different repository.  We've started investigating that.  For now all we can say is that our software is open source.  
2. There is a lot of things people need to know as I'm sure you're aware.  I wish out public twiki's were versioned as that would at least be something.  On the other hand there is a lot of information that has not changed in years and may still be useful.  Has anyone pointed you at https://twiki.cern.ch/twiki/bin/view/CMSPublic/WebHome to look for relevant pages?
3. There are CHEP papers that would be nice to link... probably best to search our CINCO system for them.

**Comment by pherterich** [comment]
@katilp @sextonkennedy I tried to look for CHEP papers and browsed the Twiki but more or less anywhere I clicked I ran into authorisation issues as the pages are only accessible to CMS members. Could you check for suitable material and provide us DOIs for papers to link or maybe even check with @RaoOfPhysics if this is worth a separate help page we should point to instead? Thanks!

**Comment by katilp** [comment]
@pherterich @RaoOfPhysics For the 2011, we will finally need to use 5_3_32 (which is not yet
out but can be in few days) bacause Josh has added a script to extract the event generator
information and it can be included to that release. I hope this is not a problem at this stage.

**Comment by pherterich** [comment]
@katilp this is for both, MC and primary datasets? If so, @tiborsimko can you correct it for the MC datasets and @AnxhelaDani and me will do the the others manually. Thanks!

**Comment by tiborsimko** [comment]
@pherterich This seems to be about creating CMS SW records. Did you think of updating the information in dataset records too?  Here is a brief overview of the current status:

- `CMSSW_5_3_12_patch1` in 2011 primary datasets
- `CMSSW_5_3_30` in 2011 event display files
- `CMSSW_5_3_16` in 2011 simulated datasets
- (... but randomly looking in DAS I see e.g. `CMSSW_5_3_23_patch1` for some simulated datasets; perhaps should we extract this information individually for each record from DAS?)

**Comment by pherterich** [comment]
@tiborsimko this is more or less my question: if cataloguing a different version is sufficient or if this means something has to be updated in the dataset records as well. @tpmccauley does this update change anything for your event display files? Maybe we can clarify in the meeting later.

**Comment by tpmccauley** [comment]
@katilp what is the version that will be available in the VM?

**Comment by katilp** [comment]
It will be 5_3_32 which can, to my understanding, be out in few days (I asked David Lange, but I had no reply yet). The necessary change for the Open data side is the script from Josh with which the LHE header can be extracted from the MC files.

**Comment by AnxhelaDani** [comment]
@sextonkennedy @katilp have you approved a license for the CMSSW?

**Comment by sextonkennedy** [comment]
A consensus is building that we should use an Apache2 license, the work that needs to be done is to make sure that externally developed software has not been imported into CMSSW, rather that it is in our external git clone area so that those products can retain their original licenses.  -Liz
