### ISSUE TITLE
CMS event display files for 2011 data

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#824]
I have produced event display files for the new release. A few questions:

* The naming convention for the files has been e.g. SingleMu.ig i.e. reflecting the dataset name. Some the datasets for this release have the same name however. Append Run2011A? Should we then append Run2010B to the others?
* For metadata shall I add to the existing xml file or create another?

**Comment by katilp** [comment]
I would rather keep the files from different years as separate records and append Run2011A and Run2010B to the dataset names. The record name on the portal will not change, it is already as explicit as it can
("Event display file derived from /MinimumBias/Run-2010B-Apr21ReReco-v1/AOD"...)

**Comment by tpmccauley** [comment]
https://cms-docdb.cern.ch/cgi-bin/DocDB/ShowDocument?docid=12752

**Comment by katilp** [comment]
OK, great! @pherterich What else you need to create the records? These are the event display records similar to those for the 2010 release (like http://opendata.cern.ch/record/610)

**Comment by pherterich** [comment]
Well, @tpmccauley could create them himself, I don't think @tiborsimko has a preference for integration (Tibor, can you provide some free record numbers?). It should be fine to copy most things from last year, just update the year and check if the text is still valid etc. Will you also upload a new code? Then we should create that record, too, so you can link to the right one. I put this on our to do list for Monday, so we can go through it..

**Comment by tpmccauley** [comment]
@pherterich I wasn't what to do with  '<controlfield tag="001"></controlfield>' so left it empty. I created a separate file for the new files.

**Comment by pherterich** [comment]
Great, I guess @tiborsimko can do that upon upload/merging of the PR.

**Comment by tiborsimko** [comment]
@pherterich Yes, I'll take care of that.
