### ISSUE TITLE
RFC: Adding Altmetric badge to datasets

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#827]
Thoughts about adding https://www.altmetric.com/ badges to our datasets?

Pinging @TimSmithCH, @suenjedt, @pherterich, @tiborsimko.

**Comment by salmele** [comment]
[Similar questions have been raised for other services in the suite of the lab recently, this comment comes from those threads - mostly in e-mails somewhere]

Which is the use case this would serve? 
How would this exactly make the service better and more attuned to what the experiments need?

The two questions above are especially in the context of a relatively low re-use (as in citations/year) and traction in press/social media of the individual DOI-tagged files.

**Comment by RaoOfPhysics** [comment]
Hmm. That seems to imply that metrics are only important for high-visibility content. Anyway, no strong feelings about this. Happy to close the issue.

**Comment by tiborsimko** [comment]
Closing the issue to the "someday" pool for housekeeping purposes.  

In case we see the general public tweeting and blogging about concrete open datasets, as opposed to mentioning just the home page of the service, we can revive the issue from this pool.

BTW here is one (random) example of the badge in action on a Zenodo-hosted dataset:
- https://zenodo.org/record/33141
