### ISSUE TITLE
Zero bias data - update the Issues & Limitations

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#829]
To underline that these datasets are not considered useful (based on recent validation). 
Nice wording needed within the "Issues and Limitations" part

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Which file(s) should I edit for this? Just https://github.com/cernopendata/opendata.cern.ch/blob/97f59123438e008f9419ce14b0c984e98b1f9771/invenio_opendata/testsuite/data/cms/cms-primary-datasets.xml#L14747 (Line 14747)

**Comment by tiborsimko** [comment]
:+1:

**Comment by RaoOfPhysics** [comment]
@katilp: How should I phrase this?

> IMPORTANT: It is NOT recommended to perform analysis on the ZeroBias dataset as recent validation has shown it is not useful.
