### ISSUE TITLE
Trigger information for 2011 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#832]
Provide a description of the trigger to the new primary datasets. For 2010, we had something like
"Events stored in this primary dataset were selected because of presence of at least one high-energy muon in the event, or because of presence of two different types on high-energy particles, such as muon and electron" (an example from http://opendata.cern.ch/record/14)

For the 2011 datasets, I would like to enhance this with the actual trigger names as in the lists provided by Andrea long while ago
https://fwyzard.web.cern.ch/fwyzard/hlt/2010/dataset
https://fwyzard.web.cern.ch/fwyzard/hlt/2011/dataset
https://fwyzard.web.cern.ch/fwyzard/hlt/2012/dataset
https://fwyzard.web.cern.ch/fwyzard/hlt/2013/dataset

However, the list of possible triggers for one primary dataset would be inconveniently long (for example: 22 possible triggers for DoubleMu and many more for others...).

Therefore, I would suggest a new collection CMS Trigger Information where we could have, as a very first attempt, the files above (for 2010 and 2011), and start working to elaborate this information e.g. to add a link to the description of the trigger. The data selection field could then have a link to the relevant place there (in addition to the simple trigger description)
 
Alicia, could you have a look 
(1) to find the simple description for the trigger selection for the 2011 RunB primary dataset
(2) find the definitions of the different trigger paths in https://fwyzard.web.cern.ch/fwyzard/hlt/2011/dataset ?

**Comment by katilp** [comment]
Recording this page https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLegacyGlobalHLT as useful further information.

Basic concepts in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLegacyGlobalHLT#Using_frozen_Run_1_or_Run_2_trig

For anyone wanting to generate new MC corresponding to 2011 public data:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLegacyGlobalHLT#frozen_running_the_2011_legacy_5

For data (mainly for information, I guess):
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLegacyGlobalHLT#CMSSW_5_3_X_Legacy_release_for_R

**Comment by katilp** [comment]
Now I have the following plan for the additional trigger information:

The trigger information for each data-taking period consists of several different trigger menus
which are valid (i.e. were in use) for known run numbers
The validity range for a trigger menu is recorded in the upper part of the following pages (Under "Physics menus")
http://fwyzard.web.cern.ch/fwyzard/hlt/2010/summary
http://fwyzard.web.cern.ch/fwyzard/hlt/2011/summary
http://fwyzard.web.cern.ch/fwyzard/hlt/2012/summary
http://fwyzard.web.cern.ch/fwyzard/hlt/2013/summary


Two sets of menus are available one for collision data (with names as /cdaq/physics/Run2011/5e33/v2.2/HLT/V4 as in the pages above) and another for simulated data (with names as /online/collisions/2011/5e33/v3.5/HLT/V10 ).
The menu defines the triggers and their parameters used in data taking (for collision data) or in simuation of the onine conditions (for simulated data), and its configuration can be extracted from the CMS confdb data base.

The trigger menu gives the exact (although quite complicated to read) definition
of the algorithms and parameters that were used to select the events in different primary dataset and therefore useful for documentation purposes

I would like to add this information in Trigger information collection.
I.e. for 2011 data, we should extract the Physics menus part from the page above i.e.:

* Physics menus

CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.2/HLT/V2                                           (runs 160404 - 160406)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.2/HLT/V5                                           (runs 160410 - 160413)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.2/HLT/V6                                           (runs 160431 - 160463)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.2/HLT/V7                                           (runs 160497 - 160579)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.2/HLT/V8                                           (runs 160808 - 160815)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.3/HLT/V3                                           (run 160819)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v4.3/HLT/V4                                           (runs 160827 - 160835)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.1/HLT/V3                                           (runs 160853 - 160877)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.2/HLT/V2                                           (run 160888)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.2/HLT/V5                                           (run 160890)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.2/HLT/V6                                           (runs 160894 - 160898)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.2/HLT/V7                                           (runs 160907 - 160943)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.3/HLT/V1                                           (runs 160955 - 161020)
CMSSW_4_1_1_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v5.3/HLT/V2                                           (runs 161103 - 161176)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.1/HLT/V1                                           (run 161216)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.1/HLT/V3                                           (run 161217)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.1/HLT/V5                                           (runs 161222 - 161233)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.1/HLT/V6                                           (runs 161310 - 161312)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/2760GeV/v1.1/HLT/V1                                      (run 161366)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/2760GeV/v1.1/HLT/V3                                      (runs 161396 - 161445)
CMSSW_4_1_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/2760GeV/v1.1/HLT/V4                                      (runs 161450 - 161474)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.2/HLT/V2                                           (runs 162718 - 162765)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.2/HLT/V3                                           (runs 162803 - 162926)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v6.2/HLT/V4                                           (runs 162929 - 163261)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.1/HLT/V5                                           (runs 163269 - 163270)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.1/HLT/V6                                           (runs 163286 - 163289)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.1/HLT/V8                                           (runs 163296 - 163334)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.2/HLT/V3                                           (runs 163337 - 163668)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.3/HLT/V2                                           (runs 163738 - 163753)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.3/HLT/V3                                           (run 163754)
CMSSW_4_1_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/5e32/v8.3/HLT/V4                                           (runs 163757 - 163869)
CMSSW_4_2_3_onlpatch3_ONLINE     /cdaq/physics/Run2011/1e33/v1.3/HLT/V2                                           (runs 165088 - 165121)
CMSSW_4_2_3_onlpatch3_ONLINE     /cdaq/physics/Run2011/1e33/v1.3/HLT/V6                                           (run 165205)
CMSSW_4_2_3_onlpatch3_ONLINE     /cdaq/physics/Run2011/1e33/v1.3/HLT/V7                                           (run 165208)
CMSSW_4_2_3_onlpatch3_ONLINE     /cdaq/physics/Run2011/1e33/v1.3/HLT/V12                                          (run 165364)
CMSSW_4_2_3_onlpatch3_ONLINE     /cdaq/physics/Run2011/1e33/v1.3/HLT/V13                                          (runs 165400 - 165633)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.3/HLT/V1                                           (runs 165970 - 165993)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.3/HLT/V3                                           (runs 166010 - 166150)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.4/HLT/V2                                           (runs 166161 - 166164)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.5/HLT/V1                                           (run 166346)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.4/HLT/V4                                           (runs 166374 - 166512)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.4/HLT/V5                                           (runs 166514 - 166782)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.4/HLT/V6                                           (runs 166784 - 166787)
CMSSW_4_2_3_onlpatch4_ONLINE     /cdaq/physics/Run2011/1e33/v2.4/HLT/V8                                           (runs 166839 - 166967)
CMSSW_4_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/1.4e33/v1.1/HLT/V1                                         (runs 167039 - 167043)
CMSSW_4_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/1.4e33/v1.2/HLT/V1                                         (runs 167078 - 167284)
CMSSW_4_2_4_onlpatch1_ONLINE     /cdaq/physics/Run2011/1.4e33/v1.2/HLT/V3                                         (runs 167551 - 167913)
CMSSW_4_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2011/2e33/v1.1/HLT/V1                                           (runs 170249 - 170406)
CMSSW_4_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2011/2e33/v1.1/HLT/V2                                           (runs 170452 - 170759)
CMSSW_4_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2011/2e33/v1.2/HLT/V1                                           (runs 170826 - 171178)
CMSSW_4_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2011/2e33/v1.2/HLT/V4                                           (runs 171219 - 172033)
CMSSW_4_2_7_onlpatch1_ONLINE     /cdaq/physics/Run2011/2e33/v1.2/HLT/V5                                           (runs 172163 - 172286)
CMSSW_4_2_7_onlpatch2_ONLINE     /cdaq/physics/Run2011/2e33/v1.2/HLT/V5                                           (runs 172389 - 172411)
CMSSW_4_2_7_onlpatch2_ONLINE     /cdaq/physics/Run2011/2e33/v1.2/HLT/V7                                           (runs 172478 - 173198)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v1.1/HLT/V1                                           (runs 173236 - 173241)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v1.1/HLT/V3                                           (runs 173243 - 173244)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v1.1/HLT/V4                                           (runs 173380 - 173439)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v1.2/HLT/V1                                           (runs 173657 - 173692)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.0/HLT/V4                                           (runs 175832 - 175837)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.0/HLT/V7                                           (runs 175857 - 175921)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.1/HLT/V1                                           (runs 175971 - 176023)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.1/HLT/V2                                           (runs 176161 - 176207)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.2/HLT/V3                                           (runs 176286 - 176309)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v2.3/HLT/V2                                           (runs 176461 - 176470)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v3.0/HLT/V2                                           (runs 176545 - 176548)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v3.1/HLT/V1                                           (runs 176697 - 177053)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v4.0/HLT/V2                                           (runs 177074 - 177184)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v4.0/HLT/V3                                           (run 177201)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v4.0/HLT/V5                                           (runs 177222 - 177878)
CMSSW_4_2_7_onlpatch3_ONLINE     /cdaq/physics/Run2011/3e33/v4.0/HLT/V6                                           (runs 177718 - 177719)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.0/HIHLT/V2                                            (run 181531)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.0/HIHLT/V3                                            (runs 181604 - 181611)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.1/HIHLT/V1                                            (runs 181749 - 181778)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.2/HIHLT/V2                                            (run 182123)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.3/HIHLT/V1                                            (runs 182133 - 182257)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.3/HIHLT/V5                                            (runs 182296 - 182382)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.4/HIHLT/V1                                            (runs 182398 - 182536)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.6/HIHLT/V1                                            (runs 182561 - 182591)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.6/HIHLT/V2                                            (runs 182609 - 183123)
CMSSW_4_4_2_onlpatch1_ONLINE     /cdaq/physics/Run2011HI/v1.7/HIHLT/V1                                            (runs 182960 - 183126)

NB that the above run ranges are all 2011 data, Run 2011 A is 160404-173692
Then to complete, we should extract the full configurations for each of these entries
(each one is a text file of around 2 MB).

An example of a trigger menu is here, this is the full configuration (I have extracted this from the path /online/collision so this is what has been used for simulated data , I will update it soon)
[Config9.txt](https://github.com/cernopendata/opendata.cern.ch/files/85679/Config9.txt)

I think that this could be one record for one year, containing all possible trigger menus. For example for Run 2011 A, it would 58 trigger menu files.

@pherterich @tiborsimko Would that be possible?

**Comment by pherterich** [comment]
Let me try to summarise this just to make sure I really understand (or figure out the parts that I don't).
First, is there a difference between these trigger menus and the list of triggers we looked at except that the menus are clearly linked to a run and the list is more abstract? If we do these trigger menus for every year, we don't do subsets for each primary dataset as we thought about on Friday?
So in this plan now, we have one record per year for primary data only (what happens to the simulated data triggers? Ignore for now?) that contains the menu i.e. a long list of triggers and then a config file for each line in the list. Is this for preservation and transparency or do you also think things like this need to be citable? Then I think it will become a bit more complicated. Other than that I don't see why this shouldn't be possible.

**Comment by katilp** [comment]
Right, these menus contain the exact definition of the entries in the list of triggers we looked at before (and which is useful as well, but it only tells what trigger names are used in each primary dataset but does not tell what these triggers actually do). In the format in which I can easily extract them (i.e. the file Config above) all trigger definitions are included so indeed there will not be a file for each primary dataset or a file for each trigger name but they are all in.

This is for information, preservation and transparency and to my view no need for these to be citable.

For the simulation, we may need or want to give similar information, but let us first do the exercise with the collision data.

**Comment by pherterich** [comment]
Thanks, I think I understand now. I will discuss with @AnxhelaDani then and try to come up with a first record which you and @tiborsimko can then work with and iterate on in the next meetings.

**Comment by katilp** [comment]
@tiborsimko The config file for trigger menus for 2011 runs are now in https://cernbox.cern.ch/index.php/s/AfsweuwAf3sA6as (zipped floder). Can you get them from there?

**Comment by fwyzard** [comment]
Hi,
I think you got things right, let me just add a couple comments.

For data, the HLT menu (the python files) is the same for all datasets; in fact the HLT is run before the split into datasets, and the HLT results are used to define the datasets.
In principle, I guess we could generate "sub-menus" corresponding to each dataset, limiting the HLT menu to the list of trigger paths in each dataset. But it would only add more complication to the process, for very little advantage.

For MC, the HLT menus in principle could be different for different datasets, if they are generated from different MC campaigns. The vast majority of the time a single menu is used for the whole production, though.

Finally, you may want to take into account the fact the the HLT menus are only half of the story: the L1 (Level 1) Trigger runs before the HLT, and defines both the data that reach the HLT,and which L1 algorithms the HLT can be "seeded" by.
All L1 menus everused for data taking and MC production are documented on the twiki page at https://twiki.cern.ch/twiki/bin/viewauth/CMS/GlobalTriggerAvailableMenus . 
The association of the run number to each L1 menu an be extracted from the conditions database:
  - https://cms-conddb.cern.ch/browser/#list/Prod/tags/L1GtTriggerMenu_CRAFT09_hlt gives the association between run number and payload
  - unfortunately the association of the payload of the name cannot be done from the web page (yet), but only via the `conddb` command.

Ah, regarding whether it is necessary to store all "versions" of each menu: in principle the differences between versions (HLT/V1, HLT/V2, ...) should be very minor, often limited to different prescales. One would have to check to make sure, though.
If including all versions is not a problem, I think it would be the easier solution.


Ciao,
.Andrea

**Comment by katilp** [comment]
@fwyzard Thanks Andrea, very useful. I will have to digest the L1 information. For the link to conddb you gave, why CRATF09? Is that a list starting from CRAFT09 i.e from the start of data-taking?

**Comment by fwyzard** [comment]
Hi Kati,
yes, we have used the same conditions tag since the very start, from
CRAFT09.

Ciao,
.Andrea

**Comment by katilp** [comment]
@fwyzard OK, thanks. What does the string like "8bfbda71489804dceb710cf8854ffe321b6d696a" mean in the payload field of https://cms-conddb.cern.ch/browser/#list/Prod/tags/L1GtTriggerMenu_CRAFT09_hlt ? Does it have a one-to-one correspondence to one of the L1 trigger menus listed in https://twiki.cern.ch/twiki/bin/viewauth/CMS/GlobalTriggerAvailableMenus or does it also contain (refer to) some other information?

To test my understanding: Would the condDB table link the run range to the L1 menu in use?
For example (read from the conDB table)
since run 165894 a payload of  2cf110c6f174b84fba4728ae2cd95743863942f8 was used and this would correspond to the trigger menu which has the "trigger menu interface key" of L1Menu_Collisions2011_v3 described in
https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3
(an association which - as you said - I can't do on the web page but had to find "by hand")
I could then find the parameters in use for for different triggers that menu in
https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3/L1Menu_Collisions2011_v3_L1T_Scales_20101224_Imp0_0x1021.html
This latter is likely the information we would need to provide if we want to be complete.
Is it available in any other more concise form than those html pages?

**Comment by fwyzard** [comment]
>
> @fwyzard <https://github.com/fwyzard> OK, thanks. What does the string
> like "8bfbda71489804dceb710cf8854ffe321b6d696a" mean in the payload field
> of
> https://cms-conddb.cern.ch/browser/#list/Prod/tags/L1GtTriggerMenu_CRAFT09_hlt
> ? Does it have a one-to-one correspondence to one of the L1 trigger menus
> listed in
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/GlobalTriggerAvailableMenus
> or does it also contain (refer to) some other information?
>

Those strings are the hashes of the payloads in conditions database.
In the case of the L1 menus, they are most likely in one-to-one
correspondence to the menus on the twiki page - though I cannot exclude
that the same menu could have been uploaded multiple times, resulting in
multiple entries for the same menu.

To test my understanding: Would the condDB table link the run range to the
> L1 menu in use?
> For example (read from the conDB table)
> since run 165894 a payload of 2cf110c6f174b84fba4728ae2cd95743863942f8 was
> used and this would correspond to the trigger menu which has the "trigger
> menu interface key" of L1Menu_Collisions2011_v3 described in
>
> https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3
> (an association which - as you said - I can't do on the web page but had
> to find "by hand")
>
Correct.


> I could then find the parameters in use for for different triggers that
> menu in
>
> https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3/L1Menu_Collisions2011_v3_L1T_Scales_20101224_Imp0_0x1021.html
> This latter is likely the information we would need to provide if we want
> to be complete.
> Is it available in any other more concise form than those html pages?
>
Well, there is the corresponding XML representation, linked from the twiki
page. In this case it would be

/afs/
cern.ch/user/g/ghete/public/L1Menu/L1Menu_Collisions2011_v3/xml/L1Menu_Collisions2011_v3_L1T_Scales_20101224_Imp0_0x1021.xml

 - but it's not particularly user friendly.
I think the HTML pages are the bet way of making the information available
in a human readable format.


Ciao,
.Andrea

-- 
Strategy is a system of expedients.

Field Marshall Helmuth Carl Bernard Graf von Moltke

**Comment by tiborsimko** [comment]
> CMSSW_4_2_7_onlpatch1_ONLINE /cdaq/physics/Run2011/2e33/v1.2/HLT/V5 (runs 172163 - 172286)
> CMSSW_4_2_7_onlpatch2_ONLINE /cdaq/physics/Run2011/2e33/v1.2/HLT/V5 (runs 172389 - 172411)

These two entries are referring to the same file `cdaq_physics_Run2011_2e33_v1.2_HLT_V5.py`.  Is this correct?  If yes, then we may need to "revise" file names, because they have to be named in a unique manner if we attach them all under the same record.

**Comment by fwyzard** [comment]
Yes, they are the same HLT configuration.

What changes is the release of the CMSSW software that was used for data
taking.

.A

On 26 January 2016 at 14:18, Tibor Simko <notifications@github.com> wrote:

> CMSSW_4_2_7_onlpatch1_ONLINE /cdaq/physics/Run2011/2e33/v1.2/HLT/V5 (runs
> 172163 - 172286)
> CMSSW_4_2_7_onlpatch2_ONLINE /cdaq/physics/Run2011/2e33/v1.2/HLT/V5 (runs
> 172389 - 172411)
>
> These two entries are referring to the same file
> cdaq_physics_Run2011_2e33_v1.2_HLT_V5.py. Is this correct? If yes, then
> we may need to "revise" file names, because they have to be named in a
> unique manner if we attach them all under the same record.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cernopendata/opendata.cern.ch/issues/832#issuecomment-175007650>
> .
>



-- 
Strategy is a system of expedients.

Field Marshall Helmuth Carl Bernard Graf von Moltke

**Comment by tiborsimko** [comment]
As discussed with @katilp the remaining tasks are:

- [ ] create nice "table of contents" for the trigger mother record
- [ ] create individual trigger records and link them from primary datasets https://fwyzard.web.cern.ch/fwyzard/hlt/2011/dataset
- [ ] create individual trigger path records and inter-link them http://fwyzard.web.cern.ch/fwyzard/hlt/2011/summary

**Comment by tiborsimko** [comment]
Comments from live discussion:
- record 1700
  - High-level trigger information...
  - hide Files section
- records 2000+
  - High-level trigger path information...
  - add link to TOC record ("See the full list of ...")
- primary datasets
  - 567 $a text $w recid to link to trigger path

**Comment by katilp** [comment]
@tiborsimko The rest of the 2011 proton-proton config files are now in https://cernbox.cern.ch/index.php/s/63Nwh93V3or4IXI
These are the file for the data which for the moment are not released.

**Comment by katilp** [comment]
@AnxhelaDani The text to be added after the general description of how these data were selected (primary dataset, the file from @RaoOfPhysics):

The possible High Level Trigger paths in this datasets are:

(and @tiborsimko will extract you the list)

**Comment by tiborsimko** [comment]
> @tiborsimko The rest of the 2011 proton-proton config files are now in https://cernbox.cern.ch/index.php/s/63Nwh93V3or4IXI
> These are the file for the data which for the moment are not released.

Thanks, grabbed. Shall I upload them to the portal as well, either into public or into non-public collection, or shall we leave this for later?  In any case you may now remove the files from the box, if necessary.

**Comment by katilp** [comment]
@tiborsimko Maybe the easiest solution (for the future) would be to upload them to the collection where they belong but somehow flag them invisible, if it is easy to do. There is nothing secret that needs to be hidden, though, it would be just not to confuse the users with files that do not belong to to any released data on the portal.

**Comment by tiborsimko** [comment]
> Maybe the easiest solution (for the future) would be to upload them to the > collection where they belong but somehow flag them invisible

It happens that we use the collection concept to decide about visibility... I.e. if a record belongs to a public collection, then it's visible.  If we want it to remain hidden, then we put it into another (non-public) collection. 

> There is nothing secret that needs to be hidden, though, it would be just > not to confuse the users with files that do not belong to to any released > data on the portal.

Yes, I understand.  On the other hand, having 12 more configuration files (among many) will probably not be seen so visible as to mislead people?  We could also add a special comment for them if that would help?

**Comment by katilp** [comment]
OK, so let us just have them in the collection. In any case, I do not expect anyone to search through the config files in the collection, they will most likely get to them from the dataset record.

**Comment by tiborsimko** [comment]
All done now, except for linking, which will be a separate issue once we have all datasets in.

**Comment by katilp** [comment]
The remaining configs (for heavy ion runs) are in https://cernbox.cern.ch/index.php/s/FpnvP56AxSUR9jQ
