### ISSUE TITLE
Corrections to the glossary

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#836]
CMSSW:

- HTML special characters do not display correctly (chrome, windows10)

- Corrections to terms:

Now: Stands for CMS Software and refers to the so-called “Offline” software needed to analyse CMS data.
-->
More precisely:
... to the so-called "Offline" software needed to simulate, reconstruct and analyse CMS data and the "Online" software needed for online data selection

@sextonkennedy can maybe confirm or improve?

Now:
Particle jet: A jet is a shower of hadrons clustered together after being produced in particle collisions.
-->
Maybe: replace "after being" by "originating from a quark or a gluon" ? Or something alike, but adding the concept that jets originate from quarks and gluons

RunB: 
--> update this to be more generic to explain that any CMS data-taking year is divided in sets and add the definition for RunA (referring to 2011 RunA)

Add definitions:
- Monte Carlo (syn. simulated data)
- Generator
- Trigger

**Comment by sextonkennedy** [comment]
Hi All,

Answering your questions and looking into what you have done is on my todo list, but alas another day has gone by, and I still didn’t get to it.  When the HSF packaging meeting is over tomorrow, I should have some time.

Cheers, Liz

On Nov 17, 2015, at 7:50 AM, katilp <notifications@github.com<mailto:notifications@github.com>> wrote:


CMSSW:

  *   HTML special characters do not display correctly (chrome, windows10)

  *   Corrections to terms:

Now: Stands for CMS Software and refers to the so-called “Offline” software needed to analyse CMS data.
-->
More precisely:
... to the so-called "Offline" software needed to simulate, reconstruct and analyse CMS data and the "Online" software needed for online data selection

@sextonkennedy<https://github.com/sextonkennedy> can maybe confirm or improve?

Now:
Particle jet: A jet is a shower of hadrons clustered together after being produced in particle collisions.
-->
Maybe: replace "after being" by "originating from a quark or a gluon" ? Or something alike, but adding the concept that jets originate from quarks and gluons

RunB:
--> update this to be more generic to explain that any CMS data-taking year is divided in sets and add the definition for RunA (referring to 2011 RunA)

Add definitions:

  *   Monte Carlo (syn. simulated data)
  *   Generator
  *   Trigger

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Should I simply make more commits to #798?

**Comment by tiborsimko** [comment]
OK, please push some more commits on top, we can take care of both updates at the same time afterwards.

**Comment by RaoOfPhysics** [comment]
@katilp: I've made the changes to "CMSSW", "Particle Jet" and "Run(A/B)". I need rough definitions for:

- Monte Carlo (syn. simulated data)
- Generator
- Trigger

**Comment by katilp** [comment]
Sorry for the delay...

Monte Carlo: Computational algorithms based on numerical random samplings used in simulation programs for generating the particle collisions and for simulating of particle interactions in the detector material. Often used as a synonym to simulated data.

Generator: Simulation programs used to generate the particle collision

Trigger: Algorithms to select particle collisions to be stored in primary datasets

**Comment by katilp** [comment]
We also need the definition for Global tag (from Andreas' slides in CMS DPOA meeting
https://indico.cern.ch/event/350296/contribution/2/attachments/692095/950433/GTforDataPresAndOpenData-2014-11-03.key.pdf
Global tag: coherent collection of “Tags” used for running
Tag: record of additional data needed by reconstruction and analysis software 

<img width="489" alt="globaltag" src="https://cloud.githubusercontent.com/assets/5859918/11813933/68142940-a344-11e5-8776-53590ac0c5a6.png">
