### ISSUE TITLE
Collection list on the search page

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#842]
The collection list in the left bar of the search page is not visible to the end (beyond the size of the page) as it does not have separate scroll bar. As the collections are now more than those that fit in the page it is an issue.
<img width="960" alt="searchcodp" src="https://cloud.githubusercontent.com/assets/5859918/11267060/5538de42-8ea9-11e5-9146-56a9657de2e5.png">

**Comment by tiborsimko** [comment]
The UI works acceptably when pressing "more"; better facet UI to come via Invenio 3.
