### ISSUE TITLE
Global tag appears as the parent data set for the event display

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#843]
In the search view and in the record view, the global tag is mistakenly in the parent dataset field
in opendatadev

**Comment by pherterich** [comment]
@AnxhelaDani can you edit https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/testsuite/data/cms/cms-eventdisplay-files-Run2011A.xml and link the event display files to the correct primary datasets now that Tibor created the records?
