### ISSUE TITLE
Author list for the CMS 2011 release

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#848]
The author list for the 2011 release is in preparation and will be approved at the CB on the 11th Dec.

**Comment by pherterich** [comment]
@jalavik do you think you can do some MARCXML magic on that again mid December?

**Comment by jalavik** [comment]
@pherterich Sure! Just say the word. I assume it is about converting the authorlist XML to MARCXML, correct?

**Comment by pherterich** [comment]
@jalavik yes, same business as last year

**Comment by katilp** [comment]
@pherterich For the author list records in general, would it be possible to have a downloadable pdf or something else in the record. Looking at the record http://opendata.cern.ch/record/450, one
can only go page by page of all 50 pages, which is not very practical.

**Comment by pherterich** [comment]
I'm pretty sure we can attach xml/csv/pdf files there. We can discuss the best solution with @tiborsimko next week.

**Comment by salmele** [comment]
Would there be a dynamic option to update the record itself (and therefore produce on the fly updated xml/csv as we learn more ORCID IDs of the authors themselves?

**Comment by salmele** [comment]
Also, once we are at that, how are we going to display the existence of an ORCID ID close to an author name in the page? We've done something discrete e.g. http://repo.scoap3.org/record/12707 with the logo close to the names where we've a ORCID ID

**Comment by tiborsimko** [comment]
@salmele Yes, it's possible. Currently the record metadata update process goes via source code repository, since the content is mostly "static".  (So it's possible, but somewhat less curator-friendly and more programmer-friendly.) We can also amend formats to display ORCIDs.

**Comment by katilp** [comment]
The author list is now being prepared.
This is not the final list 
[list_authors1113.txt](https://github.com/cernopendata/opendata.cern.ch/files/103882/list_authors1113.txt) but maybe you can confirm if this kind of format is OK for you?

**Comment by pherterich** [comment]
@jalavik can you give it a look and a first run through the conversion script and let us know about the outcome? Thanks!

**Comment by katilp** [comment]
The final list is 
[list_authors1113_complete_with_doubles.txt](https://github.com/cernopendata/opendata.cern.ch/files/105236/list_authors1113_complete_with_doubles.txt)
It has all authors, but also some doubles. The first part of the file has all authors 2011-2013 in order of countries and institutes, but then the special author list from our Higgs publication is added just to the end of file, so that many authors appear double. Is it difficult for you to order it properly and remove the doubles?

**Comment by jalavik** [comment]
@pherterich @katilp I see that this format is a bit different than the standard collaboration authorlist XML format (http://inspirehep.net/info/HepNames/tools/authors_xml/index). Any chance it is possible to provide the authorlist format, like in #402? If not, we can create a new script to convert the data if this is gonna be the way forward. Thanks!

**Comment by katilp** [comment]
@jalavik We have some changes in personnel who is taking care of this in CMS and that may have caused some changes, my apologies. In any case now we the list without duplicates and special characters, and this is now hopefully a better format 
[authorslist12011_2013.txt](https://github.com/cernopendata/opendata.cern.ch/files/107267/authorslist12011_2013.txt)

**Comment by jalavik** [comment]
Thanks @katilp. Unfortunately, after a second look I do notice some potential issues with the format and data provided:

- the special characters are a bit funny (see Karancsi below)
- the affiliations are a bit short (unless there is a mapping somewhere?)
- the names are not structured so `lastname, firstname` conversions would be inaccurate.

See example from file:

```
ASRT-ENHEP
Yasser Assran, Sherif Elgammal, Ali Ellithi Kamel, Alaa Metwaly Kuotb Awad, Mohammed Mahmoud, Amr Radi, Nady Bakhet, Shaaban Khalil, Ayman Aly, Adel Awad, Ayman Mahrous, 

ATHENS
Loukas Gouskos, Apostolos Panagiotou, Niki Saoulidou, Efstathios Stiliaris, Theodoros Mertzimekis, 

ATOMKI
Noemi Beni, Sandor Czellar, JÃ¡nos Karancsi, Jozsef Molnar, Jozsef Palinkas, Zoltan Szillasi, Andras Fenyvesi, 
```

We can convert this to something like:

```
<datafield tag="700" ind1=" " ind2=" ">
  <subfield code="a">Gouskos, Loukas</subfield>
  <subfield code="u">ATHENS</subfield>
</datafield>
...
```

To me it feels like a little step back from the last one, but I'll let content curators comment on that: 

```
  <datafield tag="700" ind1=" " ind2=" ">
    <subfield code="a">Khachatryan, Vardan</subfield>
    <subfield code="u">Yerevan Phys. Inst.</subfield>
    <subfield code="i">INSPIRE-00314584</subfield>
    <subfield code="h">CCID-667227</subfield>
  </datafield>
```
https://github.com/cernopendata/opendata.cern.ch/blob/9c852f51b1335f6dc11b18e404cf1ab0ac25ca85/invenio_opendata/testsuite/data/cms/cms-author-list.xml

Let me know if we should continue along this path.

**Comment by suenjedt** [comment]
Thanks @katilp. The arxiv submissions are usually handled that way and come with such an author xml file (as Jan show's it). I am not sure with whom you have been in touch for that already, apologies. those persons might be able to pull that info from the CMS databases though. Otherwise, we will try to process this here.

**Comment by katilp** [comment]
@suenjedt Were the inspire and ccid fields provided by us (CMS) last time or was it something you were able to add?

**Comment by pherterich** [comment]
@jalavik was that done by the script? I think so, but you might know better...

**Comment by katilp** [comment]
Here is the new list from Gilles and comments:
[newauthorslist12011_2013.txt](https://github.com/cernopendata/opendata.cern.ch/files/172246/newauthorslist12011_2013.txt)


    the special characters are a bit funny (see Karancsi below
        ------------      display in unicode is working fine
    the affiliations are a bit short (unless there is a mapping somewhere?)
       ------------       i added ( institute id - spireICN ) but what for italy, spireICNa, b or c ?
    the names are not structured so lastname, firstname conversions would be inaccurate.
    ----------------    done

Let me know if this is OK

**Comment by suenjedt** [comment]
@katilp  it occured to me during the night that you mentioned yesterday that a HEPnote will be submitted to arXiv. I presume that submission will have the same author list as the one discussed here? 
If that is so, both should be following the authors xml "standard" and it would be good to double check the generation of the author xml with the "submitter" on the CMS side. 
Or have I misunderstood this?

**Comment by katilp** [comment]
We need a record for this (similar to http://opendatadev.cern.ch/record/450)
Then both author list records should also have the author list as pdf attached (update also to the old list)
@AnxhelaDani ?

**Comment by pherterich** [comment]
@jalavik can you give the latest file a look and just let @AnxhelaDani know what comes out of it so she has something to start working with? Thanks!
@tiborsimko is the PDF something you can easily create or is that something we should play around with on our side?

**Comment by suenjedt** [comment]
Thanks all!

**Comment by jalavik** [comment]
Here is the authorxml initial conversion from the last text file. I merged the author information from the 2010 list and updated affiliations according to new file. Authors not found in the 2010 list was added at the bottom.

Please verify that the number of authors is correct etc.

[authorlist2011_2013_marcxml.xml.zip](https://github.com/cernopendata/opendata.cern.ch/files/185875/authorlist2011_2013_marcxml.xml.zip)

**Comment by AnxhelaDani** [comment]
Thank you @jalavik !

**Comment by katilp** [comment]
@pamfilos For the pdf, margins to the top and the bottom of the pages would be needed. Thanks!
