### ISSUE TITLE
Updates to http://opendata.cern.ch/VM/CMS for 2011

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#851]
Testing with the new image from Adam
/afs/cern.ch/user/m/mhuffman/public/CMS-Open-Data-1.2.0-rc1.ova

(Update: now in /afs/cern.ch/user/m/mhuffman/public/open-data/CMS-Open-Data-1.2.0-rc1.ova)

Works fine!
- in conclusion, only version (virtualbox and cmssw) and the output need to be changed
in the instructions for 2011 http://opendata.cern.ch/VM/CMS (when the proper template 
is  available) 

I report here the full procedure 

downloading Virtualbox version 5.0.10
start ova
(need to change the net work adapter as in the "Issues and limitation")
open terminal
type the instructions: 
(need to change my keyboard setting as indicated in the "Issues and limitations")w

cmsrel CMSSW_5_3_30
(takes few minutes)
cd CMSSW_5_3_30/src
cmsenv

mkdir Demo
cd Demo
mkedanlzr DemoAnalyzer

cd DemoAnalyzer
scram b

edit configuration file with emacs:
emacs demoanalyzer_cfg.py

replace file:myfile.root with root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root

change -1 to 10 max number of events

cd ../..

cmsRun Demo/DemoAnalyzer/demoanalyzer_cfg.py

[cms-opendata@localhost src]$ cmsRun Demo/DemoAnalyzer/demoanalyzer_cfg.py
25-Nov-2015 11:30:53 CET  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root
25-Nov-2015 11:31:09 CET  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root
Begin processing the 1st record. Run 166782, Event 340184599, LumiSection 309 at 25-Nov-2015 11:31:20.947 CET
Begin processing the 2nd record. Run 166782, Event 340185007, LumiSection 309 at 25-Nov-2015 11:31:20.948 CET
Begin processing the 3rd record. Run 166782, Event 340187903, LumiSection 309 at 25-Nov-2015 11:31:20.949 CET
Begin processing the 4th record. Run 166782, Event 340227487, LumiSection 309 at 25-Nov-2015 11:31:20.950 CET
Begin processing the 5th record. Run 166782, Event 340210607, LumiSection 309 at 25-Nov-2015 11:31:20.951 CET
Begin processing the 6th record. Run 166782, Event 340256207, LumiSection 309 at 25-Nov-2015 11:31:20.952 CET
Begin processing the 7th record. Run 166782, Event 340165759, LumiSection 309 at 25-Nov-2015 11:31:20.953 CET
Begin processing the 8th record. Run 166782, Event 340396487, LumiSection 309 at 25-Nov-2015 11:31:20.954 CET
Begin processing the 9th record. Run 166782, Event 340390767, LumiSection 309 at 25-Nov-2015 11:31:20.954 CET
Begin processing the 10th record. Run 166782, Event 340435263, LumiSection 309 at 25-Nov-2015 11:31:20.955 CET
25-Nov-2015 11:31:21 CET  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 fileAction           -s file_close                             1        1
    2 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 fileAction           PostEndRun                        
    2 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  3                   3

**Comment by RaoOfPhysics** [comment]
- [ ] Add Validation Report

**Comment by RaoOfPhysics** [comment]
@katilp: Needs the Validation Report (when ready) and this issue is good to go.

**Comment by RaoOfPhysics** [comment]
As agreed with @katilp, we'll point to Validation Report for the 2010 VM, saying it may contain useful information and that a Validation Report for the 2011 VM will come in a few months.
