### ISSUE TITLE
Updates to http://opendata.cern.ch/getting-started/CMS for 2011

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#852]
Going through "Getting started instructions" in the new VM from Adam
/afs/cern.ch/user/m/mhuffman/public/CMS-Open-Data-1.2.0-rc1.ova:

Works fine! 

changed the file name to be opened with root to
root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root

opened a plot for electrons and that looks OK.

- [x] Need to decide what to do after "Applying selection cuts and reducing the data sample"

**Comment by RaoOfPhysics** [comment]
@katilp:

> Need to decide what to do after "Applying selection cuts and reducing the data sample"

Waiting for this.

**Comment by katilp** [comment]
@RaoOfPhysics I'm waiting for a reply from Achim whether I could modify his 2-lepton spectrum code to be used as an example. Other solution is to re-use the 2010 example (the first step works, see #905, but the updated code needs to put properly in github, can you help me with that?) but that would require reproducing the intermediate ntuples.

**Comment by RaoOfPhysics** [comment]
@katilp:

> I'm waiting for a reply from Achim whether I could modify his 2-lepton spectrum code to be used as an example.

:+1: 

> Other solution is to re-use the 2010 example (the first step works, see #905, but the updated code needs to put properly in github, can you help me with that?) but that would require reproducing the intermediate ntuples.

Yup, I've seen #905 and tried to proceed but I'll probably need to sit with you and work on this. Slightly beyond my abilities to process the code. I can help bringing it to GitHub, though!

**Comment by RaoOfPhysics** [comment]
@katilp: Can you please let me know which version of Scientific Linux is needed for CMSSW 5.3.30?

**Comment by katilp** [comment]
@RaoOfPhysics it is slc6. But we should use the version 5_3_32 in the instructions

**Comment by RaoOfPhysics** [comment]
@katilp: Argh, why do I have it as `30` in my docs? Ok, will update. Thanks for the quick reply!

**Comment by katilp** [comment]
@RaoOfPhysics Example output for the new version is:

16-Mar-2016 15:45:13 CET  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root
16-Mar-2016 15:45:17 CET  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root
Begin processing the 1st record. Run 166782, Event 340184599, LumiSection 309 at 16-Mar-2016 15:45:40.234 CET
Begin processing the 2nd record. Run 166782, Event 340185007, LumiSection 309 at 16-Mar-2016 15:45:40.235 CET
Begin processing the 3rd record. Run 166782, Event 340187903, LumiSection 309 at 16-Mar-2016 15:45:40.236 CET
Begin processing the 4th record. Run 166782, Event 340227487, LumiSection 309 at 16-Mar-2016 15:45:40.237 CET
Begin processing the 5th record. Run 166782, Event 340210607, LumiSection 309 at 16-Mar-2016 15:45:40.237 CET
Begin processing the 6th record. Run 166782, Event 340256207, LumiSection 309 at 16-Mar-2016 15:45:40.238 CET
Begin processing the 7th record. Run 166782, Event 340165759, LumiSection 309 at 16-Mar-2016 15:45:40.239 CET
Begin processing the 8th record. Run 166782, Event 340396487, LumiSection 309 at 16-Mar-2016 15:45:40.239 CET
Begin processing the 9th record. Run 166782, Event 340390767, LumiSection 309 at 16-Mar-2016 15:45:40.241 CET
Begin processing the 10th record. Run 166782, Event 340435263, LumiSection 309 at 16-Mar-2016 15:45:40.241 CET
16-Mar-2016 15:45:40 CET  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 fileAction           -s file_close                             1        1
    2 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 fileAction           PostEndRun                        
    2 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  3                   3
[cms-opendata@localhost src]$

**Comment by katilp** [comment]
The previous output goes to the VM page  (I updated the comment...)

**Comment by katilp** [comment]
Note also the validated runs instructions:

After, "Note also how only the validated runs are selected on lines:" should be:

import FWCore.ParameterSet.Config as cms
import FWCore.PythonUtilities.LumiList as LumiList
myLumis = LumiList.LumiList(filename='Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt').getCMSSWString().split(',')
process.source.lumisToProcess = cms.untracked.VLuminosityBlockRange()
process.source.lumisToProcess.extend(myLumis)

**Comment by katilp** [comment]
And under "Analysing the reduced dataset"

change the github link to https://github.com/katilp/OutreachExercise2011

I have not tested the full timing so maybe change "can take several hours" to "can take time"

Change the path names 2010 -> 2011 accordingly
