### ISSUE TITLE
Help page update for event display

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#853]
With the new event display the help page at http://opendata.cern.ch/visualise/events/CMS will have to be updated.

**Comment by RaoOfPhysics** [comment]
@tpmccauley: Can you please let me know what has changed so I can start with the documentation? I presume I'll have to make a whole new GIFset, but are there any other stand-out differences?

**Comment by tpmccauley** [comment]
@RaoOfPhysics most of the interface is the same. New things worth noting:

* when an event is loaded, picking on an object in the display (e.g. clicking on a muon and seeing the information)
* when an event is loaded, clicking on a collection name in the tree view on the left (like Global Muons) and seeing the contents in the table view
* in the table view, hovering over a particular row and seeing the object highlighted in the display (e.g. a particular muon turns from red to gray when selected in the table) and vice-versa

**Comment by RaoOfPhysics** [comment]
@tpmccauley: Got it. I'll have to make new animations anyway for the new look-and-feel. Thanks for flagging the highlights.

**Comment by RaoOfPhysics** [comment]
@tpmccauley: Could you please point me to where I can grab the icons used in the updated event display?

**Comment by tpmccauley** [comment]
@RaoOfPhysics Most of them come from here http://fortawesome.github.io/Font-Awesome/icons/
with the exception of ones that don't exist there like orthographic, perspective, and the axes.

You can see here which ones are used:
https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/visualise_events.html

To save you the trouble, they are listed here:

fa-folder-open
fa-step-backward
fa-step-forward
fa-home
fa-search-plus
fa-search-minus
fa-gear
fa-info

**Comment by RaoOfPhysics** [comment]
Excellent call using Font Awesome! :D

And thanks for the pointers.

**Comment by RaoOfPhysics** [comment]
@tpmccauley: Follow-up question. Should I point directly to FA's iconset or shall I download the current versions of these icons? I think the latter makes sense (that's why they have the CDN, after all), but I'm wondering how frequently you'll update the icons in the event display…

**Comment by tpmccauley** [comment]
@RaoOfPhysics FA is already included in the portal so it's probably best to include the icons directly e.g.:
`Click on <i class="fa fa-folder-open"></i> to open a file.`

**Comment by RaoOfPhysics** [comment]
:+1: 

Discussing this with Tibor now.

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Can you please let me know if it's fine for me to implement the Font Awesome Icons directly? You mentioned that it had been included somewhere on the portal, but you said you'd investigate before I got the green light. Thanks! :)

**Comment by RaoOfPhysics** [comment]
(Update: Got OK from @tiborsimko to proceed.)

**Comment by tpmccauley** [comment]
![makeitso](https://cloud.githubusercontent.com/assets/496503/13249944/0ae8febe-da1f-11e5-9bd1-b2b4a8bdac54.png)
