### ISSUE TITLE
CMS Condition Data

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#861]
- [x] introduce new collection "CMS Condition Data"
- [x] create a record

**Comment by BallzDeep** [comment]
Stop with the emails!!! I don't know wtf this is

**Comment by pherterich** [comment]
@AnxhelaDani and me can provide first versions of records, shall we create all three of them and you create the collection based on that. @tiborsimko ?

**Comment by tiborsimko** [comment]
OK. I'll collect the various files from @AnxhelaDani's private repository and commit.

**Comment by tiborsimko** [comment]
-  reuse text from the glossary in the description
- see also https://github.com/cernopendata/opendata.cern.ch/issues/836#issuecomment-164789239

**Comment by katilp** [comment]
Description for he condition data record:

Condition database includes
non-event-related information (Alignment,
Calibration, Temperature, …)
and parameters for simulation/reconstruction/analysis software

**Comment by tiborsimko** [comment]
> reuse text from the glossary in the description

@katilp @RaoOfPhysics We don't really have any text for "condition data" in the glossary, we have "CMS global tags" though.  Hence I'll use the description text following up @katilp's notes in the previous comment.  

We can still amend it later.  (And perhaps also add the expression "condition data" to the glossary...)
