### ISSUE TITLE
Add page on ProductionDataSetNames

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#864]
From (internal link) https://twiki.cern.ch/twiki/bin/viewauth/CMS/ProductionDataSetNames

**Comment by RaoOfPhysics** [comment]
@tiborsimko: I'll need a blank page for this. Please let me know how to proceed.

@katilp: Logically, where would this page reside on the portal?

**Comment by katilp** [comment]
@RaoOfPhysics I was thinking that this could reached through a link from a popup message (e.g. a question mark to be hovered over) close to all dataset names.
We should probably link it from http://opendatadev.cern.ch/about/CMS when we add a short description there about the MC datasets (under downloadable datasets).
And it could reside in http://opendatadev.cern.ch/collection/CMS-Open-Data-Instructions which is one of the collections listed on http://opendatadev.cern.ch/research/CMS

**Comment by tiborsimko** [comment]
@katilp Will this be a separate page or a new record in the instructions collection? This will allow to create a proper blank slate for @RaoOfPhysics to complete.  Personally I don't have rights to access that wiki page, so it's hard to guess how to best proceed here.

**Comment by katilp** [comment]
@tiborsimko Either (or both) will do. It is a help page explaining how the names of the simulated datasets are formed and the basic access to this page should be "more info" or "?" or similar from the simulated dataset pages, so in that sense it is a separate page. But for the sake of completeness, this page could also reside in the instructions collection.

**Comment by tiborsimko** [comment]
After live discussion, we'll go for the page with URL `/about/CMS-Simulated-Dataset-Names`. No need to split by years.

**Comment by katilp** [comment]
@pamfilos We had already decided the name :-) see above https://github.com/cernopendata/opendata.cern.ch/issues/864#issuecomment-178673654
For the other in #1017 e.g.  `/about/CMS-Pileup-Simulation`

**Comment by RaoOfPhysics** [comment]
@katilp: Indeed! :D

**Comment by RaoOfPhysics** [comment]
@pamfilos: Please don't close this issue with your commit. I will still need to add content to it. :)

**Comment by katilp** [comment]
@RaoOfPhysics @tiborsimko A correction: now on the page:
t’s the part of the dataset name before the second 'slash', i.e. for the dataset

/GluGluToHToZZTo4L_M-550_7TeV-minloHJJ-pythia6-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM

the dataset name is

DiPhotonBorn_Pt10to25.

Change DiPhotonBorn_Pt10to25 -> GluGluToHToZZTo4L_M-550_7TeV-minloHJJ-pythia6-tauola
otherwise this make little sense.

**Comment by tiborsimko** [comment]
@RaoOfPhysics @pamfilos Would you have time to take care of this template change?  I'm busy doing final QA updates and then I'll be updating the production nodes and moving the database...

**Comment by RaoOfPhysics** [comment]
@katilp: Terribly sorry, I missed the second edit. On it now.
