### ISSUE TITLE
facets: new "year" facet and "category" facet

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#865]
Introduce new facets:
-  "year" e.g. 2010, 2011
-  "category" e.g. "SM Inclusive".

to ease the browsing.

The category facet is used for CMS Simulated Datasets for now, but we can populate category field for other collections later too.

**Comment by tiborsimko** [comment]
Possible new facets: 
- "keywords" (e.g. vector boson, drell-yan) 
- "formats" (e.g. ig, csv, root)

**Comment by pherterich** [comment]
for format, I suggest MARC 347$b. @tiborsimko should we add this info manually or is there a smart way how you can fill it automatically?

**Comment by tiborsimko** [comment]
> for format, I suggest MARC 347$b

What about using `256` that we already "misuse" for other file related information?

> is there a smart way how you can fill it automatically

Can be scripted for most use cases...

**Comment by pherterich** [comment]
Well, if there's a proper MARC field, I prefer to use that. Also because I wouldn't know which subfield to use as f is taken for files already.

**Comment by tiborsimko** [comment]
The search UI and facets will be addressed in Invenio 3 based overlay.

**Comment by suenjedt** [comment]
Can I close this @tiborsimko - because we get facets with Invenio 3 anyway? The search/facets UI need deeper research (and seperate issues anyway).

**Comment by tiborsimko** [comment]
We get many faceting options Invenio 3, this issue is about deciding which facets to offer to users.  Amended milestone as we are just about to attack this...

**Comment by sefeg** [comment]
Did you already prepare a list of different facets that we have to decide on?

I'm thinking that there is a facet box that refers to the **record type** and should be used for the search result page and for all the resource pages in the mockup.

Another box will be about the **collections** (ALICE, ATLAS, ..) and will probably be used on most pages where facets apply.

Also the **run** (2010, 2011, 2012) represents probably a box that will be present on most of those pages with facets.

The facets for the dataset pages likely entail further information like the **data type** (Primary, Derived, Simulated)

So, those are some of my initial thoughts, also looking at the mockup.

**Comment by sefeg** [comment]
Also, based on the HST 2017 feedback ( #1292 ): on the dataset pages, file types could be of interest: 

> add a file type as a search key (i.e csv, ig, root, AOD, AODSIM)

**Comment by tiborsimko** [comment]
See also:
- fdbcf39a41a6f1669921b73db768d0f9603781ef
- https://github.com/cernopendata/opendata.cern.ch/issues/1426 
- https://github.com/cernopendata/opendata.cern.ch/issues/1418

**Comment by ioannistsanaktsidis** [comment]
Closing as we already have new facets in COD3. If more are needed we can create separate issues.
