### ISSUE TITLE
Lists of validated runs not visible in http://opendatadev.cern.ch/collection/CMS-Validation-Utilities

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#871]
http://opendatadev.cern.ch/record/1001 and http://opendatadev.cern.ch/record/1000 are not visible in the renamed collection http://opendatadev.cern.ch/collection/CMS-Validation-Utilities

**Comment by tiborsimko** [comment]
Fixed in the meantime.
