### ISSUE TITLE
Generator information and dataset names for MC datasets

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#876]
The generator information for the MC datasets can be found through following step:

In DAS listing for the MC datasets, click on "parents" , in parents, click on "output-config-1"
(update here, take the full file and not just part of it)

@pamfilos Can you find a way to extract this in an automated way?

As a first approximation, this file can be directly used in the MC dataset metadata
for "How were these data generated"

Furthermore, for those datasets that were generated using other programs in addition to pythia, we will also need to extract the event header from the file itself, but we can do this when the files have been transferred to eospublic. Josh has now provided a script for it.

@tiborsimko @pherterich In this same listing, there is also an Annotation field, e.g.

    annotation = cms.untracked.string('Summer2011 sample with PYTHIA6: QCD dijet production, pThat = 120 .. 170 GeV, TuneZ2'),

or 
    annotation = cms.untracked.string('B+ -> mu+ mu- K+ at 7TeV'),

If you can extract these, they can be used in the dataset title instead of the category. Would that work?

**Comment by tiborsimko** [comment]
Looking at this to provide visible example...

**Comment by tiborsimko** [comment]
... and the records were created in #938, #939, and subsequent ones.
