### ISSUE TITLE
URL text case: links broken when wrong case is used

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#883]
Shouldn't the URLs be case-insensitive? Currently, for example:
- http://opendata.cern.ch/about/CMS-Physics-Objects works, but
- http://opendata.cern.ch/about/CMS-physics-objects is broken!

**Comment by suenjedt** [comment]
Yes, that should not be the case. Thanks for spotting!

**Comment by AdityaBhardwaj002** [comment]
Two methods to do it but it is not recommended as it creates multiple entries for the search engine.

import re
from werkzeug.routing import Rule, RequestRedirect

class CIRule(Rule):
    def compile(self):
        Rule.compile(self)
        self._regex = re.compile(self._regex.pattern,
                                 re.UNICODE | re.IGNORECASE)


from flask import Flask

class CIFlask(Flask):
    url_rule_class = CIRule

via: http://librelist.com/browser/flask/2011/6/24/case-insensitive-routing/#198dd20c7198760b3e2f5d5ada19b7f9

**Comment by heitorPB** [comment]
>     * http://opendata.cern.ch/about/CMS-Physics-Objects works, but
> 
>     * http://opendata.cern.ch/about/CMS-physics-objects is broken!

Those 2 links points to the same page and some others I checked are case insenstive. I guess this was fixed?

**Comment by tiborsimko** [comment]
@heitorPB Thanks, yes, we had fixed it in the meantime.
