### ISSUE TITLE
templates: wrong "download index" button 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#886]
For contextualisation script record:

- http://opendatadev.cern.ch/record/249

the file download template says "Indexes" and "Download index", but these are files, not file indexes.

**Comment by RaoOfPhysics** [comment]
Related: Should it say "indices"? CC: @TimSmithCH?

**Comment by TimSmithCH** [comment]
Hmmm, thats a difficult one, since both are correct... indices is more common in English than American, and more common in academic circles than non-academic. So we sit in the sector than would favour Indices normally... but not strongly!

**Comment by pherterich** [comment]
I think we're also inconsistent with data being plural or singular here http://opendata.cern.ch/about (my own fault I think will update this page for the release). If we consider data being plural we also should go for the correct Latin plural and use Indices I think.

**Comment by RaoOfPhysics** [comment]
@pherterich: I went in and tried to fix the "data as plural" problems. Not sure I got everything!

@TimSmithCH: OED suggests that "Indexes" is correct here:

> *Computing*. A set of items each of which specifies one of the records of a file and contains information about its address.

Source: http://www.oed.com/view/Entry/94372?result=1#eid
