### ISSUE TITLE
Tabs for 2010/2011 data also needed for "Physics Objects"

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#888]
It was missed in #830, but since there are different instructions for 2011 data, we need a separate tab under "Physics Objects" as well: http://opendatadev.cern.ch/about/CMS-Physics-Objects

The tab should reside below the header for "[List of CMS physics objects](http://opendatadev.cern.ch/about/CMS-Physics-Objects#list)".

**Comment by tiborsimko** [comment]
It would be useful if the 2010 - 2011 tabs part stays open on the top of the page when the user scrolls down the page to reach down to physics objects.  (Ditto for other pages where we have 2010 vs 2011 tabs.)
