### ISSUE TITLE
Help page behavior for event display

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#892]
The "NEED Help?" tab on http://opendata.cern.ch/visualise/events/CMS doesn't behave as it should. Instead of acting like a tab the content instead appears below the display.

**Comment by RaoOfPhysics** [comment]
@tpmccauley: It works fine at my end, btw. Firefox on OS X.

**Comment by tpmccauley** [comment]
@RaoOfPhysics do both appear on the same page as in the attached? 

<img width="1370" alt="screen shot 2016-01-26 at 4 10 18 pm" src="https://cloud.githubusercontent.com/assets/496503/12586253/705fd666-c447-11e5-9a44-1a5276c13db5.png">

**Comment by RaoOfPhysics** [comment]
IE?! Dear lord. :P

No, when I click the button, it shows only the help content, without the event display.

**Comment by tpmccauley** [comment]
IE was what I had when testing using remote desktop. 
When I tested with docker and on localhost I had to error. It shouldn't have worked since the div was in the wrong place. Do you have a screenshot of the whole page before and after the Help tab is activated?

**Comment by RaoOfPhysics** [comment]
![codp_eventdisplay](https://cloud.githubusercontent.com/assets/7623019/12613329/3da33346-c4f9-11e5-8a48-24d9ba274776.gif)

**Comment by tpmccauley** [comment]
@RaoOfPhysics that's the old display. On dev (with the new display) it was broken. I see that I included the wrong link. It should have been http://opendatadev.cern.ch/visualise/events/CMS (like in the screenshot I included).

**Comment by RaoOfPhysics** [comment]
> On dev (with the new display) it was broken. I see that I included the wrong link. It should have been http://opendatadev.cern.ch/visualise/events/CMS (like in the screenshot I included).

:+1:
