### ISSUE TITLE
Analysis example for 2011

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#905]
I have tested the image from
/afs/cern.ch/user/m/mhuffman/public/open-data/CMS-Open-Data-1.2.0-rc1.ova
(there is now a new image which has a larger disk and cache size,
/afs/cern.ch/user/m/mhuffman/public/open-data/CMS-Open-Data-1.2.0-rc3.ova
and this is now tested as well)

with the following recipe, which has now been updated (with all updates for 2011) in
https://github.com/katilp/pattuples2011

***************************************************************

cmsrel CMSSW_5_3_32
cd CMSSW_5_3_32/src
cmsenv
git clone https://github.com/ayrodrig/pattuples2010.git
cd pattuples2010

ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA FT_53_LV5_AN1
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA.db FT_53_LV5_AN1_RUNA.db

... edit PAT_data_repo.py:

process.GlobalTag.globaltag = 'GR_R_42_V25::All'
-> 
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT_53_LV5_AN1_RUNA.db')
process.GlobalTag.globaltag = 'FT_53_LV5_AN1::All'

PhysicsTools.PythonAnalysis.LumiList -> FWCore.PythonUtilities.LumiList

myLumis = LumiList.LumiList(filename='Cert_136033-149442_7TeV_Apr21ReReco_Collisions10_JSON_v2.txt').getCMSSWString().split(',')
->
myLumis = LumiList.LumiList(filename='Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt').getCMSSWString().split(',')

Copy locally the json file above
(from the opendatadev or from https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions11/7TeV/Reprocessing/Cert_160404-180252_7TeV_ReRecoNov08_Collisions11_JSON.txt)

Change the file names in Electron2010data_500files_1.txt
to the some of the new ones e.g. from
https://github.com/cernopendata/opendata.cern.ch/blob/3de4791850cc9e5e8d3d9fa1eaecd7fa65787e7b/invenio_opendata/testsuite/data/cms/eos-file-indexes/CMS_Run2011A_DoubleElectron_AOD_12Oct2013-v1_20000_file_index.txt

and then

cmsRun PAT_data_repo.py

This run and produces a root files with electrons in it.

First time, this takes some 30 mins (depending on the connection speed) as it downloads 3.7G to cvmfs cache area of the VM. This happens before the event loop. The subsequent runs go very fast (the VM can be shutdown in between).

@RaoOfPhysics could you kindly create a new area in github starting from
https://github.com/ayrodrig/pattuples2010.git

My test was just a quick try, so I did not change all 2010 to 2011. This obviously needs to be done.

**Comment by RaoOfPhysics** [comment]
> @RaoOfPhysics could you kindly create a new area in github starting from
https://github.com/ayrodrig/pattuples2010.git

Now available at https://github.com/katilp/pattuples2011

I believe we're still waiting for the PATtulples to be produced in Spain, after which this issue can be closed.

**Comment by katilp** [comment]
@AnxhelaDani Can you created the 2011 records corresponding to the records 200 and 101
http://opendatadev.cern.ch/record/101
http://opendatadev.cern.ch/record/200

For the two records above, need to add 2010 to the title (or to the description).

**Comment by katilp** [comment]
@AnxhelaDani for the 2011 record corresponding to http://opendatadev.cern.ch/record/200:
Description stays the same
URL: https://github.com/katilp/OutreachExercise2011
How to use:
See the instructions in https://github.com/katilp/OutreachExercise2011
Use with:
... to be updated, the full datasets are in production
System details:
Use this code with the CMS Open Data VM environment
Software release: CMSSW_5_3_32
[link to new 2011 VM image]

**Comment by AnxhelaDani** [comment]
@katilp I update the record. I have to update the record corresponding to http://opendatadev.cern.ch/record/101 as well.

**Comment by RaoOfPhysics** [comment]
Can close this, I believe.
