### ISSUE TITLE
Upload VM image 2011 for testing

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#906]
@tiborsimko could you upload the vm image for 2011 data from
/afs/cern.ch/user/m/mhuffman/public/open-data/CMS-Open-Data-1.2.0-rc1.ova
to its own record under CMS tools collection

**Comment by tiborsimko** [comment]
@katilp Grabbed it.  I assume we'll create a new record?  And what about contextualisation scripts? Previously we used:

- VM image: http://opendatadev.cern.ch/record/250
- contextualisation scripts: http://opendatadev.cern.ch/record/249

CC @pherterich @AnxhelaDani

**Comment by AnxhelaDani** [comment]
@tiborsimko  you can find the new record for VM image 2011 and the contextualisation scripts at PR (#859). Tomorrow we can check again the content with @katilp

**Comment by katilp** [comment]
@tiborsimko The image to be uploaded is /afs/cern.ch/user/m/mhuffman/public/open-data/CMS-Open-Data-1.2.0-rc3.ova
