### ISSUE TITLE
CMS L1 trigger information 2011: 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#907]
L1 trigger menus for 2011

Starting from run (first actual run): 
- description
- HTML view

157942 (157945): 
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v0
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v0/L1Menu_Collisions2011_v0_L1T_Scales_20101224_Imp0_0x101e.html

161205, (161205); after the run at 2.76 TeV (done with v2), the first run with v1 back is 161643
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v1
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v1/L1Menu_Collisions2011_v1_L1T_Scales_20101224_Imp0_0x101f.html

 161568
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v2
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v2/L1Menu_Collisions2011_v2_L1T_Scales_20101224_Imp0_0x1020.html

 165897
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v3/L1Menu_Collisions2011_v3_L1T_Scales_20101224_Imp0_0x1021.html

170065
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v4
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v4/L1Menu_Collisions2011_v4_L1T_Scales_20101224_Imp0_0x1022.html

 173212
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v5
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v5/L1Menu_Collisions2011_v5_L1T_Scales_20101224_Imp0_0x1023.html

176725
- https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v6
- https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerMenu_L1Menu_Collisions2011_v6/L1Menu_Collisions2011_v6_L1T_Scales_20101224_Imp0_0x1024.html

@tiborsimko Can you access the first set of links?

**Comment by tiborsimko** [comment]
@katilp Nope, I get consistently "access denied" and "authorisation failed".

**Comment by katilp** [comment]
@tiborsimko also for the second (html) set?

**Comment by katilp** [comment]
The html files are now in
https://cernbox.cern.ch/index.php/s/CjijpPP1nuq55GE

**Comment by tiborsimko** [comment]
- create at least 7 records for 7 files
- but ideally parse HTML files and populate CMS Trigger Information with independent records similarly to HLT path information
