### ISSUE TITLE
2011 examples

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#911]
@tpmccauley Is https://github.com/cms-outreach/ispy-analyzers/tree/Run2011A
ready to go as an example for 2011 data (in a similar way as
http://opendatadev.cern.ch/record/550)
Where should we point for the event display code. For the 2010 record, it points to https://github.com/cms-outreach/ispy-services, now it should point to webGL area, shouldn't it?

@tiborsimko  @pherterich  Do we want to have separate records for 2010 and 2011 or put them in the existing record (550)? In case of separate records, we then need a new one for them:
The structure is as http://opendatadev.cern.ch/record/550 but change
- Software release: CMSSW_4_2_8 to CMSSW_5_3_32
- links to 2011 VM and primary datasets instead of those 2010
- change the list of validated files to that of 2011
- example file can be Event display file derived from /SingleElectron/Run2011A-12Oct2013-v1/AOD (http://opendatadev.cern.ch/record/629)

**Comment by pherterich** [comment]
I vote for 2 records. Otherwise the links and files get messy, non? @tiborsimko will you create it or shall @AnxhelaDani take care (once we get the OK from @tpmccauley of course)?

**Comment by suenjedt** [comment]
+1

**Comment by tiborsimko** [comment]
@pherterich @suenjedt Yes that's what we agreed upon live here as well...

**Comment by tpmccauley** [comment]
@katilp The analyzers are ready. @verdurin issued a PR which fixed the file location in the VM and I merged it. I would go for 2 records. Also, the url to ispy-services is there as this package is also needed to make the event display files.

**Comment by tpmccauley** [comment]
https://github.com/cms-outreach/ispy-analyzers/commit/add1b6f0126bdf3ea890f2f857fe97b021a4ee95

**Comment by tiborsimko** [comment]
BTW @tpmccauley we noticed that the standalone event previewer is loading the old 2010 files only? Shall it load new 2011 files? http://opendatadev.cern.ch/visualise/events/CMS
(@katilp mentions that it would be useful to have both 2010 and 2011 in a "directory" like structure in the file menu...)

**Comment by tpmccauley** [comment]
@tiborsimko Good point. I can add them. How much time do I have? :)

**Comment by katilp** [comment]
@tpmccauley You can count in days or weeks (not in minutes or hours) :-) 
We are now planning for a presentation at the WGM on the 10th of March
For the directory structure, we could add Higgs (which do not really fit under 2010 or 2011),
and a separate directory for Z and W events, maybe

**Comment by tpmccauley** [comment]
@katilp that's what I want to hear. I will sort it out next week. I have opened a separate issue #913

**Comment by tiborsimko** [comment]
Done.
