### ISSUE TITLE
2011 CMS event display files in stand-alone event display

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#913]
The event display files for 2011 should be available in the stand-alone event display currently at http://opendatadev.cern.ch/visualise/events/CMS
Probably best to have a "directory" structure with
2010/
2011/

**Comment by tpmccauley** [comment]
I have a PR. @katilp it looks like this (where I have placed all other files under "Education"; we could call it something else or divide them another way):
<img width="624" alt="screen shot 2016-02-17 at 1 08 35 pm" src="https://cloud.githubusercontent.com/assets/496503/13110618/0f23065a-d579-11e5-851b-6879e32f1cd0.png">
<img width="610" alt="screen shot 2016-02-17 at 1 08 45 pm" src="https://cloud.githubusercontent.com/assets/496503/13110632/21a632b6-d579-11e5-8d53-7172d141da39.png">

**Comment by tpmccauley** [comment]
@katilp it also occurred to me that an expandable and collapsible table would work. I thought that the major drawback to this was that one could extend the dialog to an undesirable length if one opens all of them.

**Comment by katilp** [comment]
@tpmccauley Looks good! Maybe add Higgs as a separate directory? 
for the table: Anything which scales down to phone screen size is fine. However, as loading the event is the first step in any work with the event display it should be very robust.
