### ISSUE TITLE
Corrections to http://opendatadev.cern.ch/record/101

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#916]
In http://opendatadev.cern.ch/record/101
the following link is wrong: 
"The expected output is a histogram file such as
http://opendata.cern.ch/visualise/histograms/CMS "
This link has nothing to do with this example.

The correct histograms were uploaded to the portal, you can find them in
https://github.com/cernopendata/opendata.cern.ch/issues/557

**Comment by tiborsimko** [comment]
Related to #557
