### ISSUE TITLE
Book Chapter: Early experiences with open data at CERN

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#918]
## Summary

Contacted by Vera Lipton with following request:

> We write to invite you to contribute a chapter to a book tentatively titled ‘**Digital Innovation: Harnessing the Value of Open Data**’.

> We are aware that CERN is committed to open data, especially as they are applied in the context of the Large Hadron Collider experiments. We thought your chapter might cover some of the early experiences with open data at CERN. We would, however, be happy to consider your suggestions for a different topic that fits into the proposed scope of the book.

- **Word Count**: 7,000–10,000
- **Due**: April/May 2016
- **Deadline 1**: 31 March 2016
- **Deadline 2**: TBD
- More info about the book: http://www.worldscientific.com/series/oibtp

---

## Proposal

Collaboratively edit the chapter on Authorea. The file can be found at https://www.authorea.com/users/8205/articles/100564/ So far, the following have signed up to contribute:

- @katilp 
- @suenjedt 
- @pherterich 
- @tpmccauley 
- @RaoOfPhysics
- @TimSmithCH
- @tiborsimko 
- Anyone else?

### Suggested breakdown of sub-chapters, authors, word counts

These are merely suggestions -- please feel free to edit as needed, or leave comments below and I'll edit it accordingly.

- [x] **Motivation**
    - Themes:
        1. Data preservation policies from the LHC experiments
        2. Strong commitment at CERN to "open" (e.g. @suenjedt)
    - Word count: **1,000**
    - Authors: @katilp, @RaoOfPhysics, @TimSmithCH, @suenjedt
- [x] **Challenges**
    - Themes:
        1. Volume of data
        2. Software environment and documentation
    - Word count: **2,000**
    - Authors: All
- [x] **Solution**
    - Themes:
        1. Logistical (Authors: @TimSmithCH, @tiborsimko)
        2. Technical –– schema, formats etc. (Authors: @suenjedt, @pherterich, @tiborsimko)
        3. Documentation (Authors: @katilp, @RaoOfPhysics)
    - Word count: **3,000**
- [x] **Use cases**
    - Themes:
        1. Education (Authors: @tpmccauley)
        2. Research (Authors: @katilp, Achim?)
    - Word count: **2,000**
- [x] **Impact**
    - Themes:
        1. Impact on scientists &mdash; using CMS as example? (Authors: @katilp)
            1. Better documentation
            2. Preservation is on collaboration's mind
        2. Impact in terms of usage stats (Authors: @tiborsimko)
    - Word count: **1,000**

**Total word count**: 9,000

---

**ACTION**: If there are no objections, I will divide the Authorea document into the relevant sub-chapters so we can proceed.

**Comment by RaoOfPhysics** [comment]
(I also realise that I am using this issue for matters other than the core development of the portal, but I thought it's a good place for us to have this discussion.)

**Comment by TimSmithCH** [comment]
OK, please add me, I must find a way somehow! Perhaps I simply schedule "virtual me" to do it sometime... And chalk me against Motivation/Challenges/Solution

**Comment by RaoOfPhysics** [comment]
@TimSmithCH: :+1: Thank you! :)

**Comment by suenjedt** [comment]
Added my name. Happy with TOC. Thanks!

**Comment by tpmccauley** [comment]
Thanks for this Achintya. I am fine with TOC.

**Comment by RaoOfPhysics** [comment]
@TimSmithCH, @suenjedt, @tpmccauley, @katilp, @pherterich: I've updated the Authorea document with the sub-chapters and have added direct links to the respective files in the OP above.

**Comment by suenjedt** [comment]
I need a deadline for a first draft, apologies. End of March?

**Comment by RaoOfPhysics** [comment]
@suenjedt: Let's aim for that. We can then converge on a polished version by some-time in April, I imagine.

**Comment by suenjedt** [comment]
Fantastic

**Comment by tiborsimko** [comment]
Now that I'm back I can join as well :smile:

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Excellent! To which sections should I add you?

**Comment by tiborsimko** [comment]
@RaoOfPhysics You know my area of expertise... Could contributed to Challenges, Solutions, where there isn't enough people yet.  More if needed (e.g. Impact with stats).

**Comment by RaoOfPhysics** [comment]
@tiborsimko: :+1:

**Comment by RaoOfPhysics** [comment]
Reminder! :D

**Comment by RaoOfPhysics** [comment]
@katilp, @pherterich, @suenjedt, @tiborsimko, @TimSmithCH, @tpmccauley: I've gone and added a brain-dump for chapters 1 and 2. Please feel free to edit as needed or simply add comments so that I can address them. It would be good if others can start putting down sentences or even fragments so that we can make some progress slowly but steadily. :D

**Comment by suenjedt** [comment]
I extended or started a few parts (i.e. chapter 1 and 3).

**Comment by katilp** [comment]
Sorry for being a dummy :-( but can someone tell me in very concrete terms where should I click to edit e.g. in https://www.authorea.com/users/8205/articles/100564/master/file/05_impact.md

**Comment by katilp** [comment]
Having found the superpower to edit :-)  I have now added some text in
https://www.authorea.com/users/8205/articles/100564/master/file/05_impact.md
