### ISSUE TITLE
Change ATLAS logo

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#919]
https://atlas-outreach.web.cern.ch/sites/atlas-outreach.web.cern.ch/files/ATLAS-Logo-Ref-RGB-H_0.jpg

**Comment by RaoOfPhysics** [comment]
#788

**Comment by tiborsimko** [comment]
As discussed with Steve, we can keep the titan-free square logo, as it fits better the overall site design.

See also https://github.com/cernanalysispreservation/analysis-preservation.cern.ch/issues/88
