### ISSUE TITLE
Event Display pop-up appearing outside canvas 

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#921]
See:

![codp_eventdisplay](https://cloud.githubusercontent.com/assets/7623019/13249299/d5233d76-da23-11e5-860e-f3dbb96b1ed7.gif)

**Comment by tpmccauley** [comment]
If you scroll down the page so that the top of the display is on the top of the page where does the popup appear?

**Comment by RaoOfPhysics** [comment]
The pop-up moves stays in place (i.e., it appears lower on the canvas if I scroll down). This is an acceptable solution! :D

**Comment by tpmccauley** [comment]
@RaoOfPhysics Good to hear, but it may be a better solution to have the popup always appear in the center of the display. Thoughts? @tiborsimko?

**Comment by RaoOfPhysics** [comment]
Reopening the issue for discussion.

**Comment by tpmccauley** [comment]
The more I look at it the more I think that the current behavior is fine. The modal can easily be closed by clicking anywhere else on the screen. Also, the user will typically be scrolled down in order to center the display anyway. Finally, once can scroll down the page underneath an already-opened modal. This can be re-closed.

**Comment by RaoOfPhysics** [comment]
I get the feeling that the pop-up is related to the event-display wrapper rather than the rest of the page, so my intuition is to expect it to appear within the confines of the event display rather than outside it.

**Comment by tiborsimko** [comment]
I also think the current behaviour is acceptable.  The pop-up appears 
always "within reach" for me.  

Situation A, when the page starts at the top:

![2016-03-08-044515_1366x768_scrot](https://cloud.githubusercontent.com/assets/517546/13591453/0c551cae-e4e9-11e5-98d1-36eeecb33652.png)

Situation B, when the page is scrolled down:

![2016-03-08-044540_1366x768_scrot](https://cloud.githubusercontent.com/assets/517546/13591456/155b62ea-e4e9-11e5-9feb-8f4ef74ace27.png)

Both seem fine.

P.S. Note that in the latter case the pop-up appears much closer to the event display box when compared to @RaoOfPhysics's original screenshot?! Nothing flies above.

**Comment by RaoOfPhysics** [comment]
@tiborsimko: As I mentioned to @tpmccauley in person, I think that since the "Open" button appears not on the whole page but within the event-display canvas, the pop-up itself should limit itself to this canvas. But I have no strong feelings about it and I leave it to Tom to prioritise. :P

**Comment by tpmccauley** [comment]
I think then this should be closed. If users complain we can revisit.
