### ISSUE TITLE
New record in CMS tools collection needed for di-lepton spectrum

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#926]
We have now available a nicely commented example code to produce the famous di-muon spectrum.
Two new records needed in the CMS tools collection, with a similar structure as in http://opendatadev.cern.ch/record/550

NB, what follows is for 2010, but we will need a similar record with 2011, with only slight modifications @AnxhelaDani we can have a look together once the 2010 record is created

Title:
Example code to produce the di-muon spectrum from a CMS 2010 primary dataset

Authors: Achim Geiser, I. Dutta, H. Hirvonsalo, B. Sheeran

"Description" and "How can you use this" fields
from /afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo/readme.txt

No URLs but the code files can be directly attached as files in the record
/afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo:
    BuildFile.xml
    demoanalyzer_cfg.py 
    Demoanalyzer.cc 

"Use with.."
2010 Mu primary dataset http://opendatadev.cern.ch/record/14
or any other 2010 primary datasets containing muons (see detailed instructions in code)

"System Details" 
as in http://opendatadev.cern.ch/record/550 i.e.
Use this code with the CMS Open Data VM environment
Software release: CMSSW_4_2_8
CMS VM Image, for 2010 CMS open data

"Validation"
as in http://opendatadev.cern.ch/record/550 

An example output should be attached to this record:
upload from /afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo/Mudemo.root

**Comment by AnxhelaDani** [comment]
@katilp I have created the draft records, please let me know when we can have a look together

**Comment by katilp** [comment]
@AnxhelaDani Would you propagate it to opendatadev (@tiborsimko) so we could have a look together tomorrow?

**Comment by katilp** [comment]
@AnxhelaDani You can now find the 5 files in https://cernbox.cern.ch/index.php/s/9Zoq94XAfjg7M7h

**Comment by tiborsimko** [comment]
The record is now visible on DEV:

- http://opendatadev.cern.ch/record/560
