### ISSUE TITLE
New record in CMS validation utilities collection needed 

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#927]
The first validation code is now available in
/afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004val/readme.txt

As a first trial, it can have a similar structure as the corresponding example code (#926).
We can then review and correct if needed.

The code files are available in
/afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004val

A clear statement is needed to explain that code in this category is not meant as a pedagogical example (i.e. not all examples will have detailed explanatory comments) but as a validation tool.
Not all validation code entries will have a corresponding version with explanations.

**Comment by katilp** [comment]
@AnxhelaDani The file are now available in https://cernbox.cern.ch/index.php/s/PrIBIaLSfSUbnxb

**Comment by katilp** [comment]
The text under "How can you use these data?" in this record can be the same as in http://opendatadev.cern.ch/record/560 (there were some modifications and clarifications done by @tiborsimko , my apologies to @AnxhelaDani that I forgot to say that)

**Comment by tiborsimko** [comment]
Done.
