### ISSUE TITLE
collections: CMS Configuration Files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#935]
- [x] Introduce new collection CMS Configuration Files
- [x] Populate records with files taken from DAS.
- [x] Add pileup record and its configuration file.
- [x] Add trigger path information related configuration files.
- Later, link them to both primary and simulated datasets.

**Comment by katilp** [comment]
Description text:
This collection contains the configuration files that were used in different steps of the data processing.

**Comment by tiborsimko** [comment]
Title example: LHE + annotation + last part of filenames variable

**Comment by katilp** [comment]
Can also add the pileup configuration in this collection and point to it from the file record
https://cmssdt.cern.ch/SDT/doxygen/CMSSW_5_3_12/doc/html/d0/d74/mix__2011__FinalDist__OOTPU__cfi_8py_source.html

**Comment by tiborsimko** [comment]
@katilp Some of the configuration files (notably `7b0f1f8e4df3d63108f095f9fa57f554.configFile`) are too big to live in the description field.  I'll add them all as files then...

**Comment by katilp** [comment]
OK, perfect

**Comment by katilp** [comment]
Btw, we could also have the config files 
https://github.com/cernopendata/opendata.cern.ch/issues/832#issuecomment-171018874
in this new configuration file collection and leave the trigger path information
(pieces from http://fwyzard.web.cern.ch/fwyzard/hlt/2011/summary) in the trigger information collection.

**Comment by tiborsimko** [comment]
@katilp So far I called all the files `configFile.py`, following CouchDB, but this is not ideal. I wonder whether we can simply reuse `python_filename` from the CLI options that used to generate the file?  For example, from the following header:

```
# Auto generated configuration file
# using:
# Revision: 1.381.2.28
# Source: /local/reps/CMSSW/CMSSW/Configuration/PyReleaseValidation/python/ConfigBuilder.py,v
# with command line options:
Configuration/GenProduction/python/Hadronizer_MgmMatchTuneZ2_7TeV_madgraph_cff.py
--dbsquery find file where
dataset=/GJets_TuneZ2_40_HT_100_7TeV-madgraph/Summer11LegpLHE-START53_LV4-v1/GEN
--fileout file:step1.root --mc --eventcontent RAWSIM --customise
SimG4Core/Application/reproc2011_2012_cff.customiseG4 --datatier GEN-SIM
--conditions START53_LV4::All --beamspot Realistic7TeV2011CollisionV2 --step
GEN,SIM --python_filename
/afs/cern.ch/cms/PPD/PdmV/work/McM/submit/SUS-Summer11Leg-00004/SUS-Summer11Leg-00004_1_cfg.py
--no_exec -n 8
```

we'd take `SUS-Summer11Leg-00004_1_cfg.py` as the significative configFile file name. Would that work?

**Comment by tiborsimko** [comment]
> Btw, we could also have the config files #832 (comment) in this new
> configuration file collection

Yes, indeed.  I'll call them in a similar manner, using file name in place of annotation, e.g. for `cdaq_physics_Run2011_5e32_v4.2_HLT_V8.py` the record title would be *"CMS HLT configuration file /cdaq/physics/Run2011/5e32/v4.2/HLT/V8"*. We can revise later.

**Comment by katilp** [comment]
@tiborsimko For the config file names: the names like  SUS-Summer11Leg-00004_1_cfg.py  reflect our production system (i.e. Summer11Leg is the production round for these datasets). They are not very informative to external users, but on the other hand it does not necessarily matter as they will be connected to the appropriate record. So as a first approximation, I think it is OK. We can check on Thursday
