### ISSUE TITLE
Record for event display needs to be updated/replaced

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#945]
Since the new event display will replace the one in the portal described in this record
http://opendatadev.cern.ch/record/555
should this record be modified to use the information for the new display or should an entirely new record be created?

**Comment by tiborsimko** [comment]
I guess we could simply modify the existing record, since we don't store anything there, except for the pointer to GitHub. Could update the pointer, or even add more event display repositories there.  Otherwise a new record is also a possibility... @AnxhelaDani @pherterich @suenjedt

**Comment by pherterich** [comment]
The new display will also run the examples from last year, non? So the old display will be not be visibly anywhere? Then I'd vote for updating the record and maybe keep the link for the older version in the record somehow just in case.

**Comment by tpmccauley** [comment]
@pherterich yes, the new display works for 2010 files as well. I will update the record.
