### ISSUE TITLE
CMS record appears in LHCb learning resources

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#947]
http://opendatadev.cern.ch/collection/LHCb-Learning-Resources

<img width="866" alt="screen shot 2016-03-15 at 5 33 43 pm" src="https://cloud.githubusercontent.com/assets/496503/13787531/3c5e9344-ead4-11e5-8142-78c9a47626d7.png">

**Comment by tpmccauley** [comment]
Like in #946 the link goes to what appears to be the correct record

**Comment by tpmccauley** [comment]
56 is used by two records:

https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/testsuite/data/cms/cms-open-data-instructions.xml#L39

https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/testsuite/data/lhcb/lhcb-learning-resources.xml#L3

**Comment by tiborsimko** [comment]
Nice catch! There seem to be a couple more records:

```console
$ git g '"001"' invenio_opendata/testsuite/data/ | awk -F'>' '{print $2;}' | sort | uniq -d
1102</controlfield
55</controlfield
56</controlfield
```

as you also observed in #946. I'll fix them.
