### ISSUE TITLE
Notes for the meeting 17/3

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#949]
Research page (http://opendatadev.cern.ch/research/CMS)

- ~~the 2010 and 2011 are still fixme, maybe still being updated?~~
  - *Tibor:* Already ticketised as #904

About CMS (http://opendatadev.cern.ch/about/CMS)

- ~~maybe just not updated yet, so these points may already have been adressed~~
- ~~could add a note on AODSIM in " in a format known as AOD or Analysis Object Data for collision data or AODSIM for simulated data"~~
- ~~on availability of MC. Replace . "Future releases may include this information." -> "The release of 2011 data includes simulated data. However, these data is not a full set of simulations, but those datasets that have been reprocessed with a compatible software release with the collision data."~~
- ~~maybe change the statement of evolving software etc in a more generic format without referring to 2010 i.e. "CMS had just started data taking in 2010 and the methods have evolved since those early days, in particular to respond to the evolving beam conditions of the LHC." -> "The methods have evolved since the data taking of the released data.... " or something alike~~
- ~~under "Data and analysis tools" the links to the event display and histograms are in format http://opendatadev.cern.ch/invenio_opendata/visualise_events and http://opendatadev.cern.ch/invenio_opendata/visualise_histo Shouldn't they be http://opendatadev.cern.ch/visualise/events/CMS and http://opendatadev.cern.ch/visualise/histograms/CMS~~ 
  - *Achintya:* See #955

Documentation pages (VM and getting started) not updated?

~~No 2010/2011 tabs yet in http://opendatadev.cern.ch/about/CMS-Physics-Objects~~ @pamfilos coming in https://github.com/cernopendata/opendata.cern.ch/pull/944

MC records:

-  ~~The order under "How were these data generated?" could be: LHE (plus dumpLHEHeader.py instructions), SIM, RECO, HLT~~ 
- ~~As the title of the record, it would be nice to use the "nice" name from the SIM step but it is not always there and not always "nice" so we may end up using 
"Simulated dataset Vector1MToZZTo4L_M-125p6_7TeV-JHUGenV3-pythia6 in AODSIM format for 2011 collision data (SM Inclusive)" 
i.e. move the category to the end and maybe leave it off from DOI if still possible. But we can discuss that.~~
- ~~Under "System details" we should have the recommended release for analysis, see https://github.com/cernopendata/opendata.cern.ch/issues/820#issuecomment-178680340~~
- ~~Under "Issues and limitations", we could add "simulated " in "These datasets correspond to the collision data collected by the CMS experiment in 2011." -> "These simulated datasets..."~~
  - *Tibor:* all ticketised as #965
- ~~File index is missing but I guess it is coming~~
  - *Tibor:* yes, all have been added.

Primary dataset records

- ~~"How were these data selected" should have the texts from
[PDDefinition_edited.pdf](https://github.com/cernopendata/opendata.cern.ch/files/176038/PDDefinition_edited.pdf) + the list of possible HLT paths in these datasets
I think @AnxhelaDani was working on that, so it may be already coming~~
  - *Tibor:* see #925

Trigger information collection

- ~~maybe not show the full paths for the small files, but just the name?~~
  - *Tibor:* ticketised as #961
- ~~the search does not works as I would expect: in
http://opendatadev.cern.ch/search?cc=CMS-Trigger-Information&ln=en&jrec=11 I type HLT_Triple or (star)HLT_Triple(star) in the search field and nothing is found. Does the search term need to be the full name? In this case it is not very practical.~~
  - *Tibor:* The indexes were run.  You can now search for e.g. [hlt l1tech](http://opendatadev.cern.ch/search?p=hlt+l1tech) and other such terms.
- ~~dataset where the trigger appears has got dropped off from the record. E.g. Path HLT_ZeroBias (MinimumBias dataset) in the original file, but the record http://opendatadev.cern.ch/record/2956 does not show MinimumBias dataset at all. This is relevant information, is it there and not just displayed?~~
  - *Tibor:* ticketised as #958

Condition data collection

- ~~the records are empty, I'll check later~~
  - *Tibor:* the records are visible under http://opendatadev.cern.ch/collection/CMS-Condition-Data
- ~~I remember having discussed further text with @AnxhelaDani but I cannot find it know: we need to say that the jobs running on CMS Open Data VM will access the condition data automatically and it is not necessary to download these files.~~
  - *Tibor:* ticketised as #901

Validation Utilities collection
- ~~empty, I will check later~~
  - *Tibor:* This was fixed by #951.
- ~~should contain the lists for the validated runs (http://opendatadev.cern.ch/record/1001 and http://opendatadev.cern.ch/record/1000) , and the validation code from Achim (see https://github.com/cernopendata/opendata.cern.ch/pull/932)~~
  - *Tibor:* All there except for #932 that is already ticketised and still WIP.

CMS Tools collection
- ~~new records missing: dimuon example, new 2011 pattuples and analysis, 2011 vm image~~
  - *Tibor:* ticketised as #926 #959 #859

**Comment by AnxhelaDani** [comment]
> Primary dataset records
"How were these data selected" should have the texts from PDDefinition_edited.pdf + the list of possible HLT paths in these datasets I think @AnxhelaDani was working on that, so it may be already coming 
>  

@katilp I have updated the records with the text (see PR #925 )

> Condition data collection
I remember having discussed further text with @AnxhelaDani but I cannot find it know: 

> 

See #923

**Comment by tiborsimko** [comment]
All items were addressed in linked issues.
