### ISSUE TITLE
Link the new author list to the new records "CMS collaboration"

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#954]
All new data records should link to the new author list, see  #848 
Old 2010 records stay with http://opendatadev.cern.ch/record/450

**Comment by tiborsimko** [comment]
- author collaboration field 110
- introduce new subfield $w with record ID of the author record

**Comment by AnxhelaDani** [comment]
@katilp I think you can close this issue, records are linked with the proper author list.

**Comment by katilp** [comment]
OK, this is not in opendatadev yet, but is it coming?

**Comment by tiborsimko** [comment]
@katilp Yes, the template link change was implemented in 3213e0d169827c62b2807bb1f33d5e578a50ed2f and everything has now been deployed on DEV.
