### ISSUE TITLE
New record for intermediate pattuples 2011

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#959]
Two new records needed for 2011 version of
http://opendatadev.cern.ch/record/202 and http://opendatadev.cern.ch/record/201
Names:
Muons and electrons in PAT candidate format derived from /DoubleMu/Run2011A-12Oct2013-v1/AOD.  primary dataset
Muons and electrons in PAT candidate format derived from /DoubleElectron/Run2011A-12Oct2013-v1/AOD primary dataset
Software release: CMSSW_5_3_32

How were these data selected?

change 2010 RunB Muon -> 2011 RunA DoubleMu
or (the second record) 2010 RunB Electron -> 2011 RunA DoubleElectron

Add (to these new records and also to the 2010 records):
These datasets were produced with the code in (record for code with pattuple2011: http://opendatadev.cern.ch/record/233  or pattuples2010: http://opendatadev.cern.ch/record/200)

How can you use these data?

Change the link to the new 2011 record (OutreachExample2011 : http://opendatadev.cern.ch/record/234)

**Comment by tiborsimko** [comment]
Done.
