### ISSUE TITLE
Update CMS's "Getting Started" to point to Achim's di-muon examples

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#969]
- [x] For 2010 data: explicitly point to the example code
- [x] For 2011 data: point to code saying that it is optimised to run on 2010 data, but can be run on 2011 data by:
    1. Changing the CMSSW version (appropriate VM version)
    2. Changing one line of code
    3. Changing the input files, in the same file as the one in ii.

The example record should also include this caveat that the code can be run on 2011 data but hasn't been optimised for it.

**Comment by katilp** [comment]
- Need also to mention that one has to use the correct VM (together with i.)
- for ii. : PhysicsTools.PythonAnalysis.LumiList -> FWCore.PythonUtilities.LumiList (the 4th line of demoanalyzer_cfg.py)

**Comment by RaoOfPhysics** [comment]
For reference: http://opendatadev.cern.ch/record/560
