### ISSUE TITLE
ispy: jquery error in previewer

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#979]
The event file loads and one can move through the event but there seems to be an error related to jquery in the page (see screenshot) that prevents rendering:
<img width="880" alt="screen shot 2016-03-22 at 5 15 36 pm" src="https://cloud.githubusercontent.com/assets/496503/13960919/292745a4-f052-11e5-8d3e-8184b53ca894.png">

**Comment by tpmccauley** [comment]
It looks like the script that appends #push to #wrap isn't needed since it's already in the html template:
https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/page.html#L60

**Comment by tiborsimko** [comment]
Example where this is not working: 

- http://opendatadev.cern.ch/record/632

**Comment by pamfilos** [comment]
@tpmccauley As I can see, the JS warning for "wrap" comes from the previewer module because the "jQuery" lib isn't loaded yet (will fix..but this doesn't seem to be the issue).

If you check http://opendatadev.cern.ch/record/632/preview?filename=TauPlusX.ig , the event doesn't get rendered. But when you resize the window, the canvas is rendering and then gets non-responsive till you resize again. The problem seems to be somewhere in the ispy js files that get bundled into the "previewer_ispy.js"

**Comment by tiborsimko** [comment]
I see the resizing issue too, and the console says `TypeError: e is null` in `previewer_ispy.js`.

**Comment by tpmccauley** [comment]
I see this as well. Hmm. I have my suspicions. Will look into it. Thanks.

**Comment by tpmccauley** [comment]
I think I get the problem. Since the load file menu does not exist in the previewer a getElementById returns a null. In the stand-alone display this is not a problem. It looks like a fix in invenio-ispy-previewer. Will do so.

**Comment by tpmccauley** [comment]
I also notice that I am missing the info dialogs. Will add.

**Comment by tiborsimko** [comment]
Thanks, I updated DEV and the error is gone indeed :smile:

**Comment by tpmccauley** [comment]
@tiborsimko great. Thanks. One question: the version in the previewer bundles is v21 yet the version indicated in the information dialog is v19? 

https://github.com/inveniosoftware/invenio-previewer-ispy/blob/master/invenio_previewer_ispy/bundles.py#L77

https://github.com/cms-outreach/ispy-webgl/blob/0.9.4-invenio.21/js/config.js#L3

**Comment by tiborsimko** [comment]
Ah, yes, I had not regenerated the `bower.json` file.  Fixed now.
