### ISSUE TITLE
Stand-alone event display: extra i elements of class fa-gear

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#980]
For some reason there appear to be spurious gears (as i elements) on the page
http://opendatadev.cern.ch/visualise/events/CMS:
<img width="487" alt="screen shot 2016-03-22 at 6 16 15 pm" src="https://cloud.githubusercontent.com/assets/496503/13962788/799a378c-f05a-11e5-8cbd-3203f27a25af.png">

**Comment by katilp** [comment]
Flower power? :-)

**Comment by tpmccauley** [comment]
I must admit to not quite understanding how this proliferated from an un-closed tag but I assume some template black magic. The problem doesn't appear anymore for me on my local install but best to check on dev.
