### ISSUE TITLE
CMS: cdaq trigger record description

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#982]
For trigger information records such as `/cdaq/physics/Run2011/5e32/v4.2/HLT/V8`, add to the description the corresponding TOC line with Run number and Software version taken from record 1700.

**Comment by tiborsimko** [comment]
@katilp In addition to yesterday's files, there are a few cdaq physics versions missing:

```console
$ grep -o -P '\(\/cdaq.*?\)' invenio_opendata/testsuite/data/cms/cms-trigger-path-Run2011A.xml  | sort -u
(/cdaq/physics/Run2011/3e33/v5.0/HLT/V1)
(/cdaq/physics/Run2011/5e33/v1.4/HLT/V3)
(/cdaq/physics/Run2011/5e33/v1.4/HLT/V5)
(/cdaq/physics/Run2011/5e33/v2.2/HLT/V2)
(/cdaq/special/0Tesla/HLT/V2)
(/cdaq/special/90m/v1.1/HLT/V12)
(/cdaq/special/HeavyIon/HIHLT_v1p1_V2_Run2011HI_EM/V1)
(/cdaq/special/HeavyIon/HLT_HIon2011_L1TimingTest/V2)
(/cdaq/special/HeavyIon/v1.1/HIHLT/V1)
(/cdaq/special/HighPUFill/Oct2011/HighPUFill_10b_HighRate/V9)
(/cdaq/special/HighPUFill/Oct2011/HighPUFill_10b/V9)
(/cdaq/special/HighPUFill/Oct2011/HighPUFill_1b/V5)
(/cdaq/special/HighPUFill/Oct2011/HighPUFill_1b/V6)
```

**Comment by katilp** [comment]
The missing cdaq/physics (4 files) are now in https://cernbox.cern.ch/index.php/s/Luk6PoPoTpddwff

**Comment by katilp** [comment]
https://cernbox.cern.ch/index.php/s/cVAjgFqgCc1dXTo

**Comment by tiborsimko** [comment]
@katilp All deployed on DEV, please check:

- TOC http://opendatadev.cern.ch/record/1700
- example 1 http://opendatadev.cern.ch/record/3548
- example 2 http://opendatadev.cern.ch/record/3552

**Comment by katilp** [comment]
Ok, perfect!
________________________________________
